### ISSUE TITLE
cups package

### ISSUE THREAD

**Issue by stephentcannon** [skycocker/chromebrew#10]
A cups package would be a nice addition if cups can work on chromeos.  It should.

**Comment by JL2210** [comment]
If you mind, I'd like to add a cups package. It'll take a little work, though.

**Comment by skiman6010** [comment]
CUPS is supported by Chrome OS natively. https://support.google.com/chrome/a/answer/7276100?hl=en

**Comment by JL2210** [comment]
Ok, but Cups is a dependency of HPLIP, used to print to HP printers. And
what about offline printing?

**Comment by uberhacker** [comment]
CUPS is available in G Suite accounts.  Only schools and organizations can set up these accounts. So basically this means CUPS is not available to personal accounts.  The "native" support claim is a bit misleading.
```
admin.google.com is for G Suite accounts only. Regular Gmail accounts cannot be used to sign in to admin.google.com.
```
I think we need a cups package.  It also provides the libraries and headers along with the binaries used for printing operations.
