### ISSUE TITLE
cannot execute g++ compiled output files 

### ISSUE THREAD

**Issue by h-bar** [skycocker/chromebrew#100]
After I compiled my c++ code I cannot use execute it and get the message "bash ./a.out permission denied"

**Comment by Tivoli** [comment]
Where are you running them from @h-bar? There are permissions on the home directories that don't allow you to execute from it. You can update the permissions to allow you to run from your home directory with the following;

```
sudo mount -i -o remount,exec ~
```

Or you can make a directory in /usr/local and then symlink it in your home directory.

**Comment by h-bar** [comment]
@Tivoli  Thanks! It's now working '_>' I thought it was due the lack of something in the chromebrew.
