### ISSUE TITLE
Outdated wiki

### ISSUE THREAD

**Issue by yancouto** [skycocker/chromebrew#1018]
The wiki page about creating packages is outdated, specially the second part. The `create_package.sh` script also seems outdated, it still uses sha1. Should it be deleted?

- So, to create a binary package I should create a normal package and then use `crew build <package>`, and then upload the files like in the second part of the wiki (but with sha256)?
- And when a dependency is added with `depends_on 'package' => :build` this means this dependency will only be necessary if the package is being built from source, and the others will always be needed?

(These answers should probably be added to that wiki page)

**Comment by flyingP0tat0** [comment]
Indeed, this should be easier to understand.
But for the binaries, there should be some more discussion about better tools, the current situation is not very good. Maybe something like a `crew create` command would be useful, but that's something for another issue...

**Comment by jam7** [comment]
@flyingP0tat0 What kind of feature is required for your `crew create` command?  I really would like to have any kind of inputs.  This is related to #140.  Currently, I'm trying to make a kind of automatic binary build environment by using `crew build` command.

@yancouto `crew build` creates both .sha1 and .sha256 files.  Your thought about `=> :build` is correct.  I appreciate if you update wiki pages.  Thanks.

**Comment by flyingP0tat0** [comment]
@jam7 I thought of `crew create` as a command to ask the user some questions:

- type of build (autotools, automake, cmake, ...)
- source (url)
- flags to build
- and maybe other stuff

... to create a (source) package the simple way.

**Comment by jam7** [comment]
I see something like what homebrew has.  That's good idea.

**Comment by yancouto** [comment]
@jam7 I updated the [wiki page](https://github.com/skycocker/chromebrew/wiki/Creating-a-package). Please check if everything is ok.

(Wow, I thought I had to do a pull request or something, but I can just change it.)

**Comment by uberhacker** [comment]
@jam7: Thank you for updating the wiki.  Something you mentioned in that wiki article prompted me to add the issue at #1049.  Let me know what you think.

**Comment by uberhacker** [comment]
@flyingP0tat0: I like your idea also.  Please submit a PR when you get a chance.

**Comment by yancouto** [comment]
I'll close this, then. When we decide on where to store the binaries I can update that step of the wiki page again.
