### ISSUE TITLE
Multiple arguments in a single command?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1026]
```
$ crew install pkg1 pkg2 pkg3 ...
$ crew remove pkg1 pkg2 pkg3 ...
$ crew upgrade pkg1 pkg2 pkg3 ...
```
Possible?

**Comment by flyingP0tat0** [comment]
That would need a lot of rewriting, implementing some sort of framework. So yes, it is possible, with some new code and packages.

**Comment by yancouto** [comment]
Wouldn't it be possible to use one of [these](http://www.awesomecommandlineapps.com/gems.html)? Or would implementing one from scratch be better?

It would be cool to give extra commands with dashes, something like `crew install --from-source --keep pkg1 pkg2`

**Comment by uberhacker** [comment]
@yancouto: I'm getting a blank green screen at http://www.awesomecommandlineapps.com/gems.html.

**Comment by yancouto** [comment]
It was just a page with some gems to make it easier to deal with command line stuff. [This](https://www.sitepoint.com/ruby-command-line-interface-gems/) has less options but seems more relevant to this issue, and more detailed.

**Comment by flyingP0tat0** [comment]
[Thor](https://github.com/erikhuda/thor) seems well documented and under continious development.

**Comment by uberhacker** [comment]
Should we close this issue now that #1079 has been merged?
