### ISSUE TITLE
libmpc.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by h-bar** [skycocker/chromebrew#103]
I failed to past the gcc test when I install git from source. It says "C compiler cannot create executables". And then I tried to compile a simple c hello world program. It also failed and the error massage is /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.1/../../../../x86_64-unknown-linux-gnu/bin/ld:cce: file format not recognized; treating as linker script
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.1/../../../../x86_64-unknown-linux-gnu/bin/ld:cce:1: syntax error
collect2: error: ld returned 1 exit status
I tried to reinstall ld from source but the whole chomebrew stops working after I did this, any command related to chrombrew will lead to segmentation failed.

**Comment by skycocker** [comment]
what is your device?

**Comment by h-bar** [comment]
Toshiba chromebook 2

**Comment by lyxell** [comment]
This is probably due to a missing `--libdir=/usr/local/lib64` for a configure script somewhere. Was git the only thing you tried to install from source?

**Comment by h-bar** [comment]
nope, anything with gcc test (as far as I konw) fails. And using gcc compiler itself gets the error ld returned 1 exit status.

**Comment by lyxell** [comment]
Alright, but when did the problem occur? After installing git from source or after installing a git dependency?

**Comment by h-bar** [comment]
when I doing ./configure for github. Haven't think about dependency yet

**Comment by lyxell** [comment]
Could you provide a link for the tarball you tried to install?

**Comment by h-bar** [comment]
I download it from git-scm.com. here is the download link https://www.kernel.org/pub/software/scm/git/git-2.5.2.tar.gz

**Comment by lyxell** [comment]
Can you ensure you got binutils, gmp, mpc, mpfr and glibc installed?

**Comment by h-bar** [comment]
chromebrew tells me that I've installed all things you list when I use 'crew search'. Is there any other way to check that without using crew?

**Comment by h-bar** [comment]
I checked the config.log file and found that there was an error
configure:2819: gcc    conftest.c  >&5
/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
is this due to the mpc package is missing. But when I do  'crew instll mpc', it prints 'I have no idea how to do instll :('

**Comment by cassial** [comment]
no idea how to install

**Comment by lyxell** [comment]
Remove chromebrew and install it again or reinstall libmpc manually.

**Comment by pbrady** [comment]
I'm getting the same configure error about missing libmpc when trying to `crew install python27`.  It turns out that I can compile a simple helloworld program in C and I also have mpc installed:

```bash
$ ls /usr/local/lib64/libmpc*
/usr/local/lib64/libmpc.a   /usr/local/lib64/libmpc.so.2
/usr/local/lib64/libmpc.la  /usr/local/lib64/libmpc.so.3
/usr/local/lib64/libmpc.so  /usr/local/lib64/libmpc.so.3.0.0

$ ls /usr/local/lib/libmpc*
/usr/local/lib/libmpc.a   /usr/local/lib/libmpc.so.2
/usr/local/lib/libmpc.la  /usr/local/lib/libmpc.so.3
/usr/local/lib/libmpc.so  /usr/local/lib/libmpc.so.3.0.0
```

`gcc` also apears to be linking to the libraries correctly:
```bash
$ ldd /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1
        linux-vdso.so.1 (0x00007ffcde7b7000)
        libmpc.so.2 => /usr/local/lib/libmpc.so.2 (0x00007fd72f1ca000)
        libmpfr.so.4 => /usr/local/lib/libmpfr.so.4 (0x00007fd72ef6e000)
        libgmp.so.10 => /usr/local/lib/libgmp.so.10 (0x00007fd72ecf8000)
        libdl.so.2 => /usr/local/lib/libdl.so.2 (0x00007fd72eaf4000)
        libm.so.6 => /usr/local/lib/libm.so.6 (0x00007fd72e7f1000)
        libc.so.6 => /usr/local/lib/libc.so.6 (0x00007fd72e438000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd72f3e2000)
```

So it seems like maybe this is a path issue.  Does launching the configure/build script from ruby clobber the environment variables (like LD_LIBRARY_PATH) so that gcc can find it's shared libraries?

**Comment by pbrady** [comment]
It's an issue with RPATH.  Following the advice in #49 fixed the my errors.  `patchelf` can be aquired from the archlinux repos https://www.archlinux.org/packages/community/x86_64/patchelf/

**Comment by alpinegizmo** [comment]
I'm stuck on this too. I tried to follow the advice above, and sort of installed patchelf, but I can't figure out how to convince the OS to let me execute it. I also tried to compile a simple hello world program. gcc built an executable, but the OS refuses to execute it ("permission denied", even though it is world executable).

Is there a way to cleanly uninstall chromebrew? I might want to start over.

**Comment by alpinegizmo** [comment]
I'm stuck on this too, but my situation is different. Although I have a 64-bit machine, I don't have a /usr/local/lib64. I have a working gcc and ruby, etc, but they're all 32-bit for some reason. I wanted to install emacs, but can't:

    checking for gcc... gcc -m64
    checking whether the C compiler works... no
    configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77

**Comment by ryanpcmcquen** [comment]
I wonder if this would help at all? https://github.com/skycocker/chromebrew/pull/116

**Comment by skycocker** [comment]
@alpinegizmo, @pbrady @h-bar please reinstall Chromebrew and let us know whether the problem is now solved.

**Comment by RolluS** [comment]
Hello,

I'm using the latest ArnoldTheBat 64 bits build to date: Version 49.0.2600.0 (64-bit)
Plateform 7769.0.2015_12_26_0614 (Developer Build - devbot-x64) developer-build amd64-generic

I had a similar issue with libmpc 64 not installed.

/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory

I've just deleted (see #9 ) and reinstalled Chromebrew as chronos user, and use 'crew install' as chronos user.

**Comment by jam7** [comment]
Now this problem will not happen anymore since new toolchains (#461) have rpath inside. 👍
