### ISSUE TITLE
When to increment the Chromebrew version?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1035]
Since we currently install Chromebrew from the master branch, this might be a good time to talk about tagged releases.  The Chromebrew version is stored in the `crew` command.  In order to maintain some sanity about when to increment the version number, I would like to offer the following proposal:
1. Change the installation line to use the latest tagged release from https://github.com/skycocker/chromebrew/releases instead of the master branch.
2. The version of the latest tagged release should match the version inside the `crew` command.
3. Only tag a new release when either there are changes to the `crew` command itself or a sufficient number of new packages have been added or updated.
4. Maybe we can have a monthly release cycle since project activity has picked up over the last few months?

**Comment by uberhacker** [comment]
This proposal would require a change in the current update process.  The `crew update` command probably should checkout the latest tagged release instead of pulling from master.

**Comment by jam7** [comment]
I'm not sure how using release branch is better than using master branch.  Can you explain more details?  e.g. listing up pros/cons?  Thanks.

**Comment by uberhacker** [comment]
If you look around github.com, all of the big projects tag releases.  This provides a snapshot of the code that is known to be "stable" and "tested".  The master branch is usually reserved for "unstable" or "untested" code.  For example, we know certain packages have dependencies and if a package is merged into master that relies on a pending PR that hasn't been merged yet, then we have a problem.  Also, if a package is updated, it could create problems for other packages that use it.  This is especially true for library packages.  Tagged releases have (or should have) fully tested code that doesn't cause problems. 
 Hopefully, that explains it in more detail.

**Comment by jam7** [comment]
There are many projects using `stable` release because they don't need to merge newly added packages  so often.  If you check homebrew or linuxbrew, both are package manager like chromebrew, they both use master branch since (I guess) they want to allow users to access recently added packages without making new release.

So, I think the making decision whether to use master or release is up to each project.  In order to decide it, we need to discuss it.  It's the reason why I asked to list up pros and cons.  Can you list them up and let us know why using release is better for chromebrew?  Thanks.

**Comment by jam7** [comment]
BTW, if we change it to use tagged release, all newly added packages are unavailable until the next release.  Is it what you want?  For example, if you modify a dependency of a package, it will be available next month belong to your scenario.  It's sounds like too late for me...

**Comment by uberhacker** [comment]
We won't lose the ability to pull from the master branch.  That option won't go away.  What we would gain, however, is the ability to snapshot a "stable" release that won't have any surprises.  It also makes it easier to establish milestones or "goals" for the next release.  All of this means we won't have foolish arguments about whether to increment the Chromebrew version in the crew script.  If we have a monthly release cycle, that may be soon enough for most users.  I think it's disorganized the way we present the releases now.  Either we offer them or we don't.  But we shouldn't have releases that are badly outdated.  It just creates confusion.  Maybe offer the ability to install "stable" or "developer" versions?
