### ISSUE TITLE
cairo install fail

### ISSUE THREAD

**Issue by yancouto** [skycocker/chromebrew#1037]
Cairo installation fails with the message

`cairo-xlib-surface.c:71:33: fatal error: X11/extensions/XShm.h: No such file or directory
 #include <X11/extensions/XShm.h>`

I'm not sure which dependency should be added.

**Comment by uberhacker** [comment]
I noticed this also.  I guess it's X11 growing pains.  Several packages depend on this one so we shoulld fix it sooner rather than later.

**Comment by flyingP0tat0** [comment]
I don't get that error without `libx11` installed. What platform were you guys running this install on?

**Comment by uberhacker** [comment]
@flyingP0tat0: I was using an HP Chromebook x86_64 system.

**Comment by uberhacker** [comment]
@jam7: Here is a prime example of why we should have releases.

**Comment by flyingP0tat0** [comment]
My fault, I thought it would occur without `libx11`, but when testing with it, I also get this error.

**Comment by jam7** [comment]
Ah... sry I didn't mention it but #1023 would fix this problem.

You can configure cairo with `--disable-xlib` option atm.  In near future, once x11 is available, we can remove that option I think.

**Comment by jam7** [comment]
@flyingP0tat0 similar problem exists on both libsdl and libsdl2.  Please fix them if you can.  Thanks.  In addition, if you can submit PR to add `disable-xlib` like above, please do it.  I'll merge that soon.
