### ISSUE TITLE
Compile errors for many packages

### ISSUE THREAD

**Issue by yancouto** [skycocker/chromebrew#1051]
I was trying to build all packages, but some did not work. Here are their errors:

## LIBCAP

gcc -O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Dlinux -Wall -Wwrite-strings -Wpointer-arith -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wshadow -g  -fPIC -I/usr/local/tmp/crew/libcap-2.25.tar.xz.dir/libcap-2.25/libcap/../libcap/include/uapi -I/usr/local/tmp/crew/libcap-2.25.tar.xz.dir/libcap-2.25/libcap/../libcap/include -c cap_file.c -o cap_file.o
make[1]: *** [Makefile:63: cap_text.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/tmp/crew/libcap-2.25.tar.xz.dir/libcap-2.25/libcap'
make: *** [Makefile:12: all] Error 2
libcap failed to build: `make -j2` exited with 2

## CLAMAV

configure: error: The installed zlib version may contain a security bug. Please upgrade to 1.2.2 or later: http://www.zlib.net. You can omit this check with --disable-zlib-vcheck but DO NOT REPORT any stability issues then!
clamav failed to build: `./configure` exited with 1

## CMATRIX

gcc -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -Wall -Wno-comment -c cmatrix.c
cmatrix.c:37:20: fatal error: curses.h: No such file or directory
 #include <curses.h>
                    ^
compilation terminated.
make: *** [Makefile:186: cmatrix.o] Error 1
cmatrix failed to build: `make -j2` exited with 2

## CURL

TESTDONE: 79 tests out of 912 reported OK: 8%
TESTFAIL: These test cases failed: 1 (... many others)
TESTDONE: 1092 tests were considered during 2917 seconds.
make[1]: *** [Makefile:778: quiet-test] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/curl-7.54.1.tar.bz2.dir/curl-7.54.1/tests'
make: *** [Makefile:1350: test] Error 2
curl failed to build: `make test` exited with 2

## DISKSCAN

make: *** No rule to make target 'check'.  Stop.
diskscan failed to build: `make check` exited with 2

## EXPECT

configure: configuring expect 5.45
checking for Tcl configuration... configure: error: Can't find Tcl configuration definitions
expect failed to build: `./configure --prefix=/usr/local` exited with 1

## FETCH

Building from source, this may take a while...
fetch failed to build: `go get github.com/urfave/cli` exited with 127

## FINCH

configure: error:
Neither GnuTLS or NSS SSL development headers found.
Use --disable-nss --disable-gnutls if you do not need SSL support.
Novell Groupwise and Google Talk will not work without GnuTLS or NSS. OpenSSL is NOT usable!

## GITHUB_RELEASE

fatal: Not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
go list -f '{{join .Deps "\n"}}' | xargs go list -e -f '{{if not .Standard}}{{.ImportPath}}{{end}}' | xargs go get -u
/bin/sh: go: not found
xargs: go: No such file or directory
xargs: go: No such file or directory
make: *** [Makefile:70: dep] Error 127
github_release failed to build: `make -j2` exited with 2

## GOX

Preconfiguring package...
toolchain.go:6:2: cannot find package "github.com/mitchellh/iochan" in any of:
        /usr/local/lib/go/src/github.com/mitchellh/iochan (from $GOROOT)
        /home/chronos/user/go/src/github.com/mitchellh/iochan (from $GOPATH)
gox failed to install: `go build -o /usr/local/tmp/crew/dest/usr/local/bin/gox` exited with 1

## IMAGEMAGICK

Downloading source...
--2017-08-11 21:18:37--  https://www.imagemagick.org/download/releases/ImageMagick-7.0.6-4.tar.xz
Resolving www.imagemagick.org... 198.72.81.86
Connecting to www.imagemagick.org|198.72.81.86|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-08-11 21:18:39 ERROR 404: Not Found.

Checksum mismatch. :/ Try again.

## HUB

script/build: line 44: go: command not found
You need to install Go 1.8 or higher to build hub
hub failed to build: `script/build -o /usr/local/bin/hub` exited with 1

## HEROKU

yarn install v0.27.0-20170629.1443
[1/5] Validating package.json...
error heroku-cli@6.13.9: The engine "node" is incompatible with this module. Expected version ">=8.1.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
heroku failed to build: `yarn install` exited with 1

## KUBECTL

which: no go in (/usr/local/bin:/usr/bin:/bin:/opt/bin)

Can't find 'go' in PATH, please fix and retry.
See http://golang.org/doc/install for installation instructions.

!!! [0811 21:46:51] Call tree:
!!! [0811 21:46:51]  1: /usr/local/tmp/crew/v1.7.0.tar.gz.dir/kubernetes-1.7.0/hack/lib/golang.sh:619 kube::golang::setup_env(...)
!!! [0811 21:46:51]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0811 21:46:51] Call tree:
!!! [0811 21:46:51]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile.generated_files:302: _output/bin/deepcopy-gen] Error 1
make: *** [Makefile:459: generated_files] Error 2
kubectl failed to build: `make -j2 -j1 generated_files` exited with 2

## LIBSLZ

Downloading source...
--2017-08-11 22:26:39--  http://git.1wt.eu/web?p=libslz.git;a=snapshot;h=afa04ae1f976957cf36287cc5370998d0559bc63;sf=tbz2
Resolving git.1wt.eu... 51.15.8.218
Connecting to git.1wt.eu|51.15.8.218|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 229577 (224K) [application/x-bzip2]
Saving to: 'web'

web                                   100%[======================================================================>] 224.20K  21.9KB/s    in 9.4s

2017-08-11 22:26:53 (23.8 KB/s) - 'web' saved [229577/229577]

Checksum mismatch. :/ Try again.

## MESTASPLOIT

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...

An error occurred while installing pg (0.20.0), and Bundler cannot
continue.
Make sure that `gem install pg -v '0.20.0'` succeeds before bundling.

In Gemfile:
  metasploit-framework was resolved to 4.14.28, which depends on
    metasploit-credential was resolved to 2.0.10, which depends on
      metasploit_data_models was resolved to 2.0.14, which depends on
        pg
metasploit failed to build: `bundle install` exited with 5

## MONGODB

./build.sh: 10: Bad substitution
Building bsondump...
./build.sh: 27: go: not found
***YOU NEED TO SET UP GO ENVIRONMENT IN ORDER TO COMPILE MONGO-TOOLS***
cp: cannot stat âmongo-tools/bin/*â: No such file or directory
mongodb failed to build: `cp mongo-tools/bin/* src/mongo-tools/` exited with 1

## CBASE

Downloading source...
--2017-08-13 12:05:32--  http://www.hyperrealm.com/cbase/cbase-1.3.7.tar.gz
Resolving www.hyperrealm.com... 50.87.249.191
Connecting to www.hyperrealm.com|50.87.249.191|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-08-13 12:05:33 ERROR 500: Internal Server Error.

Checksum mismatch. :/ Try again.

------------------------------

Here is a checklist to manage what's already been solved:

- [x] libcap
- [x] clamav
- [x] cmatrix
- [x] curl
- [x] diskscan
- [x] fetch
- [x] finch
- [x] github_release
- [x] gox
- [x] imagemagick
- [x] hub
- [x] heroku
- [x] kubectl
- [x] libslz
- [ ] metasploit
- [x] mongodb
- [x] cbase
- [x] misctools
- [x] imagemagick6

**Comment by jam7** [comment]
Many of them are fixed in pending PR of mine except clamav, imagemagick, libslz and metasploit.

**Comment by yancouto** [comment]
Nope, cbase doesn't work either. Must have missed that error. Will edit it in.

**Comment by yancouto** [comment]
Oops. Have you fixed diskscan? If so, I can revert that part of the PR.

**Comment by jam7** [comment]
No problem.  Go ahead.  I can merge your PR.  :)

**Comment by jam7** [comment]
Please add misctools and imagemagick6.

**Comment by jam7** [comment]
@yancouto clamav will be fixed by #1064.  Regarding to curl, can you see what is different in your environment from https://github.com/jam7/chromebrew/releases/download/bin-x86_64/curl-7.54.1-chromeos-x86_64.log?

**Comment by yancouto** [comment]
I'm not sure what was wrong. Maybe some package conflicts? It is working now. I'll mark it done.

**Comment by jam7** [comment]
If you upgrade go, several errors related to go will be solved like gox, heroku, kubectl, mongodb.

**Comment by uberhacker** [comment]
Looks like openssl cannot be updated:
```
$ crew upgrade openssl
(i) openssl: OpenSSL is an open source project that provides a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols.
https://www.openssl.org/
version 1.0.2l-1
Updating openssl...
The following packages also need to be installed: 
perl_locale_messages perl_text_unidecode perl_unicode_eastasianwidth lzip ed bc 
Do you agree? [Y/n]  
Proceeding...
perl_locale_messages: Perl Locale::Messages - Gettext Like Message Retrieval.
https://metacpan.org/pod/Locale::Messages
version 1.27
No precompiled binary available for your platform, downloading source...
--2017-08-18 23:12:29--  https://cpan.metacpan.org/authors/id/G/GU/GUIDO/libintl-perl-1.27.tar.gz
Resolving cpan.metacpan.org... 151.101.48.249
Connecting to cpan.metacpan.org|151.101.48.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 468340 (457K) [application/x-gzip]
Saving to: 'libintl-perl-1.27.tar.gz'

libintl-perl-1.27.tar.gz              100%[======================================================================>] 457.36K  1.95MB/s    in 0.2s    

2017-08-18 23:12:29 (1.95 MB/s) - 'libintl-perl-1.27.tar.gz' saved [468340/468340]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Preconfiguring package...
perl_locale_messages failed to install: `cpanm -l build --self-contained .` exited with 127
```

**Comment by jam7** [comment]
Upgrade your perl first.  Check #1087 for details.

**Comment by uberhacker** [comment]
OK, thanks.  I cannot upgrade cairo either:
```
/bin/sed: can't read /usr/local/lib/libexpat.la: No such file or directory
libtool:   error: '/usr/local/lib/libexpat.la' is not a valid libtool archive
make[3]: *** [Makefile:2099: libcairo.la] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/cairo-1.14.10.tar.xz.dir/cairo-1.14.10/src'
make[2]: *** [Makefile:1947: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/cairo-1.14.10.tar.xz.dir/cairo-1.14.10/src'
make[1]: *** [Makefile:905: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/cairo-1.14.10.tar.xz.dir/cairo-1.14.10'
make: *** [Makefile:756: all] Error 2
cairo failed to install: `make -j2` exited with 2
```

**Comment by jam7** [comment]
It says no `/usr/local/lib/libexpat.la`.  So where do you have that?  You can check it by `crew whatprovides libexpat.la`.  I think it is a command you provides...

**Comment by jam7** [comment]
Anyway, I think what you need first is `crew upgrade`.  Did you try that?

**Comment by jam7** [comment]
And one more thing, I heard Chrome OS 60 is available on stable channel.  So, if you already update to 60, you may have difficulties to use chromebrew for a while like we discussed in #689.

**Comment by uberhacker** [comment]
I did not upgrade yet.
```
Version 59.0.3071.134 (Official Build) (64-bit)
```

**Comment by fp555** [comment]
`texinfo` still has some problems (this is after #1087 fix):
```
texinfo: Texinfo is the official documentation format of the GNU project.
https://www.gnu.org/software/texinfo/
version 6.4-1
No precompiled binary available for your platform, downloading source...
--2017-08-19 10:45:24--  http://ftpmirror.gnu.org/texinfo/texinfo-6.4.tar.xz
Resolving ftpmirror.gnu.org... 208.118.235.200
Connecting to ftpmirror.gnu.org|208.118.235.200|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://mirror2.mirror.garr.it/mirrors/gnuftp/gnu/texinfo/texinfo-6.4.tar.xz [following]
--2017-08-19 10:45:25--  http://mirror2.mirror.garr.it/mirrors/gnuftp/gnu/texinfo/texinfo-6.4.tar.xz
Resolving mirror2.mirror.garr.it... 90.147.164.69, 90.147.160.69, 2001:760:ffff:b6:4:100:0:69
Connecting to mirror2.mirror.garr.it|90.147.164.69|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-08-19 10:45:26 ERROR 404: Not Found.

Checksum mismatch. :/ Try again.
```
This makes `openssl` upgrade fail.

**Comment by jam7** [comment]
@fp555 `404 not found` is a problem of ftp mirror server near to you.  We cannot help you.  You can wait for a while until its up or you can download source file from different mirror server and put it on `/usr/local/tmp/crew`

**Comment by jam7** [comment]
BTW, I think this is not an issue to claim individual problems...

**Comment by yancouto** [comment]
Installing finch from source still fails, now with
`/usr/local/lib/gcc/x86_64-cros-linux-gnu/4.9.4/../../../../x86_64-cros-linux-gnu/bin/ld: cannot find -lpython2.7`
Gox installing works, but running `gox` yields
`error reading Go version: exit status 1
Stderr: fork/exec /tmp/go-build788354891/command-line-arguments/_obj/exe/version: permission denied`
I'm not sure how gox is used, but I guess this shouldn't happens.
I'll check the other packages later.

**Comment by yancouto** [comment]
I still get the same errors for the other packages. This issue should be reopened.

**Comment by jam7** [comment]
@yancouto, I think you can reopen this whenever you think it is needed.  Please let me know if you don't see 'reopen and comment' button.

BTW, `finch` may requires `depends_on 'python27'`.  I didn't try it without python2.7.  Regarding to gox, you need to modify your environment variable like below.  Installing `go` shows how to do it.
```
$ export TMPDIR=/usr/local/tmp
$ gox...
```

**Comment by yancouto** [comment]
Okay, I've marked gox as done. I don't see the reopen button.

**Comment by jam7** [comment]
Ok.  I reopen this.

**Comment by yancouto** [comment]
finch and metasploit still do not work. Adding `depends_on 'python27'` to finch does not help. I don't know how to fix them.

**Comment by uberhacker** [comment]
@yancouto: Do they still compile correctly using `crew install finch -s` and `crew install metasploit -s`?

**Comment by yancouto** [comment]
No. finch actually installs correctly from the binaries, but not from source. metasploit does not have binaries.

**Comment by uberhacker** [comment]
I installed finch from source fine on my system.  What are your system specs?

**Comment by yancouto** [comment]
Well, I reinstalled python27 and it worked. Crossed it off the list. 18 down, 1 to go.

**Comment by yancouto** [comment]
metasploit still doesn't work. should it be removed?
