### ISSUE TITLE
Who is in favor of a complete overhaul of the node package?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1056]
Currently, we have 4 different ways to install node.  Obviously, this will create some confusion.
1. node
2. node_current
3. nvm
4. nodebrew

I would like to simplify the process so there is only one method of installation where you can choose whatever version you like.  I think `1.` and `2.` are not the preferred methods because they take an eternity to compile from source.  Also, there is no way to control the version once it's installed.  `3.` is a better option since you can easily install the binary of any version you want quickly and painlessly.  It also installs npm which is a nice added benefit.  The con of this method is it requires your shell resource file to be modified.  `4.` is the most recent addition and it also lets you easily install the binary of any version you want with the added option of compiling from source.  The downside is it creates a local `~/.nodebrew` directory and also requires the `PATH` variable to be modified.  The ideal solution would be a method that installs like `nvm` or `nodebrew` without modifying the shell resource file or the `PATH` variable.  I would like to propose we keep either `nvm` or `nodebrew` (or another package since there are several available in the wild) and remove the `node` and `node_current` packages.  It might even make sense to rework the `node` package so it installs via `nvm` or `nodebrew` or ...

**Comment by jam7** [comment]
FYI, @thedamian said node v6 is the latest LTS.  I didn't know that, but it is truth.  So, it may be better to leave `node` as is as v6.

Still we can make `node` and `node8` wrapper using `nvm` or `nodebrew`, though.

**Comment by uberhacker** [comment]
That is true but several packages including `heroku` and `yarn` require v8 to install.  I don't know about you, but I'm not going to wait around every time I have to recompile node when doing my testing.  I'm just going to install the binary via nvm or nodebrew.  IMHO, I think this is how we should install node as a dependency of any package.

**Comment by jam7** [comment]
I'm not talking anything about re-compile stuff.  I said we may need to leave `node` to install node version 6.  I didn't mention how to do that.  It's possible to use node version manager or source compile.  So we can perform something like below if we use nodebrew.

node.rb:
```
system "nodebrew install-binary v6"
system "nodebrew use v6"
```
node_current.rb:
```
system "nodebrew install-binary latest"
system "nodebrew use latest"
```

**Comment by cstrouse** [comment]
+1 for the nodebrew solution
