### ISSUE TITLE
Can't install bc

### ISSUE THREAD

**Issue by R-Jones** [skycocker/chromebrew#1060]
Hey all,

Ran into the following while trying to install bc(On an asus chromebook 201)...any ideas how I can fix this?

bc: bc is an arbitrary precision numeric processing language.
http://www.gnu.org/software/bc/
version 1.07.1
No precompiled binary available for your platform, downloading source...
--2017-08-13 22:56:30--  https://ftp.gnu.org/gnu/bc/bc-1.07.1.tar.gz
Resolving ftp.gnu.org... 208.118.235.20, 2001:4830:134:3::b
Connecting to ftp.gnu.org|208.118.235.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 419850 (410K) [application/x-gzip]
Saving to: 'bc-1.07.1.tar.gz'

bc-1.07.1.tar.gz                      100%[========================================================================>] 410.01K   425KB/s    in 1.0s    

2017-08-13 22:56:32 (425 KB/s) - 'bc-1.07.1.tar.gz' saved [419850/419850]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for bison... bison -y
checking for ranlib... ranlib
checking whether make sets $(MAKE)... (cached) yes
checking for stdarg.h... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for errno.h... yes
checking for limits.h... yes
checking for unistd.h... (cached) yes
checking for lib.h... no
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for ptrdiff_t... yes
checking for vprintf... yes
checking for _doprnt... no
checking for isgraph... yes
checking for setvbuf... yes
checking for fstat... yes
checking for strtol... yes
checking for tparm in -lncurses... yes
checking for readline in -lreadline... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
Using the readline library.
Adding GCC specific compile flags.
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bc/Makefile
config.status: creating dc/Makefile
config.status: creating lib/Makefile
config.status: creating doc/Makefile
config.status: creating doc/texi-ver.incl
config.status: creating config.h
config.status: executing depfiles commands
make  all-recursive
make[1]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1'
Making all in lib
make[2]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/lib'
gcc -DHAVE_CONFIG_H  -I. -I..  -I. -I.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT getopt.o -MD -MP -MF .deps/getopt.Tpo -c -o getopt.o getopt.c
gcc -DHAVE_CONFIG_H  -I. -I..  -I. -I.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT getopt1.o -MD -MP -MF .deps/getopt1.Tpo -c -o getopt1.o getopt1.c
gcc -DHAVE_CONFIG_H  -I. -I..  -I. -I.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT vfprintf.o -MD -MP -MF .deps/vfprintf.Tpo -c -o vfprintf.o vfprintf.c
gcc -DHAVE_CONFIG_H  -I. -I..  -I. -I.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT number.o -MD -MP -MF .deps/number.Tpo -c -o number.o number.c
mv -f .deps/vfprintf.Tpo .deps/vfprintf.Po
mv -f .deps/getopt.Tpo .deps/getopt.Po
mv -f .deps/getopt1.Tpo .deps/getopt1.Po
mv -f .deps/number.Tpo .deps/number.Po
rm -f libbc.a
ar cru libbc.a getopt.o getopt1.o vfprintf.o number.o 
ranlib libbc.a
make[2]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/lib'
Making all in bc
make[2]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/bc'
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT bc.o -MD -MP -MF .deps/bc.Tpo -c -o bc.o bc.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT scan.o -MD -MP -MF .deps/scan.Tpo -c -o scan.o scan.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT execute.o -MD -MP -MF .deps/execute.Tpo -c -o execute.o execute.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT load.o -MD -MP -MF .deps/load.Tpo -c -o load.o load.c
mv -f .deps/load.Tpo .deps/load.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT storage.o -MD -MP -MF .deps/storage.Tpo -c -o storage.o storage.c
mv -f .deps/scan.Tpo .deps/scan.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
mv -f .deps/bc.Tpo .deps/bc.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT warranty.o -MD -MP -MF .deps/warranty.Tpo -c -o warranty.o warranty.c
mv -f .deps/execute.Tpo .deps/execute.Po
mv -f .deps/warranty.Tpo .deps/warranty.Po
mv -f .deps/storage.Tpo .deps/storage.Po
mv -f .deps/util.Tpo .deps/util.Po
echo '{0}' > libmath.h
make global.o
make[3]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/bc'
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT global.o -MD -MP -MF .deps/global.Tpo -c -o global.o global.c
mv -f .deps/global.Tpo .deps/global.Po
make[3]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/bc'
gcc -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char   -o libmath.h -o fbc main.o bc.o scan.o execute.o load.o storage.o util.o warranty.o global.o ../lib/libbc.a -lfl -lreadline -lncurses 
./fbc -c ./libmath.b </dev/null >libmath.h
./fix-libmath_h
2655
2793
rm -f ./fbc ./global.o
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT global.o -MD -MP -MF .deps/global.Tpo -c -o global.o global.c
mv -f .deps/global.Tpo .deps/global.Po
gcc -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char   -o bc main.o bc.o scan.o execute.o load.o storage.o util.o global.o warranty.o ../lib/libbc.a -lfl -lreadline -lncurses 
make[2]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/bc'
Making all in dc
make[2]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/dc'
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT dc.o -MD -MP -MF .deps/dc.Tpo -c -o dc.o dc.c
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT misc.o -MD -MP -MF .deps/misc.Tpo -c -o misc.o misc.c
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT eval.o -MD -MP -MF .deps/eval.Tpo -c -o eval.o eval.c
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT stack.o -MD -MP -MF .deps/stack.Tpo -c -o stack.o stack.c
mv -f .deps/misc.Tpo .deps/misc.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT array.o -MD -MP -MF .deps/array.Tpo -c -o array.o array.c
mv -f .deps/dc.Tpo .deps/dc.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT numeric.o -MD -MP -MF .deps/numeric.Tpo -c -o numeric.o numeric.c
mv -f .deps/array.Tpo .deps/array.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I./.. -I./../h  -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char -MT string.o -MD -MP -MF .deps/string.Tpo -c -o string.o string.c
mv -f .deps/stack.Tpo .deps/stack.Po
mv -f .deps/string.Tpo .deps/string.Po
mv -f .deps/numeric.Tpo .deps/numeric.Po
mv -f .deps/eval.Tpo .deps/eval.Po
gcc -g -O2 -Wall -funsigned-char -g -O2 -Wall -funsigned-char   -o dc dc.o misc.o eval.o stack.o array.o numeric.o string.o ../lib/libbc.a 
make[2]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/dc'
Making all in doc
make[2]: Entering directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/doc'
restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (makeinfo --no-split --version) >/dev/null 2>&1; then \
  for f in bc.info bc.info-[0-9] bc.info-[0-9][0-9] bc.i[0-9] bc.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if makeinfo --no-split   -I . \
 -o bc.info bc.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./bc.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (makeinfo --no-split --version) >/dev/null 2>&1; then \
  for f in dc.info dc.info-[0-9] dc.info-[0-9][0-9] dc.i[0-9] dc.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if makeinfo --no-split   -I . \
 -o dc.info dc.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./dc.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
/bin/bash: line 9: makeinfo: command not found
make[2]: *** [Makefile:320: bc.info] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/bash: line 9: makeinfo: command not found
make[2]: *** [Makefile:320: dc.info] Error 127
make[2]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1/doc'
make[1]: *** [Makefile:357: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/bc-1.07.1.tar.gz.dir/bc-1.07.1'
make: *** [Makefile:297: all] Error 2
bc failed to install: `make -j4` exited with 2

**Comment by jam7** [comment]
You need to install `texinfo` by hand.  It contains missing `makeinfo`.  Pending PR #1023 fixed this problem.

**Comment by R-Jones** [comment]
That did the trick. Thank you!
