### ISSUE TITLE
can't compile mesa on armv7l

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#1065]
It shows following errors.
```
$ crew install mesa
...
checking for LIBDRM... yes
checking for GLPROTO... yes
checking for DRI2PROTO... yes
checking for XF86VIDMODE... no
checking for DRIGL... yes
configure: WARNING: --with-egl-platforms is deprecated. Use --with-platforms instead.
checking for WAYLAND_SCANNER... yes
checking for XCB_DRI2... yes
checking for WAYLAND... yes
checking for EXPAT... yes
checking for INTEL... no
configure: error: Package requirements (libdrm >= 2.4.75 libdrm_intel >= 2.4.75) were not met:

No package 'libdrm_intel' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables INTEL_CFLAGS
and INTEL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
It's arm, so no drm_intel.  Is three any any way to avoid this?  Thanks.

**Comment by flyingP0tat0** [comment]
@jam7 That's unfortunate. There is a libdrm repo [here](https://github.com/intel/external-libdrm). I don't know if this solves the problem (I only have x86_64), but maybe you can try it out?

**Comment by jam7** [comment]
@flyingP0tat0 Thank you for reply.  If you don't know it, someone having armv7l need to work.  :)
I'll try if I have a chance.  Thank.

**Comment by beliefless-dogmasless** [comment]
- Same problem here (with armv7l) :

checking for INTEL... no
configure: error: Package requirements (libdrm >= 2.4.75 libdrm_intel >= 2.4.75) were not met:

No package 'libdrm_intel' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables INTEL_CFLAGS
and INTEL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
mesa failed to install: `./configure --enable-gles2 --with-egl-platforms=x11,wayland,drm --enable-gbm --enable-shared-glapi --with-gallium-drivers=swrast --disable-dri3` exited with 1

**Comment by flyingP0tat0** [comment]
Could you please try out installing the libdrm from Intel I linked before? I don't have access to an armv7l machine...

**Comment by beliefless-dogmasless** [comment]
@flyingP0tat0
Yes I saw the message above, 

I tried, but the installation (external-libdrm), it asks for other dependencies :
xorg-macros   
[error: must install xorg-macros 1.12 or later before running autoconf/autogen]

I tried to install (xorg-macros), Without Success.

**Comment by flyingP0tat0** [comment]
@beliefless-dogmasless Hoiw did you install `xorg_macros`?

**Comment by beliefless-dogmasless** [comment]
@flyingP0tat0
I used the git (https://anongit.freedesktop.org/git/xorg/util/macros.git/), tried a 'bunch' of commands (to compile) but without success.

**Comment by flyingP0tat0** [comment]
@beliefless-dogmasless I think the correct one is https://www.x.org/pub/individual/util/util-macros-1.19.1.tar.bz2.
Should be installed via a simple `make install`.

**Comment by beliefless-dogmasless** [comment]
It seems that now with
(https://www.x.org/pub/individual/util/util-macros1.19.1.tar.bz2),
the compilation goes well.

But (https://github.com/intel/external-libdrm) does not
compile for Tegra, and apparently not for Intel :

[libdrm 2.4.85 will be compiled with:
libkms yes
Intel API no
vmwgfx API yes
Radeon API yes
AMDGPU API yes
New API yes
OMAP API no
EXYNOS API no
Freedreno API yes (kgsl: no)
Tegra API no.
VC4 API yes
Etnaviv API no]

**Comment by bluequilla** [comment]
Any progress here? Cos I have been following your steps and am now at the same road block...

**Comment by bluequilla** [comment]
I managed to do it by adding "--enable-intel" to the "configure" in question (the autoreconf has to be called manually beforehand to create "configure", otherwise it failed with version conflict on my side).
But no futher, my java swing application hangs then at another thingy...

**Comment by flyingP0tat0** [comment]
@bluequilla Do you talk about libdrm-intel working with `--enable-intel`?

**Comment by HiyaTsai** [comment]
So , Any solution in this problem ? Thanks.
(Ubuntu 14.04 , 32bt , armv7)

**Error**
--------------------------------------------------------
checking for INTEL... no configure: error: Package requirements (libdrm_intel >= 2.4.61) were not met: No package 'libdrm_intel' found


**My build comand:**
----------------------------------------------------------------------------
MESA:
        tar xvf mesa-12.0.6.tgz
        cd mesa; \
        PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) ./configure --prefix=$(INSTALL_PATH) --with-dri-searchpath=$(DRIVER_PATH) --enable-selinux \
                --enable-dri \
                #--with-dri-drivers=radeon,r200 \
                #--with-gallium-drivers=r300,r600,radeonsi,swrast \
                --enable-egl \
                --enable-gles1 \
                --enable-gles2 \
                --enable-vdpau \
                --enable-va \
                --enable-shared-glapi \
                --enable-gbm \
                --disable-xvmc \
                --with-egl-platforms=x11,drm,wayland \
                --enable-texture-float \
                --enable-xa \
                --enable-osmesa \
                --enable-omx \
                --enable-glx \
                --enable-glx-tls; \
        make -j4; \
        make install;
----------------------------------------------------------------------------

**Comment by bluequilla** [comment]
@flyingP0tat0 No, at the libdrm mentioned above. It does not configure automatically for "intel", but it runs smoothly with "--enable-intel" and mesa compiles as smoothly afterwards!
Unfortunately, it does not solve the problem.

**Comment by flyingP0tat0** [comment]
@bluequilla I am still not sure which software you are talking about.

chromebrew's mesa package,
chromebrews's libdrm package,
or [libdrm](https://github.com/intel/external-libdrm) from intel?

Thanks :)

**Comment by HiyaTsai** [comment]
@flyingP0tat0 Sorry, could you give me the answer to this question?

**Comment by lovedheart** [comment]
@HiyaTsai 
try 
./configure --enable-shared-glapi --with-gallium-drivers=nouveau --with-dri-drivers=nouveau --enable-egl --with-egl-platforms=x11,drm,wayland

**Comment by lovedheart** [comment]
it can pass libdrm_intel for me. (Tegra k1)

**Comment by bluequilla** [comment]
@flyingP0tat0  Sorry, yes: the external drm on github by intel.

**Comment by lovedheart** [comment]
I put a pull request on mesa.rb, which is modified to compile mesa on armv7l.

**Comment by beliefless-dogmasless** [comment]
I do not know what has changed since the last time(which I tried to install) but now it works (mesa is installed). Maybe a new version, or other software that I installed in the meantime, or guix that I'm trying to install. Short.

**Comment by uberhacker** [comment]
@beliefless-dogmasless: You can thank @lovedheart who updated mesa recently.

**Comment by beliefless-dogmasless** [comment]
@lovedheart Yeah, thanks, that's what I thought, an 'update', thanks anyway.

**Comment by uberhacker** [comment]
Can we close this issue?

**Comment by beliefless-dogmasless** [comment]
For me yes. Don't know 'about the others'.
