### ISSUE TITLE
Remove handle in packge script

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#1075]
I am currently facing some problems when I try to install packages (no yet released ones), which don't work very well with other packges due to various bugs.
I think something lke `remove 'packge'` would be helpful for creating packges. This should reinstall the packge after the requesting one has installed. I gues due to the many tricks with our platform something like this is just a need to get more and more packges.

**Comment by yancouto** [comment]
I've done something like this locally. It actually just renames all files in the package, so "reinstalling" is just renaming back, very fast. I called this "hiding" and "showing" a package.

I wrote a function to hide all but the dependencies of the package, to look for dependency mistakes.

**Comment by jam7** [comment]
I had similar experience.  I changed the package file to ignore those problematic packages by `--disable-xxx` or `--without-xxx` options.

Removing other packages in the middle of installation may cause problem in user environment, so I don't like that way.  Can you find other ways like above options?

**Comment by flyingP0tat0** [comment]
I will try.
