### ISSUE TITLE
Using bintray for pre-compiled binary distribution

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#1082]
Hi all, currently I'm preparing for binary distribution from https://bintray.com/chromebrew.  The reason I choose bintray over github is their speed.  It is still under the construction, so please wait little more bit.

I also want to invite @skycocker and @lyxell to there.  Hey guys, please create a free OSS account on bintary from https://bintray.com/signup/oss if it is possible.  Thanks.

Once it is available, I think we collaborator perform something like below.

 1. create pre-compiled binaries
 2. put them to bintray as much as possible
 3. if we receives PR having binary distributed files
 4. check them somehow... (I have no idea here)
 5. put them to bintray also.

In future, I'd like to deploy pre-compiled binary automatically somehow.

**Comment by uberhacker** [comment]
This would be pretty awesome.  How would we link it to Github releases?  We'll obviously have different versions as packages are updated over time and we'll want those tracked somehow, right?

**Comment by jam7** [comment]
I will update each package binary_url.  So, basically we don't need link there from release pages.

Whenever we update package file and modify version number, we need to remove binary_url from the package file.  Otherwise, `crew` install old binary files instead of compiling new programs from source code.  Then, me or other collaborator pre-compile new package and link them again.  I would like to make some CI process to deploy pre-compiled binaries in future somehow.

**Comment by jam7** [comment]
I upload pre-compiled files and prepared package files.  It is still under construction, but you can try them by performing following commands.  There are two problems need to discuss.  I write them at the bottom of this msg.
```
$ cd /usr/local/lib/crew
$ git checkout -b jam7-bintray-binaries master
$ git pull https://github.com/jam7/chromebrew.git bintray-binaries
```
In order to revert it, please performs following commands.
```
$ cd /usr/local/lib/crew
$ git co master
$ git branch -D jam7-bintray-binaries
```

There are two minor problems.

1. It is binary distribution.  Therefore none of `build` or `install` function is called.  Some packages show messages in `install` function.  Other packages modify files directly not through CREW_DEST_DIR.  All of them doesn't work.
2. `Crew` doesn't recognize version number from binary_url.  So, if user update source code and modify version number but forget to remove binary_url, `crew` installs old binaries as new version.  So, each developers need to remove binary_url whenever they modify package files.

How do you think?  Are those are OK, so send PR?  Or should we solve them beforehand?  Thanks.

**Comment by yancouto** [comment]
Great changes! Everything is so much faster now :D 
So, for now, what should people do when creating packages? Just add the source, remove the previous binary and wait for you or another collaborator to add the binaries? (This should probably be updated on the wiki again)

**Comment by uberhacker** [comment]
@yancouto: That is a great question.  Like PRs for source commits that get reviewed before they're merged in this repo, we should also have a repo set up for bintray commits as well.  Not that we don't trust the validity of @jam7's compiled binaries but so we can have some accountability and testing before acceptance.  Ideally, that repo would have the same PR workflow and review process as Github.

**Comment by yancouto** [comment]
Cool fact: Now we will have some statistics on package downloads ([git](https://bintray.com/chromebrew/chromebrew/git#statistics) for example). Couldn't find statistics for all downloads, though.

**Comment by jam7** [comment]
@yancouto Something like blow is required

 1. update package file like adding source
 2. BUMP VERSION NUMBER
 3. REMOVE PREVIOUS BINARY
 4. PR
 5. wait for merge
 6. wait for pre-compiled binaries PR (a day or two)

2 and 3 is very important.  Otherwise, users' environment will be corrupted.  I'll post how to do 6 by each collaborator soon.

**Comment by jam7** [comment]
1~4 are something like this https://github.com/skycocker/chromebrew/pull/1150/commits/33de65193f467cdb924539c088825aaa01a161f4.  
6 is something like this https://github.com/skycocker/chromebrew/pull/1150/commits/870e88d6a8d32ba832a42a25c1a6f963795658c2.

**Comment by uberhacker** [comment]
What is wrong with bumping the binary version even though the files are unavailable?  I think removing the previous binaries in the package is a bit drastic and probably not necessary.  I would <3 to update crew to compile from source as a fallback if binaries either don't exist or fail installation.

**Comment by cstrouse** [comment]
I'm updating a few packages and after bumping the version number and removing the binaries the package won't upgrade.

**Comment by uberhacker** [comment]
@cstrouse: Did you try `crew upgrade <package> -s`?  This will force a source build instead of upgrading via binary.

**Comment by cstrouse** [comment]
@uberhacker I got it sorted with -s thanks.

**Comment by uberhacker** [comment]
@cstrouse: I'm not sure you are aware, but we added a few new constants awhile back that simplify destination directories.  I wanted to correct this on the next round of updates but I see that you took that on already.  I really appreciate your efforts.  What I had envisioned was to change all references to `/usr/local` to use destination constants instead.  So, for example, `#{CREW_DEST_DIR}/usr/local` would be changed to `#{CREW_DEST_PREFIX}` and `#{CREW_DEST_PREFIX}/lib` would be changed to `#{CREW_DEST_LIB_PREFIX}` since x86_64 systems use `/usr/local/lib64` instead of `/usr/local/lib` on other systems.  We've had a few issues with libraries that were installed in the wrong directory on some packages.  Just thought I might make you aware so you know.
Thanks

**Comment by cstrouse** [comment]
@uberhacker No problem, I'll make sure I do that one these next ones. What's the best way to deal with the binary url issue? Leave them for now?

**Comment by jam7** [comment]
I prefer removing them is good.  Otherwise, if it is merged and user performs `crew upgrade pkg`.  That old binary is installed as a new version.  If we remove binary URL, crew simply compile it from source.

I just don't understand why @uberhacker think removing URL is drastic...  I think it is necessary and easy.

**Comment by jam7** [comment]
@uberhacker What wrong with bumping the binary version even though the files are unavailable is we may mis-type.  Removing URL is simple.  What is wrong with removing URL?

**Comment by uberhacker** [comment]
@jam7: Who said you needed to merge the PR before the binary urls were available?  My point I mentioned in #1163 might be worth considering.  It's fine to do it this way, it just means more work and more PRs.  I guess I'm just lazy, that's all.

**Comment by jam7** [comment]
I simply cannot build pre-built binary files without performing merge.  You asked me to pass pre-built binary sha256, but it's impossible for me.  It's the limitation of current work flow.

**Comment by uberhacker** [comment]
You cannot add the PR repository and do it that way?  How do you test PRs before you merge?  Isn't this the same thing?  Why does the update need to be merged into the master branch first?

**Comment by jam7** [comment]
I need to compile it to all three architectures.  That's the reason.  I'm doing pull and merge stuff for the test before merge.  However, I don't want to do that for all three architectures to create pre-build binaries since I'm lazy.  I want to use simple one `make` to build all new binaries for each architecture.

**Comment by uberhacker** [comment]
Can you use `crew install <package> -s` to bypass binary and build from source?  That way, it doesn't matter if binary_url is blank or not.

**Comment by jam7** [comment]
Not sure why you start talking about `-s` option here.  Are you answering previous question or something?

**Comment by uberhacker** [comment]
Yes, I was just thinking if you were going to merge anyway, you could compile that way and not need to remove the binary_urls each time.

**Comment by jam7** [comment]
I don't merge it if it contains old or non-existing URLs since it causes errors.  It is possible to use such package with `-s` option like you described, but I don't want to force it to all other users.

**Comment by jam7** [comment]
It is running for a while.  Please let me know if you have any problems.

Some questions and answers I imagine:

 - How do you compile and upload them?  Check #1167 for details
 - Who can post to bintray?  All collaborators can.  Actually, only me and @thedamian can at the moment.  But we will give privilege to all other collaborators once they make their own account on bintray.
- Can I ask to post my own pre-built binaries?  I appreciate if you ask us to *build* and post binaries since I'm not sure how to avoid binary poisoning.
- Can you post pre-built binaries automatically?  No for now.  We have plan to do that, but not yet.  This is just an technical problem.  I appreciate if you can make some mechanism to do that using circleci.

**Comment by jam7** [comment]
I'm not chromebrew collaborator anymore.  I've passed the ownership of https://bintray.com/chromebrew to @uberhacker.
