### ISSUE TITLE
Package tig: ./autogen.sh: 20: aclocal: not found

### ISSUE THREAD

**Issue by tomas** [skycocker/chromebrew#1085]
I'm trying to install `tig` on a fresh Chromebrew install. But `crew install tig` throws the following:

```
[...]
Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
./autogen.sh: 20: aclocal: not found
tig failed to install: `./autogen.sh` exited with 127
```

I tried installing `autoconf` but no workie.

**Comment by tomas** [comment]
On another note, why do some packages have a binary version available and some not? (e.g. less, readline, tig, autoconf, filecmd, ncurses, nano, etc)

Thanks again!

**Comment by tomas** [comment]
`crew install automake` fixes the problem above. I guess it should be marked as a dependency of `tig`.

**Comment by jam7** [comment]
Thank you for the report again.  I experienced the same problem.  adding `depends_on 'automake'` fixes this problem actually.

I appreciate someone send PR about this.  Thanks.

**Comment by cstrouse** [comment]
@jam7 PR coming in a few minutes adding the dependency and updating the package.

**Comment by jam7** [comment]
@cstrouse thanks.  close in favor of #1092.
