### ISSUE TITLE
cc command not found

### ISSUE THREAD

**Issue by faddee** [skycocker/chromebrew#111]
When installing node-sass with npm I got the following error: `make: cc: Command not found`

Solved it by creating a cc-symlink to gcc: `$ ln -s /usr/local/bin/gcc /usr/local/bin/cc`

Just wanna let you know. Not sure if this is your issue but it would probably save someones headache if you created it when you install gcc.

**Comment by thedamian** [comment]
Just a quick node. the line is:
ln -s /usr/local/bin/gcc /usr/local/bin/cc

(you had /user)

Other than that. GREAT Suggestion.

**Comment by thedamian** [comment]
an amazing suggestion. but it's not part of the crew project as a whole unless skycocker decides to add it to the initial scripts (which sounds like a good idea)

So I suggest closing this issue.

**Comment by faddee** [comment]
Thanks for the heads-up with the typo. Edited my comment just in case someone finds this solution without reading the comments. :-)

**Comment by thedamian** [comment]
The suggestion is excellent. And I did it right away after seeing it. That's how I found the typo. But regardless it a fantastic trick!

**Comment by skycocker** [comment]
AFAIR it should be fixable without the symlinks through come configure or make flag. Anyway, do you think the issue could be closed now?
