### ISSUE TITLE
Installation instructions aren't clear

### ISSUE THREAD

**Issue by ptarjan** [skycocker/chromebrew#117]
It gives me a command to run on my chromebook, but where do I run it? If I try the terminal (which I open by pressing CTRL + ALT + T) I get `Unknown command: 'wget'`. Where else I can run your command? Do I have to do developer mode? Is so, please mention that and maybe point to a full tutorial.

**Comment by Kriskras99** [comment]
You first need to type shell to get in the real terminal. If that gives an error developer mode isn't enabled and you will need to enable it.

**Comment by ptarjan** [comment]
I'll try that, but all I ask is that you add it to your README please.

**Comment by Kriskras99** [comment]
Please see my pull request (#118), and say if you think anything else should be added.

**Comment by ptarjan** [comment]
Thanks for being so quick. It looks good but I would tell people the common error when you type shell on a non-developer mode and point them back to the above section.

Sent from my iPhone

**Comment by Kriskras99** [comment]
Any more ideas?

**Comment by ptarjan** [comment]
lgtm
shipit

**Comment by Kriskras99** [comment]
Then it's waiting for @skycocker to merge it.
