### ISSUE TITLE
nano fails to start after upgrade

### ISSUE THREAD

**Issue by fp555** [skycocker/chromebrew#1173]
I just ran a `crew upgrade nano` on my system, installing the precompiled binary. But now nano fails to start with the message:
```
nano: error while loading shared libraries: libmagic.so.1: cannot open shared object file: No such file or directory
```
I couldn't find a `libmagic` package to install, so I'm not quite sure how to fix this. Help appreciated!
btw, I'm running ChromeOS version `62.0.3193.0` (dev).

**Comment by flyingP0tat0** [comment]
Maybe [`file`](https://github.com/file/file) could be the solution?

**Comment by fp555** [comment]
Thank you @flyingP0tat0, I'll let you know as soon as I have time to try it.
Shouldn't it be added in the package repository, and as a dependency though?

**Comment by jam7** [comment]
@fp555 Sorry for inconvenience.  Please install filecmd by `crew install filecmd`.

**Comment by fp555** [comment]
`crew install filecmd` fixed it. Thank you for your help.
