### ISSUE TITLE
Can't use traditional linux commands such as apropos and man for example

### ISSUE THREAD

**Issue by emran26** [skycocker/chromebrew#119]
There are some others too but I keep getting command not found. I am following the steps in:

http://cli.learncodethehardway.org/book/

and I can't do some of the commands that are listed there. Is there something I'm doing wrong?

**Comment by Kriskras99** [comment]
You're doing nothing wrong, if you used these commands on ubuntu for example they would work. The Chrome OS CLI is just really basic so some commands won't work.

**Comment by thedamian** [comment]
@emran26 I think crouton (http://www.howtogeek.com/162120/how-to-install-ubuntu-linux-on-your-chromebook-with-crouton/) is the answer for you. 

It gives you a full linux machine when you want to learn linux. and it gives you chromebook speed and security when you don't.

**Comment by jparagon** [comment]
And the great thing is eventually with things like chromebrew and linux brew you will have the advantage of a chrome UI / linux command / full linux 

I have most of it working right now but there are still some kinks. https://github.com/Homebrew/linuxbrew/wiki/Chromebook-Install-Instructions

**Comment by thedamian** [comment]
@jparagon I like that link to brew. But @emran26 problem isn't that he has a problem with this version of homebrew and not yours. It's that he wants a full linux machine so he can follow along on his book.

Following your instructions would NOT fix this problem as brew doesn't have a forumal for installing man pages or anything else he wants. 

He still needs to either get a shell on any of the free linux out there (like joyent.com or codeAnywhere.com) or simply install crouton which will let him/her load a FULL LINUX on his chromebook for his work.

**Comment by jparagon** [comment]
I was offering an observation, not a solution.

**Comment by lyxell** [comment]
Closing as invalid.
