### ISSUE TITLE
Python3 PyGame error - unable to open a terminal window

### ISSUE THREAD

**Issue by ijean** [skycocker/chromebrew#1208]
Hello,

I've installed Python 3 through Chromebrew and PyGame (which uses SDL 1.2 for graphics) through pip3. My problem is that I can't seem to be able to open a window for a simple PyGame app when I start the program from crosh -> shell.

Is this expected behaviour ? I've noticed that Chromebrew lets you install SDL 1.2 and SDL 2 how will I be able to open a windowed application ?

Thanks,
Jean

**Comment by jam7** [comment]
Are you trying to run GUI programs?  If so, chromebrew doesn't have ability to do so.  Some of us are working to achieve it in #889, though.

If not, please let us know what you typed to run your application.  I'm not python guy, so I don't know even how to reproduce your problem at my side.

**Comment by ijean** [comment]
Yes, it is a GUI program. PyGame is simple game framework for Python. PyGame is based on SDL. 

I noticed that Cromebrew has libsdl and libsdl2 available so I assumed there is a way to run GUI applications. What is the point of providing graphical libraries if you can not use them ?

**Comment by flyingP0tat0** [comment]
@ijean You can use these libraries without a GUI. We are working on a GUI, but I don't have much time at the moment, that will take some time.

**Comment by ijean** [comment]
@flyingP0tat0 Thanks.
