### ISSUE TITLE
libSDL2 - No available video device error

### ISSUE THREAD

**Issue by ijean** [skycocker/chromebrew#1209]
Hello,

I've tried to compile a simple SDL2 program and SDL_Init fails with *No available video device*. Do I need to set the **SDL_VIDEODRIVER** to a certain value ? Is it even possible to run SDL2 programs under Chrome OS ?

Thanks,
Jean

**Comment by flyingP0tat0** [comment]
As I already wrote, at the moment you can't run GUI programs.

**Comment by ijean** [comment]
OK, understood. I will close both issues since they seem without object for now.

Thanks.
