### ISSUE TITLE
Zsh: Requires gdbm

### ISSUE THREAD

**Issue by AravK** [skycocker/chromebrew#1213]
Steps:
Install ZSH
run `zsh`
```
zsh: error while loading shared libraries: libgdbm.so.4: cannot open shared object file: No such file or directory
```
Please add the `gdbm` package as a dependency.

**Comment by jam7** [comment]
Sorry for inconvenience.  It was my fault while I was hand-compiling zsh on x86_64.  I will update pre-built binary files.  Please install zsh with `crew install zsh -s` in the meantime.
