### ISSUE TITLE
JDK8 package for 64bit is missing (404 error) on dropbox

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#125]
in the JDK8 package (https://github.com/skycocker/chromebrew/blob/master/packages/jdk8.rb) for the x86_64 you are pointing to: "https://www.dropbox.com/s/2zohwl033i6rol2/jdk1.8.0_25_x86_64.tar.gz?dl=0"

it's a 404 error, and drop box does not have that file.

It throws a "Checksum mismatch :/ try again" But it's the fact the file is missing in dropbox that's the issue.

Thank you. and I LOVE this product. I am presenting at a conference next month WITH my chromebook BECAUSE of your amazing work!

**Comment by thedamian** [comment]
I have a pull request to fix this link in the package file:
https://github.com/skycocker/chromebrew/pull/127

But I can suggest looking for your own jdk8.rb file (I thnk it's in the /usr/local/lib/chromebrew/packages) and copying the 32bit version of the JDK to the 64bit version. install the jdk8 package using crew and then going to the official jdk8 link (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and unzip the jdk. you'll end up with a directory like: jdk8_65_....., copy the contents and overwrite the files in /usr/local/lib/opt/java (which should look the same and you'll have the 64bit JDK8 working)

**Comment by skycocker** [comment]
shoud I consider it fixed as you PR was merged?

**Comment by thedamian** [comment]
Yes. That PR is my copy of the file on my box I used to install jdk8 on a 64bit Chromebook pixel. 
So I'm closing the issue.
