### ISSUE TITLE
Protobuf SHA256 Mismatch

### ISSUE THREAD

**Issue by rumpaar1** [skycocker/chromebrew#1279]
The sha256 hash for the source for protobuf doesn't match the hash of the actual download at the url stated in the protobuf.rb file.

**Comment by rumpaar1** [comment]
Looks like the file's changed as it doesn't match the older sha1 sum from comit e81747f either. Odd.

**Comment by flyingP0tat0** [comment]
Good catch. Will provide a fix.

**Comment by rumpaar1** [comment]
I would have done it but by the time a contributor checks the hash they may
as well have done it anyway as would have to download and hash the file
anyway.



Aaron Rumpler

Year 13 - 13BU

Kaikorai Valley College
500 Kaikorai Valley Road
Bradford
Dunedin 9011
New Zealand
