### ISSUE TITLE
Support for xclip

### ISSUE THREAD

**Issue by whitneyit** [skycocker/chromebrew#128]
Would it be possible to add support for `xclip` or something similar?

**Comment by thedamian** [comment]
Can I suggest you:
1) crew install buildessential
2) download and unzip the xclip code: http://sourceforge.net/projects/xclip/
3) follow these instructions (except for the last step of creating the man files) https://github.com/milki/xclip/blob/master/INSTALL
4) copy the xclip bin to /usr/local/bin (with sudo): sudo cp xclip /usr/local/bin

(if it's a whole library the correct way is to copy the whole library to /usr/local/lib into it's own directory and then link the bin to /usr/local/bin/xcopy, but if it's just one file that comes out of it just cheat and copy it to your /usr/local/bin)

Try that, and let us know.

**Comment by cstrouse** [comment]
Seems `xclip` isn't going to be possible according to the discussion on a [chromium bug report.](https://bugs.chromium.org/p/chromium/issues/detail?id=320361)

> FWIW, https://chromium.googlesource.com/apps/libapps/+/master/hterm/etc/osc52.sh lets you copy arbitrary data from stdin to the system clipboard.  This should provide similar functionality to `xclip -i`.

**Comment by lyxell** [comment]
Closing since it seems this won't be possible.
