### ISSUE TITLE
[clisp] Conflicting configure options

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#1304]
The clisp package specifies both `--disable-static` and `--enable-static` in the build step. One of these configure options should be kept and the other removed.

**Comment by uberhacker** [comment]
I would be in favor of `--disable-static`.  Which option currently "wins"?  Should we also add `--enable-shared`?

**Comment by cstrouse** [comment]
Not sure, right now the package fails to build due to the sed modification to the Makefile not working properly.
