### ISSUE TITLE
cURL + Git.io = Win

### ISSUE THREAD

**Issue by efmeeks** [skycocker/chromebrew#1310]
Just thought I'd point out that you could use `curl -Ls git.io/vddgY | bash` instead of `wget -q -O - https://raw.githubusercontent.com/skycocker/chromebrew/master/install.sh | bash`.

The end result is identical, but brevity is always better in my opinion ;)

Cheers!

**Comment by cstrouse** [comment]
I don't think we should obscure the filename that will be downloaded from the user just to save a few characters.

**Comment by efmeeks** [comment]
Why? What's important is the contents of the file, not the length of the URL. The full, non-shortened URL could just as easily be something *other* than what the Readme claims it to be, right? 

There is a certain level of trust when piping code to bash. It's up to the user to take a look at the code first to ensure legitimacy and that is true regardless of the URL length. Even if a user were to check the contents of the file first, I doubt they would read through every line, further illustrating my point that most people trust that the copy/paste code is okay to use.

Also, it's worth noting that [Git.io](https://git.io) is an https service offered by GitHub and it only allows shortening of GitHub-hosted content, not any random URL.

I do think transparency is important, but in this case, I don't think it really matters as people will do what they already do: check the source code first, trust the project maintainer, or both.

**Comment by jcvernaleo** [comment]
I very much agree that a shortened URL is a bad idea in this case.  It adds to the things places where you need to trust something.  Clarity is way more important than shortening something that will just be copied and pasted anyway (as opposed to something that would need to be typed by hand).

**Comment by uberhacker** [comment]
Why do we need one or the other?  Why not both?  It's nice to know there are alternative ways of doing things.  As a wise philosopher once said: _"There is more than one way to skin a cat."_

**Comment by efmeeks** [comment]
Hehe. Good point, Ed :)

**Comment by cstrouse** [comment]
Since both options are now included in the readme can we close this?
