### ISSUE TITLE
What are the default recommended cmake args for chromebrew?

### ISSUE THREAD

**Issue by CatLover91** [skycocker/chromebrew#1319]
I am working on porting over a variety of packages from homebrew to chromebrew because they are needed as a dependency for ncmpcpp (which uses mpd, which has a load of dependencies). I am finding that across a large portion of these packages, they utilize homebrew's `std_cmake_args` to normalize cmake installations across the package manager. Homebrew's definition is located [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L1274) within their formula class. I am willing to implement something like this within package.rb as I start actually debugging the installations of all the packages, but I want to know if something like this is desired within chromebrew, and if so what kind of flags would be preferred for just usable defaults in the library.

I am currently manually using flags similar to how chromebrew does in [brotli](https://github.com/skycocker/chromebrew/blob/81215dd30732224aac97ffdca522771fe76ef24e/packages/brotli.rb#L20), but desired recommendations from core maintainers would be greatly appreciated.

On the topic of proper C flags, homebrew also uses a superenv variable name [cxx11](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ENV/super.rb#L296) which I do not know how to handle within chromebrew. It is used for correctly supporting C++11 compilation, which may also be candidate for a standardized package.rb variable (or support for implementation of super.rb to help encourage further porting between the two libs).

**Comment by uberhacker** [comment]
Hey @CatLover91: Your timing is good as [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is in progress.  Make sure you sign up so you can get credit for these new packages.  I personally don't have any specific recommendations for arguments.  Usually, the README or INSTALL docs have all the information you need to compile from source.  As long as the package installs/uninstalls and executes correctly on your Chromebook after a successful compile, that is usually good enough.  Please check out the [Wiki](https://github.com/skycocker/chromebrew/wiki).  Let me know if have any other questions about adding new packages.

**Comment by CatLover91** [comment]
That recommendation is on a per-package basis though. Wouldn't stock defaults that are best optimized for chromeos be encouraged across chromebrew packages? 

Homebrew has OSX specific cmake args along with what appears to be "best practice" arguments, and then formula-specific flags are added at the package level. This kind of set up would still allow for per-package flag declaration as we currently use, but would give a strong boilerplate build configuration.

**Comment by uberhacker** [comment]
@CatLover91: I imagine the optimizations don't have a dramatic effect on performance but if you think we can benefit from improved "best practice" documentation, by all means, please feel free to go ahead and do it if it can add value.  Keep in mind there are 4 separate architectures that need supported so a generic compile is probably the most sane approach unless you can figure out the nuances of each platform.
