### ISSUE TITLE
New Feature Request Thread

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#132]
I suggest making only ONE thread for new features so that we don't fill the "issues" section with REQUESTS.

Also I'll try to make a Wiki (unless someone beats me to it) to show how to create a new Package yourself.

So Please feel free to use this thread to make a request of a package you want. WHERE we can find it. and WHY you need it.

I suggest closing all the other request Issues unless Skycocker likes having 26 open issues where a lot of them are just a request for X package or Y package.

**Comment by Kriskras99** [comment]
Good idea, here are the current package/feature requests:

Current open package requests:
#10 [Cups](https://www.cups.org/)
#27 Man-pages ([man-db](http://man-db.nongnu.org/) and [less](https://www.gnu.org/software/less/))
#63 [Mosh](https://mosh.mit.edu/)
#66 [rdesktop](http://www.rdesktop.org/) / [freerdp](http://www.freerdp.com/)
#128 [xclip](http://sourceforge.net/projects/xclip/)

Current open feature requests:
#4 ARM support
#48 Error handling when download fails
#49 Recompiling binaries with rpath
#68 More binaries
#70 Support for tinycore packages
#72 Better error handling when git gives an error

**Comment by ealgase** [comment]
One package I'd like to add is the X windows manager.  You could also install Xfce and Gnome as separate packages.

**Comment by jabyrd3** [comment]
I'd kill for arm support. Can we raise a bounty or something?

**Comment by bfayers** [comment]
> ealgase commented on 8 Feb
One package I'd like to add is the X windows manager. You could also install Xfce and Gnome as separate packages.

I'm sure this can be done relatively easily, just with some compiling, heck you could probably do it yourself? Gnome has its source avaliable anyways. [https://github.com/GNOME/gnome-desktop](https://github.com/GNOME/gnome-desktop) [https://github.com/GNOME/gnome-shell](https://github.com/GNOME/gnome-shell) or is it harder than i think?

**Comment by bfayers** [comment]
>ealgase commented on 8 Feb
One package I'd like to add is the X windows manager. You could also install Xfce and Gnome as separate packages.

>bfayers commented 3 days ago
I'm sure this can be done relatively easily, just with some compiling, heck you could probably do it yourself? Gnome has its source avaliable anyways. https://github.com/GNOME/gnome-desktop https://github.com/GNOME/gnome-shell or is it harder than i think?

@ealgase 
Around my house in total we have 3-4 chromebooks and I've got an old Dell D630 or a D620, don't remember. It has either a Core 2 Duo T7250 or T7500, they're 64bit so when i'm back around I can take a look at compiling the gnome-shell on the dell thing (neverware, chromium os) and report back

**Comment by bfayers** [comment]
Something I would love to see is wine, they provide source [here](https://dl.winehq.org/wine/source/1.9/wine-1.9.7.tar.bz2)  mainly because it would be super cool to be able to run windows programs.

**Comment by bfayers** [comment]
Does [this](https://github.com/ludoo/chromebrew-arm-bootstrap) help with ARM atall?

**Comment by jabyrd3** [comment]
Bump. 

Would really love to be able to use this on C100.

**Comment by bfayers** [comment]
@jabyrd3 hi, I've started work on getting chrome brew to work on arm, at I'm having to crosscompile gcc & buildessential on my Ubuntu vm. WARNING IT DOESN'T WORK AT THE MOMENT SINCE THE RUBY PACKAGES I USED ARE Broke.

**Comment by jabyrd3** [comment]
@bfayers i will buy you as much beer / coffee as you can drink.

**Comment by bfayers** [comment]
@jabyrd3 haha, thanks I'm currently compiling GCC on crouton (cross compiling was a mistake) its been going for ~7hours and still going... I'm just leaving it plugged into power waiting, just waiting.

**Comment by drbree82** [comment]
Mutt email client would be handy.

**Comment by jabyrd3** [comment]
@bfayers any luck getting gcc to build? if you can send it to me i'd be eternally grateful; I got ruby installed and running before the enormity of compiling gcc in crouton scared me off pursuing it. If you got that side figured out I'm pretty sure I can get it running.

**Comment by drbree82** [comment]
In reference to building for ARM, has anyone built a qemu-kvm image with the Chromebook ARM architecture? This would help with building for ARM.

**Comment by bfayers** [comment]
@jabyrd3  @drbree82 As far as I know no there is not, If i new how id make one, having a hard time compiling gcc in crouton, would definitely appreciate any help.

**Comment by drbree82** [comment]
@bfayers Ok, here's the basics.
Run `sudo apt-get install qemu`
Even if you already have qemu installed, do this, as the base package doesn't have all the machines.
You'll need to go download the open source chromeOS image from somewhere. Not sure how, but I'd probably start with the chromeOS recovery tool in chrome browser
run
`qemu-system-arm -h`
Set a source image(chromeOS image) and a target. I gather all this info is in the help for qemu-system-arm, or the man page.

I haven't actually done this all myself for lack of time. I have however, used this procedure for running other environments.
If you aren't running ubuntu 16.04 LTS, then you probably have access to the original qemu-kvm package, which makes it a hell of a lot easier.

Good luck, and if you get stuck, reply back on here and I'll try to fire it up at my end.

**Comment by bfayers** [comment]
@drbree82 You can get the chromium os images from http://chromium.arnoldthebat.co.uk/index.php?dir=weekly%2F

**Comment by drbree82** [comment]
Is Chromium OS the same as Chrome OS? Either way, sounds like you've got enough to go along with.

**Comment by jabyrd3** [comment]
Where'd we net out on this? Is anybody working on it, and if so, can I help you out if you're stuck? I got as far as getting ruby running in chromium and editing chromebrew to attempt to install, but there's a lot of packages that need to be built for arm before it'll actually work.

**Comment by Prosserc** [comment]
I would love to see a package added for pip (package manager for Python libraries). I would be happy to have a go at this, I'm not really familiar with ruby, but the other packages look pretty straight forward from what I've seen.

**Comment by Prosserc** [comment]
Another feature request, it would be nice to be able to include wildcards in the search e.g. `crew search py*` could return:

> (i) python
> python27
> python34

**Comment by bfayers** [comment]
@jabyrd3 No, not much further I get stuck with C compiler cannot build executables. no matter what.

**Comment by bfayers** [comment]
@Prosserc you can get pip by doing this:  

`sudo su -`

`wget https://bootstrap.pypa.io/get-pip.py`

`python get-pip.py`

pip then works as usual.

**Comment by minektur** [comment]
not without a working openssl - if you build one of the from-source pythons without my openssl headers, because the crew openssl is kind of broken, you end up not being able to install pip because you can't install the python openssl pacakges which pip relies on.  

It was that fact that got me looking at fixing openssl, and then instead doing the openssl headers package.

**Comment by minektur** [comment]
(I have 80% of a pip package done - when I get unbusy this weekend....)

**Comment by bfayers** [comment]
@minektur Ah, openssl see I dont have the crew one because I dont have crew (ARM)

**Comment by TheLonelyGhost** [comment]
Just wanted to throw my hat into the ring for support of other package repositories, similar to Homebrew's tap functionality.

**Comment by cstrouse** [comment]
How about adding a test method to the package class like homebrew does to validate that basic features of the software function properly after installation?

**Comment by lyxell** [comment]
@cstrouse While I like this idea we need to have in mind that many of our packages have quite extensive test suites, and many Chromebooks have limited hardware, making testing a slow process. I don't really think the gains of running the suites are worth it if it slows down installation time by numerous minutes. Otherwise, its a good idea.

**Comment by cstrouse** [comment]
@lyxell I was thinking tests along the lines of [this](https://github.com/Homebrew/homebrew-core/blob/a5b4b2571f208f8ca35bb4a5cf89bc5c15b1af4e/Formula/newlisp.rb#L39) rather than the package's test suite.

**Comment by cstrouse** [comment]
I've created a bash [autocomplete script for crew](https://gist.github.com/cstrouse/8e13a7008ebfef49f335d05bb4212409). Please give it a try and if people find it useful maybe we can include it during install.

**Comment by cstrouse** [comment]
Does anyone else feel like we should add some basic logging functionality?

**Comment by uberhacker** [comment]
@cstrouse: This autocomplete script is a really cool idea.  What kind of logging functionality were you thinking of implementing?

**Comment by thedamian** [comment]
@drbree82 Mutt added in added pull https://github.com/skycocker/chromebrew/pull/618

**Comment by uberhacker** [comment]
I don't believe we have rdesktop/freerdp, xclip or crew autocomplete yet.  But it might be good to update this thread to show which feature requests have been added vs those that need added yet.

**Comment by sajjaadf** [comment]
THIS IS OUTDATED!

**Comment by sajjaadf** [comment]
CLOSE THIS

**Comment by JL2210** [comment]
@sajjaadf It is not. I am still working on some of these packages.

**Comment by uberhacker** [comment]
#66 is still an open issue this thread references.  I agree this is getting old and if you have any better suggestions of where we can try to track these package requests, I'm all ears.

**Comment by JL2210** [comment]
Right here. I am still working on these. Please do not close.

**Comment by uberhacker** [comment]
@thedamian suggested: `I suggest making only ONE thread for new features so that we don't fill the "issues" section with REQUESTS.`  This has not been honored by any means. :)

**Comment by JL2210** [comment]
I wish. That would be so much easier.

**Comment by torzod** [comment]
I requested love to play "not tetris 2," which requires a very spwcific version - 0.7.2. Löve in turn requires a specific version of lua, and I was having trouble building that on my xe303c12. Löve's error was that it couldn't find the dependency `lua_pcall`, which is an error I've gotten every machine I've tried to build it on. I do not remember the error I got when building lua, but I was building ot because the precompiled versions of `lua` and `luajit` do not provide the library needed.

**Comment by JL2210** [comment]
@torzod `lua_pcall` is not a DEPENDENCY, it is a C FUNCTION not provided by newer versions of Lua. Please do not confuse the two (and while you're at it, try linking with `-llua`).

**Comment by torzod** [comment]
my bad, i knew it was not a 'dependency,' but at the time i couldn't remember the correct name for it. what should i try `-llua` with by the way? building love? or building lua?

**Comment by JL2210** [comment]
Love: `LIBS=-llua ./configure ...`

**Comment by torzod** [comment]
executing `LIBS=-llua ./configure` gives a permission denied error, despite me `chmod -x`-ing it. How can I fix this?

**Comment by JL2210** [comment]
First of all, it's `chmod +x`. But you have to move it to `/usr/local` due to a decision made by the Chromium team.

**Comment by torzod** [comment]
i tried `chmod +x`, but i didn't know about the `/usr/local` thing, thanks
for letting me know

**Comment by saltedcoffii** [comment]
it's been 6 years, closing
