### ISSUE TITLE
New package PRs needed

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1320]
Think you can add packages that are missing from this project?  Prove it and win a free t-shirt if you add 4 new package PRs before October 31.  Alternatively, you can help resolve issues as well.  More details here: https://hacktoberfest.digitalocean.com/.

**Comment by CatLover91** [comment]
I am currently working on packages for [kitty terminal](https://github.com/kovidgoyal/kitty), [ncmpcpp](https://rybczak.net/ncmpcpp/), [mpd](https://wiki.archlinux.org/index.php/Music_Player_Daemon), along with their dependencies for those who wish to work on linux audio and terminal emulation.

**Comment by cstrouse** [comment]
Signed up and have completed. Thanks for letting us know about the event @uberhacker!

**Comment by cstrouse** [comment]
Thanks to everyone who participated! Event has concluded. Closing.
