### ISSUE TITLE
[compressdoc] Package should use a tagged release for source

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#1326]
`compressdoc` is a shellscript from the BLFS project that's useful for compressing manpages correctly. It's used (when available) in `crew`.

The script does actually have a version `20080421.1623` in its current iteration.

There are a few problems with this package IMO:
1. Using an arbitrary commit sha instead of a tagged release.
2. Downloading the entire archive of tools just to cherry pick a single file vs downloading that file from `raw.githubusercontent.com`.
3. Using `chmod` + `mkdir -p` + `cp` when all you need is `install -Dm755 ../compressdoc #{CREW_DEST_PREFIX}/bin/compressdoc}`

**Comment by uberhacker** [comment]
@cstrouse: While normally I would agree we should use tagged releases when possible, in this project there are none available.  Since there is no way to download an archive of a single file, it was necessary to download the entire project so it could be checksum'd.  With that said, you are welcome to change the version and update the install section.  Then you can submit a new PR.
Thanks

**Comment by cstrouse** [comment]
There is a tagged release for BLFS but I guess to just download a single file we could just use something like `https://raw.githubusercontent.com/ojab/BLFS/af6c11d985fe36c8828abaa9d5124c8725580b15/auxfiles/compressdoc` and then sha256sum that file?

**Comment by uberhacker** [comment]
Right, but the tagged releases don't have compressdoc in them. :)  In order to checksum, we need a tarball.

**Comment by cstrouse** [comment]
I'm missing something here. Why can't we just use

https://raw.githubusercontent.com/ojab/BLFS/af6c11d985fe36c8828abaa9d5124c8725580b15/auxfiles/compressdoc

and use the sha256 of that file?, which would be

`f380473baaa8785b1c7a7a30f2dda4b748a9baed3b335655faedad49ebf8246b`

**Comment by uberhacker** [comment]
If you can make that work, then go for it.  You will still need a "throw away" source tarball, however.

**Comment by cstrouse** [comment]
It works fine if you use that file, that sha256 and then the following for the install step:

```ruby
system "install -Dm755 ../compressdoc #{CREW_DEST_PREFIX}/bin/compressdoc}"
```

**Comment by uberhacker** [comment]
Indeed it does.  Go ahead and submit a PR and I'll merge it.
