### ISSUE TITLE
Set PAGER to /usr/local/bin/less

### ISSUE THREAD

**Issue by ibraheem-moosa** [skycocker/chromebrew#1329]
`man` uses `PAGER` environment variable to show content. Default `PAGER` is set to `/usr/bin/less`. However `less` is actually located at `/usr/local/bin/less`. So `man` does not work. Setting `PAGER` to `/usr/local/bin/less` in `.bashrc` solves the problem.

**Comment by uberhacker** [comment]
@ibraheem-moosa: Thank you for the feedback.  Since man and git are both executable after crew is installed and do not require packages, it might make sense to install less at the same time crew is installed.  Not sure why less is not in Chrome OS core but this would solve that issue.

**Comment by cstrouse** [comment]
I'd like to see less included by default.

**Comment by ibraheem-moosa** [comment]
Hi thanks for replying. Where do I ask a general question? For example if I want to ask how some part of code works where do I do that?

**Comment by uberhacker** [comment]
@ibraheem-moosa: If you haven't done it yet, please examine the `crew` command and the supporting libraries located in the `lib` directory.  This is where most of the core logic that drives Chromebrew is located.  If you have a specific question, you can open a new issue or continue the conversation here if it's related to `less`.

**Comment by uberhacker** [comment]
See PR #1217 which addresses this issue.

**Comment by ibraheem-moosa** [comment]
Installing `less` using `crew install less` does not set `PAGER`. I think you need to set that too.

**Comment by uberhacker** [comment]
I added a command which the user can execute manually to set the PAGER environment variable after install.

**Comment by uberhacker** [comment]
Fixed in #1217.
