### ISSUE TITLE
Issue installing chromebrew on ASUS Chromebook Flip C302CA

### ISSUE THREAD

**Issue by lonfaure** [skycocker/chromebrew#1335]
``` sh
crosh> shell
chronos@localhost / $ wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.4.1-chromeos-x86_64.tar.xz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the ruby download.
```

**Comment by uberhacker** [comment]
@lonfaure: Thank you for reporting this issue.  Did you only try it once?  If the download was corrupted for some reason, you would get this message.  I have installed Chromebrew recently and did not experience this problem.

**Comment by cstrouse** [comment]
I just received the same error doing a reinstall on my XE500C13-K01US. I'm on a slow connection so that could be to blame or possibly something is up on Github's end right now.

```
chronos@localhost / $ wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash

Password: 
Creating new device.json...
Downloading ruby...
#####################################                                     52.2%
curl: (18) transfer closed with 4786652 bytes remaining to read
Verifying ruby...
ruby-2.4.1-chromeos-x86_64.tar.xz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the ruby download.
```

**Comment by cstrouse** [comment]
Yeah definitely looks like a failure due to network latency and packet loss. Trying again it resumed and successfully installed for me.

**Comment by uberhacker** [comment]
@lonfaure: Were you able to get around this issue or are you still having trouble?

**Comment by uberhacker** [comment]
Can we close this issue?

**Comment by cstrouse** [comment]
Since this doesn't appear to actually be a bug and @lonfaure isn't responding I'd say it's fine to close this.
