### ISSUE TITLE
Node and node_stable

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#138]
I added a new pull https://github.com/skycocker/chromebrew/pull/137 which renames the "nodejs" package to "node" to match how the package on rpm and deb are called now.

They changed from nodejs to node when they joined back with io.js a little while back.

Also updated it .0.1 version to the offical LTS version 4.2.4

I added a "node_stable" package to match node's official "STABLE" version which is at v5.4.1

This just catches crew up with what node officially supports.

Please let me know what you guys think?

**Comment by lyxell** [comment]
Is there a reason to why you used the uncompiled version instead of the precompiled in https://github.com/thedamian/chromebrew/commit/faaf0b5272a81a50311c44397944eafca577e309?

**Comment by thedamian** [comment]
Because it was easier and closer to what the original package was.

I prefer doing things that work on both x86 and 64x since I only have a 64x Chromebook to test it on.

It does take considerably longer but the reßults are the same.

**Comment by thedamian** [comment]
Fixed in pull https://github.com/skycocker/chromebrew/pull/173
