### ISSUE TITLE
crew -v|--version should display the version

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1385]
Currently, `crew -v|--version` does not work.  However, to complicate matters, the `-v` switch is also used to get verbose output from `crew search <package> -v`.  I propose we repurpose the `-v|--verbose` switch to something like `-x|--expand` instead so we can get `crew -v|--version` working.

**Comment by skiman6010** [comment]
I second this. Most command line tools use -v for version, so going against the grain with -v and --verbose seems confusing and not user friendly.

**Comment by cstrouse** [comment]
Many tools that have both verbose and version as options use -v for verbose and -V for version.

**Comment by uberhacker** [comment]
That is true but the way crew uses the `-v|--verbose` switch is not what you might expect.  I think we should have the verbose option, just not in the way we're using it currently.

**Comment by cstrouse** [comment]
Maybe use it for toggling the V=0 and V=1 options to make?

**Comment by uberhacker** [comment]
Yeah, and it could also be used to remove `-s` on curl commands and `-q` on wget commands.

**Comment by cstrouse** [comment]
Ok so -v for setting V=1 on make and removing the quiet options from curl/wget and then -V for version info? I think that is the way to go.

**Comment by uberhacker** [comment]
Agreed.  I'll try and submit a PR later this evening.
