### ISSUE TITLE
Limitations with Fake Packages

### ISSUE THREAD

**Issue by skiman6010** [skycocker/chromebrew#1390]
There seems to be some problems with fake packages that we have.

If you run `crew update` with glibc 1.1 installed, it will tell you: 
```glibc could be updated from 1.0 to 1.1```.

Obviously you already have glibc 1.1 installed, so any updating will not fix this problem. 

The solution is to run `crew uninstall glibc`.

I wanted to bring this up to see if anyone had any ideas on how to remedy this to make fake packages work seamlessly.

**Comment by uberhacker** [comment]
@skiman6010: Thank you for bringing attention to this issue.  The problem appears to be that fake packages are not "upgradeable".  In the meantime, until a solution is available, the recommended workaround is to remove and install again.  In the case of `glibc`, execute the following:
```
$ crew remove glibc
$ crew install glibc
```

**Comment by JL2210** [comment]
Can we find a way to circumvent this? I know that real packages are removed before they are upgraded. Maybe we could 'remove' fake packages, too.

**Comment by lettucehead** [comment]
What JL2210 said makes SO much sense!!!!
