### ISSUE TITLE
Binary Packages or compiled?

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#140]
Alright. it's time to brawl!

Do you create packages with binaries that install quickly but need a i686 (32bit) and x64 (64bit) versions?

Or do we have everyone compile everything. 

Binary: 
PRO - Fast, REALLY FAST! you can be done in maybe 2 minutes)
CON - 32bit and 64bit versions. No one realized java had it's 64bit version missing until I tried it (because the 32bit version works flawlessly)

Compile:
PRO - One version for everyone. If I test it on my 64bit version. your 32bit machine will work. And it's EASY for ANYONE to update to the latest version of a package. NODE updated? Just find the new link. find the sha1sum of the file and do a pull request. Everyone has the latest and greatest faster.
CON - You're compiling each and every single time. SLOW! I mean multiply EVERY computer with the time wasted compiling. Did I mention slow?

Thoughts? @skycocker @jbaum98 @Tivoli you guys have done the most work here. What do you guys think?

**Comment by Tivoli** [comment]
I prefer compiling, not just for the easier updating, but as you get into more complex packages, like postgresql for example, that have multiple binaries for its tools would have to be supported and even more of a complex update process. With nodejs, you have npm and node that get installed, so you would have to do multi package updates with that possibly.

**Comment by jbaum98** [comment]
I feel like we can emulate Homebrew here, which uses "formulas," which are compiled on every computer, as well as "bottles" which I think are precompoled binaries. You just can have a list of binaries and a way of determining whether or not they are applicable on the machine and compile it yourself as a fallback.

**Comment by Tivoli** [comment]
I like that idea. :+1:

**Comment by thedamian** [comment]
cool! In brew do the forumals have these "bottles" ready to go and fall back on them? or you choose "binary or compiled" somehow?

**Comment by jbaum98** [comment]
I think if the precompiled "bottle" is available, it will be used unless the user specifies not to. They describe exactly how they decide which to use [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-do-you-compile-everything]).

**Comment by lyxell** [comment]
One idea could be to set up a server with a hook to this repository which compiled things automatically as soon as the master branch is updated, it's a bit of work but totally possible.

**Comment by jbaum98** [comment]
Homebrew uses [Bintray](https://bintray.com/homebrew/bottles).

**Comment by skycocker** [comment]
I guess we currently kind of resemble homebrew's behavior - precompiled binaries where possible (or necessary), and source builds where there is no binary available. One good thing would be to precompile as much as we can an store it somewhere like mentioned Bintray - but this would require us to have all the possible chromebook architecture variations available somewhere (arm, i686 and x86_64).

**Comment by thedamian** [comment]
Ok. I've done the minimum which is register on bittray but like an idiot I just realized it's under my name.
https://dl.bintray.com/thedamian/ChromeBrew/

do we want to make an official bintray.com/chromebrew

and I don't know to have many people submit to it etc.

**Comment by jam7** [comment]
FYI, now `crew` has `build` command to generate binary packages.  Theoretically, we can build all binary packages for particular architecture by runnning following script on each architecture.
```
pkgs=/usr/local/lib/crew/packages/*
for i in $pkgs; do
  base=`basename $i`
  targ=${base%.*}
  crew build $targ
done
```
So, If we have a good server with qemu, we can build binary packages automatically.   :)
Maybe it is possible to follow brew's way.  Just an idea, though.

**Comment by kirbyfan64** [comment]
FWIW I'd like it if there could be a mix, so that binary packages will be picked if present, but it will otherwise be built from source...

**Comment by jam7** [comment]
@kirbyfan64 crew does what you want.  :)

We can put both source URL and binary URL to one package.  If crew finds a binary URL for the particular architecture, it installs the binary.  Otherwise, crew installs from the source.

There is no option like homebrew to force to install from the source yet, though.  We only have `build` command at the moment.

**Comment by jam7** [comment]
FYI, if you guys want to run Chromium OS for each architecture on KVM to set up a server to build `bottle` automatically, https://github.com/jam7/chromeos-build is yours.  I released pre-compiled Chromium OS R60 there.

You can compile your own Chromium OS from the source using scrips provided there, or you can download pre-compiled Chromium OS R60 provided there.

Tested x86_64 and i686 Chromium OS, and they work fine on KVM.  My KVM box doesn't support ARM, so I could not test arm Chromium OS yet, but it should work.

**Comment by yancouto** [comment]
How could I submit the binaries to the [chromebrew bintray](https://dl.bintray.com/thedamian/ChromeBrew/)? Or should I create my own?

In #1036 I uploaded a binary to a release in my fork (since it doesn't need versioning), as that seems better than dropbox and I've seen done in some packages. Bintray seems to be made for this, but isn't it also paid?

**Comment by uberhacker** [comment]
Both?
