### ISSUE TITLE
Anyone interested in a 24 pull request challenge this December?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1455]
♬ On the First day of Christmas my true love sent to me 
a Parser for a Syntax Tree.

On the Second day of Christmas my true love sent to me 
Two passing tests, 
and a Parser for a Syntax Tree. ♬

We've had a visit from a ghost, the ghost of Christmas yet to come. It showed us a horrible future where projects we used and loved lay unmaintained because developers took from open-source without contributing. Projects were incompatible with new browsers and only supported old versions of the spec. Security errors stalked the land and many pagers summoned unhappy developers from their Christmas feasts.

Worst of all, we saw newbies slamming shut their laptops, cursing the day they heard the name of open-source.

Only you can prevent this coming to pass by giving back to the open-source community this Christmas!

Joining in is simple - visit 24pullrequests.com/contributing to find out how to contribute 24 pull requests between December 1st and December 24th. Your contributions can be tiny, as simple as fixing a typo, to something incredible. Speed up Rails. Document Express. Fix a bug that you reported.

If you need a reminder about what 24 Pull Requests is all about, it's a yearly initiate designed to let you give back little gifts of code over the holiday season. The link above can get you started contributing. But if you're not ready to start contributing just this moment you can spread the word! Tweet your friends to get them involved or say hi to us at @24pullrequests

Open source has given so much to all of us, it's time to give 24 little gifts back.

**Comment by cstrouse** [comment]
I'm in.

**Comment by minektur** [comment]
busiest time of the year for me.... I'll cheer you guys on.

**Comment by uberhacker** [comment]
@minektur: You would only need about 30 minutes per day.
