### ISSUE TITLE
Detecting already-installed packages

### ISSUE THREAD

**Issue by kablondino** [skycocker/chromebrew#1460]
I wish for chromebrew to manage all the packages it can. This includes ones that come already installed on Chrome OS, such as vim and wget. Is there something like this already implemented? And if not, is it possible?

**Comment by uberhacker** [comment]
@kablondino: We already have packages for vim and wget.  There are a few other packages that have updated versions of commands that ship with Chrome OS also.  Some that I can think of off the top of my head include coreutils, curl and iptables.  If you know of others that are missing, please submit a pull request.  Adding new packages is easy.  We have documented the process in the [wiki](https://github.com/skycocker/chromebrew/wiki).

**Comment by kablondino** [comment]
Yes, I understand that chromebrew also has these packages, but that's not the issue.

Let me give you an example. Chrome OS comes default with vim version 7.4.712. I install vim with crew, and it displays that it installed version 8.0-1. Opening vim, or typing "vim --version" still displays the older version. This indicates to me that crew installed a separate version elsewhere. I imagine this would occur for other already-installed packages.

So I pose the question again: is there a way for chromebrew to detect which packages are already installed by default by Chrome OS and subsequently manage them?

**Comment by uberhacker** [comment]
If you are not seeing the Chromebrew version of vim, that likely means your `/usr/bin` path is found before `/usr/local/bin`.  What is the output of `echo $PATH`?

**Comment by kablondino** [comment]
echo $PATH gives the following:
/usr/local/bin:/usr/bin:/bin:/opt/bin

**Comment by uberhacker** [comment]
What is the output of `which vim`?

**Comment by kablondino** [comment]
which vim gives
/usr/bin/vim

**Comment by kablondino** [comment]
`crew files vim` gives around 1400 lines, most of which start with "/usr/local/share/vim/vim80/..."
A few of the lines at the top are different directories.

I definitely have the Chromebrew version installed, since I can open in by explicitly running the binary "/usr/local/bin/vim"

**Comment by uberhacker** [comment]
That is strange because `which vim` should output `/usr/local/bin/vim` based on your PATH.  Try exiting crosh and then start a new session.  See if that makes a difference.

**Comment by kablondino** [comment]
Ah yes, restarting the session did change the `$PATH`. It correctly now opens the crew installed one.

However, the old binary is still there, in /usr/bin/vim. Therefore, there are two installed versions. Practically, this is obviously not a problem anymore, but theoretically shouldn't Chromebrew look into taking this into account.

**Comment by uberhacker** [comment]
Great, glad it was only a corrupt shell session.  The problem with managing the Chrome OS installed version is that directory is mounted read-only.  This is actually a good thing because it means you cannot corrupt the original version.  If you want to return to the shipped version, you can simply uninstall the Chromebrew package.

**Comment by kablondino** [comment]
Good point, thank you. I guess I have to remember to restart the session.
