### ISSUE TITLE
anyone use virtulization and run chromium os images for archs other than x86_64?

### ISSUE THREAD

**Issue by minektur** [skycocker/chromebrew#1488]
I know you can use cloudready to get pretty close to a chromeos environment for x86_64, but is anyone using any emulators/virtualizaiton to try and run chromium on the other arches chromebrew supports?  

If it were possible to do so.... then we could have some CI/automated-build-test stuff set up...  

I'm looking for some automated build/test options other than buying a bunch of used chromebooks and manually testing on each...

**Comment by uberhacker** [comment]
@minektur: I have set up i686 in VMWare Workstation Player.  You can grab the image here: https://github.com/crosbuilder/CustomBuilds/releases.
