### ISSUE TITLE
vim 7.4.712

### ISSUE THREAD

**Issue by dantrevino** [skycocker/chromebrew#1509]
Installation of vim says it will install 8.0, but when I look at :version I see version 7.4.712.

## Versions and system information
chromebrew: `crew --version` = 0.4.3

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4446936
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=77
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R62-9901.77.0
CHROMEOS_RELEASE_BUILD_NUMBER=9901
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=62
CHROMEOS_RELEASE_DESCRIPTION=9901.77.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9901.77.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9901.77.0
Model: YOUR MODEL HERE

Architecture: `uname -m`
x86_64
## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
Hey @dantrevino: You might try `crew update` followed by `crew upgrade vim`.  The latest version is `8.0.586`.

**Comment by uberhacker** [comment]
@dantrevino: Are you still having an issue with the vim version?

**Comment by uberhacker** [comment]
You might try `rm /usr/local/lib/crew/packages/vim.rb` followed by `crew update`.  Sounds like you have a problem with the `crew update` command.  Permissions maybe?

**Comment by uberhacker** [comment]
PR #1545 should resolve this issue.
