### ISSUE TITLE
git package fails to create /usr/local/bin/cc symlink

### ISSUE THREAD

**Issue by trisk** [skycocker/chromebrew#151]
Excerpt from install script (same as `crew install git`):

```
Found git, version 1.8.4
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-03-04 15:06:41--  https://dl.dropboxusercontent.com/s/g3binxopw5nfky1/git-1.8.4-chromeos-i686.tar.gz?token_hash=AAEWnMNBfozSIzLD1unbYGJzT4FGkEfJmLFQ-3uzydfT_A&dl=1
Resolving dl.dropboxusercontent.com... 108.160.173.133
Connecting to dl.dropboxusercontent.com|108.160.173.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22832393 (22M) [application/octet-stream]
--2016-03-04 15:06:42--  https://dl.dropboxusercontent.com/s/g3binxopw5nfky1/git-1.8.4-chromeos-i686.tar.gz?token_hash=AAEWnMNBfozSIzLD1unbYGJzT4FGkEfJmLFQ-3uzydfT_A&dl=1
Reusing existing connection to dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 22832393 (22M) [application/octet-stream]
Saving to: 'git-1.8.4-chromeos-i686.tar.gz'

git-1.8.4-chromeos-i6 100%[========================>]  21.77M  1.05MB/s   in 25s    

2016-03-04 15:07:08 (891 KB/s) - 'git-1.8.4-chromeos-i686.tar.gz' saved [22832393/22832393]

Archive downloaded
Unpacking archive, this may take a while...
Installing...
Git installed!
ln: failed to create symbolic link ‘/usr/local/bin/cc’: Permission denied
Initialized empty Git repository in /usr/local/lib/crew/.git/
Updating origin
remote: Counting objects: 1122, done.
remote: Total 1122 (delta 0), reused 0 (delta 0), pack-reused 1122
Receiving objects: 100% (1122/1122), 200.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (616/616), done.
```

**Comment by lyxell** [comment]
Try this:
`user=$(whoami) && sudo chown -R $user:$user /usr/local`

**Comment by trisk** [comment]
A reasonable workaround would just be the create the `cc` symlink by hand; `/usr/local` should be owned by `root:root`.

**Comment by lyxell** [comment]
I have hard to imagine that you would run in to any errors if it's not, but if you're concerned about that you could just chown /usr/local to root after issuing the recursive chown.
```
user=$(whoami) && sudo chown -R $user:$user /usr/local
sudo chown root:root /usr/local
```

**Comment by skycocker** [comment]
@trisk does chowning `/usr/local` fix the issue? symlinking cc by hand isn't too smart in long term usage - crew probably won't be able to create/change any files

**Comment by trisk** [comment]
Cr/Chrome OS still has some security considerations of a multi-user system, so `/usr/local` shouldn't be writable by chronos because it's in the default PATH. crew correctly invokes `sudo` during the installation steps for other packages when started as a normal user, so it appears only the git package has this problem. (Not having the `cc` symlink doesn't appear to break anything using autoconf, either).

**Comment by lyxell** [comment]
@trisk Is this really something that would be meaningful in practice? If developer mode is activated, even the guest user has sudo-rights.

**Comment by lyxell** [comment]
Closing as resolved, please reopen if I'm incorrect.
