### ISSUE TITLE
libevent missing openssl dependency

### ISSUE THREAD

**Issue by trisk** [skycocker/chromebrew#152]
`crew install libevent` fails with:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c bufferevent_openssl.c  -fPIC -DPIC -o .libs/bufferevent_openssl.o
bufferevent_openssl.c:60:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
                         ^
```
Either the OpenSSL support should be disabled or `openssl` declared as a dependency for libevent.

**Comment by trisk** [comment]
It appears https://github.com/skycocker/chromebrew/pull/82 reverts to using system OpenSSL, but the header is still necessary for libevent in this configuration. `sudo crew remove openssl` fixes the runtime issue with `OpenSSL version mismatch. Built against 1000204f, you have 1000105f` afterward. The `libevent` package can't be built without `crew install openssl` though.

**Comment by minektur** [comment]
pull request #177 fixes this
