### ISSUE TITLE
trouble installing jdk8

### ISSUE THREAD

**Issue by theonlyDaBall** [skycocker/chromebrew#1526]
chromebrew: 0.4.3

ChromeOS: 63.0.3239.86

Model: Acer Chromebook 15 CB5-571

Architecture: x86_64

When I try to install jdk8 using crew install jdk8 I get this:

`jdk8: The JDK is a development environment for building applications, applets, and components using the Java programming language.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
version 8u152
Precompiled binary available, downloading...
curl: error while loading shared libraries: librtmp.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/crew:361:in `read': No such file or directory @ rb_sysopen - ./jdk8-8u152-chromeos-x86_64.tar.xz (Errno::ENOENT)
        from /usr/local/bin/crew:361:in `block in download'
        from /usr/local/bin/crew:354:in `chdir'
        from /usr/local/bin/crew:354:in `download'
        from /usr/local/bin/crew:606:in `install'
        from /usr/local/bin/crew:510:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:808:in `block in install_command'
        from /usr/local/bin/crew:804:in `each'
        from /usr/local/bin/crew:804:in `install_command'
        from /usr/local/bin/crew:854:in `<main>'`

I've looked at the previous issues with jdk8 but they didn't seem to be the same issue.

**Comment by uberhacker** [comment]
Hey @theonlyDaBall: Thank you for reporting your error.  This is related to #1501.  There is a pending PR #1505 which should fix your issue as well.  Keep barking loudly and the other collaborators @cstrouse @thedamian may merge it sooner rather than later. :)
