### ISSUE TITLE
Suggestion: Add redshift to packages

### ISSUE THREAD

**Issue by alexmigf** [skycocker/chromebrew#153]
Chrome OS doesn't have an f.lux or redshift good extension or app, and i prefer to use Chromebrew instead of crouton.

Will be good to have at least redshift included in the packages to people that work many hours in front of computer screens.

**Comment by kofdog** [comment]
+1

**Comment by krruzic** [comment]
I'm working on this but am having a problem with one of redshifts dependencies. `intltool` requires a perl module but the perl bundled with crew isn't configured to allow dynamic loading of modules. I tried compiling perl myself but didn't know how. If someone could do that this would hopefully be possible. Although I have a feeling it won't work anyway

**Comment by alexmigf** [comment]
What about f.lux or iris?

**Comment by krruzic** [comment]
k got a new perl by using linuxbrew (I actually suggest people just use that as it's easier and seems to work). I'll try compiling this again. I'll also check out flux

**Comment by krruzic** [comment]
like I thought, redshift won't work. If you have android apps try things like Twilight. It changes the screen colour but seems to act like a big window on top of everything. No click or touch events pass through it

**Comment by alexmigf** [comment]
Ok, thanks anyway for the efforts ;)

**Comment by lyxell** [comment]
Closing since Chrome OS doesn't use X window system, making building of redshift impossible.
