### ISSUE TITLE
vim 8.0.586 cannot find libperl.so

### ISSUE THREAD

**Issue by duckunix** [skycocker/chromebrew#1535]
## Description
vim cannot find libperl.so as it is not in the standard library paths

If you executed a specific command:
```shell
vim --version
```
Output:
```shell
vim: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: 0.4.3

ChromeOS: 
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_RELEASE_BOARD=peppy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=13
CHROMEOS_RELEASE_BUILDER_PATH=peppy-release/R64-10176.13.1
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.13.1 (Official Build) dev-channel peppy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=1
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_VERSION=10176.13.1
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.13.1

Model: Acer 720
Architecture: x86_64

## Addtional information
By running:
```shell
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib/perl5/5.26.1/x86_64-linux/CORE vim --version
```
It works.  So, a fix would be to add that to my bash profile, however that will break when perl gets upgraded next time

**Comment by uberhacker** [comment]
@duckunix: Thank you for reporting this issue.  It looks like vim needs some more work.  It also reports version 7.4.712 instead of 8.0.586.  I'll see if I can fix it in a bit.
