### ISSUE TITLE
JDK8 does not install correctly

### ISSUE THREAD

**Issue by Speenah** [skycocker/chromebrew#156]
Most of the error messages look like this:
`mv: cannot stat ‘/usr/local/tmp/crew//usr/local/opt/java/....’: No such file or directory`

Every now and then there's one like 
`mv: cannot move ‘/usr/local/tmp/crew//usr/local/opt/java/’ to ‘/usr/local/opt/java/java’: Directory not empty`

I'm assuming none of the files get moved properly since it's a long list of 'cannot stat' and 'cannot move' errors. At the end it still says JDK8 installed.

**Comment by JALsnipe** [comment]
Can reproduce on my Chromebook Pixel:

Version 49.0.2623.112 (64-bit)
Platform 7834.70.0 (Official Build) stable-channel link
Firmware Google_Link.2695.1.169

Looking into this...

**Comment by Speenah** [comment]
For clarification, I have an Acer C720 Chromebook.

Version 49.0.2623.112 (64-bit)
Platform 7834.70.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0

**Comment by bfayers** [comment]
@Speenah try `sudo crew remove jdk8` then try `crew install jdk8`

**Comment by Speenah** [comment]
I've done that a few times already. My guess is there's a mix up in the directory prefixes since there's two `/user/local/` directories concatenated together in the `mv` command.

**Comment by bfayers** [comment]
Yeah, I think ` ‘/usr/local/tmp/crew//usr/local/opt/java/’ ` is this issue here.

**Comment by spaceface777** [comment]
Same thing happens to me

**Comment by JALsnipe** [comment]
Is the bug where chromebrew builds the directory to unpack the tarball to?

    topdir = `tar -tf #{meta[:filename]} | sed -e 's@/.*@@' | uniq`.chomp!

**Comment by MaxPleaner** [comment]
same issue.

**Comment by lyxell** [comment]
Closing as resolved by #247.
Please reopen if I'm incorrect.
