### ISSUE TITLE
Chromebrew source location on private Dropbox

### ISSUE THREAD

**Issue by idvoretskyi** [skycocker/chromebrew#157]
When one is going to install the Chromebrew, it's sources are located on the Dropbox - https://github.com/skycocker/chromebrew/blob/master/install.sh#L35

I suppose, it's a bit insecure and may bring the issues to install Chromebrew if the Dropbox account is unavailable/closed/down etc.

What is the reason for this solution?

If there are no objections, I may start to work with source migrating to the original sources of applications.

**Comment by idvoretskyi** [comment]
@skycocker, I'd like to hear your point-of-view.

**Comment by ryanpcmcquen** [comment]
Also it would be great if the toolchain got an update. There are some things I want to bring to Chromebrew that will not work on the old version of GCC.

**Comment by skycocker** [comment]
@idvoretskyi would moving to [bintray](https://bintray.com/) be a good solution?

**Comment by ryanpcmcquen** [comment]
Is there a reason not to use GitHub? None of the files are that big, a separate `chromebrew-bin` repo would work well.

**Comment by skycocker** [comment]
@ryanmjacobs github is not a file hosting platform, and the fact that no files *yet* are that big doesn't mean there will never be such. Why would github be better than dropbox anyway?

**Comment by ryanpcmcquen** [comment]
Versioning. Looks more credible. It is also unlikely that toolchain files will ever get that big ... whatever _big_ means in this context.

Also the rest of chromebrew is already on GitHub, it makes the project more centralized. Should make collaboration easier than bintray.

**Comment by idvoretskyi** [comment]
@skycocker, well, bintray doesn't look like a bad solution (it is better than Dropbox, yes).

But I'd rather vote +1 for @ryanpcmcquen's proposal (GitHub).

**Comment by idvoretskyi** [comment]
@skycocker. Are there (on Dropbox) vanilla ruby packages placed or patched in some way?

**Comment by bfayers** [comment]
@skycocker @idvoretskyi @ryanpcmcquen Perhaps [https://git-lfs.github.com/](GIT-LFS) still hosted by github and still has versioning just meant for larger documents. [https://github.com/blog/1986-announcing-git-large-file-storage-lfs](More info in a Github blog post here.) Looks like every user and/or org has 1GB of free storage and 1GB of quota/month. You can easily buy more.

**Comment by skycocker** [comment]
@idvoretskyi built with the initial gcc/buildessential stack on Chrome OS with chromebrew, without any patches.

**Comment by lyxell** [comment]
@skycocker Could you provide information on how you built the initial gcc/buildessential stack?

**Comment by skycocker** [comment]
@lyxell sure. Used crouton to start ubuntu, compiled gcc/buildessential, extracted the files to chrome os, then used them to compile gcc/buildessential on chrome os itself, then compiled the final version again on chrome os.

**Comment by bfayers** [comment]
@skycocker On the install script it installs a few things,  which are the important ones? (Trying to make crew work on arm) Also is crouton compiling a better idea than cross compiling in an Ubuntu vm.

**Comment by ryanpcmcquen** [comment]
@skycocker any idea if doing the compiling under CloudReady would work? I do not have access to a _real_ Chromebook ... Also, did you actually compile all of `build-essential`, or just `apt-get install` it?

**Comment by lyxell** [comment]
I've been trying to compile build-essential for ARM by cross-compiling via docker. GCC works via this method, but glibc will unsurprisingly produce a segmentation fault
https://gist.githubusercontent.com/lyxell/6f544b2c63f5b0fe33820a0617f6d9c9/raw/350acc6ed3dc88c48897c3a65ae5edd5b0aad095/Dockerfile
Does anyone have an idea on how to make glibc compatible with the target system by cross-compiling?

**Comment by bfayers** [comment]
@lyxell not sure about glibc, however if you can upload the binaries for amv7l, that'd be great and I can take a look.

**Comment by lyxell** [comment]
@bfayers Sure, which binaries do you want? Could you provide your full output of `uname -a`?

**Comment by ryanpcmcquen** [comment]
@lyxell, I thought from my LFS days that `gcc` and `glibc` both had to be compiled _twice_ to function properly ... are you doing that?

**Comment by lyxell** [comment]
@ryanpcmcquen Yes, the native compiler builds a cross compiler which builds the native compiler for the host.

**Comment by ryanpcmcquen** [comment]
@lyxell, but does the cross compiler need to be built twice?

**Comment by lyxell** [comment]
@ryanpcmcquen Yes, see the source provided in my original comment.

**Comment by bfayers** [comment]
@lyxell Sure can! Linux localhost 3.8.11 #1 SMP Wed Apr 20 16:24:29 PDT 2016 amv7l ARMv7 Processor rev 4 (v71) SAMSUNG EXYNOS5 (Flattened Device Tree) GNU/Linux

**Comment by ryanpcmcquen** [comment]
@lyxell, thanks! Your method is awesome and should also be used for the Intel toolchain.  :-)

**Comment by jam7** [comment]
Are we going to move binaries to somewhere more comfortable than dropbox?  As discussed here, #157, and #268.  Also related to #162.

When @thedamian made release 0.4.1, I was thinking we are going to move binaries to somewhere also with "0.4.1" release tag, but it doesn't happen.  I made helper script at #343 for the case we choose github.com for binary release files hosting.

This is not offense, I'm just wondering where we are going to.

**Comment by uberhacker** [comment]
What is wrong with storing all the binaries right here?  Of course, we would also want to give users the option to install the package binary or compile from source if they wish.

**Comment by cstrouse** [comment]
Can we close this now that we're on Bintray?
