### ISSUE TITLE
Can chromebrew make my ChromeOS more all-purpose?

### ISSUE THREAD

**Issue by willardthor** [skycocker/chromebrew#1588]
## Description

I am looking into ways to make my Chromebook a little more all-purpose. The chromebrew package manager sounds like an ideal fit for this. I am writing here to ask you guys a few questions, to gauge the suitability of using chromebrew to address my needs (I'll outline where I am coming from at the end of this message).

(Note: While I've used Linux for over 10 years, I am not a Linux hacker, so in case these questions sound naive, please bear with me)

1) Sandboxing?    
    
Where does chromebrew install packages? Does it put files in the same location that Chrome OS already stores its pre-installed applications (e.g. /usr/share and similar locations), or does it put files in some more local directory? If the former, could my Chrome OS break completely (e.g. requiring a powerwash) when Google ships out an update and asks me to restart to obtain them?

2) Graphical applications?    
    
I see wine, xwayland, and other graphics-relevant packages; can I install and run graphical applications (using Wayland or X) using chromebrew?

3) New packages?    
    
Say I wish to do something obscure on a whim, like install ghc, coqide, gimp, or steam. There are no packages for these applications. What do I need to do to install these applications and to make them work?

Kind regards,
Willard

P.S.: Here's where I am coming from. 

I am aware of [crouton](https://github.com/dnschneid/crouton), which installs Ubuntu in a chroot.

However, to run graphical applications with 3D hardware acceleration, an X server needs to be started. While acceptable, this feels silly, since Chrome OS already has Wayland built-in (this is said with all due respect to the crouton maintainers, who have done a fantastic job to make this work).

I am aware of [crouton-fedora-wayland](https://github.com/nmilosev/crouton-fedora-wayland), which modifies crouton to run Fedora and to use Wayland to manage graphical applications.

However, while I can easily get used to using Fedora, crouton-fedora-wayland seems much less maintained and stable than crouton, so I'm concerned that my chroot will suddenly break with no fix in sight (this happened to my [chroagh](https://github.com/drinkcat/chroagh) on an older Chromebook).

If I can install the few applications I need without a chroot (using chromebrew), that, to me, sounds ideal. Otherwise, I'll likely try out crouton-fedora-wayland and hope for the best.

## Versions and system information

Model:
Asus C302CA-GU003-OSS

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4510202
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_RELEASE_BOARD=cave-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=22
CHROMEOS_RELEASE_BUILDER_PATH=cave-release/R64-10176.22.0
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.22.0 (Official Build) beta-channel cave 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=10176.22.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.22.0

Architecture:
x86_64

## Addtional information

---

## That's it

**Comment by uberhacker** [comment]
@willardthor: All valid questions.  I'll try and answer the best I can.

1. Sandboxing?

Chromebrew installs all packages in separate and isolated locations within /usr/local.  The nice thing about Chromebooks is they protect the factory installed core assets in read-only directories that cannot be modified by the typical chronos user.  Chromebrew does have packages that override the defaults with newer versions such as curl, wget, coreutils and iptables, but these packages can be uninstalled cleanly and allow you to return to the untouched factory installed versions.

2. Graphical applications?

The GUI is currently a work in progress, so at the moment, Chromebrew only works with command line programs.  See issue #889.

3. New packages?

Check out [CONTRIBUTING.md](https://github.com/skycocker/chromebrew/blob/master/CONTRIBUTING.md) and this [wiki](https://github.com/skycocker/chromebrew/wiki/Creating-a-package) article.

Hopefully, that answers your questions adequately.  Let me know if you need more info.
