### ISSUE TITLE
Dedicated server space

### ISSUE THREAD

**Issue by drbree82** [skycocker/chromebrew#162]
Hi all,

Chromebrew is a cool project and I love it/want to see it as a more solid replacement for crouton based linux installs.

Would there be any benefit to setting up a dedicated server/mirror network? I have not really poked through the code, but I noticed that everything is ruby script with wget dragging files off dropbox. While this is an awesome start, would it be better for consistency if there was a dedicated server somewhere? Would this mean that we could then run something like yum, dnf or apt-get style pulls, instead of wget from dropbox accounts?

If this is a path the project wants to go down, I'd be happy to do my bit. I have an "All you can eat" VDSL internet connection which I run a ddns service through portforward to. It's not much, but I would be happy to chuck a TB of storage up for the project. 
I get 8MB/s upload on it. I'd be happy to offer 20% of this speed if it helps.

However, I am based in New Zealand so this may only help those based in NZ or Australia. However, if others wanted to jump on board around the world, and someone wanted to code the package manager to use SFTP or SCP or something, then I'd be happy to help where I can. Unfortunately I can only code java at the moment (badly) and would have to learn ruby.

**Comment by Alanaktion** [comment]
I've got a few unmetered 1 Gbps dedicated servers in Canada I'd be happy to use to mirror things as well.

**Comment by finwo** [comment]
I still have some servers running in the Netherlands ( 1Gbps, unlimited traffic ). Volunteering as possible mirror here.

**Comment by uberhacker** [comment]
Closing since Bintray has agreed to sponsor this project.
