### ISSUE TITLE
Elixir crashing on fresh pixelbook/chromebrew install

### ISSUE THREAD

**Issue by kaiyote** [skycocker/chromebrew#1620]
## Description
On a brand new Pixelbook (i5, 256GB ssd), having just enabled Developer mode and installed chromebrew, then elixir, Elixir crashes whenever I try to run it. Erlang runs fine, however.

```shell
crew install elixir
```
```shell
elixir: Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
http://elixir-lang.org/
version 1.5.2
The following packages also need to be installed: 
erlang 
Do you agree? [Y/n] 
Proceeding...
erlang: Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
http://www.erlang.org/
version 20.1
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
Elixir installed!
```

And then when I run `elixir -v`:
```shell
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...
```
(an attempt to find the erl_crash.dump file never produces any results, so I'm not sure it actually exists)

## Versions and system information
chromebrew: 0.4.3

ChromeOS: 10032.75.0 (Official Build) stable-channel eve (Release Chrome Milestone = 63)

Model: Google Pixelbook 7A24G00VF5

Architecture: x86_64

## Addtional information
This issue sounds very similar to [this error](https://github.com/elixir-lang/elixir/issues/4092) (that was on Win10 w/ Chocolatey, but the scenario is very similar).

**Comment by uberhacker** [comment]
@kaiyote: Thank you for reporting this issue.  I'll look into this and see if I can reproduce and provide a fix, if possible.

**Comment by kaiyote** [comment]
Did some more poking around, seems like this might be an elixir/pixelbook issue instead. Installed erlang from source, tried doing the same for elixir and got the same error just trying to build it.

**Comment by ento** [comment]
I was seeing the same error on Pixelbook i7 and was able to work around it by editing /usr/local/bin/elixir and tweaking the code path the gets passed to Erlang:

```diff
--- elixir_original     2018-01-15 03:02:15.487906693 -0800
+++ /usr/local/bin/elixir       2018-01-15 02:55:43.735909048 -0800
@@ -124,4 +124,4 @@
   fi
 fi
 
-exec "$ERL_PATH" -pa "$SCRIPT_PATH"/../lib/*/ebin $ELIXIR_ERL_OPTIONS $ERL -extra "$@"
+exec "$ERL_PATH" -pa "$SCRIPT_PATH"/../lib64/lib/*/ebin $ELIXIR_ERL_OPTIONS $ERL -extra "$@"
```

Looking in /usr/local/lib64/lib, there seems to be only Elixir related directories:

```bash
$ ls /usr/local/lib64/lib/
eex  elixir  ex_unit  iex  logger  mix
```

I get the feeling this and the bin directory with Elixir-related executables should be nested under /usr/local/lib64/elixir, and /usr/local/bin/elixir (and other executables) should be symlinks to /usr/local/lib64/elixir/bin/* ..?

Debugging note:

- `erl_crash.dump` started getting written once I moved to the home directory. (type and execute `cd` in the shell)  I couldn't interpret its content though. Perhaps folks at elixir-lang can.
- I installed strace with `crew install strace` and ran it like `strace -f -o elixir.strace elixir -v`. At the end of the output file, there's a lot of `write` calls that write out the dump file traced, and just above that, there were traces of Erlang trying to find `elixir.beam` by trying various locations:
```
...
31148 open("/usr/local/bin/../lib/*/ebin/elixir.beam", O_RDONLY <unfinished ...>
31161 <... ppoll resumed> )             = 0 (Timeout)
31148 <... open resumed> )              = -1 ENOENT (No such file or directory)
...
31150 open("/usr/local/lib64/erlang/lib/stdlib-3.4.2/ebin/elixir.beam", O_RDONLY <unfinished ...>
31161 <... futex resumed> )             = 1
31150 <... open resumed> )              = -1 ENOENT (No such file or directory)
...
```
- Tried tweaking `PATH` as per https://github.com/elixir-lang/elixir/issues/4092, but to no success.
- Elixir itself must be telling Erlang where to find `elixir.beam`. `which elixir` says `/usr/local/bin/elixir` is the path of the executable, and at its very end, it surely specifies the ebin paths, but in the wrong location.
  - I had `crew install mlocate`, so `updatedb` followed by `locate elixir.bin` told me that it's at `/usr/local/lib64/lib/elixir/ebin/elixir.beam`.
- This is my first chromebook and I'm glad/grateful I have access to these familiar unix tools through chromebrew!

**Comment by uberhacker** [comment]
Hey @ento: Thank you for the detailed debugging output.  You have described your issue very clearly which should definitely help accelerating a solution.  Fortunately, elixir has an updated version so I'll try and fix these path issues on the next release.
