### ISSUE TITLE
Can't install Chromebrew - Checksums don't match

### ISSUE THREAD

**Issue by nicolas161** [skycocker/chromebrew#1624]
Hi,

I am using an ARM Chromebook, and some hours ago I started to get problems when trying to crew install any application. After downloading the binaries, Chromebrew threw a checksum error. I figured that something could be wrong with my Chromebrew, so I nuked my /usr/local folder and tried to install Chromebrew from zero again. But when I try to do it, I get this error:

> wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
> Password: 
> Creating new device.json...
> Downloading ruby...
> ######################################################################## 100.0%
> Verifying ruby...
> ruby-2.4.1-chromeos-armv7l.tar.xz: FAILED
> sha256sum: WARNING: 1 computed checksum did NOT match
> Verification failed, something may be wrong with the ruby download.

Why do I keep getting this warnings about the checksums?

Thanks,

Nicolás.

**Comment by uberhacker** [comment]
Sorry guys, I think this is bintray rate limiting the project.  Apparently, they want $150 / month so we can continue using their service.

**Comment by Church-** [comment]
And I just borked my download trying to upgrade and then spent time trying to figure out why it was broken... awesome.

**Comment by Church-** [comment]
@uberhacker So is their a service we can easily move this to? Because if not I can probably fund a bit of cash if it means getting my machine back up for work.

**Comment by uberhacker** [comment]
I just sent a message to their support.  Hopefully, they can reply back soon.  If worse comes to worst, we can just host the binaries here.

**Comment by Church-** [comment]
Noted. Hmm, might need to check on the bandwith for a few of my VPS's. What's the ultimate size of all the binaries you think?

**Comment by uberhacker** [comment]
Less than 1 gb and probably closer to 500 mb.  That includes the binaries for all 3 architectures.  Their policy is 1 tb / month of bandwidth and there is no freakin' way we used that much 6 days into the month.

**Comment by Church-** [comment]
Aye, so worst comes to worst. Let me know, I'll spin up a vps at prgrm.com and point my a sub domain at it, chromebrew.chatsubo.me for a temp fix if you lot want to? Or I could snag chromebrew.org off namecheap and point that at the vps. Thoughts?

**Comment by nicolas161** [comment]
Thank you very much for the quick response, @uberhacker.

If I were you I would just host the files on Github. It gives people unlimited bandwidth, so this would not happen again.

**Comment by uberhacker** [comment]
Let's wait and see what bintray has to say.  It might just be a glitch in their system.

**Comment by Church-** [comment]
Aye.

**Comment by uberhacker** [comment]
Here is the response from binary support:
```
Your account has been blocked due to exceeding the storage quota of 10 GB. We have unblocked Chromebrew and temporarily extended your storage limit to 12 GB.
Since it will revert to 10 GB soon, please delete any irrelevant content so you will not get blocked again.
```
I didn't think we uploaded that much so I'll work on reducing the size so we don't have this happen again.  With that said, the checksum mismatch issue should be resolved...for now.

**Comment by sedlund** [comment]
git bin is missing for me:

Downloading git...
+ curl -C - -# -L --ssl https://dl.bintray.com/chromebrew/chromebrew/git-2.14.1-1-chromeos-armv7l.tar.xz -o git-2.14.1-1-chromeos-armv7l.tar.xz
######################################################################## 100.0%
+ echo 'Verifying git...'
Verifying git...
+ sha256sum -c -
+ echo 8548a8273beeb7956fed40e5db078d624b3d0f9c7b5897980b31aaba5d0837b8 git-2.14.1-1-chromeos-armv7l.tar.xz
git-2.14.1-1-chromeos-armv7l.tar.xz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
+ case $? in
+ echo 'Verification failed, something may be wrong with the git download.'
Verification failed, something may be wrong with the git download.
+ exit 1
chronos@localhost /usr/local/tmp/crew $ ls
dest  git-2.14.1-1-chromeos-armv7l.tar.xz  ruby-2.4.1-chromeos-armv7l.tar.xz  usr
chronos@localhost /usr/local/tmp/crew $ **cat git-2.14.1-1-chromeos-armv7l.tar.xz 
The requested path was not found.**chronos@localhost /usr/local/tmp/crew $

**Comment by corenel** [comment]
@sedlund git binary on the server is now of version 2.15.1 (you could find at  https://dl.bintray.com/chromebrew/chromebrew)

For temperory fix, you could modify the url and checksum of `install.sh` to install.
I modified x86_64 part and put it in [gist](https://gist.github.com/corenel/fe6551068f8f53031498a63550b11555#L72-L73). Notice the line 72-73.

**Comment by uberhacker** [comment]
Sorry guys, I got a bit too aggressive cleaning up old binaries on bintray since I don't want them to rate limit us again.  The fix @corenel suggests is what we need to change to resolve this issue.   I'll submit a PR soon unless you would like to give it a try yourself @corenel.

**Comment by nicolas161** [comment]
The checksum of libssh2-1.8.0-chromeos-armv7l.tar.xz also gives an error.

**Comment by barrymichaeldoyle** [comment]
Why was this issue closed? Is it resolved? How do I get around it?

**Comment by uberhacker** [comment]
@barrymichaeldoyle: Did you try this yet?
```
$ sudo dev_install --reinstall -y
$ curl -Ls git.io/vddgY | bash
```

**Comment by Noisytoot** [comment]
# I also have a similar issue with the libssh2 download:
```
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.5.1-chromeos-armv7l.tar.xz: OK
Extracting ruby (this may take a while)...
Installing ruby (this may take a while)...
Updating version number of existing ruby information in device.json...
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.17.1-chromeos-armv7l.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Updating version number of existing git information in device.json...
Downloading libssh2...
######################################################################## 100.0%
Verifying libssh2...
libssh2-1.8.0-chromeos-armv7l.tar.xz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the libssh2 download.
```

**Comment by uberhacker** [comment]
@Noisytoot: What is your Chrome OS version?   There might be an issue with release 67.
