### ISSUE TITLE
shared library: libicuuc missing but required for R

### ISSUE THREAD

**Issue by zacharysang** [skycocker/chromebrew#1629]
## Description

After running `crew install r`, when running the `R` command, I am getting this error: 

If you executed a specific command:
command being run: ```R```

Output:
```/usr/local/lib64/R/bin/exec/R: error while loading shared libraries: libicuuc.so.60: cannot open shared object file: No such file or directory```

## Versions and system information
crew: `0.4.3`

ChromeOS: ```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4505339
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={7B2FC5AC-894A-5702-D00E-62E999F0AE22}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={7B2FC5AC-894A-5702-D00E-62E999F0AE22}
CHROMEOS_RELEASE_BOARD=asuka-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=75
CHROMEOS_RELEASE_BUILDER_PATH=asuka-release/R63-10032.75.0
CHROMEOS_RELEASE_BUILD_NUMBER=10032
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=63
CHROMEOS_RELEASE_DESCRIPTION=10032.75.0 (Official Build) stable-channel asuka 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10032.75.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10032.75.0```

Model: Dell Chromebook 13

Architecture: `x86_64`

I am not sure if this is a missing dependency? It looks like this package is not already included in chromebrew, but I am not sure if others have been able to use R without this by changing configuration or something?

**Comment by zacharysang** [comment]
I was actually able to solve this by running: `crew install icu4c`. I made a pull request to include this package as a dependency for R

**Comment by yeesterPlus** [comment]
update libicuuc

**Comment by satmandu** [comment]
Updating `icu4c` is a huge PITA. I was just looking into this yesterday. We need to update 46 packages that depend upon it.

The most annoying problem with `icu4c`, unlike most other libraries, is that newer versioned libraries are not backwards compatible with older versions of `icu4c`, so when you update `icu4c` you have to rebuild every single dependent package, or those break.

We don't yet have an automated build system to rebuild all dependent projects, so this all has to be done manually.
