### ISSUE TITLE
tmux install fails 

### ISSUE THREAD

**Issue by apathinwalking** [skycocker/chromebrew#163]
Here's what was output:

--2016-04-25 09:14:37--  http://downloads.sourceforge.net/tmux/tmux-1.9a.tar.gz
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: http://sourceforge.net/downloads [following]
--2016-04-25 09:14:37--  http://sourceforge.net/downloads
Resolving sourceforge.net... 216.34.181.60
Connecting to sourceforge.net|216.34.181.60|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/downloads [following]
--2016-04-25 09:14:37--  https://sourceforge.net/downloads
Connecting to sourceforge.net|216.34.181.60|:443... connected.
WARNING: cannot verify sourceforge.net's certificate, issued by '/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/publish [following]
--2016-04-25 09:14:38--  https://sourceforge.net/publish
Connecting to sourceforge.net|216.34.181.60|:443... connected.
WARNING: cannot verify sourceforge.net's certificate, issued by '/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/publish/ [following]
--2016-04-25 09:14:38--  https://sourceforge.net/publish/
Connecting to sourceforge.net|216.34.181.60|:443... connected.
WARNING: cannot verify sourceforge.net's certificate, issued by '/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 17367 (17K) [text/html]
--2016-04-25 09:14:38--  https://sourceforge.net/publish/
Connecting to sourceforge.net|216.34.181.60|:443... connected.
WARNING: cannot verify sourceforge.net's certificate, issued by '/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 17367 (17K) [text/html]
Saving to: 'tmux-1.9a.tar.gz'

tmux-1.9a.tar.gz       100%[=============================>]  16.96K  --.-KB/s   in 0.07s  

2016-04-25 09:14:38 (250 KB/s) - 'tmux-1.9a.tar.gz' saved [17367/17367]

Checksum mismatch :/ try again

**Comment by lyxell** [comment]
We should probably use https://github.com/tmux/tmux/releases instead of the current sourceforge link.

**Comment by dragon788** [comment]
@lyxell wget can follow redirects, but it doesn't do so unless you increase the --max-redirect from the default, which for security reasons is of course 0. Would that help at all?

**Comment by lyxell** [comment]
I guess it would, but it seems like a rather hackish solution, it would be better to properly fix what's broken.

**Comment by minektur** [comment]
the issue with wget and aws 403s is our usage of --content-disposition which the aws servers do not support.  removing --content-disposition fixes the download problem.

**Comment by minektur** [comment]
and pull 177 fixes tmux builds, and updates to the latest version

**Comment by skycocker** [comment]
@apathinwalking, @lyxell - should we consider it fixed by now?

**Comment by lyxell** [comment]
@skycocker Yes.
