### ISSUE TITLE
Setting up a real time community: revisted

### ISSUE THREAD

**Issue by Church-** [skycocker/chromebrew#1631]
So, has anybody given any thought towards setting up a community sub-reddit, irc channel, or slack? Seems like real time communication would be an effective way of communicating problems quickly, and discussion of features or requested packages as well. Thoughts?

**Comment by uberhacker** [comment]
We have a slack channel.   See https://github.com/skycocker/chromebrew/issues/857.  It might be a good idea to add a link to the homepage or wiki page also.  PRs definitely welcome.
