### ISSUE TITLE
Node.js without nodebrew

### ISSUE THREAD

**Issue by revolutionnaire** [skycocker/chromebrew#1633]
Would it be ok if there was also an option to install it without the version manager?

I want to make a pull request where in I revert the file `packages/node.rb` to commit: 
`e6e348f67c56923891de10fafea5a8d610c878d5`

Then, just update it to the latest LTS version?

**Comment by uberhacker** [comment]
@revolutionnaire: The problem with node and the reason we got rid of the package(s) was because it takes an eternity to compile and maintaining multiple versions was just not practical.  The nodebrew and nvm packages both provide binaries of any version you would want, including the latest lts version.  If you don't like nodebrew, you might want to check out nvm.  To install the latest lts version, simply execute `nvm install lts/carbon`.  This is a bit easier than nodebrew: `nodebrew install-binary 8.9.4`.  Let me know if you have any trouble installing either of these packages.
Thanks

**Comment by revolutionnaire** [comment]
I didn't say remove Nodebrew completely, though. I was just hoping that it would also be possible to install the latest Node JS without the use of Nodebrew.

**Comment by revolutionnaire** [comment]
I believe this is fascist behaviour. You're not giving users any options but to use Nodebrew. You simply closed the issue without even addressing it properly.

You know what I did? I checked out the file `node.rb` when it was switched to SHA256 and updated it to the current version with the corresponding SHA256. I was able to install it properly.

Additionally, I really don't understand why we have to fork it just to contribute when we can just submit pull requests.

Believe me, I've been through this when I started out in a software development company. I forked the the repository and every one laughed at me. I was embarassed and didn't know what was funny about it until I realized that what I did was like pirating the code into my own…much, much later on.

**Comment by uberhacker** [comment]
Dude, I'm about as far from fascist as anybody.  This is free software and you are welcome to fork and do whatever you want.  Just don't complain unless you are willing to help and do the work necessary to make this project better.  I explained my reasons why we will not be supporting node.  It's just too difficult to maintain and not necessary.  What is wrong with nodebrew or nvm?  Either of these methods is perfectly fine for installing binaries and it would be way more flexible than anything we ever did with Chromebrew.

**Comment by revolutionnaire** [comment]
I really get your point. Some people like to switch between different versions of Node JS. But, what I would like you to understand is that some people prefer not to. I'm not saying we remove Nodebrew.

I just want the option to install the Current version of Node without Nodebrew.

I've asked if I can make a pull request so I can merge the changes I've made to make that possible.

I apologize for calling you a fascist. Might have been a little harsh. Let me know how I can make it up to you. Maybe a bottle of beer or something—when we both have the time 😁

**Comment by uberhacker** [comment]
@revolutionnaire: No worries at all.  Another issue that we have is node binaries are huge.  Our current binary repository (hosted on bintray) is getting big and once we go over the 10 gb limit, hosting is no longer free.  If you want to help with the costs of going over the limit, we will gladly accept donations and free beer. :)

**Comment by revolutionnaire** [comment]
I'm not sure about that. This will cause conflict of interest on what I will be working on in the future, but beers are fine 😅

**Comment by revolutionnaire** [comment]
Is there an issue with using the distributed tarball [https://nodejs.org/dist/v10.15.0/node-v10.15.0.tar.xz](url)? I was able to install it on my Chromebook.

**Comment by JL2210** [comment]
@revolutionnaire Nope. That's what Nodebrew does, anyway. If you want to install `node` from source, just run `nodebrew install-source <version>`.
