### ISSUE TITLE
crew error

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1662]
I tried to upgrade some packages and got following error:

chronos@localhost / $ crew upgrade
Updating packages...
(i) python27: Python is a programming language that lets you work quickly and integrate systems more effectively.
https://www.python.org/
version 2.7.14
The following packages also need to be installed: 
bz2 sqlite gdbm zlibpkg 
Do you agree? [Y/n] y
Proceeding...
bz2: bzip2 is a freely available, patent free (see below), high-quality data compressor.
http://www.bzip.org/
version 1.0.6
Precompiled binary available, downloading...
Traceback (most recent call last):
        7: from /usr/local/bin/crew:854:in `<main>'
        6: from /usr/local/bin/crew:837:in `upgrade_command'
        5: from /usr/local/bin/crew:319:in `upgrade'
        4: from /usr/local/bin/crew:319:in `each'
        3: from /usr/local/bin/crew:323:in `block in upgrade'
        2: from /usr/local/bin/crew:516:in `resolve_dependencies_and_install'
        1: from /usr/local/bin/crew:516:in `ensure in resolve_dependencies_and_install'
/usr/local/bin/crew:516:in `chdir': No such file or directory @ dir_chdir - /usr/local/tmp/crew/ (Errno::ENOENT)

platform: acer 13 tegra k1 chromebook

**Comment by uberhacker** [comment]
Thank you for reporting this issue @lovedheart.  It appears there is an issue with the `bz2` binary.  You are running an `armv7l` system, correct?

**Comment by lovedheart** [comment]
@uberhacker   armv7l

**Comment by lovedheart** [comment]
@uberhacker I find that the directory /usr/local/tmp/crew does not exist.

I try to fix the crew code to check existence of the directory before do  Dir.chdir BREW_CREW_DIR

**Comment by uberhacker** [comment]
@lovedheart: That directory should always exist.  Did you run `dev_install` to clear things out?  Probably even better would be to create the directory if it doesn't exist.  But I don't think this logic should ever be needed.  Something out of the ordinary happened with your local crew install.

**Comment by lovedheart** [comment]
Where is that script? I only got the error today by installing or upgrading packages. How to uninstall crew cleanly? I will try a clean install.

**Comment by uberhacker** [comment]
You can wipe out crew completely with `sudo dev_install --reinstall -y`.

**Comment by lovedheart** [comment]
Extracting /usr/local/portage/packages/net-misc/dhcp-4.3.4.tbz2
Files downloaded, configuring emerge.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Emerge installation complete. Installing additional optional packages.
!!! PORTAGE_BINHOST unset, but use is requested.
emerge: incomplete set configuration, missing set(s): "selected", "system", and "world"
        This usually means that '/usr/share/portage/config/sets/portage.conf'
        is missing or corrupt.
        Falling back to default world and system set configuration!!!
Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "gmerge".

emerge: searching for similar names... nothing similar found.

**Comment by uberhacker** [comment]
I don't know what that is all about.  Try and reinstall crew anyway.

**Comment by lovedheart** [comment]
Is dev_install on system level?

**Comment by uberhacker** [comment]
Not sure what you mean by system level.  If you run `which dev_install`, it returns: `/usr/bin/dev_install`.

**Comment by lovedheart** [comment]
yeah. I mean is it safe to run this? In my case I guess the command does not run successfully.

**Comment by uberhacker** [comment]
It basically wipes out `/usr/local` and all subdirectories.  Probably what happened in your case was the emerge bootstrap failed.  I have never been able to get emerge working on any of my Chromebooks so it's essentially useless anyway.

**Comment by lovedheart** [comment]
@uberhacker OK. I reinstall crew nwo.
