### ISSUE TITLE
How to compile code with -j1 using crew?

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1666]
I tried to compile libomxil-bellagio. It has been shown that only "make -j1" works. How to compile code with single job. I am not much familiar with ruby.

**Comment by uberhacker** [comment]
@lovedheart: That is the correct way to prevent parallel builds.  What is your plan with all these additional library packages?

**Comment by lovedheart** [comment]
for mesa build on armv7l

**Comment by lovedheart** [comment]
I think it's useful to enhance crew like this:
crew install -j1  xxxx  to ensure only single core compilation.

**Comment by uberhacker** [comment]
OK great.  That is one of the packages that needs updated in #1585.  We can check that off the list once you submit a PR.

**Comment by uberhacker** [comment]
We could add that as an option but since we also have binaries, it might be better just to add the option in with the package.

**Comment by lovedheart** [comment]
Yeah I known. We could also ask the user to complie the code using -j1 or -jN, when no precompiled code is available. What do you think of it?

**Comment by uberhacker** [comment]
What is wrong with just putting the option in the package?  Or are you saying we should pass a variable to the package as a make option?  It might even be a good idea to parse any number of compile options added to `crew install ...`.

**Comment by lovedheart** [comment]
It is a good option!

**Comment by thedamian** [comment]
Just merged https://github.com/skycocker/chromebrew/pull/1677 to fix this issue
