### ISSUE TITLE
Crew issue for architecture check

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1672]
I try to build gobject_introspection, one of the packages for gtk build. I modified the script **gobject_introspection.rb** from flyingP0tat0

------------------------------------------------------------------------------------------------------------------------------

require 'package'

class Gobject_introspection < Package
  description 'GObject introspection is a middleware layer between C libraries (using GObject) $
bindings.'
  homepage 'https://wiki.gnome.org/action/show/Projects/GObjectIntrospection'
  version '1.52.1'
  source_url
'https://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.52/gobject-introspection-1.52.$
  source_sha256 '2ed0c38d52fe1aa6fc4def0c868fe481cb87b532fc694756b26d6cfab29faff4'

  depends_on 'glib'
  depends_on 'flex'
  depends_on 'bison'

  def self.build
    system './configure'
    system 'make'
  end

  def self.install
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
  end
end

------------------------------------------------------------------------------------------------------------------------------

When i began to use "crew install object_introspection", it showed that:

------------------------------------------------------------------------------------------------------------------------------

gobject_introspection: GObject introspection is a middleware layer between C libraries (using GObject) and language 
bindings.
https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
version 1.52.1
No precompiled binary or source is available for armv7l.

------------------------------------------------------------------------------------------------------------------------------

However I could build it from source successfully for armv7l. Maybe check the crew code to remove architecture check?

**Comment by uberhacker** [comment]
@lovedheart: Based on what I'm seeing from the code you pasted, it appears the source_url is missing the .tar.gz extension and an ending quote.  That might fix it.

**Comment by uberhacker** [comment]
Is this still an issue?

**Comment by lovedheart** [comment]
Yes

chronos@localhost /usr/local/lib/crew/packages $ crew -k install gobject_introspection
gobject_introspection: GObject introspection is a middleware layer between C libraries (using GObject) and language 
bindings.
https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
version 1.52.1
No precompiled binary or source is available for armv7l.

**Comment by uberhacker** [comment]
I'm thinking we should close this since the object_introspection package is not in the repo yet.  Once you fix things locally, then you can push a PR to add this package.
