### ISSUE TITLE
Fail to install libomxil_bellagio

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1675]
I got the error:
libomxil_bellagio failed to install: `make -j4 V=0 -j1 CFLAGS=-Wno-error=switch` exited with 2

It seems that we must force set  -j1 only for this package.    It should be fixed in #1666

**Comment by uberhacker** [comment]
@lovedheart: I think this change has already been merged into master.  Did you run `crew update` to update your local install?  Maybe you are working off an older copy of the package?

**Comment by uberhacker** [comment]
Is this still an issue?

**Comment by lovedheart** [comment]
Before I did that, I made the update

**Comment by uberhacker** [comment]
If you are sure you have the latest commits from master, go to your local cloned repo's packages directory and execute:
```
$ cp libomxil_bellagio.rb /usr/local/lib/crew/packages/
$ crew install libomxil_bellagio
```

**Comment by lovedheart** [comment]
It does not work. The problem is that we must remove -jN to make it work.

**Comment by uberhacker** [comment]
This is what we have in master now for the make line:
```
system "make", "-j1 CFLAGS=-Wno-error=switch"    # only -j1 possible (tested on armv7l)
```
Are you saying this doesn't work?

**Comment by lovedheart** [comment]
No working. I mean we must remove or enhance some feature to prevent compilation with multiple jobs in crew

**Comment by uberhacker** [comment]
The `-j1` option assures it operates on a single job.  This is not correct?

**Comment by lovedheart** [comment]
I mean the following code in package.rb should be modified:

  def self.system(*args)
    # add "-j#{CREW_NPROC}" argument to "make" at only compile-time
    if @in_build == true
      if args[0] == "make"
        # modify ["make", "args", ...] into ["make", "-j#{CREW_NPROC}", "args", ...]
        if @opt_verbose then
          args.insert(1, "-j#{CREW_NPROC}", "V=1")
        else
          args.insert(1, "-j#{CREW_NPROC}", "V=0")
        end
      elsif args.length == 1
        # modify ["make args..."] into ["make -j#{CREW_NPROC} args..."]
        if @opt_verbose then
          args[0].gsub!(/^make /, "make -j#{CREW_NPROC} V=1 ")
        else
          args[0].gsub!(/^make /, "make -j#{CREW_NPROC} V=0 ")
        end
      end
    end
    Kernel.system(*args)
    exitstatus = $?.exitstatus
    raise InstallError.new("`#{args.join(" ")}` exited with #{exitstatus}") unless exitstatus == 0
  end

**Comment by lovedheart** [comment]
I don't know quite about that. But if you see this code. It automatically adds -jN.  I made the compliation work **only** using -j1

**Comment by uberhacker** [comment]
We don't need to modify the code.  Just set the `CREW_NPROC` variable to 1 and you should be good.

**Comment by lovedheart** [comment]
I don't know how. I am not much familiar with ruby.

**Comment by uberhacker** [comment]
`$ export CREW_NPROC=1`
You can also put this in your `~/.bashrc` also but I wouldn't recommend it.

**Comment by lovedheart** [comment]
Is there a good way to put it in libomxil_bellagio.rb?

**Comment by uberhacker** [comment]
`system "make", "-j#{CREW_PROC}", "CFLAGS=-Wno-error=switch"`

**Comment by lovedheart** [comment]
But in this case you also get  make  -jN -j1 CFLAGS=-Wno-error=switch

**Comment by uberhacker** [comment]
What you have now is fine.  As long as it compiles cleanly, you don't need to worry about it.

**Comment by lovedheart** [comment]
I can't complie it..

**Comment by uberhacker** [comment]
Just remove the `-j1` option and try again.  That flag is optional anyway.

**Comment by lovedheart** [comment]
It fails

**Comment by uberhacker** [comment]
What is your error?

**Comment by lovedheart** [comment]
/libomxil-bellagio.lax/libomxcoreext.a/libomxcoreext_la-OMXCoreRMExt.o 
libtool: link: ranlib .libs/libomxil-bellagio.a
libtool: link: rm -fr .libs/libomxil-bellagio.lax
libtool: link: ( cd ".libs" && rm -f "libomxil-bellagio.la" && ln -s "../libomxil-bellagio.la" "libomxil-bellagio.la" )
make[3]: Leaving directory '/usr/local/tmp/crew/libomxil-bellagio-0.9.3.tar.gz.dir/libomxil-bellagio-0.9.3/src'
make[2]: *** [Makefile:627: all-recursive] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/libomxil-bellagio-0.9.3.tar.gz.dir/libomxil-bellagio-0.9.3/src'
make[1]: *** [Makefile:381: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/libomxil-bellagio-0.9.3.tar.gz.dir/libomxil-bellagio-0.9.3'
make: *** [Makefile:266: all] Error 2
libomxil_bellagio failed to install: `make -j4 V=0 CFLAGS=-Wno-error=switch` exited with 2

**Comment by uberhacker** [comment]
Try this:
```
$ cd /path/to/chromebrew/packages
$ rm -f libomxil_bellagio.rb
$ git pull origin master
$ crew update
$ cp libomxil_bellagio.rb /usr/local/lib/crew/packages/
$ crew install libomxil_bellagio
```
You should be getting the `-j1` option instead of `-j4`.

**Comment by lovedheart** [comment]
libomxil_bellagio failed to install: `make -j4 V=0 -j1 CFLAGS=-Wno-error=switch` exited with 2

**Comment by lovedheart** [comment]
What did you change?

**Comment by uberhacker** [comment]
I changed nothing.  This is your package.  Did you `export CREW_NPROC=1`?

**Comment by lovedheart** [comment]
It works with "export CREW_NPROC=1" and removing the -j1 in code

**Comment by uberhacker** [comment]
Let's just go with that then.  Did you want to commit another PR with the `-j1` removed?

**Comment by lovedheart** [comment]
Leave it alone. Maybe we enhance that first.

**Comment by thedamian** [comment]
Just merged https://github.com/skycocker/chromebrew/pull/1677 to fix this issue
