### ISSUE TITLE
CMP command request 

### ISSUE THREAD

**Issue by VitaliyKulikov** [skycocker/chromebrew#1681]
command `cmp` is used in `/usr/local/bin/autopoint` installed by `gettext` package

**Comment by uberhacker** [comment]
Welcome @VitaliyKulikov: Thank you for reporting this issue.  This means the `diffutils` package should be a dependency of `gettext`.  Try this and see if the issue is resolved:
```
$ vim (or nano) /usr/local/lib/crew/packages/gettext.rb
```
Add `depends_on 'diffutils'`
```
$ crew install gettext
```

**Comment by VitaliyKulikov** [comment]
@uberhacker thank you. 
btw: i am working on prepare build for `mc` (midnight commander). currently, have an issue with `cons.saver` ((
https://github.com/MidnightCommander/mc/commit/eef076cef654010dcf4313e595860b261886afc4#r27031550

**Comment by JL2210** [comment]
@uberhacker Can this be closed? `diffutils` is a core package.
