### ISSUE TITLE
Fix the certificates for OpenSSL

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#169]
Right now wget and similiar software which depends on OpenSSL will need the flag "--no-check-certificates" when the Chromebrew OpenSSL has been installed, this is because the Chromebrew OpenSSL can't find the certificates provided by Chrome OS. 

This can be solved by adding the symbolic link:
`sudo ln -s /etc/ssl/certs /usr/local/ssl/certs`
or the alternative workaround, copying the certificates via:
`sudo cp /etc/ssl/certs/* /usr/local/ssl/certs`

This should also help solving #163 and might help #69 and #57 

Should I create a pull request?

**Comment by dragon788** [comment]
I wonder if it would make more sense to use the system openssl and symlink it for tmux and libevent rather than installing a Chromebrew version.

**Comment by lyxell** [comment]
The system OpenSSL does not ship with the headers, so there should at least be a package for these.

**Comment by lyxell** [comment]
Closing in favour of #181
