### ISSUE TITLE
[python27,python3] pip/pip3 command not available from binaries

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1691]
This appears to be an "across the board" issue with all architectures.  If you install the package via source (aka `-s`), pip is available.

**Comment by skiman6010** [comment]
Was this issue present in earlier binaries or just these new 3.6.4 binaries?

**Comment by uberhacker** [comment]
@skiman6010: I'm not sure but I suspect the reason they didn't get picked up was they were never installed in `#{CREW_DEST_PREFIX}/bin`.

**Comment by beliefless-dogmasless** [comment]
With the 'Recent' Update, pip is 'no longer available', but I have not 'updated' Python from the Source(but from the Binary). So you have to download(/install) 'manually', pip:
aria2c -m 0 -s 50 -x16 https://bootstrap.pypa.io/get-pip.py;python get-pip.py
    https://pip.pypa.io/en/stable/installing/
