### ISSUE TITLE
How could I add gcloud?

### ISSUE THREAD

**Issue by jcoonrod** [skycocker/chromebrew#1702]
I suspect chromebrew could run gcloud, making my chromebook capable of deploying to Google App Engine. But how would I go about adding it to your package list?

**Comment by uberhacker** [comment]
Hey @jcoonrod: I assume you want `crew install google_cloud_sdk`?

**Comment by jcoonrod** [comment]
Ha! Yes! I didn't see it listed on the site but sure enough it's there! Thanks! The tricky part is hitting cntl-C on the long oauth2 url - it also crashes the running instance - is there an alternative copy/paste for shell? (I was able to get around it by manually typing in the authentication code)

**Comment by jcoonrod** [comment]
Ah - found the answer - ctrl-shift c or v. But now ... I want to clone a github repository and I don't see an obvious source code area and when I try to create one it says readonly file system. Where do I put local files?

**Comment by uberhacker** [comment]
You will have rw + exec to any location inside `/usr/local`, so if you created a directory something like `mkdir /usr/local/gcloud`, that would work.  ChromeOS "protects" user home directories and I'm guessing that is where you tried initially.

**Comment by jcoonrod** [comment]
Ahah! Thanks - ok, for those interesting in deploying to GCP from a chromebook, after installing gcloud there are a few more steps. (1) gcloud components update (it will load a bunch of stuff) and (2) gcloud beta deploy ./app.yaml --project=xxxxxx --version=1
For some reason gcloud deploy doesn't work for beta deploy does.
