### ISSUE TITLE
ldconfig destroys /usr/local/lib

### ISSUE THREAD

**Issue by minektur** [skycocker/chromebrew#171]
Might be related to issue #49 ...

I've been playing around with building a few things using the chromebrew tool chain.  (end goal:  lxc, gpg)

anything that installs a library and uses autoconf will eventually end up, as part of the install, calling libtool --finish   which, among other things will run '/sbin/ldconfig /usr/local/lib', which totally screws up the libraries replacing them with bogus or incorrect symlinks. 

for instance if you try an install 'libpipeline' (a pre-req for man_db)  as seen at

 http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.4.1.tar.gz

I've made myself a chronos-writable directory in /usr/local, I unpack it there and then run ./configure  and then make and then

sudo make install

Which copies all the libraries to /usr/local/lib and then eventually runs ldconfig.

At this point pretty much any binary that uses shared libraries installed in /usr/local/bin/ is horked - and even some system binaries.  As an example, 'ls' works, but 'ls -l' does not for some reason.  At first my only method of recovery was emptying /usr/local/ and re-bootstrapping chromebrew.  Eventually I discovered that I could just 'unset LD_LIBRARY_PATH' and then I could at least run commands again, and after MANY reinstalls discovered that I could just untar a pre-install tar backup of /usr/local/lib to get back to working again.
# Solution 1  (doesn't work)

I thought that just replacing /sbin/ldconfig with /usr/local/sbin/ldconfig would solve the problem.  The same problem happens.  Why is this?  I guess because /usr/local/sbin/ldconfig does the same wrong thing to the libraries there.
# Solution 2

edit configure to replace all references to ldconfig with a no-op  (in my case ':')  - this lets you at least install the libraries so that other things depending on them can find them at build time.
# Solution 3

choose a different --prefix= at configure time...

e.g. 
./configure --prefix=/usr/local/tmp/foo

Everything will get installed at that location, and then you can manually move it to /usr/local/\*  - which works for things that don't depend on where they live or have embedded paths in them.

What I really want is to know what the right solution to this would be.  Second, I'd love to have lxc working (without crouton) so that I could make a 'real' container like crouton, but with a different distro inside...  Initially discovered this ldconfig issue when trying to build gpg (which has 8 or so support libraries) because gpg is needed by lxc/lxd

**Comment by lyxell** [comment]
What happens if you remove /usr/local/sbin/ldconfig and configures libpipeline?

**Comment by minektur** [comment]
The binaries core-dump when run.  - I'll try removing /usr/local/sbin/ldconfig  and re-running the build/install.  I'm concerned that it will still find the one in /usr/bin/ which i can't remove.  Perhaps I should replace the one in /usr/local with a script that does nothing.... I'll experiment.

**Comment by lyxell** [comment]
Could this be because there's symlinks from `/usr/local/lib*` into `/usr/lib*` and `/lib*`? The current glibc is kind of hackish since there's a lot of shared libraries from glibc already on the OS natively which would get overridden if they were put in `/usr/local/lib*`.

**Comment by lyxell** [comment]
This would probably be solved by #185

**Comment by minektur** [comment]
Not sure this is an issue any more...
