### ISSUE TITLE
sudo/root needed at all?

### ISSUE THREAD

**Issue by minektur** [skycocker/chromebrew#172]
I've installed (manually) uninstalled chromebrew 30 or so times in the last couple days...  I've been wondering why chromebrew needs to use sudo for some commands.

Maybe it's just my lenovo n21 chromebook, but all of /usr/local starts out writable by chronos user.

If the binary bootstrap packages didn't install as root-owned, you could theoretically have everything in /usr/local owned by and writable by chronos.

Experimentally, after initial install, I  "cd /usr/local &&  chown -R chronos:chronos *"

I then removed the instances of sudo in /usr/local/bin/crew

and pretty much everything seems to work as normal/expected.  

on MacOSX the homebrew code uses sudo on initial install to set the right ownership/permissions of stuff in /usr/local/ to you, but from then on out you never run sudo again.  Would this be a good operating model for chromebrew?

**Comment by lyxell** [comment]
I agree totally with this.

**Comment by lyxell** [comment]
Closing since there's an active PR.
