### ISSUE TITLE
Add more package dependencies to Chromebrew "core"

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1742]
I wanted to open this discussion to talk about adding a few more packages to the base Chromebrew install.  The reason I want to introduce new dependencies is several packages require `autogen.sh` to generate a `configure` script.  Rather than add all these necessary dependencies in with each package, would it make sense to just have these packages available by default on a fresh Chromebrew install?

**Comment by lovedheart** [comment]
@uberhacker  It is meaningful to do that.   glib and gobject_introspection should be in the core, since the later compilation highly depends on these.

**Comment by skiman6010** [comment]
I think we should only install the necessary packages needed on a fresh install. It might just be me, but the less "bloat" installed against my will, the better. If `autogen.sh` can be installed later without any problems, I think that is the best way to go.

**Comment by uberhacker** [comment]
@skiman6010: The problem we run into is every package that requires `autogen.sh` needs a few extra dependencies to install without error.  I understand your point but there is a trade-off either way.  We could just include everything on a fresh Chromebrew install or require that every package include the extra dependencies.  The latter could get messy depending on how many packages require `autogen.sh`.

**Comment by skiman6010** [comment]
@uberhacker: So you're saying that `autogen.sh` has extra packages that would also need to be installed before `autogen.sh` could be installed? In that case, I agree with adding them to the fresh install.

**Comment by uberhacker** [comment]
Exactly.  See #1789.  If you can think of other dependencies needed for `autogen.sh`, please mention them in that PR.

**Comment by uberhacker** [comment]
Resolved by #1789.
