### ISSUE TITLE
[graphene] Dependency loop

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1765]
```
$ crew install graphene
(i) graphene: A thin layer of graphic data types
https://github.com/ebassi/graphene
version 1.6.0
```
Hangs indefinitely. Interestingly, if I remove the `gobject_introspection` dependency, it installs fine.

**Comment by lovedheart** [comment]
I tried to crew upgrade. It hangs as well

         34: from /usr/local/bin/crew:552:in `push_dependencies'
         33: from /usr/local/bin/crew:552:in `each'
         32: from /usr/local/bin/crew:554:in `block in push_dependencies'
         31: from /usr/local/bin/crew:552:in `push_dependencies'
         30: from /usr/local/bin/crew:552:in `each'
         29: from /usr/local/bin/crew:554:in `block in push_dependencies'
         28: from /usr/local/bin/crew:552:in `push_dependencies'
         27: from /usr/local/bin/crew:552:in `each'
         26: from /usr/local/bin/crew:554:in `block in push_dependencies'
         25: from /usr/local/bin/crew:552:in `push_dependencies'
         24: from /usr/local/bin/crew:552:in `each'
         23: from /usr/local/bin/crew:554:in `block in push_dependencies'
         22: from /usr/local/bin/crew:552:in `push_dependencies'
         21: from /usr/local/bin/crew:552:in `each'
         20: from /usr/local/bin/crew:554:in `block in push_dependencies'
         19: from /usr/local/bin/crew:552:in `push_dependencies'
         18: from /usr/local/bin/crew:552:in `each'
         17: from /usr/local/bin/crew:554:in `block in push_dependencies'
         16: from /usr/local/bin/crew:552:in `push_dependencies'
         15: from /usr/local/bin/crew:552:in `each'
         14: from /usr/local/bin/crew:554:in `block in push_dependencies'
         13: from /usr/local/bin/crew:552:in `push_dependencies'
         12: from /usr/local/bin/crew:552:in `each'
         11: from /usr/local/bin/crew:554:in `block in push_dependencies'
         10: from /usr/local/bin/crew:552:in `push_dependencies'
          9: from /usr/local/bin/crew:552:in `each'
          8: from /usr/local/bin/crew:553:in `block in push_dependencies'
          7: from /usr/local/bin/crew:119:in `search'
          6: from /usr/local/lib/ruby/2.5.0/find.rb:43:in `find'
          5: from /usr/local/lib/ruby/2.5.0/find.rb:43:in `each'
          4: from /usr/local/lib/ruby/2.5.0/find.rb:48:in `block in find'
          3: from /usr/local/lib/ruby/2.5.0/find.rb:48:in `catch'
          2: from /usr/local/lib/ruby/2.5.0/find.rb:64:in `block (2 levels) in find'
          1: from /usr/local/lib/ruby/2.5.0/find.rb:64:in `reverse_each'
/usr/local/lib/ruby/2.5.0/find.rb:67:in `block (3 levels) in find': Interrupt

**Comment by lovedheart** [comment]
Should remove depends_on 'gobject_introspection' in cairo.rb

**Comment by beliefless-dogmasless** [comment]
I suceeded to install 'graphene', by removing first util_linux, then install graphene, that install first util_linux.

**Comment by lovedheart** [comment]
@beliefless-dogmasless  What kind of error did you get if not removing util_linux? Did you try a fresh install for graphene?

**Comment by beliefless-dogmasless** [comment]
I told you now it works, I tried both binary and source, both work now, but first I had to remove util_linux. I wrote the problem somewhere, but I can't remember where(on github), it was a "libk" something.

**Comment by beliefless-dogmasless** [comment]
my bad, it was for gobject_introspection, I removed my comment.

**Comment by uberhacker** [comment]
Resolved.
