### ISSUE TITLE
GTK3 needs improvement

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1772]
I have tried to run gtk3-daemon, something works and something not. It needs more effort to improve it.

**Comment by lovedheart** [comment]
#2128

**Comment by uberhacker** [comment]
Latest gtk3 upgrade produces:
```
Performing post-install...
Error opening directory “/usr/local/tmp/crew/dest/usr/local/share/glib-2.0/schemas”: No such file or directory
gtk3 failed to install: `glib-compile-schemas /usr/local/tmp/crew/dest/usr/local/share/glib-2.0/schemas` exited with 1
```

**Comment by uberhacker** [comment]
Installing gtk3 from source on `i686` produces:
```
hecking for BASE_DEPENDENCIES... no
configure: error: Package requirements (glib-2.0 >= 2.49.4    atk >= 2.15.1    pango >= 1.37.3    cairo >= 1.14.0    cairo-gobject >= 1.14.0    gdk-pixbuf-2.0 >= 2.30.0) were not met:

Package 'xxf86vm', required by 'egl', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BASE_DEPENDENCIES_CFLAGS
and BASE_DEPENDENCIES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
gtk3 failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib --enable-broadway-backend --enable-x11-backend --enable-wayland-backend` exited with 1
```

**Comment by lovedheart** [comment]
I am trying the workaround

**Comment by uberhacker** [comment]
It appears gtk3 is missing 2 dependencies:
```
depends_on 'libxxf86vm'
depends_on 'libxrender'
```

**Comment by lovedheart** [comment]
i prefer to include xorg_lib

**Comment by uberhacker** [comment]
Would it make sense to include `system "glib-compile-schemas #{CREW_DEST_PREFIX}/share/glib-2.0/schemas"` in the `glib` package instead?

**Comment by lovedheart** [comment]
No. I dont' think so

**Comment by beliefless-dogmasless** [comment]
Hy,

Here is a list of 'some that works':
caja-connect-server
caja-file-management-properties
dconf-editor
gcr-viewer
geany
gentoo        # gentoo file manager
gtk3-demo
gtk3-demo-application
gtk3-icon-browser
gtk3-widget-factory
gtk4-demo
gtk4-demo-application
gtk4-icon-browser
gtk4-widget-factory
mate-about
mate-calc
mate-color-select
syncthing-gtk
      (weston-terminal)


Most Don't, "a" "Gtk-WARNING **: cannot open display:" of some sort, there are 'ambiguous message('on the net') about that'.
Still not sure, Plus I don't Understand why 'without Weston' installed, those program work. And I can't find 'someone to explain 'it to me''.

Plus there a LOT OF 'related problems' with gtk that come with it:
the gestion of clipboard, of the dconf, the ability to move the windows with the finger, make the icons(close/minimize buttons) work, the integration with the 'chromeos' shell.

I'm gonna try Qt, if It's easier, they are 'more logical people in it', gtk is 'Always a Mess'.
