### ISSUE TITLE
Is there a way to use aria2, instead of wget ?

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1779]
Is there a way to use aria2, instead of wget(to download packages) ?

**Comment by uberhacker** [comment]
The problem with aria2 is it doesn't support https and a lot of packages have those urls.  Otherwise, what is the advantage of using aria2 over wget?

**Comment by beliefless-dogmasless** [comment]
It does support https, I've got a shitty dsl connection, where I live, the 'only downloader' that works, and finally succeed to download small packages, by resuming the operation is aria2.

**Comment by uberhacker** [comment]
I meant the current package build doesn't support ssl.  See #1792.

**Comment by beliefless-dogmasless** [comment]
I am 'on the version 1.33.1-1', and it works perfectly well (I'm on arm).

**Comment by beliefless-dogmasless** [comment]
I Answer 'my own question', replacing curl  by aria2, in  /usr/local/lib/crew/packages/crew
Works 'pretty well'. 
- There are 2 lines' 'to change'.
