### ISSUE TITLE
[meson] can't install

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1785]
meson, is needed for meson > graphene > gtk3:

I've got a pip error, but the strange thing is that argument --root is used:

meson failed to install: `pip3 install --prefix /usr/local --root /usr/local/tmp/crew/dest meson` exited with 127

- Am I 'the only one' ?

PS: pip is up to date.

and, the second 'strange thing', is that meson, need (depends_on 'python3'), but when I try to install directly with pip install meson, it talks about python2.7

**Comment by lovedheart** [comment]
Hi, the problem is that the python27 and python3 binary are corrupted. You need to build python27 and python3 by yourself .

**Comment by beliefless-dogmasless** [comment]
Ö..K.
You mean by yourself, without 'using crew' ?

**Comment by lovedheart** [comment]
Using crew. Just add '#' or remove the related lines for binary.

**Comment by beliefless-dogmasless** [comment]
Ok I try (remove those things), but I have a shitty dsl connection, so it's gonna be long, I post a message when it's done.

**Comment by lovedheart** [comment]
Which chromebook do you have? x86, i686, or arm version?

**Comment by beliefless-dogmasless** [comment]
An arm.

**Comment by lovedheart** [comment]
It works for tegrak1 (Acer 13)

**Comment by beliefless-dogmasless** [comment]
Ok I also have a tegrak1 (cb5 311p).

**Comment by uberhacker** [comment]
@beliefless-dogmasless @lovedheart: Just so you know, you don't need to comment out the binaries in the package.  You can force a compile from source with `crew install meson -s`.

**Comment by lovedheart** [comment]
Thanks for the tip

**Comment by beliefless-dogmasless** [comment]
Yeah I know, I usually have that "-s" in bashrc by default for crew install.
Thanks uberhacker.

**Comment by beliefless-dogmasless** [comment]
@lovedheart :
Ok it Works(now), Thanks A Lot.
