### ISSUE TITLE
Package Flex-2.5.39 fails to download

### ISSUE THREAD

**Issue by Brunux** [skycocker/chromebrew#179]
Hi guys package [Flex](https://github.com/skycocker/chromebrew/blob/master/packages/flex.rb) fails to download due to ERROR 410: Gone.

So I just fix the sourcer now it works as before.

how can I push my changes to master branch?

Thanks

**Comment by thedamian** [comment]
Only @skycocker has merge capabilities. He'll do it soon.

**Comment by Brunux** [comment]
Great I'll make the PR for review.

**Comment by minektur** [comment]
out of curiosity, what are you using flex for?  <secretly hoping for a more recent gcc build>

**Comment by Brunux** [comment]
lol not happening now (gcc) but hopefully we will have pcaplib a few other libs and finally nmap

**Comment by hsharrison** [comment]
How did you get this to work without yacc? I tried changing the source_url, version, and source_sha1 fields, but it still needs yacc.

**Comment by Brunux** [comment]
Yep correct, like Lex = Flex you need to symlink those

**Comment by hsharrison** [comment]
I got it to work just by installing bison. Should I also be symlinking something?

**Comment by Brunux** [comment]
I guess it depends on the package that you are trying to build as a good practice you could symlink BSD style tools to GNU style tools but only if those are compatible like Bison and Flex vs Yacc and Lex respectively.

**Comment by lyxell** [comment]
Resolved.
