### ISSUE TITLE
Can't install glib-2.54.3

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1798]
/usr/bin/install -c -m 644 ./html/right.png
 /usr/bin/install -c -m 644 ./html/style.css
 /usr/bin/install -c -m 644 ./html/tools.html
 /usr/bin/install -c -m 644 ./html/up-insensitive.png
 /usr/bin/install -c -m 644 ./html/up.png
Traceback (most recent call last):
  File "/usr/local/bin/gtkdoc-rebase", line 28, in <module>
    from gtkdoc import common, config, rebase
  File "/usr/local/share/gtk-doc/python/gtkdoc/rebase.py", line 28, in <module>
    from six import iteritems, iterkeys
ImportError: No module named six
make[5]: *** [Makefile:1030: install-data-local] Error 1
make[5]: Leaving directory '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3/docs/reference/glib'
make[4]: *** [Makefile:772: install-am] Error 2
make[4]: Leaving directory '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3/docs/reference/glib'
make[3]: *** [Makefile:487: install-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3/docs/reference'
make[2]: *** [Makefile:487: install-recursive] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3/docs'
make[1]: *** [Makefile:1280: install-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3'
make: *** [Makefile:1746: install] Error 2
glib failed to install: `make DESTDIR=/usr/local/tmp/crew/dest install` exited with 2

**Comment by uberhacker** [comment]
Installed fine on `i686`.  You only tried arm?

**Comment by lovedheart** [comment]
It works fine on armv7l with a fresh crew

**Comment by beliefless-dogmasless** [comment]
I can't install that version, the previous one was working. I've got, a 'lot of warnings' about libtool, (I installed libtool again, but no changes) :

libtool: warning: remember to run 'libtool --finish /usr/local/lib'
...
libtool: warning: 'libglib-2.0.la' has not been installed in '/usr/local/lib'
...
libtool: warning: relinking 'libgmodule-2.0.la'
...
libtool: warning: relinking 'libgthread-2.0.la'
...
libtool: warning: relinking 'libgobject-2.0.la'
...
libtool: warning: './libgobject-2.0.la' has not been installed in '/usr/local/lib'
...
...
libtool: warning: '../gobject/libgobject-2.0.la' has not been installed in '/usr/local/lib'
libtool: warning: '/usr/local/tmp/crew/glib-2.54.3.tar.xz.dir/glib-2.54.3/glib/libglib-2.0.la' has not been installed in '/usr/local/lib'
...
libtool: warning: '../glib/libglib-2.0.la' has not been installed in '/usr/local/lib'

**Comment by uberhacker** [comment]
No worries @beliefless-dogmasless.  A binary will be available soon.

**Comment by beliefless-dogmasless** [comment]
No worry, I was going to roll back to the previous version. Anyway Thanks @uberhacker.

**Comment by beliefless-dogmasless** [comment]
By the way, the glib-2.52.3   'source' version, does not work neither for me (I'm on arm), the binary is ok.

**Comment by uberhacker** [comment]
You might try a fresh Chromebrew reinstall to see if that clears things up.

**Comment by beliefless-dogmasless** [comment]
What do you mean, by 'Chromebrew reinstall'

**Comment by uberhacker** [comment]
```
$ sudo dev_install --reinstall -y
$ curl -Ls git.io/vddgY | bash
```

**Comment by beliefless-dogmasless** [comment]
I can't remember have done a    dev_install
when I installed Chromebrew.

**Comment by uberhacker** [comment]
Probably not but this is how you would reinstall.

**Comment by uberhacker** [comment]
You can also Powerwash but that is a bit extreme.

**Comment by beliefless-dogmasless** [comment]
The last time I used that command, was before I knew crew, and it has the effect to wipe /usr/local/*    from memory. And there were, some crouton installation in it. Since Then, I warn 'people', to be careful, with that one.
