### ISSUE TITLE
[gusb] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1802]
`i686` error:
```
./configure: line 2969: syntax error near unexpected token `1.29'
./configure: line 2969: `GOBJECT_INTROSPECTION_CHECK(1.29)'
gusb failed to build: `./autogen.sh` exited with 2
```

**Comment by uberhacker** [comment]
It appears the issue on `x86_64` is gusb is looking in the wrong directory for libudev.la.  The correct directory is `/usr/local/lib64/libudev.la`.

**Comment by lovedheart** [comment]
It seems like to need gobject_introspection to build it.
