### ISSUE TITLE
Compiling to 'sbin/' should be linked to 'bin/' at /usr/local

### ISSUE THREAD

**Issue by Brunux** [skycocker/chromebrew#182]
Hi guys,

Yesterday I was compiling e2fsprogs #179 commit bf7e395 and since some binaries are call 'essentials'  they got install at /usr/local/sbin/ the issue here is that the $PATH for the non root users by default (/etc/profile) do not include /usr/local/sbin/.

So having said this, I want to check your thoughts about to make a core functionality in order to check for newly created files (after installation a package)  at  /usr/local/sbin/ to link those to /usr/local/bin/

or

At the installation process of chromebrew access /etc/profile and add /usr/local/sbin/ to $PATH (I think this is easiest and right way to do it)
Any thoughts?

**Comment by minektur** [comment]
Are you just saying that we should put everything in /usr/local/bin?  or that we should symlink?  or recommend to people to add /usr/local/sbin/ to their path?  Those are the three options, I think.

**Comment by Brunux** [comment]
Hi @minektur be honest

**Comment by minektur** [comment]
? what do you mean?
