### ISSUE TITLE
Unable to install sqlite - Checksum mismatch. :/ Try again

### ISSUE THREAD

**Issue by hakanu** [skycocker/chromebrew#1823]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
```bash
crew install sqlite
```

If you executed a specific command:
```shell
crew install sqlite
```

Output:
```shell
sqlite: SQLite is a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
http://www.sqlite.org/
version 3.20.1
Precompiled binary available, downloading...
######################################################################## 100.0%
Checksum mismatch. :/ Try again.
```

## Versions and system information
chromebrew: `crew --version`
0.4.3
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_RELEASE_BOARD=setzer-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=65
CHROMEOS_RELEASE_BUILDER_PATH=setzer-release/R64-10176.65.0
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.65.0 (Official Build) beta-channel setzer 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=10176.65.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.65.0

Model: HP

Architecture: `uname -m`
x86_64
## Addtional information
Mention things we might need to know. Like:
When I run sqlite3, it looks like it's already installed but throws this error.
`$ sqlite3`
`sqlite3: symbol lookup error: /usr/local/lib64/libreadline.so.6: undefined symbol: UP`

What I think needs to be done:
- just open sqlite3 console.

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by beliefless-dogmasless** [comment]
Have you tried to the 'source version'(instead of the binary):

crew install -s -v sqlite

**Comment by hakanu** [comment]
thanks for the reply.
Looking at the error, I think it's about my chromebook's libreadline installation rather than chromebrew. Thanks. 
 
```bash
crew install -s -v sqlite
(i) sqlite: SQLite is a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
http://www.sqlite.org/
version 3.21.0-1
Package sqlite already installed, skipping...
removed directory 'dest'
Sqlite installed!
$ sqlite3
sqlite3: symbol lookup error: /usr/local/lib64/libreadline.so.6: undefined symbol: UP
```

**Comment by uberhacker** [comment]
Thank you for reporting this issue @hakanu.  It appears sqlite is missing the readline package dependency.  This can be added on the next update.
