### ISSUE TITLE
[cbase]  can't install

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1824]
Cbase  is needed for  >misctools.

I have 'this message', Compiling it(I'm on Arm):

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wall -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I. -g -O2 -MT libcbase_la-strings.lo -MD -MP -MF .deps/libcbase_la-strings.Tpo -c strings.c  -fPIC -DPIC -o .libs/libcbase_la-strings.o
strings.c: In function ‘C_string_valist2vec’:
strings.c:376:6: error: wrong type argument to unary exclamation mark
   if(!vp)
      ^
make[2]: *** [Makefile:676: libcbase_la-strings.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libcbase_la-sockctl.Tpo .deps/libcbase_la-sockctl.Plo
make[2]: Leaving directory '/usr/local/tmp/crew/cbase-1.3.7.tar.gz.dir/cbase-1.3.7/lib'
make[1]: *** [Makefile:297: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/cbase-1.3.7.tar.gz.dir/cbase-1.3.7'
make: *** [Makefile:226: all] Error 2
cbase failed to install: `make V=0 -j2` exited with 2

- Am I, the 'Only one' ?

PS: 
I tested the "cbase-1.3.5.tar.gz" version( found on https://osdn.net/projects/sfnet_slackbuildsdirectlinks/downloads/cbase/cbase-1.3.5.tar.gz/ ), It Is the same message

**Comment by uberhacker** [comment]
Thank you for reporting this issue @beliefless-dogmasless.  I assume this is happening on your arm system?  Can you please submit a PR with this new dependency when you get a chance?

**Comment by beliefless-dogmasless** [comment]
@uberhacker

Yes, it's on Arm. 
- What is "PR" ?

**Comment by uberhacker** [comment]
@beliefless-dogmasless: PR means Pull Request.  It might be time to learn. :)

**Comment by beliefless-dogmasless** [comment]
@uberhacker

Thanks, English is not 'my mother tongue'.

I can do a PR of cbase, but the version available on site ( http://www.hyperrealm.com/packages/cbase-1.3.7.tar.gz ), is the latest, maybe it's only an "arm problem", or my configuration 'is faulty'. So, I don't see the advantage of it, is it, for some 'administrative purposes'?

**Comment by beliefless-dogmasless** [comment]
Ok, I will, I left some message to the developer.

**Comment by lovedheart** [comment]
error is similar to [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=437289](url)

**Comment by beliefless-dogmasless** [comment]
Yes, I 'Checked', it's 'Quite a recurrent Message', but I can't seem to find the Solution Behind It.

**Comment by beliefless-dogmasless** [comment]
Ok, I Managed 'How to do it', you need to remove those lines, from /lib/strings.c :  

  if(vp)
    return(NULL);

* that if 'thing' is no needed.

Then I Removed, 'the need' of cbase for misctools:
removing that line, from /usr/local/lib/crew/packages/misctools.rb: 

depends_on 'cbase'

   - Then, the 'misctools', Compile Itself.

NOW, for the Pull Request, I don't Know How to Do:
- because, if you compile 'without cbase', I don't know if it works(I have not tempted to remove that dependency 'first')
- second, I don't know, if I need to send you the update 'file':	/lib/strings.c		
		or you do the modification.
Let me Know What you Decide,(how you proceed).

**Comment by lovedheart** [comment]
You need to just replace if(!vp) to if (&vp == NULL)  in strings.c

**Comment by beliefless-dogmasless** [comment]
With 'that':     (&vp == NULL) 
I still have the error  ( used struct type value where scalar is required )

**Comment by lovedheart** [comment]
if (&vp == NULL)
return(NULL)

**Comment by beliefless-dogmasless** [comment]
You,re Right, it Works too, with:

if (&vp == NULL)
return(NULL)
