### ISSUE TITLE
Enhance xorg

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1825]
I think it is beneficial to enhance xorg library. I am working on this.

**Comment by uberhacker** [comment]
I really appreciate all the hard work you have done to get the X window system working.  I just hope we can find a good home for all these new binaries!

**Comment by jrjaggari** [comment]
Looks like xauth is missing. I get the following error, startx: xauth: not found

**Comment by beliefless-dogmasless** [comment]
Yes it is missing:
https://www.x.org/archive/individual/app/xauth-1.0.10.tar.gz

**Comment by uberhacker** [comment]
Would you like to add the package @beliefless-dogmasless? :)

**Comment by beliefless-dogmasless** [comment]
The package works, but there is always something which I don't understand, why some gtk applications work and most don't with the "Cannot open display", I'm working on it. But until now, now luck. It's the same with guix(the package manager), packages install themselves, but there is a problem linking the 'interface'.

**Comment by uberhacker** [comment]
Have you looked at CloudReady yet @beliefless-dogmasless?  They include all the X Window libraries out-of-the-box.  You could probably examine the directory structure and determine what is missing.  See https://www.neverware.com/freedownload.

**Comment by beliefless-dogmasless** [comment]
http://www.linuxfromscratch.org/blfs/view/svn/index.html
propose all the X Window libraries out-of-the-box, too, but it's not about the libraries, it's about linking the interface. The last thing that pops up today was checking about iptables, if something blocks it, maybe some applications use "some services" to access the web and block their start, don't know, need to check that further.
