### ISSUE TITLE
Package maintainer 

### ISSUE THREAD

**Issue by Brunux** [skycocker/chromebrew#183]
Hi guys,

Since compiling package can be a little bit tricky and when someone manage to build a package successfully, sometimes with quick fixes or patches. I believe there should be a references for the "maintainer" in the package.rb so if somebody has a question about how to build or whatever, knows where to refer the question or whatever needs.

Any thoughts?

**Comment by minektur** [comment]
sounds like a good idea - then you know who to talk to about issues.... I guess you could get that same info from git commit logs.... hm...

**Comment by Brunux** [comment]
Yeah and I think that this could give some sort of responsibility to make a good package but I don't know if this is a good or bad thing for the maintainer

**Comment by minektur** [comment]
Nothing is preventing current package authors from putting their contact info in them now as a comment :).  I should go and do that with the few that I've submitted.

**Comment by skycocker** [comment]
what about some git blame usage?

**Comment by Brunux** [comment]
Yeah sure
