### ISSUE TITLE
[libxft] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1852]
```
checking for FREETYPE... configure: error: Package requirements (freetype2 >= 2.1.6) were not met:

Package 'libpng', required by 'freetype2', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

libxft failed to build: `./configure --prefix=/usr/local --libdir=/usr/local/lib` exited with 1
```

**Comment by lovedheart** [comment]
We should recomplie freetype again.

I have tried to compile it from source:

...
checking for ZLIB... no
checking for gzsetparams in -lz... yes
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
checking for BZIP2... no
checking for BZ2_bzDecompress in -lbz2... yes
checking bzlib.h usability... no
checking bzlib.h presence... no
checking for bzlib.h... no
checking for LIBPNG... no
checking for libpng-config... no
checking for HARFBUZZ... no
configure: creating ./config.status
config.status: creating unix-cc.mk
config.status: creating unix-def.mk
config.status: creating ftconfig.h
config.status: executing libtool commands
configure:

Library configuration:
  external zlib: no
  bzip2:         no
  libpng:        no
  harfbuzz:      no

I think these packages should be included. However there is a dependency loop:
freetype and harbuzz. I will check it further.
