### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1882]
Hy, I've got a " no implicit conversion of nil into String (TypeError) "
 when Crew Update,(complete message):
 
 Traceback (most recent call last):
        5: from /usr/local/bin/crew:854:in `<main>'
        4: from /usr/local/bin/crew:827:in `update_command'
        3: from /usr/local/bin/crew:258:in `update'
        2: from /usr/local/bin/crew:258:in `each'
        1: from /usr/local/bin/crew:262:in `block in update'
/usr/local/bin/crew:262:in `+': no implicit conversion of nil into String (TypeError)

[the line is 'about':        
puts @pkg.name + " could be updated from " + package[:version] + " to " + @pkg.version		]

I, also can't install, those packages (cairomm, atkmm, bmon, gusb, gobject_introspection), they hang a few minutes, then:
Message:
Traceback (most recent call last):
        12679: from /usr/local/bin/crew:854:in `<main>'
        12678: from /usr/local/bin/crew:804:in `install_command'
        12677: from /usr/local/bin/crew:804:in `each'
        12676: from /usr/local/bin/crew:808:in `block in install_command'
        12675: from /usr/local/bin/crew:507:in `resolve_dependencies_and_install'
        12674: from /usr/local/bin/crew:564:in `resolve_dependencies'
        12673: from /usr/local/bin/crew:558:in `expand_dependencies'
        12672: from /usr/local/bin/crew:552:in `push_dependencies'
         ... 12667 levels...
            4: from /usr/local/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
            3: from /usr/local/bin/crew:120:in `block in search'
            2: from /usr/local/bin/crew:104:in `set_package'
            1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require': stack level too deep (SystemStackError)

PS: I'm on Arm.
Manually those packages just install fine, I tried for bmon and its dependencies.
   			   
The other 'funny thing' was, before that impossibility to update(crew update), crew was saying that package need 'to be updated',
so one by one, I removed them, and install them again, but every crew update, it was about one package not 'a list of one'. I noticed, too, they were all about 1.0.3, even if the packages were already updated, I checked on a couple of packages.
Strange.
The 'other strange thing' is that some packages can be installed, but not those ones (cairomm, atkmm, bmon, gusb, gobject_introspection). Here is some of those, that I have updated 'one by one':

      ...
      groff could be updated from 1.0.3 to 1.22.3-1
      mandb could be updated from 1.0.3 to 2.7.6.1-2
      dmidecode could be updated from 1.0.3 to 3.1
      sysstat could be updated from 1.0.3 to 11.5.6
      cpustat could be updated from 1.0.3 to 0.02.03
      help2man could be updated from 1.0.3 to 1.47.4
      glibc223 could be updated from 1.0.3 to 2.23-2
      binutils could be updated from 1.0.3 to 2.25-3
      ...

**Comment by uberhacker** [comment]
@beliefless-dogmasless:  This has all the earmarks of the notorious dependency loop problem.  PR #1879 fixes an issue with `buildessential`.  My guess is something was corrupted during the update process.  I would recommend installing Chromebrew fresh and hopefully this will clear things up a bit.

**Comment by beliefless-dogmasless** [comment]
For informations:
if you remove 'libtool' dependency, trousers, intltool installs itself
if you remove 'trousers' dependency, gnutls installs itself
if you remove 'libconfuse' dependency, libnl3, bmon installs itself
if you remove 'atk' dependency, atkmm installs itself
if you remove 'cairo' dependency, cairomm, gobject_introspection installs itself

**Comment by beliefless-dogmasless** [comment]
Ok, it's about 'libuuid'
there is a package:				https://github.com/skycocker/chromebrew/pull/1524
but it's not in the list:			https://github.com/skycocker/chromebrew/tree/master/packages

so I added it(downloaded it and copied it in 	usr/local/lib/crew/packages )
but some others softwares must have installed it, because after some manipulations, I figured out it was installed

after some crew update, and crew upgrade(and crew remove/install libuuid and buildessential)
, I've got  the 'Your software is up to date.'

I just need to check with some new 'update packages', that it works(completly) again. I think there is an update 'coming' of imagemagick, then I will close the issue.

**Comment by uberhacker** [comment]
@beliefless-dogmasless: Package libuuid was removed in https://github.com/skycocker/chromebrew/pull/1874.  My guess is you have an older package installed with libuuid as a dependency.  Package `gptfdisk` maybe?

**Comment by beliefless-dogmasless** [comment]
Yes I have  gptfdisk.

**Comment by beliefless-dogmasless** [comment]
The update works. I have new packages to update. I close the Issue.
