### ISSUE TITLE
Imagemagick dependencies?

### ISSUE THREAD

**Issue by tomas** [skycocker/chromebrew#1887]
I'm not sure if this is on purpose, but both `imagemagick` and `imagemagick6` are missing dependencies for them to work. The former doesn't list [any dependencies](https://github.com/skycocker/chromebrew/blob/master/packages/imagemagick.rb) in the package definition, while [the latter](https://github.com/skycocker/chromebrew/blob/master/packages/imagemagick6.rb) lists some but not all of them (`libwebp` and `openjpeg` are still missing).

This results in nasty error messages when trying to run the `convert` command:

    $ convert  
    convert: error while loading shared libraries: libwebp.so.7: cannot open shared object file: No such file or directory
    $ crew install libwebp
    (...)
    $ convert 
    convert: error while loading shared libraries: libopenjp2.so.7: cannot open shared object file: No such file or directory

**Comment by uberhacker** [comment]
@tomas: Thank you for reporting this issue.  We'll make sure the next update includes these missing dependences.
