### ISSUE TITLE
Broken Dependency in SVN

### ISSUE THREAD

**Issue by HamishCPratt** [skycocker/chromebrew#1910]
Installing the subversion package does not require the installation of filecmd, however running svn without filecmd gives the following error:
`error: svn: error while loading shared libraries: libmagic.so.1: cannot open shared object file: No such file or directory` 

This was on Chrombrew 0.4.3, and simply running `crew install --keep filecmd` fixed all issues

**Comment by uberhacker** [comment]
Thank you for reporting this issue @HamishCPratt.  We will make sure the next svn update includes this dependency.

**Comment by thedamian** [comment]
Fixed in PR https://github.com/skycocker/chromebrew/pull/1912
