### ISSUE TITLE
clang: iostream file not found

### ISSUE THREAD

**Issue by lzfgnu** [skycocker/chromebrew#1915]
when i type "clang++ - o test test.cc" in command line 
i got 
test.cc:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.
could you help me to solve this problem.

**Comment by uberhacker** [comment]
@linzemin: Thank you for reporting this issue.  I can confirm this also.  Apparently, it looks like the problem is the `llvm_compiler_rt` package is not installing files.

**Comment by lovedheart** [comment]
@lzfgnu Can you test your program using llvm6 from #2263

**Comment by JL2210** [comment]
Have you tried including `<iostream.h>`? I know that is legacy on GCC, but in Clang, it may not be the case.
