### ISSUE TITLE
Creating Packages - source_sha256

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1919]
Hy,

I try to create some packages, why do I need to 'use', to make a sha256.
I tried http://www.xorbin.com/tools/sha256-hash-calculator (online), or the command line:
echo -n "https://github.com/transmission/transmission-releases/blob/master/transmission-2.93.tar.xz" | shasum -a 256

but Then, I have a "Checksum mismatch. :/ Try again." for both:
I also have 'a shitty connection' 'where I live'

Thanks.

**Comment by uberhacker** [comment]
@beliefless-dogmasless: The sha256 checksum is so you can ensure the download has completed successfully.  Since there is a mismatch, my guess is the download was interrupted and never completed.  Keep trying and eventually it should match.  A simple way to verify the checksum is below:
```
$ wget https://github.com/transmission/transmission-releases/blob/master/transmission-2.93.tar.xz
$ sha256sum transmission-2.93.tar.xz
```

**Comment by beliefless-dogmasless** [comment]
So 'sha256 checksum' function, in rb file, are there to check the validity of the weblink, or the validity of the size(/integrity) of the file ? Because, if I look your response, it's about the 'integrity of what's downloaded'.

**Comment by uberhacker** [comment]
Yeah, the checksum should verify the download completed successfully and the full contents of the file are available.

**Comment by beliefless-dogmasless** [comment]
Ok, Thanks @uberhacker.
