### ISSUE TITLE
google_cloud_sdk help broken.

### ISSUE THREAD

**Issue by skiman6010** [skycocker/chromebrew#1921]
The help files for google_cloud_sdk do not exist in the crew install.

```
$ gcloud --help
/bin/sh: 1: /usr/local/bin/less: not found
```

Looks like we'll need to move the files into `/usr/local/bin/less` and symlink them.

**Comment by uberhacker** [comment]
@skiman6010: The `less` package should be installed via Chromebrew "core".  Was it removed?

**Comment by skiman6010** [comment]
@uberhacker 

```
$ crew files less
(i) less: GNU less is a program similar to more, but which allows backward movement in the file as well as forward movement.
https://www.gnu.org/software/less/
version 487-1
/usr/local/bin/less
/usr/local/bin/lessecho
/usr/local/bin/lesskey
/usr/local/share/man/man1/less.1.gz
/usr/local/share/man/man1/lessecho.1.gz
/usr/local/share/man/man1/lesskey.1.gz
Total found: 6
```

Looks like it has been installed already. But I removed it and reinstalled it and everything works now. Another package that I needed to do that for. Looks like most of my core packages were installed incorrectly and are bugged.

**Comment by thedamian** [comment]
If this is true this is bigger than just the gcloud. I'll look into this. Can anyone else confirm this? can they install gcloud and see if they get the less error.

**Comment by skiman6010** [comment]
@thedamian Looks like it was an error with my crew install only. I've been having weird issues with the core packages that can be fixed by uninstalling and reinstalling. I forgot `less` was a core package. I should have closed this after I figured it out.
