### ISSUE TITLE
[libpng] gawk, is needed to Compile libpng as source

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1927]
Hy,

gawk, is needed(depedency) to Compile libpng as source.

**Comment by uberhacker** [comment]
Thank you for reporting @beliefless-dogmasless.  mawk doesn't work?  What is your error during compilation?  I assume this is an arm system?

**Comment by beliefless-dogmasless** [comment]
Yes, it's for arm, there's a "mawk" error message, if gawk is not installed, libpng can't compile.
