### ISSUE TITLE
Rb Filename Issue with "_"

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1929]
Hy,

There are packages with underscore, but every time I try to create a package(rb file) with underscore, I've got a (NameError):

crew search adw:

"Traceback (most recent call last):
        15: from /usr/local/bin/crew:854:in `<main>'
        14: from /usr/local/bin/crew:819:in `search_command'
        13: from /usr/local/bin/crew:819:in `each'
        12: from /usr/local/bin/crew:820:in `block in search_command'
        11: from /usr/local/bin/crew:129:in `regexp_search'
        10: from /usr/local/bin/crew:129:in `each'
         9: from /usr/local/bin/crew:129:in `block in regexp_search'
         8: from /usr/local/bin/crew:89:in `print_package'
         7: from /usr/local/bin/crew:119:in `search'
         6: from /usr/local/lib/ruby/2.5.0/find.rb:43:in `find'
         5: from /usr/local/lib/ruby/2.5.0/find.rb:43:in `each'
         4: from /usr/local/lib/ruby/2.5.0/find.rb:48:in `block in find'
         3: from /usr/local/lib/ruby/2.5.0/find.rb:48:in `catch'
         2: from /usr/local/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         1: from /usr/local/bin/crew:120:in `block in search'
/usr/local/bin/crew:105:in `set_package': uninitialized constant Adwaita_icon_theme (NameError)"

**Comment by uberhacker** [comment]
@beliefless-dogmasless: I have not experienced issues with underscores in any of the architectures (arm, i686 and x64_86).  Can you please provide more details and the specific packages that you have created that have this issue?  If you can please follow the issue template and provide details of your architecture also that would help us to troubleshoot your problem.

**Comment by beliefless-dogmasless** [comment]
@uberhacker 
Every time, I use(create) a package with "-" "_" or space, there is a problem with crew search:

/usr/local/bin/crew:105:in `const_get': wrong constant name Adwaita-icon-theme (NameError)

/usr/local/bin/crew:105:in `set_package': uninitialized constant Adwaita_icon_theme (NameError)

/usr/local/bin/crew:105:in `const_get': wrong constant name Adwaita icon theme (NameError)

- The Line105 is 'all about':
@pkg = Object.const_get(pkgName.capitalize)

**Comment by uberhacker** [comment]
I don't believe you can use dash (-) or space but underscore (_) should work.

**Comment by uberhacker** [comment]
Is this still an issue @beliefless-dogmasless?  I don't have this problem.

**Comment by beliefless-dogmasless** [comment]
@uberhacker 
I made a 'fresh install', yesterday, now it seems to work.
