### ISSUE TITLE
Harbuff Needs 'Six package' to Compile.

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#1934]
Harbuff Needs 'Six package' to Compile:

Hy,

Why not put, that 'six package' in the 'build essential':
Python->Pip->Six Package:

For pip:
curl -O https://bootstrap.pypa.io/get-pip.py;python get-pip.py

**Comment by uberhacker** [comment]
You mean `harfbuzz`?  We could probably make a case for the `setuptools` pip package as well.  Might make sense if these dependencies were packaged.  We don't want to install pip via `get-pip.py` since there is no version control and it would always install the latest version.

**Comment by beliefless-dogmasless** [comment]
Yes, excuse me, harfbuzz.

"We don't want to install pip via get-pip.py since there is no version control." Ok.
