### ISSUE TITLE
How can I install mysql client?

### ISSUE THREAD

**Issue by lovese** [skycocker/chromebrew#1937]
I find brew like this:
`brew install mysql --client-only --universal`
so I use:
`crew install mysql --client-only --universal`
It's right?

Thank you for you help!

**Comment by beliefless-dogmasless** [comment]
Try to see, first, if you can compile it.

**Comment by lovese** [comment]
You mean I can't compile it?

**Comment by lovese** [comment]
I want to know the author's answer. I can't try it. I don't know ChromeOS.

**Comment by lovese** [comment]
Does the crew through compile to install all software? Can it install software with binary files?

**Comment by lovese** [comment]
I want install MySQL-client with  binary files,but I don't know crew.

**Comment by lovese** [comment]
I try to install mysql-shell-1.0.11-linux-glibc2.12-x86-64bit.tar.gz ,but failed.

**Comment by lovedheart** [comment]
Use "crew search mysql" to see if it is supported in chromebrew. Or you can try to compile it from source.

**Comment by lovese** [comment]
```
chronos@localhost ~/Downloads $ crew search mysql
percona_server: Percona Server for MySQL® is a free, fully compatible, enhanced, open source drop-in replacement for MySQL that provides superior performance, scalability and instrumentation.
chronos@localhost ~/Downloads $ 
```
but it will install mysql-server

**Comment by uberhacker** [comment]
@lovese: The `percona_server` package will install both the server and client.  You don't need to execute the server and the client should work out-of-the-box.

**Comment by lovese** [comment]
I know，but I don't want to install server,because disk space is not enough

**Comment by uberhacker** [comment]
@lovese:
```

**Comment by lovese** [comment]
OK，I get it，thanks！
