### ISSUE TITLE
[libinput,libwacom] Unable to install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1956]
```
/bin/grep: /usr/local/lib/libudev.la: No such file or directory
/bin/sed: can't read /usr/local/lib/libudev.la: No such file or directory
libtool:   error: '/usr/local/lib/libudev.la' is not a valid libtool archive
make[2]: *** [Makefile:422: libwacom.la] Error 1
make[2]: Leaving directory '/media/tmp/crew/libwacom-0.28.tar.bz2.dir/libwacom-0.28/libwacom'
make[1]: *** [Makefile:461: all-recursive] Error 1
make[1]: Leaving directory '/media/tmp/crew/libwacom-0.28.tar.bz2.dir/libwacom-0.28'
make: *** [Makefile:370: all] Error 2
libwacom failed to build: `make V=0 -j1` exited with 2
```
Missing libudev dependency?

**Comment by lovedheart** [comment]
Which architecture?

**Comment by uberhacker** [comment]
All architectures.  Apparently, it's a case of missing a dependency.

**Comment by lovedheart** [comment]
I don't get any errors on armv7l

**Comment by uberhacker** [comment]
Did you try on a fresh Chromebrew install?

**Comment by lovedheart** [comment]
Befor I submit the PR, I try fresh install

**Comment by lovedheart** [comment]
Maybe try install eudev then compile it @uberhacker

**Comment by uberhacker** [comment]
That is my point.  Shouldn't those be dependencies so I don't need to do that?

**Comment by lovedheart** [comment]
I don't think this is a dependency.  see https://archlinuxarm.org/packages/arm/libwacom for arm version 
or  https://www.archlinux.org/packages/extra/x86_64/libwacom/  fox x86_64

**Comment by uberhacker** [comment]
Maybe this is a case where `eudev` is a missing dependency of `libgudev`?

**Comment by lovedheart** [comment]
libgudev depends on libsystemd, which outputs libudev.so

**Comment by uberhacker** [comment]
The original error indicates a missing `libudev.la`, not `libudev.so` so maybe that is only available in the `eudev` package?

**Comment by lovedheart** [comment]
eudev contains libudev.la and libudev.so
