### ISSUE TITLE
[recordproto] binary corrupted

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#1966]
The following packages also need to be installed: 
recordproto renderproto resourceproto scrnsaverproto trapproto videoproto windowswmproto xcmiscproto xf86driproto xf86vidmodeproto xf86rushproto xf86dgaproto xf86bigfontproto xineramaproto xproxymanagementproto libpciaccess libdrm xorg_proto libxext libxdamage libxkbfile wayland python27 libxshmfence mesa xcb_util 
Do you agree? [Y/n] y
Proceeding...
recordproto: The protocols for the X window system provide extended functionality for communication between a X client and the server.
https://x.org
version 1.14
Precompiled binary available, downloading...
Checksum mismatch. :/ Try again.

**Comment by uberhacker** [comment]
Thank you for reporting this issue @lovedheart.  Oddly enough, the binaries exist at bintray so apparently the sha256 checksums are incorrect.

**Comment by uberhacker** [comment]
@lovedheart: I just verified the sha256 checksum for arm and it's correct.  Did you try more than once.  Maybe a bad internet connection?
```
$ head -20 recordproto.rb 
require 'package'

class Recordproto < Package
  description 'The protocols for the X window system provide extended functionality for communication between a X client and the server.'
  homepage 'https://x.org'
  version '1.14'
  source_url 'https://www.x.org/archive/individual/proto/recordproto-1.14.tar.gz'
  source_sha256 '74fc0e8919f3c234848794f1ee266ba6d090f9b99fd65ab913c54ee3ad3ff377'

  binary_url ({
    aarch64: 'https://dl.bintray.com/chromebrew/chromebrew/recordproto-1.14-chromeos-armv7l.tar.xz',
     armv7l: 'https://dl.bintray.com/chromebrew/chromebrew/recordproto-1.14-chromeos-armv7l.tar.xz',
       i686: 'https://dl.bintray.com/chromebrew/chromebrew/recordproto-1.14-chromeos-i686.tar.xz',
     x86_64: 'https://dl.bintray.com/chromebrew/chromebrew/recordproto-1.14-chromeos-x86_64.tar.xz',
  })
  binary_sha256 ({
    aarch64: '9a678d4dbf0ab327462fea060cbbf9a32a06d6bc88385bf31b7e92b950ba9d13',
     armv7l: '9a678d4dbf0ab327462fea060cbbf9a32a06d6bc88385bf31b7e92b950ba9d13',
       i686: 'edc33d494671906c1e4bdafab208bb9c79850845685f366af43fdf076ddadd2a',
     x86_64: 'ba204da29b67fedd013f5156a557043f789e220b7321a7ea4d45dc1f60cfdec4',
$ sha256sum recordproto-1.14-chromeos-armv7l.tar.xz 9a678d4dbf0ab327462fea060cbbf9a32a06d6bc88385bf31b7e92b950ba9d13  recordproto-1.14-chromeos-armv7l.tar.xz
```

**Comment by lovedheart** [comment]
With a fresh crew install, it works now.
