### ISSUE TITLE
[gtk3] Unable to install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1974]
```
/bin/grep: /usr/local/lib/libdrm.la: No such file or directory
/bin/sed: can't read /usr/local/lib/libdrm.la: No such file or directory
libtool:   error: '/usr/local/lib/libdrm.la' is not a valid libtool archive
make[4]: *** [Makefile:1170: libgdk-3.la] Error 1
make[4]: Leaving directory '/usr/local/tmp/crew/gtk+-3.22.26.tar.xz.dir/gtk+-3.22.26/gdk'
make[3]: *** [Makefile:1652: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/gtk+-3.22.26.tar.xz.dir/gtk+-3.22.26/gdk'
make[2]: *** [Makefile:1089: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/gtk+-3.22.26.tar.xz.dir/gtk+-3.22.26/gdk'
make[1]: *** [Makefile:722: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/gtk+-3.22.26.tar.xz.dir/gtk+-3.22.26'
make: *** [Makefile:616: all] Error 2
gtk3 failed to build: `make V=0 -j2` exited with 2
```
This appears to be a case where `gtk3` is looking for `libdrm.la` in the wrong directory.  The correct location is `/usr/local/lib64/libdrm.la`.

**Comment by beliefless-dogmasless** [comment]
Hy, 

I don't know, I've 'just installed' the latest version  https://download.gnome.org/sources/gtk+/3.22/gtk+-3.22.29.tar.xz

and I have 'no problem' with the Installation'. I checked libdrm installed and I have 'the same version(2.4.89)'.

'By the way', the gtk3 rb file lacks in def self.build:

    system "sh autogen.sh"

**Comment by uberhacker** [comment]
@beliefless-dogmasless: The issue is specific to `x86_64` systems.  I could install fine on `arm` and `i686`.

**Comment by beliefless-dogmasless** [comment]
Yes, that's what I thought. Apparently, there 'a lot of them' on x86_64.
