### ISSUE TITLE
[gdb] unable to install

### ISSUE THREAD

**Issue by lzfgnu** [skycocker/chromebrew#1976]
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
config.status: creating Makefile
**gdb failed to install: `make V=0 -j4` exited with 127**

**Comment by uberhacker** [comment]
Thank you for reporting this issue @lzfgnu.

**Comment by skiman6010** [comment]
@lzfgnu what CPU architecture are you encountering this error on?

**Comment by blu** [comment]
On aarch64:

`g++ -x c++ -std=gnu++11 -g -O2   -I. -I. -I./common -I./config -DLOCALEDIR="\"/usr/local/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/.. -I./../readline/.. -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber  -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1  -I/usr/local/include/python2.7 -I/usr/local/include/python2.7 -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-narrowing -Wno-error=maybe-uninitialized  -c -o aarch64-linux-hw-point.o -MT aarch64-linux-hw-point.o -MMD -MP -MF ./.deps/aarch64-linux-hw-point.Tpo nat/aarch64-linux-hw-point.c
In file included from nat/aarch64-linux-hw-point.c:26:0:
/usr/local/include/sys/ptrace.h:75:4: error: expected identifier before numeric constant
    PTRACE_GETREGS = 12,
    ^
/usr/local/include/sys/ptrace.h:75:4: error: expected ‘}’ before numeric constant
/usr/local/include/sys/ptrace.h:75:4: error: expected unqualified-id before numeric constant
In file included from /usr/local/include/features.h:368:0,
                 from /usr/local/include/stdio.h:27,
                 from build-gnulib/import/stdio.h:43,
                 from ./common/common-defs.h:52,
                 from nat/aarch64-linux-hw-point.c:19:
/usr/local/include/sys/ptrace.h:225:1: error: expected declaration before ‘}’ token
 __END_DECLS
 ^
make[2]: *** [Makefile:1640: aarch64-linux-hw-point.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./common/common-defs.h:79:0,
                 from defs.h:28,
                 from aarch64-linux-nat.c:21:
aarch64-linux-nat.c: In function ‘void fetch_fpregs_from_thread(regcache*)’:
./common/gdb_assert.h:25:33: error: static assertion failed: 
 #define gdb_static_assert(expr) static_assert (expr, "")
                                 ^
aarch64-linux-nat.c:245:3: note: in expansion of macro ‘gdb_static_assert’
   gdb_static_assert (sizeof regs >= VFP_REGS_SIZE);
   ^
aarch64-linux-nat.c:273:15: error: ‘elf_fpregset_t’ has no member named ‘vregs’
         &regs.vregs[regno - AARCH64_V0_REGNUM]);
               ^
aarch64-linux-nat.c:275:65: error: attempt to take address of bit-field structure member ‘user_fpregs::fpsr’
       regcache_raw_supply (regcache, AARCH64_FPSR_REGNUM, &regs.fpsr);
                                                                 ^
aarch64-linux-nat.c:276:65: error: attempt to take address of bit-field structure member ‘user_fpregs::fpcr’
       regcache_raw_supply (regcache, AARCH64_FPCR_REGNUM, &regs.fpcr);
                                                                 ^
In file included from ./common/common-defs.h:79:0,
                 from defs.h:28,
                 from aarch64-linux-nat.c:21:
aarch64-linux-nat.c: In function ‘void store_fpregs_to_thread(const regcache*)’:
./common/gdb_assert.h:25:33: error: static assertion failed: 
 #define gdb_static_assert(expr) static_assert (expr, "")
                                 ^
aarch64-linux-nat.c:293:3: note: in expansion of macro ‘gdb_static_assert’
   gdb_static_assert (sizeof regs >= VFP_REGS_SIZE);
   ^
aarch64-linux-nat.c:321:20: error: ‘elf_fpregset_t’ has no member named ‘vregs’
     (char *) &regs.vregs[regno - AARCH64_V0_REGNUM]);
                    ^
aarch64-linux-nat.c:325:25: error: attempt to take address of bit-field structure member ‘user_fpregs::fpsr’
          (char *) &regs.fpsr);
                         ^
aarch64-linux-nat.c:328:25: error: attempt to take address of bit-field structure member ‘user_fpregs::fpcr’
          (char *) &regs.fpcr);
                         ^
make[2]: *** [Makefile:1621: aarch64-linux-nat.o] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/gdb-8.1.tar.xz.dir/gdb-8.1/gdb'
make[1]: *** [Makefile:9127: all-gdb] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/gdb-8.1.tar.xz.dir/gdb-8.1'
make: *** [Makefile:850: all] Error 2
gdb failed to install: `make V=0 -j4` exited with 2
`

**Comment by skiman6010** [comment]
@blu Can you try again? Seems that a recent package update fixed the issue on x86_64.

**Comment by blu** [comment]
As of #2259 same build errors : https://pastebin.com/UzEzXaaB

At a closer look, there is no way how `gdb-8.1/gdb/nat/aarch64-linux-hw-point.c` and `gdb-8.1/gdb/aarch64-linux-nat.c`could be build with the available `sys/ptrace.h`, `asm/ptrace.h` and `sys/user.h`:

1. first TU includes <asm/ptrace.h> and <sys/ptrace.h> -- that will always result in the PTRACE_GETREGS enumerator issue discussed above.
2. second TU static-asserts on the size of `user_fpregs` from `sys\user.h`

**Comment by blu** [comment]
@uberhacker did you have gcc7 installed during the gdb build on aarch64?

**Comment by uberhacker** [comment]
@blu: No, just the regular gcc but my build was on armv7l.  Should work on aarch64, however.  Let me know after the PR is merged if the binary works or not.
