### ISSUE TITLE
node_current does not install

### ISSUE THREAD

**Issue by faddah** [skycocker/chromebrew#200]
hello,

i am finding this on all the node installs, but particularly with the one i want, `node_current`. i do a `$ crew install node_current`, it goes on for for quite a while configuring, compiling & installing, about an hour each time, and then it always fails and exits on the install with —

```

...
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
sh: npm: not found
Password: 
node_current failed to install: `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}` exited with 1

```

this happens every time, and after it going on with the install for nearly an hour. why is this happening? you say not to use `sudo` with `crew`, but then why is it asking for the admin password mid-way through the install? why is it saying `npm` is not found? npm is installed *_with_* node.js, so it should either all ready know where it is, or know the it needs to install it with node.js. please advise on this and what to do to get node.js installed, please.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment]
you asked three questions, and I'll go in backwards order for speed
1) Why does it ask for password: Because we set permissions so you can npm i -g without sudo
2) why does it say npm: not found (for the same reason as #3 
3) Why does it fail to install (regardless of how long it takes)

THIS is all the same issue. I know that each time I install it I have to do something in addition that regular crew doesn't have yet.

Try this:

ln -s /usr/local/lib64/libmpc.so.3 /usr/local/lib64/libmpc.so.2

Tell us if it then installs

**Comment by thedamian** [comment]
Alright.

Just wiped my chromebook clean and I'm running the Dev Channel (TO make sure) and I'm having the same issue.

I fixed it by copying the files manually.

Do me a favour: 
1) Make sure you're using my newest file (not the regular one in chromebrew's regular git
2) get RID of the line I put at the end: 
system "sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}"

you DO need to run it but I need to make sure it works before I remove it.

**Comment by thedamian** [comment]
Ok. @faddah You took too long (more than 2 minutes ;-P ) so I did it for you.

See pull https://github.com/skycocker/chromebrew/pull/197

Just copy the node_current.rb and place it in your /usr/local/lib/crew/packages directory.
Do the same with the openssl_devel.rb 

then try it again. It'll go MUCH faster this time (which isn't saying much) and please report if it installs it.

**Comment by faddah** [comment]
@thedamian (& @skycocker ) —

ok, sorry, i took a few days off. i wasn't expecting someone to be checking for my posts and doing fixes and PRs, like, every two minutes.  ;)  but i thank you for your attentiveness.

so i did as you said, got the `node_current.rb` and the `openssl-devel.rb` from your PR #197, and tried running the install but the damn Acer C720P-2600 crashed on me 2/3s of the way through the compile/install. i will have to try the new `node_current.rb` & `openssl_devel.rb` again after i get home in a while.

i will let you know once i get all the way through an install or it fails and at what point.probably later tonight or early tomorrow.

more later.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment]
Put the 10 or so last lines after it failed to install. Or is it the kind of a crash that reboot the machine. Crew should nEVER do that.

**Comment by faddah** [comment]
@thedamian & @skycocker —

hi. well, it failed. i tried it about three times, as it kept doing that query for my admin Password, and the first couple of times it also failed (same failure, not finding npm), as i didn't give it the password in time (doing chores around the house while it takes an hour or so each time to compile the source). the third time i input the password correctly on time, but it still gave the same error. the error comes after it does all the installs as part of (i assume) `sudo make install` —

```
...
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
Password: 
chown: cannot access ‘/usr/local/lib/node_modules’: No such file or directory
node_current failed to install: `sudo chown -R chronos /usr/local/lib/node_modules` exited with 1
```

so that's what i keep running into each time, still cannot get node installed. any help here would  be appreciated.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment]
Edit the node_current.rb file in /usr/local/lib/crew/packages

Take out the second to last line or so that should say

System "`sudo chown -R chronos.....


Then run it again.

I will uninstall node and try that myself but I can't be sure if it works for me it'll work for you.

It should no longer ask you for your password and now no longer fail.

**Comment by thedamian** [comment]
ok @faddah 

I just updated my pull. Update the /usr/local/lib/crew/packages/node_current.rb with the file below (linked at the bottom) 

then run the crew install node_current

you shouldn't have to "catch the login" and just try this and see if it installs node.

https://raw.githubusercontent.com/thedamian/chromebrew/cc998495853b668ab0ee8aabebd5235b4858836e/packages/node_current.rb

**Comment by faddah** [comment]
@thedamian & @skycocker  —

so i did download the latest `node_current.rb` and replaced it from what was in my `/usr/local/lib/crew/packages/` directory. i then ran the `$ crew install node_current`. it goes further, seeming to install most everything, after its usual hour or so of needing compile, but unfortunately, it _*still*_ does not install node or npm. i get a lot of "installing" messages at the end, as if it is finishing up, then get some sort of error out message, and it quits, after all that time, without completing the install of node or npm.

here's some of the final lines i see —

```

...
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
/usr/local/lib/crew/packages/node_current.rb:21:in `install': undefined method `echo' for Node_current:Class (NoMethodError)
        from /usr/local/bin/crew:242:in `block (2 levels) in install'
        from /usr/local/bin/crew:237:in `chdir'
        from /usr/local/bin/crew:237:in `block in install'
        from /usr/local/bin/crew:231:in `chdir'
        from /usr/local/bin/crew:231:in `install'
        from /usr/local/bin/crew:162:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:353:in `<main>'

```

i tried this twice, failed this way each time

i'm open to any other suggestions, please? 

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment]
@faddah  That explained it all

I've done a check in that will fix the issue.

Again copy the node_current.rb to your /usr/local/lib/crew/packages just like last time but this time use the new versions I just uploaded.

https://raw.githubusercontent.com/thedamian/chromebrew/f0202173fe415d6cd0f3dd998f72c5e6ea8cf539/packages/node_current.rb

Thanks for the help @faddah

**Comment by faddah** [comment]
@thedamian & @skycocker —

unfortunately, i didn't wait much longer. i was able to install Node.JS v6.3.0 and npm v3.10.3 from source after much back and forth on ChromeOS reddit forum (see here — https://www.reddit.com/r/chromeos/comments/4t6oh9/acer_c720p_in_dev_mode_with_chromebrew_cannot_do/), i got it to install from source.

so i have Node.JS v6.3.1 &  npm v3.10.3 installed, and, to be honest, i don't want to chance running the `crew` ruby scripts again so it doesn't mess up my Node.JS install that is working now. sorry.  :(

perhaps someone else has an Acer C720P-2600 Chromebook with the latest ChromeOS updates for you to try it on?

also, as a side note, it appears that a number of things have changed in updates in the past few months to ChromeOS. one is the issue named in this repository's issue #190 , where people repeatedly get `error: undefined symbol: rl_signal_event_hook`, because, it would seem, the new Bash v4.3 in ChromeOS doesn't like any other `readline` installed, as packages are wont to do, other than the system's own `readline` that it is expecting. also, the issue i reference with the [ChromeOS reddit forum link above](https://www.reddit.com/r/chromeos/comments/4t6oh9/acer_c720p_in_dev_mode_with_chromebrew_cannot_do/), where it now appears, per what i found in the forum, that the `~/Downloads` directory is on a partition formatted for ChromeOS filesystem that is now `noexec`; whereas, before, i could install/compile from source from directories i downloaded into `~/Downloads` with no issues. i think an FAQ should be made to note these differences and their solutions for users of ChromeOS, Chromebooks and Chromebrew here.

all i know is: previously, i never had such problems attempting to install Node.JS from Chromebrew or compiling it via source from a sub-directory of `~/Downloads`, and now there are nothing but problems with that. i think it needs to be documented with solutions, my suggestion, at least.

best,

—  faddah
      portland, oregon, u.s.a.

**Comment by thedamian** [comment]
@faddah 
you didn't take my advice and install my package correctly.

luckly node update to 6.3.1 so I had a chance to do it myself.

I instlaled it with the node_current.rb in the pull that's waiting to be approved.

and here's the output that successfully worked:

....
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
Now to get npm -g working you should type this
sudo chown -R chronos /usr/local/lib/node_modules
Installing...
Node_current installed!

You can use the node crew in the future when you're ready

**Comment by thedamian** [comment]
p.s. I'm using the latest developer channel

Version 53.0.2785.23 dev (64-bit)
Platform 8530.24.0 (Official Build) dev-channel link
Firmware Google_Link.2695.1.169

so it works on all chromebooks now with any version.

Enjoy.

**Comment by thedamian** [comment]
Readline's "undefined symbol: rl_signal_event_hook" issue fixed in latest pull https://github.com/skycocker/chromebrew/pull/197

**Comment by faddah** [comment]
@thedamian & @skycocker ‒

that last fixed it for me. node all installed, v6.3.1, along with npm and _lot_ o' packages. thank you for hand-holding me through all the help. ok to close this one out? do we need to keep it to make sure a fix is PR'd for this? please let me know. and thank you again.

best,

‒  faddah
    portland, oregon,. u.s.a.

**Comment by thedamian** [comment]
No. You can close this issue and the PR will love along with . 

You COULD do us all a favor and always comment on the PR 's thread saying it worked for you with tmsome details so that it'll be more quickly merged.

**Comment by faddah** [comment]
ok, i'll comment on the PR thread. thanks! consider this closed.

best, 

—  faddah
     portland, oregon, u.s.a.
