### ISSUE TITLE
python2 -c 'import ssl' fails

### ISSUE THREAD

**Issue by mike-pomodoro** [skycocker/chromebrew#201]
I'm using Chromebrew, version 0.2.1 on an Acer C720 laptop.
I ran: crew install python27
And learned python 2.7 is not compiled/built with ssl support so this command fails:
    python -c 'import ssl'

To fix this  I downloaded python27  source (crew download python27) and added line 792 and line 806.

/usr/local/tmp/crew/Python-2.7.10/setup.py
 791         search_for_ssl_incs_in = [
 792                               '/usr/local/include', #### CHROMEOS PATH TO openssl/ssl.h
 793                               '/usr/local/ssl/include',
 794                               '/usr/contrib/ssl/include/'
 795                              ]

 804         ssl_libs = find_library_file(self.compiler, 'ssl',lib_dirs,
 805                                      ['/usr/local/ssl/lib',
 806                                       '/usr/lib64', #### CHROMEOS PATH TO libssl.so & libssl3.so
 807                                       '/usr/contrib/ssl/lib/'
 808                                      ] )

**Comment by mike-pomodoro** [comment]
Actually I think the only problem is that openssl needs to be installed first, and then python27; so this dependency should probably be added.

**Comment by mike-pomodoro** [comment]
The new openssl package broke  ssh.

chronos@localhost ~$ ssh sdf
OpenSSL version mismatch. Built against 1000207f, you have 1000105f

**Comment by mike-pomodoro** [comment]
removing openssl allows ssh to work again:
> sudo remove openssl

**Comment by thedamian** [comment]
actually this pull request (it's an old one) already fixes this issue: https://github.com/skycocker/chromebrew/pull/207

please close this issue if this fixes the issue.

**Comment by lyxell** [comment]
@thedamian Pull request #207 does not change OpenSSL in it's current state.

**Comment by thedamian** [comment]
@lyxell your statement is.true but @Mike-pomodoro was trying.to install python eith openssl and that pull does that and so I think my statement stands.

**Comment by mike-pomodoro** [comment]
Just installed chromebrew few minutes ago:

> wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash

But still getting this error:

> chronos@localhost ~$ bash
> bash: symbol lookup error: bash: undefined symbol: rl_signal_event_hook

Laptop was powerwashed few minutes before installing Chromebrew (so it's freshly installed with nothing else mucking up the configuration):
> Version 52.0.2743.116 (64-bit)
> Platform 8350.68.0 (Official Build) stable-channel peppy
> Firmware Google_Peppy.4389.93.0

Am I missing something or did this issue not get fixed?

**Comment by mike-pomodoro** [comment]
I someone got it working.

python can import ssl, ssh also works, but the readline error in issue #190 is still there can removing readline does not fix it.

It's better to use chromebrew from the master branch since all 3 of these issues can be worked around.

**Comment by thedamian** [comment]
There's already pull requests fixing all of these issues.

**Comment by thedamian** [comment]
Mike my install.sh isn't the solution. The package that installs python is.

Of course I'm saying this for the next person that runs into this since you're all set without our help (best solution ;-)

**Comment by bfayers** [comment]
I've gotten SSL to build on python2.7, however I am on an ARM device, though my rambling instructions might help you out. things like changing versions on openssl_devel would be pointless for you but other things should be all good. https://github.com/skycocker/chromebrew/pull/235#issuecomment-266043757

**Comment by lyxell** [comment]
Closing as resolved.
