### ISSUE TITLE
How to install Ruby 2.3.1 in chromebook - Comments please!

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#202]
Alright. 

This is NOT an issue. but something I will post on the wiki. But first I need to know what you think.

I have ruby 2.3.1 AND RVM (so Rails next?)

Here's how I did it.

1) I installed rvm 
curl -sSL https://get.rvm.io | bash -s stable
# It will fail installing ruby because of openssl and because it can't find which version of linux we have

2) install openssl 1.0.2f
crew install openssl_devel

3) install the openssl and readline ruby packages, and then ruby using the openssl packages just installed:
rvm package install openssl
rvm package install readline
rvm install 2.3.1 -C --with-openssl-dir=$HOME/.rvm/usr,--with-readline-dir=$HOME/.rvm/usr 

I need opinions.

Should I put a new package with these steps already done for you? Should I just keep it as a "HOW-TO" in the Wiki?

What do YOU think.

**Comment by mike-pomodoro** [comment]
Prefer putting it in the package.

Otherwise I'd manually install rvm, have it fail, google the error and may or may not  find the wiki on how to fix it. Having it in a package would probably save an hour or more of troubleshooting.

**Comment by TheLonelyGhost** [comment]
I'm also interested in Ruby 2.3.1 on a chromebook, but would definitely be dissuaded by the automatic inclusion of RVM.

What makes this different from updating the SHA, source URL, and dependencies in the `Ruby_latest` package?

Can RVM be its own package instead? Have you tried porting something simpler like chruby with ruby-install?

**Comment by lyxell** [comment]
Closing since ruby_latest is updated.
