### ISSUE TITLE
[libxcb] build problem

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#2026]
libxcb needs python2.7 , which is located in /usr/local/lib

checking XCBPROTO_XCBINCLUDEDIR... /usr/local/share/xcb
checking XCBPROTO_XCBPYTHONDIR... /usr/local/lib/python2.7/site-packages

Could python27 and python3 be moved to /usr/local/lib64 for further simplification of compilation?

#1981

**Comment by uberhacker** [comment]
As long as the binaries still get installed in `/usr/local/bin`, that should be fine.

**Comment by uberhacker** [comment]
Fixed in #2107.
