### ISSUE TITLE
Add 'Some Gnome/gtk/Graphical' Fake Package

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#2029]
Hy,

Can we add some "fake" package for gnome/graphical/gtk 'stuff' (like the core package):

Otherwise, we have to add, in the dependencies all the files, each time.
For example, for mate-calc, all those need to be added:

  NEEDED               libgtk-3.so.0
  NEEDED               libgdk-3.so.0
  NEEDED               libpangocairo-1.0.so.0
  NEEDED               libpango-1.0.so.0
  NEEDED               libatk-1.0.so.0
  NEEDED               libcairo-gobject.so.2
  NEEDED               libcairo.so.2
  NEEDED               libgdk_pixbuf-2.0.so.0
  NEEDED               libgobject-2.0.so.0

, but those 'are recurrent'.

**Comment by uberhacker** [comment]
Sounds like a good idea to me.  What do you think @lovedheart?

**Comment by lovedheart** [comment]
To prevent some dependency loop, I prefer to separate them. If they are stable, we can consider to wrap them.

**Comment by beliefless-dogmasless** [comment]
Ok  "prevent some dependency loop, I prefer to separate them. If they are stable".
