### ISSUE TITLE
libjpeg-turbo or libjpeg

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#2040]
- libjpeg-turbo is a JPEG image codec that uses SIMD instructions (MMX, SSE2, AVX2, NEON, AltiVec) to accelerate baseline JPEG compression and decompression on x86, x86-64, ARM, and PowerPC systems. On such systems, libjpeg-turbo is generally 2-6x as fast as libjpeg, all else being equal. On other types of systems, libjpeg-turbo can still outperform libjpeg by a significant amount, by virtue of its highly-optimized Huffman coding routines. In many cases, the performance of libjpeg-turbo rivals that of proprietary high-speed JPEG codecs.

- libjpeg-turbo implements both the traditional libjpeg API as well as the less powerful but more straightforward TurboJPEG API. libjpeg-turbo also features colorspace extensions that allow it to compress from/decompress to 32-bit and big-endian pixel buffers (RGBX, XBGR, etc.), as well as a full-featured Java interface.

see [https://libjpeg-turbo.org/](url)

Should we replace libjpeg by libjpeg-turbo ??

**Comment by uberhacker** [comment]
If the packages that require `libjpeg` can compile cleanly with the turbo replacement, by all means, do it.  Faster and more efficient is always better.
