### ISSUE TITLE
Add LibSass package

### ISSUE THREAD

**Issue by VitaliyKulikov** [skycocker/chromebrew#2042]
A C/C++ implementation of a Sass compiler http://libsass.org

Thank You.

**Comment by uberhacker** [comment]
Do you want to try and take a shot at this @VitaliyKulikov?  Creating new packages is fairly easy.  See https://github.com/skycocker/chromebrew/wiki/Creating-a-package.

**Comment by uberhacker** [comment]
It doesn't look like a package is even needed.  A simple `gem install` is all you need.  See http://sass-lang.com/install#install-ruby-linux.

**Comment by VitaliyKulikov** [comment]
@uberhacker sure, i can build by myself. just need time.
i need `libsaas` for `node-saas` to avoid g++ re-compilation each time during the project build.

**Comment by lesthack** [comment]
@VitaliyKulikov any solution ? i'm trying install node-sass unsuccessful
