### ISSUE TITLE
Applications, I think 'need to be compiled' as gtk3

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#2061]
Hy,

Just to notice, I figured out, that applications, need to 'be compiled with gtk3 option', otherwise with 2.24(gtk)only, they won't start*:

autogen.sh --enable-gtk3
or if no autogen:
configure --enable-gtk3

*geany
cannot open display
caja
Could not parse arguments: Cannot open display:

**Comment by sajjaadf** [comment]
This is useful

**Comment by JL2210** [comment]
Are you sure? How would it be? We have both gtk2 and gtk3. Why does it matter?

**Comment by saltedcoffii** [comment]
We are now moving on to supporting gtk4 and gnome 40 packages as much as possible, and using gtk3 as a backup. gtk2 will remain in our repositories. Closing issue as it's not irrelevant.
