### ISSUE TITLE
How to get a package from a .deb file.... PLEASE COMMENT AND CORRECT ME!

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#208]
OK. So you find the package you want but it's from a .deb file.
Our packages can't handle .deb files YET.

Here's what you do. 
Download the file to some temporary directory.
ar vx {filename.deb}
create a new directory that represents this software, maybe same as the "filename" in "filename.deb" file and go into that directory.
tar xcvf ../data.tar.gz file (that's not ANY file. it's the actual data.tar.gz file which WILL be there)
it'll probably create a /usr directory with a lot of files in there. 
You will have to create a file that doesn't drop everything into the /usr directory but into the /usr/local directory (which you have access to)
create a "local" directory inside the usr directory then move all the other content into there.
run the create_package.sh

that's it.

You're not a top contributor!

COMMENTS

**Comment by lyxell** [comment]
Yes, this is the correct way to unpack a .deb-file. Most packages will work out-of-the-box, however, Debian-packages often have a very Debian-specific configuration which may result in undesired behaviour.

**Comment by thedamian** [comment]
What I'm thinking is that if we add support for.dev files to the crew command then we can add packages that instead of looking only at.tar.gz files will use chosen.dev files as well.

I'm working on a new package that had some dependencies that were simply some header files and were available in.dev form.

So instead of me doing this .deb trick manually and making my own tar.xz version that eventually never gets updated; I use officially a.deb file instead.

It works be a specifically created package file by the creator of the crew package but they wouldn'have to host a file somewhere which feels like a barrier.
