### ISSUE TITLE
[node] problem installing node (path?)

### ISSUE THREAD

**Issue by hutzlibu** [skycocker/chromebrew#2086]
Hi there,

I installed my Chromebook(ARM Asus C213) freshly new and I run into a problem while installing node, I had not before.
(I had it all running without problems)

So I put it into Dev-Mode, assigned password.
Installed crew:
`curl -Ls git.io/vddgY | bash`
and then
`crew install node`
And it all went without problems. Except when I type 
`node`
he gives me command not found ...
7z for example was installed without a problem.
Any Ideas?

**Comment by uberhacker** [comment]
@hutzlibu: You will need to install either the `nodebrew` or `nvm` packages to install node.  We are no longer supporting the `node` package and it has been deprecated.
Steps for nodebrew (replace 9 with the version you want):
```
$ crew install nodebrew
$ nodebrew install-binary 9
$ nodebrew use 9
```
Steps for nvm (replace 9 with the version you want):
```
$ crew install nvm
$ nvm install 9
```

**Comment by hutzlibu** [comment]
Thanks for the quick help ...

**Comment by JL2210** [comment]
I don't think NVM is used/supported anymore. Just use nodebrew or build from source yourself.

**Comment by JL2210** [comment]
Try `crew install node` and it installs Nodebrew.

**Comment by JL2210** [comment]
Also, please create a new issue instead of commenting on a closed one.

**Comment by shinriyo** [comment]
@uberhacker Thank you. I also helped by your answer
however it was not needed. `crew install` already installed it.
```
crew install nodebrew
```
