### ISSUE TITLE
Can not find .la files by compiling packages on x86_64

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#2108]
The compile error "/usr/local/lib/foo.la is not a valid libtool archieve" or "can not find /usr/local/lib/foo.la" is  a very common problem when building packages on x86_64. It seems that those *.la files located in /usr/local/lib64 can be deleted to resolve the compile errors.

see [https://gnunet.org/faq-la-files](https://gnunet.org/faq-la-files)
[https://blog.flameeyes.eu/2009/09/removing-la-files-for-dum-w-uncertain-people/](https://blog.flameeyes.eu/2009/09/removing-la-files-for-dum-w-uncertain-people/)

#2105

**Comment by uberhacker** [comment]
Fixed in #2110.
