### ISSUE TITLE
package/feature request — can we add MySQL?

### ISSUE THREAD

**Issue by faddah** [skycocker/chromebrew#211]
Hello,

Is it possible to add MySQL 5.6 or 5.7 to the list of install-able packages for Chromebrew, here, please? I need it for WordPress development. WordPress still will not work with any other SQL database except for MySQL, so SQLIte will not do.

Please let me know on this. Thank you.

best,

— faddah
     portland, oregon, u.s.a.

**Comment by smerkousdavid** [comment]
@faddah 
Have you thought about doing it yourself from source? Maybe it could be added to the list but for now you can use gcc,cmake and make which chromebrew supports
https://dev.mysql.com/doc/refman/5.6/en/installing-source-distribution.html

**Comment by dihuta** [comment]
Does Anyone succeed on installing mysql server?

**Comment by b3n10** [comment]
I'm not sure but looks like installing mysql is only possible if **libaio** is installed but crew doesn't have it available. And also as per the steps to install MySQL `groudadd` and `useradd` are required to add a mysql user but chromebook shell also doesn't have these commands.

**Comment by flyingP0tat0** [comment]
I already tried installing MySQL. The install itself worked fine after some tweaks. But the resulting MySQL service (we don't even have a service manager) was kind of useless and reported lot's of errors. Same goes for MariaDB.

**Comment by thedamian** [comment]
We have a fix:
https://github.com/skycocker/chromebrew/pull/1708
