### ISSUE TITLE
package/feature request — can we add PHP 7.x?

### ISSUE THREAD

**Issue by faddah** [skycocker/chromebrew#212]
Hello,

Is it possible to add PHP 7.x (whatever is current stable version) to the list of install-able packages for Chromebrew, here, please? I need it for WordPress development. WordPress still will not work without PHP.

Please let me know on this. Thank you.

best,

— faddah
     portland, oregon, u.s.a.

**Comment by jkoudys** [comment]
+1

**Comment by finwo** [comment]
@faddah This has been added in #306

**Comment by lyxell** [comment]
Resolved :)
