### ISSUE TITLE
Java package error

### ISSUE THREAD

**Issue by dryamJS** [skycocker/chromebrew#213]
mv: cannot stat ‘/usr/local/tmp/crew//usr/local/opt/java/bin/javac’: No such file or directory
mv: cannot stat ‘/usr/local/tmp/crew//usr/local/opt/java/bin/jvisualvm’: No such file or directory
mv: cannot stat ‘/usr/local/tmp/crew//usr/local/opt/java/bin/jcontrol’: No such file or directory
Jdk8 installed!

A little mistake.

**Comment by thedamian** [comment]
Created the jdk8 package back in the carter administration but can you run "java"?

**Comment by Camarde** [comment]
I have the same problem with jdk, just tried it again. I get the following error:
`chronos@localhost / $ java
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.`

See attachment for complete log during "crew install jdk":

[feedbackJdb8.txt](https://github.com/skycocker/chromebrew/files/522678/feedbackJdb8.txt)

**Comment by lyxell** [comment]
Duplicate of #156
