### ISSUE TITLE
dependency loop (crew upgrade)

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#2132]
crew upgrade does nothing but always checking dependency

**Comment by uberhacker** [comment]
Just curious.  Did you execute `crew update` prior to `crew upgrade`?

**Comment by lovedheart** [comment]
crew upgrade

**Comment by uberhacker** [comment]
Try this sequence:
```
$ git pull origin master
$ crew update
$ crew upgrade
```
