### ISSUE TITLE
[npm] add Packages from Npm

### ISSUE THREAD

**Issue by beliefless-dogmasless** [skycocker/chromebrew#2138]
Hy,

Not 'really an issue', but more an improvment. Do you guys know, how to make a rb file, able to handle the uninstallation in 
usr/local/share/nodebrew/node/    directory:

For example, the installation, of that works fine, but the uninstallation don't 'get rid' of the files 'in that directory': 

require 'package'

class Cloudcmd < Package
  description 'Cloud Commander is an orthodox web file manager with console and editor. https://github.com/coderaiser/cloudcmd'
  homepage 'https://github.com/coderaiser/cloudcmd/releases'
  version '8.5.0'
  source_url 'https://github.com/coderaiser/cloudcmd/archive/v8.5.0.tar.gz'
  source_sha256 '1ac0aa4b0f195a9d9d12489f86203510af6d45738edc397686910f2d3c8fa291'

  depends_on 'node'
  depends_on 'nodebrew'
  depends_on 'python27'

  def self.install
    system "npm i cloudcmd -g" # the steps required to install the package
  end
  
end

**Comment by uberhacker** [comment]
@beliefless-dogmasless: There are postinstall uninstall instructions in both the `nodebrew` and `nvm` packages.
nodebrew:
```
    puts "To uninstall, execute the following:".lightblue
    puts "crew remove nodebrew".lightblue
    puts "rm -rf #{CREW_PREFIX}/share/nodebrew".lightblue
    puts
```
nvm:
```
    puts "To uninstall, execute the following:".lightblue
    puts "crew remove nvm".lightblue
    puts "rm -rf #{CREW_PREFIX}/share/nvm".lightblue
    puts "Delete any lines with NVM_DIR in ~/.bashrc.".lightblue
```
We probably don't want to include npm or yarn modules.  Just let those "package managers" handle them.

**Comment by beliefless-dogmasless** [comment]
Thanks.
