### ISSUE TITLE
Add a crew list installed and crew list available option

### ISSUE THREAD

**Issue by pgdagenais** [skycocker/chromebrew#2145]
Going back on this closed pull request by @uberhacker https://github.com/skycocker/chromebrew/pull/319

I do think that this option is useful. Maybe with a new argument like `crew list installed` and `crew list available`

It doesn't really fit with `crew search`

If you don't mind @uberhacker I would take your code and modify it to match match what I said.

**Comment by uberhacker** [comment]
@pgdagenais: Sure, go for it!  If you add a new command, make sure you document it with help.  You can probably get a good idea of how to do that from the existing commands.  I was thinking it might also be good if the `crew files` command included the disk space used (aka size) for all the files in the package.

**Comment by uberhacker** [comment]
Fixed in #2151.
