### ISSUE TITLE
Feature Request: Use github source for imagemagick install

### ISSUE THREAD

**Issue by jeffmcneill** [skycocker/chromebrew#2159]
ImageMagick tends to remove second-most-recent builds as well as sha digests as soon as a new version is released. This means updates to imagemagick.rb, imagemagick6.rb, and imagemagick7.rb need to be made quite regularly. 

Instead, it may be better to point to the github source, which does not remove the source distribution files on new versions. Also, ImageMagick itself says that the github source is canonical. 

However, there does not seem to be a sha256 digest available for the github source files, nor does the sha256 produced for the source files on the ImageMagick site work (probably due to the filenames being different).

I'm not familiar with out sha256 is generated for a file, but it would seem to be easier work maintaining the imagemagick installation in crew to generate a sha256 manually and add to the imagemagick*.rb files, which would allow for those installation scripts to work into the future.

**Comment by uberhacker** [comment]
@jeffmcneill: What you say makes sense, however, since we have binaries, the missing source files will go unnoticed unless you force compilation using `crew install imagemagick7 -s`.  With that said, I kinda like the fact that they remove the old source since it alerts us that an update is available.

**Comment by uberhacker** [comment]
Please test the new binaries when you get a chance @jeffmcneill.  They were recently merged into master.

**Comment by jeffmcneill** [comment]
New binaries worked a charm. I also noticed that with `crew upgrade` the only package with an update was the notorious `lzma`. In any case, it's all good now.
