### ISSUE TITLE
Website doesn't link to packages or github repo...

### ISSUE THREAD

**Issue by benlowry** [skycocker/chromebrew#217]
https://skycocker.github.io/chromebrew/

**Comment by krruzic** [comment]
In the top right it links to "fork me on github" click that and you'll get the repo. Packages should maybe be listed

**Comment by thedamian** [comment]
Packages are listed. 
Please look for the words "packages" which is Germán for "Packages"

**Comment by krruzic** [comment]
They aren't listed anywhere on the website. 

Where are you seeing them?

**Comment by thedamian** [comment]
Either we are thinking of two different things when you say packages or you're going blind like me.

If you're seeing this text (on github not on your email client) then click on "Code" and look for packages 

You can use control-F on Linux and windows or command-F on a Mac to help with this. 

Don't we all need Ctrl-F in our lives!

**Comment by krruzic** [comment]
The website being https://skycocker.github.io/chromebrew/ I know the packages are listed in the code repository. We are thinking of two different things haha

**Comment by thedamian** [comment]
The website can't link to the packed because
1)they change too frequently
2) it wouldn't fit the standard of brew we're following which is that the search is in the app not a website.

**Comment by thedamian** [comment]
@kruzics please close this issue since even if you think you're right there's a repository for the website and this ain't it.

**Comment by krruzic** [comment]
I didn't make this issue... and you're right. @benlowry
