### ISSUE TITLE
Openssl need to update

### ISSUE THREAD

**Issue by clouds56** [skycocker/chromebrew#220]
now the prebuilt version 1.0.1e is affected by heartbleed, please consider upgrade it to the latest version.

**Comment by thedamian** [comment]
I've seen a lot of complains that are fixed in the pull requests. 

For open source software please check pull requests before starting new "issues"

**Comment by thedamian** [comment]
Just for reference he's the pull that fixes this very issue you're talking about:
https://github.com/skycocker/chromebrew/pull/181/files

Now I agree completely. the openssl installed originally (and the same for python or ruby and anything else installed) should be updated for the latest, but that pull will at least help you with the issue you've brought up.

**Comment by clouds56** [comment]
Thanks!
