### ISSUE TITLE
Can't use ./

### ISSUE THREAD

**Issue by 4k-developer** [skycocker/chromebrew#221]
I can't do ./configure because it keeps saying permission denied. I tried chmod but still says that and i'm doing this in my internal SSD so I know its ext. Can someone help please.

**Comment by thedamian** [comment]
You'll have to be more specific. You don't do ./configure unless you're manually building some software which is related to an issue somewhere other than here.

**Comment by 4k-developer** [comment]
Sorry forgot to close. I figured it out ChromeOS has the home dir mounted noexec
