### ISSUE TITLE
/usr/local contains /usr/local/var/log/dptf

### ISSUE THREAD

**Issue by nealmcb** [skycocker/chromebrew#2214]
In issue #9, it says that /usr/local is empty by default in Chrome OS.  But my new Samsung Pro Chromebook has an empty directory in there: `/usr/local/var/log/dptf`.

```
sudo ls -ld /usr/local /usr/local/var /usr/local/var/log /usr/local/var/log/dptf
drwxr-xr-x. 3 root root 4096 Apr  3 20:05 /usr/local
d-wxr----t. 3 root root 4096 Apr  3 20:05 /usr/local/var
d-wxr----t. 3 root root 4096 Apr  3 20:05 /usr/local/var/log
d-wxr----t. 2 root root 4096 Apr  3 20:05 /usr/local/var/log/dptf
```

WIll this cause any problems? I'm worried because the line

    sudo chown -R `id -u`:`id -g` "${CREW_PREFIX}"

now seems to be mucking with an existing directory, with possible security issues etc.

Is it ok to run the install having first set CREW_PREFIX=/usr/crew or something
and then creating that directory?

## Versions and system information
chromebrew: `crew --version`

(Not installed yet)

ChromeOS: `cat /etc/lsb-release`

```
$ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4613139
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R64-10176.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.76.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10176.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.76.0
```

Model: Samsung Chromebook Pro model 510C24-K04

Architecture: x86_64

**Comment by beliefless-dogmasless** [comment]
I don't see any problem, there's gonna be more stuff(files and dicrectories) in /usr/local
that's all.

Funny there's a /usr/local in the initial install now, they change things every week

**Comment by nealmcb** [comment]
Good to hear.  But my concern is that changing the permissions, which seem carefully thought out, will cause bugs or security weaknesses.  Does anyone know what DPTF really does and what would happen if it broke or was manipulated?  Here are some links, but they don't clarify things for me much.

Intel® Dynamic Platform and Thermal Framework (DPTF) for Chromium OS - Documentation | 01.org
 https://01.org/intel%C2%AE-dynamic-platform-and-thermal-framework-dptf-chromium-os/documentation

 https://github.com/intel/dptf

**Comment by nealmcb** [comment]
Perhaps the easiest solution would be to not change the permissions on /usr/local itself.  Does install.sh create everything that will be necessary in /usr/local?  Is /usr/local/var never used by crew? If so, then so long as the other subdirectories are owned by chronos, subsequent installs should work fine.

**Comment by uberhacker** [comment]
Not sure what usefulness DPTF provides on ChromeOS but I'm gonna throw in a wrinkle that may or may not affect anything.  On CloudReady, `/usr/local/var` is a symlink to the read-only `/var`.

**Comment by JL2210** [comment]
Everybody has that. The directory is and stays empty. No issue.

**Comment by JL2210** [comment]
@uberhacker, can you close this?
