### ISSUE TITLE
[urlwatch] No files after install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2246]
```
$ crew install urlwatch
urlwatch: A tool for monitoring webpages for updates
https://thp.io/2008/urlwatch/
version 2.7-1
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
tar: ./usr/*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Performing post-install...
Urlwatch installed!
$ crew files urlwatch
(i) urlwatch: A tool for monitoring webpages for updates
https://thp.io/2008/urlwatch/
version 2.7-1
Total found: 0
Disk usage: 9.6M
```

**Comment by uberhacker** [comment]
@skiman6010: Did you give up?  I was having trouble also. :)

**Comment by skiman6010** [comment]
@uberhacker Yeah couldn't figure it out and didn't have the time to really dig super deep into it. Work is pretty busy right now. :)

**Comment by JL2210** [comment]
It looks like they're using Pip.

**Comment by cstrouse** [comment]
This doesn't even install for me. It fails after being unable to find a version of cffi that satisfies the version requirement.

**Comment by cstrouse** [comment]
I can build this from source now and the files show up where they belong. The binaries don't have any files besides directory and file lists.

**Comment by cstrouse** [comment]
Binaries still contain zero files.

**Comment by JL2210** [comment]
The DESTDIR logic is probably flawed.

**Comment by saltedcoffii** [comment]
@uberhacker this shouldn't be an issue anymore after #5647, this can be closed.
