### ISSUE TITLE
Add R to the list of packages?

### ISSUE THREAD

**Issue by danilofreire** [skycocker/chromebrew#228]
Is there any way to install [R](https://www.r-project.org/) with Chromebrew? Thanks! :)

**Comment by bfayers** [comment]
http://unix.stackexchange.com/questions/149451/install-r-in-my-own-directory

Try follow those directions.

**Comment by danilofreire** [comment]
@bfayers thanks for the link. I've downloaded the file successfully but this command doesn't seem to work `./configure --prefix=$HOME/R`. I've tried different directories (`$HOME`, `$HOME/R/bin` and `$HOME/bin`) but I keep getting this error: `configure: error: No F77 compiler found`. Any suggestions?

**Comment by danilofreire** [comment]
Running it with `sudo` gives me the following error: 

`checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/bin/R-3.3.1':
configure: error: C compiler cannot create executables
See `config.log' for more details'
