### ISSUE TITLE
Interest in a chromebrew discussion forum?

### ISSUE THREAD

**Issue by thpglobal** [skycocker/chromebrew#2285]
## Before you submit an issue
Several enhancement requests refer to the desire for a discussion forum for chromebrew projects, as the github issues come and go - they don't lend themselves to discussions.

## Description
I'd be willing to set one up if people are interested - there is a long discussion on github about adding a discussion tab that has not materialized, but I did find a willingness for Discourse to host a discussion for free - see https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

**Comment by uberhacker** [comment]
@jcoonrod:  Thank you for the suggestion.  We currently have a KanBan-style project at https://github.com/skycocker/chromebrew/projects/1.  If you install the ZenHub browser plugin (see https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US), you can take advantage of more awesomeness.  We also have a Slack channel which is open to more informal discussion.  If you would like to join, please send an email to crewonslack@gmail.com to receive an invite.

**Comment by pgdagenais** [comment]
Sadly I wanted the join the chromebrew slack but it is not possible at the moment.

Hey Philippe,

Sorry for the delay.  Slack has put a limit on the number of invites we can send out so I can send you one at this time.  However, if you get a @studiozenkai.com or @dhautefeuille.eu email address, you can sign up with this link: https://chromebrew.slack.com/signup.  Sorry for the trouble.

**Comment by uberhacker** [comment]
@pgdagenais: See if this invite link works for you.  https://join.slack.com/t/chromebrew/shared_invite/enQtMzUzMjI3NzU2NzUzLWViMGMzNzY1MDk0YTI5Y2RkMTIxMTY3OGQ0ZDYzMDRjODE0ZWI2NTM5MjBkM2Q4NGNlYzY4MGM1MzM2ZTI4NTQ

**Comment by pgdagenais** [comment]
@uberhacker thank you very much, it worked

**Comment by ukscone** [comment]
is slack still where all the chromebrew peeps hangout? i'm not a big fan of slack, in fact I think it's the devil incarnate but when needs must

**Comment by uberhacker** [comment]
I'm with you.  Slack does have many annoyances but it's where everybody is hanging out these days, unfortunately.

**Comment by ukscone** [comment]
can I get an invite to the chromebrew slack then please as I have a couple of requests for either has someone already build a library or can I get some help building some libraries please

**Comment by uberhacker** [comment]
Just click on the Slack logo in README.md and you should receive an invite.  Let me know if it doesn't work and I can send another invite.

**Comment by ukscone** [comment]
when i clicked it earlier it said it had expired but will give it another go

**Comment by uberhacker** [comment]
Another Slack annoyance?  That invite link did not have an expiration. LoL

**Comment by ukscone** [comment]
ah the logo works, the link next to it doesn't
