### ISSUE TITLE
Failing to install node

### ISSUE THREAD

**Issue by FreddyFish** [skycocker/chromebrew#230]
After trying a few times and reading previous issues on installing node i still can't figure out how to do it.

This is what i tried:
crew install node > I belive it tries to compile it, but ends with this:
installing /usr/local/tmp/crew/dest/usr/local/include/node/openssl/opensslconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zconf.h
installing /usr/local/tmp/crew/dest/usr/local/include/node/zlib.h
sh: npm: not found
chown: cannot access ‘/{lib/node_modules,bin,share}’: No such file or directory
node_current failed to install: `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}` exited with 1

crew install node_stable > does not even start and returns
Checksum mismatch :/ try again.

crew install node_current > seems to compile but ends with the same as "crew install node"

Can someone help me with my issue?
I'm running toshiba chromebook 2 SWANKY.

**Comment by thedamian** [comment]
This is a duplicate issue: https://github.com/skycocker/chromebrew/issues/155

Please delete. the fixes are shown at the bottom of that issue.

**Comment by FreddyFish** [comment]
But as i see the fix is to add --without -snapshot to the .rb file. 
My node_current.rb file is already having that line.

`equire 'package'

class Node_stable < Package
  version '6.2.2'
  source_url 'https://nodejs.org/dist/v6.2.2/node-v6.2.2.tar.xz'
  source_sha1 '5014800813FA3682B8053637518B37A119C26E93'

  depends_on 'buildessential'
  depends_on 'python27'

  def self.build
    system "CC='gcc' python2.7 ./configure --without-snapshot"
    system "make"
  end

  def self.install
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
    #Fix Permissiongs for -g installs of node packages
    system "sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}"
  end
end`

**Comment by jam7** [comment]
@FreddyFish: your node_current.rb has `system "sudo chown -R..."` line.  It's old.  Try `crew update` and `crew install node_current` again.

**Comment by lyxell** [comment]
I think this is resolved, please reopen if I'm incorrect.

**Comment by FreddyFish** [comment]
Well i never resolved it. But i just changed OS instead.
