### ISSUE TITLE
Gettext build fails on make check

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2301]
Gettext fails on make check. The only way I found to circumvent this is to edit /usr/local/lib/crew/packages/gettext.rb to this:
[gettext.txt](https://github.com/skycocker/chromebrew/files/1959281/gettext.txt)
Any suggestions?
EDIT: Notice the "exit 0" command at he bottom near def self.check.

**Comment by uberhacker** [comment]
@JL2210: Thank you for reporting.  Why are you compiling?  The binaries not working?  Also, please indicate your Chrome OS version along with your system specs.
```
$ cat /etc/lsb-release 
$ uname -a
```

**Comment by JL2210** [comment]
I restored a backup of my root directory and those commands work now. Here.
[uname-a.txt](https://github.com/skycocker/chromebrew/files/1962053/uname-a.txt)
[lsb-release.txt](https://github.com/skycocker/chromebrew/files/1962055/lsb-release.txt)

**Comment by uberhacker** [comment]
@JL2210: I'm guessing you won't need Chromebrew if you plan on using apt/dpkg as your package manager.  With that said, since Flint OS is running Chrome OS, I imagine it would be better to use Chromebrew.  I haven't tried Flint OS yet so I'm just speculating, however.

**Comment by JL2210** [comment]
Yes, I do plan on using them as my main package manager, in fact I have dpkg running right now, but one of the dependencies breaks when I try to install it: 'configure: error: not building from distributed tarball, gettext required' When I try to build gettext from source, it shows this error: 'In file included from message.h:23:0,
                 from x-awk.h:21,
                 from x-awk.c:24:
pos.h:21:20: fatal error: ../gnulib-lib/stddef.h: No such file or directory
 #include <stddef.h>
                    ^
compilation terminated.
make[5]: *** [Makefile:3366: xgettext-x-awk.o] Error 1
make[5]: *** Waiting for unfinished jobs....
Assembler messages:
Fatal error: can't create xgettext-x-csharp.o: No such file or directory
make[5]: *** [Makefile:3360: xgettext-x-csharp.o] Error 1
make[5]: Leaving directory '/usr/local/tmp/crew/gettext-0.19.8.1.tar.xz.dir/gettext-0.19.8.1/gettext-tools/src'
make[4]: *** [Makefile:2556: all] Error 2
make[4]: Leaving directory '/usr/local/tmp/crew/gettext-0.19.8.1.tar.xz.dir/gettext-0.19.8.1/gettext-tools/src'
make[3]: *** [Makefile:2026: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/gettext-0.19.8.1.tar.xz.dir/gettext-0.19.8.1/gettext-tools'
make[2]: *** [Makefile:1892: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/gettext-0.19.8.1.tar.xz.dir/gettext-0.19.8.1/gettext-tools'
make[1]: *** [Makefile:414: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/gettext-0.19.8.1.tar.xz.dir/gettext-0.19.8.1'
make: *** [Makefile:370: all] Error 2
gettext failed to build: `make V=0 -j2` exited with 2' I figured out how to correct this, as it is probably a build dependency, is to install icu4c. Without this package, xgettext fails to run. Then the buld fails with 'FAIL: test-sys_time
PASS: test-sys_types
PASS: test-sys_wait
PASS: test-term-ostream-xterm
PASS: test-init.sh
FAIL: test-thread_self
FAIL: test-thread_create
FAIL: test-time
FAIL: test-tls
PASS: test-u8-conv-from-enc
PASS: test-ctype_space
PASS: test-u8-width-linebreaks
PASS: test-dup-safer
PASS: test-unistd
FAIL: test-u16-mbtouc
FAIL: test-u8-check
FAIL: test-u8-cmp
PASS: test-u8-mblen
FAIL: test-u8-mbtoucr
FAIL: test-u8-prev
PASS: test-u8-strlen
PASS: test-u8-uctomb
FAIL: test-unsetenv
PASS: test-vasnprintf
FAIL: test-vasprintf
PASS: test-verify
PASS: test-verify.sh
PASS: test-vsnprintf
PASS: test-wchar
PASS: test-wcrtomb.sh
SKIP: test-wcrtomb-w32-1.sh
SKIP: test-wcrtomb-w32-2.sh
SKIP: test-wcrtomb-w32-3.sh
SKIP: test-wcrtomb-w32-4.sh
SKIP: test-wcrtomb-w32-5.sh
PASS: test-wctype-h
PASS: test-wcwidth
PASS: test-write
PASS: test-xalloc-die.sh
PASS: test-xmemdup0
PASS: test-xvasprintf
============================================================================
Testsuite summary for gettext-tools 0.19.8.1
============================================================================
# TOTAL: 197
# PASS:  173
# SKIP:  24
# XFAIL: 0
# FAIL:  12
# XPASS: 0
# ERROR: 0
============================================================================', which doesn't happen with my modification. I was hoping somebody could file a pull request with my modification, as well as with the new dependency, because I do not have authority to. On a side note, would you like a copy of the .rb file I made for dpkg? it should be platform independent, as it builds from source.

**Comment by JL2210** [comment]
My problem has been resolved, I had too many processes open at once. Thank you for all your help.
