### ISSUE TITLE
[dub] Error during install from source

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2332]
```
ldmd2: error while loading shared libraries: libLLVMXCoreDisassembler.so.5: cannot open shared object file: No such file or directory
```
It appears ldmd2 is looking for llvm version 5 shared objects instead of version 6.

**Comment by JL2210** [comment]
I'm going to work on a better D compiler than `ldc` and `dub`.

**Comment by cstrouse** [comment]
dmd would be nice but we still need to get ldc or the gnu d compiler working for the other architectures.

**Comment by JL2210** [comment]
GDC is available in tree starting with 8 AFAIK.
