### ISSUE TITLE
[kr] Unable to install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2346]
```
error: component 'rust-docs' for 'armv7-unknown-linux-gnueabihf' is unavailable for download
kr failed to install: `rustup install stable` exited with 1
```

**Comment by uberhacker** [comment]
I'm guessing the rust-docs is found with a different architecture than `armv7-unknown-linux-gnueabihf`.

**Comment by cstrouse** [comment]
Adding a conditional to do `rustup install stable-arm-unknown-linux-gnueabihf` might fix this. Also, there's a checksum mismatch on this since the source_url is set to be readme.md from master.
