### ISSUE TITLE
Unable to install crew

### ISSUE THREAD

**Issue by Bsalarius** [skycocker/chromebrew#2357]
## Description
When trying to install crew, it suggests a checksum mismatch. On visiting the download URL manually (https://dl.bintray.com/chromebrew/chromebrew/ruby-2.5.1-chromeos-x86_64.tar.xz), it returns a 403.

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.5.1-chromeos-x86_64.tar.xz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the ruby download.
```

## Versions and system information
chromebrew: (*not installed*)

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4765583
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={196C49C7-152F-499B-9C64-F5B8A89E43A4}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={196C49C7-152F-499B-9C64-F5B8A89E43A4}
CHROMEOS_RELEASE_BOARD=edgar-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=32
CHROMEOS_RELEASE_BUILDER_PATH=edgar-release/R67-10575.32.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.32.0 (Official Build) beta-channel edgar 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=10575.32.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.32.0
BUILD_ID=10575.32.0
NAME=Chrome OS
ID_LIKE=chromiumos
GOOGLE_CRASH_ID=ChromeOS
VERSION_ID=67
BUG_REPORT_URL=https://crbug.com/new
VERSION=67
HOME_URL=https://www.chromium.org/chromium-os
ID=chromeos

Model: Acer Chromebook 14 CB3-431-C5FM

Architecture: x86_64

What I think needs to be done:
- [ ] check why a 403 is returned rather than the file

**Comment by pcs3rd** [comment]
I am currently having the same issue when I try to run "install.sh", it returns this:
`install.sh: 15: [: -eq: unexpected operator
Downloading ruby...
install.sh: 57: install.sh: wget: not found
Verifying ruby...
sha256sum: ruby-2.0.0-p247-chromeos1-chromeos-x86_64.tar.gz: No such file or directory
ruby-2.0.0-p247-chromeos1-chromeos-x86_64.tar.gz: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
Verification failed, something may be wrong with the ruby download.`

Where is the download url pointing for ruby @skycocker?
it seems that the url for that ruby package has changed... 
also, "wget" is not installed on chromebooks by default. although, curl is...

**Comment by uberhacker** [comment]
@Bsalarius @pcs3rd: For some reason, Bintray has rate-limited the project.  I have opened a ticket with them and still waiting on their response.

**Comment by tgevaert** [comment]
It appears that the chromebrew bintray account is being rate limited.  Seems to have happened to [VerneMQ as well](https://twitter.com/der_graf/status/996130444163854338)

**Comment by skiman6010** [comment]
@uberhacker Do we have a way to build all core packages from source using the install command?

**Comment by pcs3rd** [comment]
@tgevaert is there any way to install for now? or do we have to wait for the issue to be resolved?

**Comment by skiman6010** [comment]
@pcs3rd You (and anyone with this issue) will have to wait until Bintray resolves the issue.

**Comment by KamilMalek** [comment]
So I guess no downloads available for now? I get `Checksum mismatch` for any package I try to upgrade/install.

**Comment by uberhacker** [comment]
Hey guys: Bintray has lifted the restrictions and you should be able to install now.  Thanks for your patience.  I'll try and make sure this doesn't happen again.

**Comment by uberhacker** [comment]
I will go ahead and close this issue since it is resolved.

**Comment by uberhacker** [comment]
@pcs3rd: Yes, it should be resolved.  It may be possible your last install attempt corrupted some files.  I would suggest the following:
```
$ sudo dev_install --reinstall -y
$ curl -Ls git.io/vddgY | bash
```

**Comment by pcs3rd** [comment]
@uberhacker, it is now actually downloading a file(s). Is there any clue as of to why the bintray was restricted?

**Comment by uberhacker** [comment]
@pcs3rd: We went over our disk usage quota.  I have removed older versions to reduce space.  They have expanded our limit and were talking about making it "unlimited" so we probably won't have this problem in the future.
