### ISSUE TITLE
LOTS of pull requests merged

### ISSUE THREAD

**Issue by thedamian** [skycocker/chromebrew#238]
Hello everyone.

The wise and amazing Skycocker has give me (and soon other) top contributors pull requests.

I'm going to start going through all the pull requests.

BUT I need YOUR help. Tell me WHAT you've done to test YOUR pull requests and why we (because there's more of us now) should accept it based on your extensive testing.

I've merged several of the ones that either I tested myself or were simply version upgrades (unless they touched in any way the main install.sh or crew.sh systems)

Please tell me which should be merged next, and why, and if I'm warranted with the comments I've made on ALL the pull requests that WEREN'T Merged.

**Comment by bfayers** [comment]
How open would you guys be to silly terminal games be put in? for example moonbuggy from the commodore 64.

**Comment by thedamian** [comment]
@bfayers the more the merrier. I have no objections to that. Your contributions so far have been 5 start!

**Comment by bfayers** [comment]
Cool. I'll put a pull request for that soon.

**Comment by bfayers** [comment]
Thoughts on making the python's have SSL support?

**Comment by thedamian** [comment]
I've managed to get python recompiled with SSL support (I think simply by including the openssl_devel project I added.

I needed it to install PIP by the simple command. (for work I was doing) So I think it's ready for that already. Just do a remove and reinstall.
