### ISSUE TITLE
Lua missing libraries doesn't work

### ISSUE THREAD

**Issue by jacksonbenete** [skycocker/chromebrew#2394]
## Description
Hello there,
Looks like Lua package doesn't work in my distriibution, this could be some problem with my machine or the package may be missing some dependencies/compiled wrong?

```shell
chronos@localhost / $ crew install lua
(i) lua: Lua is a powerful, efficient, lightweight, embeddable scripting language.
https://www.lua.org/
version 5.3.4
Package lua already installed, skipping...
Lua installed!
chronos@localhost / $ lua --version
lua: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
chronos@localhost / $ lua
lua: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: `0.4.3`

ChromeOS: `64.4.36 (Developer Build - neverware) developer-build chromeover64`

Model: Desktop

Architecture: `x86_64`

## Further

```shell
chronos@localhost / $ crew remove lua
Lua removed!
chronos@localhost / $ crew install lua
lua: Lua is a powerful, efficient, lightweight, embeddable scripting language.
https://www.lua.org/
version 5.3.4
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
Performing post-install...
Lua installed!
chronos@localhost / $ lua
lua: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
```

**Comment by uberhacker** [comment]
@jacksonbenete:  Thank you for reporting this issue.  It appears you haven't upgraded your version of crew lately.  The latest version of lua is 5.3.4-1.  You might try the following:
```
$ crew update
$ crew upgrade
```
Let me know if you still have trouble after running these commands.

**Comment by uberhacker** [comment]
@jacksonbenete: Try this:
```
$ crew install readline7
```
Can you please share your system info?  Chrome OS version and Chromebook model?
```
$ uname -a
$ cat /etc/lsb-release
```

**Comment by jacksonbenete** [comment]
@uberhacker Installing readline7 directly with crew did the trick!

Should I close the issue?

I will give you the asked informations anyways, I'm using a desktop with Neverware Chromium OS.

```shell
chronos@localhost / $ uname -a
Linux localhost 4.14.31+ #1 SMP Fri Apr 27 03:17:06 UTC 2018 x86_64 Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz GenuineIntel GNU/Linux
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server.neverware.com/
GOOGLE_RELEASE=64.4.36
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BRANCH_NUMBER=80
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_PATCH_NUMBER=2018_04_27_0520
CHROMEOS_RELEASE_TRACK=developer-build
CHROMEOS_RELEASE_DESCRIPTION=64.4.36 (Developer Build - neverware) developer-build chromeover64
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=64.4.36
CHROMEOS_AUSERVER=https://cloudready-free-update-server.neverware.com/update
```

**Comment by uberhacker** [comment]
Glad that worked.  Thank you for the information.  Just curious why your install needed readline version 7 instead of version 6.  Neverware installs a bunch of extra stuff on top of the base Chrome OS so that might be the issue.

**Comment by jacksonbenete** [comment]
Hello there @uberhacker ,

Sometime ago I've openned this issue from Chromium OS.
Since then I've worked a lot on that machine and I have decided to purchase a Chromebook.
I've experienced the same issue and have solved exactly the same way.

So, the issue isn't about Neverware extra stuff. It's very easy to solve as you teach me above, but I thought I should report it again since I've experienced the same issue in Chrome OS.

Could this be the case to include readline7 installation inside Lua package script? But I don't know what could mean changing realine6 to readline7 (probrably in the entire chromebrew system) in the package manager stability. 

```
chronos@localhost / $ uname -a
Linux localhost 3.18.0-18048-gb6252ef470ae #1 SMP PREEMPT Wed Jul 11 19:48:10 PDT 2018 x86_64 Intel(R) Celeron(R) CPU N3060 @ 1.60GHz GenuineIntel GNU/Linux
chronos@localhost / $ cat etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4884711
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={7834CC99-3294-421F-9963-028D7D6512CA}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={7834CC99-3294-421F-9963-028D7D6512CA}
CHROMEOS_RELEASE_BOARD=celes-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=1
CHROMEOS_RELEASE_BUILDER_PATH=celes-release/R69-10866.1.0
CHROMEOS_RELEASE_BUILD_NUMBER=10866
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10866.1.0 (Official Build) dev-channel celes 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_VERSION=10866.1.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10866.1.0
```

**Comment by uberhacker** [comment]
@jacksonbenete: PR #2455 should fix this in future installs.  Thanks
