### ISSUE TITLE
Xiwi support? A step closer, I guess...

### ISSUE THREAD

**Issue by 00fer0n1** [skycocker/chromebrew#2401]
Whilst this doesn't have to do with Chromebrew in particular, I really couldn't find a better place to put this. Remember Xiwi, how Crouton uses the display and makes a window? I found a post here a while ago on how it should be ported to Chromebooks directly (e.g. using Chromebrew), and I thought about that.

I have a CELES, a cheap Chromebook that works fine for me. I used to try Crouton, it was too slow. I then discovered Chromebrew and decided to make do with the command line.

I recently tried Chromebrew to see how it worked, and then I thought "Wait, what if I just moved xiwi to Chrome OS?" I decided to do that stupid idea and move it using the shared Downloads folder. Surely enough, it didn't work. Thankfully, it showed the issue -- xinit wasn't installed, and that was the problem. With that in mind, I retried it and... it didn't work. Xorg wasn't detected. Soo... I apparently forgot how to install Xorg, and I did a couple of different ways before just doing 'crew install xorg-server' because I'm dumb. Then I compiled XTerm to test it out and... error.

```
X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.14.13+ x86_64 
Current Operating System: Linux localhost 3.18.0-17027-gd16cd4c724f6 #1 SMP PREEMPT Mon May 14 23:19:45 PDT 2018 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=6a290a18-9959-5647-87ff-e7ec0e52af0b/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 3584000 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=3584000 alg=sha1 root_hexdigest=4ba28cc0e64eecd779fdbb08a7663d8f15faf0c6 salt=62445f5d2da056977edaa1326cb3cb7573fa2dec673f9b43f4ce7f6dec08c815" noinitrd vt.global_cursor_default=0 kern_guid=6a290a18-9959-5647-87ff-e7ec0e52af0b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 22 March 2018  01:06:45PM
 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/chronos/user/.local/share/xorg/Xorg.0.log", Time: Wed May 30 22:35:00 2018
(==) Using system config directory "/usr/local/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/chronos/user/.local/share/xorg/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^Z
```

Still, I think that this is a step forward. Can anyone help me with this?

**Comment by uberhacker** [comment]
@Axloqsizlik: The GUI is still very much a work in progress.  Based on the errors, it appears you are attempting to access a device that doesn't exist.  I'm not sure what can be done other than reading the error logs and trying to resolve.

**Comment by JL2210** [comment]
@Axloqsizlik, QEMU is an example of a program that does work. To file an issue on Crouton's website, please go to [here.](https://github.com/dnschneid/crouton)
Xinit does not currently work.

**Comment by bhtm** [comment]
@Axloqsizlik there is a chromebrew Xwayland X11 server that does run.  For me on an Asus 302 the keyboard isn't working; running Xwayland from a Xenial crouton chroot also has the same keyboard for me.

But note, I'm not sure what you meant by crouton is too slow; but, anything X11 running when running from /usr/local isn't going to be faster than in a crouton chroot.

**Comment by thedamian** [comment]
am I missing something? 

Crouton and xiwi have long been working. Heck I just did a PR over at the "visual studio code for chromebook" which of course uses xiwi and crouton to achieve this and that's been out for years?

what am I missing?

**Comment by uberhacker** [comment]
@thedamian: I assume you are referring to https://github.com/headmelted/codebuilds?  I wonder if it's possible if we could get VSC working on the Chromebook without Crouton?  This would be revolutionary for sure.

**Comment by thedamian** [comment]
@uberhacker that would be a dream come true. Although through chrouton it works ok. I have access to the local computer and since it's has it's own term (console) I have full access to the crouton full VM. so there's some amazing opportunity. 

If I could work on nothing else. getting VS Code to work on chromebook without crouton or the new linux app functionality coming to chromebook I'd spend all my days on that.

**Comment by Axloqsizlik** [comment]
I found out one of the problems. Xiwi config files are not there.

**Comment by ukscone** [comment]
I was googling around to see if there was any way to get GUI programs working with chromebrew as I have a few programs (VirtualT, trs80 model100 emulator & pterm, terminal for use with Plato systems, and some other emulators) I always put on computers I have access to and they are all gui'd and stumbled across this from the crouton github https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29 
I've got sommelier built and seeming to run by copying some libs from /usr/local/lib to /usr/local/lib64 and still plodding along but was curious if anyone has got it working yet or can even tell me why it won't work

**Comment by ukscone** [comment]
btw this is where I got to

----
chronos@localhost /media/removable/home/ukscone/sommelier $ ./sommelier -X --x-display=:0 --no-exit-with-child /bin/sh =c "./sommelierrc"
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 952
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 870
Warning: Unknown scale factor: 833
Warning: Unknown scale factor: 769
Warning: Unknown scale factor: 667
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/misc/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/TTF/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/OTF/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/Type1/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/100dpi/
_FontTransOpen: Unable to Parse address ${prefix}/share/fonts/X11/75dpi/
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE) 
Fatal server error:
(EE) Failed to activate virtual core keyboard: 2(EE) 
chronos@localhost /media/removable/home/ukscone/sommelier $

**Comment by ukscone** [comment]
a little more fiddling and I have xeyes running :)

https://twitter.com/ukscone/status/1026607571401158657

need to try a few more things but the above link seems to have most of the process

**Comment by ukscone** [comment]
i stand on the shoulders of giants :)

if i hadn't been so dense last night I could probably have got this working last night and the process atm isn't quite straight forward although i'm sure that's just because I don't quite get how things hook together in chromeos and chromebrew and i do something "weird" due to an irrational fear of wearing out soldered in emmc so mount a usb drive over /usr/local.

not sure how easy this would be to integrate properly into chromebrew but I hope it could be.

all credit though goes to Dave Thwaites on the Crouton github repo and to all involved with chromebrew. i'm just the idiot who tried it

**Comment by ukscone** [comment]
while I try to remember what I did so others can repeat the process.

i followed the instructions from https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29

downloaded libxkbcommon-0.5.0 source (iirc everything else required is already in crew) built libxkbcommon and moved the so.0.0.0.0 file from /usr/local/lib to /usr/local/lib/lib64 and recreated the libxkbcommon.so and libxkbcommon.so.0 in .../lib64 to point to libxkbcommon.so.0.0.0.0. changed the sommelier Makefile to set the XWAYLAND_PATH to point to /usr/local/bin then installed anything it complained about not finding from crew and that seems to be it.

to test i downloaded xeyes and xterm and anything they complained about not finding i installed via crew and so far everything seems to work.

**Comment by JL2210** [comment]
I'll add a package for this.

**Comment by ukscone** [comment]
argh getting closer to getting visual studio code running. missing one lib that doesn't seem to be in crew already and can't get it built manually. oh rodents

**Comment by ukscone** [comment]
![screenshot 2018-08-07 at 12 29 10 am](https://user-images.githubusercontent.com/3171454/43754514-471984fe-99d9-11e8-9786-2a527ea63b2a.png)

arduino ide looks like it's working as does fltk
![screenshot 2018-08-07 at 12 04 58 am](https://user-images.githubusercontent.com/3171454/43754543-61fbf900-99d9-11e8-8a49-16b7da50bc4d.png)

anyone got anything specific i should try?

**Comment by ukscone** [comment]
had to remove chromebrew supplied libsdl and rebuild from libsdl.org tarball but now have sdltrs working :) one of my goto emulators. beginning to get quite happy now

**Comment by JL2210** [comment]
How did you get around the systemd dependency?

**Comment by ukscone** [comment]
the version of sommelier mentioned in https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29 doesn't have one.

**Comment by JL2210** [comment]
OK. I'll just remove it. That version is old, anyway.

**Comment by ukscone** [comment]
i tried pulling the latest version of sommelier and had a load of stuff it needed I couldn't immediately put my hand to. virtwnd or something comes to mind (sorry memory a bit fuzzy) so I then went back to follow the instructions exactly and use the commit they used. might be worth creeping forward a few commits until we start to hit problems but 1st I want to get this to be a documented idiotproof install before I start fiddling again

**Comment by JL2210** [comment]
I'm using 0.20. Versioned packages are nice when upgrading. I had to use a workaround with git because they compress their tarballs on the fly.

**Comment by JL2210** [comment]
It works!

**Comment by ukscone** [comment]
Woot! is 0.20 before or after that commit?

**Comment by JL2210** [comment]
After.

**Comment by ukscone** [comment]
cool. a versioned version is much better than a random long numeric commit reference

**Comment by JL2210** [comment]
What's the lib that VS is missing?

**Comment by ukscone** [comment]
several but almost everything but libgconf-2.so.4 are available in chromebrew iirc

**Comment by JL2210** [comment]
Got it.

**Comment by superloach** [comment]
I'm thinking since the addition of #2520 this issue should be closed?

**Comment by JL2210** [comment]
I agree. @uberhacker?

**Comment by JL2210** [comment]
@ukscone You mentioned that you could run an SDL app when rebuilding libSDL. How did you do that? I get a display similar to `X display is not available` on every SDL app I use.

**Comment by ukscone** [comment]
@JL2210 It's been a while but I think I just rebuilt SDL turning on nearly every option I could but I might be mistaken. I'll see if I can find notes from then for you

**Comment by Merith-TK** [comment]
Would love for this @ukscone as i feel it would be truly amazing if brought to reality

**Comment by ukscone** [comment]
not been able to find my notes (think i reused that USB drive) and i'm tied up for a few days but as soon as i'm free (maybe thursday or friday) i'll see if i can replicate getting sldtrs working again. Though I honestly think I just did a normal rebuild from the source tarball and enabled everything sane and it just worked

**Comment by JL2210** [comment]
Xiwi doesn't work in Chromebrew, it's a Crouton-specific script. If you
don't mind, could you close this?

**Comment by Merith-TK** [comment]
@ukscone could you send me a email so we can have our conversation away from here?
