### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by jkrepko** [skycocker/chromebrew#2404]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@jkrepko: Did you forget to fill out your issue details?

**Comment by uberhacker** [comment]
Closing due to lack of response.
