### ISSUE TITLE
two quick questions....

### ISSUE THREAD

**Issue by minektur** [skycocker/chromebrew#242]
I'm making a package for rclone  (gdrive command line tool).  I was planning on just using their pre-build binaries.  I am currently using one I downloaded and manually dropped in /usr/local/bin and it seems to work just fine, if slow.

I know we dont quite have arm support yet, but is there or will there be a cannonical way to find the target platform?  so I can grab the right binary?  It looks like there isn't a good way to support the use case of "figure out my architecture and then download the right flavor binary" in a crew recipe...  Not that it matters quite yet...

Second on vanilla chromeos do you guys know of some way to unpack a zip file?  I know I can open it in the file app graphically and copy stuff out of it.... but that doesn't work for crew.  I guess I could also port and make a recipe for unzip....

**Comment by minektur** [comment]
note:  I could do it with either version of crew-installed python... but I'd hate to have the whole python runtime be an "unpack" dependency for this...

**Comment by minektur** [comment]
note 2:  I believe that I could make something work with perl's IO::Uncompress - with a 5 line perl script so that is the way I'll go if I dont fine anything else

**Comment by bfayers** [comment]
well the c100pa and the xe303c12 (samsung cb 1) are perfectly happy being specified as "armv7l"

**Comment by thedamian** [comment]
I have an unzip.rb package I still haven't uploaded.
But you're asking so that it's part of the system just like support to tar.gz and tar.xz are right?

It's never come up as most packages have at least one version out there in tar.gz or tar.xz format (even if it also has a .zip version)

And you're right. If the GUI file manager can unzip there should be somewhere some binary that can unzip (and that we can hook into)

as for "figuring out which platform" what do you mean? The system is able to figure out if you're on a x86 (32bit or 64bit) or an "arm" AND since there is only one version of chromeOS then there's no need to find out anything else? Or are you thinking about something else?

**Comment by minektur** [comment]
What started me on this is wanting to make an rclone package.  it allows rsync-like commands to a variety of cloud providers (including google drive).  It is theoretically possible to build rclone from source, but it has go as a dependency and they provide binaries for a variety of platforms, including an x86-64 linux binary which works on chromeos (intel).  I presume the 32-bit arm linux binary will also work... but I can't test it because of lack of hardware.

The binaries are distributed in zip files... and the source too, unless you clone from github.

So then I got sidetracked into 'unzip' support.  In my package, I could unzip the binaries  with python, with perl, or (soon with your package) ruby.  But I figure that an unzip binary would be a useful package so I'm making a package of http://www.info-zip.org/UnZip.html and will use that for my rclone unpacking.

The FreeBSD port of UnZip has a couple of security patches that haven't made it into the upstream so I'll probably include those.  See: https://svnweb.freebsd.org/ports?view=revision&revision=405286


Anyway, my questions were "is there an easy way to unzip" which I haven't found so I'm making a package for that, and "if we support arm, is there an easy way (e.g. uname -a) kind of cannonical way to see whether I'm on ARM or X86 so I can grab the right binary.  I dont know chromebrew packages support conditionally getting different sources depending on a run-time something like platform...  If there isn't then we should probably just make arm and x86 specific versions of packages and modify the crew binary (ruby script...) to pick the right one.  Or something else I haven't yet thought of.

I can't see where the unzip functionality in the graphical file manager lives in chromeos because the file manager is just another browser tab and I dont see an easy way of scripting it.  I'm all ears if you know how.

**Comment by bfayers** [comment]
packages have a 
```
  binary_url ({
    i686: "https://dl.dropboxusercontent.com/u/14799278/crew/jdk8u112-i686.tar.gz",
    x86_64: "https://dl.dropboxusercontent.com/u/14799278/crew/jdk8u112-x86_64.tar.gz",
    armv7l: "https://dl.dropboxusercontent.com/u/14799278/crew/jdk8u22-armv7l.tar.gz"
  })
```
bit and it just decides via the crew command which uses uname -m
