### ISSUE TITLE
crew install options

### ISSUE THREAD

**Issue by KBPratap** [skycocker/chromebrew#2427]
Is there a way to install packages without the confirmation prompt?

Something like

```shell 
    crew install --assume-yes node
```

**Comment by uberhacker** [comment]
@KBPratap: Yes, see below:
```
yes | crew install node
```
The node package is really just an alias (aka fake package) to nodebrew which requires more to install, however.  See https://asciinema.org/a/eBRmUTWYKzekmctc8lmeyKnec.  You might also want to check out https://github.com/skycocker/chromebrew/wiki/FAQ.
