### ISSUE TITLE
ARM packages and ChromeOS 67.x

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2430]
## Description
After an upgrade of ChromeOS from 66.x to 67.x, many arm (armhf) packages previously installed on my Acer R13 stopped working. Technically, I don't know if any of the crew packages still worked at that point.

Symptoms: entire OS and crosh commands would work as expected, but as soon as I launched bash (crosh> shell) and tried to execute something as simple as less -- core dump. Native (non-crew) binaries like those in /bin would still work. Conversely, all crashing binaries would be from /usr/local/.

## Versions and system information
chromebrew: 0.4.3

ChromeOS: 67.x -- latest official ARM version as of this post -- sorry I cannot be more specific -- I rolled back chromeos on that machine soon after.

Model: Acer Chromebook R13

Architecture: aarch64

## Additional information

The following is pure speculation on my part, but I've been through something similar before, so this might be of some value:

After each crash of a /usr/local binary, dmesg would contain a record of the form 'such and such app generated an unhandled level 3 translation fault (11)', very similar to this one documented here: http://macchiatobin.net/forums/topic/coherency-problem-with-cci-setup/ <-- that is on a cortex-A72 linux board running an aarch64 kernel (4.4.x) and userspace.

In the chromeos case, it would be an 'unhandled level 3 translation fault (11)'.

Now, ChromeOS 67.x is said to contain Specter ARM countermeasures -- special compiler techniques might have been introduced, runtime buffer- as well as kernel-level behavioral changes. A total recompile of crew packages with newer compilers might be required.

**Comment by skiman6010** [comment]
Did you read the FAQ and try the fix listed there at the top? https://github.com/skycocker/chromebrew/wiki/FAQ

```
$ sudo rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by blu** [comment]
Nope, I didn't realize there was already a FAQ entry for that, given how soon official 67 came out, but of course it's been on the dev channel for months -- my bad. Thanks for quick resolution, I'll try it later today.

**Comment by skiman6010** [comment]
No problem! Let me know if that doesn't work and we can debug more!

**Comment by uberhacker** [comment]
@blu:  Thank you for reporting.  I haven't updated my arm system yet but if I have any problems, I will definitely let you know.  FYI, for now, you can only install binary packages since the compiler is broken.  We're still working on a fix.

**Comment by blu** [comment]
I've upgraded the same machine to chromeos 68.x beta, and pulled chromebrew anew. None of the packages I use segfaults now, but there's another issue: nothing provides the file '/usr/local/include/sys/types.h' -- that used to be in glibc223, so gcc7 is not particularly useful now -- headers as trivial as stdint.h rely on that sys/types.h
