### ISSUE TITLE
bind package not finding library when running dig, nslookup

### ISSUE THREAD

**Issue by cygnus8595** [skycocker/chromebrew#2447]
## Description
I installed the bind package to get dig, nslookup working on command line but when I run either command, I get a missing library error:

If you executed a specific command:
```shell
dig google.com
```

Output:
```shell
dig: error while loading shared libraries: libcom_err.so.3: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: 0.4.3

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: Dell Chromebook 11 (3120)

Architecture: x86_64

**Comment by cygnus8595** [comment]
A little more information. Looking at /lib64, I have libcom_err.so.2 listed but not libcom_err.so.3.

**Comment by minektur** [comment]
On the off chance that you are not the person I've been talking to on reddit, you might be able to at least work around this issue by uninstalling the package and building it from source.

    crew remove bind
    crew install -s bind

As for what is wrong with the package, I'll defer to others with an ENOTIME error :)

**Comment by cygnus8595** [comment]
Yup, it's the same guy from reddit. I followed your advice and built from source, now it works just fine. Thanks for all your help!
