### ISSUE TITLE
Add packages to support vs code studio

### ISSUE THREAD

**Issue by gt945** [skycocker/chromebrew#2449]
## Description
I build vs code studio on my chromebook plus successful.
https://imgur.com/I83EyaT

But there are some dependency packages missing in chromebrew.
```
dbus-glib
libgconf
libsecret
```
can some one help to add these package?

## Versions and system information
chromebrew: `crew --version`
0.4.3

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4856647
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: chromebook plus

Architecture: `uname -m`
aarch64

**Comment by skiman6010** [comment]
This is awesome! We'll get these packages incorporated as soon as possible!

**Comment by gt945** [comment]
@skiman6010  thank you!
When you try to build vs code after you add these packages, you may meet some issues, hope below links help
https://github.com/Microsoft/node-pty/issues/209
https://github.com/Microsoft/vscode/issues/53634

**Comment by thedamian** [comment]
the chromebook plus has crostini. so I have  a feeling you've "built it" there.

Having said that we have a visual studio solution that works now (and I'm using on a chromebook pro WITHOUT any crostini) here: https://code.headmelted.com/

Plus. a request for a package sounds like you're offering to create those packages.

**Comment by uberhacker** [comment]
@thedamian: I believe what @gt945 is trying to do is get VSC working in ChromeOS without Crostini or Crouton.  This would be revolutionary.  Since most Chromebooks with less than 4 gb of RAM and late model processors cannot run either Crouton or Crostini due to resource limitations, this would be a welcome addition.

**Comment by gt945** [comment]
@thedamian I know cb plus support crostini, but I don't like run it in VM or crouton, so I build vs code with chromebrew.
Acctually I hope some one can help to create and maintain these package, not me
@uberhacker you are right, chromebrew is awesome, I can run vs code like a native app. There is a condition that the cb should support wayland, because I run vs code with Xwayland and weston. not sure whether old cb are support wayland

**Comment by uberhacker** [comment]
@gt945: [GUI](https://github.com/skycocker/chromebrew/issues/889) support is still a work in progress.  If you would like to get involved in improving it, we could sure use the help.

**Comment by VitaliyKulikov** [comment]
@gt945 any progress with put `vscode` to `crew` repo?

**Comment by JL2210** [comment]
Yeah. See #2517

**Comment by uberhacker** [comment]
Fixed in #2536.
