### ISSUE TITLE
mongodb not installing

### ISSUE THREAD

**Issue by langsor** [skycocker/chromebrew#2463]
mongodb is not installing

```shell
chronos@localhost / $ crew install mongodb
mongodb: MongoDB is the next-generation database that lets you create applications never before possible.
https://www.mongodb.com/
version 3.0.8
Precompiled binary available, downloading...
/usr/local/bin/crew:348:in `read': No such file or directory @ rb_sysopen - ./mongodb-linux-x86_64-3.0.8.tar.gz (Errno::ENOENT)
        from /usr/local/bin/crew:348:in `block in download'
        from /usr/local/bin/crew:346:in `chdir'
        from /usr/local/bin/crew:346:in `download'
        from /usr/local/bin/crew:531:in `install'
        from /usr/local/bin/crew:429:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:716:in `<main>'
chronos@localhost / $ crew remove mongodb
Package mongodb isn't installed.
```

## Versions and system information
chromebrew: `crew --version`
```shell
chronos@localhost / $ crew --version
I have no idea how to do --version :(
```

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={1E454867-ACF6-5F8B-091F-145680D4A7F5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={1E454867-ACF6-5F8B-091F-145680D4A7F5}
CHROMEOS_RELEASE_BOARD=wolf-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=wolf-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel wolf 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: YOUR MODEL HERE
Dell Chromebook 11
Intel Celeron 2955U 1.40GHz
2 Processors

Architecture: `uname -m`
x86_64

**Comment by JL2210** [comment]
Check your Internet connection and try again. Do you use a firewall or proxy?

**Comment by langsor** [comment]
Thank you for your response.
It is not my internet connection. 
I use neither firewall or proxy. 
I've had no difficulty installing several other packages already over the last year or so.

**Comment by uberhacker** [comment]
@langsor: There is an update to mongodb.  We can try the most recent version and see if that works.

**Comment by JL2210** [comment]
```
crew update && crew upgrade && crew install mongodb
```

**Comment by langsor** [comment]
Thank you. That worked!

**Comment by JL2210** [comment]
Could you please close this issue if it works? The close button is next to the comment button.
