### ISSUE TITLE
Add recursive build from source feature

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2471]
Can we add an option like crew -S install ... to recursively build package and all dependencies from source?

**Comment by uberhacker** [comment]
Sounds like a pretty good idea.  Wanna create a PR?

**Comment by JL2210** [comment]
Don't know how. Never learned Ruby, other than the experience that I've had
with Chromebrew. Crew looked like gobbledygook to me when I tried to do
this.

**Comment by JL2210** [comment]
Could you give me any help on this, @uberhacker?
