### ISSUE TITLE
A plea for a better sed

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2474]
Could you, please, consider adding sed to the packages? There is already an up-to-date sed under /bin, but somebody at google decided it was more secure to provide sed pre-built with forced-sandbox mode, thus breaking the e/r/w commands. It might be safer for the general populace, but for developer mode it's just counter-productive!

**Comment by uberhacker** [comment]
@blu: I agree!  This is really a pain.  Whoever decided sandbox mode was more secure is misguided.  I'm working on a solution.

**Comment by blu** [comment]
Thank you, @uberhacker -- that was truly nice! New sed works are expected.

**Comment by JL2210** [comment]
I could've helped with this... I built it myself without crew.
