### ISSUE TITLE
TiLP in Chromebrew? (Attempted solutions)

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2489]
TiLP is a tool for transferring data to/from TI calculators, and would be useful to many students using Chromebooks, such as myself! I'd like to share my experiences trying to install it in Chrome OS, request assistance, and propose adding it to the Chromebrew repos once it's working.

Problems:
 - Automated installer fails
   - Permission is denied when attempting to execute sanity checks.
   - Full output: https://pastebin.com/Ku8t93pa
 - Automated installer fails as root
   - Complains about not being able to work in read-only directories.
   - Modifying `SRCDIR` to somewhere read/write just gives same errors as with no root.
   - Full output: https://pastebin.com/G7wLZZ0B
 - Build instructions are wrong
   - `INSTALL` file says to use `./configure && make && make install`, but there isn't `./configure`.
   - Full output: https://pastebin.com/u43s8vRW
 - Guessed that `autoconf configure.ac` might do the trick
   - Prints the contents of `configure.ac`, and then complains about macros (with or without root).
   - Full output: https://pastebin.com/a5x7pL2n

Possible issues once we get further:
 - Says it depends on GTK
   - Might be the issue with `autoconf`, said something about a KDE-related macro.
   - Compiled, TiLP can run with `--no-gui`.
   - Weston *is* in the works, and could help with this?

It seems like some editing of the installer script might make it work, but I have no clue where to start. I'm willing to dive much deeper into getting this working, but would love to have support from more experienced Cros "porters" 😝 Hope this won't be too hard to get working and into the repo!

TiLP Homepage: http://lpg.ticalc.org/prj_tilp/
TiLP Installer: http://lpg.ticalc.org/prj_tilp/download/install_tilp.sh
TiLP Source: https://www.ticalc.org/pub/unix/tilp.tar.gz

**Comment by uberhacker** [comment]
@superloach: I went ahead and made an attempt to add this package in PR #2492 (depends on PR #2491).  Since the [GUI](#889) is still a work in progress, your mileage may vary.  Please give it a go when you get a chance and let me know if you have any success.  Feel free to post your results.  This project is a great way to help move the GUI work along.

**Comment by superloach** [comment]
Awesome, thanks! I tried installing it, and it worked with just a little tweaking.

Everything compiled, but the TI libraries ended up in `lib` instead of `lib64`. I used `sudo mv $(sudo find /usr/local/lib -name libti*.so.*) /usr/local/lib64/` to fix this.

After that TiLP would run properly, but still didn't work for my Nspire. 😕 I got the same errors as on my RPi, so I think that could just be a problem with my calc's OS version.

Thanks again for all the help, and I'm glad that it seems to at least be *somewhat* functional... I'll get back to you on actual transfer capabilities. 😅👍

**Comment by superloach** [comment]
TiLP's dev told me that the `--no-gui` mode was slightly broken, so I'm going to try installing a DE on my Raspberry Pi later.

You were right about this being a good way to push along GUI work! 😂

**Comment by JL2210** [comment]
@superloach, do you want two versions of tilp? There is a tilp1 with a configure script that would be easier to install.

**Comment by debrouxl** [comment]
The generated configure scripts were removed years ago from what became the tilibs and tilp_and_gfm repositories, because besides the fact that they take up a bit of space in the repository and clutter the diffs, IIRC, the main rationale was that some Linux distros patch their autotools, and what I generate on Debian does not necessarily suit all other distros.
IOW, any version of libticonv, libtifiles, libticables, libticalcs, gfm or tilp which has a configure script is ludicrously outdated, and nobody wants to use or package that :)

**Comment by JL2210** [comment]
OK. How would you go about installing it now? With no `make install`, how would you do it?

**Comment by JL2210** [comment]
On your comment above: The /usr/local directory is owned by you if you have crew installed, so no need to use sudo.

**Comment by uberhacker** [comment]
@JL2210: Just so you know, the current `tilp` package installs correctly on x86_64 (lib files stored in /usr/local/lib64 instead of /usr/local/lib) and there are pre-built binaries so you won't need to recompile everything from the source.  @superloach: Did you get a chance to try the recent package binary install yet?

**Comment by superloach** [comment]
I did not yet, thanks for letting me know!

**Comment by superloach** [comment]
@uberhacker: It seems to work just as it did before, thanks for getting that binary out!
Now the next step is GUI, so that TiLP will actually function. 😛

**Comment by JL2210** [comment]
I have some libs on JL2210/chrome-bin for this, if you want to try them.

**Comment by JL2210** [comment]
Should be fixed by sommelier. Try `sommelier -X tilp|

**Comment by debrouxl** [comment]
As I wrote in #2492 , a second step, once the dust of X support has settled (good work on that, I suppose :) ) would be to quit using the upstream install_tilp.sh targeting end users, and split the current tilp package into its constituents: libticonv, libtifiles, libticables, libticalcs, (gfm and) tilp. install_tilp.sh contains lots of checks and comments for end users, which are unneeded on any distro: packagers know their stuff.

All of the other package managers I know of rightfully choose to create one package per autotools definition. However, at first, if you find that 6 packages are too much, a good tradeoff is to split the current tilp package in two chunks: the 4 libti* on the one side, gfm + tilp on the other side. After I used the six former SVN repositories as a single Git repository for a while, tilibs + tilp_and_gfm is how I split the code in the end.
Splitting the libs from gfm + tilp would avoid reinventing the wheel if, some day, someone packages TilEm for Chromebrew.

**Comment by superloach** [comment]
Thanks for pointing out the issue of splitting the packages.
I am also totally blown away by how well Sommelier is working so far, I even got qemu running!

However, there still seem to be some issues with TiLP. It detects my nspire properly (woo!), but complains about libusb write permissions. I have a feeling @debrouxl may be the best to ask about this, I remember there being issues with usb permissions before.

https://i.imgur.com/AU4eKci.png
https://i.imgur.com/eR1W5KX.png

**Comment by JL2210** [comment]
@superloach, I have this almost ready.

**Comment by superloach** [comment]
Awesome, thanks! Just wanted to let you know how my testing had gone so far :)

**Comment by JL2210** [comment]
BTW, QEMU worked without sommelier.

**Comment by debrouxl** [comment]
Right before ending, install_tilp.sh prints the name of the file containing information about the one-time USB configuration required for running TILP without having to be root. On even remotely modern Linux distros, udev is the way to go.
The SCM version of that file is https://github.com/debrouxl/tilibs/blob/master/libticables/trunk/CONFIG .

**Comment by JL2210** [comment]
We got udev.

**Comment by debrouxl** [comment]
Alright.
Sorry for the delay replying to this thread. My e-mail provider's anti-spam infrastructure suddenly found it smart to mark e-mail notifications for #2489 and #2520 as spam (sigh), and I failed to browse the spam box in the Web UI for a couple weeks.

**Comment by JL2210** [comment]
No worries. This works fine now. You can rest easy.
