### ISSUE TITLE
problems with readline

### ISSUE THREAD

**Issue by ukscone** [skycocker/chromebrew#2515]
i'm having problems with anything that links to libreadline. anyone have any ideas?

/usr/local/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/7.3.0/../../../../lib64/libreadline.so: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /usr/local/lib64/gcc/x86_64-cros-linux-gnu/7.3.0/../../../../lib64/libreadline.so when searching for -lreadline
/usr/local/bin/ld: /lib64/libreadline.so.6: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /lib64/libreadline.so.6 when searching for /lib64/libreadline.so.6
/usr/local/bin/ld: cannot find /lib64/libreadline.so.6
collect2: error: ld returned 1 exit status

**Comment by doriclazar** [comment]
You might have built some of the packages with [readline7.rb](https://github.com/skycocker/chromebrew/blob/master/packages/readline7.rb) and now have only [readline.rb](https://github.com/skycocker/chromebrew/blob/master/packages/readline.rb) installed.
Latest update included [buildessential.rb](https://github.com/skycocker/chromebrew/blob/master/packages/buildessential.rb) which requires readline...
Did you update chromebrew recently?

**Comment by ukscone** [comment]
earlier this morning. oh rodents

**Comment by doriclazar** [comment]
I got /lib64/libreadline.so.6 which is on read-only.
If I remove both /usr/local/lib64/libreadlines, gcc and ld use the one from the root, so I'm unable to reproduce.

**Comment by JL2210** [comment]
Try to remove readline and readline7, and then reinstall readline only.

**Comment by ukscone** [comment]
i borked my chromebrew install so i have to restart from scratch so hopefully it won't happen this time

**Comment by JL2210** [comment]
K. be more careful next time. I hate ld.

**Comment by ukscone** [comment]
darn fresh install of chromebrew and basically the same problem with libreadline

**Comment by JL2210** [comment]
Show me.

**Comment by ukscone** [comment]
![screenshot 2018-08-07 at 12 31 04 pm](https://user-images.githubusercontent.com/3171454/43789377-d09d3b6c-9a3d-11e8-9e82-0adc1cd5c0ea.png)

**Comment by JL2210** [comment]
You're on canary. Please try again on stable.

**Comment by ukscone** [comment]
i wiped my /usr/local (reformatted the partition i mount over) fresh install of chromebrew, installed xwayland + deps and mc + deps (also unzip doesn't work from mc as tries to use it from /usr/bin) and that's it

**Comment by ukscone** [comment]
switching back to stable fixed it so guess this can be closed

**Comment by JL2210** [comment]
Look forward to fixing this in the future.

**Comment by JL2210** [comment]
@uberhacker: Look into this. It could very well be an issue in the future.
