### ISSUE TITLE
Remove packages from buildessential

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2542]
If you don't mind, could you remove some unnecessary packages from buildessential? Crew takes 30+ min. to install on a slow Internet connection. At this point, the list is getting really long.

**Comment by JL2210** [comment]
Considering I have to reinstall 2+ times a day on a 300KB/s connection, that's a lot.

**Comment by uberhacker** [comment]
What do you consider unnecessary?  And YOU are welcome to submit a PR.

**Comment by JL2210** [comment]
How about remove the buildessential package and only install the very necessary ones, like gcc and binutils?

**Comment by JL2210** [comment]
And maybe ones that Chrome OS breaks, like sed?

**Comment by uberhacker** [comment]
You could try this.  Install crew fresh and then do the following:
```
$ tar czvf ~/crew-backup.tar.gz /usr/local
```
When you are ready to restore:
```
$ rm -rf /usr/local
$ tar xvf ~/crew-backup.tar.gz
```

**Comment by JL2210** [comment]
That's a good idea? Why not make buildessential a real package and do that, without all the perl stuff?

**Comment by uberhacker** [comment]
If you are working with gui apps, you will have to reinstall a bunch of packages anyway.

**Comment by JL2210** [comment]
Yeah. Keep in mind, I only have 32GB of space, and after crew is installed, I only have 4 or 5.

**Comment by uberhacker** [comment]
That is a ton of space.  I work on VMs with like 10 gb total. LoL

**Comment by JL2210** [comment]
At one point in installing QEMU with a fresh crew, I run out of space. The VMs are very bare bones. They don't have the double-layer update system. That makes them twice as small. 2GB more for you.

**Comment by JL2210** [comment]
Oh. These stupid Android apps are taking up my space. Closing.
