### ISSUE TITLE
Failed installed (not enough disk space) and then successive install fails with JSON parser error

### ISSUE THREAD

**Issue by xrd** [skycocker/chromebrew#2550]
## Description

I tried installing crew and the initial install failed because I did not have sufficient disk space. I removed some files, and when I attempted to reinstall, it looks like it succeeded, but any attempt to install files results in a JSON error. I had hoped that adding the debug and verbose envvars would trigger more context, but this did not work. I'm assuming there is a bad JSON file somewhere that needs updating or replacement...

```shell
$ DEBUG=1 VERBOSE=1 crew install file
Traceback (most recent call last):
        2: from /usr/local/bin/crew:86:in `<main>'
        1: from /usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
```

## Versions and system information
chromebrew: 
```$ crew --version
1.0.3
```
ChromeOS: 
```
$ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F26D159B-52A3-491A-AE25-B23670A66B32}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F26D159B-52A3-491A-AE25-B23670A66B32}
CHROMEOS_RELEASE_BOARD=link-signed-mp-v5keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=link-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel link 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0
```

Model: Chromebook Pixel (2013)

Architecture: `uname -m`: x86_64

**Comment by uberhacker** [comment]
@xrd: See if this fixes your issue:
```
$ sudo rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by xrd** [comment]
I'm a little loathe to do that since I have other things in /usr/local. Is there a way to troubleshoot what is actually failing here beyond obliterating the entire local directory?

**Comment by uberhacker** [comment]
What do you have in `/usr/local` that you want to save?  If it's in an isolated location, maybe can you create a backup and then restore afterwards?  I'm guessing the files under here are too corrupted to try and fix.  It's easier just to start over.

**Comment by JL2210** [comment]
@xrd, if you hav Crouton installed, it doesn't actually remove the Crouton files. Try this:
```
rm -rf /usr/local
ln -s /mnt/stateful_partition/crouton/chroots /usr/local/
curl -Ls https://goo.gl/fd3zc | bash /dev/stdin -b
```

**Comment by JL2210** [comment]
If you don't believe me, try this:
```
rm /usr/local/etc/crew/device.json
curl -Ls https://git.io/vddgY | bash
```

**Comment by xrd** [comment]
device.json was empty:

```
chronos@localhost ~ $ ls -l /usr/local/etc/crew/device.json 
-rw-r--r-- 1 chronos chronos 0 Aug 14 09:06 /usr/local/etc/crew/device.json
```
Deleting it has allowed installation to continue. Thanks everyone. I'll update this when it is complete to confirm these instructions worked.

**Comment by xrd** [comment]
`crew install emacs` works great. Thanks!

**Comment by JL2210** [comment]
@xrd, you really should try the wiping `/usr/local` strategy. That would work better.

**Comment by JL2210** [comment]
lol, `emacs`.

**Comment by uberhacker** [comment]
Who in their right mind would want to suffer from carpal tunnel syndrome?  Use vim instead. :)

**Comment by xrd** [comment]
http://ergoemacs.org/emacs/Matz_Ruby_how_emacs_changed_my_life.html
