### ISSUE TITLE
Vim Complaining about Libpython

### ISSUE THREAD

**Issue by skiman6010** [skycocker/chromebrew#2554]
```
vim: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by uberhacker** [comment]
@skiman6010: It looks like vim needs recompiled to use the 3.7 libraries instead.  See if building from source works.  If so, we can submit new binaries.

**Comment by skiman6010** [comment]
New Python3.7 update screwed with threading. Vim 8.1 fixes the issue or removing python3 support.
