### ISSUE TITLE
Mono without fsharp, fsc and fsi

### ISSUE THREAD

**Issue by ijean** [skycocker/chromebrew#2555]
Hello,

I've installed mono with crew, however it seems that there is no F# support included. I was able to run all the expected C# commands: csc, csharp, csi but none of the F# components.

How can I add F# support to Mono ?

Regards
Jean

**Comment by ijean** [comment]
I've tried to build Fsharp from source, but I always get an SSL handshake error when I run make.

**Comment by JL2210** [comment]
Are you behind a firewall?

**Comment by JL2210** [comment]
You could try this: `sed -i 's,https,http,g' Makefile`

**Comment by ijean** [comment]
Doesn't seem to work even with the change from https to http.

Here is an example of the output:

```
Errors in packages.config projects
    Unable to find version '7.0.6' of package 'FsLexYacc'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (One or more errors occurred.)
      One or more errors occurred.
      A call to SSPI failed, see inner exception.
      Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
        at /usr/local/tmp/crew/mono-5.10.1.47.tar.bz2.dir/mono-5.10.1.47/external/boringssl/ssl/handshake_client.c:1132
    Unable to find version '0.2.0' of package 'MicroBuild.Core'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (One or more errors occurred.)
      One or more errors occurred.

```

**Comment by ijean** [comment]
@JL2210 it seems that F# has a hard dependency on MSBuild. On macOS, Hombrew builds Mono, MSBuild and finally F# (in this order). See [https://github.com/Homebrew/homebrew-core/blob/master/Formula/mono.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mono.rb).

I've tried to adapt the Homebrew formula to Chromebrew without success. Maybe someone with more experience in both Ruby and Chromebrew can do it.

**Comment by ijean** [comment]
I was able to get rid of the SSL error messages by running:

```
cert-sync --user /etc/ssl/certs/ca-certificates.crt
```
After the above, the only missing piece for successfully building F# with Chromebrew is MSBuild.

**Comment by JL2210** [comment]
You could try https://github.com/Microsoft/msbuild

**Comment by saltedcoffii** [comment]
Mono now has F# support as per a very old now merged PR.
