### ISSUE TITLE
[binutils] failure to link against ChromeOS-originating DSOs on R68 

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2563]
Hello,

It appears that since R68 stable (I can only confirm about stable ATM) some brand-new ELF section appeared in ChromeOS-originating DSOs, which trips ld from package binutils. Here are the symptoms:

```
/usr/local/bin/ld: /usr/lib/libEGL.so: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /usr/lib/libEGL.so when searching for -lEGL
/usr/local/bin/ld: cannot find -lEGL
/usr/local/bin/ld: /usr/lib/libGLESv2.so: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /usr/lib/libGLESv2.so when searching for -lGLESv2
/usr/local/bin/ld: cannot find -lGLESv2
collect2: error: ld returned 1 exit status
```

Is there a chance our linkers acquired understanding of this new 'RELR' section?

## Versions and system information
chromebrew: 1.0.3

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4922387
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=71
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R68-10718.71.2
CHROMEOS_RELEASE_BUILD_NUMBER=10718
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=68
CHROMEOS_RELEASE_DESCRIPTION=10718.71.2 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=2
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10718.71.2
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10718.71.2

Model: Lenovo Chromebook N23 Yoga

Architecture: aarch64

**Comment by JL2210** [comment]
Are you on beta, dev or canary? If so, see if the issue still persists on stable.

**Comment by JL2210** [comment]
Not so sure about that. 67 is stable right now, unless my new Chromebook is EOL.

**Comment by JL2210** [comment]
@blu: This is fine. It's trying to use the system libraries to link the application. Try `crew install mesa` and see if this fixes the issue.

**Comment by JL2210** [comment]
The system libraries are incompatible like that because they are the Chrome OS/Chromium OS specific versions. If we use the ones provided by `crew`, they work, because the source code has not been modified (in most cases) from the original. The only exception would be old or incompatible code.

**Comment by blu** [comment]
@JL2210 I think you're misunderstanding the issue.
1) R67 is currently stable, but that happened after the stable channel was reverted from 68 -- that's how I got 68 stable on my chromebook
2) I don't want to install the mesa package -- libEGL was just an example. The same holds true for libGLESv2, which is not provided in the mesa package for my GPU.

**Comment by skiman6010** [comment]
@JL2210 68 is stable but the update was paused because of intermittent wifi issues, nothing that would affect this issue.  Look at his system information. 

```
CHROMEOS_RELEASE_CHROME_MILESTONE=68
CHROMEOS_RELEASE_DESCRIPTION=10718.71.2 (Official Build) stable-channel hana
```

We should be treating 68 as stable still even though it was pulled.

**Comment by blu** [comment]
Thank you, @skiman6010!

I've reverted my everyday chromebook to R67 for the time being, but I expect more .relr.dyn issues in the near future if ld is left unattended for long. So let me know if I can be of service -- I have another chromebook on R68 beta ATM.

**Comment by uberhacker** [comment]
If I understand this issue correctly, this affects both `ld` and `lld`?  If that is the case, then both the `binutils` and `llvm` packages will need updates.  There is currently an update for `llvm` (version 6.0.1) and I have tried updating it without success.  I did try to integrate lldb into the update so that may be a cause of the problem.  One _VERY ANNOYING_ thing about ld is it errors out sometimes when it thinks libraries should be located in `/usr/lib` instead of `/usr/local/lib`.  I believe this has something to do with the path search order but not exactly sure.

**Comment by blu** [comment]
@uberhacker Hi, Ed

Your understanding is correct, since that's what I implied in the OP, but today I finally managed to get both my chromebooks in a R67-vs-R68 side-by-side check, and here are some clarifications missing from the OP:

1) Under R68 the issue manifests with ld (package binutils), but does _not_ manifest with lld (package llvm) -- the latter actually handles .relr.dyn sections properly!

   Version of binutils where ld does not handle .relr.dyn sections: 2.31.1
   Version of llvm where lld does handle .relr.dyn sections: 6.0.0-1

2) Under R67 the issue does not manifest -- neither /usr/lib/libEGL.so nor /usr/lib/libGLESv2.so contain the .relr.dyn section (they contain the traditional .rel.dyn)

3) The issue might also be present on x86_64 R68, but I can only confirm its presence on aarch64, as I don't have access to an x86_64 chromebook.

**Comment by uberhacker** [comment]
Not sure if this is related, but I get the following error while attempting to compile lldb (release 67):
```
/usr/local/bin/ld: warning: libncurses.so.6, needed by /usr/local/lib64/gcc/x86_64-cros-linux-gnu/7.3.0/../../../../lib64/libedit.so, may conflict with libncurses.so.5
/usr/local/bin/ld: lib64/liblldbHost.a(Host.cpp.o): undefined reference to symbol 'dladdr@@GLIBC_2.2.5'
/usr/local/bin/ld: /usr/local/lib64/../lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[801/807] Building CXX object source/API/CMakeFiles/liblldb.dir/__/__/scripts/LLDBWrapPython.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by blu** [comment]
This looks like a dependency was omitted from the build cmd. That symbols should be provided by libdl.so -- check if the library is in the link dependencies.

**Comment by uberhacker** [comment]
Interestingly enough, after I upgraded to release 68, now I get an entirely new error:
````
[793/807] Linking CXX executable bin/lldb-argdumper
FAILED: bin/lldb-argdumper 
: && /usr/local/bin/c++  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -w -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -O3 -DNDEBUG  -Wl,-rpath-link,/usr/local/tmp/crew/lldb-6.0.1.src.tar.xz.dir/lldb-6.0.1.src/build/./lib64  -Wl,-O3 -Wl,--gc-sections tools/argdumper/CMakeFiles/lldb-argdumper.dir/argdumper.cpp.o  -o bin/lldb-argdumper  -Wl,-rpath,"\$ORIGIN/../lib64" -lpthread lib64/liblldbUtility.a -ledit -lcurses /usr/lib64/libform.so /usr/local/lib64/libpanel.so /usr/local/lib64/libpython3.7m.so /usr/local/lib64/libxml2.so -lcurses /usr/lib64/libform.so /usr/local/lib64/libpanel.so /usr/local/lib64/libpython3.7m.so /usr/local/lib64/libxml2.so /usr/local/lib64/libLLVMBinaryFormat.so.6.0.1 /usr/local/lib64/libLLVMSupport.so.6.0.1 && :
/usr/local/bin/ld: /lib64/libncurses.so.5: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /lib64/libncurses.so.5 when searching for /lib64/libncurses.so.5
/usr/local/bin/ld: cannot find /lib64/libncurses.so.5
collect2: error: ld returned 1 exit status
[794/807] Building CXX object source/API/CMakeFiles/liblldb.dir/SystemInitializerFull.cpp.o
[795/807] Building CXX object source/API/CMakeFiles/liblldb.dir/__/__/scripts/LLDBWrapPython.cpp.o
ninja: build stopped: subcommand failed.
lldb failed to build: `ninja lldb` exited with 1
```

**Comment by uberhacker** [comment]
It appears the linker insists on libncurses.so.5.  I imagine if the linker looks for libncurses.so.6 instead, this may fix the issue.

**Comment by JL2210** [comment]
If it's looking for libncurses.so.5, we need libncurses.so.5. The ABIs are almost entirely different.

**Comment by blu** [comment]
Actually now you've stepped into the same issue this ticket was created for:
```
/usr/local/bin/ld: /lib64/libncurses.so.5: unknown type [0x13] section `.relr.dyn'
```

Welcome to R68 ;p

**Comment by JL2210** [comment]
Yeah. The system libraries are f*cked up. We need a  crew version.

**Comment by JL2210** [comment]
Those, BTW, are exported dynamic symbols. They were created by `gcc -Wl,-E`

**Comment by blu** [comment]
The system libraries are fine -- it's the new section I referred to in the OP. We need a newer ld (binutils) or alternatively we need to use lld.

**Comment by JL2210** [comment]
No newer ld. We can try the system provided one. Hint Hint, @uberhacker. (Try `/usr/bin/ld`)

**Comment by JL2210** [comment]
Opened issue https://bugs.chromium.org/p/chromium/issues/detail?id=883719

**Comment by uberhacker** [comment]
I doubt the Chromium OS team will want to support Chromebrew but I guess it's worth a shot. :)

**Comment by JL2210** [comment]
Sorry. That approach is too old. The Binutils version used to build Chrome OS is 2.27. Binutils 2.27 does not work with GCC 7+

**Comment by JL2210** [comment]
Looks like we have to change the default linker to `lld`.

**Comment by JL2210** [comment]
I think it's safe for this to be closed. The issue isn't causing any fatal errors anymore, is it?

**Comment by uberhacker** [comment]
Yes, everybody should be on at least release 70 or higher by now unless they haven't turned their Chromebook on in the last year.

**Comment by bsiegert** [comment]
I am still hitting this with an up-to-date Chromebrew (did `crew update` followed by `crew upgrade` just now) on Version 74.0.3729.0 (Offizieller Build) dev (64-Bit).

The linker that gcc uses is still `ld` from binutils 2.31.1.

```
chronos@localhost /usr/local/tmp $ cat foo.c
int main() { return 0; }
chronos@localhost /usr/local/tmp $ gcc -o foo foo.c -lnsl
/usr/local/bin/ld: /usr/lib/../lib64/libnsl.so: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /usr/lib/../lib64/libnsl.so when searching for -lnsl
/usr/local/bin/ld: /usr/lib64/libnsl.so: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: skipping incompatible /usr/lib64/libnsl.so when searching for -lnsl
/usr/local/bin/ld: cannot find -lnsl
collect2: error: ld returned 1 exit status
```

So I assert that this is not fixed at all. How do I switch over to using `lld` as linker, short of rebuilding gcc from source?

**Comment by JL2210** [comment]
`gcc -o foo foo.c /usr/local/lib64/libnsl.so` should fix your issue.

If you REALLY want to switch to `lld`, run `crew install ld_default; ld_default l`

**Comment by bsiegert** [comment]
Thanks, `ld_default` helped.
