### ISSUE TITLE
[isl] dangling symlink in package

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2567]
Hello,

Package isl on arm has a dangling symlink: `/usr/local/lib/libisl.so.15`. That does not seem to create any issues (so far), so just a heads-up.

## Versions and system information
chromebrew: 1.0.3

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4856647
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: Lenovo Chromebook N23 Yoga

Architecture: aarch64

**Comment by uberhacker** [comment]
@blu: Thank you for the feedback.  Do you receive a warning message on any specific commands?

**Comment by blu** [comment]
No warnings as far as I remember. I just noticed the symlink while re-installing buildessentials after an OS revert.

**Comment by JL2210** [comment]
Yeah, it did. Could you reinstall isl with `crew remove isl && crew install isl` and give me the output of `ls -la /usr/local/lib`

**Comment by blu** [comment]
After a fresh reinstall of isl:
```
$ ls -l /usr/local/lib/libisl*
-rw-r--r--. 1 chronos chronos 2994792 Aug 20 16:03 /usr/local/lib/libisl.a
-rwxr-xr-x. 1 chronos chronos     936 Aug 12 23:55 /usr/local/lib/libisl.la
lrwxrwxrwx. 1 chronos chronos      16 Aug 12 23:55 /usr/local/lib/libisl.so -> libisl.so.19.1.0
lrwxrwxrwx. 1 chronos chronos      27 Aug 12 23:55 /usr/local/lib/libisl.so.15 -> /usr/local/lib/libisl.so.20
lrwxrwxrwx. 1 chronos chronos      16 Aug 12 23:55 /usr/local/lib/libisl.so.19 -> libisl.so.19.1.0
-rwxr-xr-x. 1 chronos chronos 1965872 Aug 20 16:03 /usr/local/lib/libisl.so.19.1.0
-rw-r--r--. 1 chronos chronos    2891 Aug 12 23:55 /usr/local/lib/libisl.so.19.1.0-gdb.py
```
Notice how `/usr/local/lib/libisl.so.15` links to a missing file.
