### ISSUE TITLE
Control-n opens new browser window instead of moving to next line in Emacs

### ISSUE THREAD

**Issue by shakthimaan** [skycocker/chromebrew#2576]
## Description
I have installed chromebrew on an Asus Chromebook C201PA, and installed Emacs. I am able to open Emacs from the shell (Control + Alt + T). But, when I try to move the cursor down using Control + n, the browser treats it as input, and opens a new window! How can I instruct a command specific for Emacs and not the browser?

## Versions and system information
chromebrew: `crew --version`
1.0.3

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4856647
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_RELEASE_BOARD=veyron_speedy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=veyron_speedy-release/R67-10575.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=10575
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=67
CHROMEOS_RELEASE_DESCRIPTION=10575.58.0 (Official Build) stable-channel veyron_speedy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10575.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10575.58.0

Model: Asus Chromebook C201PA

Architecture: `uname -m`
armv7l

**Comment by skiman6010** [comment]
Your best option is to use the superior vim instead of emacs. :) Just kidding.

Joking and flamewars aside, the best way to get around this is to use the crosh window extension. https://chrome.google.com/webstore/detail/crosh-window/nhbmpbdladcchdhkemlojfjdknjadhmh?hl=en-US
" When clicked, this app opens a new crosh window without any chrome. This way, Ctrl-N/T/etc go to crosh and aren't picked up by Chrome."

**Comment by JL2210** [comment]
Yay! I can search in `nano` now!

**Comment by shakthimaan** [comment]
Emacs a day, keeps the vi-zing away! I am fine with using crosh window extension. 

Thanks!
