### ISSUE TITLE
Chromebrew Logo?

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2579]
It has come to my attention (while working on [FellippeHeitor/qb64.org#2](https://github.com/FellippeHeitor/qb64.org/pull/2)) that Chromebrew doesn't have a logo, and I'd definitely be willing to create one.

What do you think of combining these two in some way, since this is essentially the Chrome version of Brew on Macs?
![image](https://user-images.githubusercontent.com/30514424/44378891-5c645700-a4d1-11e8-9c9c-5db1927db094.png)![image](https://user-images.githubusercontent.com/30514424/44378939-9fbec580-a4d1-11e8-8ec9-d933bcb0b6fb.png)

I'll have a few examples ready in a minute here 👍

**Comment by uberhacker** [comment]
I like it!  We could replace the apple on top of the mug with half of the chrome logo.

**Comment by uberhacker** [comment]
As a parody, you could put a crostini on the side. ;)

**Comment by superloach** [comment]
hahaha, good one

**Comment by superloach** [comment]
i also thought of replacing the apple with the chrome logo, or removing the apple and having the mug's contents be the Chrome logo. I'll have rough examples for both ready quite soon
(*wink wink nudge nudge we need gimp, pixlr is torture*)

**Comment by superloach** [comment]
Phew, finally finished these. What do you think @uberhacker?
![image](https://user-images.githubusercontent.com/30514424/44380065-2a55f380-a4d7-11e8-9b76-7f68cb5e1ba1.png)![image](https://user-images.githubusercontent.com/30514424/44380071-317d0180-a4d7-11e8-9c28-7435579d85b9.png)
(Please ignore the terrible editing for now, pixlr really sucks and I'll find something better to use for the final version 😅)

**Comment by superloach** [comment]
Before I submit a PR, how does this look?
https://superloa.ch/src/chromebrew-4096.png

**Comment by superloach** [comment]
Here @JL2210 😁

**Comment by JL2210** [comment]
Thanks! Let me take a look.

**Comment by uberhacker** [comment]
@superloach: Very nice looking logo there!

**Comment by superloach** [comment]
Thanks! There's one spot I might clean up later, but it should be fine at smaller resolutions.

I'm being baffled by xz, give me a minute to just install GIMP and export it with something other than 0 compression 😁

**Comment by JL2210** [comment]
Simple. `xz -z9e image.png`. It's file compression, not image compression. You need to install `xz_utils` to get it working.

**Comment by JL2210** [comment]
@uberhacker This has been solved.
