### ISSUE TITLE
Package Request - GIMP

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2580]
~~Unlike my previous package requests, I haven't made much progress on getting this compiled.~~
Ironically enough, I've done most of the work on this so far! 🤣
This will probably be a pretty big project, lots of libraries from various places. I'll go ahead and make a list of dependencies.
- [x] GLib
- [x] GObject
- [x] Cairo
- [x] Pango
- [x] librsvg
- [x] libpng
- [x] libexif
- [x] libtiff
- [x] libjpeg
- [x] liblcms
- [x] pkg-config
- [x] fontconfig
- [x] aalib
- [x] zlib
- [x] python
- [x] babl - #2581
- [x] Python-Cairo - #2583
- [x] json-glib - #2584
- [x] GEGL - #2586 
- [x] libmypaint-gegl - #2587 
- [x] libexiv2 - #2593 
- [x] gexiv2 - #2594 
- [x] mypaint-brushes - #2595 
- [x] PyGObject - #2596 
- [x] GTK+ - #2589 and #2598 **TEMPORARY FIX**
- [ ] webkit - #2590 
- [x] poppler-data - #2597 
- [x] [libwmf](http://wvware.sourceforge.net/libwmf.html)

Also GIMP is *totally* a dependency for #2579 😆

**Comment by JL2210** [comment]
Sure.

**Comment by skiman6010** [comment]
Hey @superloach, I just wanted to let you know that linking the check boxes to the downloads and package websites is super helpful and I love that you did that! It is a gigantic help! For that, I shall do a package for you.

**Comment by superloach** [comment]
Haha, no problem! Very excited to see where we can take this. 😃

**Comment by superloach** [comment]
It looks like [Python-Cairo is in PyPI](https://pypi.org/project/pycairo/), should we just require Python and run a `pip install` before build?
Or would it make more sense to put that into a separate package?

**Comment by superloach** [comment]
Went ahead and submitted a PR to add `pycairo`, following the same format as `six`.

**Comment by superloach** [comment]
Moving on to GEGL, `./configure` exits with this:
```
checking for GLIB - version >= 2.44.0... yes (version 2.56.1)
checking for DEP... no
configure: error: 
        *** GLib not found. You can find it on ftp://ftp.gtk.org
        *** Errors follow:
            No package 'json-glib-1.0' found
```

**Comment by superloach** [comment]
Moving on to GEGL, `./configure` exits with this:
```
checking for GLIB - version >= 2.44.0... yes (version 2.56.1)
checking for DEP... no
configure: error: 
        *** GLib not found. You can find it on ftp://ftp.gtk.org
        *** Errors follow:
            No package 'json-glib-1.0' found
```
I'll add `json-glib` to the dependency list.

**Comment by superloach** [comment]
There we go, GEGL!

**Comment by superloach** [comment]
LibWMF seems a bit unnecessary, it converts an old Microsoft image format. If people ask for it, we can add it, but for now I'll just skip it.

**Comment by superloach** [comment]
Does it matter if we use WPE or WebKitGTK+?

**Comment by uberhacker** [comment]
I have no clue but I have a feeling this is gonna be a fat package. :)

**Comment by superloach** [comment]
Oh wait, the GIMP From Source docs link to WebKitGTK+. Updating the link to [this](https://wiki.gnome.org/action/show/Projects/WebKitGtk), whoops.

**Comment by superloach** [comment]
Yeah, WebKit is massive... It's only needed for the help browser, perhaps we could separate WebKit into another issue and recompile GIMP once that's finished?

**Comment by superloach** [comment]
I've got a package written for GIMP, first test build is running now!

**Comment by uberhacker** [comment]
Wow @superloach, you have done a great job organizing and building this project.

**Comment by superloach** [comment]
Thanks! I just know this is a missing piece for a lot of Chrome OS users, and I'm glad to contribute as much as I can to this project. 😃

**Comment by superloach** [comment]
Alright, here's the package I wrote:
```ruby
require 'package'

class Gimp < Package
  description 'GIMP is a cross-platform image editor available for GNU/Linux, OS X, Windows and more operating systems.'
  homepage 'https://www.gimp.org/'
  version '2.10.6'
  source_url 'https://download.gimp.org/pub/gimp/v2.10/gimp-2.10.6.tar.bz2'
  source_sha256 '4ec8071f828e918384cf7bc7d1219210467c84655123f802bc55a8bf2415101f'

  depends_on 'glib'
  depends_on 'glib_networking'
  depends_on 'gobject_introspection'
  depends_on 'gtk2'
  depends_on 'gtk3'
  depends_on 'cairo'
  depends_on 'pango'
  depends_on 'librsvg'
  depends_on 'libpng'
  depends_on 'libexif'
  depends_on 'libtiff'
  depends_on 'libjpeg'
  depends_on 'lcms'
  depends_on 'pkgconfig'
  depends_on 'fontconfig'
  depends_on 'aalib'
  depends_on 'zlibpkg'
  depends_on 'python27'
  depends_on 'babl'
  depends_on 'pycairo'
  depends_on 'json_glib'
  depends_on 'gegl'
  depends_on 'libmypaint'
  depends_on 'sommelier'

  def self.build
    system "./configure --prefix=#{CREW_PREFIX}"
    system "make"
  end

  def self.install
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
  end
end
```
I know there are some redundant dependencies, I'll sort that out once the build is working.
However, the build *isn't* working. It exits with these errors:
```
Error: GIMP configuration failed.

  - Error: missing dependency gtk+-2.0 >= 2.24.10
      *** Test for GTK+ failed.
  - Error: missing dependency gexiv2 >= 0.10.6
  - Error: missing dependency libbzip2
      *** libbzip2 library not found
  - Error: missing dependency mypaint-brushes-1.0
  - Error: missing dependency rsvg >= 2.40.6
  - Error: missing dependency poppler-data >= 0.4.7
  - PyGTK 2.10.4 or newer
      *** Please install it, or skip building the python scripting extension by
      *** passing --disable-python to configure (but then you will not be able
      *** to use scripts for GIMP that are written in Python).
  - pygtk-codegen-2.0 script
      *** Please install it, or skip building the python scripting extension by
      *** passing --disable-python to configure (but then you will not be able
      *** to use scripts for GIMP that are written in Python).
```
- GTK+ looks like I just need `gtkmm2` and `gtkmm3`, but I can't install those due to a checksum mismatch on `cairomm`.
- Adding `gexiv2`, `mypaint-brushes`, and `poppler-data` to the dependency list.
- `bz2` and `librsvg` are installed, not sure what it needs.

**Comment by superloach** [comment]
Oh, and PyGTK sounds related to #2531.

**Comment by superloach** [comment]
Hopefully that will fix the GTK+ problem, still need to figure out poppler-data though.

**Comment by superloach** [comment]
I've already created one, but we're still having dependency issues. Some of libmypaint's dependencies have broken symlinks in their binaries, GIMP is asking for the deprecated PyGTK, and I'm still not sure if GTK+ is actually working.

**Comment by superloach** [comment]
Alright, I can confirm that gtkmm2 and gtkmm3 fix the GTK+ dependency. Confusing names, if you ask me.

**Comment by JL2210** [comment]
Is there a configure script? Try `./configure --help | grep disable | grep -i pygtk`

**Comment by superloach** [comment]
I don't really want to disable PyGTK, but for now I guess we can see if it lets GIMP build.

**Comment by JL2210** [comment]
If it's deprecated, you shouldn't use it.

**Comment by superloach** [comment]
This is a known problem with GIMP, but it's still needed for a lot of plugins to work.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885289

**Comment by JL2210** [comment]
Let me see your copy of the GIMP package.

**Comment by superloach** [comment]
```ruby
require 'package'

class Gimp < Package
  description 'GIMP is a cross-platform image editor available for GNU/Linux, OS X, Windows and more operating systems.'
  homepage 'https://www.gimp.org/'
  version '2.10.6'
  source_url 'https://download.gimp.org/pub/gimp/v2.10/gimp-2.10.6.tar.bz2'
  source_sha256 '4ec8071f828e918384cf7bc7d1219210467c84655123f802bc55a8bf2415101f'

  depends_on 'glib'
  depends_on 'glib_networking'
  depends_on 'gobject_introspection'
  depends_on 'gtk2'
  depends_on 'gtk3'
  depends_on 'cairo'
  depends_on 'pango'
  depends_on 'librsvg'
  depends_on 'libpng'
  depends_on 'libexif'
  depends_on 'libtiff'
  depends_on 'libjpeg'
  depends_on 'lcms'
  depends_on 'pkgconfig'
  depends_on 'fontconfig'
  depends_on 'aalib'
  depends_on 'zlibpkg'
  depends_on 'python27'
  depends_on 'babl'
  depends_on 'pycairo'
  depends_on 'json_glib'
  depends_on 'gegl'
  depends_on 'libmypaint'
  depends_on 'sommelier'
  depends_on 'libexiv2'
  depends_on 'gexiv2'
  depends_on 'mypaint_brushes'
  depends_on 'poppler_data'
  depends_on 'gtkmm2'
  depends_on 'gtkmm3'
  depends_on 'pygobject'

  def self.build
    system "./configure --help"
    system "make"
  end

  def self.install
    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
  end
end
```
I know there are some redundant dependencies, I'll fix them once the package can actually build.

**Comment by superloach** [comment]
Whoops, that should be `system "./configure --prefix=#{CREW_PREFIX}"`.

**Comment by superloach** [comment]
Here's yet another issue regarding GIMP not migrating from PyGTK to PyGObject: https://gitlab.gnome.org/GNOME/gimp/issues/339

**Comment by JL2210** [comment]
Looks like we need libWMF now.

**Comment by JL2210** [comment]
I have an old copy from a while back. Let me whip up a PR.

**Comment by superloach** [comment]
The only thing stopping me from getting a Python-less build is the issue of it not finding `libbzip2`, even though it's installed.

**Comment by superloach** [comment]
Oh, and the same thing with rsvg.

**Comment by JL2210** [comment]
Hmm....

**Comment by superloach** [comment]
Hey there, sorry I haven't worked on this in a while! Being a 15-year-old nonbinary chick has done annoying things to my brain, LOL.
Anyways, I'm going to try building it again tonight. It looks like some of the weird dependency errors may have been resolved by other projects, so hopefully it works a little better.

**Comment by JL2210** [comment]
How did it go?

**Comment by superloach** [comment]
Guessing this should be closed by #2764?

**Comment by JL2210** [comment]
Yep, awesome, right?

**Comment by JL2210** [comment]
Make that logo now, please. That would be awesome if you could.

**Comment by superloach** [comment]
GIMP is currently installing 👍
I actually made those logos on Pop!_OS, which works wonderfully on CYAN aside from 18.10 suddenly getting pushed and nearly bricking everything.
I'm very glad to be back in the swing of cros fiddling, though!

**Comment by superloach** [comment]
Aaand, missing libraries.
```
gimp: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
```

**Comment by JL2210** [comment]
Huh, @uberhacker? Tested on `x86_64`? Sounds like you got lazy.

**Comment by superloach** [comment]
Alright, `libomp.so` is in the `llvm` package. That needs to be a dependency.

Also seems to need an icon theme, should we add `hicolor_icon_theme` as a dependency or put a post-inst message in case people want to use their own?

**Comment by JL2210** [comment]
Yeah. That also needs to be in QEMU. I really wish we could seperate all these darn LLVM packages into seperate dependencies.

**Comment by superloach** [comment]
Yeah, I noticed that seemed odd.

Installing hicolor doesn't seem to fix this, unfortunately.
![image](https://user-images.githubusercontent.com/30514424/47435470-ad632680-d772-11e8-8328-6521ab8abed5.png)

Any ideas?

**Comment by JL2210** [comment]
Yeah... It doesn't help QEMU either. Notice the GUI issue is marked beta.

**Comment by uberhacker** [comment]
Whatever @JL2210.  We all know how well you test. :-P  @superloach: Sorry about the missing dependency.  I sent you a DM regarding the missing icons.  Config tip: If icons aren't rendering, from the menu select `Edit > Preferences > Icon Theme > Legacy > OK`.

**Comment by JL2210** [comment]
Can you send me a DM too? I test the packages. It's just that they're never good enough for you, and I only test once. lol.

**Comment by JL2210** [comment]
I think this can be closed. We already have Gimp. (needs `gnome_icon_theme`)

**Comment by satmandu** [comment]
It's more a `gcc_lib` breakage issue on newer milestone releases...
