### ISSUE TITLE
Package request - WebKitGTK

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2590]
Source: [webkitgtk-2.21.91.tar.xz](https://webkitgtk.org/releases/webkitgtk-2.21.91.tar.xz)
Build Instructions: [Building GTK - WebKit](https://trac.webkit.org/wiki/BuildingGtk)
Dependencies: [official install-dependencies script (pastebin)](https://pastebin.com/Kaw7K2WH)

**Comment by JL2210** [comment]
I think this can be closed, too.

**Comment by uberhacker** [comment]
This is actually still a legit request.  Several apps including gimp could benefit from this package.

**Comment by uberhacker** [comment]
Solved with `webkit2gtk.rb`?
