### ISSUE TITLE
Shasum mismatch of VS Code stable sources

### ISSUE THREAD

**Issue by davidschreiber** [skycocker/chromebrew#2599]
## Description

Running `crew install code` on the Pixelbook fails due to a shasum mismatch of the downloaded sources.

```
chronos@localhost / $ crew download code
code: Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS.
https://code.visualstudio.com/
version 1.25
No precompiled binary available for your platform, downloading source...
Checksum mismatch. :/ Try again.
```

The shasum of the source package served by Microsoft is:
```
5ef2f82e1272b0008a446fc8f62f9693e2af7c83d5922883ecbfd8a9986fd40b
```

I assume that the stable VS Code version has changed, and that the package script requires updating.

## Versions and system information
chromebrew: 1.0.3
ChromeOS: 10718.71.2
Model: Google Pixelbook
Architecture: x86_64

**Comment by uberhacker** [comment]
Closing to create an issue that generalizes the problem.  See #2603.
