### ISSUE TITLE
Installer doesn't check for errors

### ISSUE THREAD

**Issue by Warbo** [skycocker/chromebrew#2601]
## Description

I've tried running the install commands from the README on an Asus C202S ChromeBook. The `wget` version said `command not found`, so I tried the `curl` version:

```shell
curl -Ls git.io/vddgY | bash
```

This asked for a password with the "respect other users, etc." message from `sudo`, then said downloading Ruby. After downloading, it spewed out hundreds of `permission denied` and `file not found` errors. Then it did the same for Git, then finished with the claim "successfully installed", even though it wasn't.

It looks to me like the password was entered incorrectly, but the install script doesn't appear to be doing any sort of error checking or validation of its steps.

## Versions and system information

chromebrew: `crew --version`

Didn't manage to install.

ChromeOS: `cat /etc/lsb-release`

```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4613139
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C9947713-1881-D543-F1C0-900256540EFC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C9947713-1881-D543-F1C0-900256540EFC}
CHROMEOS_RELEASE_BOARD=terra-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=terra-release/R64-10176.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.76.0 (Official Build) stable-channel terra
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10176.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.76.0
```

Model: Asus C202S

Architecture: `uname -m`

```
Linux localhost 3.18.0-16387-g09d1f8eebf5f #1 SMP PREEMPT Sat Feb 24 13:30:32 PST 2018 x86_64 Intel(R) Celeron(R) CPU N3060 @ 1.60GHz GenuineInte
l GNU/Linux
```

**Comment by superloach** [comment]
I keep forgetting that there's a Chromebook which happens to have my name.
Anyways, did you "enable debugging features" on first boot? That's caused similar issues for me in the past.

**Comment by uberhacker** [comment]
Thank you for the feedback @Warbo.  I agree a more graceful exit from the installer would make sense.

**Comment by JL2210** [comment]
@superloach's issue is what caused this. You need to remount the root filesystem as read-write, log in as root, and set a password for chronos.

**Comment by JL2210** [comment]
How about `set -e`?

**Comment by Warbo** [comment]
@superloach Yes I did enable debugging features.

@JL2210 I've managed to SSH in as root and set a chronos password.

I re-ran the installer, and it seems to have worked, but now the `crew` command says:

```
$ crew
Traceback (most recent call last):
        1: from /usr/local/bin/crew:2:in `<main>'
/usr/local/bin/crew:2:in `require_relative': cannot load such file -- /usr/local/lib/crew/lib/color (LoadError)
```

Here's the contents of that path:

```
$ find /usr/local/lib/crew
/usr/local/lib/crew
/usr/local/lib/crew/lib
/usr/local/lib/crew/lib/package_helpers.rb
/usr/local/lib/crew/lib/package.rb
/usr/local/lib/crew/crew
```

Not sure if this is due to an incomplete installation, or something else.

**Comment by Warbo** [comment]
Rerunning the install script after adding /usr/local/bin and sbin to my PATH, it gave an sha256 mismatch for libssh2. I downloaded the file on  a separate machine, confirmed that it does have the right hash, `scp`'d it on to the chromebook and patched the chromebrew install script to use that file instead.

It now seems to be installing properly, fetching a bunch of programs (perl, gettext, flex, etc.) :)

**Comment by uberhacker** [comment]
@Warbo: It sounds to me like your initial install was incomplete and that messed things up on the second attempt.  In the future, if you run into errors like this, my best advice is to wipe the slate clean and start over:
```
$ sudo rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by JL2210** [comment]
Don't run crew as root. Try `rm -rf /usr/local/`.

**Comment by JL2210** [comment]
Just powerwash and don't enable debugging features. To get the same functionality, try ```shell
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 2 && sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 4
```

**Comment by Warbo** [comment]
@JL2210 All runs were as the `chronos` user; I logged in as root over SSH so I could run `# passwd chronos`, so that I had a working password for the install script's invocation of `sudo`. I used `su chronos` to actually run the script.

I didn't know that debugging features were problematic, thanks for the info and command (I just wanted to remove as many of Google's restrictions as possible ;) )

**Comment by JL2210** [comment]
@Warbo: How is this working for you now? Any issues?

**Comment by Warbo** [comment]
@JL2210 Chromebrew's working fine for me now; I wasn't sure whether to close this as my install works, or keep is open to track error handling.
