### ISSUE TITLE
[code] moving target source_url

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2603]
Apparently, the url to download the code package changes with every new release.  We will need to figure out how to pull specific versions instead, if possible.

**Comment by skiman6010** [comment]
Are you sure that link is static? Looks like it still might just download the newest stable release. 

I still propose we build from source like we do for most of our other packages. Would be easier to add arm support as well. https://github.com/Microsoft/vscode/releases

**Comment by JL2210** [comment]
Why not? Sure, but try it.

**Comment by uberhacker** [comment]
@skiman6010: No, I'm not sure but it looks like it could be unique based on the hex folder pattern.  Another issue might be that Microsoft conveniently deletes the older versions as new releases become available.  If that is the case, we would essentially have the same problem.  The issue with building from source is the result is a massive disk space hog (like in the order of 1gb+).  I have created a package that works for all architectures but I still think installing the binaries is a better solution.  If we can figure out a way to generate optimized binaries like Microsoft does with their releases, then it could work but why do that if they're already available?

**Comment by nfssfn** [comment]
Found an url for packages inside Portage database
```
SRC_URI="
     x86? (  https://vscode-update.azurewebsites.net/${PV}/linux-ia32/stable -> ${P}_i386.tar.gz )
     amd64? ( https://vscode-update.azurewebsites.net/${PV}/linux-x64/stable -> ${P}_amd64.tar.gz )
     "
```
So, for the latest version (1.26.1) it will look like
https://vscode-update.azurewebsites.net/1.26.1/linux-deb-x64/stable for deb
https://vscode-update.azurewebsites.net/1.26.1/linux-x64/stable for source

**Comment by uberhacker** [comment]
Thank you for the reference @nfssfn.  Do they have non-distro specific binaries?  We cannot use Debian-based or RedHat-based packages.

**Comment by nfssfn** [comment]
I think they have only .deb, .rpm and sources

**Comment by skiman6010** [comment]
@uberhacker Let's use the links you found and if it breaks again then we can try something else.

**Comment by uberhacker** [comment]
I noticed all official binary code versions 1.26+ are broken even if sommelier is running.  The last known working binary is 1.25.1.  I have tested this on i686 and x86_64.  Apparently, we now have no choice but to build from source.

**Comment by JL2210** [comment]
FYI, They're not sources. They are binaries.
