### ISSUE TITLE
Clang fails to compile C code

### ISSUE THREAD

**Issue by ijean** [skycocker/chromebrew#2605]
Hello,

I've installed the llvm package from Chromebrew. However, when I try to compile a simple C code with clang I get the following linker error:

```
chronos@localhost ~ $ clang test.c
/usr/local/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/local/bin/ld: cannot find -lgcc
/usr/local/bin/ld: cannot find -lgcc
```

**Comment by skiman6010** [comment]
```
$ clang test.c -v
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
 "/usr/local/bin/clang-6.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose
 -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/local/lib64/clang/6.0.0 -internal-isystem /usr/local/include -internal-isystem /usr/local/lib64/clang/6.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/chronos/user/Downloads -ferror-limit 19 -fmessage-length 130 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /usr/local/tmp/test-158a72.o -x c 
test.c
clang -cc1 version 6.0.0 based upon LLVM 6.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/lib64/clang/6.0.0/include
 /usr/include
End of search list.
 "/usr/local/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/local/bin/../lib64/crt1.o /usr/local/bin/../lib64/crti.o crtbegin.o -L/usr/local/bin/../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/bin/../lib -L/lib -L/usr/lib /usr/local/tmp/test-158a72.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed crtend.o /usr/local/bin/../lib64/crtn.o
/usr/local/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/local/bin/ld: cannot find -lgcc
/usr/local/bin/ld: cannot find -lgcc
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by blu** [comment]
@uberhacker: Well, it would create an implicit package dependency of llvm on gcc7, no?

**Comment by uberhacker** [comment]
That would be fine but we install llvm in Chromebrew "core" anyway so it's all good.

**Comment by JL2210** [comment]
Wait, you install llvm in buildessential? That is absolutely ridiculous. You don't need clang to compile hardly anything. Everything uses GCC now.

**Comment by blu** [comment]
@JL2210 Not sure what you're referring to by 'to compile anything' -- clearly both g++ and clang++ can compile the same source code, but in terms of quality of the generated binaries there are codes where g++ produced clearly-better output and codes where clang++ produces clearly-better output. In that regard, both compilers are needed by performance-sensitive codes.

**Comment by JL2210** [comment]
I suppose so. How long has it been since you've seen a program that uses strictly clang or clang++ for compilation?

**Comment by uberhacker** [comment]
@JL2210: Have you ever heard the saying _"There is more than one way to skin a cat"_?  The beauty of oss is there are many choices and you have the freedom to choose which works best for you.

**Comment by blu** [comment]
@JL2210 'Uses' as in 'mandates by the choice of its authors'? Daily. I work in a sphere best described as HPC and we pick our compilers extremely carefully (down to minor revisions), not because our code won't compile with another compiler (we're multiplat so we naturally maintain high code portability), but because our products can show double-digit-% performance deltas based on compiler choice alone. Likewise when I was in gamedev.

**Comment by JL2210** [comment]
Wow. Sorry. I guess I was being kind of oblivious to this kind of thing. There is a package called `pakextract` that I created a fork of, called `pakextract-ng`. The guy who created it used clang. I switched it over to GCC. I guess I need to do some more looking at he differences. I still have a lot to learn about C.

**Comment by blu** [comment]
@uberhacker Here's equivalent wrapper for clang (package llvm) -- it's actually notably simpler than the c++ version, as there are no missing includes, just a lib path (tested with some wayland code):

```
#!/bin/bash

gnuc_lib=/usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/7.3.0
clang $@ -B ${gnuc_lib} -L ${gnuc_lib}
```

**Comment by uberhacker** [comment]
@blu: This is great info.  I'll see if I can include this in the next update.  Just so you know, the bottleneck is this daggum lldb command.  It just refuses to compile no matter what I throw at it.

**Comment by JL2210** [comment]
Why would it not work? An issue with CMake?

**Comment by uberhacker** [comment]
Some weird python utf8 encoding error.

**Comment by JL2210** [comment]
Oh. Change your locales for glibc. I've always had that issue using ISO-####
