### ISSUE TITLE
pkg install not called for binary packages...

### ISSUE THREAD

**Issue by minektur** [skycocker/chromebrew#261]
So... every binary package we have just "unpacks" into /usr/local, it looks like - if I want to have a binary package that gets unpacked into a temp directory, and then I put stuff in the right place, there is no easy way to make it happen.

Would it be better to treat this as a "source" package and make a complicated build rule that downloads and unpacks the zip file, and then puts the stuff into the right places for installation, or would it be better to change this clause in 'crew'

if meta[:source] == true
          .......
         puts "Preconfiguring package..."
         @pkg.install

moving @pkg.install out of the conditional so it is run for every package (and of course there are a bunch of details  to work out...)

My ruby is.... not very strong - I'm tempted to make the hacky .rb file.

Either way, it looks like I'm going to have to modify crew to support unpacking zip files since it now only does stuff that "tar xf" supports...

**Comment by bfayers** [comment]
Hmm, not sure. Though I do know about the zip stuff. made a few pull reqs with source that came as zips had to re-pack as .tar.gz s was kind of annoying.

**Comment by lyxell** [comment]
Could you elaborate on the use case for this? When would it be needed?

**Comment by thedamian** [comment]
@minektur - I think you could simply use the current set of isntall and make methods to do your copying. Heck I do some deleting of pages in there. It's hacky. but it works.

@bfayers - YES, we need to be able to accept zip files. Unfortunately that'd need work in the install.sh to install the unzip you include in the unzip.rb package. so that it'd be ready when we do the code changes to crew to need it.

**Comment by minektur** [comment]
Ok - I've read the code, played with it, and now I understand where I was confused.

As things are currently implemented, binary packages for chromebrew MUST be pre-prepared specifically as chromebrew packages ahead of time.  What I mean is that it must be ready to be unpacked directly into /usr/local.  (though this isn't actually what happens, but close)  And it must have a preprepared dlist and filelist in the top directory.

In other words, a binary package is something that one of us downloads source for, builds, makes a temp install for, prepares a dlist and filelist for and then packages (and hosts).


I've been trying to make a binary package from:

http://rclone.org/downloads/

using their "binary" packaged zip files.  What I would/will need to do is to make a rclone.rb crew-package-file that looks like a from-source chromebrew package, but it's install downloads the right zip file per architecture, does it's own sha1sum checking, unpacks it, and puts the files in the right place in CREW_DEST_DIR so that the correct code will get run to generate the dlist and filelist files.


I have an experimental 'crew' binary that can detect if the download file ends with ".zip" and then does unzip on it instead of tar -xf... but even with that code will only work with source-built packages because binaries dont get most of the package stuff (e.g. look at the code surrounding the line "puts "Building from source, this make take a while...")

I started trying to modify the code to handle zip and then realized what I wanted was code to handle 3rd-party-binary pacakges.  I was going to add a new Package method so I could do @pkg.bininstall but... it gets really messy.  My ruby is weak enough that I'm pretty sure I'll break something.

It would be nice if there was "3rd party binary" support - e.g. it gets treated like a source package, and the @pkg.build and @pkg.install methods were called, but that the source itself is architecture dependent.

As it is I need to make a separate Package for each architecture so that I can have different sources for different binaries - something like rclone-386.rb rclone-armv7.rb and rclone-x86_64.rb.

**Comment by minektur** [comment]
I just sent a PR that adds "source package in zip file" support and an example rclone package pr#267

**Comment by minektur** [comment]
I've just had a different idea - how about a hook for both binary and source packages - that if @pkg.unpack is defined in the package file that it is called instead of doing the default tar xf


Then we could support any kind of package.


pseudo-code:

if @pkg.unpack exists
   topdir = @pkg.unpack
else
   do the tar xf that we now do and set topdir
end


do whatever else we do now (.e.g build, install)


This would let us support any format that someone is willing to write an 'unpack' method for, and not clutter up the code.

**Comment by thedamian** [comment]
@minektur very smart idea.
I like your solution for adding the unzip also for now, (this new idea is also very smart)

I'm waiting I think for a couple of changes that you said he'd do before I merge it.
because .zip packages are definitely needed.
