### ISSUE TITLE
Ada compiler

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2617]
Could we please bootstrap an Ada and a Go compiler with GCC? I really would like to be able to bootstrap GCC for my chroot without having to use 6.1.2, the version used by AdaCore right now.

**Comment by uberhacker** [comment]
Who uses Ada? :)  I guess my question is why do this?

**Comment by JL2210** [comment]
Why can't we include Ada in our distribution? If anything, possibly a seperate package?

**Comment by uberhacker** [comment]
Who said we can't have it?  I'll wait for your PR. :)

**Comment by JL2210** [comment]
OK. How about this? A gcc_ada package that builds GCC Ada from sources, and an ada_bootstrap package that contains the temporary ada toolchain required as a circular dependency?

**Comment by uberhacker** [comment]
What is wrong with just calling the package ada?

**Comment by JL2210** [comment]
I'll need some advice :)

**Comment by JL2210** [comment]
Ok. That seems like a great name. lol

**Comment by JL2210** [comment]
Oh well. This has gone stale and is totally useless.
