### ISSUE TITLE
Request for further libwayland packages

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2620]
Hello,

I have been experimenting with libwayland package lately for the sake of doing native (i.e. out-of-browser) GLES development, and I believe I have an idea re what is currently missing from Chromebrew repo so that a full-performance GLES/EGL/wayland stack is available to Chomebrew users.

But first a bit of background. Around the introduction of Android apps support (or perhaps slightly earlier -- I'm new to the platform myself), several key components appeared among the ChromeOS system components:
1. `/usr/lib/libGLESv2.so` -- a native GLES GPU stack
2. `/usr/lib/libEGL.so` -- a native-GLES-compatible EGL implementation by mesa 
3. A fully-functional wayland server

 The wayland server available on ChomeOS (circa R67/68) provides the following interfaces:
```
wl_compositor id 1
wl_shm id 2
zwp_linux_dmabuf_v1 id 3
wl_subcompositor id 4
wl_shell id 5
wl_output id 6
zxdg_shell_v6 id 7
zcr_vsync_feedback_v1 id 8
wl_data_device_manager id 9
for wl_seat id 10
wp_viewporter id 11
wp_presentation id 12
zcr_secure_output_v1 id 13
zcr_alpha_compositing_v1 id 14
zcr_remote_shell_v1 id 15
zaura_shell id 16
zcr_gaming_input_v2 id 17
zcr_stylus_v2 id 18
zwp_pointer_gestures_v1 id 19
zcr_keyboard_configuration_v1 id 20
zcr_stylus_tools_v1 id 21
zcr_keyboard_extension_v1 id 22
zwp_input_timestamps_manager_v1 id 23
```
Of those, `zwp_linux_dmabuf_v1` is essential for EGL (the platform-binding companion API to GL/GLES) to get a surface that can be later on presented with zero overhead by the wayland server. The client-side functionality for that interface, though, in nowhere to be found in the libwayland package libraries. The current libwayland package provides other EGL-intended interfaces which are not compatible with the system-native EGL stack.

Now, somebody with more wayland experience might correct me here, but I believe that something along https://chromium.googlesource.com/chromium/src.git/+/51.0.2673.1/third_party/wayland-protocols could provide that `zwp_linux_dmabuf_v1` functionality in a lib. The good news is that once this wayland interface is available client-side, the system-provided libEGL offers the matching EGL extension for making the bond with wayland.

The alternative to that mechanism is copying EGL off-screen buffers to wayland shm buffers manually, and that poses a serious performance hit (example here: https://vimeo.com/287615192 -- pay attention to the CPU load for displaying such a small surface).

Thank you, and keep up the great Chromebrew work!

**Comment by uberhacker** [comment]
Thank you @blu.  This is excellent background information.  I'm all for using as much "out-of-the-box" stuff that we can use effectively.  I'm not as wayland literate to know which is the best approach going forward.  But it sounds like if we can get the client-side working, this could make it functional.

**Comment by blu** [comment]
Looking for a volunteer with a x86 chromebook and basic knowledge in EGL to test this out: https://github.com/blu/hello-chromeos-gles2

**Comment by JL2210** [comment]
@blu: Why not just use a VM? Will x86_64 work?

**Comment by blu** [comment]
@JL2210: yep, a x86_64 should work as well. Re why not a VM -- I'm presently in the countryside with an ARM chromebook and 8KB/s worth of internet -- I can barely pull chromebrew packages ; )

**Comment by JL2210** [comment]
Same.

**Comment by JL2210** [comment]
No makefile?

**Comment by blu** [comment]
@JL2210: no makefile for now -- just use the build_xxx.sh scripts. But what do you mean by same?

**Comment by JL2210** [comment]
I'm out in the country with crappy Internet. Seems to need `<bits/c++config.sh>`, though I've done some messing around with /usr/local and Clang. I'll see if it works later.

**Comment by blu** [comment]
Ah, I'm slow today. Ok, let me know if you need help with clang (or switching to g++ for that matter).

**Comment by blu** [comment]
@uberhacker: I've tested the code on a x86-64 chromebook and I've updated the clang/clang++ wrapper scripts accordingly -- they did not work on x86-64 due to a slight difference in lib paths. Only now wrappers might be robust enough for use in Chromebrew packages ; )

**Comment by JL2210** [comment]
Great! How do they work?

**Comment by blu** [comment]
@JL2210: I've updated them to take all necessary lib paths/path fragments from gcc itself, vis-a-vis assuming those. Let me see to that error you've encountered.

**Comment by blu** [comment]
Quick update: as it turns out, the `zwp_linux_dmabuf_v1` by itself can be integrated into client code at the expense of a single TU plus a couple of headers -- so no need really for full-fledged package just for that, but perhaps the complete `wayland-protocols` package would still be worth it. Moreover that the versioning found at https://chromium.googlesource.com/chromium/src.git/ seems to match precisely the ChromeOS releases. For instance, for the current stable ChromeOS R68.0.3440.118 ->
https://chromium.googlesource.com/chromium/src.git/+/68.0.3440.118/third_party/wayland-protocols/

**Comment by uberhacker** [comment]
@blu: Is this the source for wayland protocols?  See https://github.com/wayland-project/wayland-protocols.  If so, do you want to take a shot at creating a package?  They are not as difficult as you might expect.  See https://github.com/skycocker/chromebrew/wiki/Creating-a-package.

**Comment by blu** [comment]
@uberhacker Yep, I'll give `wayland-protocols` a try, but let me first get the code that needed `zwp_linux_dmabuf_v1` up and running.

**Comment by JL2210** [comment]
@blu: `wayland_protocols` is already a package.

**Comment by blu** [comment]
@JL2210: Thanks for the heads-up -- I somehow missed yet another wayland package : /
That's the right version as well - it just needs passing through the wayland scanner (i.e. automated protocol src generator).
