### ISSUE TITLE
No audio.

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2634]
I think the issue is with some of the audio codec packages crew has, specifically `alsa_lib` and `alsa_plugins`. After removing those packages, Youtube still does not work at all. So, I searched `codec`, and I found that `libogg`, `libopencoreamr`, `libopus`, `libvoamrwbenc`, `libxvid`, and `openjpeg` were installed. After removing these packages, Youtube audio and video works, but Flash audio still does not. If there is anything I can do to fix this, I would be more than glad to. Audio does work without crew.

**Comment by JL2210** [comment]
After removing `libxvmc` `libxv` `libx265` `libx264` `libtheora` `libfrei0r`, and `ffmpeg`, everything works properly.

**Comment by uberhacker** [comment]
I guess the solution is don't install ffmpeg.

**Comment by JL2210** [comment]
But the thing is, all of them break something. Video doesn't work with some of these installed.

**Comment by uberhacker** [comment]
Is this still an issue?

**Comment by JL2210** [comment]
No.
