### ISSUE TITLE
'crew update' and 'crew upgrade' failed, saying 'undefined method'

### ISSUE THREAD

**Issue by VictorSu000** [skycocker/chromebrew#2635]
## Description

Things began after I removed ruby by mistake and reinstalled crew. (Firstly I can't upgrade buildessential. It said that glibc233 was not found. So I removed glibc233 and buildessential and reinstalled buildessential. Then I found that ruby can be upgraded, so I removed ruby and wanted to reinstall it... At that time I forgot crew relies on ruby.)

After reinstallation of crew, 'crew update' and 'crew upgrade' don't work.

P.S. I did not delete /usr/local/ directory, just simply ran curl -Ls git.io/vddgY | bash

If I run 'crew update', output:

```shell
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 80feec66 Merge pull request #2632 from uberhacker/update-filecmd-package
Package lists, crew, and library updated.
Checking for package updates...

Traceback (most recent call last):
        4: from /usr/local/bin/crew:963:in `<main>'
        3: from /usr/local/bin/crew:936:in `update_command'
        2: from /usr/local/bin/crew:327:in `update'
        1: from /usr/local/bin/crew:327:in `each'
/usr/local/bin/crew:329:in `block in update': undefined method `version' for nil:NilClass (NoMethodError)
```

In /usr/local/bin/crew, if I print out the data.

```ruby
canBeUpdated = 0
@device[:installed_packages].each do |package|
   search package[:name], true
   puts package                                                                                                                                 
   if package[:version] != @pkg.version
     canBeUpdated += 1
     puts @pkg.name + " could be updated from " + package[:version] + " to " + @pkg.version
   end
end   
```

And then run 'crew update', I can get package version data.

```shell
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 80feec66 Merge pull request #2632 from uberhacker/update-filecmd-package
Package lists, crew, and library updated.
Checking for package updates...

{:name=>"ncursesw", :version=>"6.1"}
Traceback (most recent call last):
        4: from /usr/local/bin/crew:964:in `<main>'
        3: from /usr/local/bin/crew:937:in `update_command'
        2: from /usr/local/bin/crew:327:in `update'
        1: from /usr/local/bin/crew:327:in `each'
/usr/local/bin/crew:330:in `block in update': undefined method `version' for nil:NilClass (NoMethodError)
```

If I run 'crew upgrade', output: 

```shell
Traceback (most recent call last):
        6: from /usr/local/bin/crew:963:in `<main>'
        5: from /usr/local/bin/crew:946:in `upgrade_command'
        4: from /usr/local/bin/crew:363:in `upgrade'
        3: from /usr/local/bin/crew:363:in `each'
        2: from /usr/local/bin/crew:370:in `block in upgrade'
        1: from /usr/local/bin/crew:649:in `expand_dependencies'
/usr/local/bin/crew:624:in `push_dependencies': undefined method `is_binary?' for nil:NilClass (NoMethodError)
```

## Versions and system information
chromebrew: `crew --version`    1.0.3

ChromeOS: `cat /etc/lsb-release`

```shell
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4945098
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={7834CC99-3294-421F-9963-028D7D6512CA}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={7834CC99-3294-421F-9963-028D7D6512CA}
CHROMEOS_RELEASE_BOARD=celes-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=21
CHROMEOS_RELEASE_BUILDER_PATH=celes-release/R69-10895.21.0
CHROMEOS_RELEASE_BUILD_NUMBER=10895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10895.21.0 (Official Build) beta-channel celes 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=10895.21.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10895.21.0
```

Architecture: `uname -m`    x86_64

Lots of thanks for your help!

**Comment by JL2210** [comment]
Have you tried reinstalling? `rm -rf /usr/local && curl -Ls http://git.io/vddgY | bash`

**Comment by uberhacker** [comment]
My guess is something is corrupt or the beta channel is not ready for prime time.  Please return to the stable channel and report back if you still have trouble.

**Comment by JL2210** [comment]
He is on the stable channel. His crew version is very old. See `glibc223`? In fact, the stable channel now should be 70. So he needs to update his Chromebook.

**Comment by uberhacker** [comment]
Last I checked, the stable channel is release 68.  This is the giveaway:
```
CHROMEOS_RELEASE_TRACK=beta-channel
```

**Comment by skiman6010** [comment]
@JL2210 Please only comment on issues if you can in fact back up your wild claims with evidence. The stable channel isn't even close to being updated to 70 yet, it hasn't even been updated to 69. Check the releases with https://chromereleases.googleblog.com/search/label/Chrome%20OS. That's the least you can do; your erratic messages and spam are confusing people looking for help.

Anyway,
@VictorSu000 I think the best thing you can do is `rm -rf /usr/local` at this point. Looks like `crew` is broken beyond repair.

**Comment by JL2210** [comment]
Whoops. Sorry. My mistake. @VictorSu000, the best way to fix your issue at this point is going through a full reinstallation, like @skiman6010 said. Your crew version is so old, you probably ought to.

**Comment by VictorSu000** [comment]
Today I found out where the problem is.

In file `/usr/local/lib/crew/crew` between line 327 to line 333,

```ruby
@device[:installed_packages].each do |package|
   # call 'search' method. in 'search' method, method 'set_package' is called and @pkg is set in 'set_package' 
   search package[:name], true 
   # however, here @pkg is nil
   if package[:version] != @pkg.version
     canBeUpdated += 1
     puts @pkg.name + " could be updated from " + package[:version] + " to " + @pkg.version
   end
end
```

Between line 145 to line 150,

```ruby
def search (pkgName, silent = false)                                                                                                                  
   Find.find (CREW_LIB_PATH + 'packages') do |filename|
     # Here if no '.rb' files match pkgName, 'set_package' won't be called, so @pkg is nil
     # And I have a package 'ncursesw', which seems to have been removed in crew... So this situation occurs...
     return set_package(pkgName, silent) if filename == CREW_LIB_PATH + 'packages/' + pkgName + '.rb'
   end 
   abort "Package #{pkgName} not found. :(".lightred unless silent
end
```

`crew upgrade` fails due to the same problem.

### Solution

I think after calling `search` method, `@pkg` should be checked whether it is nil. Inserting `next if @pkg == nil` before futher operation solves this issue. Should I make a PR?

Plenty of thanks!

**Comment by uberhacker** [comment]
@VictorSu000: Thank you for the analysis.  In this context, @pkg should never be nil.  All the packages from @device should be located in both packages directories.  It sounds like maybe your `/usr/local/etc/crew/device.json` file is corrupt.  I have seen this happen occasionally if something doesn't install correctly or is aborted halfway through the process.  Please examine your device.json file and make sure it looks complete.  If not, then your best solution is to start over with a fresh crew install.

**Comment by skiman6010** [comment]
@VictorSu000 Did you add `next if @pkg == nil` to your installation was able to successfully bypass your issue? If that is the case, @uberhacker I think we should add that as a check so this weird issue is fixed.

**Comment by uberhacker** [comment]
If there is a problem with device.json, that is not solving the problem because device.json lists (or should) all the installed packages.  If there are any packages missing, those will be excluded from updates.  I may be wrong but it sounds to me like his crew installation is corrupt.

**Comment by VictorSu000** [comment]
@skiman6010 Yes, this solves my problem. @uberhacker Indeed there's one problem in my `device.json`. My `device.json` was generated by an old version of crew - well, pretty old, maybe two months ago or even older. So it includes a package which can not be found now. When I reinstalled crew, I did not deleted `device.json`, and the crew installation script doesn't remove those package messages, so the messages are stills there. That's why this problem occurs. Actually I know  a fresh install is the best to avoid more potential problems. So I don't know if it's good to add such a check.

**Comment by skiman6010** [comment]
I agree. That doesn't seem to really solve the problem then. I think we should definitely think about adding some more checks to the installation process though, we've had a couple of complaints from people with broken installations.

**Comment by uberhacker** [comment]
My advice to anyone with a broken installation is to just reinstall fresh.  It's not worth the effort to try and figure it out and even if you do, it's probably still missing something.

**Comment by JL2210** [comment]
Yeah. A good way to make the most of it is to create a tarball of
`/usr/local` after installation.

**Comment by JL2210** [comment]
@VictorSu000, how is this working for you? Any problems?

**Comment by VictorSu000** [comment]
Thank you all guys! I think this issue can be closed. A fresh reinstall is the best solution.

**Comment by JL2210** [comment]
Glad we could help.
