### ISSUE TITLE
error installing freedos

### ISSUE THREAD

**Issue by DovaMerith** [skycocker/chromebrew#2640]
Cant install FreeDOS package
## Description
I run the `crew install freedos` and set the image size to 4000mb
If you executed a specific command:
```crew install freedos
```

Output:
```(Healthy Dependancy installing, then this)

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Enter the drive C: partition size (in MB):
4000
--2018-09-10 13:29:45--  https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/FD12CD.iso
Resolving www.ibiblio.org... 152.19.134.40, 2610:28:3090:3000:0:bad:cafe:23
Connecting to www.ibiblio.org|152.19.134.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 438777856 (418M) [application/octet-stream]
Saving to: ‘FD12CD.iso’

FD12CD.iso                         100%[================================================================>] 418.45M  3.78MB/s    in 5m 47s  

2018-09-10 13:35:32 (1.21 MB/s) - ‘FD12CD.iso’ saved [438777856/438777856]

Formatting 'freedos.img', fmt=raw size=4194304000
WARNING: Image format was not specified for 'freedos.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
audio: Could not init `oss' audio driver

(qemu-system-i386:20277): Gtk-WARNING **: 13:35:46.910: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
freedos failed to install: `qemu-system-i386 -m 16 -k en-us -rtc base=localtime -soundhw all -device cirrus-vga -display gtk -hda freedos.img -cdrom FD12CD.iso -boot order=d` exited with 
```

## Versions and system information
chromebrew: `crew --version` 
1.0.3

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C776D42E-287A-435E-8BA7-E770BD30B46D}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C776D42E-287A-435E-8BA7-E770BD30B46D}
CHROMEOS_RELEASE_BOARD=x86-alex_he-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=72
CHROMEOS_RELEASE_BUILDER_PATH=x86-alex_he-release/R58-9334.72.0
CHROMEOS_RELEASE_BUILD_NUMBER=9334
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=58
CHROMEOS_RELEASE_DESCRIPTION=9334.72.0 (Official Build) stable-channel x86-alex_he 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9334.72.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9334.72.0

Architecture: `uname -m`
1686

**Comment by JL2210** [comment]
There is no `1686` architecture, did you mean `i686`?

**Comment by DovaMerith** [comment]
Yes sorry, damn that was a fast reply

**Comment by JL2210** [comment]
Yeah. I am on this a lot. Try `crew remove gdk_pixbuf`.

**Comment by uberhacker** [comment]
@DovaMerith: Thank you for reporting this issue.  Release 58 is fairly old.  Have you tried to update yet?  Also, what model is your Chromebook or is this a VM?

**Comment by JL2210** [comment]
He's on i686. i686 builds were deprecated a long time ago, remember?

**Comment by DovaMerith** [comment]
its the latest release, this is a series 3 samsung chromebook i beleive.
its the latest chromeOS version availiable

**Comment by DovaMerith** [comment]
Okay, i ran `crew remove gdk_pixbuf` now what?

**Comment by JL2210** [comment]
I'll try to replicate your issue.

**Comment by uberhacker** [comment]
I see you entered 4000 for the partition size.  That would mean 4 gb.  Did you mean 400 instead?

**Comment by JL2210** [comment]
Try installing again.

**Comment by uberhacker** [comment]
You can update to release 60 on i686.  It was deprecated a year ago.  I know all about this release.

**Comment by JL2210** [comment]
On a VM.

**Comment by DovaMerith** [comment]
Not for my version, m on the latest build for me

**Comment by JL2210** [comment]
He said he was on the latest release available to him. That should be fine.

**Comment by DovaMerith** [comment]
```freedos: FreeDOS is a free DOS-compatible operating system.
http://www.freedos.org/
version 1.2
The following packages also need to be installed: 
gdk_pixbuf 
Do you agree? [Y/n] ```

What do i do?

**Comment by JL2210** [comment]
Sorry. Say `n`.

**Comment by DovaMerith** [comment]
`no changes made` then exits the installer

**Comment by JL2210** [comment]
Yeah. Can you give me the output of `qemu-system-i386 --version`?

**Comment by DovaMerith** [comment]
```qemu-system-i386: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory```

**Comment by DovaMerith** [comment]
imma try reinstlaling the program

**Comment by JL2210** [comment]
Ah. Reinstall gdk_pixbuf and try again. I need to think before I make sporadic comments like that.

**Comment by DovaMerith** [comment]
okay

**Comment by uberhacker** [comment]
My guess is this ChromeOS version is so old that there are conflicts with the newer package versions.  I doubt we can provide adequate support due to the age of the release.  Just out of curiousity, what is the output of `ls /lib/libc-*`?

**Comment by DovaMerith** [comment]
```/lib/libc-2.23.so```

**Comment by uberhacker** [comment]
Well, at least that is a version that is still used even in the latest 68 release.

**Comment by JL2210** [comment]
@uberhacker, there seems to be an issue with this on two other platforms, too. Check NixOS/nixpkgs#37696

**Comment by DovaMerith** [comment]
the longest part here is constantly downloading the FD12FULL.ISO each time...

**Comment by JL2210** [comment]
Yeah. I haven't figured out a way around that.

**Comment by DovaMerith** [comment]
Maybe have it download to ~/Downloads/.crew and then have it check for the file, and then use that, and at the end of the script, remove the files?

**Comment by JL2210** [comment]
@DovaMerith: That's not the file name. It's FD12CD.ISO. When's the last time you've run `crew update && crew upgrade`?

**Comment by JL2210** [comment]
That could work. I'm not sure about it right now, though. Have you reinstalled `gdk_pixbuf`?

**Comment by JL2210** [comment]
This is the proper way to use the triple `:
` ```
<texthere>
``` `

**Comment by DovaMerith** [comment]
okay,

**Comment by JL2210** [comment]
Sorry. Let me send you a text file.

**Comment by DovaMerith** [comment]
I am using a default `CTRL+ALT+T` terminal, gonna try in a VC

**Comment by JL2210** [comment]
Test: ***italics***

**Comment by JL2210** [comment]
No. You're good.

**Comment by JL2210** [comment]
*italics*

**Comment by JL2210** [comment]
[Markdown.txt](https://github.com/skycocker/chromebrew/files/2368463/Markdown.txt)

**Comment by JL2210** [comment]
<text>

**Comment by DovaMerith** [comment]
welp, gnna reset the chromebook later (flipping the dev-switch) and try again when i have the password

**Comment by JL2210** [comment]
I'm getting a totally different error:
```
*** stack smashing detected ***: qemu-system-i386 terminated
freedos failed to install: `qemu-system-i386 -m 16 -k en-us -rtc base=localtime -soundhw all -device cirrus-vga -display gtk -hda freedos.img -cdrom FD12CD.iso -boot order=d` exited with 
```

**Comment by JL2210** [comment]
You have a DEV SWITCH? Not to be rude, but those things are ancient. There is a software one, now. It's Escape-Refresh-Power, and then CTRL-D.

**Comment by DovaMerith** [comment]
Its a hardware switch, yes

**Comment by DovaMerith** [comment]
I have a XE500C21

**Comment by JL2210** [comment]
@DovaMerith: As a note, don't enable debugging features when you reset. It's known to cause problems with crew.

**Comment by JL2210** [comment]
Try `crew remove qemu gdk_pixbuf && crew install -S qemu`
Notice the capital S.

**Comment by DovaMerith** [comment]
reinstalling right now. ran the command listed, but had to shut the lid and it timed itself out and turned off.

**Comment by DovaMerith** [comment]
and debugging isnt enabled at all

**Comment by DovaMerith** [comment]
Status Update Dependancies are installing, no issues yet

**Comment by DovaMerith** [comment]
```(qemu-system-i386:15941): Gtk-WARNING **: 11:30:45.394: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
freedos failed to install: `qemu-system-i386 -m 16 -k en-us -rtc base=localtime -soundhw all -device cirrus-vga -display gtk -hda freedos.img -cdrom FD12CD.iso -boot order=d` exited with ```

**Comment by DovaMerith** [comment]
so... i guess im fraked

**Comment by JL2210** [comment]
@DovaMerith, my suggestion at this point is to try to install QEMU and install Chrome OS inside a QEMU image to run freedos in QEMU.

P.S. I'm a madman.

**Comment by uberhacker** [comment]
@JL2210: Can you please outline the steps to get a Chrome OS i686 image running in QEMU?  I want to know also. :)

**Comment by JL2210** [comment]
Lol. I was kidding. If QEMU doesn't work, how would you run a Chromium OS image in QEMU to run QEMU?

**Comment by JL2210** [comment]
Look at the GCC 8 page and the instructions you gave me.

**Comment by JL2210** [comment]
This can be closed. The update fixed it.
