### ISSUE TITLE
Stack smashing in QEMU

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2641]
Exact output:
```
*** stack smashing detected ***: qemu-system-i386 terminated
freedos failed to install: `qemu-system-i386 -m 16 -k en-us -rtc base=localtime -soundhw all -device cirrus-vga -display gtk -hda freedos.img -cdrom FD12CD.iso -boot order=d` exited with 
```
I think this has something to do with not using the `--disable-stack-protect{or,ion}` option when configuring QEMU.

**Comment by superloach** [comment]
I might try building QEMU later, and figure out the appropriate flags.
Right now I'm working on cleaning up GIMP's dependencies, and maybe a few preliminary Steam deps 😉😉

**Comment by JL2210** [comment]
Hint: Steam doesn't work. Don't try it. I spent forever trying to get Steam up on Gentoo. No luck.

**Comment by superloach** [comment]
Well I may or may not have recently switched to System76's Pop!_OS, so I guess that's not really a problem anymore 😆
In that case, though (and along the lines of QEMU), how could I get a ChromeOS VM running to continue work on Chromebrew? Or have I completely screwed you guys over on accident? 😅

**Comment by JL2210** [comment]
Oh, no. I'm fine. I can recompile this. Hardware Chromebook.

**Comment by JL2210** [comment]
Do you need to use QEMU? The QEMU image doesn't work properly.
