### ISSUE TITLE
[GLES over EGL/wayland] almost there with a proper frameloop

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#2662]
Heya, chromebrewers!

I've been nagging you (mainly @uberhacker and @JL2210) a lot over the past few weeks with various requests, but it has all snapped into place now: a proper native (without Chrome) GLESv2 frameloop, done via ChromeOS-native libEGL, libGLESv2 and libdrm, and Chromebrew's libwayland and wayland_protocols packages. It's all here: https://github.com/blu/hello-chromeos-gles2. Just wanted to say 'thank you' to the entire chromebrew bunch for the great work you do, enabling old crazy hacks like myself to use their chromebooks in ways Google might not have envisioned ; ]

Of course, there's one last quirk -- it appears the wayland server does not recognize a rather important flag during dmabuf creation -- `ZWP_LINUX_BUFFER_PARAMS_V1_FLAGS_Y_INVERT`, so frames appear upside-down on screen; if somebody knows something about that -- I'd be happy if you shared it.

Cheers, and keep rocking!
blu

**Comment by JL2210** [comment]
Great! You haven't been nagging me.

**Comment by JL2210** [comment]
How do you know so much about C++ and EGL/Wayland?

**Comment by JL2210** [comment]
I'm going to go to college for this sort of stuff. I'm mediocre at C, but Dad went to college for the same thing I'm going to go for, so he helps me. I created a small Coreutils implementation. If you want, I could create a Github page for it.

**Comment by blu** [comment]
I enjoy studying all kinds of low-level code, so a coreutils implementation would be interesting. More importantly, you've picked a good platform to experiment on. College is important, but what you do beyond college is equally important.

BTW, one of the things I truly enjoy about chromeos is the streamlining of the linux platform to a degree that reminds me of the apple2 days.

**Comment by uberhacker** [comment]
@blu @JL2210: If you haven't already, check out qtcreator from the qt package.  It's a C++ developer's dream IDE.

**Comment by JL2210** [comment]
OK. Qt is not installing for me. Says I only have 77MB or something and it needs 128MB when in reality I have 3GB available.

**Comment by uberhacker** [comment]
Maybe it is installing on a different partition with less space available?

**Comment by JL2210** [comment]
Nope. `/usr/local/opt/qt5` is the target.

**Comment by JL2210** [comment]
I had that issue  when trying to install GNAT 2018, so I switched back to 2017.

**Comment by JL2210** [comment]
You know, it would be better to compile from source.

**Comment by uberhacker** [comment]
Certainly a lot more difficult.

**Comment by JL2210** [comment]
So?

**Comment by JL2210** [comment]
lol

**Comment by JL2210** [comment]
I've got 'Richard Stallman'itis.

**Comment by uberhacker** [comment]
Richard Stallman would never use Chrome OS as his operating system.  As far as he's concerned, Google is run by the devil himself.

**Comment by JL2210** [comment]
You're right about that. But he wouldn't want to use binary packages of Qt, either.

**Comment by uberhacker** [comment]
He wouldn't even use Qt, period.  He would use g++ instead. :)

**Comment by JL2210** [comment]
:). Lol. Maybe a mild case?

**Comment by blu** [comment]
@uberhacker Thanks for the heads-up, but I'm a die-hard vim/gdb user ; )

**Comment by JL2210** [comment]
He would probably use GTK. After all GNOME Toolkit, and GNOME stands for GNU Network Object Model Environment.

**Comment by JL2210** [comment]
@uberhacker is too. You should see him when somebody uses Emacs.

**Comment by blu** [comment]
@uberhacker Hehe. Luckily I don't share Stallman's views, which allows me to greatly enjoy chromeos ; ]

'Libre' cannot be the ultimate criteria for the viability of something which has essentially utilitarian reasons for existence. Instead, I give major weight to the 'fitness for a purpose' criteria (so readily disclaimed in license notes). In this regard I have no issue using closed software, if that's what gets 'the job done'.

**Comment by JL2210** [comment]
To a point, that's my idea. I generally stay far away from closed-source software unless I can't find something I need in open source form (such as WiFi drivers), or it's to please someone else (Mom, Dad).

**Comment by JL2210** [comment]
Also, most of Chrome OS is generally free, so I am OK with it.

**Comment by blu** [comment]
Update: I've traced the issue with server's rejection of ZWP_LINUX_BUFFER_PARAMS_V1_FLAGS_Y_INVERT flag to here:
https://chromium.googlesource.com/chromium/src/+/master/components/exo/wayland/server.cc ->
ValidateLinuxBufferParams

Hopefully google will address it sooner than later.

**Comment by JL2210** [comment]
Is there anything you could do on your side to reverse the video? A user-defined variable? A hack? I'm good at those, if you need help. ![https://discordemoji.com/assets/emoji/AwesomeFace.png]()

**Comment by blu** [comment]
@JL2210 There's a well-known client-side GLES hack for such situations, where one flips the y-axis in the projection matrix along with the winding of all primitives, but I really don't want to do that -- it's a bit ridiculous in this day and age.

**Comment by JL2210** [comment]
Sorry to break it to you, but Google/Chromium won't fix anything 'little' like this. The `.relr.dyn` section issue I filed hasn't received any comments yet, and it's been a week since I posted it. I've had to switch to Clang and lld for not one, but *two* packages since this. Looks like you *might* have to use that hack.

**Comment by blu** [comment]
@JL2210 I would still give them some time -- this flag is mandatory for the version of the wayland protocol that uses the flag and that google implements, so chances are they might introduce support for the flag in the future, if they intend to ever have a standards-compliant wayland server.

**Comment by JL2210** [comment]
I suppose that they might, though standards-compliant wouldn't be at the top of their list. Keep in mind that this is supposed to be a secure OS that works solely as a browser. Maybe they don't need to make the browser display upside down or backwards.

**Comment by JL2210** [comment]
I'd say that your programs look good as they are.

**Comment by blu** [comment]
@JL2210 Thank you for the kinds words, James, but the current examples look ok only because they exhibit up-down symmetry. Had they shown some, say, character animation, it'd look weird ; )

**Comment by blu** [comment]
@JL2210 There something called wl_outut_transform, but: https://chromium.googlesource.com/chromium/src/+/master/components/exo/wayland/server.cc#505

Close but no cigar.

Notice, that for a proper y-invert output of a buffer, it takes FLIPPED_180 semantics, which, again, is not implemented in the chromium's wayland server. We should still be able to do plain TRANSFORM_180, but the image will come out left-right mirrored, which might still better than top-down mirrored for some scenarios.

**Comment by blu** [comment]
A word of caution: I've just discovered a wayland-related system crash on RK3399 chromebooks: https://github.com/blu/hello-chromeos-gles2/issues/4

Users of Samsung Chromebook Plus and Asus Chromebook Flip C101PA -- beware.

**Comment by JL2210** [comment]
Don't you just love non-compliant wayland servers?

**Comment by blu** [comment]
Love the smell on non-compliant wayland servers in the morning ; )

This appears like a bug in the wayland/DRM/EGL chain of command, and given google have to cater to nobody but their own code, that bug could have remained latent forever. I'm considering filing a bug with them, but then again see the prev sentence.

**Comment by blu** [comment]
I want to thank Google and Zach Reizner in particular:
https://bugs.chromium.org/p/chromium/issues/detail?id=887036

My user expectations have been largely surpassed.

**Comment by JL2210** [comment]
Yay! Progress!

**Comment by blu** [comment]
Heads-up: ZWP_LINUX_BUFFER_PARAMS_V1_FLAGS_Y_INVERT works in r73. I believe this ticket can be closed now.

**Comment by blu** [comment]
To mark the enablement of ZWP_LINUX_BUFFER_PARAMS_V1_FLAGS_Y_INVERT in r73, I've added yet another small test app to https://github.com/blu/hello-chromeos-gles2, but this time app has an apparent up-down orientation ; ) Build via build_chromeos_skeleton_shadow.sh. Cheers!
