### ISSUE TITLE
Unable to install on i686

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2670]
Command:
` curl -Ls https://git.io/vddgY | bash `
Goes through install process until git.

At git, fails with:
`git: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory`

Using VDI R60 VM image from https://github.com/crosbuilder/CustomBuilds

**Comment by uberhacker** [comment]
Good catch.  Not sure why git is complaining about this now.  See PR #2671.

**Comment by uberhacker** [comment]
This is happening on all architectures.  PR updated accordingly.

**Comment by wyuenho** [comment]
This is still happening on a rooted Google Wifi

**Comment by uberhacker** [comment]
@wyuenho: This should not happen with the latest `install.sh` from master.  Do you notice libiconv attempting to install at all?  If not, you likely have an earlier version of the repo.

**Comment by wyuenho** [comment]
I'm curling the install.sh from master, I just copied and pasted that command into the shell. There are a few minor issues in there related to sha256sum and tar but once those are fixed, the libiconv archive did verify, it's just once extracted and moved into place, no binaries are able to find it, so my Chromebrew install failed when trying to `git init`.

**Comment by uberhacker** [comment]
Sounds like something is corrupt.  If you can afford to lose everything in `/usr/local`, I would recommend the following:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by wyuenho** [comment]
> Sounds like something is corrupt.

Thats a strange thing to assume if you know your binaries are good.

Turns out the Galeforce rooted Google Wifi doesn't event define `LD_LIBRARY_PATH` in the environment, once it's defined to include `/usr/local/lib`, everything is fixed. May be you will consider checking for this in the install script.
