### ISSUE TITLE
crew update lists already updated packages

### ISSUE THREAD

**Issue by revolutionnaire** [skycocker/chromebrew#2699]
`crew update` brings up this:
`buildessential could be updated from 1.2 to 1.3`

`crew upgrade buildessential` brings up this:
`version 1.3`
`buildessential is already up to date.`

**Comment by uberhacker** [comment]
Thank you for reporting this issue @revolutionnaire.  See https://github.com/skycocker/chromebrew/issues/1390.

**Comment by revolutionnaire** [comment]
Sorry about the duplicate
