### ISSUE TITLE
[sommelier] Unable to install due to dependency loop

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2706]
This happens on a fresh crew install as well.  Fix coming soon...

**Comment by uberhacker** [comment]
You must not have checked good enough.  There were 3 redundant dependencies when I tested it last night.

**Comment by JL2210** [comment]
Redundant is different than circular.

**Comment by uberhacker** [comment]
Dude, it's the redundancies that cause the looping.

**Comment by JL2210** [comment]
This could probably be renamed to `[mesa|llvm] Unable to install due to dependency loop`

**Comment by uberhacker** [comment]
Dude, there were 3 additional redundant dependencies I removed from sommelier.

**Comment by JL2210** [comment]
Yes, three redundant. The dependency loop itself was in mesa.

**Comment by uberhacker** [comment]
The dependency loop was also in sommelier.  If you ever noticed, it took an eternity to determine the dependencies.  Now it's almost instantaneous.
