### ISSUE TITLE
Package glibc223 not found. :(

### ISSUE THREAD

**Issue by paulwratt** [skycocker/chromebrew#2726]
## Description
I just did had to do a upgrade because gcc7 could not find a library (libisl) and it said binutils would be upgraded too

If you executed a specific command:
```shell
crew update && crew upgrade
```

Output:
```shell
(i) glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
https://www.gnu.org/software/libc/
version 2.23
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Removing since upgrade...
Glibc removed!
Installing...
Performing post-install...
Glibc installed!
Package glibc223 not found. :(
```

## Versions and system information
chromebrew: 1.0.3

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4959629
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_RELEASE_BOARD=veyron_speedy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=veyron_speedy-release/R68-10718.88.2
CHROMEOS_RELEASE_BUILD_NUMBER=10718
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=68
CHROMEOS_RELEASE_DESCRIPTION=10718.88.2 (Official Build) stable-channel veyron_speedy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=2
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10718.88.2
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10718.88.2

Model: ASUS CP201P

Architecture: armv7l

cheers

Paul

**Comment by JL2210** [comment]
Reinstall. You haven't updated in a long time. `rm -rf /usr/local && curl -Ls https://git.io/vddgY | bash`

**Comment by JL2210** [comment]
If that doesn't work, then try `crew install gtk2 gtk3`

**Comment by uberhacker** [comment]
Yeah, a fresh reinstall appears to be the best option in this situation.

**Comment by paulwratt** [comment]
I did no what to do, cos I needed the other packages, so I ended up running the install again, but the error is still there but at least I can update individual packages now.

**Comment by JL2210** [comment]
```
crew remove binutils && crew update && crew install binutils
```

**Comment by JL2210** [comment]
You probably should still reinstall, though.
Try this:
```
crew list installed > ~/Downloads/packages.txt
rm -rf /usr/local && curl -Ls https://git.io/vddgY | bash
crew install `cat  ~/Downloads/packages.txt`
```

**Comment by JL2210** [comment]
@paulwrat: Is this working for you now? If so, could you close this issue?

**Comment by JL2210** [comment]
@uberhacker, can you close this? I think his issue is fixed.

**Comment by JL2210** [comment]
Just reinstall. We have instructions to restore Crouton in the Wiki now
(How-to-remove-chromebrew).
