### ISSUE TITLE
cant do crew search

### ISSUE THREAD

**Issue by paulwratt** [skycocker/chromebrew#2727]
## Description
crew search has an error. it used to work.

If you executed a specific command:
```shell
crew search SDL_image
```

Output:
```shell
armv7l architecture not supported.
Unable to install google_cloud_sdk.  Supported architectures include i686 and x86_64 only.
Architecture not supported.  The only available platform is x86_64.
armv7l architecture not supported.
Package SDL_image not found. :(
```

## Versions and system information
chromebrew: 1.0.3

ChromeOS: `cat /etc/lsb-release`

CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4959629
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_RELEASE_BOARD=veyron_speedy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=veyron_speedy-release/R68-10718.88.2
CHROMEOS_RELEASE_BUILD_NUMBER=10718
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=68
CHROMEOS_RELEASE_DESCRIPTION=10718.88.2 (Official Build) stable-channel veyron_speedy
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=2
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10718.88.2
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10718.88.2

Model: ASUS CP201P

Architecture: armv7l

cheers

Paul

**Comment by JL2210** [comment]
Reinstall. `rm -rf /usr/local && curl -Ls https://git.io/vddgY | bash`

**Comment by uberhacker** [comment]
A reinstall is not necessary.  This is actually expected behavior.  The sdl_image package really doesn't exist. :)

**Comment by JL2210** [comment]
@uberhacker: Look at his error. google_cloud_sdk is messing up his search because he's on armv7l.

```
armv7l architecture not supported.
Unable to install google_cloud_sdk.  Supported architectures include i686 and x86_64 only.
Architecture not supported.  The only available platform is x86_64.
armv7l architecture not supported.
```

**Comment by skiman6010** [comment]
This seems like expected behavior to me with how the arch selection logic is handled.
