### ISSUE TITLE
Mongodb failed to install

### ISSUE THREAD

**Issue by sylvestertarnowski** [skycocker/chromebrew#2731]
## Description
I am trying to install mongodb and I run into the following issue:

I executed
```shell
crew install mongodb
```

It runs for a while fine but then the following happens:

Output:
```shell
Building mongooplog...
2018-10-06T19:53:52.212+0200    warning: mongooplog is deprecated, and will be removed completely in a future release
mongooplog version: r3.2.16
git version: ec63fa2fc5202dc53a4f5ac81ac735ba602c2992
Go version: go1.11.1
   os: linux
   arch: amd64
   compiler: gc
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
Preconfiguring package...
scons: Reading SConscript files ...
Mkdir("build/scons")
scons version: 3.0.1
python version: 2 7 15 'final' 0
Checking whether the C++ compiler works... no
C++ compiler g++ doesn't work
mongodb failed to install: `scons -j4 install --ssl --prefix=/usr/local/tmp/crew/dest/usr/local --use-new-tools` exited with 1
```

## Versions and system information
chromebrew: `1.0.3`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5006116
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={B00DD0BC-D2C9-BAB4-E66C-81AE3F5A7CED}
CHROMEOS_RELEASE_BOARD=cave-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=cave-release/R69-10895.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=10895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10895.56.0 (Official Build) stable-channel cave 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10895.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10895.56.0`

Model: ASUS c302ca

Architecture: `x86_64`
--

Any ideas?

**Comment by sylvestertarnowski** [comment]
> Have you tried just building a basic c++ program with g++?

Not sure what that would mean - compiling a C++ program using "gcc" command in shell?

I just tried doing that with a simple Hello World program, and it failed:
```
chronos@localhost ~/Downloads $ gcc -o app app.cpp
/usr/local/bin/ld: /tmp/cc6BzkS4.o: in function `main':
app.cpp:(.text+0xa): undefined reference to `std::cout'
/usr/local/bin/ld: app.cpp:(.text+0xf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/usr/local/bin/ld: app.cpp:(.text+0x14): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
/usr/local/bin/ld: app.cpp:(.text+0x1c): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
/usr/local/bin/ld: /tmp/cc6BzkS4.o: in function `__static_initialization_and_destruction_0(int, int)':
app.cpp:(.text+0x4a): undefined reference to `std::ios_base::Init::Init()'
/usr/local/bin/ld: app.cpp:(.text+0x59): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
```

**Comment by uberhacker** [comment]
`g++ -o app app.cpp`?

**Comment by sylvestertarnowski** [comment]
This seems to have worked:
```
chronos@localhost ~/Downloads $ ls
Example-Coding-Project  'Screenshot 2018-10-06 at 14.58.02.png'  'Screenshot 2018-10-06 at 18.47.12.png'  app  app.cpp  contact000000.vcf
```
Does that mean the compiler worked?

**Comment by uberhacker** [comment]
Not sure, I cannot see the output. :)

**Comment by sylvestertarnowski** [comment]
Result:
```
chronos@localhost ~/Downloads $ chmod +x app
chronos@localhost ~/Downloads $ ./app
-su: ./app: Permission denied
chronos@localhost ~/Downloads $ 
```

**Comment by sylvestertarnowski** [comment]
Result:
```
chronos@localhost /usr/local/tmp $ cp ~/Downloads/app.cpp .
chronos@localhost /usr/local/tmp $ g++ -o app app.cpp
chronos@localhost /usr/local/tmp $ chmod +x app
chronos@localhost /usr/local/tmp $ ./app.cpp
-su: ./app.cpp: Permission denied
chronos@localhost /usr/local/tmp $ 
```

**Comment by JL2210** [comment]
@sylvestertarnowski: `./app`
You're trying to run the app's source code.

**Comment by sylvestertarnowski** [comment]
@JL2210 
Sorry I didn't see that I made a mistake there:
```
chronos@localhost /usr/local/tmp $ cp ~/Downloads/app.cpp . 
chronos@localhost /usr/local/tmp $ g++ -o app app.cpp
chronos@localhost /usr/local/tmp $ chmod +x app
chronos@localhost /usr/local/tmp $ ./app


Hello World.
Welcome to my first C++ program on Ubuntu Linux


chronos@localhost /usr/local/tmp $
```
This seems to have worked

**Comment by sylvestertarnowski** [comment]
Hey, currently don't have access to my C302 to further assist in solving this issue, hopefully someone else will be able to chime in.

**Comment by JL2210** [comment]
I'll figure something out. I might just rewrite the package anyway. Right now, it's very badly written.

**Comment by adnascent** [comment]
I have a C302, running into the same issue.

**Comment by JL2210** [comment]
It's an old, forgotten package. Somebody will need to rewrite it for it to
work.

**Comment by 0x0123456789ABCDEF** [comment]
So what about MongoDB?

**Comment by JL2210** [comment]
@0x0123456789ABCDEF See above comment.
