### ISSUE TITLE
[emacs] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2732]
```
lcms.c:23:10: fatal error: lcms2.h: No such file or directory
 #include <lcms2.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:376: lcms.o] Error 1
make[1]: Leaving directory '/media/tmp/crew/emacs-26.1.tar.xz.dir/emacs-26.1/src'
make: *** [Makefile:418: src] Error 2
emacs failed to build: `make V=0 -j1` exited with 2
```
cc @s-urbaniak 

I'm wondering if we can split the gui version of emacs into a separate package called gemacs?  It might be worthwhile for those who only are interested in the cli version and want to keep their installation leaner.

**Comment by JL2210** [comment]
`liblcms2`?

**Comment by uberhacker** [comment]
Yes, but the crazy thing is emacs builds just fine on x86_64 without the lcms dependency.

**Comment by JL2210** [comment]
It's probably an `#if defined !(_x86_64_)`

**Comment by JL2210** [comment]
It's because x86_64 Chrome OS doesn't have the lcms lib installed by the system. i686 and ARM probably do.

**Comment by s-urbaniak** [comment]
That's quite a surprise indeed. As stated in the original PR I don't have an ARM/i686 chromebook. Do you have cross-compilation documented anywhere?

**Comment by uberhacker** [comment]
@s-urbaniak: No, we don't currently but it sounds like we could benefit by adding it to the wiki.  I have been building and testing on the actual hardware for x86_64 and aarch64/armv7l.  I use a Virtualbox VM for i686.

**Comment by JL2210** [comment]
It is odd. It's also Chrome OS. You really never know.

**Comment by JL2210** [comment]
@s-urbaniak: It's not documented, but we do have a cross-compilation script in the `tools/` directory. I have a PR up to fix it.
