### ISSUE TITLE
Visual Studio Code not working

### ISSUE THREAD

**Issue by codekrafter** [skycocker/chromebrew#2741]
I installed the `code` package, with all of the dependencies, and when I run it (by running the `code` command) it runs without any output (like it normally does on linux), but it does not open a window. I am pretty sure it is running Intel Bay Trail, which does not have VT-x support. I do not know if that is the issue, or if it is something else.

Thanks for the help!

## Versions and system information
chromebrew: 1.0.3

ChromeOS:
`CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_RELEASE_BOARD=gnawty-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=gnawty-release/R69-10895.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=10895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10895.56.0 (Official Build) stable-channel gnawty 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10895.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10895.56.0`

Model: Acer CB3-131

Architecture: `x86_64`

**Comment by uberhacker** [comment]
@codekrafter: Is sommelier running?  Try `startsommelier && code`.  If that doesn't work, `crew install sommelier` and follow the post install directions in blue text.

**Comment by codekrafter** [comment]
It was already installed, so I removed it then re-installed it and followed the instructions. When I start it it is not working with code and giving me this message: 
`_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 952
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 870
Warning: Unknown scale factor: 833
Warning: Unknown scale factor: 769
Warning: Unknown scale factor: 667
sommelier process 13897 is running
`

**Comment by codekrafter** [comment]
I restarted the computer, and It is now working, although it is scaled weird. Is there a way to change the scale?

**Comment by uberhacker** [comment]
@codekrafter:  You could try this:
Edit /usr/local/sbin/sommelierd and change to this
```#!/bin/bash
sommelier -X --x-display=$DISPLAY --scale=1 --no-exit-with-child /bin/sh -c "/usr/local/etc/sommelierrc"
```
and then restart sommelier.  Change the scale value to whatever works best for you.

**Comment by codekrafter** [comment]
Thanks! For my last question is there a way to make it show up in the shelf on the bottom?

**Comment by uberhacker** [comment]
I'll defer that question to @skiman6010. :)

**Comment by skiman6010** [comment]
@codekrafter I'm working on that right now. I've been dissecting Crostini and sommelier looking for clues on how to show icons in the shelf. Hopefully soon I will get it. :)

**Comment by uberhacker** [comment]
@codekrafter: I'm glad you asked. :)  We could always use more help with package updates.  See https://github.com/skycocker/chromebrew/issues/1585.  The procedure is simple.  Just pick the package you would like to update and check to make sure the latest version is selected from the Github releases page or whereever.  Download the update and verify the checksum with `sha256sum`.  These values will replace the current version of `source_url` and `source_sha256`.  If you need more assistance, check out the wiki page at https://github.com/skycocker/chromebrew/wiki/Creating-a-package or just ask here.

**Comment by uberhacker** [comment]
Also, if you haven't done so already, sign up at https://hacktoberfest.digitalocean.com/ so you can get credit for 5 pull requests to this project and earn your Hacktoberfest t-shirt. :)

**Comment by codekrafter** [comment]
Thanks for all of the help! I am adding GLFW, and then I can do package upgrades!

**Comment by JL2210** [comment]
I knew there was something up with Sommelier, Code, and rebooting! I origianally tried adding a note about that, but @uberhacker here didn't want to.

**Comment by uberhacker** [comment]
My guess is the crosh session needed refreshed.  Sometimes simply closing the session and opening it again can fix issues.  Also, something as simple as `source ~/.bashrc` can fix a myriad of issues.  Rebooting a Linux system is rarely needed to fix any issue.  This is not Windows. :)

**Comment by JL2210** [comment]
Not necessarily. The process runs in the background, and often new processes are better than recreating old ones. There might be bind mounts that need refreshed, too. I know I had an issue with Sommelier that needed a reboot, not just a simple tab close.

**Comment by uberhacker** [comment]
If you want to restart sommelier, this is all you would need: `stopsommelier && startsommelier`.  This would start a new process, not recreate an old process.

**Comment by JL2210** [comment]
That doesn't work, though. It doesn't kill all sommelier processes.

**Comment by JL2210** [comment]
All right. This issue is fixed. I'll let it be.
