### ISSUE TITLE
Package request "cron"

### ISSUE THREAD

**Issue by teckel12** [skycocker/chromebrew#2743]
## Description
`cron` not an option to install

## Versions and system information
Chromebrew: 1.0.3

CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5006116
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={40C6BCAB-B8D4-466F-9C3C-069B8CAC36D7}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={40C6BCAB-B8D4-466F-9C3C-069B8CAC36D7}
CHROMEOS_RELEASE_BOARD=lulu-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=lulu-release/R69-10895.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=10895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10895.56.0 (Official Build) stable-channel lulu 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10895.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10895.56.0

Model: Dell Chromebook 13 7310

Architecture: x86_64

What I think needs to be done:
- [x] add `cron`
- [x] `crew install cron`
- [x] disco

**Comment by uberhacker** [comment]
Hey @teckel12: I was actually working on this awhile back.  I might need to resurrect this package now that you requested it.  Didn't disco fade away 40 years ago? :)

**Comment by teckel12** [comment]
@uberhacker I'm willing to bring it back if I can schedule cron jobs on my Chromebook.

Actually, I just got my first Chromebook and one of the first things I do with all linux installs is get `mlocate` installed and `updatedb` scheduled (well, I typically install `nano` first, but `mlocate` is a close second).  Anyway, when I went to schedule `updatedb` I was like...  Ah...  Where's `cron`?

Just to make sure I'm not totally missing something, there isn't some other way to run scheduled tasks on a Chromebook is there?  I'm willing to just use a different method instead of `cron` if it's the Chromebook way of doing things.

In any case, thanks for looking into this, and I'll send you the disco video if you like.

**Comment by uberhacker** [comment]
There is a package called jobsceduler.  See https://github.com/skycocker/chromebrew/blob/master/packages/jobscheduler.rb.  I have never really used it.  You are welcome to give it a go and report back if cron-like jobs are successful or not.

**Comment by teckel12** [comment]
@uberhacker Of course, I just did a `crew list uninstalled | grep "cron"` and didn't even consider trying to find something else, cause it's it always cron?  I'll look at `jobscheduler` and report back.

**Comment by teckel12** [comment]
@uberhacker Installed and tried using jobscheduler.  It doesn't appear to be a task scheduler like cron.  Seems to only do web-based scheduling and uses a java front-end (at least on Windows).  Doesn't seem to be anyway to schedule from the command line.  Not really sure what it does.

**Comment by uberhacker** [comment]
@teckel12: Sorry to waste your time on the jobscheduler package.  I have submitted a PR to add cron.  See #2744.  Disco affectionados everywhere will be dancing the night away.

**Comment by JL2210** [comment]
@uberhacker, why all the disco jokes?

**Comment by teckel12** [comment]
@JL2210 Who's joking?

**Comment by teckel12** [comment]
Used chromebrew to install cronie and it works great, thanks!  As promised: https://youtu.be/nya5_ogQnVI  

Be sure to watch it till the end

**Comment by uberhacker** [comment]
That is great @teckel12!  10 hours? LoL
