### ISSUE TITLE
Work on FHS compliance

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2783]
Chromebrew installs several non-compliant directories in /usr/local, i.e.
```
/usr/local/cache
/usr/local/doc
/usr/local/docbook
/usr/local/man
/usr/local/var/db
/usr/local/var/krb5kdc
```
These really should be replaced with the the corresponding proper locations, i.e.
```
/usr/local/var/cache
/usr/local/share/doc
/usr/local/share/docbook
/usr/local/share/man
/usr/local/var/lib/nss_db
/usr/local/var/lib/krb5kdc
```
I understand CloudReady has a symlink from /usr/local/var to /var, which is not writable by the chronos user. Any ideas on how to circumvent this?

**Comment by uberhacker** [comment]
Yeah, put stuff in the "non-compliant" `/usr/local/cache` directory instead. ;)  Honestly, I think something like cache is better located in `/usr/local/tmp/cache`.  I also have reservations about `/usr/local/var/lib`.  This is totally arbitrary and opinionated but `/usr/local/share/nss_db` and `/usr/local/share/krb5kdc` are "better" locations for those items also.

**Comment by JL2210** [comment]
Usually, the `/tmp` directory is cleared on reboot. Non-persistent files, such as the cache, should be stored there. Also, databases should be stored in `/var/lib/nss_db`, according to FHS v3.0.

**Comment by uberhacker** [comment]
Right, but that is different than `/usr/local/tmp` which is persistent after a reboot.  Don't get too hung up on compliance since everything Chromebrew-related is stored in `/usr/local` or `#{CREW_PREFIX}`.  The FHS compliance is based on directories from root or `/` so anything stored in `/usr/local` can be more loosely organized.  According to the standard, the `/usr/local` directory is a _tertiary hierarchy for local data_.

**Comment by JL2210** [comment]
True. We should most likely still clean up /usr/local/tmp before a reboot, though. I need to check about the ***`tertiary hierarchy`*** standards.

**Comment by JL2210** [comment]
Aha!
```
4.9.2. Requirements
The following directories, or symbolic links to directories, must be in 
/usr/local
Directory
Description
bin
Local binaries
etc
Host-specific system configuration for local
binaries
games
Local game binaries
include
Local C header files
lib
Local libraries
man
Local online manuals
sbin
Local system binaries
share
Local architecture-independent hierarchy
src
Local source code
No  other  directories,  except  those  listed  below,  may  be  in  
/usr/local
  after  first  installing  a  FHS-
compliant system.
```

**Comment by JL2210** [comment]
Yes, I know, *after first installing*, but I think Chromebrew would count, as it's a package manager.

**Comment by uberhacker** [comment]
https://wiki.linuxfoundation.org/en/FHS Gone!

**Comment by JL2210** [comment]
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf
