### ISSUE TITLE
VLC Package

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2785]
VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files, and various streaming protocols.

Source: http://ftp.videolan.org/pub/videolan/vlc/3.0.4/vlc-3.0.4.tar.xz

**Dependencies:**
======
Sources: https://download.videolan.org/contrib/
- [x] [a52](http://liba52.sourceforge.net/) - #2786 
- [x] [aom](https://aomedia.googlesource.com/aom/)
- [x] [aribb24](https://github.com/nkoriyama/aribb24)
- [x] [aribb25](https://code.videolan.org/videolan/aribb25)
- [ ] [asdcplib](https://www.cinecert.com/asdcplib/)
- [ ] [breakpad](https://chromium.googlesource.com/breakpad/breakpad/)
- [x] [cddb](http://libcddb.sourceforge.net/)
- [x] [chromaprint](https://github.com/acoustid/chromaprint)
- [ ] [crystalhd](https://github.com/yeradis/crystalhd)
- [ ] [daala](https://xiph.org/daala/)
- [ ] [dvbpsi](https://www.videolan.org/developers/libdvbpsi.html)
- [ ] [dvdcss](https://www.videolan.org/developers/libdvdcss.html)
- [x] [dvdnav](https://www.videolan.org/developers/libdvdnav.html)
- [x] [dvdread](http://dvdnav.mplayerhq.hu/#download)
- [ ] [ebml](http://matroska-org.github.io/libebml/)
- [ ] [faad2](https://github.com/dsvensson/faad2)
- [ ] [fluidlite](https://github.com/divideconcept/FluidLite)
- [x] [glew](http://glew.sourceforge.net/)
- [ ] [gme](https://github.com/mcfiredrill/libgme)
- [ ] [goom](http://www.fovea.cc/?page=details_produits&id=goom)
- [ ] [gsm](http://www.quut.com/gsm/)
- [ ] [kate](https://wiki.xiph.org/OggKate)
- [x] [libbluray](https://www.videolan.org/developers/libbluray.html)
- [ ] [libbpg](https://bellard.org/bpg/)
- [x] [libdca](https://www.videolan.org/developers/libdca.html)
- [ ] [libfluid](http://opennetworkingfoundation.github.io/libfluid/)
- [ ] libmpeg2
- [ ] libplacebo
- [x] live555
- [ ] matroska
- [ ] mfx
- [ ] microdns
- [ ] modplug
- [x] mpg123
- [ ] mysofa
- [ ] nfs
- [ ] orc
- [ ] [pcsclite](https://pcsclite.apdu.fr/)
- [ ] postproc
- [ ] projectM
- [ ] pthreads
- [x] qtsvg
- [x] ragel - #2786 
- [ ] regex
- [x] samplerate
- [ ] schroedinger
- [x] SDL_image
- [ ] shout
- [ ] sidplay2
- [ ] sparkle
- [ ] spatialaudio
- [x] taglib
- [ ] tiger
- [ ] tremor
- [ ] twolame
- [ ] vncclient
- [x] vpx
- [ ] xorg-macros
- [x] xproto
- [x] zvbi

**Comment by superloach** [comment]
Does anyone know where to find `aom`? It looks like it *might* be part of `ffmpeg`, but I'm not entirely sure.

**Comment by JL2210** [comment]
https://github.com/mozilla/aom

**Comment by superloach** [comment]
Yeah, I found it. Thanks though!

**Comment by superloach** [comment]
Also, I've realized that I can just use this for all the sources, which is nice.
https://download.videolan.org/contrib/

**Comment by JL2210** [comment]
They're not all the latest, though. On libdvdcss2, you actually have to go crawling around the mirror to get the latest version. Talk about annoying.

**Comment by superloach** [comment]
Well yes, but these provide a fantastic start

**Comment by uberhacker** [comment]
@JL2210: The latest versions of some dependencies may break this package, however.  I think we're having the same problem with ffmpeg currently.

**Comment by JL2210** [comment]
Let me guess, API changes in openssl? I hate that.

**Comment by JL2210** [comment]
Well, I need to recover my Chromebook while still keeping all my data. Gotta go for a few minutes. I'll be in the living room working on it.

**Comment by uberhacker** [comment]
Yeah, openssl 1.1.x definitely breaks stuff that relies on 1.0.x.  They completely re-engineered it.  Not sure why it's only a minor instead of a major release.  Too many cooks in the kitchen is my guess.

**Comment by JL2210** [comment]
I do think it is a tad bit better, even if they did break some stuff. They might have too many cooks in the kitchen, but those cooks are pretty smart. One way they're smart is that you can install both openssl's at the same time.

**Comment by superloach** [comment]
I noticed `breakpad` was from the Chromium project. After a quick `find`, apparently there's an arm version of `libsc-breakpad.so` under the _Android_ image on my Chromebook! 😂

**Comment by JL2210** [comment]
@superloach, it should probably be libfluid. Also, https://www.videolan.org/developers/libdca.html is dca.

**Comment by saltedcoffii** [comment]
VLC is now available with flatpak

**Comment by heavygabriel** [comment]
@uberhacker: I think that this thread should be closed since VLC is available with flatpak.

**Comment by uberhacker** [comment]
Does it work with flatpak?

**Comment by Mia-Rain** [comment]
This should be re-opened as flatpak is broken beyond use currently and having flatpak doesn't solve the fact that the package is missing. Seeing as there is a ton of packages required it might be a good idea for someone to focus all their attention on this, I could try adding these packages but it's been a while since I worked on chromebrew and I currently don't have the time to be a maintainer.

**Comment by Mia-Rain** [comment]
Unfortunately it seems a crap ton of stuff is broken... Maybe it's ChromeOS Flex but I'm on stable channel so everything should work fine, but tons of stuff is throwing errors about missing symbols and not even any hardware acceleration
