### ISSUE TITLE
Users should be warned about installing the dpkg package

### ISSUE THREAD

**Issue by Ewpratten** [skycocker/chromebrew#2794]
Im not sure how to implement it, so im making it an issue.

When dpkg is installed from chromebrew, it breaks the crouton installer without any clear reason. My suggested fix is to add a message before confirming the installation that says the following:
```
WARNING! Installing dpkg alongside crouton will break your chroots. Proceed at your own risk
```

**Comment by JL2210** [comment]
Oh. It does, doesn't it. I'll add something along these lines to the wiki.

**Comment by JL2210** [comment]
See the FAQ.

**Comment by Ewpratten** [comment]
Yes.

**Comment by JL2210** [comment]
OK. Can you close it?
