### ISSUE TITLE
Add binaries for the dpkg package

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2799]
If we had pre-built binaries for dpkg, it would be much easier to install and to not have to worry about errors. (see #2796 for details)
Currently, it should be possible to build binaries for it, but the build scripts in the `tools/` directory are blocking this.
Why is that?

**Comment by JL2210** [comment]
Not what i'm saying at all. Pre-built binaries for the `dpkg` package in Chromebrew is what I meant.

**Comment by uberhacker** [comment]
Oh, so what you are saying is your cros build script is failing to build the dpkg binaries?  Why doesn't that surprise me? ;)

**Comment by JL2210** [comment]
What? No, the `dpkg.rb` file doesn't have binaries in it right now.

**Comment by JL2210** [comment]
And Bintray doesn't have any either.

**Comment by uberhacker** [comment]
I get that but what does the tools directory have anything to do with building pre-built binaries?

**Comment by JL2210** [comment]
`exclusions+=" docx2txt.rb ***dpkg.rb*** dr.rb far.rb fpc.rb freedos.rb ghc.rb julia.rb kr.rb libtinfo.rb lsb_release.rb"`

**Comment by JL2210** [comment]
Notice the emphasis on `dpkg.rb`. This is in the file `tools/needs_binaries.sh`

**Comment by uberhacker** [comment]
I don't even know why you are even looking at that script.  It's probably there because I couldn't create the binaries elegantly.  It won't block you from building the pre-built binaries.  That is only a report of files helpful to determine which packages need pre-built binaries.

**Comment by JL2210** [comment]
Great. I'll whip up a PR removing dpkg from that.

**Comment by uberhacker** [comment]
Don't remove it.  I put it there for a reason.  There was a problem creating the binaries on all platforms.

**Comment by JL2210** [comment]
Yes, that was before they patched it. It was fixed in 1.19.1, I believe.
