### ISSUE TITLE
Vdev installs libraries in /usr/local/lib on x86_64

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2819]
The `vdev` package installs libraries and files in `/usr/local/lib` on x86_64

**Comment by uberhacker** [comment]
I have created a list of packages that need these kinds of fixes.  See https://github.com/skycocker/chromebrew/issues/2240.  If you want to take a stab at fixing the unchecked items, go for it.  I will go ahead and close this issue and mark it as a duplicate.  If you notice any other packages that aren't on that list, please add there.  Great sleuthing, by the way.
