### ISSUE TITLE
Cannot Install Critical Packages python3 fskit libcap_ng vdev util_linux six glib harfbuzz freetype fontconfig libxinerama libxfont2 libxft xorg_lib mesa libepoxy libxfont xinit xkbcomp xwayland 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2837]
python3 fskit libcap_ng vdev util_linux six glib harfbuzz freetype fontconfig libxinerama libxfont2 libxft xorg_lib mesa libepoxy libxfont xinit xkbcomp xwayland 
(they all depened on python3)

The error is that python3 cannot install.

**Comment by uberhacker** [comment]
@sajjaadf: There is a PR in the queue to help with that issue.  I bumped the priority to, hopefully, get it merged in faster.  In the meantime, you could try to reinstall Chromebrew:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```
Hope that helps.

**Comment by sajjaadf** [comment]
I did try that twice, but anything with GUI wont run

**Comment by sajjaadf** [comment]
Here is the error exactly `"python3 failed to install: `./configure CPPFLAGS=-I/usr/local/include/ncurses -I/usr/local/include/ncursesw LDFLAGS=-Wl,-rpath,-L/usr/local/lib --with-ensurepip=install --enable-shared` exited with 1"`

**Comment by uberhacker** [comment]
What is your architecture?  I will try to reproduce.

**Comment by JL2210** [comment]
Can you give me the full error log, please? Make sure to include the lines before the error itself.

**Comment by sajjaadf** [comment]
I will do, But I'm not on my chromebook. The Arch is AMD or amd71  32bit
chrome os Canary Dev_Mode with read write system. Just did a powerwash with
a brittle sponge and a jet washer.
[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by JL2210** [comment]
That's the problem. Canary and Dev Mode are not supported.

**Comment by JL2210** [comment]
Just revert to the stable channel and it should work.

**Comment by sajjaadf** [comment]
I was reading about the gui thing- I need arduino to run without crouton

[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sajjaadf** [comment]
I have a package request for Arduino Ide for Chromebrew
[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sajjaadf** [comment]
I will start finding Dependencys- But I need help for it.
[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sajjaadf** [comment]
Will start working on it after school. ( Yes i'm 13 years old )
[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by JL2210** [comment]
Same. Can you give me `build.log` from the command `cd ~/Downloads/ && crew install -s python3 &>build.log`?

**Comment by uberhacker** [comment]
Is this still an issue @sajjaadf?  If not, can we close?

**Comment by sajjaadf** [comment]
python3: Python is a programming language that lets you work quickly and integrate systems more effectively.
https://www.python.org/
version 3.7.1
Downloading source...
[1;32mArchive downloaded[0m
Unpacking archive, this may take awhile...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
[1;34mRename all *.la files to *.la_tmp[0m
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
configure: WARNING: unrecognized options: --with-ensurepip, --enable-shared
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
configure: error: cannot run /bin/bash ./config.sub
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
[1;31mpython3 failed to install: `./configure CPPFLAGS=-I/usr/local/include/ncurses -I/usr/local/include/ncursesw LDFLAGS=-Wl,-rpath,-L/usr/local/lib --with-ensurepip=install --enable-shared` exited with 1[0m

**Comment by sajjaadf** [comment]
This is the build.log

**Comment by sajjaadf** [comment]
I think It should be closed

**Comment by JL2210** [comment]
Great.

**Comment by JL2210** [comment]
Duplicate of #2838
