### ISSUE TITLE
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by akossomfai** [skycocker/chromebrew#2838]
## Description
Executing sed fails related to shared library libselinux.so.1.

If you executed a specific command:
```shell
sed
```

Output:
```shell
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: `crew --version`
1.0.3

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_RELEASE_BOARD=daisy-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=daisy-release/R70-11021.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=11021
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=70
CHROMEOS_RELEASE_DESCRIPTION=11021.56.0 (Official Build) stable-channel daisy 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11021.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11021.56.0

Model: Samsung xe303c12

Architecture: `uname -m`
armv7l

## Addtional information
"crew install sed" does not help, just gives:

Package sed already installed, skipping...
Sed installed!

**Comment by JL2210** [comment]
Can you give me the output of `crew files sed`?

**Comment by JL2210** [comment]
Try first `crew update && crew upgrade` and then from there, try to build `sed` from source: `crew remove sed && crew install -s sed`

**Comment by uberhacker** [comment]
@JL2210: I don't think he will be able to install sed from source since sed is needed to compile packages and removing it will force the compiler to use the system sed which runs everything in sandbox mode (basically meaning any `sed -e ...` operations will puke).  Maybe just try a reinstall: `crew remove sed && crew install sed` without the `-s` switch.

**Comment by JL2210** [comment]
You're right. I can't believe I forgot about that.
`sed -e` will succeed, but `sed 'e/<someting'` will fail. Sandbox mode isn't nearly as bad as you think it is. The `-e` option just adds another expression to evaluate.
```
-e script
--expression=script
Add the commands in script to the set of commands to be run while processing the input.
```
Read the docs: https://www.gnu.org/software/sed/manual/sed.html

**Comment by JL2210** [comment]
Example:
```
chronos@localhost ~/Downloads/unhardcode-ld_default-package/packages $ /bin/sed 'e/hello'
/bin/sed: -e expression #1, char 1: e/r/w commands disabled in sandbox mode
chronos@localhost ~/Downloads/unhardcode-ld_default-package/packages $ echo 'Hello, World!' | /bin/sed -e 's/Hello/Goodbye/g'
Goodbye, World!
chronos@localhost ~/Downloads/unhardcode-ld_default-package/packages $ 
```

**Comment by JL2210** [comment]
Keep in mind that this is SUPPOSED to be a secure OS, not a developer's playground. Chrome OS is probably, out of all the Linux distributions (if you could call it that), the most secure one and the most non-forbearing on lax file permissions. For example, Linux users in general can usually execute files in the `/tmp` directory. Chrome OS doesn't allow that, as it can be a security issue. It also does not allow programs to be executed from the user's home directory.
Even file permissions are useless, sometimes. For example, I once created a file as `root` and changed the file permissions on it to `000`. I was still able to remove it as `chronos`, even with those file permissions.
Needless? Would you like somebody being able to run a command as `sudo` without a password on your "secure" system?

**Comment by JL2210** [comment]
```
For sed, this is new behavior.  We're disabling support for the e/r/w
commands because (1) we don't care about them and have no known legit
users and (2) they needlessly expose random shell scripts to attacks.
```
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-reviews/GMCN7k7SMLQ
By Mike Frysinger himself.

**Comment by uberhacker** [comment]
I wouldn't give anybody sudo access.  If ChromeOS was really that secure, they wouldn't even allow the chronos user to execute sudo, but they do.

Tell Mike Frysinger he must not have attempted to compile any open source code lately because A LOT of Makefile scripts still use sed in the "unsecure" way.  Maybe if can asked him to rewrite all those scripts to work in sandbox mode his attitude would change.  This concern about shell scripts open to attack is fooey.  First off, an attacker would need write access to your filesystem and the only way I know how to do that is with a rootkit (which you should be more concerned about than anything else).  If an attacker gains root access to your system, there is no security measure in the world good enough to stop them from doing anything they want.

**Comment by JL2210** [comment]
Keep in mind that `sudo` is only usable in dev-mode. Chrome OS the way it's meant to be used doesn't have to deal with Makefiles. **not a developer's playground** was what you were supposed to be getting from that last comment. A rootkit wouldn't work to modify the root filesystem, because the root filesystem is being constantly verified by the (also verified) kernel. People can still run bash scripts through pipes ( `curl -Ls https://git.io/vddgY | bash` anyone? ).

```
Rootkits require local software installation, and access to the kernel. The former is only allowed via the Chrome Web Store, and the second is not allowed in any way, shape, or form. I'd say this is a definite "no."
```
https://productforums.google.com/forum/#!topic/chromebook-central/GCbX7Iasofs

**Comment by JL2210** [comment]
Also from the above link:
`There is a standing $3 Million in prize money that Google has put up; unclaimed to date.`

**Comment by uberhacker** [comment]
Chromebrew is only available in dev-mode.  Not sure what is the point.  If you can sudo, you can change permissions.  That is how we change the `/usr/local` directory to be rwx.  In fact, I can mount any directory I want and run any executable I want.  So does that make ChromeOS insecure?  Maybe...but so what?  If I hose my system, I can powerwash and restore.  No big deal.

**Comment by JL2210** [comment]
Exactly. But when *not* in dev-mode, Chrome OS is probably the most secure OS you can get. That it does not have trouble achieving. I do agree with you in that I don't like the fact that they have all these crazy security things. But if they didn't, that goal would be much harder to reach.
(Also, as a side note, it's not kind to say that things people do are `stupid and totally unnecessary`. Most often, these things have a reason for being done.)
+1 for the note about Powerwashing. That's one of the best things about Chrome OS.

**Comment by JL2210** [comment]
Back to the real issue: Can you update to the latest release on your armv7l Chromebook and recompile `sed`? That might fix the issue.

**Comment by uberhacker** [comment]
I stand by my statement. :)

**Comment by JL2210** [comment]
Anyway, on with the real issue. Could you do that?

**Comment by uberhacker** [comment]
I don't have a problem with sed on my armv7l or aarch64 system.  I think his issue is due to not being on the stable channel if I read all that correctly.

**Comment by JL2210** [comment]
`CHROMEOS_RELEASE_DESCRIPTION=11021.56.0 (Official Build) `*stable-channel*` daisy`

**Comment by uberhacker** [comment]
@akossomfai: I'm not having a problem with sed on my armv7l system:
```
chronos@localhost ~$ sed --version
sed (GNU sed) 4.5
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
chronos@localhost ~$ crew const CHROMEOS_RELEASE
CHROMEOS_RELEASE=70
```
I recently updated to release 70.  You might try reinstalling fresh:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by JL2210** [comment]
@akossomfai Try updating your Chrome OS version. Go to `Settings->About Chrome OS->Check for updates`

**Comment by uberhacker** [comment]
@JL2210: He is already updated to the latest (release 70).  Something is corrupt, apparently.

**Comment by JL2210** [comment]
Maybe something's wrong on your end. It looks like everybody else is having this issue.

**Comment by akossomfai** [comment]
Using the latest ChromeOS (70.0.3538.76, 32 bit).
Tried to remove /usr/local then do a fresh reinstall. The problem is still seen, also during re-install:

Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
sed: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
Performing post-install...
Most installed!

**Comment by uberhacker** [comment]
What is the output of `echo $LD_LIBRARY_PATH`?  Not sure why sed is referencing selinux.

**Comment by akossomfai** [comment]
chronos@localhost ~ $ echo $LD_LIBRARY_PATH
/usr/local/lib

**Comment by uberhacker** [comment]
I just reinstalled Chromebrew after completely wiping out my `/usr/local` directory and still can run sed fine.  Try this (if you can) and let me know the output:
```
$ crew install mlocate
$ sudo updatedb
$ locate libselinux.so.1
```

**Comment by uberhacker** [comment]
@JL2210: sed is not working.  crew may still work.

**Comment by akossomfai** [comment]
Yes, crew seems to work.
The output of "locate libselinux.so.1" is empty.
Seems that there is no selinux lib installed:

chronos@localhost ~ $ locate selinux
/etc/selinux
/etc/selinux/arc
/etc/selinux/config
/etc/selinux/arc/contexts
/etc/selinux/arc/policy
/etc/selinux/arc/contexts/files
/etc/selinux/arc/contexts/files/file_contexts
/etc/selinux/arc/policy/policy.30
/mnt/stateful_partition/dev_image/include/linux/selinux_netlink.h
/usr/local/include/linux/selinux_netlink.h
chronos@localhost ~ $

**Comment by JL2210** [comment]
Fine.

**Comment by akossomfai** [comment]
chronos@localhost ~ $ crew const CHROMEOS_RELEASE
CHROMEOS_RELEASE=70
chronos@localhost ~ $

**Comment by uberhacker** [comment]
Thank you.  I just wanted to be sure since I have `/lib/libselinux.so.1` on my armv7l system.  I wish I understood why your system is different.  Apparently, Google has different images based on the hardware.  I'll see if I can rebuild the binaries without selinux support.  Probably what happened was it enabled selinux on my binary build and since release 69 and below included it on other hardware platforms, it worked then.  These kinds of differences makes testing more difficult.

**Comment by uberhacker** [comment]
@akossomfai: Please execute the following when you get a chance and let me know if this fixes your issue:
```
crew update && crew upgrade sed
```
Thanks

**Comment by JL2210** [comment]
@akossomfai It's mine, but no big deal. @uberhacker really helped with the binaries.

**Comment by akossomfai** [comment]
@JL2210: thanks for you too.
