### ISSUE TITLE
Package Request-Arduino IDE

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2841]
I'm currently working on this, but I could use some help.
As far as I know, Chromebrew has all the dependencies for this.
Depends on #2840 

See https://github.com/skycocker/chromebrew/issues/2837#issuecomment-436023787 for details.

**Comment by sajjaadf** [comment]
I think Some packages would be 

 `python3 fskit libcap_ng vdev util_linux six glib harfbuzz freetype fontconfig libxinerama libxfont2 libxft xorg_lib mesa libepoxy libxfont xinit xkbcomp xwayland sommelier `

**Comment by JL2210** [comment]
No. Not really dependencies. I think the package pulls in all the dependencies itself.

**Comment by sajjaadf** [comment]
This is what I use currently to run it
`sudo mount -o remount,rw -o exec /home/chronos/user
them cd ~/Downloads/'Linux Apps'/Arduino-1.8.7
then sudo chmod a+rw /dev/ttyACM0
then ./arduino`

**Comment by JL2210** [comment]
Not bad, but I want to make this into a system-wide installation. I'll probably install it into <CREW_PREFIX>/share/arduino-1.8.7-linux<ARCH>

**Comment by sajjaadf** [comment]
The `sudo chmod a+rw /dev/ttyACM0 ` is to get my Arduino to get not permission denied.

**Comment by JL2210** [comment]
Yeah. I understand. It's just not polite to use sudo privileges without the user knowing. `gksu` has a graphical prompt asking for user confirmation.

**Comment by JL2210** [comment]
BTW, not a good idea to make your little Arduino world-writable. Just run `sudo -E ./arduino`
