### ISSUE TITLE
Invalid file in arm binary for jdk8

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#285]
There's an invalid file in the jdk8 binary for ARM, namely `create_package.sh` rendering the error message `mv: inter-device move failed: ‘/usr/local/tmp/crew//create_package.sh’ to ‘/create_package.sh’; unable to remove target: Read-only file system`.

This doesn't break installation, but should probably be fixed anyway.

**Comment by jam7** [comment]
x86_64 jdk8 has an identical problem.

It's good to place crewte_package.sh at the parent directory of target something like...
```
/dest/create_package.sh
/dest/jdk8u111-armv7l/usr/local/...
```
then performs
```
$ cd /dest/jdk8u111-armv7l/
$ sh ../create_package.sh
```

**Comment by bfayers** [comment]
This is likely my fault, though the create_package.sh leaves itself in...

**Comment by jam7** [comment]
Close in favor of #980
