### ISSUE TITLE
Maybe... WINE (Windows apps...)

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2851]
Is this even possible on arm?

**Comment by JL2210** [comment]
With a statically linked x86 WINE and QEMU installed, yes.

**Comment by sajjaadf** [comment]
what is linked statically?

**Comment by JL2210** [comment]
x86 wine that works in QEMU

**Comment by JL2210** [comment]
I'm building a copy right now.

**Comment by JL2210** [comment]
If you want it to go faster, just a tip: Use 
```
make -j$(( `nproc --all` + 1 ))
```

**Comment by sajjaadf** [comment]
Okay
[image: Picture]
Sajjaad Farzad
        About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
