### ISSUE TITLE
(Abandoned) GUI Package Store (Still can be made)

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2861]
This could be a very good idea, maybe with the command` Crew store`?

**Comment by sajjaadf** [comment]
Making a mockup with a stock chromeOS screenshot

**Comment by sajjaadf** [comment]
Use Issue #2579 for icon

**Comment by sajjaadf** [comment]
- [ ] Get icon

- [ ] Get support

- [ ] Get Gui working

**Comment by sajjaadf** [comment]
#2460 Is a step to add deb files

**Comment by sajjaadf** [comment]
#889 from #886 gui

**Comment by sajjaadf** [comment]
Please put the improvement tag and help wanted tag and Gui and enhancement tag

**Comment by sajjaadf** [comment]
#2061 for running it as gtk3

**Comment by 5nowx** [comment]
how can i help? I'm not much of a developer except maybe python
