### ISSUE TITLE
Package Request- LibreOffice

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2862]
Is this even useful?

**Comment by sajjaadf** [comment]
![screenshot-2018-09-04-at-5 17 17-am](https://user-images.githubusercontent.com/32078755/48381231-e286d880-e68f-11e8-8c71-f1649e2d3d91.png)

**Comment by uberhacker** [comment]
Very useful as an alternative to Google Docs.  I tried this awhile ago.  It's not for the faint of heart. <3

**Comment by sajjaadf** [comment]
So, could this work?

**Comment by JL2210** [comment]
Yeah. I'll get some time in on it after Arduino.

**Comment by rafi16jan** [comment]
When is this ready? Please make for ARM too :)

**Comment by JL2210** [comment]
Seriously, dude? ARM support was added and automated a long time ago. The
Chromebrew packages work with all architectures.

**Comment by JL2210** [comment]
Oh. If it works, then it works. We're not going to patch it to add ARM
support, if that's what you're asking.

**Comment by rafi16jan** [comment]
@sajjaadf hey how do you get that nice looks on crostini? mine is very ugly 
![image](https://user-images.githubusercontent.com/7939687/49293016-65f25780-f4e1-11e8-982d-fc2ff717c7f2.png)

**Comment by rafi16jan** [comment]
turn out I haven't install libreoffie-gtk3

**Comment by uberhacker** [comment]
@rafi16jan: We do not support Crostini.  Have you checked the ChromeOS forums?

**Comment by sajjaadf** [comment]
@rafi16jan What os it THAT?
Can you tell me please?

**Comment by rafi16jan** [comment]
@sajjaadf lol, its FydeOS, it have play store and crostini
@uberhacker no I'm just asking sajjad why the gtk theme is bad, turnout I haven't install the libreoffice gtk theme deb package

**Comment by JL2210** [comment]
It looks like FlintOS.
