### ISSUE TITLE
Package request-Geary mail client

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2863]
I see that Chromebooks could support this easy.

**Comment by sajjaadf** [comment]
![screenshot-2018-09-09-at-7 22 42-pm](https://user-images.githubusercontent.com/32078755/48381221-d7cc4380-e68f-11e8-8e8b-8c95044227e3.png)

**Comment by JL2210** [comment]
How did you install that? What `configure` command did you use, more specifically?

**Comment by skiman6010** [comment]
@JL2210 That looks like a screenshot from Androidpolice that Corbin posted on one of his or another writers article on Crostini.

**Comment by uberhacker** [comment]
@sajjaadf: Is that a GNOME app?  If so, we just merged in the `gnome_icon_theme` package yesterday.  It was needed for the gui version of transmission.

**Comment by sajjaadf** [comment]
Oh
