### ISSUE TITLE
Package request-Atom

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2864]
Just to solve all of the text editor issues

**Comment by sajjaadf** [comment]
![screenshot-2018-09-04-at-5 33 32-am](https://user-images.githubusercontent.com/32078755/48381203-ca16be00-e68f-11e8-86d8-52c707a8cde7.png)

**Comment by uberhacker** [comment]
This editor is built with Electron like the code package.  Electron apps have not been very Chromebrew friendly lately.

**Comment by sajjaadf** [comment]
Use Snap #1719 for electron apps [snapcraft.io]( https://snapcraft.io/store)
