### ISSUE TITLE
Package request-Transmission

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2865]
Torrents are useful

**Comment by sajjaadf** [comment]
![screenshot-2018-09-09-at-7 43 52-pm](https://user-images.githubusercontent.com/32078755/48381189-be2afc00-e68f-11e8-9d69-4ad068ed6c63.png)

**Comment by uberhacker** [comment]
@sajjaadf: We already have the cli version of this package.  PR #2869 update supports the gtk (ie. gui) client as well as the daemon which downloads files automatically in `~/Downloads` if the torrent is available.
