### ISSUE TITLE
getconf not found (ENOENT)

### ISSUE THREAD

**Issue by camdroid** [skycocker/chromebrew#287]
When I try to install Chromebrew, I get a message that the installation was successful, but also get an error message about not being able to find getconf. When I try using Chromebrew to install anything, it just gives me the same error about not being able to find getconf.

```Last-modified header missing -- time-stamps turned off.
2016-12-21 10:31:34 (69.6 MB/s) - 'linuxheaders.rb' saved [721/721]

/usr/local/bin/crew:19:in ``': No such file or directory - getconf (Errno::ENOENT)
        from /usr/local/bin/crew:19:in `<main>'
/usr/local/bin/crew:19:in ``': No such file or directory - getconf (Errno::ENOENT)
        from /usr/local/bin/crew:19:in `<main>'
ln: failed to create symbolic link ‘/usr/local/bin/cc’: File exists
bash: line 137: git: command not found
bash: line 138: git: command not found
bash: line 139: git: command not found
bash: line 140: .git/info/sparse-checkout: No such file or directory
bash: line 141: .git/info/sparse-checkout: No such file or directory
bash: line 142: .git/info/sparse-checkout: No such file or directory
bash: line 143: git: command not found
bash: line 144: git: command not found
Chromebrew installed successfully and package lists updated.```

```chronos@localhost / $ crew install git
/usr/local/bin/crew:19:in ``': No such file or directory - getconf (Errno::ENOENT)
        from /usr/local/bin/crew:19:in `<main>'```

**Comment by clening** [comment]
I'm getting the same error, running on a chromebook Pixel 2. Not sure how to diagnose or resolve this.

**Comment by camdroid** [comment]
I'm on an HP 13 G1, guess I should've mentioned that in the original post.

**Comment by finwo** [comment]
The same problem occures on my Acer Chromebook 14. In my case it happened installing after a powerwash. (Chromebrew was installed before the powerwash).

**Comment by camdroid** [comment]
Huh, same thing happened for me - I had Chromebrew installed and working (along with crouton, although I'm not sure if that's relevant), then did a powerwash, and suddenly Chromebrew wouldn't even install.

**Comment by finwo** [comment]
Just found a way to temporarily work around the issue. The error appeared due to the getconf binary missing on the machine.

After making sure the arch of my chromebook was x86_64, I've copied the getconf binary from another x86_64 machine (ubuntu 14.04 in this case, it was located in `/usr/bin`). After verifying the getconf binary worked, the chromebrew installer worked like a charm.

**Comment by camdroid** [comment]
Same thing worked for me, although I copied getconf from CentOS 6.4 instead of Ubuntu. Guess if they're not the same, they're close enough.

**Comment by clening** [comment]
@finwo Curious - When I try doing a mv / cp of a separate copy of getconf, I get the following error: 

`mv: inter-device move failed: ‘/home/chronos/user/Downloads/getconf’ to ‘/usr/bin/getconf’; unable to remove target: Read-only file system`

How did you get around that error?

**Comment by lyxell** [comment]
@clening Move it to `/usr/local/bin` instead of `/usr/bin`.

**Comment by thedamian** [comment]
Ok. I just removed the line that sets it to a non-used variable.
Please try again. You'll have to do either a "crew update" if that works or just manually edit the crew file that should be in /usr/local/lib/crew/crew 

Please tell if when anyone tests this.

**Comment by thedamian** [comment]
I essentially commented (put a # in front of) the line with getconf

**Comment by finwo** [comment]
@thedamian Just ran `crew update`.
As a test I've ran `crew upgrade` to check if the install still works (re-installing should not make a difference, as it also depended on getconf), and it does on my machine.

Just thinking about it, just like `getconf`, the following file should be present on all linux (and thus ChromeOS as well) systems: `/proc/cpuinfo`. You might be able to fetch the cpu word-size from it, for if you can't depend on the newly-added switch (a.k.a. new cpu types)

**Comment by cstrouse** [comment]
@finwo You can see if a CPU is 64-bit my looking for the "lm" flag in /proc/cpuinfo. You can also check gcc's default target to see if it's configured for 64-bit or not.

**Comment by lyxell** [comment]
Closing as resolved.
