### ISSUE TITLE
Instead of atom, what about Bluefish?

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2872]
[http://bluefish.openoffice.nl/index.html](http://bluefish.openoffice.nl/index.html)

**Comment by uberhacker** [comment]
Why not both? :)  You might also want to check out scite which was merged into master yesterday.

**Comment by sajjaadf** [comment]
Show me please

**Comment by uberhacker** [comment]
`crew install scite` then type `scite` to launch.

**Comment by sajjaadf** [comment]
is it gui?

**Comment by uberhacker** [comment]
Yes
