### ISSUE TITLE
How Do you import your own packages to chromebrew?

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2873]
Like a atom.rb package

**Comment by sajjaadf** [comment]
HELP PLEASE

**Comment by uberhacker** [comment]
@sajjaadf: Not sure what you mean by importing but you can create an atom package.  See https://github.com/skycocker/chromebrew/wiki/Creating-a-package.

**Comment by sajjaadf** [comment]
Like use a demo.rb file to see if it works

**Comment by sajjaadf** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhh
