### ISSUE TITLE
[firefox] Why Wont this Package Work...

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2880]
I cant get Firefox.rb from uberhackers fork work...

**Comment by uberhacker** [comment]
@sajjaadf: That is definitely still a WIP.  Probably missing a few (or a lot of) dependencies.

**Comment by sajjaadf** [comment]
Do you think firefox will work though. I cant find an Arm build

**Comment by uberhacker** [comment]
Hard to say.  I gave it a somewhat half-hearted effort the first time I tried installing it.  More effort needed on the next try.  We can try building it from source for arm.

**Comment by sajjaadf** [comment]
what is GLIBC_2.27? my build says it needs it.

**Comment by sajjaadf** [comment]
```
XPCOMGlueLoad error for file /home/chronos/user/Downloads/usr/lib/firefox/liblgpllibs.so:
/usr/local/lib/libm.so.6: version `GLIBC_2.27' not found (required by /home/chronos/user/Downloads/usr/lib/firefox/liblgpllibs.so)
Couldn't load XPCOM.
```

**Comment by sajjaadf** [comment]
what is needed here?

**Comment by uberhacker** [comment]
A newer version of glibc2.23 which is currently installed in Chromebrew.

**Comment by sajjaadf** [comment]
How can I change dependncys?

**Comment by uberhacker** [comment]
Looks like another missing dependency.

**Comment by sajjaadf** [comment]
The 'Firefox' file is gibberish

**Comment by sajjaadf** [comment]
is it convertable?

**Comment by uberhacker** [comment]
You need to add another package.  Probably liblgpllibs.rb

**Comment by uberhacker** [comment]
Maybe with a lot of effort.

**Comment by sajjaadf** [comment]
have you made that?

**Comment by sajjaadf** [comment]
lemme make a fake pakage
