### ISSUE TITLE
Package Request-Firefox

### ISSUE THREAD

**Issue by theMackabu** [skycocker/chromebrew#2882]
I have tried so much by Glibc2.27 and ongar are missing.

**Comment by sajjaadf** [comment]
And firefox.rb does not work

**Comment by uberhacker** [comment]
This is proving to be a difficult package to build.

**Comment by sajjaadf** [comment]
It has been

**Comment by sajjaadf** [comment]
Why can you assign labels?

**Comment by uberhacker** [comment]
As a co-maintainer of this project, I have that permission.

**Comment by sajjaadf** [comment]
oh

**Comment by uberhacker** [comment]
This browser package may be possible once release 72 is stable.

**Comment by JL2210** [comment]
Or, with a source build, possible now. I've built Firefox from source before. It's not that hard.

**Comment by sajjaadf** [comment]
Can You specify How you did that please?

**Comment by JL2210** [comment]
Follow the instructions on their web page after downloading the source.

**Comment by sajjaadf** [comment]
I can’t seem to do it on armv7I
--
Sent with DejaLu (https://dejalu.me?sig)

**Comment by uberhacker** [comment]
This might be a possibility once release 72 rolls.

**Comment by JL2210** [comment]
I don't understand why 72 might fix this. We could always just build from
source. We have rust and cargo.

**Comment by uberhacker** [comment]
Release 72 will have libc 2.27 which this requires.

**Comment by torzod** [comment]
has any progress been made towards getting firefox working?

**Comment by JL2210** [comment]
It'll take a while.

**Comment by cstrouse** [comment]
@torzod Firefox works but is having sound-related issues.

**Comment by vincowl** [comment]
@uberhacker Maybe we can close this one ?

**Comment by uberhacker** [comment]
Yep, good call.
