### ISSUE TITLE
Not A chromebrew issue- a message to JL2210 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2883]
Your avatar icon is blurry

![38843657](https://user-images.githubusercontent.com/32078755/48677540-26179180-eb2b-11e8-8f93-f4c130a9c606.jpeg)

Vs: 

![1778935](https://user-images.githubusercontent.com/32078755/48677542-2adc4580-eb2b-11e8-8df8-f10a0546d77e.png)

**Comment by sajjaadf** [comment]
Want to fix it?

**Comment by skiman6010** [comment]
No. This is not what issues are for. The collaborators on this project get an email with each and every issue and PR submitted on this project

Please feel free to submit issues relating to `crew` but keep "issues" like this to yourself. This would fit well in our random chat on our Slack. Feel free to join that for more casual conversation. 

Thanks for understanding.

**Comment by sajjaadf** [comment]
Okay
