### ISSUE TITLE
It's time to drop support for i686.

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2900]
Proposal:
> As Chrome OS release 72 comes up, along with the non-optional update to glibc 2.27 for most of our users, the time to drop support for i686 in the installer has come. After this is done, existing Chromebrew users will not be affected, however new users will not be able to install. New and/or updated binaries will not be uploaded to Bintray, and any pre-existing binaries and/or support for i686 will slowly be dropped. We plan to complete this by 2020. Chrome OS version 71 will be the last supported version by Chromebrew. We regret any inconveniences this may cause for our users.

**Comment by JL2210** [comment]
Can you label this [i686] and [please review]?

**Comment by JL2210** [comment]
Also, may I suggest removing i686 support from the master branch at the time 72 becomes stable and creating a fork called chromebrew-i686?

**Comment by uberhacker** [comment]
I have a plan to avoid this, hopefully.

**Comment by sajjaadf** [comment]
Good thing Im armv7I

**Comment by sajjaadf** [comment]
How?

**Comment by JL2210** [comment]
@uberhacker Thanks.

**Comment by uberhacker** [comment]
@sajjaadf: The idea is simple, really.  We will just support both glibc 2.23 and 2.27.  There will be a transition period where we'll need to support both versions anyway (from release 71 to 72).

**Comment by sajjaadf** [comment]
okay

**Comment by JL2210** [comment]
2.23 is broken now. It can't even be built by gcc 7.3.0. Why do all this work for 1% of our users?

**Comment by uberhacker** [comment]
@JL2210: Please read my earlier comment.  BTW, it's not a lot of work.  The change is minor.

**Comment by JL2210** [comment]
I understand. Explain to me how we are going to build the package under a
new name?

**Comment by JL2210** [comment]
As it cannot be built with GCC 7.3.0.

**Comment by uberhacker** [comment]
I added a note about support on README.md.

**Comment by JL2210** [comment]
All right. However, until i686 support is fully dropped, I'd like this to still be open. After all, the original intent of this was to drop *all* support.

**Comment by uberhacker** [comment]
Apparently, you haven't read the README.md yet.

**Comment by JL2210** [comment]
Thank you. Do you need some help with the new glibc?

**Comment by uberhacker** [comment]
I have a working branch in my repo named `update-glibc-2.23-2.27`.

**Comment by rafi16jan** [comment]
Guys, your wine build is defaultly installs to 64 bit wine on x86_64. Don't drop support to all i686 packages because we still need 32 bit wine

**Comment by uberhacker** [comment]
@rafi16jan: How would you suggest we change to support i686 on x86_64 systems?

**Comment by rafi16jan** [comment]
@uberhacker I don't know. I mean packages like 32 bit wine is still critical, many of the legacy windows apps (which is where wine is good at, like the old MS Office) can only be ran on 32 bit wine. Maybe just make wine the only supported GUI 32 bit app?

Besides, can you elaborate about the build_cros_gcc script? I can't make it work although the command prints valid targets but it does nothing

**Comment by uberhacker** [comment]
We can build a 32-bit wine but it would only be installable on i686 systems.  I will let @JL2210 answer the build_cros_gcc script question since he is convinced it works.

**Comment by skiman6010** [comment]
@rafi16jan Can you not use wine prefixes? This is the recommended way of running 32 bit programs on wine. 

https://askubuntu.com/questions/74690/how-to-install-32-bit-wine-on-64-bit-ubuntu

**Comment by rafi16jan** [comment]
@skiman6010 I tried, but wine command is actually a simlinked to wine64 and winecfg, winefiles and stuff are all 64 bit. It gives an error "winecfg is a 32-bit installation, it cannot support 64-bit applications." if I put WINEPREFIX to a 32 bit prefix or WINEARCH=win32.

**Comment by skiman6010** [comment]
@rafi16jan Okay... can you please create a new issue for wine then? Thanks.

**Comment by rafi16jan** [comment]
#3049 @skiman6010
