### ISSUE TITLE
Package Request-Minecraft launcher 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2901]
Idk if either will work.

**Comment by uberhacker** [comment]
Is this 2 requests or 1?  If 2, we should probably split into separate issues.

**Comment by sajjaadf** [comment]
Okay

**Comment by JL2210** [comment]
Minecraft is proprietary software, and needs a license. Chromebrew is GPL and open-source. We can't do this.

**Comment by sajjaadf** [comment]
Not even mc launcher.jar

**Comment by sajjaadf** [comment]
you need to sign into mc to play to

**Comment by suoko** [comment]
What about sklauncher?
