### ISSUE TITLE
Cursor bug (Reference)

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2902]
For any Gtk Gui app gets a black block as cursor

**Comment by uberhacker** [comment]
Can you please provide your system specs?

**Comment by sajjaadf** [comment]
chromebrew: Latest version, just ran crew update

ChromeOS: 72 canary December 1st update

Model: Asus C201 PA

Architecture: ArmV7L

**Comment by JL2210** [comment]
72 is not supported. Revert to stable or do it yourself.

**Comment by sajjaadf** [comment]
where is GDK cursor theme stored?

**Comment by JL2210** [comment]
Try `crew install libxcursor xcb_util_cursor`

**Comment by sajjaadf** [comment]
Thanks

--
Sent with DejaLu (https://dejalu.me?sig)

**Comment by sajjaadf** [comment]
Put a label (Reference)
