### ISSUE TITLE
Issue - Vscode give error

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2903]
`(code:9434): Gtk-WARNING **: 22:38:35.661: cannot open display: :0 ` is the error, yes, I did run sommeleir and gimp starts up fine

**Comment by sajjaadf** [comment]
`(code:11119): Gtk-WARNING **: 23:00:35.067: cannot open display: :0`

**Comment by skiman6010** [comment]
You need to give more information. Follow the issue template please.

**Comment by skiman6010** [comment]
@uberhacker seems like a different error to me.
