### ISSUE TITLE
VScode Error 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2906]
## Description
Using a arm version of vscode, when command `code` ran it says `(code:11119): Gtk-WARNING **: 23:00:35.067: cannot open display: :0`

## Versions and system information
chromebrew: Latest version, just ran crew update

ChromeOS: 72 canary December 1st update

Model: Asus C201 PA

Architecture: ArmV7L
 
- [ ] From the Vscode ARM pull request.

**Comment by sajjaadf** [comment]
And Yes, I did try `crew remove eudev && crew install eudev`

**Comment by uberhacker** [comment]
We don't support release 72 yet.  My guess is there is a conflict with glibc 2.27.

**Comment by sajjaadf** [comment]
When will 72 be supported?

**Comment by uberhacker** [comment]
As soon as it becomes the stable channel.  We're on 70 now so the next 2 releases.

**Comment by JL2210** [comment]
Correction: 71 now.

**Comment by JL2210** [comment]
Whoops. That's on desktop.

**Comment by skiman6010** [comment]
@uberhacker He's also using the unsupported arm PR that didn't seem to work very well. I bet that doesn't help either.

**Comment by sajjaadf** [comment]
true

**Comment by JL2210** [comment]
@uberhacker @skiman6010 It's not a 72 issue. He didn't follow the instructions after installing Sommelier.

**Comment by sajjaadf** [comment]
Actually I did and other GUI apps like gimp and ardunio (Running from ./arduino) is working

--
Sent with DejaLu (https://dejalu.me?sig)

**Comment by sajjaadf** [comment]
Also I did the instructions in light blue, its in my .bashrc and gimp Inkscape and other work fine

--
Sent with DejaLu (https://dejalu.me?sig)

**Comment by sajjaadf** [comment]
unofficial package, that had a PR a while back... I Think it was #2798 or #2797

**Comment by skiman6010** [comment]
Do you see why we won't be able to help now? Both of those are closed because of issues.

**Comment by sajjaadf** [comment]
72 is almost out

**Comment by sajjaadf** [comment]
A few weeks from 72 release

**Comment by skiman6010** [comment]
Closed because unofficial port was used that was not merged into Chromebrew.
