### ISSUE TITLE
Package Request - Nautilus or Thunar

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2909]
I've started working on Thunar. If anyone could help with Nautilus, that would be great.

**Comment by uberhacker** [comment]
Both of these file managers are inferior to the spacefm package which was just merged this morning.  Also, these package requests have very fat desktop environment requirements.

**Comment by JL2210** [comment]
Thunar, if at most, has one dependency that Chromebrew doesn't have. I don't think users are going to be happy if they're forced to use the spacefm package, even if Nautilus and Thunar are "inferior".

**Comment by uberhacker** [comment]
Nobody is forcing anybody to use spacefm over any other file manager.  I just thought I could save you the effort of adding an entire desktop environment to install a gui file manager. :)  Maybe we should work on desktop environments before these kinds of apps?

**Comment by sajjaadf** [comment]
XFCE is huge!, and Dolphin is a good file browser too, right?

**Comment by sajjaadf** [comment]
actually 
[SpaceFM](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwik3dq07oTfAhVGOK0KHUjGDYkQjRx6BAgBEAU&url=http%3A%2F%2Fwww.webupd8.org%2F2012%2F02%2Fspacefm-highly-customizable-multi-pane.html&psig=AOvVaw1gICGv_fj-SYDokGHfdtjo&ust=1543967790033015)
V.S.
[Dolphin](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiVgbDb7oTfAhVJXq0KHajcDewQjRx6BAgBEAU&url=https%3A%2F%2Fwww.distroscreens.com%2F2017%2F11%2Fkubuntu-1710-artful-aardvark-screenshots.html&psig=AOvVaw2yrnK83INRcBS-8WAvCOpd&ust=1543967866364643)

**Comment by uberhacker** [comment]
Dophin is actually huger when you consider KDE is the fatest and most bloated of all the desktop environments. :)

**Comment by uberhacker** [comment]
Your Dolphin link is Kubuntu 17.04.  Can you please update?

**Comment by sajjaadf** [comment]
true

**Comment by JL2210** [comment]
All Thunar needs is Exo. That's one package out of the whole ~10 in XFCE.

**Comment by JL2210** [comment]
Darn. Exo depends on a few XFCE libs. Guess I need to create a few more packages.

**Comment by uberhacker** [comment]
Rather than just creating enough packages to get Thunar working, why don't you just go all the way and build all of XFCE?  I imagine future apps that require XFCE will need other resources separate from what Thunar needs.

**Comment by JL2210** [comment]
That sounds like a good idea. For now, though, let's try to reach the smaller goal of building Thunar.

**Comment by uberhacker** [comment]
Both packages are now available.

**Comment by satmandu** [comment]
Honestly I got most of the deps for nautilus working by using the Arch PKGbuild files...
