### ISSUE TITLE
Software center (help needed)

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2939]
- [ ] aptdaemon 
- [ ] gir1.2-glib-2.0 
- [ ] gir1.2-gmenu-3.0 
- [ ] GObject
- [ ] gir1.2-gtk-3.0
- [x] GTK3+
~~GTK+~~
- [ ] gir1.2-webkit-3.0
- [ ] gvfs-backends
- [ ] humanity-icon-theme
- [ ] Humanity Icon theme
- [ ] iso-codes
- [ ] oneconf 
- [ ] policykit-1
- [ ] policykit-1-gnome
- [x] python
- [ ] python-apt 
- [ ] libapt-pkg
- [ ] python-aptdaemon 
- [ ] python-aptdaemon.gtk3widgets
- [ ] python-dbus
- [ ] python-debtagshw
- [ ] python-defer
- [ ] python-gi 
- [ ] python-gi-cairo
- [ ] python-xapian
- [ ] Xapian search engine interface for Python
- [ ] python-xdg
- [ ] software-center-aptdaemon-plugins
- [ ] ubuntu-sso-client
- [ ] apt-xapian-index (>= 0.38ubuntu1)
- [ ] lsb-release
- [ ] software-properties-gtk
- [ ] update-notifier
- [ ] xz-utils
**_are needed_**...

**Comment by skiman6010** [comment]
So... you want to install deb packages on Chromebooks using Chromebrew to install the Software Center? Do you see how that could be a problem?

**Comment by JL2210** [comment]
I had a lot of trouble building `apt` a while back. I quit before I could get it working.

**Comment by JL2210** [comment]
No way. That's a dpkg-compatible package manager. Not apt code.

**Comment by JL2210** [comment]
The apt code is long gone.

**Comment by Ewpratten** [comment]
Just a side note, 
I have been installing debs on my chromebook for a long time. All that has to be done is the following:

```
ar x <package>.deb
tar -xvf data.tar.xz
```
 
Then copy the extracted files to their respective locations in /usr/local/

Not the perfect solution, but It works most of the time for .deb files, and may help here.

**Comment by sajjaadf** [comment]
Cool

**Comment by sajjaadf** [comment]
That can help thestore

**Comment by JL2210** [comment]
While it is true about not being able to uninstall, the packages don't install "a bunch of Debian-specific files". One serious issue that we might have is that Debian uses `<prefix>/lib/<arch>-linux-gnu` as their libdir instead of `<prefix>/lib<suffix>`. If we want a "software center", we can write a C or C++ program that interacts with Chromebrew and uses the icons from the 'homepage' variable.

**Comment by JL2210** [comment]
@blu?

**Comment by uberhacker** [comment]
@JL2210:  With simple programs that may be true but with more complex installs, you will definitely see more _"Debian-specific files"_.  There are also subtle differences like what you just described.  IOW, you can't just blindly install .deb packages and expect them to work without tweaking.

**Comment by JL2210** [comment]
What does IOW mean?

**Comment by JL2210** [comment]
> If we want a "software center", we can write a C or C++ program that interacts with Chromebrew and uses the icons from the 'homepage' variable.

**Comment by uberhacker** [comment]
In other words

**Comment by JL2210** [comment]
oh.

**Comment by blu** [comment]
Even though individual packages could be used the way @Ewpratten mentions, generally it's a low-success-probability thing. That said, Gentoo packages could have better chances : )

**Comment by uberhacker** [comment]
@blu: You are correct.  Even Slackware packages would probably work better than Debian.

**Comment by JL2210** [comment]
@blu, I was hoping you could write a C or C++ program that interacts with Chromebrew and uses images of webpages from the 'homepage' variable as icons, as a makeshift "software center". I think emerge would be a good goal to achieve, though. I may try to package it.
