### ISSUE TITLE
Install Chromebrew to a USB

### ISSUE THREAD

**Issue by codekrafter** [skycocker/chromebrew#2955]
I am trying to install chromebrew to a USB drive, but there are the noexec and nodev flags. I have tried to remount it, but then the untar of ruby gives errors when creating the symlinks (`tar: usr/local/lib64/libruby.so: Cannot create symlink to ‘libruby.so.2.5.1’: Operation not permitted`).

Any help would be appreciated!

**Comment by codekrafter** [comment]
I can test it tomorrow.

**Comment by codekrafter** [comment]
Turns out chromebrew does not have a binary for mkfs.ext4 I can download, so I have to wait a few hours until I have format it on my linux machine.

**Comment by JL2210** [comment]
@codekrafter Try running `sudo mkfs.ext4 <device>`. You are right about Chromebrew not having the binary. The stock Chrome OS system has it in `/usr/sbin/mkfs.ext4`.

**Comment by codekrafter** [comment]
Mine is at /sbin/mkfs.ext4. I was able to install it but it will not run because ruby is missing libssp.

**Comment by uberhacker** [comment]
@codekrafter: The libssp library is in gcc, not ruby.  It sounds to me like gcc is not executable.  Can you find it via `which gcc`?

**Comment by codekrafter** [comment]
It cannot find it. Where does chromebrew install gcc and other stuff when a custom $CREW_PREFIX is used?

**Comment by uberhacker** [comment]
Chromebrew should install gcc in `#{CREW_PREFIX}/bin` (or a symlink to the gcc specific directory).  Maybe you need to add `export PATH="#{CREW_PREFIX}/bin:$PATH"` in your `~/.bashrc`?  Of course, replace `#{CREW_PREFIX}` with the correct directory.

**Comment by codekrafter** [comment]
For my install ${CREW_PREFIX}/bin is a symlink to ${CREW_PREFIX}/lib/crew/crew, which is the crew exectuable.

**Comment by JL2210** [comment]
@codekrafter That's not the proper layout. There should be a directory, `#{CREW_PREFIX}/bin/`, that has a symlink named `crew` in it that points to `#{CREW_PREFIX}/lib/crew/crew`.
To ease installation, you may consider temporarily bind-mounting your flash drive to `/usr/local`:
```
sudo mount -o bind <Flash Drive Mount Point> /usr/local
```
When replacing `<Flash Drive Mount Point>` with your flash drive's mount point.

**Comment by codekrafter** [comment]
I reinstalled it, and it was able to successfully install the essentials (All I really needed was Git). It is saying it cannot find `/usr/local/etc/crew/device.json`

**Comment by JL2210** [comment]
Try replacing `/usr/local` with the directory you installed Chromebrew in in the file
`<install_directory>/lib/crew/lib/const.rb`.

**Comment by codekrafter** [comment]
It works! Thank you
