### ISSUE TITLE
Non-working Chromebrew installation despite install.sh saying it was successful

### ISSUE THREAD

**Issue by farmerbb** [skycocker/chromebrew#2959]
## Description
Attempting to install Chromebrew by running the below shell command results in a non-functional Chromebrew install.
Looking at the contents of /usr/local/bin I can see that the git, ruby, and crew binaries are installed, but /usr/local/bin is not set in my path and trying to execute /usr/local/bin/crew manually (even after manually adding /usr/local/bin to my path) produces an error:
```
Traceback (most recent call last):
        1: from /usr/local/bin/crew:2:in `<main>'
/usr/local/bin/crew:2:in `require_relative': cannot load such file -- /usr/local/lib/crew/lib/color (LoadError)
```

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
Downloading ruby...

######################################################################## 100.0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Verifying ruby...
ruby-2.5.1-chromeos-x86_64.tar.xz: OK
Extracting ruby (this may take a while)...
Installing ruby (this may take a while)...
tar: ./home: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
tar: ./usr: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Updating version number of existing ruby information in device.json...
Downloading libiconv...

######################################################################## 100.0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Verifying libiconv...
libiconv-1.15-chromeos-x86_64.tar.xz: OK
Extracting libiconv (this may take a while)...
Installing libiconv (this may take a while)...
tar: ./home: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
tar: ./usr: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Updating version number of existing libiconv information in device.json...
Downloading git...

######################################################################## 100.0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Verifying git...
git-2.19.0-chromeos-x86_64.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
tar: ./home: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
tar: ./usr: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Updating version number of existing git information in device.json...
Downloading libssh2...

######################################################################## 100.0%
Verifying libssh2...
libssh2-1.8.0-chromeos-x86_64.tar.xz: OK
Extracting libssh2 (this may take a while)...
Installing libssh2 (this may take a while)...
tar: ./home: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
tar: ./usr: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Updating version number of existing libssh2 information in device.json...
#=#=#                                                                         
##O#- #                                                                       

######################################################################## 100.0%
#=#=#                                                                         

###################################                                       49.7%
######################################################################## 100.0%
#=#=#                                                                         

######################################################################## 100.0%
bash: line 191: git: command not found
bash: line 192: git: command not found
bash: line 193: git: command not found
bash: line 194: .git/info/sparse-checkout: No such file or directory
bash: line 195: .git/info/sparse-checkout: No such file or directory
bash: line 196: .git/info/sparse-checkout: No such file or directory
bash: line 197: git: command not found
bash: line 198: git: command not found
bash: line 199: crew: command not found

To set the default PAGER environment variable to be able to use less:
echo "export PAGER=/usr/local/bin/less" >> ~/.bashrc && . ~/.bashrc

Alternatively, you could use most.  Why settle for less, right?
echo "export PAGER=/usr/local/bin/most" >> ~/.bashrc && . ~/.bashrc

Chromebrew installed successfully and package lists updated.

```

## Versions and system information
chromebrew: `crew --version`
I cannot get crew to run, so obtaining the version is impossible, but the install.sh script was executed as of revision `e194c3ce287a787c6af27a62e369be40d60f3318`.

ChromeOS: `cat /etc/lsb-release`
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5133027
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=81
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R70-11021.81.0
CHROMEOS_RELEASE_BUILD_NUMBER=11021
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=70
CHROMEOS_RELEASE_DESCRIPTION=11021.81.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11021.81.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11021.81.0
```

Model: Samsung Chromebook Pro

Architecture: `uname -m`
`x86_64`

## Addtional information
This is my first time attempting to install Chromebrew on my machine, so I really, _really_ hope this isn't user error on my part...

**Comment by uberhacker** [comment]
@farmerbb: Sorry you had a bad first experience.  Thank you for submitting a new issue with all the requested info added.  Wish others that submit issues would be as complete as you. :)  From the looks of it, you appear to have an issue with curl.
```
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```
By chance, what is the output of `which curl`?  If not `/usr/bin/curl`, you might consider a powerwash and restore the system back to the factory settings.  My guess is something is corrupt.  It appears you have a good Internet connection so that doesn't look like an issue.

**Comment by farmerbb** [comment]
Thanks.  `which curl` outputs `/usr/bin/curl`, and after a quick Google search it looks like that particular error occurs when curl tries to redownload an already completed file.  If I remove the downloaded *.tar.xz files from /usr/local/tmp/crew and then rerun the installer, I get the exact same output minus the curl errors.

**Comment by JL2210** [comment]
@uberhacker Sorry about that. I forgot that it errors if `./home` is not present.

**Comment by farmerbb** [comment]
@uberhacker So I tried installing Chromebrew again, and it still fails to install due to the `git` and `crew` commands not being found.  I was able to fix the install myself by adding `export PATH="$PATH:/usr/local/bin` to my `.bashrc` so that `git` and `crew` would resolve correctly.  Although, I'm still getting errors when actually trying to run certain packages due to it not being able to find shared libaries (likely more PATH issues)

For example, when trying to launch `zsh`:

```
zsh: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory
```

So it looks like the issues I'm having boil down to an incorrect PATH configuration. On my Chromebook the default `$PATH` is set to `/bin:/usr/bin`.   So either:
* The default PATH configuration on Chrome OS has changed recently, assuming /usr/local/bin was included there before
* Somehow I've changed my PATH from the default, inadvertently 
* Chromebrew's installer fails to set /usr/local/bin and any other paths to shared libraries correctly

**Comment by uberhacker** [comment]
@farmerbb: That is definitely an unusual situation.  What is the output of `echo $LD_LIBRARY_PATH`?  If you don't have `/usr/local/lib64`, that could be the problem with the missing library files.  Do you have anything in `~/.bashrc` or the shell that you are using that sets these environment variable paths?

**Comment by farmerbb** [comment]
`echo $LD_LIBRARY_PATH` returns nothing, and adding `export LD_LIBRARY_PATH="/usr/local/lib64"` to my .bashrc seems to fix the ability to run programs.

Just to confirm, these variables are supposed to be set by default on a stock Chrome OS system with developer mode enabled?  If so, then I'm wondering if there's just something wrong with the environment on my specific machine (I do use crouton, etc which I'm guessing might be messing with these variables)

**Comment by JL2210** [comment]
Ahem. Wiki page:
```
Q: Crouton fails to install after installing the dpkg package. What do I do?

A: Installing Crouton alongside Chromebrew can cause many bugs, including Crouton trying to use the Chromebrew-provided dpkg, which will not work. You can remove the dpkg package and install Crouton, however doing so is unsupported. Proceed at your own risk. For more information, please see #2794.
```
Installing Chromebrew and Crouton alongside each other is * unsupported *.

**Comment by JL2210** [comment]
However, the default PATH is `/usr/local/bin:/usr/bin:/bin:/opt/bin` and the default LD_LIBRARY_PATH is `/usr/local/lib64`. Make sure ***not*** to install Chromebrew inside Crouton.

**Comment by farmerbb** [comment]
...the crouton thing was purely speculation on my part, and there's nothing in the readme that blatantly states "Do not install this alongside crouton".

Nevertheless, Chromebrew seems to be working with my environment variables set up correctly, so let's just close this ¯\_(ツ)_/¯

**Comment by uberhacker** [comment]
@farmerbb: Glad you were able to make it work.  You are correct about the message regarding the conflict with Crouton and Chromebrew not being clearly visible to project newcomers.  Maybe we can add something in the README.md?  That wiki article only mentions an issue with dpkg, not a general incompatibility issue.

**Comment by farmerbb** [comment]
That sounds good to me. I imagine the number of people interested in both Chromebrew and crouton would be high enough to warrant adding that :)

**Comment by JL2210** [comment]
@farmerbb Editing FAQ now.

**Comment by jedi-ux** [comment]
![Screenshot 2021-05-05 08 14 39](https://user-images.githubusercontent.com/82736855/117103233-3878fa80-ad7a-11eb-873e-cfdbab7e8f3b.png)
![Screenshot 2021-05-05 08 03 50](https://user-images.githubusercontent.com/82736855/117103234-39119100-ad7a-11eb-8dfe-168fe75053fe.png)
![Screenshot 2021-05-05 08 02 01](https://user-images.githubusercontent.com/82736855/117103235-39aa2780-ad7a-11eb-9164-3e365d01fa36.png)
![Screenshot 2021-05-05 07 57 50](https://user-images.githubusercontent.com/82736855/117103237-3a42be00-ad7a-11eb-8793-e165822d69e7.png)

**Comment by jedi-ux** [comment]
I dont know where these repoś come from, are they standard?


![Screenshot 2021-05-05 08 31 53](https://user-images.githubusercontent.com/82736855/117104503-8b53b180-ad7c-11eb-8c02-b73f47ae758d.png)
![Screenshot 2021-05-05 08 14 39](https://user-images.githubusercontent.com/82736855/117104506-8c84de80-ad7c-11eb-989e-0870cbd81952.png)
![Screenshot 2021-05-05 08 03 50](https://user-images.githubusercontent.com/82736855/117104508-8c84de80-ad7c-11eb-9e5c-9c798dd9df86.png)
![Screenshot 2021-05-05 08 02 01](https://user-images.githubusercontent.com/82736855/117104510-8d1d7500-ad7c-11eb-9430-b21095d86d83.png)
![Screenshot 2021-05-05 07 57 50](https://user-images.githubusercontent.com/82736855/117104511-8d1d7500-ad7c-11eb-810f-d21c028004d9.png)

**Comment by uberhacker** [comment]
@jedi-ux: Can you please open a new issue with the output of `cat /etc/lsb-release`, `arch` and Chromebook make and model?
