### ISSUE TITLE
sommelier failed to install: `git clone https://chromium.googlesource.com/chromiumos/containers/sommelier` exited with 128

### ISSUE THREAD

**Issue by ctuxboy** [skycocker/chromebrew#2971]
When instaling a package, then it shows this error:
**sommelier failed to install: `git clone https://chromium.googlesource.com/chromiumos/containers/sommelier` exited with 128**

```
chronos@localhost / $ crew install code
code: Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS.
https://code.visualstudio.com/
version 1.25.1
The following packages also need to be installed: 
sommelier 
Do you agree? [Y/n] y
Proceeding...
sommelier: Sommelier works by redirecting X11 and Wayland programs to the built-in ChromeOS wayland server.
https://chromium.googlesource.com/chromiumos/containers/sommelier
version 1382ce084cc
No precompiled binary available for your platform, downloading source...
Archive downloaded
Unpacking archive, this may take awhile...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Cloning into 'sommelier'...
remote: Total 514 (delta 295), reused 514 (delta 295)
Receiving objects: 100% (514/514), 748.35 KiB | 4.20 MiB/s, done.
Resolving deltas: 100% (295/295), done.
HEAD is now at 1382ce0 Move some defines into Makefile instead of .c file.
sommelier failed to install: `make V=0 -j4 PREFIX=/usr/local SYSCONFDIR=/usr/local/etc` exited with 127
```
My Chromebook: Acer R13

**Comment by uberhacker** [comment]
@ctuxboy: Glad you were finally able to install Chromebrew.  Looks like we need some pre-built binaries for sommelier.  I'll try to submit a PR later today.

**Comment by ctuxboy** [comment]
Hi @uberhacker,
Thanks a lot man!

**Comment by JL2210** [comment]
@ctuxboy From what I can tell, you might not have `make` installed. To install make, just run this command: `crew install make`

**Comment by nosarthur** [comment]
I have the same error when upgrading sommerlier. When I run `crew update`

`sommelier could be updated from 1382ce084 to 1382ce084cc`

But running `crew upgrade sommelier` gives rise to 

```
/usr/local/bin/ld: cannot find /usr/local/lib64/libm.so.6
/usr/local/bin/ld: cannot find /usr/local/lib64/libmvec.so.1
collect2: error: ld returned 1 exit status
make: *** [Makefile:33: sommelier] Error 1
rm xdg-shell-unstable-v6-protocol.c gtk-shell-protocol.c viewporter-protocol.c keyboard-extension-unstable-v1-protocol.c aura-shell-protocol.c drm-protocol.c linux-dmabuf-unstable-v1-protocol.c
sommelier failed to install: `make V=0 -j4 PREFIX=/usr/local SYSCONFDIR=/usr/local/etc` exited with 2
```

Then I notice the links to these shared objects are broken. For example, `libm.so.6 -> libm-2.23.so -> /lib64/libm-2.23.so`, but I actually have `/lib64/libm-2.27.so` . I can manually fix these soft links. Is there any better way to do it? What is the cause of it? Is it due to chrome os update?

**Comment by nosarthur** [comment]
I pointed these so links in `/usr/local/lib/` to the new ones in `/lib64`. It seems to run ok so far

**Comment by JL2210** [comment]
It will, however is unsupported. When 72 is stable, [this branch](https://github.com/uberhacker/chromebrew/tree/update-glibc-2.23-2.27) will be pushed to `master`.

**Comment by nosarthur** [comment]
I see. Thanks @JL2210

**Comment by JL2210** [comment]
You can copy all your data to a flash drive with this command: `cp -a ~/ '/media/removable/<USB Drive>/home' && cp -a /usr/local /media/removable/<USB Drive>`

**Comment by ctuxboy** [comment]
Hi guys,
Sorry about my late answer, very busy now.
Try it in the next days.
Wist you all a Merry Christmas!!!!

**Comment by JL2210** [comment]
@ctuxboy Glad I could help. Can you close this?

**Comment by ctuxboy** [comment]
Closed 😊
