### ISSUE TITLE
Directories and files with spaces are not reported by `crew files` without errors

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2972]
Example: `crew files powerline_fonts` returns a bunch of messages like the following:
```
du: cannot access ‘Italic’: No such file or directory
```
These files/directories with spaces do display in the output but the errors make it more difficult to view.

**Comment by JL2210** [comment]
Could we escape spaces with backslashes?

**Comment by JL2210** [comment]
I think this is an issue with `du` thinking that every space in a file's name is specifying another file to take into account the space of.

**Comment by cstrouse** [comment]
Changing it to something like this partially solves the problem but some files and links don't report properly then.
```
size = `xargs -Ifile du -ch file <$(cat #{filelist}) | tail -1 | cut -f 1`
```
