### ISSUE TITLE
I am willing to make a Forum

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2987]
Like a reddit subreddit 
or a website with a request area
or even another GitHub repo for suggestions

**Comment by JL2210** [comment]
Chromebrew already has a Reddit.

**Comment by sajjaadf** [comment]
What about a repo for ideas?

**Comment by sajjaadf** [comment]
https://github.com/sajjaadf/Chromebrew_Ideas

**Comment by sajjaadf** [comment]
http://chromebrew.freeforums.net

**Comment by sajjaadf** [comment]
or

**Comment by sajjaadf** [comment]
https://chromebrew.createaforum.com

**Comment by sajjaadf** [comment]
or
