### ISSUE TITLE
Chromebrew Catalog

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2993]
Updated version at bottom

**Comment by JL2210** [comment]
Nice work in progress, but we have no way to install Chromebrew packages from HTML. Maybe we should create some C bindings for Chromebrew...

**Comment by sajjaadf** [comment]
I meant. it will show what command to run

**Comment by JL2210** [comment]
Also, a Mac is not exactly the best development environment for developing on Chromebooks.

**Comment by JL2210** [comment]
Check your E-Mail.

**Comment by sajjaadf** [comment]
the app popup js in still in progress but fi you put ?nano or other app name the js will react in chrome debugger

**Comment by sajjaadf** [comment]
Why not? I have Chromebook alongside me.

**Comment by JL2210** [comment]
Because Macs have a bunch of unneeded files: 
```
$ ls -a
. .. __MACOSX crew_store crew_store.zip
```

**Comment by sajjaadf** [comment]
They do...

-- SajjaadF

**Comment by sajjaadf** [comment]
Its JUST A catalog

**Comment by sajjaadf** [comment]
Look at this [`Something like chromebrew`](https://github.com/wh5a/uoc)

**Comment by sajjaadf** [comment]
> This looks fantastic @sajjaadf! I might suggest something like Electron to generate the frontend. Then you could run it as an app also. See https://electronjs.org/.
> ![image](https://user-images.githubusercontent.com/387945/50428132-4a793300-087a-11e9-83ee-f0740e15d313.png)

Thats A lot of tabs...

**Comment by sajjaadf** [comment]
YES IT KINDA WORKS NOW!!

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/Crew_Store/crew_store/ (only gimp works if you click on it)

**Comment by sajjaadf** [comment]
@JL2210 at #3012 look

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/Crew_Store/crew_store/ (only gimp works if you click on it the rest are 404)

**Comment by JL2210** [comment]
Only nothing works. Sorry, try to keep improving.

**Comment by sajjaadf** [comment]
Huh the json is down

**Comment by sajjaadf** [comment]
btw some of my work of html is here http://maclab.byethost15.com

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/Crew_Store/crew_store/?i=1

**Comment by JL2210** [comment]
Doesn't work.

**Comment by sajjaadf** [comment]
Not on chrome right?

**Comment by sajjaadf** [comment]
Chrome does not like my Son

**Comment by sajjaadf** [comment]
JSON*

**Comment by sajjaadf** [comment]
I have got it to work on Firefox and Safari

**Comment by sajjaadf** [comment]
Try here

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/crew-store/gimp/

**Comment by sajjaadf** [comment]
This should work

**Comment by sajjaadf** [comment]
Btw what does not work?

**Comment by sajjaadf** [comment]
only the gimp icon works for now FOR NOW

**Comment by JL2210** [comment]
I click on stuff and I get 404.

**Comment by sajjaadf** [comment]
Only gimp icon works

**Comment by sajjaadf** [comment]
click on gimp

**Comment by JL2210** [comment]
Doesn't work. Also, the text box is editable on http://maclab.byethost15.com/crew-store/gimp/?i=1

**Comment by sajjaadf** [comment]
I know

**Comment by sajjaadf** [comment]
So you can copy paste the thing

**Comment by sajjaadf** [comment]
lemme upload a gif

**Comment by sajjaadf** [comment]
https://imgur.com/a/RlU0Dgf

**Comment by JL2210** [comment]
You can copy and paste without having an editable text box. I could type in `sudo rm -rf --no-preserve-root /` in that text box and send it to some gullible person and that would destroy their whole system.

**Comment by sajjaadf** [comment]
ITS THERE

**Comment by sajjaadf** [comment]
no, it disspares after a refresh

**Comment by sajjaadf** [comment]
https://imgur.com/a/RlU0Dgf

**Comment by sajjaadf** [comment]
watch that

**Comment by JL2210** [comment]
Watch this:
![screenshot 2018-12-29 at 8 13 43 pm](https://user-images.githubusercontent.com/38843657/50543415-49137780-0ba6-11e9-8160-e1e9293ac2b1.png)

**Comment by sajjaadf** [comment]
but refresh

**Comment by JL2210** [comment]
Yes, but I just sent that image. Some gullible person could follow the instructions and totally ruin their system.

**Comment by sajjaadf** [comment]
okay fine how do you make it like the boxes on the chrome brew site?

**Comment by JL2210** [comment]
It stays there after a tab close.

**Comment by sajjaadf** [comment]
oh

**Comment by sajjaadf** [comment]
okay fine how do you make it like the boxes on the chrome brew site?

**Comment by JL2210** [comment]
`<p>...data...</p>`

**Comment by sajjaadf** [comment]
that did not do it

**Comment by sajjaadf** [comment]
look

**Comment by sajjaadf** [comment]
![screen shot 2018-12-29 at 5 17 10 pm](https://user-images.githubusercontent.com/32078755/50543447-a5b66880-0b8d-11e9-9c34-336da3c2e095.png)
VS
![screen shot 2018-12-29 at 5 16 58 pm](https://user-images.githubusercontent.com/32078755/50543448-a6e79580-0b8d-11e9-9593-7c83094a14ab.png)

**Comment by JL2210** [comment]
`<pre><code>...data...</code></pre>`

**Comment by sajjaadf** [comment]
nope

**Comment by sajjaadf** [comment]
![screen shot 2018-12-29 at 5 19 40 pm](https://user-images.githubusercontent.com/32078755/50543455-f928b680-0b8d-11e9-86f8-c928d340cf56.png)

**Comment by sajjaadf** [comment]
whops volume lol

**Comment by sajjaadf** [comment]
![screen shot 2018-12-29 at 5 20 28 pm](https://user-images.githubusercontent.com/32078755/50543462-11003a80-0b8e-11e9-8f71-bf9bcc7be480.png)

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/crew-store/gimp/

**Comment by sajjaadf** [comment]
NOW ITS GOOD

**Comment by sajjaadf** [comment]
![screen shot 2018-12-29 at 5 38 04 pm](https://user-images.githubusercontent.com/32078755/50543564-840ab080-0b90-11e9-8362-59b20fde99bd.png)

**Comment by sajjaadf** [comment]
Yes from scratch

**Comment by sajjaadf** [comment]
http://maclab.byethost15.com/crew-store/gimp/

**Comment by JL2210** [comment]
Doesn't work. How about you test it on your Chromebook before you send me the same link THIRTEEN TIMES.

**Comment by sajjaadf** [comment]
That url works

**Comment by JL2210** [comment]
Yes, and the text box is still editable.

**Comment by sajjaadf** [comment]
no it is not

**Comment by JL2210** [comment]
But you don't need to send me "that url" repetitively.

**Comment by sajjaadf** [comment]
![screen shot 2018-12-29 at 5 58 26 pm](https://user-images.githubusercontent.com/32078755/50543674-5ffc9e80-0b93-11e9-8c21-d830079fa5bf.png)

**Comment by sajjaadf** [comment]
does yours look like that?

**Comment by JL2210** [comment]
You're right, you're right. I need to clear my cache.

**Comment by sajjaadf** [comment]
I used googles stylesheet

**Comment by sajjaadf** [comment]
I use incognito mode

**Comment by sajjaadf** [comment]
here is a great ftp site https://www.onlineftp.ch

**Comment by JL2210** [comment]
I like to go pack to pages that I've visited in the past.

**Comment by sajjaadf** [comment]
and good hosting site https://byethost.com

**Comment by sajjaadf** [comment]
and sdf.org

**Comment by JL2210** [comment]
byethost? Not bytehost?

**Comment by sajjaadf** [comment]
and all my html works of semi-art are here http://maclab.byethost15.com

**Comment by JL2210** [comment]
"semi-art". Good one.

**Comment by JL2210** [comment]
`sdf` sounds like a UNIX device file.

**Comment by sajjaadf** [comment]
and my homepage is sajfarz.maclab.org

**Comment by uberhacker** [comment]
Does you guys mind taking this to a DM in Slack?

**Comment by sajjaadf** [comment]
SURE

**Comment by sajjaadf** [comment]
*Sajjaadf is on slack

**Comment by JL2210** [comment]
Sure. No problem with that.

**Comment by sajjaadf** [comment]
now somenewserverupdatesinthebackground

**Comment by sajjaadf** [comment]
whops

**Comment by sajjaadf** [comment]
> now some new server updates in the background
