### ISSUE TITLE
Proposal: Add icons to packages

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#2994]
Add something like `icon 'http://domain.tld/path/to/icon.png'` or `icon 'file:///path/to/icon.png'` if the file is available locally below the `description '..`.  These icons should be no bigger than 32 x 32 pixels and can be included in the new store app when available.

**Comment by JL2210** [comment]
Sounds good. I don't think this "app store" will get anywhere without a language programmer, though. HTML can't access the command line.

**Comment by sajjaadf** [comment]
The "App Store" would be a catalog. when said user clicks on icon, a popup says "Crew install appname" + size of app + website and some screenshots

**Comment by JL2210** [comment]
OK. I could see that, however how would this help?

**Comment by sajjaadf** [comment]
Instead of them browsing on GitHub, they launch this app, and the GetJSON is updated from a external server, in this case berri-co.me/js.json

**Comment by sajjaadf** [comment]
aka


`.getJSON('http://berri-co.me/js.json', function(json){
	jQuery.each(json, function(i, webapp) {
		var summary = 0;
		for(var a = 1; a < 6; a++) {
			summary = summary + a*webapp[a + 'stars'];
		}
		
		var average = precisionRound(summary / webapp.stars, 1);
		
		$('#apps #list').append(
			'<a href="?' + i + '/"><div class="webapp top">\
					<img src="' + webapp.icon  + '" alt="' + webapp.name + '" style="background-color:  ' + webapp.themecolor +'"/><div>\
						<h4>' + webapp.name + '</h4>\
						<div class="category">' + webapp.category + '</div>\
						<div class="middle"><span class="rate">' + average + '</span><i class="material-icons">star</i></div>\
					</div>\
			 </div></a>');
	`

**Comment by JL2210** [comment]
Use triple backticks: "```"

**Comment by sajjaadf** [comment]
ahhh thanks

**Comment by JL2210** [comment]
You could download the packages from `https://github.com/skycocker/chromebrew/raw/master/packages/*.rb`

**Comment by uberhacker** [comment]
I think you are failing to release what a potential maintenance nightmare the catalog task will become if it isn't tied into the Chromebrew project to get the information.

**Comment by JL2210** [comment]
You have to have a line between the backticks:
`
```
<JavaScript here>
```
`

**Comment by sajjaadf** [comment]
That Berri-co.me thing is just for the demo

**Comment by sajjaadf** [comment]
the js can be modified to be in the chrome brew repo and when people put a pull request they must update that too

**Comment by sajjaadf** [comment]
and the catalog is for Gui and apps like nano with shell Gui

**Comment by JL2210** [comment]
So:
"` ` `
<JavaScript>
` ` `"
Remove the spaces between the backticks in this example. I couldn't get it to format right for Github.

**Comment by JL2210** [comment]
@sajjaadf https://github.com/skycocker/chromebrew/issues/2994?%27%20+%20i%20+%20%27/#issuecomment-449888853 is not going to happen.

**Comment by uberhacker** [comment]
I fixed it. :)

**Comment by sajjaadf** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by JL2210** [comment]
Bingo. That's what I use.

**Comment by sajjaadf** [comment]
I was too lazy to go there lol its bookmarked

**Comment by JL2210** [comment]
lol?

**Comment by sajjaadf** [comment]
@uberhacker close this please
