### ISSUE TITLE
Tada (Chrome App)

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#2995]
------>
[ChromebrewStoreApp.zip](https://github.com/skycocker/chromebrew/files/2709807/ChromebrewStoreApp.zip)

**Comment by JL2210** [comment]
@sajjaadf You can put this in your former issue, #2993

**Comment by JL2210** [comment]
STOP DEVELOPING ON MACOS!

**Comment by JL2210** [comment]
Is your Chromebook even *in* Developer Mode?

**Comment by JL2210** [comment]
He can't create Chromebrew packages on MacOS. I asked him what he was doing his editing on, and he showed me this:
![image](https://user-images.githubusercontent.com/38843657/50489096-c0dd7880-09d3-11e9-80bf-2fe4b5c7a494.png)

**Comment by uberhacker** [comment]
He's not planning on creating a Chromebrew package.  He mentioned Chrome app.  There is a difference, you know.

**Comment by JL2210** [comment]
I was telling him how to create a package, and he was doing it on a Mac.

**Comment by uberhacker** [comment]
Does he even own a Chromebook? :1st_place_medal:

**Comment by JL2210** [comment]
And the Chrome apps he creates have two issues:
1. They don't even install properly.
2. They have a random folder called __MACOSX with random junk in it.

**Comment by JL2210** [comment]
I doubt it.

**Comment by sajjaadf** [comment]
I do have a chromebook

**Comment by sajjaadf** [comment]
I am just used to using vscode on Mac

**Comment by sajjaadf** [comment]
and Xit is a GitHub git viewer

**Comment by sajjaadf** [comment]
and I did not have time to test the chrome app

**Comment by JL2210** [comment]
All right. Do you see this screen when starting up your Chromebook?
!(image.png)[https://www.howtogeek.com/wp-content/uploads/2015/02/ximg_54f13e9a6f60f.jpg.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.9D9nY51pCC.jpg]
