### ISSUE TITLE
Filezilla stopped working

### ISSUE THREAD

**Issue by caglewebsolutions** [skycocker/chromebrew#2999]
## Description
I had Filezilla working previously (it was on the beta and development channels at the time). Now, I'm on the stable channel (where I should be with Chromebrew) and Filezilla doesn't load. 

If you executed a specific command:
```shell
filezilla
```

Output:
```shell
Reading locale option from /home/chronos/user/.config/filezilla/filezilla.xml
GLib-GIO-Message: 20:51:09.338: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Floating point exception (core dumped)
```

## Versions and system information
chromebrew: `1.0.6`

ChromeOS: `CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0`

Model: Dell Chromebook 11 3120

Architecture: `x86_64`

**Comment by JL2210** [comment]
@caglewebsolutions Try reinstalling Chromebrew. If you compiled ANY apps from source on version 72+, it may very well be affecting your experience now.

**Comment by caglewebsolutions** [comment]
Did powerwashing not get rid of apps I might have installed? I know it compiled Nano when I installed it.

**Comment by JL2210** [comment]
Oh. Forgot about that. Sorry.

**Comment by JL2210** [comment]
Just try reinstalling. I don't know what your issue might be. Try `crew install -S filezilla` and report back.

**Comment by caglewebsolutions** [comment]
Well reinstalling Filezilla was one of the first things I thought of and I tried that. Will try it this way though.

**Comment by JL2210** [comment]
`-S` is a recursive build from source option. I recommended it myself. You may also try to remove all the dependencies as far back as you wish.

**Comment by caglewebsolutions** [comment]
OK.

**Comment by caglewebsolutions** [comment]
Ah, this seems to be taking forever to do. Longer than it took when I initially installed Filezilla, I believe.

**Comment by caglewebsolutions** [comment]
(i) filezilla: FileZilla Client is a free FTP solution.
https://filezilla-project.org/
version 1.6.3

The following packages also need to be installed: 
ed bc tcl expect dejagnu help2man 
Do you agree? [Y/n] Proceeding...
ed: GNU ed is a line-oriented text editor.
http://www.gnu.org/software/ed/ed.html
version 1.14.2-1
Downloading source...
################################################################################################################################################################# 100.0%
Checksum mismatch. :/ Try again.

**Comment by caglewebsolutions** [comment]
Actually I'm retrying it and making more progress now.

**Comment by caglewebsolutions** [comment]
Ah Curl timed out while trying to download TCL

**Comment by caglewebsolutions** [comment]
Tried again, but I'm still timing out on Curl. Anyway I've got to head home soon and I'll try it from there.

**Comment by JL2210** [comment]
OK. I'll try to have Code pushed by then. Meanwhile, join (Slack)[https://join.slack.com/t/chromebrew/shared_invite/enQtNDA2MTQ5ODQ3NDc2LTA0ZmJlMGFmNmZhOTYwNDE3ZDY0NDA0MWI0OTE3MzJkYTQxN2UxMWQ1YTEzOWFmNTliMGM4NDZjYzY2NjczZGE].

**Comment by caglewebsolutions** [comment]
Well unfortunately after installing using -S, I'm still getting

Reading locale option from /home/chronos/user/.config/filezilla/filezilla.xml
GLib-GIO-Message: 23:56:57.881: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Floating point exception (core dumped)

**Comment by JL2210** [comment]
'crew remove glib gobject_introspection && crew install -S glib
gobject_introspection'

**Comment by caglewebsolutions** [comment]
ok. Will try that.

**Comment by caglewebsolutions** [comment]
Still getting core dumped.

**Comment by JL2210** [comment]
@caglewebsolutions See #3000 for an update to the `code` package. Includes ARM support.

**Comment by caglewebsolutions** [comment]
OK thanks. I'm on an Intel CPU here, but good for others to know it includes ARM support.

**Comment by caglewebsolutions** [comment]
I'm just curious...should there be an actual filezilla.xml at /home/chronos/user/.config/filezilla/filezilla.xml ? Because there's not. And when I try to create it, it complains that it's a read only filesystem and doesn't let me do it.

Interestingly, sudo filezilla gives me

Reading locale option from /root/.config/filezilla/filezilla.xml
No protocol specified
Unable to init server: Could not connect: Connection refused
01:51:37: Error: Unable to initialize GTK+, is DISPLAY set properly?

**Comment by caglewebsolutions** [comment]
Well I don't know how much longer I'm going to focus on this, myself. Sublime Text and the SFTP plugin is working for me. So I might not really need Filezilla or Code. It would be nice to see those working, though.

**Comment by caglewebsolutions** [comment]
So I did a powerwash because I was having problems with SFTP on Sublime Text, and I wanted to give Filezilla another shot.

I re-installed Chromebrew, and the first thing I tried to install was Filezilla. But, it looks like I can't. I get to this...

patch: Patch takes a patch file containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions.
http://savannah.gnu.org/projects/patch/
version 2.7.6
Downloading source...
################################################################################################################################################ 100.0%
Archive downloaded
Unpacking archive, this may take awhile...
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether make supports nested variables... (cached) no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/patch-2.7.6.tar.xz.dir/patch-2.7.6':
configure: error: C compiler cannot create executables
See `config.log' for more details
patch failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64` exited with 77

**Comment by caglewebsolutions** [comment]
Also earlier on...

Unpacking archive, this may take awhile...
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
sh: 1: aclocal: not found
autoreconf: aclocal failed with exit status: 127

**Comment by caglewebsolutions** [comment]
Well...I'm having too many problems with Chromebrew it seems. Crouton worked well for me, and I think I'm going to go back to that.

**Comment by JL2210** [comment]
@caglewebsolutions You can go ahead and remove the `-S` option when installing Filezilla. If you're really set on it, sorry to see you go.

**Comment by JL2210** [comment]
Just keep in mind that GUI is in its beta stage right now.

**Comment by caglewebsolutions** [comment]
Understood. I will probably try again at some point when things are a bit more developed. :) I do like the Chromebrew concept. :) I think I will put Chromium OS on an SD card or flash drive and continue to test things out, for sure.

**Comment by caglewebsolutions** [comment]
@uberhacker I haven't had a chance. I've switched back to Crouton (which I mentioned in another thread) for now and things are working fine there. I understand this is beta. When I can get a system set up to test this out, and when I have time, I will.

**Comment by sajjaadf** [comment]
@caglewebsolutions Im using crouton and chromebrew at the same time

**Comment by sajjaadf** [comment]
I installed a simple nongui chroot with sommelier and crew for sommelier for testing

**Comment by JL2210** [comment]
@sajjaadf Installing Crouton and Chromebrew together is unsupported. Use one or the other or we can't help you.

**Comment by caglewebsolutions** [comment]
Exactly. I want to set it up on a separate system so it could be supported. Yes, I totally could use both on the same system but a) my internal space on this Chromebook is very limited to begin with b) they've stated using both on the same system is unsupported. 

Because of space alone, I only want to use one or the other for regular use. I'd love to switch to Chromebrew for regular use when it's a bit more stable, unless of course my Chromebook gets official support for Linux apps. (It's planned but not officially supported yet, and doesn't work in beta or development channels yet)

**Comment by sajjaadf** [comment]
@JL2210 I know

**Comment by sajjaadf** [comment]
my Chromebook has android apps too

**Comment by sajjaadf** [comment]
all on my sd card

**Comment by caglewebsolutions** [comment]
That's nice. But some of us are interested in this solution or Crouton because our Chromebooks have yet to receive official support from Google for Linux apps. And then I'm sure there are still those who prefer Crouton or Chromebrew over Google's solution for Linux. 

It's cool if you're able to use both but at least with Chromebrew, they won't be able to help you if you have any issues. So that's at your own risk

**Comment by sajjaadf** [comment]
yup

**Comment by sajjaadf** [comment]
I know

**Comment by skiman6010** [comment]
@sajjaadf I'm not going to warn you again, stop with the spammy messages that add nothing to the conversation. One comment is enough and if you need to add more, you can always edit. Thanks in advance! :)

@caglewebsolutions I'm going to leave this open and the Code issue open for us to track the problem, but if you don't want to hear anymore about this I would recommend unsubscribing to the issue. Thanks for understanding and I hope we can get you to use `crew` again once we get the gui perfect.
