### ISSUE TITLE
[svgalib] Cannot build from source

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3011]
```
ld.bfd: cannot find -lvga
collect2: error: ld returned 1 exit status
make[1]: *** [/usr/local/tmp/crew/e698d8c11f938bb6039a1791dc54c620c228d308.tar.gz.dir/svgalib-1-e698d8c11f938bb6039a1791dc54c620c228d308/utils/Makefil$
make[1]: Leaving directory '/usr/local/tmp/crew/e698d8c11f938bb6039a1791dc54c620c228d308.tar.gz.dir/svgalib-1-e698d8c11f938bb6039a1791dc54c620c228d308$
make: *** [Makefile:305: textutils] Error 2
```
I assume this is the reason libsdl #3010 cannot build also.

**Comment by JL2210** [comment]
Just remove the `svgalib` package. Like svgalib-1 said:
> if you still use this library there's probably something wrong with you.

**Comment by uberhacker** [comment]
If I remember correctly, it was YOU who added this package and now you want me to clean up your mess?

**Comment by uberhacker** [comment]
How do you explain the error in #3010?

**Comment by JL2210** [comment]
I explain it as something going wrong with your Chromebrew installation. `svgalib` installs files before it's packaged. That's probably caused the issue. Please don't revert the `libsdl` update. I spent a long time trying to get it to work.
