### ISSUE TITLE
Package Request: xorg-xsetroot

### ISSUE THREAD

**Issue by gt945** [skycocker/chromebrew#3015]
When use sommelier to run gtk-demo. the default cursor is a cross.
In /usr/local/etc/sommelierrc, it call xsetroot to change default cursor to left_ptr.
Please add xorg-xsetroot package and add it as dependency of sommelier

**Comment by JL2210** [comment]
Can you provide a source url? I've been looking for that one for a while. Can't seem to find it.

**Comment by gt945** [comment]
@JL2210 awesome, thanks a lot

**Comment by sajjaadf** [comment]
I thought it was a chrome limitation, thanks @JL2210
