### ISSUE TITLE
FIXED It 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#3023]
@JL2210 Look AT #2993 PLEASE

**Comment by uberhacker** [comment]
@sajjaadf: It is easier just to reply at #2993 rather than opening a new issue.  This is not an alert system.  It's for unique issues.  We have enough trouble sifting through these issues as it is.

**Comment by sajjaadf** [comment]
Sorry

**Comment by sajjaadf** [comment]
Thats why I say we should make a fourm

**Comment by JL2210** [comment]
@sajjaadf, I already get notifications on #2993. Just comment there.
