### ISSUE TITLE
Fix cursor Bug 

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#3039]
so you don't get a bug for GUI apps

**Comment by uberhacker** [comment]
@sajjaadf: What bug do you notice?  When you open an issue, please enter a brief description of the issue you are experiencing or we won't be able to help with a "fix".  Screenshots would be helpful also, if needed. IOW, we need to know what you mean by a bug.

**Comment by JL2210** [comment]
@sajjaadf Can you please give us your system details? We may be able to help you if you do.

**Comment by skiman6010** [comment]
@jl2210 your hostility recently is getting to be unacceptable. Please keep it civil. We're all here to help one another. 

Thank you for understanding.

**Comment by JL2210** [comment]
@skiman6010 @sajjaadf I'm sorry. I just... get frustrated when people know something's not supported, do it anyway, and file an issue when it doesn't work. I'll try and help. @sajjaadf, what's the issue that you're having?

**Comment by uberhacker** [comment]
@JL2210: How do you even know what bug he is talking about if he hasn't described it yet? :1st_place_medal:

**Comment by JL2210** [comment]
I just asked what the issue he was having was.

**Comment by sajjaadf** [comment]
I reinstalled sommelier and it fixed itself
