### ISSUE TITLE
crew installation invalid after dev_install

### ISSUE THREAD

**Issue by finwo** [skycocker/chromebrew#304]
After some searching on google on how to install sshfs on a chromebook, I found the [dev_install command](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/install-software-on-base-images) for chromium-os, which also happened to work on chrome-os.

This will install a package manager called "emerge", which includes packages like the sshfs utility.

All fun and games, until I noticed the chromebrew installation did not work anymore. Re-installing chromebrew did the trick of getting the environment back but it might be worth adding this to the documentation.

I haven't done an in-depth search on what dev_install exactly does to corrupt chromebrew (yet).

**Comment by cstrouse** [comment]
@finwo Chromebrew and dev_install can't co-exist because of the behavior of dev_install's remove_installed_packages function. It removes everything within /usr/local/.

```bash
remove_installed_packages() {
  echo "To clean up, we will run:"
  echo "  rm -rf /usr/local/"
  echo "Any content you have stored in there will be deleted."
  if yes_or_no "Remove all installed packages now"; then
    rm -rf --one-file-system /usr/local/*
    echo "Removed all installed packages."
  else
    echo "Operation cancelled."
    exit 0
  fi
}
```

**Comment by finwo** [comment]
@cstrouse In that case, simply not installing too much through emerge & especially not removing anything would do the trick for me, as it was solely for sshfs (and support for fuse)

**Comment by cstrouse** [comment]
@finwo This was first reported in 2013 and appears to still no have no solution figured out in the Chromium OS project. You can [read the discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=255485) on their bug tracker.

**Comment by lyxell** [comment]
Closing as invalid
