### ISSUE TITLE
[sommelier] Unable to install due to dependency loop

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3048]
Waited over 5 min on a fresh install without dependencies resolved.  Finally hit Ctrl+C to interrupt.  This is likely caused by libdrm or mesa.

**Comment by JL2210** [comment]
How many lines were in the output? If there were only ~42 then you just
have to wait a while longer. Otherwise, check `tests/`.

**Comment by JL2210** [comment]
Here we go:
```
Found dependency cycle!
["alsa_plugins", "pulseaudio", "alsa_plugins"]
```

**Comment by JL2210** [comment]
That looks like it's it.

**Comment by JL2210** [comment]
I'm working on a PR with misc. fixes, so this should be easy to add.

**Comment by JL2210** [comment]
@uberhacker "Merging this is probably going to come back and bite us later but we'll deal with it then, I guess."
```
Found dependency cycle!
["sommelier", "xwayland", "xinit", "xterm", "sommelier"]
```

**Comment by uberhacker** [comment]
Resolved with the latest pre-built binaries.
