### ISSUE TITLE
[mosh] fails to run due to protobuf upgrade

### ISSUE THREAD

**Issue by kaiminglee** [skycocker/chromebrew#3054]
## Description
Protobuf was recently updated, but mosh is still linked against an older version.

```shell
mosh test.server
```

Output:
```shell
mosh-client: error while loading shared libraries: libprotobuf.so.15: cannot open shared object file: No such file or directory
```

What I think needs to be done:
- [ ] recompile mosh with current protobuff
- [ ] test

**Comment by skiman6010** [comment]
Hey @kaiminglee thanks for the issue!

Is this an issue when mosh is installed via binaries only or an issue with binaries and source?

You can check by installing mosh via `crew install mosh -s`.

**Comment by kaiminglee** [comment]
> Hey @kaiminglee thanks for the issue!
> 
> Is this an issue when mosh is installed via binaries only or an issue with binaries and source?
> 
> You can check by installing mosh via `crew install mosh -s`.

Rebuilding fixes the issue.  I'd do it myself, but I don't know how to contribute binaries (also for all the other architectures).

**Comment by JL2210** [comment]
@kaminglee Don't bother. That's @uberhacker's job.
