### ISSUE TITLE
Proposal: Remove outdated or unnecessary issues

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#3055]
So we clear up space.

**Comment by JL2210** [comment]
Trust me. We close all "outdated or unnecessary issues". If you are having
a real problem with Chromebrew, please report it.

**Comment by sajjaadf** [comment]
Well I can't because I have chroot by the _unsupported_ crouton

**Comment by JL2210** [comment]
Read the FAQ. I removed it :)

**Comment by JL2210** [comment]
The FAQ entry was unnecessary and causing... controversy.

**Comment by sajjaadf** [comment]
What!!!
