### ISSUE TITLE
Is there an issue with Chromebrew and the new version of Ruby?

### ISSUE THREAD

**Issue by revolutionnaire** [skycocker/chromebrew#3059]
## Description
I just installed Chromebrew and tried installing Jekyll to run an existing GitHub page that currently works, but an error occurs when I run the server locally. I'm not sure if it's related to issue #79

`bundle exec jekyll serve`

Output:
`Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in '<main>'
        1: from /usr/local/lib64/ruby/2.5.0/rubygems.rb:308:in 'activate_bin_path'
/usr/local/lib64/ruby/2.5.0/rubygems.rb:289:in 'find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)`

## Versions and system information
chromebrew: `1.0.6`

ChromeOS: 
`CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_RELEASE_BOARD=gnawty-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=gnawty-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel gnawty 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0`

Model: Acer CB3-131-series N15Q10

Architecture: `x86_64`

**Comment by JL2210** [comment]
Did you try reinstalling Chromebrew?

**Comment by revolutionnaire** [comment]
I did.

I get this error when I first try running `bundle exec jekyll serve` after cloning the repository:
`bash: bundle: command not found`

Then, I run `gem install bundler` and `bundle exec jekyll serve` and it gives me this error instead:
`Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in '<main>'
        1: from /usr/local/lib64/ruby/2.5.0/rubygems.rb:308:in 'activate_bin_path'
/usr/local/lib64/ruby/2.5.0/rubygems.rb:289:in 'find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)`

**Comment by JL2210** [comment]
What repository?

**Comment by revolutionnaire** [comment]
Sorry, forgot to specify that it's the repository of the Jekyll run GitHub page I'm trying to run locally.

**Comment by revolutionnaire** [comment]
I apologize if I left that part out.

[Here](https://revolutionnaire.github.io/) it is.

**Comment by JL2210** [comment]
Thank you. Let me take a look.
[This](https://stackoverflow.com/questions/47026174/find-spec-for-exe-cant-find-gem-bundler-0-a-gemgemnotfoundexception) website may be relevant.

**Comment by uberhacker** [comment]
@revolutionnaire: Thank you for reporting.  Sorry, I'm not following the issue here.  Did you run some `gem` commands to install jekyll and bundle?

**Comment by revolutionnaire** [comment]
I did, @uberhacker .

**Comment by uberhacker** [comment]
Can you please show us the history of the commands you executed?

**Comment by JL2210** [comment]
https://github.com/skycocker/chromebrew/issues/3059#issue-396231966
https://github.com/skycocker/chromebrew/issues/3059#issuecomment-451779686

**Comment by uberhacker** [comment]
That doesn't help me @JL2210.

**Comment by revolutionnaire** [comment]
I'm not sure if I can still pull a log of the commands because I've already _powerwashed_ this Chromebook again, @uberhacker .

Basically, it's just the following steps:
- Updated Ruby
- Cloned the repository
- Installed the Jekyll gem
- Installed the Bundler gem
- Changed permissions of some folders
- Powerwash the Chromebook
- Reinstall Chromebrew
- Run `sudo mount -i -o remount,exec /home/chronos/user`
- Powerwash it again

**Comment by uberhacker** [comment]
How did you install the gems?  Did you prefix with sudo?  Did you install locally or globally?  This is the kind of detailed info we need to try and troubleshoot.

**Comment by revolutionnaire** [comment]
I tried both ways and tried uinstalling both ways also. Sorry, forgot to add the latter step in the list.

**Comment by uberhacker** [comment]
Well, please try and reproduce the issue and send us your log history and that will help us to help you.

**Comment by revolutionnaire** [comment]
Is there a log file I can pull somewhere that lists all the activity I've done since the last _powerwash_?

**Comment by JL2210** [comment]
He said since. There is a fairly good file for that purpose :
'~/.bash_history' and the output of 'history'.

**Comment by uberhacker** [comment]
His last step above is `_Powerwash_ it again`.

**Comment by JL2210** [comment]
> Is there a log file I can pull somewhere that lists all the activity I've
done *since* the last *powerwash*?

**Comment by skiman6010** [comment]
@revolutionnaire I think the next step here is to do the exact same steps you have done to before but this time before you powerwash it would be great to get us `~/.bash_history` so we can try and see where the failure is.

**Comment by JL2210** [comment]
@revolutionnaire Run these commands in your repository to fix the issue:
```
$ sed -i 's,1\.16\.1,2\.0\.1,g' Gemfile.lock
$ bundle install 
$ bundle exec jekyll serve
```
If you'd like to save the changes and push them to GitHub, run this:
```
$ git add -A
$ git commit -m "Update 'bundle' version used"
$ git push
```

**Comment by JL2210** [comment]
Just make sure to change/remove `Gemfile.lock` every time there's an update to `bundler`.

**Comment by JL2210** [comment]
![screenshot 2019-01-09 at 1 47 12 pm](https://user-images.githubusercontent.com/38843657/50921079-1c1c5b80-1415-11e9-8375-91849c8a803c.png)

**Comment by revolutionnaire** [comment]
Thank you!

**Comment by JL2210** [comment]
@revolutionnaire Can this be closed?

**Comment by revolutionnaire** [comment]
Yes. And, I'm really sorry I troubled you with an unrelated issue to Chromebrew.

**Comment by JL2210** [comment]
No biggie. That's what we're here for.
