### ISSUE TITLE
Is this a good idea?

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#3066]
I have a chroot installed (crouton), then have virtualbox in the chroot and installed [ArnoldTheBat CHROMIUM OS](https://chromium.arnoldthebat.co.uk) installed in it with chromebrew installed in the virtualbox in the chroot. Is this a good Idea and would it work like normal chromebrew?

**Comment by sajjaadf** [comment]
and what is this pro thing @sajjaadf 
![screen shot 2019-01-07 at 7 41 38 pm](https://user-images.githubusercontent.com/32078755/50808640-4efb0e00-12b4-11e9-8dd7-22583f6b4934.png)
when hover my name, it says pro... what is that?

**Comment by skiman6010** [comment]
You can't use VirtualBox inside a Crouton chroot on a Chromebook. 

But anyway, this doesn't relate to Chromebrew really at all and is not an issue. Please stop spamming the issue feed.

**Comment by sajjaadf** [comment]
Qemu I meant

**Comment by sajjaadf** [comment]
Would that work?

**Comment by skiman6010** [comment]
Yeah most likely.
