### ISSUE TITLE
sommelier HAS dock icons

### ISSUE THREAD

**Issue by sajjaadf** [skycocker/chromebrew#3079]
this is native chromeos 73!

**Comment by sajjaadf** [comment]
![screenshot 2019-01-13 at 7 40 14 am](https://user-images.githubusercontent.com/32078755/51087336-d60e1300-1706-11e9-8c00-35a6d814e08a.png)

**Comment by JL2210** [comment]
Nice. Now please go back to the stable channel and wait for that incredible feature. Actually, I have it in stable channel right now, just not for GTK apps.

**Comment by uberhacker** [comment]
This is actually not an issue but it would be nice to post in Slack so everybody is aware.

**Comment by JL2210** [comment]
I do, too. Did you just change your name from "Terra Branford" to "Terra Brown"?

**Comment by superloach** [comment]
Yeah, don't worry about it. I'm just weird with names.
