### ISSUE TITLE
Applying for Google Summer of Code

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3080]
I think that applying for Google's Summer of Code would be a good idea to help continuing development of Chromebrew at a faster rate. As some of the packages are incredibly old, I believe that this would also be a good idea to keep them updated. On January 15th, we can apply [here](https://summerofcode.withgoogle.com/get-started/).

**Comment by uberhacker** [comment]
This sounds like a good idea.  Do you want to participate?

**Comment by JL2210** [comment]
Yes.

**Comment by JL2210** [comment]
I'll sign up at 3:00.

**Comment by JL2210** [comment]
@uberhacker, can you sign up for me? I'm below the age limit. [Link](https://summerofcode.withgoogle.com/org-signup/)

**Comment by uberhacker** [comment]
Unfortunately, the Chromebrew project was not selected to participate this year.  I guess they don't consider this project viral enough.

**Comment by JL2210** [comment]
Darn. Always next year, though.
