### ISSUE TITLE
[freerdp] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3114]
```
[ 38%] Linking C shared library libwinpr2.so
[ 38%] Built target winpr
make: *** [Makefile:152: all] Error 2
freerdp failed to build: `make V=0 -j2` exited with 2
```

**Comment by JL2210** [comment]
Can you give the full error log? What you gave here is useless. Also, please set `CREW_NPROC=1` before giving the error log.

**Comment by uberhacker** [comment]
It's not useless.  The error occurred on line 152 of Makefile.  That should give you enough information.

**Comment by JL2210** [comment]
Just give me the error log. The fact that the error occurred on line 152 of `Makefile` isn't helping. It builds just fine for me.

**Comment by JL2210** [comment]
This would have been a much better error log: 
```
warning: failed to load external entity "/usr/local/share/doc/docbook-xsl-1.79.2/manpages/docbook.xsl"
cannot parse /usr/local/share/doc/docbook-xsl-1.79.2/manpages/docbook.xsl
make[2]: *** [client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make:69: client/X11/xfreerdp.1] Error 4
make[1]: *** [CMakeFiles/Makefile2:4707: client/X11/CMakeFiles/xfreerdp.manpage.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by JL2210** [comment]
I can take it from here.

**Comment by uberhacker** [comment]
See attached build log.
[freerdp.log](https://github.com/skycocker/chromebrew/files/2800064/freerdp.log)

**Comment by JL2210** [comment]
I just tested. Pushing PR now.
