### ISSUE TITLE
crew usage shows wrong version

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#313]
When you run crew with no arguments the usage message is reporting a hard-coded version instead of the version that is installed. It doesn't seem like the release version is contained anywhere in the crew source or stored metadata.

```
chronos@localhost /usr/local/lib/crew $ crew
Chromebrew, version 0.2.1
Usage: crew [command] [package]
Available commands: search, download, install, remove
```

**Comment by uberhacker** [comment]
Can we close this out since the output of the crew command matches the release tag now?
