### ISSUE TITLE
Is there a way to tell which software would potentially break after upgrading a package?

### ISSUE THREAD

**Issue by nosarthur** [skycocker/chromebrew#3146]
It happened to me that upgrading one package broke some other software in crew. Is there a way to see the dependencies?

Or is it better to not upgrade anything unless one has to?

**Comment by uberhacker** [comment]
@nosarthur: Thank you for the information.  Can you please tell us specifically which package update broke another package?  It is certainly possible there might be some overlap in files provided by multiple packages.  You can compare with `crew files <package>` and see if either package has duplicate files (ie. the same filename and path).

**Comment by JL2210** [comment]
Either way, I'd say there is a very pertinent issue that we need to fix: File collisions.
So many packages conflict with other packages, and this is just one key example of probably hundreds of them.

**Comment by uberhacker** [comment]
You are probably over exaggerating but I imagine there could be a few.

**Comment by JL2210** [comment]
Maybe not. There are almost 1000 packages now, you know:
```
chronos@localhost ~/Downloads/chromebrew/packages $ ls -A1 | wc -l
966
```

**Comment by nosarthur** [comment]
Sorry I don't have specific information.

A few weeks (or months?) ago, I did `crew upgrade`, and `code` broke. Then every once a while I would install `code` to see if it works (It works now). Now I am a bit nervous about package upgrades.

**Comment by JL2210** [comment]
Oh, no worries. We were using official binaries a while back, but they made some (in my opinion, stupid) changes that broke a lot of people's installations. We're building from source and patching those changes out until we can get them fixed upstream.

You should *not* be worried about package upgrades. In most cases, they are very much advisable, as they can fix bugs and such. We try the best to keep things stable, but just bear with us and *keep upgrading*.

**Comment by nosarthur** [comment]
Sounds good. I will report specifics if something breaks next time.

Meanwhile, I am curious how crew tracks the package/library dependencies. Is it true that if A and B both need some library L of version 1, there is only 1 copy of L installed?

**Comment by JL2210** [comment]
Yes, unless the binaries are statically linked. They all load one shared library into memory, and all programs use that one shared library. When applications are statically linked, each application loads its own copy of the library.

**Comment by JL2210** [comment]
The dependencies are specified manually in the package files.

**Comment by nosarthur** [comment]
Good to know, thanks @JL2210

**Comment by JL2210** [comment]
@uberhacker Please add "[question]" tag.

**Comment by skiman6010** [comment]
Looks like all the questions were answered. Closing!
