### ISSUE TITLE
OpenSSL upgrade

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3158]
Patches needed for OpenSSL to be upgraded to 1.1.1a:
- [x] libssh2 #3151 
- [x] Curl https://curl.haxx.se/download/curl-7.64.0.tar.xz
- [ ] PHP7?

**Comment by uberhacker** [comment]
This is a good issue.  We need to consider all the packages that are affected by this upgrade.  Packages that should be tested include:
- [ ] az
- [ ] ctorrent
- [ ] curl
- [ ] goaccess
- [ ] haproxy
- [ ] irssi
- [ ] kore
- [ ] libevent
- [ ] libssh2
- [ ] libunwind
- [ ] links
- [ ] metasploit
- [ ] mongodb
- [ ] mutt
- [ ] ncat
- [ ] nettle
- [ ] nping
- [ ] php5
- [ ] php7
- [ ] radare2
- [ ] rtmpdump
- [ ] ruby
- [ ] serf
- [ ] siege
- [ ] socat
- [ ] stunnel
- [ ] tcpdump
- [ ] trousers
- [ ] vpnc

**Comment by JL2210** [comment]
Keep in mind that if any of these need updated, we should do that before trying to patch old versions that may not have compatibility.

**Comment by JL2210** [comment]
You can cross off Ruby from your list. 2.6 should fix any issues we currently have.

**Comment by JL2210** [comment]
And Curl should be fixed by a simple upgrade, along with libssh2 and maybe PHP 7.2+

**Comment by JL2210** [comment]
Most of these might actually use GnuTLS.
