### ISSUE TITLE
python3 update questions

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#316]
Python 3.6.0 is available. To be more like the ruby package should we create a python_latest package?

**Comment by thedamian** [comment]
You can update the python package as thats following the 3.XX version. We keep python27 to keep with the more used 2.7.XX version.

Ruby has a ruby_latest because we didnt want to touch the version thats prebuilt for thebjbstallation of chromebrew.

**Comment by cstrouse** [comment]
@thedamian Does it make sense to keep the package named python34 though if we're moving it to 36?

**Comment by mattddowney** [comment]
Seems redundant. However, the git package depends on python, so it should be tested to build with python 3.6 as well. Would be nice to have a way to list off all of the packages that depend on a particular one, to facilitate testing of downstream packages.

**Comment by lyxell** [comment]
The git package is and will probably always be binary, so it doesn't really depend on python at all even though it says so. There's a pull request regarding that.
