### ISSUE TITLE
Fonts display in Gimp and Sublime_text

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3162]
## Description
while running gimp or sublime_text on a C302CA with a brand new homecrew installation, fonts are HUGE in menu bar. How can I reduce its size ? Playing with SCALE env var leads to very tiny text in the edit window of sublime_text.

**Comment by JL2210** [comment]
You can use decimal numbers in SCALE. Try 1.2.

**Comment by JL2210** [comment]
May I see a screenshot with and without SCALE set to 1.2?

**Comment by vincowl** [comment]
**Scale 1.2**
![screenshot 2019-02-12 at 15 48 23](https://user-images.githubusercontent.com/16786457/52643615-b1f84a00-2edd-11e9-9360-218003c2029d.png)
![screenshot 2019-02-12 at 15 48 00](https://user-images.githubusercontent.com/16786457/52643616-b290e080-2edd-11e9-8ae5-3a910e27e744.png)

**Scale 1**
![screenshot 2019-02-12 at 15 47 05](https://user-images.githubusercontent.com/16786457/52643617-b290e080-2edd-11e9-8b83-76fd51251d96.png)
![screenshot 2019-02-12 at 15 45 17](https://user-images.githubusercontent.com/16786457/52643618-b290e080-2edd-11e9-8a76-0a75a7d40363.png)

I managed to handle the trouble adding `gtk-font-name="sans-serif 6"` in a `~/.gtkrc-2.0` file.
![screenshot 2019-02-12 at 15 54 19](https://user-images.githubusercontent.com/16786457/52644078-7e69ef80-2ede-11e9-83a7-1a1a3b79b6e2.png)
![screenshot 2019-02-12 at 15 53 57](https://user-images.githubusercontent.com/16786457/52644080-7e69ef80-2ede-11e9-835d-62f10ebd53f6.png)

**Comment by JL2210** [comment]
Better question: Why is Gimp even BUILT with GTK+2? GTK+3 is newer and includes Wayland support.

**Comment by vincowl** [comment]
Good question....
I am going to have a look at it...

**Comment by vincowl** [comment]
![image](https://user-images.githubusercontent.com/16786457/52644591-63e44600-2edf-11e9-9dfb-a025a391e0c9.png)

**Comment by JL2210** [comment]
Try `crew remove gtk2 gimp && sed -i 's,gtk2,gtk3,g' /usr/local/lib/crew/packages/gimp.rb && crew install -S gimp`.

**Comment by vincowl** [comment]
More awful with sublime_text : dependency is not correctly defined, even if it should be linked to the old gtk2
![image](https://user-images.githubusercontent.com/16786457/52644769-ba518480-2edf-11e9-8147-56110a5f12ac.png)

**Comment by vincowl** [comment]
Command won't produce a clean result since gtk2 seams to be already needed 
```
gimp: GIMP is a cross-platform image editor available for GNU/Linux, OS X, Windows and more operating systems.
https://www.gimp.org/
version 2.10.6
The following packages also need to be installed: 
sphinx setuptools bc ed gtk2 yasm dejagnu expect tcl gcc7 lzma curl rust alsa_plugins ffmpeg libopencoreamr libvoamrwbenc
 libmp3lame libfrei0r libtheora libvorbis libogg libsdl2 nasm vidstab libopus libx264 libxvid libass speexdsp 
Do you agree? [Y/n] 
```

**Comment by JL2210** [comment]
OK, first of all, run `crew install gcc8`.

**Comment by vincowl** [comment]
It's already installed

**Comment by JL2210** [comment]
`crew remove gcc8 gcc7 && wget -O- https://bintray.com/chromebrew/chromebrew/download_file?file_path=gcc8-8.2.0-chromeos-x86_64.tar.xz | tar xpJ - -C /`

**Comment by vincowl** [comment]
OK. Waiting for installation of gcc8... 
Meanwhile, I am looking at nested dependencies and here are the packages linked to gtk2

![image](https://user-images.githubusercontent.com/16786457/52645344-e3264980-2ee0-11e9-9488-5f9538d8d879.png)

**Comment by vincowl** [comment]
Troubles to install gcc8....
```
Saving to: ‘STDOUT’
-                                    0%[                                                                ]       0  --.-KB/s               t
ar: dlist: Cannot open: Read-only file system
tar: filelist: Cannot open: Read-only file system
-                                  100%[===============================================================>]  45.73M   439KB/s    in 90s     
2019-02-12 16:23:31 (522 KB/s) - written to stdout [47952068/47952068]
tar: usr: Cannot utime: Read-only file system
tar: usr: Cannot change ownership to uid 1000, gid 1000: Read-only file system
tar: Exiting with failure status due to previous errors
```
gcc still linked to x86_64-cros-linux-gnu. Any idea ? I tried to add sudo commands without success

**Comment by JL2210** [comment]
That's normal. Please do **not** use `sudo` when dealing with Chromebrew. Now you have to run:
```
sudo chown -R chronos:chronos /usr/local
```
Try running `ruby --help` and see what happens.

**Comment by vincowl** [comment]
OK. The ruby's command help is displayed correctly with version `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`

**Comment by JL2210** [comment]
OK, now run `crew install gcc8`.

Then try setting scale to `1.3` in `~/.bashrc`.

**Comment by vincowl** [comment]
gcc8 is declared as already installed. Absolutely no impact changing SCALE to 1.3.
I don't really see the link between recompiling gcc8 and the problem with apps depending on GTK2. Don't you think it would be better to first try to reduce dependency to GTK2 ?

**Comment by JL2210** [comment]
What's the output of `crew install gcc`? Just because the files are there doesn't mean the metadata is. I just want to save you some pain with the upgrade.

What happens if you set `SCALE` to, say, `1.4` or `1.5`?

**Comment by vincowl** [comment]
``` bash
chronos@localhost / $ crew install gcc8
(i) gcc8: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
https://www.gnu.org/software/gcc/
version 8.2.0
Package gcc8 already installed, skipping...
Gcc8 installed!
```
Let's use sublime_text as reference since it is the worst case :
When SCALE is set to 1.5, menu bar's font is smaller, quite normal, but edit panel's font becomes tiny, quite unreadable.
In gimp, text size is quite OK, but icons becomes tiny too...

**Comment by JL2210** [comment]
All right, you mentioned that setting `gtk-font-name="sans-serif 6"` in `~/.gtkrc-2.0` fixed the issue, is that correct?

**Comment by vincowl** [comment]
correct.

**Comment by JL2210** [comment]
Add a FAQ entry depicting your issue and its solution and close this issue.

The best FAQ entries are short and sweet, and they describe your problem and its solution entirely.

**Comment by vincowl** [comment]
OK. Done in FAQ [here](https://github.com/skycocker/chromebrew/wiki/Troubleshooting-common-problems#troubles-with-font-size-in-apps-depending-on-gtk2)

**Comment by vincowl** [comment]
@JL2210 : Thanks for your very reactive help !
