### ISSUE TITLE
List of proprietary and non open-source (non GPL-3 compatible) packages in Chromebrew

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3163]
- [ ] `sublime_text`

More may be added later.

It would be optimal if these packages were removed from Chromebrew so as to avoid licensing conflicts.

**Comment by uberhacker** [comment]
While sublime text can officially be labeled shareware, I think we can keep it regardless of the license.  The Chromebrew project itself is GPL but any software that is installed is the user's responsibility from a legal standpoint.
```
Sublime Text may be downloaded and evaluated for free, however a license must be purchased for continued use. There is currently no enforced time limit for the evaluation.
```
