### ISSUE TITLE
[gdb] 8.2.1 brings along a bunch of x11 dependencies

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#3166]
## Description
Upgrading crew package gdb from 8.1 to 8.2.1 brings along a bunch of x11 dependencies:
libx11 xorg_proto libxcb xcb_proto libxau libxtrans

Are those really necessary?

## Versions and system information
chromebrew: 1.2.0

**Comment by JL2210** [comment]
I'm pretty sure that's because we enable the GUI debugger.

**Comment by blu** [comment]
Oh, nice! Ok, nevermind then.
