### ISSUE TITLE
[gtk3] Error 127 when attempting to install

### ISSUE THREAD

**Issue by KaehLikeTheLetterK** [skycocker/chromebrew#3168]
I've tried several time to install it, but it keeps failing at the post-install script with the error

`gtk3 failed to install: `update-mime-database /usr/local/share/mime` exited with 127`

I'm not sure what could be causing this, and it's consistent, preventing me from installing QEMU and libsdl.

The only unorthodox information I can provide is that I'm on an older version of ChromeOS (65) because the UI from the versions after it have been a mess for my device.

**Comment by uberhacker** [comment]
@KaehLikeTheLetterK: My guess is you don't have the `shared_mime_info` package installed.  Try `crew install shared_mime_info` and see if that fixes the issue.

**Comment by KaehLikeTheLetterK** [comment]
@uberhacker Yep, that seems to have solved it. Thank you kindly!
