### ISSUE TITLE
curl Missing libmetalink.so.3 after downloading

### ISSUE THREAD

**Issue by KaehLikeTheLetterK** [skycocker/chromebrew#3174]
Happened right after attempting to install clib;

```chronos@localhost ~/Downloads/bluefish/bluefish-2.2.10 $ crew install clib 
clib: C package manager-ish https://github.com/clibs/clib version 1.8.1 
The following packages also need to be installed: curl brotli libmetalink openldap rtmpdump Do you agree? [Y/n] y 
Proceeding... 
curl: Command line tool and library for transferring data with URLs. https://curl.haxx.se/ version 7.64.0 Precompiled binary available, downloading... ################################################################################################################################################ 100.0% 
Archive downloaded Unpacking archive, this may take awhile... 
Installing... 
Performing post-install... 
brotli: Brotli compression format https://github.com/google/brotli version 1.0.4 
Precompiled binary available, downloading... 
curl: error while loading shared libraries: libmetalink.so.3: cannot open shared object file: No such file or directory 
Traceback (most recent call last): 
12: from /usr/local/bin/crew:978:in `<main>' 
11: from /usr/local/bin/crew:909:in `install_command' 
10: from /usr/local/bin/crew:909:in `each' 
9: from /usr/local/bin/crew:913:in `block in install_command' 
8: from /usr/local/bin/crew:612:in `resolve_dependencies_and_install' 
7: from /usr/local/bin/crew:687:in `resolve_dependencies'
6: from /usr/local/bin/crew:687:in `each' 
5: from /usr/local/bin/crew:689:in `block in resolve_dependencies' 
4: from /usr/local/bin/crew:701:in `install' 
3: from /usr/local/bin/crew:429:in `download' 
2: from /usr/local/bin/crew:429:in `chdir'
1: from /usr/local/bin/crew:436:in `block in download' 
/usr/local/bin/crew:436:in `read': No such file or directory @ rb_sysopen - ./brotli-1.0.4-chromeos-armv7l.tar.xz (Errno::ENOENT)```

edit: formatting

**Comment by uberhacker** [comment]
I think the brotli package is missing the curl dependency.  Try this: `crew upgrade curl`

**Comment by KaehLikeTheLetterK** [comment]
@uberhacker Reports curl as up-to-date. I should also mention this breaks curl system-wide, as found when I attempted to use dev_install shortly after.

**Comment by uberhacker** [comment]
My guess is curl was corrupted somehow.  I just installed everything fresh and curl and brotli both installed fine.  Maybe try `crew remove curl && crew install curl`?

**Comment by KaehLikeTheLetterK** [comment]
That seems to have fixed it. I'm guessing the problem came from curl installing before libmetalink.

**Comment by uberhacker** [comment]
It's possible you just needed to `crew update && crew upgrade`.  It appears you were trying to install the previous version of curl.

**Comment by KaehLikeTheLetterK** [comment]
Except I literally just installed crew fresh again (dev_install led to me recovering my chromebook via usb) and was able to reproduce the issue.

**Comment by uberhacker** [comment]
That is interesting because brotli and libmetalink are now dependencies of curl which should get installed before curl.

**Comment by KaehLikeTheLetterK** [comment]
Whatever the case, removing and reinstalling curl by itself did solve it, so thank you!

**Comment by uberhacker** [comment]
No problem.  I think the new speedy dependency resolving logic is mixing up the install order.  We'll need to work on fixing that.

**Comment by KaehLikeTheLetterK** [comment]
Should I close this one?

**Comment by uberhacker** [comment]
We can keep this open because others have reported issues with curl on other packages.

**Comment by verniyb** [comment]
> My guess is curl was corrupted somehow. I just installed everything fresh and curl and brotli both installed fine. Maybe try `crew remove curl && crew install curl`?

the same problem, and reinstallation did work 👍

**Comment by FabioMen10** [comment]
Same error here: `curl: error while loading shared libraries: libmetalink.so.3: cannot open shared object file: No such file or directory`

The problem continues the same after try `crew remove curl && crew install curl`. Did not work.

crew command results with these two lines first:
`grep: /etc/lsb-release: No such file or directory`
`sh: 1: /usr/local/share/automake-*/config.guess: not found`

And now, clear command gives me this error too:
`clear: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory`

Does anyone successfully repair these errors?

**Comment by jhoward15** [comment]
@FabioMen10 Getting exact same error. Any luck fixing it?

**Comment by uberhacker** [comment]
@FabioMen10 @jhoward15:  Does `crew reinstall libmetalink` fix curl?

**Comment by satmandu** [comment]
Interesting. Libmetalink is installed much earlier than curl during installs in `install.sh`...

**Comment by FabioMen10** [comment]
I've excluded "Apps for Linux" e reinstall this. The same error on run "curl -Ls git.io/vddgY | bash" occur.
`grep: /etc/lsb-release: No such file or directory` It's normal?

**Comment by satmandu** [comment]
What device are you on? And what version of ChromeOS?

**Comment by saltedcoffii** [comment]
@FabioMen10 are you still having this error?

**Comment by FabioMen10** [comment]
Hello @saltedcoffii  I'll try again.

**Comment by FabioMen10** [comment]
I've tested @saltedcoffii . But error `grep: /etc/lsb-release: No such file or directory` continues. At least chromebrew works now!

**Comment by FabioMen10** [comment]
Not everything!
![image](https://user-images.githubusercontent.com/12684528/115320997-e6689000-a150-11eb-9134-4b6d12b2183f.png)

**Comment by uberhacker** [comment]
@FabioMen10:  Are you running chromebrew on a Chromebook?  Does `lsb-release -a` produce any output?

**Comment by satmandu** [comment]
See the Installation notes on the main page:

**Open the terminal with Ctrl+Alt+T and type shell.**

**If this command returns ERROR: unknown command: shell, please have a second look at the prerequisites and make sure your Chromebook is in developer mode.**

**Comment by FabioMen10** [comment]
Thank you for all your help. @uberhacker I receive this message from shell:
`chronos@localhost / $ lsb-release -a`
`bash: lsb-release: command not found` 
I'm sorry for the misunderstanding @satmandu. Chrome OS is already in developer mode.  But I didn't pay attention that the chromebrew only works on crosh. I would use it precisely in the crostini.

**Comment by saltedcoffii** [comment]
Alright I think this can be labelled wonfix and closed
