### ISSUE TITLE
Can install program but can't run them

### ISSUE THREAD

**Issue by ScardracS** [skycocker/chromebrew#3176]
Hi everybody!

As title said I can install program but I can't see them on my shelf and/or run them via terminal.

For example I've installed inkscape, but when I try t run it on shell (simply typing inkscape) it just tell me "Nothing to do!"

I feel myself a bit idiot asking that, but... I've doing something wrong?
I hope for a quick answer

**Comment by ScardracS** [comment]
![screenshot 2019-02-17 at 18 02 23](https://user-images.githubusercontent.com/12005889/52916333-4dbef700-32de-11e9-89c1-0967a6b88c43.png)

**Comment by ScardracS** [comment]
P.S. I've cloudready. IDK if this could be a problem

**Comment by uberhacker** [comment]
Thank you for reporting this issue @ScardracS.  My guess is you need the sommelier daemon running.  Have you followed the post-install instructions from `crew postinstall sommelier`?

**Comment by JL2210** [comment]
Shelf apps don't work yet, but try adding this to `~/.bashrc`:
```
export LC_ALL=C
export LANG=C
```

**Comment by ScardracS** [comment]
I'll try. Thank men!

**Comment by JL2210** [comment]
@ScardracS Did this work? If so, please close this issue.

**Comment by JL2210** [comment]
@uberhacker Please close this. @ScardracS is unresponsive.
