### ISSUE TITLE
Question; Compiling devkitPro on ARMv7

### ISSUE THREAD

**Issue by KaehLikeTheLetterK** [skycocker/chromebrew#3186]
I have all the requirements installed, including zlib and freeimage, but I keep getting:
```
/usr/local/bin/ld: plugin.c:(.text+0x3a0): undefined reference to `dlerror' 
/usr/local/bin/ld: plugin.c:(.text+0x3cc): undefined reference to `dlsym'
```

I've tried finding some kind of solution, but to no avail. Any ideas? It seems to compile fine in my Ubuntu chroot, but I've gotten similar errors in other programs I wanted to compile (Audacity, namely), so I'm curious.

**Comment by uberhacker** [comment]
@KaehLikeTheLetterK: You could try changing the default linker:
```
$ crew install ld_default
$ ld_default g
```
This would change the default linker to use gold instead of bfd.

**Comment by KaehLikeTheLetterK** [comment]
```
$ crew install ld_default
ld_default: Select the default ld executable and check for libraries in #{CREW_LIB_PREFIX} first
https://github.com/skycocker/chromebrew/wiki/FAQ
version 1.2
No precompiled binary available for your platform, downloading source...

Archive downloaded
Unpacking archive, this may take awhile...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

It still installed, strangely enough.

**Comment by KaehLikeTheLetterK** [comment]
Seems like that didn't work. Same error as before.

**Comment by uberhacker** [comment]
Sorry to hear it.  Maybe you are missing some extra dependency for the package you are trying to build.  The error message you see is @JL2210's use of `file:///dev/null` to bypass the source.  Not elegant, but it works.

**Comment by KaehLikeTheLetterK** [comment]
It works in Ubuntu still, so I suppose no harm done. Sorry for bugging y'all so much with my unique situations! You've been a big help, so thanks :)

**Comment by JL2210** [comment]
Try compiling with LIBS=-ldl appended to the `configure` command.
