### ISSUE TITLE
install fails when CREW_PREFIX is preset

### ISSUE THREAD

**Issue by perryh2** [skycocker/chromebrew#3187]
## Description
I encountered 3 failures while attempting to install chromebrew with CREW_PREFIX set (to install in a non-default location).  I was able to work around the first two, but it's not clear (to me) how to get past the third.

1. install.sh does not create ${CREW_PREFIX}/bin
2. install.sh does not add ${CREW_PREFIX}/bin to the PATH before trying to run crew.
3. "crew install ..." attempts to assign to an unknown target.

Details in attached logfile, best viewed with "less -R" or similar since it contains ANSI escape sequences.  The first attempt is as directed in README.md, except for piping to "bash -x" instead of just "bash" (so as to log the commands that install.sh is running).  The second attempt deletes a few lines from install.sh so as to restart at the point of previous failure (after I manually created the missing directory).  The third attempt consisted of manually retrying the failed execution of crew, after fixing PATH.  I've also included the first 15 lines of bin/crew, and the first 20 lines of const.rb, to show where the 3rd failure occurred.

## Versions and system information
chromebrew: `crew --version`
1.2.0

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_RELEASE_BOARD=enguarde-signed-mp-v25keys
CHROMEOS_RELEASE_BRANCH_NUMBER=113
CHROMEOS_RELEASE_BUILDER_PATH=enguarde-release/R71-11151.113.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.113.0 (Official Build) stable-channel enguarde 
CHROMEOS_RELEASE_KEYSET=mp-v25
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.113.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.113.0

Model: Lenovo N21 Chromebook

Architecture: `uname -m`
x86_64

## Addtional information
Background:  I have done a lot of development, including quite a bit with C and shell on Unix/Linux, but I am not familiar with Ruby.

The first issue can be fixed by adding ${CREW_PREFIX}/bin to line 39 of install.sh, and the second can be fixed by adding ${CREW_PREFIX}/bin to PATH ahead of line 204.  Not knowing Ruby, I'm not at all clear on how to fix the 3rd issue.
[crew_install.txt](https://github.com/skycocker/chromebrew/files/2892017/crew_install.txt)

**Comment by perryh2** [comment]
I've found a possible workaround, which (I think) also eliminates the need to add ${CREW_PREFIX}/bin to the PATH, to build packages from source, or even to set CREW_PREFIX in .bashrc: run the attached script (with sudo) ahead of line 204 of install.sh and comment out line 12 of const.rb.  It would probably also be advisable for crew itself to check during initialization whether it is installed in a non-standard location, and if so to refresh the symlinks, so as to cover for the case where dev_install has wiped /usr/local.
[make_crew_symlinks.sh](https://github.com/skycocker/chromebrew/files/2895471/make_crew_symlinks.sh.txt)

**Comment by JL2210** [comment]
I'm still working on all of this ${CREW_PREFIX} stuff. We're making
progress, but not much.

**Comment by perryh2** [comment]
I started looking into it also, and it seems to be a fair-sized can of worms.  Going to clean everything up and do a "normal" install, so as to at least know how it's supposed to turn out.

**Comment by JL2210** [comment]
I can solve 1. and 2., but I assume (sadly) that 3. needs to be moved from `const.rb` to `crew`.

**Comment by KellyLSB** [comment]
https://github.com/skycocker/chromebrew/blob/e63f131f81a62f990e6d1a0e4fca0052e5e130ce/install.sh#L133
