### ISSUE TITLE
Is it possible to install a specific version of a package?

### ISSUE THREAD

**Issue by nosarthur** [skycocker/chromebrew#3196]
Something like
```
crew install some-package==1.2.3
```

**Comment by JL2210** [comment]
No. As packages are upgraded and old versions are removed, it is no longer
possible to install older packages. Build them yourself or download older
binaries from Bintray and install them by hand.

**Comment by nosarthur** [comment]
I see, thanks

**Comment by JL2210** [comment]
Which package were you concerned about?

**Comment by nosarthur** [comment]
I don't have anything specific in mind. Just curious in general

**Comment by JL2210** [comment]
@nosarthur Can you close this if your issue has been resolved?
