### ISSUE TITLE
Go doesn't install 'godoc' binary

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3197]
After installing the `go` package, only `go` and `gofmt` are installed, but not all of the other programs usually installed with Go. I beleive this is because we install in `/usr/local/share/go` and create symlinks. Is there a better way to do this or do I just have to live without `godoc`?

**Comment by uberhacker** [comment]
You could provide a PR with the added symlink.  Shouldn't be difficult.

**Comment by JL2210** [comment]
I don't want to add a symlink because other programs may be left out. Is there a way we could install directly to `/usr/local` instead of to an offset? Even if we can't, a better directory for this would be `/usr/local/opt/go`.

**Comment by nosarthur** [comment]
I used `go get -v golang.org/x/tools/cmd/godoc`. It seems to work

**Comment by JL2210** [comment]
Thanks @nos. That works for me.

**Comment by JL2210** [comment]
I was looking for `go doc`. I have it as an alias in my `~/.bashrc` now.
