### ISSUE TITLE
crew should not try to unpack a non-archive

### ISSUE THREAD

**Issue by helge000** [skycocker/chromebrew#3205]
## Description
crew should not try to extract non-archives

```shell
#crew install mysqltuner
[...]
Archive downloaded
Unpacking archive, this may take awhile...
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by JL2210** [comment]
Nice!

**Comment by JL2210** [comment]
Although I don't like the message it puts out now. I think it was better before (i.e. `Unpacking archive, this may take a while...` vs. `Unpacking archive using 'tar', this may take a while...`).
