### ISSUE TITLE
[install] gcc8 needs isl

### ISSUE THREAD

**Issue by perryh2** [skycocker/chromebrew#3209]
## Description
When attempting to compile anything using gcc from the gcc8 package as installed by install.sh, without first installing buildessential from binaries, gcc fails because isl is missing.

```shell
echo 'main(){printf("hello\n");}' > hello.c
gcc hello.c
```

produces

```shell
cc1: error while loading shared libraries: libisl.so.19: cannot open shared object file: No such file or directory
```

This makes it impossible to install buildessential and its dependencies from source instead of from prebuilt binary packages.  It can't be fixed by setting LD_LIBRARY_PATH, because there is no libisl.so* anywhere within $CREW_PREFIX.

## Versions and system information
chromebrew: 1.2.1

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BB86912A-29BE-A59B-31EF-8F4DD1C023E2}
CHROMEOS_RELEASE_BOARD=enguarde-signed-mp-v25keys
CHROMEOS_RELEASE_BRANCH_NUMBER=113
CHROMEOS_RELEASE_BUILDER_PATH=enguarde-release/R71-11151.113.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.113.0 (Official Build) stable-channel enguarde
CHROMEOS_RELEASE_KEYSET=mp-v25
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.113.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.113.0

Model: Lenovo N21 Chromebook

Architecture: x86_64

## Addtional information

It looks as if install.sh may need to preinstall the "its" package along with gcc8.

**Comment by JL2210** [comment]
gcc is installed as a dependency to ruby. It's not meant to be used without
installing buildessential.

"buildessential" is a description of what it is: essentials to build
software.

**Comment by perryh2** [comment]
Well, it seems kind of pointless to install something that doesn't work.  If we need gcc as a dependency of ruby, by the same logic we also need the runtime dependencies of gcc.  (Or, alternatively, if ruby doesn't need a _working_ gcc, why not just leave that dependency unmet -- instead of leaving gcc's dependencies unmet -- or install a stub?)

Background:  const.rb attempts (unsuccessfully) to force install-from-source if CREW_PREFIX is not /usr/local.  This demonstrates an intent to support doing the initial installation of buildessential from source instead of from prebuilt binary packages, and that in turn requires a working gcc (and perhaps a few other things).

isl is the tip of a small iceberg -- so far I have also identified mpc, mpfr, and binutils (for as) -- but I expect to be able to bootstrap most of buildessentials given a working gcc.

**Comment by JL2210** [comment]
Ruby requires libssp, which gcc provides. It doesn't require any other
component of gcc.

**Comment by JL2210** [comment]
It's actually meant so you can set CREW_PREFIX after installation, but
we're still working a lot of this stuff out (mainly due to the fact that a
lot of the packages assume /usr/local as the install directory).

**Comment by JL2210** [comment]
@uberhacker This isn't a bug. He's trying to use GCC before installing buildessential. If you don't mind, adding the [invalid] and [installation] tags would be more appropriate.

**Comment by uberhacker** [comment]
The isl package is also a "core" package.
