### ISSUE TITLE
Duplicate packages

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3213]
Duplicate packages: `bdwgc` and `gc`.

Also, please update to `8.0.4`: https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz

**Comment by uberhacker** [comment]
You are welcome to submit a PR to update and remove the duplicate package.

**Comment by uberhacker** [comment]
Just make sure you also update all the other packages that currently depend on the package you plan on removing and replace the dependency with the other package.  That means testing each package afterwards that is affected also.

**Comment by JL2210** [comment]
There's no need to update if they're both the same package.

**Comment by uberhacker** [comment]
You sound so confident.  Always need to test.

**Comment by JL2210** [comment]
It's a little thing called backwards compatibility that every sane project has.

**Comment by uberhacker** [comment]
Fixed in #3222.

**Comment by JL2210** [comment]
There's a reason I didn't add "Fixes" to the description of that PR: There
may be more duplicate packages in the future. Please reopen.

**Comment by uberhacker** [comment]
I think this is the only duplicate package.

**Comment by JL2210** [comment]
That I've found so far, yes. But there may be more in the future.

**Comment by uberhacker** [comment]
If you find one, let me know and I'll reopen.
