### ISSUE TITLE
tlmgr install XXX throws error : tlmgr: Remote repository is newer than local (2017 < 2018)

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3218]
Using ```tlmgr update --self --all``` throws the following error : 
```tlmgr: Remote repository is newer than local (2017 < 2018)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```

This means we have to update texlive but running ```update-tlmgr-latest(.sh/.exe) --update``` leads to 
```Verifying archive integrity... All good.
Uncompressing TeX Live Manager Updater  100%  
/home/chronos/user/Downloads/scripts/update-tlmgr-latest.sh: 1: eval: ./runme.sh: Permission denied
```

**Comment by vincowl** [comment]
To run `update-tlmgr-update`, we have to run : 
```sudo mount -o remount,rw -io exec /tmp```

**Comment by skiman6010** [comment]
A better way to do this is probably `export TMPDIR=/usr/local/tmp`.

**Comment by vincowl** [comment]
Just for info : why would it be better since it is run only once ? Both would be forget after a reboot and /tmp is not a critical part. Maybe you're thinking to something cleaner while keeping chromebrew's tmp in /usr/local and not mixing it with the chromeOS tmp dir ? Always good for me to learn from others best practices !

**Comment by JL2210** [comment]
Thanks for the FAQ entry! I made it a little more clear and fixed some formatting errors.

**Comment by skiman6010** [comment]
@vincowl I map the temp directly into /usr/local to maintain security over the rest of the device's drive. I also have the export command in my bashrc.

**Comment by JL2210** [comment]
That's not secure at all. That would map the temporary directory into a
directory that is persistent across reboots and is accessible to all users,
even in guest mode.

**Comment by skiman6010** [comment]
Literally achieves the same thing as remounting the /tmp directory without remounting anything that isn't already mounted... 

It does not make it accessible to users in guest mode by the way. Also I don't have guest mode activated either.

**Comment by JL2210** [comment]
`/tmp` is cleared on reboot.

Guest mode users can access all your `/usr/local` data via. `/mnt/stateful_partition/dev_image/`.

Turning off guest mode would certainly tighten security, but there are ways...
