### ISSUE TITLE
Invalid grammar in `crew`

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3219]
A while and awhile have different meanings.
A while is a noun and means “a period of time.”
In contrast, awhile is an adverb, and it means “for a time.”

So `awhile` should be changed to `a while` in `crew`.

**Comment by uberhacker** [comment]
Oh no!  The grammar nazis are here again!  Feel free to submit a PR.

**Comment by JL2210** [comment]
OK.
