### ISSUE TITLE
Duplicate node packages

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#323]
Right now we have 3 identical packages for node:
https://github.com/skycocker/chromebrew/blob/master/packages/node.rb
https://github.com/skycocker/chromebrew/blob/master/packages/node_stable.rb
https://github.com/skycocker/chromebrew/blob/master/packages/node_current.rb

Is there a specific reason for this?
@thedamian

**Comment by thedamian** [comment]
When I introduced node to chromebrew (for selfish reasons) there was node (which was at 4.x) and then they called their "beta" version "stable" NOW it's "LTS and CURRENT" so this was my latest way to fix that. Actually current shouldn't be at 6.x but at 7.x

What do you guys suggest.

similar to Ubuntu. they have TWO versions (and similar to PHP, one breaks the other)

6.x is called "LTS" and 7.x (which breaks things and is not backward compatible) is called "CURRENT"

Should we call them by number.

maybe Node = 6.x and Node7 = 7.x

I didn't want to remove "stable" just in case people used it.

THOUGHTS?

**Comment by lyxell** [comment]
I think we should keep it as it is, `node.rb` for the LTS and `node_current.rb` for the latest one.

**Comment by thedamian** [comment]
and remove _stable? 

THAT'S what I'm worried about. About people wondering why their node isn't updating (although I know node can update itself so most people don't care)

**Comment by thedamian** [comment]
comments appriciated on what your'e asking here: on this PR (which does what you're suggesting) https://github.com/skycocker/chromebrew/pull/359
