### ISSUE TITLE
Package update request: LLVM 8

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3234]
Package update available at http://releases.llvm.org/download.html#8.0.0: LLVM 8.
Along with this update, please transfer to using HTTPS and update `clc` and `clc++` to use this logic:

```
#!/bin/bash
cxx_sys=#{CREW_PREFIX}/include/c++/\$(gcc -dumpversion)
cxx_inc=#{CREW_PREFIX}/include/c++/\$(gcc -dumpversion)/\$(gcc -dumpmachine)
gnuc_lib=#{CREW_LIB_PREFIX}/gcc/\$(gcc -dumpmachine)/\$(gcc -dumpversion)
clang++ --rtlib=compiler-rt -stdlib=libc++ -cxx-isystem\${cxx_sys} -I\${cxx_inc} -B\${gnuc_lib} -L\${gnuc_lib} \"\$@\"
```

This will alleviate the need for architecture-dependent scripts, and fix using `clc` after GCC upgrades.

Please include clang extra tools and omit the `-DLLVM_TARGETS_TO_BUILD` flag.

If you don't mind, it would also be nice to enable LLVM being linked against libc++ and compiler-rt.

And llvm-gold would be a great addition.

**Comment by uberhacker** [comment]
See #3248.
