### ISSUE TITLE
i get Traceback while installing code

### ISSUE THREAD

**Issue by MuZhou233** [skycocker/chromebrew#3237]
When i run 'crew install code', i got traceback.

```shell
chronos@localhost / $ crew install code
```

Output:
```shell
code: Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS.
https://code.visualstudio.com/
version 1.31.1
The following packages also need to be installed: 
xdg_base 
Do you agree? [Y/n] 
Proceeding...
xdg_base: XDG Base Directory Specification Configuration
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
version 0.7-4
No precompiled binary available for your platform, downloading source...

Archive downloaded
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Traceback (most recent call last):
        13: from /usr/local/bin/crew:974:in `<main>'
        12: from /usr/local/bin/crew:905:in `install_command'
        11: from /usr/local/bin/crew:905:in `each'
        10: from /usr/local/bin/crew:909:in `block in install_command'
         9: from /usr/local/bin/crew:608:in `resolve_dependencies_and_install'
         8: from /usr/local/bin/crew:683:in `resolve_dependencies'
         7: from /usr/local/bin/crew:683:in `each'
         6: from /usr/local/bin/crew:685:in `block in resolve_dependencies'
         5: from /usr/local/bin/crew:704:in `install'
         4: from /usr/local/bin/crew:480:in `build_and_preconfigure'
         3: from /usr/local/bin/crew:480:in `chdir'
         2: from /usr/local/bin/crew:495:in `block in build_and_preconfigure'
         1: from /usr/local/lib/crew/packages/xdg_base.rb:13:in `preinstall'
/usr/local/lib/crew/packages/xdg_base.rb:13:in `readlink': Invalid argument @ rb_readlink - /home/chronos/user/.config (Errno::EINVAL)
```

chromebrew version: 1.2.3

and, Chrome72 on x86_64

**Comment by JL2210** [comment]
@uberhacker Can we just toss out the file-manipulation section of the `xdg_base` package and focus on setting environment variables and creating directories? That would eliminate the frustration that it's currently causing.

**Comment by gt945** [comment]
There is a workaround:
before install xdg_base
mv ~/.local ~/.local.bak
mv ~/.config ~/.config.bak
after install xdg_base
mv ~/.local.bak/* ~/.local/
mv ~/.config.bak/* ~/.config/

**Comment by uberhacker** [comment]
@JL2210: The whole point of that section is to do exactly what @gt945 did as a workaround.  Apparently, the readlink line you entered hasn't been tested.  Let's try to fix that section so users don't lose all their local config everytime this package is installed.

**Comment by JL2210** [comment]
Or we could just remove the section that moves files around entirely. If there are any issues, we can fix them in other packages instead of breaking xdg_base compliance.

**Comment by Mu-Zhou** [comment]
@gt945 thanks, it works.
but when i run code-oss, it says
>  (code-oss:8101): Gtk-WARNING **: 23:26:25.246: cannot open display:

**Comment by JL2210** [comment]
That's normal. You have to run `sommelier -X code-oss`.

**Comment by Mu-Zhou** [comment]
wow, it turned on but the window is blurry, can i do something to fix it?

**Comment by JL2210** [comment]
change `SCALE` in `~/.bashrc`.

**Comment by Mu-Zhou** [comment]
@JL2210 Thanks for you help.
I can`t find the exact way to set the environment variable, How should I write in the file, could you give me an example

**Comment by JL2210** [comment]
Run 'nano ~/.bashrc' and change 'SCALE=1' to 'SCALE=<some number here>'
until it works.
