### ISSUE TITLE
running `exit` crashes chrome

### ISSUE THREAD

**Issue by Merith-TK** [skycocker/chromebrew#3245]
## Description
Installed xterm, which installed sommelier, when i run 
If you executed a specific command:
```shell
chronos@localhost ~ $ sommelier -X xterm
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
Warning: Cannot convert string "-adobe-helvetica-bold-r-normal--*-120-*-*-*-*-iso8859-*" to type FontStruct
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
```
Xterm loads, but when i exit xterm, it crashes hard (entire system,)

## Versions and system information
chromebrew: `1.2.3`

ChromeOS: `CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C776D42E-287A-435E-8BA7-E770BD30B46D}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C776D42E-287A-435E-8BA7-E770BD30B46D}
CHROMEOS_RELEASE_BOARD=x86-alex_he-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=72
CHROMEOS_RELEASE_BUILDER_PATH=x86-alex_he-release/R58-9334.72.0
CHROMEOS_RELEASE_BUILD_NUMBER=9334
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=58
CHROMEOS_RELEASE_DESCRIPTION=9334.72.0 (Official Build) stable-channel x86-alex_he 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9334.72.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9334.72.0`

Model: XE500C21

Architecture: `i686`

**Comment by uberhacker** [comment]
Thank you for letting us know about your issue.  It is difficult to support gui apps on i686 since the latest official release is 59.  Google has stopped supporting i686 systems and we can only provide limited support for cli apps in Chromebrew.  We mention this on the [project homepage](https://github.com/skycocker/chromebrew).

**Comment by Merith-TK** [comment]
I am aware. I figured that I should at least contact support before I give
up.

I am reinstalling chromebrew and trying again now. Give me a short bit and
I shall reinstall it to try again with a fresh setup

**Comment by Merith-TK** [comment]
Same issue.
