### ISSUE TITLE
OpenSSL installation prevents secure login

### ISSUE THREAD

**Issue by DanielWagaman** [skycocker/chromebrew#3274]
After installing Chromebrew I set a root password in the dev console as recommended. It was verified and accepted. Then trying to login as chronos failed. 

Then I tried sudo from the shell:

> `shell  sudo chromeos-setdevpasswd`

which prompts for my password. After entering the correct password it outputs:

> `openssl: symbol lookup error: openssl: undefined symbol: RC5_32_set_key`

This leaves no way to login as chronos. After some googling I found a crouton discussion of the [same error trying to encrypt a chroot](https://github.com/dnschneid/crouton/issues/3738). Uninstalling openssl allows secure login. 

chromebrew: 1.2.3

ChromeOS: CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5506735
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={40C6BCAB-B8D4-466F-9C3C-069B8CAC36D7}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={40C6BCAB-B8D4-466F-9C3C-069B8CAC36D7}
CHROMEOS_RELEASE_BOARD=lulu-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=95
CHROMEOS_RELEASE_BUILDER_PATH=lulu-release/R74-11895.95.0
CHROMEOS_RELEASE_BUILD_NUMBER=11895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=74
CHROMEOS_RELEASE_DESCRIPTION=11895.95.0 (Official Build) stable-channel lulu 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11895.95.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11895.95.0

Model: Dell Chromebook 13 7310 - Lulu

Architecture: x86_64

**Comment by JL2210** [comment]
I think we can enable this by passing rc5 to OpenSSL's Configure. It's
disabled by default because it's insecure, but it's still used a lot.

**Comment by uberhacker** [comment]
@DanielWagaman: Thank you for reporting this issue.  It appears sudo is attempting to run /usr/bin/openssl instead of /usr/local/bin/openssl.  Yes, the system version is what throws the error, not the the crew version so we don't need to change anything in the config.  What you need is to do is pass `PATH=/usr/local/bin:$PATH` to the environment to make sure the crew version executes instead.

**Comment by DanielWagaman** [comment]
@uberhacker This might be a product of my inexperience but that didn't resolve the issue. I added `PATH=/usr/local/bin:$PATH` to `~/.bashrc` and when that didn't work I also added it to `~/.bash_profile`. While openssl is installed in crew I still get undefined symbol error. 

Questions:
1) Did I misunderstand your instructions to pass the path to the environment? 
2) Is updating the path SOP and I missed it in the installation instructions? If so perhaps this isn't an issue for others and this could be closed. 
3) Uninstalling crew's openssl solved the problem. What problems, if any, does it create?

**Comment by uberhacker** [comment]
Hey @DanielWagaman: I think the issue is when you use sudo, it uses the root user environment instead of chronos.  Apparently, the root user environment is missing `/usr/local/bin` in `$PATH`.

**Comment by JL2210** [comment]
Try adding /usr/local/lib64 to LD_LIBRARY_PATH.

**Comment by JL2210** [comment]
Along with that, we can add the rc5 algorithm to the OpenSSL package we
currently have as the passwd program apparently uses it.

**Comment by DanielWagaman** [comment]
@JL2210  As I mentioned `export PATH=/usr/local/bin:$PATH` definitely worked. That change is also mentioned as a fix in the comments of a top google hit for "[python on Chromebook](https://wsvincent.com/install-python3-chromebook/)" I'm guessing the path change is common requirements on chromebooks in dev mode. Is the simplest solution to add path change instructions on the installation page? 

Also, is it time to close this as resolved or should I leave it open?

**Comment by JL2210** [comment]
Leave it open until we enable rc5. It would be best to maintain
compatibility with system versions of OpenSSL.

**Comment by uberhacker** [comment]
@JL2210: The problem is not with the crew version of openssl.  The issue is with the system version (`/usr/bin/openssl`).   We don't need to change anything.  @DanielWagaman: The path addition is what forces `/usr/local/bin/openssl` over `/usr/bin/openssl` which hopefully, is all you need to fix that error.

**Comment by JL2210** [comment]
We need to maintain compatibility with system-provided libraries or bad
things will happen like segmentation faults. Remember when Chrome OS 62
came out?

**Comment by uberhacker** [comment]
Well, considering his error was due to the system provided openssl, I think that is out of our control.  Why would a system provided executable not work with system provided libraries?
