### ISSUE TITLE
Why do we have pkg_config and pkgconfig?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#328]
There are two versions of the same package?  Am I missing something here?  Shouldn't we only have one with the latest available stable version?

**Comment by lyxell** [comment]
@thedamian

**Comment by uberhacker** [comment]
@lyxell: You pointing fingers? LoL

**Comment by lyxell** [comment]
:)

**Comment by uberhacker** [comment]
https://github.com/skycocker/chromebrew/issues/344#issuecomment-271133351

**Comment by thedamian** [comment]
Oh absolutely. If there was already a pkg-confit they I did a boo boo.

I'll delete it if it's the same.

**Comment by uberhacker** [comment]
@thedamian: Before you delete `pkg_config`, make sure there are no other packages that currently depend on it.  If there are any, those will need to be converted over to use `pkgconfig` instead (if necessary).  We had a situation with `openssl_devel` after it was removed from the repo.  See #335.

**Comment by uberhacker** [comment]
Can we close out this issue?
