### ISSUE TITLE
[gcc7] checksum mismatch

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#3301]
## Description
Trying to install gcc7 on aarch64 brings to 'Checksum mismatch'

## Versions and system information
chromebrew: 1.2.4

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5608800
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_RELEASE_BOARD=elm-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=elm-release/R75-12105.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.53.0 (Official Build) beta-channel elm 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=12105.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.53.0

Model: Acer Chromebook R13 and ASUS Chromebook Flip C101PA

Architecture: aarch64

**Comment by uberhacker** [comment]
@blu: From our wiki:
```
Q: I'm having miscellaneous errors when installing packages on the beta, dev, or canary channels. What do I do?

A: Installing Chromebrew on the beta, dev, or canary channels is NOT supported. Revert back to the stable channel and try again.
```
That said, is there a particular reason you need gcc7 instead of gcc8?

**Comment by blu** [comment]
Just for some regression performance testing, not the biggest of concerns. But the beta channel shouldn't be a problem in this case, no?

**Comment by uberhacker** [comment]
It probably depends on the magnitude of the change.  For instance, when we had the upgrade from glibc 2.23 to 2.27, there was a time the beta and stable channels had different versions and the effect was global to everything working or not.

**Comment by blu** [comment]
I remember that time -- that was easy to workaround on the beta channel. I had all links under `/usr/local/lib/` patched out to the correct versions under `/usr/lib` and all crew packages I used were working correctly. Actually, I should still have this setup on one of my chromebooks to this day (crew not updated in a long time there).

But my question was different -- I meant that the checksum mismatch for gcc7 should not be affected by beta, no?

**Comment by uberhacker** [comment]
Right, if the mismatch is on beta, it should also be on stable.  I'll see if I can fix both of these checksum issues for aarch64 (gdb and gcc7).  Gotta wait for the day job to end ... zzz.
