### ISSUE TITLE
[gdb] missing dependency lib

### ISSUE THREAD

**Issue by blu** [skycocker/chromebrew#3302]
## Description
Installing gdb (v8.2.1) on aarch64 results in a missing library:

```shell
$ ldd `which gdb`
        libreadline.so.7 => not found
        libz.so.1 => /usr/local/lib/libz.so.1 (0xee6ee000)
        libncursesw.so.6 => /usr/local/lib/libncursesw.so.6 (0xee685000)
        libdl.so.2 => /usr/local/lib/libdl.so.2 (0xee672000)
        libpython2.7.so.1.0 => /usr/local/lib/libpython2.7.so.1.0 (0xee492000)
        libpthread.so.0 => /usr/local/lib/libpthread.so.0 (0xee46d000)
        libutil.so.1 => /usr/local/lib/libutil.so.1 (0xee45a000)
        libm.so.6 => /usr/local/lib/libm.so.6 (0xee3d9000)
        libexpat.so.1 => /usr/local/lib/libexpat.so.1 (0xee39c000)
        liblzma.so.5 => /usr/local/lib/liblzma.so.5 (0xee36c000)
        libmpfr.so.6 => /usr/local/lib/libmpfr.so.6 (0xee2fe000)
        libc.so.6 => /usr/local/lib/libc.so.6 (0xee201000)
        /lib/ld-linux-armhf.so.3 => /usr/local/lib/ld-linux-armhf.so.3 (0xee71b000)
        libgcc_s.so.1 => /usr/local/lib/libgcc_s.so.1 (0xee1d1000)
        libgmp.so.10 => /usr/local/lib/libgmp.so.10 (0xee164000)```
```
## Versions and system information
chromebrew: 1.2.4

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5608800
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={564AC308-CBD5-485D-9EF5-EB97DBB5F264}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={564AC308-CBD5-485D-9EF5-EB97DBB5F264}
CHROMEOS_RELEASE_BOARD=bob-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=bob-release/R75-12105.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.53.0 (Official Build) beta-channel bob 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=12105.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.53.0

Model: ASUS Chromebook Flip C101PA

Architecture: aarch64

**Comment by uberhacker** [comment]
@blu: From our wiki:
```
Q: I'm having miscellaneous errors when installing packages on the beta, dev, or canary channels. What do I do?

A: Installing Chromebrew on the beta, dev, or canary channels is NOT supported. Revert back to the stable channel and try again.
```
That said, we need to recompile the gdb binaries to fix the readline issue but you still should be able to compile from source on the stable channel.

**Comment by JL2210** [comment]
Just requires an update. Try installing from source after installing
readline8.

**Comment by uberhacker** [comment]
@JL2210: His architecture is aarch64 so the binaries are important in this case.  He may not be able to compile from source.

**Comment by JL2210** [comment]
Nah, that's only for weird configure scripts. GNU configure doesn't do that.

**Comment by uberhacker** [comment]
Apparently, you have never attempted to compile on aarch64 architecture.

**Comment by JL2210** [comment]
If you want to know if it works, ask @blu, because, apparently, you don't
own an aarch64 chromebook.

**Comment by uberhacker** [comment]
Typical only child response.  As a matter of fact, I do own an aarch64 Chromebook and you should already know that compiling on aarch64 is not straightforward.

**Comment by JL2210** [comment]
@uberhacker I don't appreciate you discriminating against me because I'm an only child. I am not saying that compiling on aarch64 is straightforward. Please test my suggestion and see if it works.

**Comment by skiman6010** [comment]
On x86_64 beta.
```
$ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5608800
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=samus-release/R75-12105.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.53.0 (Official Build) beta-channel samus 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=12105.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.53.0
```

```
$ ldd `which gdb`
        linux-vdso.so.1 (0x00007ffef0754000)
        libreadline.so.7 => /usr/local/lib64/libreadline.so.7 (0x00007f7b97676000)
        libz.so.1 => /usr/local/lib64/libz.so.1 (0x00007f7b97281000)
        libncursesw.so.6 => /usr/local/lib64/libncursesw.so.6 (0x00007f7b97013000)
        libdl.so.2 => /usr/local/lib64/libdl.so.2 (0x00007f7b96e0f000)
        libpython2.7.so.1.0 => /usr/local/lib64/libpython2.7.so.1.0 (0x00007f7b96bef000)
        libpthread.so.0 => /usr/local/lib64/libpthread.so.0 (0x00007f7b969d1000)
        libutil.so.1 => /usr/local/lib64/libutil.so.1 (0x00007f7b967ce000)
        libm.so.6 => /usr/local/lib64/libm.so.6 (0x00007f7b9646f000)
        libexpat.so.1 => /usr/local/lib64/libexpat.so.1 (0x00007f7b97640000)
        liblzma.so.5 => /usr/local/lib64/liblzma.so.5 (0x00007f7b9624a000)
        libmpfr.so.6 => /usr/local/lib64/libmpfr.so.6 (0x00007f7b95fcf000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007f7b95c16000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007f7b9749e000)
        libgmp.so.10 => /usr/local/lib64/libgmp.so.10 (0x00007f7b975c7000)
```

**Comment by blu** [comment]
Just to report that the official `readline-8.0` configures and builds out of the box without hassle on aarch64 -- it does not attempt to pass any fancy target options to the host gcc, so the aarch64 cros kernel/userland combo does not cause issues as in other cases.

Regardless, the shortest workaround to getting gdb functional on aarch64 in its current form is
`ln -s /usr/local/lib/libreadline.so.8 /usr/local/lib/libreadline.so.7` -- the version of libreadline provided by the respective crew package is not the one gdb seeks.
