### ISSUE TITLE
vscode - no extensions available

### ISSUE THREAD

**Issue by darkoverlordofdata** [skycocker/chromebrew#3303]
When I run VSCode, there are no extensions listed in the Extension View, Under Popular it shows 'no extensions found;

You can also access the marketplace by entering ctrl-P and pasting into the command window
```shell
ext install vector-of-bool.cmake-tools
```

Notification:
```shell
no extension gallery service configured
```

chromebrew: 1.2.4

ChromeOS: No such file or directory; 74.4.58 (Developer Build - neverware) stable-channel chromeover64

Model: Dell Inspiron 15 3521

Architecture: x86_64

**Comment by uberhacker** [comment]
@darkoverlordofdata: From the [wiki](https://github.com/skycocker/chromebrew/wiki/FAQ):
```
Q: I don't see any extension in code's Marketplace. What do I do?

A: The Marketplace must be activated by hand by adding the following information to /usr/local/share/code/resources/app/product.json:

"extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
}
```

**Comment by darkoverlordofdata** [comment]
Thanks. I read 'codes Marketplace' and thought it was a reference to the website. I got confused ;)
