### ISSUE TITLE
New package manifest proposal

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#332]
Hey guys,
What are your thoughts on creating a manifest of all the installed packages?  Basically, the idea is to store metadata about each package such as name, description, version, etc.  It would be kind of like `package.rb` but more human-readable and include data about every installed package.  I was thinking it would be nice to be able to list all the packages and a short description (for mere mortals).  I thought about maybe adding the description to each package but then you would need to parse each package everytime you wanted information.  Storing it all in one file would be more efficient.
Thanks

**Comment by minektur** [comment]
We could just insert that information as some kind of tag or string in each
package.... and then somehow display that on demand... I haven't looked at
the code - how do we decide if somehting is already installed now?

Presumably you would want this to have the actual info for the actually
installed version so that if you updated crew and it's packages that the
information would still be correct - we'd need to store it at package
install time.   Stash it in a single file?  it would probably be easier to
make a 3rd manifest file for each package (right now we have a file list
manifest and a directory list manifest )...

It seems like a good idea to me.

**Comment by lyxell** [comment]
Right now we are populating a json-file: `/usr/local/etc/crew/device.json`

**Comment by uberhacker** [comment]
@lyxell: This is exactly what I had envisioned.  Not sure how I missed it.  Maybe because I was expecting a file named `packages.json` instead of `device.json`? :)  Do you think it would be difficult to sneak in a short description for each installed package as well?  I imagine if the .rb packages had a description, this would be easier.

**Comment by lyxell** [comment]
@uberhacker Sounds like a good idea to me.

**Comment by thedamian** [comment]
I love it.

who's going to take the lead on this?

I'll volunteer to change our http://skycocker.github.io/chromebrew/ to add a search or just pull from that .json file and list all the packages available and that short description.

**Comment by uberhacker** [comment]
@thedamian: I'll take on the challenge!  The only concern I have is how to handle the transition.  We will need a way to elegantly parse existing packages (that folks have already installed) without a description as well as the new packages with the description.  We could just ask folks to update all their packages but that would be a bit extreme.  Maybe a script that inserts the description into existing packages that don't have one yet?

**Comment by thedamian** [comment]
Yeah. Just create a file and copy the names, and title and descriptions as just the name of the package for now. You push that. I'll merge it right away and then we can either do a couple at a time or I'll make sure NOT to approve anything that doesn't also have their changes on your file. slowly we'll fill it up.

this way also I'll have a file I can pull with my javascript script on that github.io page for now.

**Comment by uberhacker** [comment]
Here's my proposal.  Please let me know if you think there is a better approach.  I will create a packages.json file that contains name, description, homepage, version.  Then I will update the `crew` command to include logic that reads from this file.  We can leave the device info in device.json but eventually remove the packages section once all the .rb files have descriptions.  Does this sound reasonable?

**Comment by lyxell** [comment]
@uberhacker I think it would be more reasonable to have the description in the ruby files.

**Comment by uberhacker** [comment]
See PR #373.  This proposal only adds packages.json and doesn't require any of the .rb files to be updated.  Also, devices.json is untouched and can remain functioning the same way it does currently.  The caveat to make this work is anytime a package is added, updated or removed, packages.json will need to be updated as well.  Maybe we can do this with an update.sh script?

**Comment by uberhacker** [comment]
Not needed since #696, #720 and #723 address this issue.
