### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by jayvdb** [skycocker/chromebrew#3353]
https://github.com/skycocker/chromebrew/issues/997 was the last issue dealing with tests, resulting in manual test instructions at https://github.com/skycocker/chromebrew/wiki/Testing-procedure

To automate them, a reliable docker image of chromeos is needed.

Using docker image [`brunux/chromeos`](https://hub.docker.com/r/brunux/chromeos/) fails due to https://github.com/skycocker/chromebrew/issues/3305#issuecomment-507054309

Is there a better image?

**Comment by jayvdb** [comment]
@jam7 , since you built https://github.com/jam7/dockcross-chromebrew , maybe you can help with this.

**Comment by JL2210** [comment]
@jayvdb, @jam7 hasn't been affiliated with this project in a long time.
