### ISSUE TITLE
lua missing pkgconfig .pc file

### ISSUE THREAD

**Issue by paulwratt** [skycocker/chromebrew#3358]
## Description
The `lua` package in missing the necessary ".pc" file that allows `pkg-config` to generate project compile time information. According to a project `Makefile` script I have (copyright 2018), that ".pc" file can be named any of the following:
```
          LUAPKG := $(shell for p in lua5.3 lua-5.3 lua53 lua5.2 lua-5.2 lua52 lua5.1 lua-5.1 lua51 lua ; do $(PKG_CONFIG) --exists $$p && echo $$p && break ; done)
          LUACOPT = $(shell $(PKG_CONFIG) $(LUAPKG) --cflags)
          LUALOPT = $(shell $(PKG_CONFIG) $(LUAPKG) --libs)
```  

The current version of `lua` is:
```
$ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
```

From the shell, the expected output should be:
```
$ 
```

## Versions and system information
chromebrew: `1.2.4`

ChromeOS:
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_RELEASE_BOARD=veyron_speedy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=75
CHROMEOS_RELEASE_BUILDER_PATH=veyron_speedy-release/R75-12105.75.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.75.0 (Official Build) stable-channel veyron_speedy 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.75.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.75.0
```

Model: `Asus CP201`

Architecture: `armv7l`

## Addtional information
`luajit` is also provided, but it ONLY works with `lua-5.1`.

What I think needs to be done:
- [ ] step one: change current `lua` package name to `lua-5.3` or `lua53`
- [ ] step two: ensure `lua-5.3.pc` or `lua53.pc` is generated into `./lib/pkgconfig/`
- [ ] step three: add Lua version 5.1 and 5.2 to the package repository

Example `lua53.pc` generation:
```
$ cat > lua53.pc << "EOF"
V=5.3
R=5.3.5

prefix=/usr/local
INSTALL_BIN=${prefix}/bin
INSTALL_INC=${prefix}/include
INSTALL_LIB=${prefix}/lib
INSTALL_MAN=${prefix}/share/man/man1
INSTALL_LMOD=${prefix}/share/lua/${V}
INSTALL_CMOD=${prefix}/lib/lua/${V}
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${R}
Requires:
Libs: -L${libdir} -llua53 -lm -ldl
Cflags: -I${includedir}
EOF
```

Cheers

Paul

**Comment by cstrouse** [comment]
@uberhacker @paulwratt I don't have a problem breaking lua up into multiple packages. I'll work on this if you guys think it's a good idea and no one else is working on it.

**Comment by uberhacker** [comment]
Go for it!
