### ISSUE TITLE
No Audio in Programs Compiled from Source

### ISSUE THREAD

**Issue by KaehLikeTheLetterK** [skycocker/chromebrew#3373]
Hi guys. I've been trying to solve this for a while (currently with snes9x) and I've failed to get audio working on programs compiled inside ChromeOS.

After installing chromebrew, `aplay` broke until I bind mounted `/usr/lib/lib-alsa` to `/usr/local/lib/lib-alsa`. Since then, it's worked just fine, and so has `mpg123`, but graphical apps fail to output any sound.

The error message I see is:
```
ERROR: Failed to open sound device /dev/dsp for writing.
  (Try loading snd-pcm-oss module?)
```

However, snes9x comes with a command-line function for specifying a different audio device, and so I used `/dev/input/event1`, and `/dev/i2c-0`/1/2/4, and still nothing.

This is only present in chromebrew programs installed with `crew`, or in programs compiled with chromebrew (e.g. jar files using the armv7h jdk I placed in `/usr/local/java` work fine)

Not sure if the following info is needed, but I'll provide it anyway:

crew version: `1.2.4`
lsb-release:
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5563251
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={87C6D674-9385-6143-BE67-8B5E3064E89D}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={87C6D674-9385-6143-BE67-8B5E3064E89D}
CHROMEOS_RELEASE_BOARD=veyron_jerry-signed-mp-v12keys
CHROMEOS_RELEASE_BRANCH_NUMBER=118
CHROMEOS_RELEASE_BUILDER_PATH=veyron_jerry-release/R74-11895.118.0
CHROMEOS_RELEASE_BUILD_NUMBER=11895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=74
CHROMEOS_RELEASE_DESCRIPTION=11895.118.0 (Official Build) stable-channel veyron_jerry 
CHROMEOS_RELEASE_KEYSET=mp-v12
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11895.118.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11895.118.0
```
uname -m: `armv7l`

My rootfs is 4GB instead of 2, and RW. I'm not afraid to make changes to it if necessary, since I can easily reflash the original rootfs image if it breaks.

Thanks in advance!

**Comment by uberhacker** [comment]
@KaehLikeTheLetterK: Thank you for the feedback.  Which gui apps have you tried?  The audacious package should work using the ALSA plugin.  You might try installing the cras package if you haven't already.  That helps with sound.

**Comment by KaehLikeTheLetterK** [comment]
I tried audacious about a week ago; It didn't output any sound then, either. This has been an ongoing issue (I'm assuming only with my device, for some reason?) for the last few months.

I'll try using cras and see if that helps.

**Comment by KaehLikeTheLetterK** [comment]
It seems like Audacious has it's own set of issues now

```
ERROR plugin.cc:312 [init]: Unknown or unsupported transport “disabled” for address “disabled:”
WARNING plugin-init.cc:102 [start_plugin]: MPRIS 2 Server failed to start.
```
It didn't launch. Nor does snes9x output sound; (still searching for /dev/dsp. Is there a way to create a virtual /dev/dsp?)

**Comment by uberhacker** [comment]
To get audacious working, you need to follow the postinstall steps.  Try `crew postinstall audacious` and see if configuring the ALSA plugin works.

**Comment by KaehLikeTheLetterK** [comment]
Audacious is now outputting sound. Progress! I had to perform a full chromebrew reinstall to get it to launch, but that aside, it's working now. Where am I supposed to point non-crew programs?

**Comment by uberhacker** [comment]
What do you mean by non-crew programs?

**Comment by KaehLikeTheLetterK** [comment]
Again, like snes9x. It complains about not having `/dev/dsp` and I have no idea where to point it for audio output. DeSmuME also complains.

**Comment by uberhacker** [comment]
Closed since not relevant to Chromebrew.
