### ISSUE TITLE
Update the toolchains

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#338]
Hi,

I'm preparing new toolchains for all architectures using cross compile and created a repository at https://github.com/jam7/chrome-cross.  Current toolchains for armv7l is compiled by this.  I've tested this toolchains on x86_64 too recently.  I've prepared toolchains for x86 also, but it is not tested.  I appreciate if people try this out and let me know problems.

I also made a branch at https://github.com/jam7/chromebrew/tree/newgcc for the ease of try.  You can try it by
```
wget -q -O - https://raw.github.com/jam7/chromebrew/newgcc/install.sh | bash
```
or you can compile all from the source codes using above chrome-cross.

In addtion, this solves: ldconfig problem (#171), rpath problem partially since all binaries are compiled with correct rpath (#49, #103), ldd not working problem
This doesn't solve: lib or lib64 problem
Known problem: none currently

Thanks.

**Comment by lyxell** [comment]
Great work Jam!

**Comment by ryanpcmcquen** [comment]
Thank you so much for doing this!

I am getting an error on download though:
```
--2017-02-12 16:17:29--  (try:18)  https://raw.githubusercontent.com/jam7/chromebrew/newgcc/packages/gcc.rb
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 711 [text/plain]
Saving to: 'gcc.rb'

gcc.rb                                100%[======================================================================>]     711  --.-KB/s    in 0s      

2017-02-12 16:17:29 (67.9 MB/s) - Read error at byte 822/711 ((null)). Retrying.
```

**Comment by jam7** [comment]
Thank you for your try!

I guess you tried use install.sh over existing chromebrew environment.  Please remove your existing gcc.rb.  Current version of install.sh doesn't overwrite those package files when it writes new package file to /usr/local/lib/crew/packages/gcc.rb.  So, it writes only 771 bytes (new length) into 822 bytes (old length) then is confused.

You can do following steps also.

1. Overwrites all necessary package files by hand.
   `for i in binutils cloog gcc glibc gmp isl linuxheaders mpc mpfr; do wget https://raw.githubusercontent.com/jam7/chromebrew/newgcc/packages/$i.rb -O /usr/local/lib/crew/packages/$i.rb; done`
2. Upgrade by `crew upgrade`
3. If you want to revert to original gcc, `crew update; crew upgrade`

**Comment by ryanpcmcquen** [comment]
Thank you! Getting a new error on `crew upgrade`.

```
chronos@localhost / $ for i in binutils cloog gcc glibc gmp isl linuxheaders mpc mpfr; do wget https://raw.githubusercontent.com/jam7/chromebrew/newgcc/packages/$i.rb -O /usr/local/lib/crew/packages/$i.rb; done

...

2017-02-12 17:29:22 (58.4 MB/s) - '/usr/local/lib/crew/packages/linuxheaders.rb' saved [601/601]

--2017-02-12 17:29:22--  https://raw.githubusercontent.com/jam7/chromebrew/newgcc/packages/mpc.rb
Resolving raw.githubusercontent.com... 151.101.40.133
Connecting to raw.githubusercontent.com|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 566 [text/plain]
Saving to: '/usr/local/lib/crew/packages/mpc.rb'

/usr/local/lib/crew/packages/mpc.rb   100%[======================================================================>]     566  --.-KB/s    in 0s      

2017-02-12 17:29:22 (61.4 MB/s) - '/usr/local/lib/crew/packages/mpc.rb' saved [566/566]

--2017-02-12 17:29:22--  https://raw.githubusercontent.com/jam7/chromebrew/newgcc/packages/mpfr.rb
Resolving raw.githubusercontent.com... 151.101.40.133
Connecting to raw.githubusercontent.com|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 570 [text/plain]
Saving to: '/usr/local/lib/crew/packages/mpfr.rb'

/usr/local/lib/crew/packages/mpfr.rb  100%[======================================================================>]     570  --.-KB/s    in 0s      

2017-02-12 17:29:22 (51.3 MB/s) - '/usr/local/lib/crew/packages/mpfr.rb' saved [570/570]

chronos@localhost / $ crew upgrade
/usr/local/bin/crew:434: syntax error, unexpected tSTRING_BEG, expecting end-of-input
```

**Comment by jam7** [comment]
@ryanmjacobs Sorry for saying this, but I guess your chromebrew environment is already flushed at first execution of `install.sh` over existing chromebrew environment.

You can fix current situation be following steps, but it is required to install all packages you are using again.

1. Revert crew to original
   `wget https://raw.githubusercontent.com/skycocker/chromebrew/master/crew -O /usr/local/lib/crew/crew`
1. Revert package.rb to original
   `wget https://raw.githubusercontent.com/skycocker/chromebrew/master/lib/package.rb -O /usr/local/lib/crew/lib/package.rb`
1. Check your crew (nothing installed I guess)
   `crew search`
1. If it works, revert to original first
   `crew update`
1. Overwrites all necessary package files by hand.
   `for i in binutils cloog gcc glibc gmp isl linuxheaders mpc mpfr; do wget https://raw.githubusercontent.com/jam7/chromebrew/newtoolchains/packages/$i.rb -O /usr/local/lib/crew/packages/$i.rb; done`
1. Performs git installation
   `crew install git`
1. Upgrade by `crew upgrade`
1. Test newtoolchains
1. If you want to revert to original gcc, `crew update; crew upgrade`

**Comment by ryanpcmcquen** [comment]
Thank you, I will try it. FYI, I am @ryanpcmcquen, not `ryanmjacobs`.

**Comment by jam7** [comment]
oh, sorry about that

2017年2月13日(月) 11:11 Ryan P.C. McQuen <notifications@github.com>:

**Comment by jam7** [comment]
Closing since #461 is merged.  Thank you for your help.
