### ISSUE TITLE
Uninstall chromebrew

### ISSUE THREAD

**Issue by TheElf01** [skycocker/chromebrew#3439]
Hi,  i did not spected it will take soo much HDD space.  Of course install failed in some point because im out of space in my chromebook

The chromebrew website did not say how much MB will take...

How can i uninstall? or i need to remove by hand every file? 

I read using 

rm -rf /usr/local

But i dont know if i will remove other ChromeOS files?¿ because before install chromebrew i think there was some files in /usr/local  ...

thanks a lot

**Comment by JL2210** [comment]
The only files that were in `/usr/local` before the install will be recreated if necessary. It's fine to run `rm -rf /usr/local`.

**Comment by cstrouse** [comment]
Closing. Not an issue.
