### ISSUE TITLE
New release long overdue?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#345]
Do you think we're about ready for another tagged release?  The latest release is from Jun 8, 2015. :)

**Comment by thedamian** [comment]
Release of what?

**Comment by uberhacker** [comment]
https://github.com/skycocker/chromebrew/releases

**Comment by thedamian** [comment]
I do agree. 

What do you guys think of a version 0.40

https://github.com/skycocker/chromebrew/releases/

**Comment by uberhacker** [comment]
If you type `crew` you get:
```
Chromebrew, version 0.2.2
```
If we do release version 0.40, we better update the crew command before tagging the release.

**Comment by jam7** [comment]
@thedamian nice.  now it's possible to put all dropbox binaries to that page if we would like to do.

In addition, adding reference to #268

**Comment by cstrouse** [comment]
Also see #313

**Comment by uberhacker** [comment]
Can we close out this issue?
