### ISSUE TITLE
Reminder: OpenSSL 1.0.2 is to be deprecated at the end of December

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#3463]
OpenSSL 1.0.2 is to be deprecated at the end of December. We should start upgrading our packages to the newer versions.

Some updates:

* curl has released a new version and should only require an update and a rebuild.

* PHP 5.6 has OpenSSL 1.1 support updates [here](https://github.com/microsoft/php-src/tree/PHP-5.6-security-backports-openssl11).

* I can help find any others that need updates.

Also note that [1.0.2t should not be installed yet](https://github.com/openssl/openssl/issues/7679#issuecomment-531591284).

**Comment by uberhacker** [comment]
Thanks for the reminder @JL2210.  Can you please do some research and find all the packages that this update could affect and list them on this issue?  Also, we need to make sure this doesn't break the core packages and therefore kill the install process.

**Comment by JL2210** [comment]
This will require immediate rebuilds (as in included in the PR for the update) so it'll be a little difficult, but I'll see what I can do.

**Comment by JL2210** [comment]
Core packages that need to be rebuilt with update:

* cmake
* curl
* libssh2
* libunbound

Working on updates to the last two.

**Comment by cstrouse** [comment]
Is there any reason we can't start using `libressl` instead? I have a package in my fork for it and seems to work great with the packages I use regularly.

**Comment by uberhacker** [comment]
I don't see why not if it doesn't break anything.

**Comment by JL2210** [comment]
It's a fork of OpenSSL that may not bring the latest updates... I generally try to stay away from forks of anything.

**Comment by JL2210** [comment]
On second thought, look at the backwards compatibility percentage for the "latest and greatest version":

![Screenshot 2019-10-23 at 11 49 01 PM](https://user-images.githubusercontent.com/38843657/67452016-0a94f080-f5f0-11e9-9ee4-89b2286dba69.png)

A big, whopping goose egg.

**Comment by JL2210** [comment]
@cstrouse Looks great, considering openssl 1.1.1 won't even build correctly.
