### ISSUE TITLE
[Question]  Any Virtual PC software?

### ISSUE THREAD

**Issue by TheElf01** [skycocker/chromebrew#3479]
Hi, is possible to install a virtual pc software, like virtualbox?  i tried qemu but is not usable, super slow and with mouse problems

thanks a lot

**Comment by uberhacker** [comment]
@TheElf01: Unless you have a Chromebook with at least 8 gb of RAM, any kind of VM software will be sluggish.  But no, qemu is the only package we have currently.

**Comment by cstrouse** [comment]
You can run software in containers if you don't need to emulate another hardware platform.

**Comment by TheElf01** [comment]
> @TheElf01: Unless you have a Chromebook with at least 8 gb of RAM, any kind of VM software will be sluggish. But no, qemu is the only package we have currently.

thanks, sad news

Funny thing is my old  1999 PowerBook Lombard,  PowerPC G3 400mhz, 192mb ram, Virtual PC 7,  run Windows NT4 perfect,   similar to use in a pentium 120

I can do all my windows works there without problem

But same NT4 in a qemu in a modern intel CPU, 2Gb ram, is sluggish like hell...   not usable at all

**Comment by JL2210** [comment]
@TheElf01 What kind of software are you using? There may be a free software equivalent that doesn't require a VM.

**Comment by TheElf01** [comment]
> 
> 
> @TheElf01 What kind of software are you using? There may be a free software equivalent that doesn't require a VM.

Is a software to control robots in a factory, propietary ode,  it works on windows 3.1, is just 16bits old good code,  just a 384kb exe that controls a 250k usd robot jaja

Qemu is just too slow, the software is not usable,  my old Powerbook 400mhz with VirtualPC works great

**Comment by TheElf01** [comment]
Hi,   I use same thread to do a question,  anyone succeed or try to compile DosBox on Chromebrew?

thanks

**Comment by uberhacker** [comment]
@TheElf01:  Have you tried `freedos` yet?

**Comment by JL2210** [comment]
It compiles, but doesn't run.

**Comment by TheElf01** [comment]
> 
> 
> @TheElf01: Have you tried `freedos` yet?

I dont know why i will need freedos on the chromebook, i dont understand your question, thanks

> 
> It compiles, but doesn't run.

How did you compile? what verson? I tried and i always get error,   plain dosbox 0.74 and latest devel, that have proper support to 64bits

thanks!

**Comment by JL2210** [comment]
DOSBox doesn't work anyway, don't bother with it. There's a FreeDOS package
in Chromebrew as a VM for QEMU.
