### ISSUE TITLE
Average space taken by a basic chromebrew install?

### ISSUE THREAD

**Issue by kirbyfan64** [skycocker/chromebrew#348]
Considering the fact that a lot of Chrome OS devices/USB sticks don't necessarily have huge amounts of disk space, it would be helpful to have a rough estimate of how much space it takes to install chromebrew.

**Comment by kirbyfan64** [comment]
Beeeeep...

**Comment by minektur** [comment]
Your original request was sent less than 24 hours ago.  Have patience.

Making a rough estimate of the default install would be simple, by just
checking disk space before and after the install - and it could be put on
the website/readme - someone will probably get around to this eventually...

How about you make the estimate by checking available space before and
after a base install and I'll submit a PR for adding your number to the
readme and web site?

**Comment by lyxell** [comment]
@kirbyfan64
Without any extra packages (buildessential, ruby, git and dependencies):
x86_64 and i686 - ~250 mb
arm - ~150 mb

**Comment by lyxell** [comment]
I'll keep this issue open for discussion on whether the disk usage should be put in the README.
