### ISSUE TITLE
[ghc] checksum mismatch once again

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3511]
This package needs to be modified to use something other than the checksum of the webpage since that's a moving target that's constantly changing. Any ideas?

```
chronos@localhost / $ crew install cabal
cabal: Common Architecture for Building Applications and Libraries
https://www.haskell.org/cabal/
version 2.2.0.0
The following packages also need to be installed: 
ghc 
Do you agree? [Y/n] y
Proceeding...
ghc: The Glasgow Haskell Compiler is a state-of-the-art, open source compiler and interactive environment for the functional language Haskell.
https://www.haskell.org/ghc/
version 8.4.2
No precompiled binary available for your platform, downloading source...
-=#=-#    #     #                                                                                                        
Checksum mismatch. :/ Try again.
```

**Comment by uberhacker** [comment]
This package probably needs updated anyway.  Did you want to submit a PR @cstrouse?

**Comment by cstrouse** [comment]
I just updated it to the latest version. The problem is that they are constantly changing text on the homepage and we shouldn't be using that as the source file to download. What should we use instead? Something that doesn't change would be like:

```https://downloads.haskell.org/~ghc/8.8.1/ghc-8.8.1-src.tar.xz.sig```

**Comment by uberhacker** [comment]
@cstrouse: That file looks like an excellent candidate.  You could also download the source but that would be overkill just to throw it away.

**Comment by vincowl** [comment]
pandoc, ghc and cabal have been upgraded. No binary available at the moment, but does it solve the problem ?

**Comment by vincowl** [comment]
Please have a look at the related PRs and issues : ghc cannot be upgraded to 8.8.1 due to slack incompatibility

**Comment by saltedcoffii** [comment]
Ghc no longer has binary packages, this can be closed @uberhacker
