### ISSUE TITLE
Several packages in core list appear to be missing on a fresh install

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3558]
I did a fresh install a few days ago and when going to install `mandb` noticed that `gdbm` and `libpipeline` were missing even though they are supposed to be included as core packages.

@uberhacker Is the core list hand generated or automatically generated?

**Comment by uberhacker** [comment]
No, that is a static list but can be generated after a fresh install with `crew list installed`.  We've updated several core packages recently so that would probably explain it.  Thank you for noticing!

**Comment by JL2210** [comment]
Yay! Reducing the dependencies needed to install!

**Comment by cstrouse** [comment]
Are `libpipeline` and `gdbm` included in a fresh install for you guys? They're both in the core list but I had to manually install them on my ARM machine after the last reinstall of crew I did. Perhaps the install was interrupted or corrupted somehow but let's make sure that the list is accurate since we've been removing deps from packages quite a bit.

If we're still using that CI setup that someone setup for us maybe we can automatically generate that file when updates are merged?

**Comment by cstrouse** [comment]
@uberhacker I just did a fresh install of crew and ran `crew list installed` and then ran a diff to see what differs between the core packages list under `tools/` and what's actually installed on my machine.

```
chronos@localhost /usr/local/tmp $ diff fresh_install.txt core_packages.txt 
7d6
< cloog
16d14
< gcc8
17a16,17
> gcc8
> gdbm
22a23
> groff
30c31
< libmetalink
---
> libpipeline
42a44,45
> mandb
> manpages
49d51
< osl
63a66
> uchardet
```

As we've been removing dependencies that are on the "core" list during updates we've likely been causing missing dependency problems due to the list not being accurate.

Do we need to add some missing dependencies to packages or do we need to make sure that these packages are being installed in the "core" install?
