### ISSUE TITLE
Upgrade vim to 8.1.2225

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3588]
Vim is actually built against dynamic python3interp, that crashes vim plugins. Upragde to 8.1.2225 resolves this

**Comment by JL2210** [comment]
If you already have a PR that fixes this, don't open issues. That's just sending two emails to the maintainers' accounts instead of one.

**Comment by vincowl** [comment]
I was used to open issues and then create a PR. That's fine to me if you ared used to directly create PRs
