### ISSUE TITLE
Upgrade pulseaudio to 13.0

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3591]
Trying to solve #3582, I have tested what would happen with the latest pulseaudio version. Doesn't help, but since the job is done, I upgrade this package

**Comment by JL2210** [comment]
Solving the issue is as simple as putting `ln -sf /var/run/dbus /usr/local/var/run/dbus` in `~/.bashrc`.

**Comment by JL2210** [comment]
We do need to update `dbus`, though...

**Comment by vincowl** [comment]
Just a little correction : works with `ln -sf /var/run/dbus /usr/local/var/run` in `~/.bashrc`
