### ISSUE TITLE
Anaconda-navigator in miniconda package doesn't  work

### ISSUE THREAD

**Issue by richblack** [skycocker/chromebrew#3599]
## Description
I searched miniconda, and installed Jupyter Notebook and Anaconda navigator with conda and succeed, but can't run from command line.

Usually type jupyter notebook or anaconda-navigator, but it said 

If you executed a specific command:
```shell
jupyter notebook
anaconda-navigator
```
Output:
```shell
bash: anaconda-navigator: command not found
bash: jupyter: command not found
```

## Versions and system information
chromebrew: 1.2.5

ChromeOS: 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=5950196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_RELEASE_BOARD=reef-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=40
CHROMEOS_RELEASE_BUILDER_PATH=reef-release/R78-12499.40.0
CHROMEOS_RELEASE_BUILD_NUMBER=12499
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=78
CHROMEOS_RELEASE_DESCRIPTION=12499.40.0 (Official Build) beta-channel reef 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=12499.40.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12499.40.0

Model: Asus Chromebook C213NA

Architecture: x86_64

## Addtional information
Mention things we might need to know. Like: Currently, the packages that run well are the packages without GUI, I tried to download inkscape and Filezilla, both can't run due to lack of some packages support.

What I think needs to be done:
- [ ] If there is a different way to run a package, maybe write in the package list.
- [ ] Is it possible to build a desktop entry automatically for packages?

**Comment by richblack** [comment]
After the issue submitted, I found a way to run conda, but still doesn't work.

1. I still can't run anaconda navigator by type command from the very outside of terminal, but when the anaconda virtual envoronment activated, the command works.
2. But it looks like there still lack some dependencies so that it won't run.

Please help! thanks!
 
```shell
chronos@localhost /usr/local/share/miniconda3/bin $ source activate root
(base) chronos@localhost /usr/local/share/miniconda3/bin $ anaconda-navigator
Traceback (most recent call last):
  File "/usr/local/share/miniconda3/bin/anaconda-navigator", line 7, in <module>
    from anaconda_navigator.app.main import main
  File "/usr/local/share/miniconda3/lib/python3.7/site-packages/anaconda_navigator/app/main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "/usr/local/share/miniconda3/lib/python3.7/site-packages/anaconda_navigator/utils/__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "/usr/local/share/miniconda3/lib/python3.7/site-packages/qtpy/QtGui.py", line 21, in <module>
    from PyQt5.QtGui import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by richblack** [comment]
Update, after I install mesa, the the lack of libGL fixed, the problem now is that:
```shell
(base) chronos@localhost /usr/local/share/miniconda3/bin $ anaconda-navigator
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.
```
I searched and tried update qt and update conda, but it can't be solved still.

**Comment by skiman6010** [comment]
Haven't tried using the GUI version of anaconda before, but seems like sommelier isn't set up correctly to open X displays. Did you follow the sommlier postinstall instructions? You could also try `sommelier -X anaconda-navigator` as well.

**Comment by richblack** [comment]
Thank you, it is really works! Touching...

**Comment by skiman6010** [comment]
I believe this is solved. If not, please re-open the issue. Thanks!
