### ISSUE TITLE
GitHub projects that need updates

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3601]
- [ ] at_spi2_atk | https://github.com/GNOME/at-spi2-atk/archive/AT_SPI2_ATK_2_34_1.tar.gz | 2.26.1 | 2.34.1
- [ ] at_spi2_core | https://github.com/GNOME/at-spi2-core/archive/AT_SPI2_CORE_2_34_0.tar.gz | 2.26.1 | 2.34.0
- [x] autosetup | https://github.com/msteveb/autosetup/archive/v0.6.9.tar.gz | 0.6.7 | 0.6.9
- [ ] avocado | https://github.com/avocado-framework/avocado/archive/73.0.tar.gz | 67.0 | 73.0
- [ ] aws | https://github.com/aws/aws-cli/archive/1.16.292.tar.gz | 1.16.268 | 1.16.292
- [ ] az | https://github.com/Azure/azure-cli/archive/azure-cli-2.0.77.tar.gz | 2.0.46 | 2.0.77
- [ ] bitpocket | https://github.com/sickill/bitpocket/archive/v0.3.tar.gz | 0.2 | 0.3
- [ ] cf | https://github.com/cloudfoundry/cli/archive/v6.47.2.tar.gz | 6.36.1 | 6.47.2
- [ ] clib | https://github.com/clibs/clib/archive/2.0.0-next.12.tar.gz | 1.8.1 | 2.0.0-next.12
- [ ] cmatrix | https://github.com/abishekvashok/cmatrix/archive/v2.0.tar.gz | 1.2 | 2.0
- [ ] cmus | https://github.com/cmus/cmus/archive/v2.8.0.tar.gz | 2.7.1 | 2.8.0
- [x] codium | https://github.com/VSCodium/vscodium/archive/1.40.2.tar.gz | 1.40.0 | 1.40.2
- [ ] commacd | https://github.com/shyiko/commacd/archive/v1.0.0.tar.gz | 0.4.0 | 1.0.0
- [ ] cronie | https://github.com/cronie-crond/cronie/archive/cronie-1.5.5.tar.gz | 1.5.2 | 1.5.5
- [ ] cros_resize | https://github.com/ethanmad/chromeos-resize/ | 6b01b7 | 5bde8f8
- [ ] cups | https://github.com/apple/cups/archive/v2.3.0.tar.gz | 2.2.8 | 2.3.0
- [x] dart | https://github.com/dart-lang/sdk/archive/2.6.1.tar.gz | 1.24.3 | 2.6.1
- [ ] docbook_xsl | https://github.com/docbook/xslt10-stylesheets/archive//snapshot/2019-10-28.tar.gz | 1.79.2 | 2019-10-28
- [ ] dstat | https://github.com/dagwieers/dstat/archive/v0.7.4.tar.gz | 0.7.3 | 0.7.4
- [ ] dub | https://github.com/dlang/dub/archive/v1.18.0.tar.gz | 1.7.1 | 1.18.0
- [ ] elixir | https://github.com/elixir-lang/elixir/archive/v1.9.4.tar.gz | 1.9.1-1 | 1.9.4
- [ ] enchant | https://github.com/AbiWord/enchant/archive//v2.2.7.tar.gz | 2.2.3 | 2.2.7
- [x] eudev | https://github.com/gentoo/eudev/archive/v3.2.9.tar.gz | 3.2.7 | 3.2.9
- [ ] f3 | https://github.com/AltraMayor/f3/archive/v7.2.tar.gz | 7.1 | 7.2
- [ ] fetch | https://github.com/gruntwork-io/fetch/archive/v0.3.7.tar.gz | 0.1.1 | 0.3.7
- [ ] ffmpegthumbnailer | https://github.com/dirkvdb/ffmpegthumbnailer/archive//2.2.2.tar.gz | 2.2.0-1 | 2.2.2
- [ ] fish | https://github.com/fish-shell/fish-shell/releases/download/3.0.2/fish-3.0.2.tar.gz | 2.7.1-1 | 3.0.2
- [ ] fontforge | https://github.com/fontforge/fontforge/archive//20190801.tar.gz | 20170731 | 20190801
- [ ] fribidi | https://github.com/fribidi/fribidi/archive/v1.0.7.tar.gz | 1.0.1 | 1.0.7
- [ ] fswatch | https://github.com/emcrisostomo/fswatch/archive//1.14.0.tar.gz | 1.11.2 | 1.14.0
- [ ] fuse | https://github.com/libfuse/libfuse/archive/fuse-3.8.0.tar.gz | 2.8.6 | 3.8.0
- [x] fzf | https://github.com/junegunn/fzf/archive/0.19.0.tar.gz | 0.17.3 | 0.19.0
- [ ] gcc | https://github.com/gcc-mirror/gcc/archive/gcc-9_2_0-release.tar.gz | 8.3.0 | 9.2.0
- [ ] get_iplayer | https://github.com/get-iplayer/get_iplayer/archive/v3.23.tar.gz | 3.01 | 3.23
- [ ] gifsicle | https://github.com/kohler/gifsicle/archive/v1.92.tar.gz | 1.89 | 1.92
- [x] git | https://github.com/git/git/archive/v2.24.0.tar.gz | 2.23.0 | 2.24.0
- [ ] git_lfs | https://github.com/git-lfs/git-lfs/archive/v2.9.1.tar.gz | 2.2.1 | 2.9.1
- [ ] glfw | https://github.com/glfw/glfw/archive/3.3.tar.gz | 3.2.1-1 | 3.3
- [ ] glib_networking | https://github.com/GNOME/glib-networking/archive/2.63.1.tar.gz | 2.57.3 | 2.63.1
- [ ] glide | https://github.com/Masterminds/glide/archive/v0.13.3.tar.gz | 0.12.3 | 0.13.3
- [ ] glm | https://github.com/g-truc/glm/archive//0.9.9.6.tar.gz | 0.9.9.3 | 0.9.9.6
- [ ] glog | https://github.com/google/glog/archive/v0.4.0.tar.gz | 0.3.5 | 0.4.0
- [ ] gmime | https://github.com/jstedfast/gmime/archive//3.2.4.tar.gz | 3.2.3 | 3.2.4
- [ ] gnome_docking_library | https://github.com/GNOME/gdl/archive/GDL_3_34_0.tar.gz | 3.28.0-0 | 3.34.0
- [ ] gnome_themes_standard | https://github.com/GNOME/gnome-themes-extra/archive//3.28.tar.gz | 3.27.92-0 | 3.28
- [ ] gox | https://github.com/mitchellh/gox/archive/v1.0.1.tar.gz | 0.4.0 | 1.0.1
- [ ] graphene | https://github.com/ebassi/graphene/archive/1.10.0.tar.gz | 1.8.0 | 1.10.0
- [ ] grive | https://github.com/vitalif/grive2/archive/v0.5.1.tar.gz | 0.5.0-1 | 0.5.1
- [ ] gsettings_desktop_schemas | https://github.com/GNOME/gsettings-desktop-schemas/archive//3.34.0.tar.gz | 3.28.0 | 3.34.0
- [ ] gtk_doc | https://github.com/GNOME/gtk-doc/archive/GTK_DOC_1_32.tar.gz | 1.29 | 1.32
- [ ] gtk_engines_adwaita | https://github.com/GNOME/gnome-themes-extra/archive//3.28.tar.gz | 3.27.92 | 3.28
- [ ] gusb | https://github.com/hughsie/libgusb/archive/0.3.1.tar.gz | 0.2.11-0 | 0.3.1
- [ ] gzsize | https://github.com/bfontaine/gzsize/archive/0.1.4.tar.gz | 0.1.1 | 0.1.4
- [ ] harfbuzz | https://github.com/behdad/harfbuzz/archive/2.6.4.tar.gz | 1.7.6-0 | 2.6.4
- [ ] has | https://github.com/kdabir/has/archive/v1.4.0.tar.gz | 1.1.0 | 1.4.0
- [ ] healthcheck | https://github.com/SimplyLinuxFAQ/health-check-script/archive/v2.0.tar.gz | 1cace5 | 2.0
- [ ] heroku | https://github.com/heroku/cli/archive/v7.35.0.tar.gz | 7.33.3 | 7.35.0
- [ ] hub | https://github.com/github/hub/archive/v2.13.0.tar.gz | 2.4.0 | 2.13.0
- [x] hugo | https://github.com/gohugoio/hugo/archive//v0.60.1.tar.gz | 0.59.1 | 0.60.1
- [ ] ilmbase | https://github.com/openexr/openexr/archive/v2.4.0.tar.gz | 2.3.0 | 2.4.0
- [ ] inxi | https://github.com/smxi/inxi/archive/3.0.37-1.tar.gz | 811a19 | 3.0.37-1
- [ ] ipfs | https://github.com/ipfs/go-ipfs/archive/v0.4.22.tar.gz | 0.4.13 | 0.4.22
- [ ] jfrog | https://github.com/JFrogDev/jfrog-cli-go/archive/1.31.2.tar.gz | 1.23.1 | 1.31.2
- [ ] json2xml | https://github.com/vinitkumar/json2xml/archive/v3.0.0.tar.gz | 2.1.0-1 | 3.0.0
- [ ] jsoncpp | https://github.com/open-source-parsers/jsoncpp/archive/1.9.2.tar.gz | 1.8.4 | 1.9.2
- [ ] julia | https://github.com/JuliaLang/julia/archive/v1.3.0.tar.gz | 1.0.4 | 1.3.0
- [ ] kakoune | https://github.com/mawww/kakoune/archive//v2019.07.01.tar.gz | v2018.09.04 | v2019.07.01
- [ ] kbd | https://github.com/legionus/kbd/archive/v2.2.0.tar.gz | 2.0.4 | 2.2.0
- [ ] kbfsfuse | https://github.com/keybase/kbfs/archive/v2.11.0.tar.gz | 1.0.40 | 2.11.0
- [ ] kbfsgit | https://github.com/keybase/kbfs/archive/v2.11.0.tar.gz | 1.0.40 | 2.11.0
- [ ] kcov | https://github.com/SimonKagstrom/kcov/archive/v37.tar.gz | v36 | v37
- [ ] keybase | https://github.com/keybase/client/archive/v5.0.0.tar.gz | 1.0.40 | 5.0.0
- [ ] kore | https://github.com/jorisvink/kore/archive/3.3.1-release.tar.gz | 2.0.0 | 3.3.1
- [ ] kotlin | https://github.com/JetBrains/kotlin/releases/download/v1.3.61/kotlin-compiler-1.3.61.zip | 1.2.21 | 1.3.61
- [ ] kr | https://github.com/kryptco/kr/archive/2.4.15.tar.gz | 2.4.4 | 2.4.15
- [ ] kubectl | https://github.com/kubernetes/kubernetes/releases/download/v1.16.3/kubernetes.tar.gz | 1.7.0 | 1.16.3
- [ ] ldc | https://github.com/ldc-developers/ldc/releases/download/v1.18.0/ldc-1.18.0-src.tar.gz | 1.7.0 | 1.18.0
- [x] leveldb | https://github.com/google/leveldb/archive/1.22.tar.gz | 1.20-1 | 1.22
- [ ] libconfuse | https://github.com/martinh/libconfuse/archive/v3.2.2.tar.gz | 3.2.1 | 3.2.2
- [ ] libdsm | https://github.com/videolabs/libdsm/archive//v0.3.1.tar.gz | 0.3.0 | 0.3.1
- [ ] libepoxy | https://github.com/anholt/libepoxy/archive/1.5.4.tar.gz | 1.4.3 | 1.5.4
- [x] libevent | https://github.com/libevent/libevent/archive/release-2.1.11-stable.tar.gz | 2.1.8-0 | 2.1.11
- [ ] libgit2 | https://github.com/libgit2/libgit2/archive/v0.28.3.tar.gz | 0.28.2 | 0.28.3
- [x] libheif | https://github.com/strukturag/libheif/archive/v1.6.0.tar.gz | 1.3.2 | 1.6.0
- [ ] libmypaint | https://github.com/mypaint/libmypaint/archive/v1.4.0.tar.gz | 1.3.0 | 1.4.0
- [ ] libnghttp2 | https://github.com/nghttp2/nghttp2/archive//v1.40.0.tar.gz | 1.38.0 | 1.40.0
- [ ] libnotify | https://github.com/GNOME/libnotify/archive//0.7.8.tar.gz | 0.7.7 | 0.7.8
- [ ] libpsl | https://github.com/rockdaboot/libpsl/archive/libpsl-0.21.0.tar.gz | 0.20.2 | 0.21.0
- [ ] librhash | https://github.com/rhash/RHash/archive/v1.3.8.tar.gz | 1.3.6 | 1.3.8
- [ ] librsync | https://github.com/librsync/librsync/archive/v2.2.1.tar.gz | 2.0.1-1 | 2.2.1
- [x] libseccomp | https://github.com/seccomp/libseccomp/archive/v2.4.2.tar.gz | 2.4.1 | 2.4.2
- [ ] libsecret | https://github.com/GNOME/libsecret/archive/0.19.1.tar.gz | 0.18.6 | 0.19.1
- [ ] libstrophe | https://github.com/strophe/libstrophe/archive/0.9.3.tar.gz | 0.9.2 | 0.9.3
- [ ] libudev_stub | https://github.com/therealkenc/libudev-stub/archive/v1.0.4.tar.gz | 0.9.0 | 1.0.4
- [ ] libva | https://github.com/intel/libva/releases/download/2.5.0/libva-2.5.0.tar.bz2 | 2.3.0 | 2.5.0
- [ ] libvpx | https://github.com/webmproject/libvpx/archive/v1.8.1.tar.gz | 1.8.0 | 1.8.1
- [ ] libxi | https://github.com/mirror/libXi/archive/libXi-1.7.10.tar.gz | 1.7.9-0 | 1.7.10
- [ ] libzip | https://github.com/nih-at/libzip/archive/rel-1-5-2.tar.gz | 1.5.1 | 1.5.2
- [ ] lynis | https://github.com/CISOfy/lynis/archive/2.7.5.tar.gz | 2.5.7 | 2.7.5
- [ ] masscan | https://github.com/robertdavidgraham/masscan/archive/1.0.5.tar.gz | 1.0.4 | 1.0.5
- [ ] mc | https://github.com/MidnightCommander/mc/archive/4.8.23.tar.gz | 4.8.20 | 4.8.23
- [ ] mdp | https://github.com/visit1985/mdp/archive/1.0.15.tar.gz | 1.0.10 | 1.0.15
- [ ] meson | https://github.com/mesonbuild/meson/archive/0.52.1.tar.gz | 0.52.0 | 0.52.1
- [ ] metasploit | https://github.com/rapid7/metasploit-framework/archive/5.0.62.tar.gz | 4.16.19 | 5.0.62
- [ ] miniconda3 | https://github.com/Anaconda-Platform/anaconda-project/archive/v0.8.4.tar.gz | 4.5.11 | 0.8.4
- [ ] mm_common | https://github.com/GNOME/mm-common/archive/0.9.12.tar.gz | 0.9.11 | 0.9.12
- [ ] mongodb | https://github.com/mongodb/mongo/archive/r4.3.2.tar.gz | 3.2.16-1 | 4.3.2
- [ ] multitail | https://github.com/flok99/multitail/archive/6.5.tar.gz | 6.4.2-1 | 6.5
- [x] nanomsg | https://github.com/nanomsg/nanomsg/archive/1.1.5.tar.gz | 1.0.0 | 1.1.5
- [ ] neofetch | https://github.com/dylanaraps/neofetch/archive/6.1.0.tar.gz | 6.0.0 | 6.1.0
- [ ] nethack | https://github.com/NetHack/NetHack/archive/NetHack-3.6.2_Released.tar.gz | 3.6.0 | 3.6.2
- [ ] nvm | https://github.com/creationix/nvm/archive/v0.35.1.tar.gz | 0.33.8 | v0.35.1
- [ ] oc | https://github.com/openshift/origin/archive/v4.1.0.tar.gz | 3.11.0 | 4.1.0
- [ ] oci | https://github.com/oracle/oci-cli/archive//v2.6.14.tar.gz | 2.4.23 | 2.6.14
- [ ] od1n | https://github.com/CoolerVoid/0d1n/archive/OdinV2.6.tar.gz | 2.3 | 2.6
- [ ] oniguruma | https://github.com/kkos/oniguruma/archive/v6.9.4.tar.gz | 6.9.3 | 6.9.4
- [ ] openblas | https://github.com/xianyi/OpenBLAS/archive/v0.3.7.tar.gz | 0.2.20 | 0.3.7
- [ ] openexr | https://github.com/openexr/openexr/archive//v2.4.0.tar.gz | 2.3.0 | 2.4.0
- [ ] openssh | https://github.com/openssh/openssh-portable/archive/V_8_1_P1.tar.gz | 7.6 | 8.1.P1
- [ ] owl | https://github.com/aoh/owl-lisp/archive/v0.1.16.tar.gz | 0.1.14 | 0.1.16
- [ ] p11kit | https://github.com/p11-glue/p11-kit/archive/0.23.18.1.tar.gz | 0.23.14 | 0.23.18.1
- [ ] packer_completion | https://github.com/mrolli/packer-bash-completion/archive//1.4.3.tar.gz | 1.0.0 | 1.4.3
- [ ] pandoc | https://github.com/jgm/pandoc/archive//2.8.0.1.tar.gz | 2.7.3 | 2.8.0.1
- [ ] peek | https://github.com/phw/peek/archive/1.4.0.tar.gz | 1.3.1 | 1.4.0
- [ ] perl_gcstring_linebreak | https://github.com/hatukanezumi/Unicode-LineBreak/archive/Unicode-LineBreak-2019.001.tar.gz | 2018.003 | 2019.001
- [ ] perl_read_key | https://github.com/jonathanstowe/TermReadKey/archive/2.38.tar.gz | 2.37 | 2.38
- [ ] phive | https://github.com/phar-io/phive/archive/0.13.2.tar.gz | 0.9.0 | 0.13.2
- [ ] platformsh | https://github.com/platformsh/platformsh-cli/archive/v3.49.3.tar.gz | 3.26.0 | 3.49.3
- [ ] pmd | https://github.com/pmd/pmd/archive/pmd_releases/6.20.0.tar.gz | 5.8.1 | 6.20.0
- [ ] profanity | https://github.com/profanity-im/profanity/archive/0.7.1.tar.gz | 0.6.0 | 0.7.1
- [ ] progress | https://github.com/Xfennec/progress/archive/v0.14.tar.gz | 0.13.1 | 0.14
- [ ] protobuf | https://github.com/google/protobuf/archive/v3.11.0.tar.gz | 3.9.2 | 3.11.0
- [ ] q | https://github.com/harelba/q/archive/2.0.6.tar.gz | 1.7.1 | 2.0.6
- [ ] qb64 | https://github.com/Galleondragon/qb64/archive/v1.3.tar.gz | 1.2 | 1.3
- [ ] qpdf | https://github.com/qpdf/qpdf/archive/release-qpdf-9.1.0.tar.gz | 7.1.1 | 9.1.0
- [ ] qtfm | https://github.com/rodlie/qtfm/archive/6.2.0.tar.gz | 6.1.9 | 6.2.0
- [ ] radare2 | https://github.com/radare/radare2/archive/4.0.0.tar.gz | 2.4.0 | 4.0.0
- [ ] ranger | https://github.com/ranger/ranger/archive/v1.9.2.tar.gz | 1.8.1 | 1.9.2
- [ ] re2c | https://github.com/skvadrik/re2c/archive//1.2.1.tar.gz | 1.1.1 | 1.2.1
- [ ] rhino | https://github.com/mozilla/rhino/archive/Rhino1_7_11_Release.tar.gz | 1.7.10 | 1.7.11
- [ ] ripgrep | https://github.com/BurntSushi/ripgrep/archive/11.0.2.tar.gz | 0.8.1 | 11.0.2
- [ ] rng_tools | https://github.com/nhorman/rng-tools/archive/v6.8.tar.gz | 6.5 | 6.8
- [ ] rsu_client | https://github.com/rsu-client/rsu-client/archive/v4.3.8.tar.gz | 4.3.8 | 4.3.8
- [ ] rust | https://github.com/rust-lang/rust/archive/1.39.0.tar.gz | 1.36.0 | 1.39.0
- [ ] s | https://github.com/zquestz/s/archive/v0.5.14.tar.gz | 0.5.10 | 0.5.14
- [ ] s3cmd | https://github.com/s3tools/s3cmd/archive/v2.0.2.tar.gz | 2.0.1 | 2.0.2
- [ ] sbt | https://github.com/sbt/sbt/archive/v1.3.4.tar.gz | 0.13.15 | 1.3.4
- [ ] screenfetch | https://github.com/KittyKatt/screenFetch/archive/v3.9.1.tar.gz | 3.9.0 | 3.9.1
- [ ] sejda_console | https://github.com/torakiki/sejda/archive/v4.0.0.M4.tar.gz | 3.2.46 | 4.0.0.M4
- [ ] selenium_server_standalone | https://github.com/SeleniumHQ/selenium/archive/selenium-3.141.59.tar.gz | 3.11.0 | 3.141.59
- [ ] setuptools | https://github.com/pypa/setuptools/archive/v42.0.2.tar.gz | 41.6.0 | 42.0.2
- [ ] shmux | https://github.com/shmux/shmux/archive/v1.0.3.tar.gz | 1.0.2 | 1.0.3
- [ ] six | https://github.com/benjaminp/six/archive/1.13.0.tar.gz | 1.12.0 | 1.13.0
- [ ] sleuthkit | https://github.com/sleuthkit/sleuthkit/archive/sleuthkit-4.7.0.tar.gz | 4.6.0 | 4.7.0
- [ ] snooze | https://github.com/chneukirchen/snooze/archive/v0.3.tar.gz | 0.2 | 0.3
- [ ] speedtest | https://github.com/sivel/speedtest-cli/archive/v2.1.2.tar.gz | 2.0.2 | 2.1.2
- [ ] sphinx | https://github.com/sphinx-doc/sphinx/archive/v2.2.1.tar.gz | 1.8.1 | 2.2.1
- [ ] sqlmap | https://github.com/sqlmapproject/sqlmap/archive/1.3.11.tar.gz | 1.2 | 1.3.11
- [ ] sshcode | https://github.com/cdr/sshcode/archive/v0.9.0.tar.gz | 0.8.0 | 0.9.0
- [ ] sshfs | https://github.com/libfuse/sshfs/archive/sshfs-3.6.0.tar.gz | 2.10 | 3.6.0
- [ ] sshrc | https://github.com/Russell91/sshrc/archive/0.6.2.tar.gz | 0.6.1 | 0.6.2
- [ ] sshuttle | https://github.com/sshuttle/sshuttle/archive/v0.78.5.tar.gz | 0.78.3 | 0.78.5
- [ ] syncthing | https://github.com/syncthing/syncthing/archive/v1.3.1.tar.gz | 0.14.41 | 1.3.1
- [ ] sysstat | https://github.com/sysstat/sysstat/archive/v12.2.0.tar.gz | 12.1.5 | 12.2.0
- [ ] tcpflow | https://github.com/simsong/tcpflow/archive//tcpflow-1.5.2.tar.gz | 1.5.0 | 1.5.2
- [ ] terraform | https://github.com/hashicorp/terraform/archive/v0.12.16.tar.gz | 0.11.1 | 0.12.16
- [ ] textract | https://github.com/deanmalmgren/textract/archive/v1.6.3.tar.gz | 1.6.1 | 1.6.3
- [ ] thefuck | https://github.com/nvbn/thefuck/archive/3.29.tar.gz | 3.26 | 3.29
- [ ] tidy | https://github.com/htacg/tidy-html5/archive/5.7.28.tar.gz | 5.6.0 | 5.7.28
- [ ] tig | https://github.com/jonas/tig/archive/tig-2.5.0.tar.gz | 2.4.1 | 2.5.0
- [ ] tldr | https://github.com/raylee/tldr/ | 93cfb27 | a7fa21c
- [ ] tmux | https://github.com/tmux/tmux/archive/3.0a.tar.gz | 2.9 | 3.0a
- [ ] tox | https://github.com/tox-dev/tox/archive/3.14.1.tar.gz | 3.4.0 | 3.14.1
- [ ] umockdev | https://github.com/martinpitt/umockdev/archive/0.13.2.tar.gz | 0.9.4 | 0.13.2
- [ ] unshield | https://github.com/twogood/unshield/archive/1.4.3.tar.gz | 1.4.2 | 1.4.3
- [ ] urlwatch | https://github.com/thp/urlwatch/archive/2.17.tar.gz | 2.7-1 | 2.17
- [ ] utf8proc | https://github.com/JuliaLang/utf8proc/archive/v2.4.0.tar.gz | 2.1.0-1 | 2.4.0
- [ ] uwsgi | https://github.com/unbit/uwsgi/archive/2.0.18.tar.gz | 2.0.17 | 2.0.18
- [ ] v2ray | https://github.com/v2ray/v2ray-core/archive//v4.21.3.tar.gz | v4.21.1 | v4.21.3
- [ ] vagrant | https://github.com/hashicorp/vagrant/archive/v2.2.6.tar.gz | 2.0.1 | 2.2.6
- [x] vim | https://github.com/vim/vim/archive/v8.1.2374.tar.gz | 8.1.2234 | 8.1.2374
- [x] vim_runtime | https://github.com/vim/vim/archive/v8.1.2374.tar.gz | 8.1.2234 | 8.1.2374
- [ ] virtualenv | https://github.com/pypa/virtualenv/archive/16.7.8.tar.gz | 16.0.0 | 16.7.8
- [ ] waf | https://github.com/waf-project/waf/archive/waf-2.0.8.tar.gz | 1.9.13 | 2.0.8
- [ ] weston | https://github.com/wayland-project/weston/archive//7.0.0.tar.gz | 4.0.0 | 7.0.0
- [ ] whois | https://github.com/rfc1036/whois/archive/v5.5.3.tar.gz | 5.5.2 | 5.5.3
- [ ] wkhtmltox | https://github.com/wkhtmltopdf/wkhtmltopdf/archive/0.12.5.tar.gz | 0.12.4-1 | 0.12.5
- [ ] wl_clipboard | https://github.com/bugaevc/wl-clipboard/ | c0109 | f3a45f6
- [ ] wp_cli | https://github.com/wp-cli/wp-cli/archive/v2.4.0.tar.gz | 2.3.0 | 2.4.0
- [ ] wxwidgets | https://github.com/wxWidgets/wxWidgets/archive//v3.1.3.tar.gz | 3.0.4 | 3.1.3
- [ ] yamllint | https://github.com/adrienverge/yamllint/archive/v1.19.0.tar.gz | 1.11.1 | 1.19.0
- [x] yarn | https://github.com/yarnpkg/yarn/archive/v1.21.0.tar.gz | 1.19.1 | 1.21.0
- [ ] yelp_tools | https://github.com/GNOME/yelp-tools/archive/3.32.2.tar.gz | 3.27.90 | 3.32.2
- [ ] yelp_xsl | https://github.com/GNOME/yelp-xsl/archive/3.34.0.tar.gz | 3.27.90 | 3.34.0
- [ ] youtubedl | https://github.com/rg3/youtube-dl/archive/2019.11.28.tar.gz | 2019.10.29 | 2019.11.28
- [ ] zeromq | https://github.com/zeromq/libzmq/archive/v4.3.2-win.tar.gz | 4.2.2 | 4.3.2-win
- [ ] zstd | https://github.com/facebook/zstd/archive/v1.4.4.tar.gz | 1.3.4 | 1.4.4

**Comment by vincowl** [comment]
Here is a short overview of the last updates done :

- asciinema 2.0.2
- aspell packages
- cabal 2.4.1.0
- gemacs 26.3
- ghc 8.6.5
- Hunspell 1.7.0 and languages
- Neovim 0.4.2
- pulseaudio 13.0
- setuptools 41.6.0
- stack 2.1.3
- Vim 8.1.2225 and soon 8.1.2233

**Comment by uberhacker** [comment]
Really appreciate the help @vincowl!

**Comment by JL2210** [comment]
We should use gcc.gnu.org for GCC updates from now on. Then we won't have to generate the configuration scripts.

**Comment by uberhacker** [comment]
Closed in favor of https://github.com/skycocker/chromebrew/wiki/Updating-existing-packages.
