### ISSUE TITLE
multi core compilation

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#362]
It is possible to use multiple cores embedded in CPU with -j flag of make.

For example, crew install php7 takes 34 min on c202sa which contains 2 cores.  It takes only 16 min with make -j2 (I modified php7.rb locally).

How can we use these multiple cores?  Modify crew or modify each package?  I wish we have good solution for all of us.

BTW, the number of cores is taken by `nproc` linux command.

**Comment by cstrouse** [comment]
@jam7 I agree that adding additional jobs would be a great idea so long as it doesn't break things for anyone. Make is supposed to check the load and scale the number of processes based on load when just using `make -j` with no job count so do we really need to set that using the core count? I recommend that we go with `make -j`.

**Comment by jam7** [comment]
Maybe that's fine.  I was thinking someone might want to use only few of their cores like 2 out of 4.

**Comment by kirbyfan64** [comment]
Maybe I'm the only person this has happened to, but `make -j` frequently overestimates the power of my computer and locks the whole thing up. It tries to schedule far too many jobs at once for my 2-core.

**Comment by jam7** [comment]
How about this?  Make `crew` to set the number of processor to CREW_NPROC variable and to add `-j#{CREW_NPROC}` as additional argument to `system "make"` command.  Then, we also make `crew` to prioritize $CREW_NPROC environment variable.

So, if user want to specify the number of processor to use, set above environment variable.  Otherwise, `crew` uses all processors.

**Comment by jam7** [comment]
#430 is merged, so closing this issue.

**Comment by jam7** [comment]
@kirbyfan64 please let me know if you have problem with #430.

**Comment by jam7** [comment]
After applying #430, `crew install openssl` fails on flip c100pa.  It works on other machines AFAIK.  I've investigated and found the source of problem is to use -j# at install time.  I'm going to send PR for remedy.

In the mean time, we should either of following items.

- compile using only one core by default?
- specify additional flag to not use multi cores on only broken packages?
- use 2 by default?  (if using 4 cores is the source of problem)

How do you think?  Thanks.

**Comment by lyxell** [comment]
@jam7 What kind of error is reported on c100pa?

**Comment by jam7** [comment]
Openssl is compiled without any errors, but when I run a command using either libcrypto or libssl, system says libxxx is empty or something.  I can reproduce it and post mode details tonight.

**Comment by jam7** [comment]
For example, it is something like this.  Sometime, the size of shared library installed becomes 0 and showing different errors.  Basically, the file copy in the middle of installation seems to be terminated.  I'm not sure why it happens.
```
$ wget
wget: error while loading shared libraries: /usr/local/lib/libssl.so.1.0.0: invalid ELF header
$ ls -l /usr/local/lib/libssl.so.1.0.0
-r-xr-xr-x. 1 chronos chronos 389120 Feb  2 17:29 /usr/local/lib/libssl.so.1.0.0
```

**Comment by jam7** [comment]
Rarely openssl shows following errors in the middle of installation too.
```
Preconfiguring package...
making all in crypto...
created directory `/usr/local/tmp/crew/dest/etc'
created directory `/usr/local/tmp/crew/dest/etc/ssl'
created directory `/usr/local/tmp/crew/dest/etc/ssl/man'
created directory `/usr/local/tmp/crew/dest/etc/ssl/man/man1'
created directory `/usr/local/tmp/crew/dest/etc/ssl/man/man3'
created directory `/usr/local/tmp/crew/dest/etc/ssl/man/man5'
created directory `/usr/local/tmp/crew/dest/etc/ssl/man/man7'
Cannot create directory /usr/local/tmp/crew/dest/etc: File exists
make: *** [install_sw] Error 17
make: *** Waiting for unfinished jobs....
```
Looks like several `mkdir -p` or similar commands at once and causing race condition.  So, I guess if makefile has complicated sequence of shell commands, using multi cores cause race condition errors rarely.  Maybe use `-j#{CREW_NPROC}` for build only?

Please let me know any kind of erros.  Thanks.

**Comment by cstrouse** [comment]
@jam7 Agreed that it makes sense to build in parallel but maybe not for install.

**Comment by cstrouse** [comment]
GNU Portable Threads also cannot have -j passed during compile or it fails. Looks like we may need to just have the -j behavior as it currently is but adding a way to disable it on a per-package level.

**Comment by cstrouse** [comment]
Also, the assumption that make will always be the first arg probably isn't the best idea. What if someone passes something else before make? Maybe split the args array and check all elements for the presence of make?

**Comment by jam7** [comment]
@cstrouse Thank you for new information about GNU Pth.

Regarding to the way to disable `-j`, it is possible to write `system "make", "-j1"` to disable it.  Crew executes it as `system "make", "-j#{NUM_PROC}", "-j1", so make uses only one core.

Regarding to modification of make handling, I wish I could.  However, it is difficult to split one string arg or search inside of it since we need to handle shell escape here too.  Does ruby have such API to quote-shell or something?  Maybe we can check all arguments if arguments are in array.

**Comment by jam7** [comment]
As I mentioned in #443, I compiled all packages.  While doint that, I've found following packages requires to be compiled by single core only.

 - bacon
 - clisp
 - ffcall
 - git
 - groff
 - slang
 - unrar

How do you think?  I'm thinking using single core by default is better now since there are several Makefiles causing problems.

It is still possible to use mutiple cores by specifying `system "make", "-j#{CREW_NPROC}"` in package file clearly.  Maybe it is also possible to use new `CREW_FORCE_NPROC` environment variable to overwrite the default setting (forcing using multiple cores).

**Comment by jam7** [comment]
Well, no opinion to change the behavior, I'm going to keep original behavior:
 - compile in parallel as much as possible and install in sequential
 - compile in sequential if it doesn't work in parallel

I've submitted #488, #526, #527 to fix problems.  I appreciate if those are merged.  Thanks.

**Comment by jam7** [comment]
Going close this since all PR are merged.
