### ISSUE TITLE
[hunspell_base]  Unable to spellcheck a file

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3632]
```
$ hunspell file.txt
Hunspell has been compiled without Ncurses user interface.
```
Interactive cli spell checker works fine:
```
$ hunspell
Hunspell 1.7.0
exampl 
& exampl 4 0: example, exam pl, exam-pl, exemplar
```

**Comment by cstrouse** [comment]
The project's [README](https://github.com/hunspell/hunspell/blob/master/README.md) gives the following usage info:

After compiling and installing (see INSTALL) you can run the Hunspell spell checker (compiled with user interface) with a Hunspell or Myspell dictionary:

```
hunspell -d en_US text.txt
```

or without interface:

```
hunspell
hunspell -d en_US -l <text.txt
```

It seems that since we've compiled hunspell with the interface enabled you have to pass it a dictionary argument.

**Comment by uberhacker** [comment]
You can also add `export DICTIONARY=en_US` to `~/.bashrc` and then you don't need to add the `-d en_US` option.  Interestingly, this works:
```
hunspell < file.txt
```
But this doesn't:
```
hunspell file.txt
```
According to the help, I shouldn't need the redirect.

**Comment by vincowl** [comment]
Same issue here. Note that I have these infos while compiling hunspell from sources :
```
checking for tparm in -lncursesw... yes
Compiling with curses user interface.
checking curses.h usability... no
checking curses.h presence... no
checking for curses.h... no
checking ncursesw/curses.h usability... yes
checking ncursesw/curses.h presence... yes
checking for ncursesw/curses.h... yes
```
Strange.... Is there a way to "test" ncursesw" for instance ? I don't know how to use this lib.

**Comment by vincowl** [comment]
Maybe an hint here : [https://bugs.gentoo.org/692614](https://bugs.gentoo.org/692614)

**Comment by vincowl** [comment]
Seems like libs are not found even if LD_LIBRARY_PATH is correctly set. Absolutely no idea how this can be... `libtinfo` is installed  but `tgetent` can't find it, same for `libncurses`, `libncursesw`, ... @uberhacker @cstrouse , any idea ?

**Comment by uberhacker** [comment]
@vincowl: No idea but I guess this could be another workaround?  `cat spellcheckthis.txt | hunspell`

**Comment by cstrouse** [comment]
@vincowl Is that using the binaries? source builds? both? I have issues a lot of times with the binaries and symbols not being found at the expected locations.

**Comment by vincowl** [comment]
@cstrouse the hunspell with ncurses error happens with binaries installation or with a clean compilation. Thus I am trying to find a solution, hopping this is related to ncurses compilation (libs in /usr/local/lib64 are not seen by the ./compile step) or to libtinfo (can't find a libtinfo.so.6 version nor any sources)

**Comment by vincowl** [comment]
OK. I found a solution. It finally works here. I need to modify `hunspell_base` but also `ncurses`. Is there a solution to add a patch to a downloaded file in the configure step or am I forced to use sed ?

**Comment by JL2210** [comment]
We need to link `readline` with `ncurses` or vice versa, but I forget exactly which...
