### ISSUE TITLE
Fail to install SpaceFM

### ISSUE THREAD

**Issue by richblack** [skycocker/chromebrew#3649]
# Description
I'm looking for a GUI file manager and I found SpaceFM package is listed, but it was failed.
Thank you!

If you executed a specific command:
```shell
$ crew install spacefm
```

Output:
```shell
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... objdump: /bin/sh: unknown type [0x13] section `.relr.dyn'
x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for stow... no
checking whether make supports nested variables... (cached) no
checking whether ln -s works... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/pulseaudio-13.0.tar.xz.dir/pulseaudio-13.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
pulseaudio failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64` exited with 77
```

## Versions and system information
chromebrew: `1.2.5`

ChromeOS: 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=5975690
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_RELEASE_BOARD=reef-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=51
CHROMEOS_RELEASE_BUILDER_PATH=reef-release/R78-12499.51.0
CHROMEOS_RELEASE_BUILD_NUMBER=12499
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=78
CHROMEOS_RELEASE_DESCRIPTION=12499.51.0 (Official Build) beta-channel reef 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=12499.51.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12499.51.0

Model: Asus Chromebook C213NA

Architecture: `x86_64`

**Comment by uberhacker** [comment]
@richblack: Thank you for the feedback.  Have you run `crew update` lately?  There are pre-built binaries available for this package.  Did you try to install with `crew install spacefm -s`?  It appears there is something wrong with your compiler: `configure: error: C compiler cannot create executables`.  Are you able to compile other packages from source?

**Comment by uberhacker** [comment]
@richblack: The binary install is working fine for me.  Did you find out what was wrong with your compiler?  It might be easier to reinstall:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by uberhacker** [comment]
I will close this for now but please open again if this is repeatable.
