### ISSUE TITLE
Codium doesn't display correctly

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3654]
Running this works properly
```
startsommelier
codium
```
But since sommelier and xkb produces a lot of crap inside my terminal, I prefer using `sommelier -X codium`. Using this, codium doesn't display. But if I run `sommelier -X codium --verbose`, everything is fine but my term is flooded by codium's logs (which is normal but it would be better to avoir the --verbose option). How can I solve this ?

**Comment by uberhacker** [comment]
@vincowl: I'm not sure but I suspect the binaries were generated to require logging (aka debug support).  You might mention this in the [issue queue](https://github.com/VSCodium/vscodium/issues).

**Comment by vincowl** [comment]
It might be part of the problem, but it works perfectly with sommelier started and launching codium without verbose mode. Issue occures only with sommelier -X

**Comment by uberhacker** [comment]
@vincowl: Maybe #3696 is related?  What happens if you `crew remove pulseaudio`?

**Comment by vincowl** [comment]
@uberhacker unfortunately, this doesn't help at all... Still the same behavior. So, due to sommelier's broken pipe when entering sleep mode, I am leaving codium aside and favoring nvim. But that would be great to solve this issue and  the #3359 one

**Comment by uberhacker** [comment]
Another option is to disable sleep mode.  You can configure "Always On" for the display.

**Comment by vincowl** [comment]
Right... But it won't lock the screen and watch out your battery drain then... But yes, that's a workaround.

**Comment by uberhacker** [comment]
That's what power cords are for, to save your battery. :)

**Comment by vincowl** [comment]
Right ! :) To nitpick : what if I leave my laptop unplugged all night long with a 30% battery level ? It will shutdown the shell, and session's infos will be lost. Ok.... this is a worst case that won't happen often. :)

**Comment by saltedcoffii** [comment]
no longer an issue, also stale, closing.
