### ISSUE TITLE
Update readline dependency in r.rb binary

### ISSUE THREAD

**Issue by lagerratrobe** [skycocker/chromebrew#3655]
The R binary currently is looking for libreadline7, but Chromebrew is installing libreadline8.  With a brand new install, trying to run R gives the following error:

```
/usr/local/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: 
cannot open shared object file: No such file or directory
```

Doing a local build from source and then installing the built package works fine.

## Versions and system information
chromebrew: 1.2.6

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5978010
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=51
CHROMEOS_RELEASE_BUILDER_PATH=samus-release/R78-12499.51.0
CHROMEOS_RELEASE_BUILD_NUMBER=12499
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=78
CHROMEOS_RELEASE_DESCRIPTION=12499.51.0 (Official Build) beta-channel samus 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=12499.51.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12499.51.0

Model: 2015 Google Pixel

Architecture: x86_64

## Addtional information
Probably can be fixed by simply rebuilding the precompiled binary with libreadline8.

**Comment by uberhacker** [comment]
Thank you for the feedback @lagerratrobe.  This package needs an update anyway.

**Comment by cstrouse** [comment]
Did your last batch of packages not include readline? I did a fresh install yesterday and ruby doesn't have readline support.

**Comment by lagerratrobe** [comment]
The dependency on readline is for the R stats package.

**Comment by uberhacker** [comment]
It's been awhile since this package has been updated and this was likely before we did the readline7 update.  I'll try to submit a PR with new binaries.
