### ISSUE TITLE
Cannot crew install gdk_pixbuf package 

### ISSUE THREAD

**Issue by stencylxd** [skycocker/chromebrew#3666]
I can't crew install the gdk_pixbuf package.
When it's in post install, it gives this:

```shell
Performing post-install...
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/insurmountably)
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/libblkid.so.1)
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/libuuid.so.1)
gdk_pixbuf failed to install: `gdk-pixbuf-query-loaders --update-cache` exited with 1
```
- I think it's a package called libc6, but it needs to be installed with APT/APT-GET and Crosh shell 
  doesn't have that. Is there any way I can get it? 

Chromebrew: `1.2.6`
ChromeOS: `10895.78.0 (Official Build) stable-channel stout`
Model: `Lenovo Thinkpad X131e Chromebook`
Architecture: `x86_64`

**Comment by uberhacker** [comment]
@stencylxd: Thank you for bringing this to our attention.  The way to install and manage packages in Chromebrew is with the crew command.  We don't use apt since that is a tool specific to Debian, not ChromeOS.  I will try and compile new binaries for this package to remove that error.

**Comment by stencylxd** [comment]
The error was fixed, but when I reinstalled chromebrew and tried it, it came up again
I did run:
```shell
crew update
crew upgrade
```
Even after the command completing successfully it still came up.
Same specs and hardware.

**Comment by uberhacker** [comment]
@stencylxd: I'm not noticing an issue after a fresh install on my x86_64 Chromebook.  How did you reinstall?  Did you `rm -rf /usr/local` and then reinstall Chromebrew?  I know if you don't follow the postinstall instructions, you cannot run `gdk-pixbuf-query-loaders --update-cache` without an error.  Can you please post the error you see?

**Comment by stencylxd** [comment]
@uberhacker I Powerwashed (a old name for a wipe of the system in update 69) my Chromebook.
This just resets it to when it was on the shelf. I then installed crew. I ran crew update.
I can tell you that when I put in the command:
 ```shell
gdk-pixbuf-query-loaders --update-cache
```
The error that popped up was the same error in the initial post.
```shell
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/insurmountably)
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/libblkid.so.1)
gdk-pixbuf-query-loaders: /usr/local/lib64/../lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/../lib64/libuuid.so.1)
```
I used:
```shell
sudo crossystem dev_boot_signed_only=1
sudo crossystem dev_boot_usb=1
sudo crossystem dev_boot_legacy=1
```
Before the install. Will those commands affect crew?
I now have Ubuntu on the Chromebook. I'm really sorry if that effects this.

**Comment by uberhacker** [comment]
@stencylxd: Are you on the ChromeOS stable channel?  I'm not sure why it looks for glibc 2.25 but it should be looking for glibc 2.27 since that is the version installed with Chromebrew.  Are you running Ubuntu with Crouton?

**Comment by stencylxd** [comment]
I was on the stable channel. In fact, I couldn't swap channels because my Chromebook was EOL.
Yes, it was GLIBC 2.27. I just copied the initial post error and forgot to edit. Sorry for wasting time. 
I actually flashed a new UEFI BIOS and installed Ubuntu on that. I no longer have Chome OS.

I'm really sorry. In order to fix it I should've stayed on Chrome OS.

**Comment by uberhacker** [comment]
No worries.  If you have a tutorial to install Ubuntu over ChromeOS, I would be interested.

**Comment by stencylxd** [comment]
@uberhacker Over as in keeping Chrome OS or overwriting Chrome OS? 
Use crouton as you mentioned to keep Chrome OS.

Use [this tutorial](https://mrchromebox.tech/#fwscript) to make your chromebook boot UEFI or Legacy operating systems. 
(depends on what payload you choose)

Most options require write protection to be off. Some ways you can turn it off:
A switch on your motherboard that you need to flip
A screw grounding a pin that you need to unscrew
(etc)

Once you have write protection off and you chose a BIOS payload:
Reboot
Plug in a USB or SD with a UEFI or Legacy system (depends on payload)
Install operating system or use as liveusb.
Boom, you got it.

You might be able to boot into Chrome OS still with a legacy payload, not sure though.
