### ISSUE TITLE
GDAL package broken due to version mismatch in libproj dependency

### ISSUE THREAD

**Issue by lagerratrobe** [skycocker/chromebrew#3668]
I've had this happen several times now and I'm wondering if there is a way to "force" an installation to be from a local build, rather than relying on precompiled binaries?

On a clean machine, after installing gdal with ```crew install gdal```, I get the following error when I try to import it in Python.

```
   _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libproj.so.12: cannot open shared object file: No such file or directory
>>> 
```

This is because the dependencies that were installed alongside of gdal are newer than this pre-compiled version expects.

```
chronos@localhost / $ find /usr/local -name "libproj.so.12"
chronos@localhost / $ find /usr/local -name "libproj.so.*"
/usr/local/lib64/libproj.so.13.0.1
```

My solution will be to do a ```crew build gdal``` and then modify the package file to point to the locally built package for install.  Having done this already a couple times, I'm wondering if I could "skip the middleman" in the future?  Trying to keep these packages in sync has got to be a nightmare.

**Comment by uberhacker** [comment]
Thank you for bringing this to our attention @lagerratrobe.  If you notice any other pre-compiled binaries that have this issue, let us know and we can build a new set for each package.

**Comment by lagerratrobe** [comment]
Same package (gdal) is also bailing on libjson version.

```
ImportError: libjson-c.so.2: cannot open shared object file: No such file or directory
>>> 
chronos@localhost /usr/local/lib64 $ find /usr/local -name "libjson-c.so*"
/usr/local/lib64/libjson-c.so.4.0.0
/usr/local/lib64/libjson-c.so
/usr/local/lib64/libjson-c.so.4
```

**Comment by lagerratrobe** [comment]
There's actually an additional problem that affects the source for this package.  In order for it to compile, it needs to have this patch applied - [gdal-2.2.3_json-c_013.patch](https://src.fedoraproject.org/fork/churchyard/rpms/gdal/blob/44c89eba5149dfd9d69b2bb18287f5d2a69efd64/f/gdal-2.2.3_json-c_013.patch).

**Comment by uberhacker** [comment]
@lagerratrobe: I went ahead and updated this package to 2.4.3.  No patch was needed to compile the newer version successfully.  Just so you know, there is another way to determine the version of a file in a package with:
```
$ crew whatprovides libproj.so
proj4: /usr/local/lib/libproj.so
proj4: /usr/local/lib/libproj.so.13
proj4: /usr/local/lib/libproj.so.13.0.1
```

**Comment by uberhacker** [comment]
We will just need to remember to compile this package along with any future proj4 package updates.

**Comment by lagerratrobe** [comment]
Thanks, that's great.  I'll pull the new package in shortly, as I need some of the stuff that was added in the 2.3.x release of GDAL.
