### ISSUE TITLE
Does ssh with X11 forwarding work with chromebrew packages?

### ISSUE THREAD

**Issue by billyblackburn** [skycocker/chromebrew#3673]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
I have crostini installed and ssh with -X works on it, but I wanted to try chromebrew but want to see if anyone has ssh working with it and X forwarding?

If you executed a specific command:
ssh -X tux@tux

?????
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@billyblackburn:  I have never tried to do that.  What is your use case?

**Comment by billyblackburn** [comment]
its not important, it works with putty in crostini. I found that chromeOS uses wayland so maybe its more trouble than its worth?

**Comment by JL2210** [comment]
I don't think it does. I tried a while back and it didn't work. I'd have to try it again to remember why, though.

**Comment by vincowl** [comment]
It works here. Please try : 

- Install `xauth` package.
- `touch /home/chronos/.Xauthority`
- make sure you have something like this in your `~/.ssh/config`
```
Host *
    ForwardX11Trusted yes
    ForwardX11 yes
    XAuthLocation /usr/local/bin/xauth
```
- check which options you have activated on the destination machine in `/etc/ssh/sshd_config`. For instance, I have this 
```
AllowTcpForwarding yes
X11Forwarding yes
X11DisplayOffset 10
PermitTTY yes
```
- restart sommelier

Normally it should work (it does on my x86_64 at least!)

**Comment by JL2210** [comment]
Yes, but that's only if you have a write-enabled root filesystem.

**Comment by vincowl** [comment]
I just had this in my `~/.bashrc` for sommelier and xdg needs
```
sudo chmod -R 1777 /tmp/.X11-unix
sudo chown root:root /tmp/.X11-unix
```
Dev mode is activated on my chromebook (prerequisites for chromebrew).
Nothing else. Maybe it is set up under the hood on my machine but I don't think so.

**Comment by vincowl** [comment]
@billyblackburn If the previous answers meet your needs, maybe we could close this issue ?

**Comment by supechicken** [comment]
Here is a more simple but not secure method
```shell
xhost + # On target computer
export DISPLAY=<target computer ip>
