### ISSUE TITLE
[firefox] Unable to launch

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3685]
```
(crashreporter:23789): Gtk-WARNING **: 20:39:17.671: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/gnome/16x16/status/image-missing.png: Unable to load image-loading module: /usr/local/share/firefox/../lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /usr/local/share/firefox/../lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
```

**Comment by uberhacker** [comment]
We might have to compile this one from source.  Not for the faint of heart.

**Comment by uberhacker** [comment]
I was unable to replicate this on a clean install.  After I wiped all my configs from `/usr/home/chronos/user` and reinstalled Chromebrew, I was able to launch firefox without an issue.  The key here is to make sure it is a `clean` install.

**Comment by satmandu** [comment]
In case anyone else sees this bug, I ran across this issue with geany, but fixed it with ```crew reinstall gdk_pixbuf``` (and following the instructions at the end about putting things in my ~/.bashrc)

**Comment by uberhacker** [comment]
This is good info @satmandu.  Maybe you can add something in the [FAQi](https://github.com/skycocker/chromebrew/wiki/FAQ).

**Comment by Noppey** [comment]
I'm getting this exact error when running firefox within a docker container, but only after a few days.

Not using Chromebrew, but do you guys have any suggestions on how to move forward?

**Comment by satmandu** [comment]
> Not using Chromebrew, but do you guys have any suggestions on how to move forward?

@Noppey Maybe the postinstall section in https://github.com/skycocker/chromebrew/blob/master/packages/gdk_pixbuf.rb might be of help to you.
