### ISSUE TITLE
[pulseaudio] Breaks gui apps

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3696]
Installing this package will prevent codium and firefox from launching.  There may be other packages affected as well.

**Comment by uberhacker** [comment]
Also worth mentioning:
```
$ crew files pulseaudio
...
du: cannot access '/lib/udev/rules.d/90-pulseaudio.rules': No such file or directory
```

**Comment by vincowl** [comment]
@uberhacker No trouble here coupling codium and pulseaudio or firefox and pulseaudio. Indeed I hav troubles with codium (cf #3654), but if I remove pulseaudio, the trouble still occurs. Firefox displays and behaves correctly.
