### ISSUE TITLE
python binary package missing pip

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#374]
Python 3.3.2 installed by `python.rb` is missing the pip command.

**Comment by thedamian** [comment]
you can install pip without it being part of the python package. 

https://pip.pypa.io/en/stable/installing/

**Comment by thedamian** [comment]
can I close this issue?

**Comment by cstrouse** [comment]
The python packager docs say we're supposed to include it. It is also the default and expected behavior for python 3.
