### ISSUE TITLE
zeromq package source version incompatible with GCC 8

### ISSUE THREAD

**Issue by lagerratrobe** [skycocker/chromebrew#3770]
## Description
Current version of zeromq (4.2.2) will not build properly using gcc version 8.

If you executed a specific command:
```shell
crew install -s zeromq
```
## Versions and system information
chromebrew: 1.2.9

ChromeOS: `cat /etc/lsb-release`

Model: Google Pixel, 2015

Architecture: x86_64

## Addtional information
Update the source to this:

https://github.com/zeromq/libzmq/releases/download/v4.3.2/zeromq-4.3.2.tar.gz

**Comment by cstrouse** [comment]
We accept PRs. You can also supply a compilation log to help figure out what the problem is.
