### ISSUE TITLE
Is there a way to install .deb files with chromebrew?

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#3781]
I have a couple .deb files that I'd really like to be compatible with chromebook, and I've tried the three other methods and none of them work for me. Crouton is too slow and weirdly complicated. Chrx, on my computer, doesn't work with audio. Crostini doesn't have the GUI capabilities I need. Does Chromebrew work with .deb files. If not, is there another way? Could this be added?

Using chromebrew 1.2.9

cat /etc/lsb-release                     output the following:

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6065001
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_RELEASE_BOARD=coral-signed-mp-v17keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=coral-release/R79-12607.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=12607
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=79
CHROMEOS_RELEASE_DESCRIPTION=12607.58.0 (Official Build) stable-channel coral 
CHROMEOS_RELEASE_KEYSET=mp-v17
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=12607.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12607.58.0

Model: ASUS C423N
Architecture: x86_64

EDIT: Crostini outputs an error every time a program with a GUI tries to run. Something about "can't find X" or "No display"

**Comment by skiman6010** [comment]
What packages are you trying to install? @uberhacker has been using [alien package converter](https://manpages.ubuntu.com/manpages/trusty/man1/alien.1p.html) to convert packages to install with Chromebrew.

Also just curious, what GUI capabilities are you trying to use that Crostini doesn't support?

**Comment by cstrouse** [comment]
Isn't GPU acceleration the only thing that it doesn't support widely? You can always extract the files from the package and try using either `patchelf` or `chrpath` to make them work from `/usr/local`

**Comment by skiman6010** [comment]
I think GPU acceleration is on by default now. Audio in is in testing right now as well. I think USB exec permissions are still really restricted though.

**Comment by KellyLSB** [comment]
Revisiting this. Is it possible for Chromebrew to update Chrome OS core components; including yet not limited to compiling and installing newer Kernels and even the Crostini and Cros-Termina Modules into the operating system?

This may open some doors for better Chromebrew and Chrome OS integration and reusing or overriding as many core libraries as possible.

**Comment by uberhacker** [comment]
Very good question.  You would need a virtualized kernel to run Crostini but why would you want to add an extra layer to run apps when Chromebrew can run them on Chrome OS natively?  I suppose the pros to Crostini would be more apps available and icons on the desktop but what you are doing essentially is running Linux (Debian) on top of Linux (Chrome OS).

**Comment by JL2210** [comment]
No. `.deb` files install files in `/` and `/usr`, which are both read-only and have no space left. Even if you could it would be wiped after an update.

**Comment by uberhacker** [comment]
@JL2210: Yes, check out the atom, brackets, opera and skype packages.  The destination paths have been altered to install in `/usr/local` instead of `/usr`.  This is possible with binaries and most are only available for x86_64 architecture, unfortunately.

**Comment by uberhacker** [comment]
If you can figure out how to get sound working in skype, you are a better man than me.

**Comment by saltedcoffii** [comment]
Chromebrew now supports deb files as a source_url, this can be closed @uberhacker

**Comment by yeesterPlus** [comment]
Whatabout fusing filesystems
