### ISSUE TITLE
[PHP] dependencies are getting out of control

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3791]
Why is PHP bringing in sommelier, wayland, mesa, pulseaudio, and other desktop-related packages? Chromebooks with 4GB of memory and limited storage definitely don't need all of this bloat enabled by default.

@uberhacker Is this just an issue with how the binaries were compiled or do we need to consider adding a means to disable the desktop packages for those who don't want/need them?

```bash
chronos@localhost:~/Downloads $ crew install php

  Select the version to install:
  5.6 = PHP 5.6.40
  7.0 = PHP 7.0.33
  7.1 = PHP 7.1.33
  7.2 = PHP 7.2.26
  7.3 = PHP 7.3.13
  7.4 = PHP 7.4.1
    0 = Cancel
7.4
php: PHP is a popular general-purpose scripting language that is especially suited to web development.
http://www.php.net/
version 5.6.40-7.4.1
The following packages also need to be installed: 
php74 libwebp libsdl xorg_server pixman xorg_lib libxtrans libx11 xorg_proto libxcb xcb_proto libxau pthread_stubs libxext libfontenc libxinerama fontconfig libxdamage libxfixes libxtst libxi libpciaccess libxkbfile libxshmfence libxcursor libxrender libdmx libfs libice libbsd libsm libxaw libxmu libxt libxpm libxfont2 libxft libxrandr libxres libxv libxvmc libxxf86dga libxxf86vm libxcomposite libxscrnsaver libepoxy mesa libva libdrm libvdpau wayland_protocols wayland font_util dbus libxkbcommon xkeyboard_config xkbcomp xcb_util glproto alsa_lib pulseaudio gsettings_desktop_schemas gnome_common gobject_introspection cairo lzo tcpwrappers libsndfile libgconf dbus_glib gdk_pixbuf pango fribidi jasper shared_mime_info freeglut libglu libtiff libjpeg_turbo psmisc xsetroot xbitmaps iso_codes json_glib gtk_doc graphene at_spi2_atk at_spi2_core atk cups libusb openpam gnome_icon_theme icon_naming_utils perl_xml_simple hicolor_icon_theme xdg_base libsoxr jsonc speex tdb libzip exif libexif popt tidy unixodbc oniguruma gtk3 sommelier 
```

**Comment by uberhacker** [comment]
This is why most distros have separate header packages and why the problem becomes more apparent when you try to include the kitchen sink of php extensions.  I suppose we could spend the time and determine which packages need build-only instead of run-time dependencies.  It's also possible sommelier is a dependency of a package that doesn't really need it.

**Comment by cstrouse** [comment]
@uberhacker Is it the IDEs that are dragging that stuff in as a dependencies for the package?

**Comment by uberhacker** [comment]
Likely what is happening is one of the php extensions requires a library of a package with sommelier as its dependency.
