### ISSUE TITLE
libjpeg or libjpeg_turbo?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3832]
These packages have conflicting files.  Should we get rid of libjpeg and stick with libjpeg_turbo?

**Comment by cstrouse** [comment]
Either that or potentially replace them both with mozjpeg which is based on libjpeg_turbo.

**Comment by cstrouse** [comment]
Also, this breaks emacs.

**Comment by uberhacker** [comment]
As long as vim still works, I don't care about emacs.  Oops...I may have started a flame war again. LoL

**Comment by cstrouse** [comment]
Nope, won't work currently. It builds fine and all of the tests pass but when you run `cjpeg` it throws a `relocation error` when it can't find the symbol `jpeg_float_quality_scaling` in LIBJPEG_8.0 (libjpeg.so.8). If you remove the two libraries and rebuild from source it works or if you upgrade them.

**Comment by cstrouse** [comment]
Are there any reasons *not* to drop `libjpeg` in favor of `libjpeg_turbo`?

**Comment by uberhacker** [comment]
Here are all the packages that depend on libjpeg.  If they all build fine with libjpeg_turbo instead of libjpeg then there is your answer.
```
emacs.rb
freedos.rb
gemacs.rb
hplip.rb
libheif.rb
libmng.rb
libtiff.rb
libwmf.rb
mapserver.rb
poppler.rb
qpdf.rb
qtbase.rb
r.rb
sdl2_image.rb
testdisk.rb
weston.rb
```

**Comment by cstrouse** [comment]
I don't have any x86_64 devices with X so I'm unable to test some of these. @JL2210 can you help us test these?

**Comment by JL2210** [comment]
I might still have a device with developer mode somewhere, but it's unavailable to me right now (can't leave the house), and it has screen issues. Maybe once the "stay at home" order is lifted I could try.

**Comment by saltedcoffii** [comment]
Libjpeg_turbo is no longer a package, libjpeg has apparently been chosen. Closing this issue.
