### ISSUE TITLE
[composer] checksum no longer matches

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3833]
We need to fix the package so it follows the upstream recommendations for how to install it programmatically. We should be pulling down their SHA-384 (https://composer.github.io/installer.sha384sum) and comparing our checksum to that rather than hardcoding the value into the package.

**Comment by uberhacker** [comment]
Agreed.  Did you want to create a PR to fix?

**Comment by cstrouse** [comment]
Sure

**Comment by vincowl** [comment]
Other packages could benefit frome the same mechanic. I am thinking at hugo for instance. It would be great to maybe add this feature in the chromebrew's core to use it as often as possible. Is it too ambitious ?
