### ISSUE TITLE
How would it be possible to improve package update processes ?

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3834]
I would love to spend more time to update available packages and follow new versions. But I am facing these steps : 

- I have to subscribe to new releases alerts from every packages. Easy on github hosted ones, but rather hard on self-hosted ones.
- I need to be alerted at each new pushed release
- I would need to handle the whole chromebrew's packages list (which is quite impressive now !)

On the other hand, once I receive the alert, a lot of these updates require a simple repetitive task that could be easily automated. 

Couldn't we think about automated tasks (CI tasks for instance) that would automatically check new available releases, automatically create a PR with these simple steps aleady applied ?

Then we would only have to test these PRs (compilation and installation steps could be automated) and approve them before merging in master branch. Any opinion about this ?

**Comment by cstrouse** [comment]
We also need to stop building packages on machines with all sorts of installed packages and start doing it via CI on a fresh crew install. There should be prior work on jam7's Github dealing with CrOS builds and Docker that could be updated for the current version. You need a pretty stout machine with 16GB+ of memory to build the image and it takes a while. We might also look at using Arnoldthebat's images as the base or Cloudready. Cloudready got rid of the guest mode so you'd need a Gmail account to be used for builds and testing.

**Comment by uberhacker** [comment]
We definitely don't want to be using Cloudready for testing.  It strays too far from your standard Chrome OS in many ways.  I do agree we should be automating package testing with fresh installs.  I've been trying to set something up for awhile now, although half-heartedly. @jayvdb created a PR awhile back for Travis.  See https://github.com/skycocker/chromebrew/pull/3367.

**Comment by vincowl** [comment]
Absolutely totally agree with this too... But I would not be a great help chosing a cloud CI solution since I am hosting my own CI server and my own docker registry. Absolutely no problem to give a hand once a hosting solution will be chosen ! This whole solution would be great !!

**Comment by cstrouse** [comment]
I have a new script for building Docker images for us. Where should I put it?

**Comment by uberhacker** [comment]
@cstrouse: Nice!  Looks like the tools directory would be appropriate.

**Comment by saltedcoffii** [comment]
We now have a docker container build system. Closing.
