### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by daemonspudguy** [skycocker/chromebrew#3837]
How do you join the Slack instance thing?

**Comment by uberhacker** [comment]
Yeah, I noticed the invite link is dead again.  Maybe @skiman6010 can fix this?

**Comment by cstrouse** [comment]
![Screenshot from 2020-02-27 21-44-15](https://user-images.githubusercontent.com/849044/75511120-5692e000-59aa-11ea-8608-eedb5ad97206.png)

**Comment by daemonspudguy** [comment]
That's lovely.

**Comment by cstrouse** [comment]
Perhaps we should move to a channel on Freenode so there aren't any restrictions on who can participate. Thoughts on this @uberhacker @skiman6010 @JL2210?

**Comment by JL2210** [comment]
Freenode doesn't have message history or a good online client.

**Comment by cstrouse** [comment]
IRC is a protocol which is widely supported by dozens of web-based clients. There are also tons of bots that log channel activities. A open-source project shouldn't be using a closed saas product that doesn't allow for us to include anyone who wishes to participate.

**Comment by JL2210** [comment]
Do any of those online clients also have message history?

**Comment by JL2210** [comment]
Discord is free and it doesn't have any such limitations.
