### ISSUE TITLE
[REQUEST] Alpine email client

### ISSUE THREAD

**Issue by daemonspudguy** [skycocker/chromebrew#3838]
I would love to see the email client Alpine added to the list of packages. I tried building it but it complains about LibSSL.so.1.0.0 and LibCrypt.so.1.0.0. Maybe someone can have more luck than me?

**Comment by uberhacker** [comment]
@daemonspudguy: I can try to build tonight after work.  Is this the project?  http://alpine.x10host.com/alpine/

**Comment by daemonspudguy** [comment]
Ja!

**Comment by cstrouse** [comment]
@uberhacker That is a patched version for Windows from the looks of it. There's another project called re-alpine on SF that continued development of the client for a few years that might be worth a look.

**Comment by daemonspudguy** [comment]
It has a source code tarball that builds on *N?X systems @cstrouse

**Comment by cstrouse** [comment]
What configure options did you try?

**Comment by daemonspudguy** [comment]
./configure PREFIX=/usr/local, make, and then it complains about libssl.so.1.0.0

**Comment by cstrouse** [comment]
@daemonspudguy Can you pastebin your config.log and link to it here?

**Comment by daemonspudguy** [comment]
Sure. https://gist.github.com/daemonspudguy/1358794110aa85aa48c3b500f48bd735

**Comment by cstrouse** [comment]
Ok, got it to build. Try this:

```bash
./configure --prefix=/usr/local \
	--libdir=/usr/local/lib64 \
	--with-ssl-dir=/etc/ssl \
	--with-ssl-include-dir=/usr/local/include \
	--with-ssl-lib-dir=/usr/local/lib64 \
	--disable-nls
```

![Screenshot from 2020-02-28 13-06-42](https://user-images.githubusercontent.com/849044/75583643-43742480-5a2b-11ea-9d90-dee64bd634c4.png)

**Comment by daemonspudguy** [comment]
How? I get these errors: `usr/local/bin/ld: warning: libssl.so.1.0.0, needed by /usr/local/lib64/libldap.so, not found (try using -rpath or -rpath-link)
/usr/local/bin/ld: /usr/lib64/libcrypto.so.1.0.0: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: /usr/lib64/libcrypto.so.1.0.0: unknown type [0x13] section `.relr.dyn'
/usr/local/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/local/lib64/libldap.so, not found (try using -rpath or -rpath-link)
/usr/local/bin/ld: alpine.o: in function `main':
/usr/local/alpine-2.22/alpine/alpine.c:688: undefined reference to `pith_ssl_encryption_version'
/usr/local/bin/ld: /usr/local/alpine-2.22/alpine/alpine.c:689: undefined reference to `pith_ssl_encryption_version'
/usr/local/bin/ld: /usr/local/alpine-2.22/alpine/alpine.c:712: undefined reference to `pith_ssl_encryption_version'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:528: alpine] Error 1
make[4]: Leaving directory '/usr/local/alpine-2.22/alpine'
make[3]: *** [Makefile:622: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/alpine-2.22/alpine'
make[2]: *** [Makefile:442: all] Error 2
make[2]: Leaving directory '/usr/local/alpine-2.22/alpine'
make[1]: *** [Makefile:536: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/alpine-2.22'
make: *** [Makefile:424: all] Error 2
`

**Comment by cstrouse** [comment]
You may need to add a few more options to get the functionality you need but it works and runs at least. From there it'll be pretty easy to create a package.

**Comment by daemonspudguy** [comment]
Already made an AMD64 Binary. (That's my Chromebook's architecture Time for a pull request!
