### ISSUE TITLE
[go] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3848]
```
go: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
https://golang.org/
version 1.14
The following packages also need to be installed: 
go_bootstrap 
Do you agree? [Y/n] Proceeding...
go_bootstrap: Bootstrap tool chain for the Go programming language.
https://golang.org/
version 1.4-1
Precompiled binary available, downloading...
######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Installing...
Performing post-install...
Downloading source...
######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
Rename all *.la_tmp files back to *.la
Checking...
sh: 1: go: not found
go failed to build: `PATH="/usr/local/tmp/crew/go1.14.src.tar.gz.dir/go/src/../bin:$PATH" GOROOT="/usr/local/tmp/crew/go1.14.src.tar.gz.dir/go/src/.." TMPDIR="/usr/local/tmp" go tool dist test` exited with 127
```

**Comment by cstrouse** [comment]
Need more info for that. Works for me on fresh installs w/ x86_64 and arm. That looks like go_bootstrap isn't working properly.

**Comment by uberhacker** [comment]
I received the same error after recompiling go_bootstrap from source.

**Comment by uberhacker** [comment]
@cstrouse: It appears go needs itself to compile itself.  How did you get it to work?  Was go already installed when you built it?

**Comment by cstrouse** [comment]
go_bootstrap contains the last version of Go that can be built without a Go compiler.

**Comment by uberhacker** [comment]
I'm going to try another scrubbing when I get home.  We gotta get the binaries.  This is a popular package.

**Comment by uberhacker** [comment]
@cstrouse: This is still an issue for me on a fresh install.  The worst part about this is go installs fine but there is no go executable available.  And I still get the same error after trying to build.  We need to fix this and I'm not sure how to do it.

**Comment by cstrouse** [comment]
There is a go executable it's just not where you think it is. When I get home I'll send you the path.

**Comment by uberhacker** [comment]
Do you have any environment variables set?  That might be the missing link here.  In any event, we need to document how to build this from a powerwashed system.

**Comment by cstrouse** [comment]
@uberhacker Yes. You can't install go from a powerwashed system by installing the current go. You have to install `go_bootstrap`, configure the environment per the postinstall instructions, and then build the current go package. The go binary installed by `go_bootstrap` can be found in `/usr/local/share/go_bootstrap/go/bin/go`.

**Comment by uberhacker** [comment]
I did all that and still cannot generate a go binary.  I even created a symlink from `/usr/local/share/go_bootstrap/go/bin/go` to `/home/chronos/user/bin/go` and included `$HOME/bin` in my path.  Then I received this message after attempting to build go:
```
go tool: no such tool "dist"
go failed to build: `PATH="/usr/local/tmp/crew/go1.14.src.tar.gz.dir/go/src/../bin:$PATH" GOROOT="/usr/local/tmp/crew/go1.14.src.tar.gz.dir/go/src/.." TMPDIR="/usr/local/tmp" go tool dist test` exited with 3
```
What am I missing?
