### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3855]
It's probably time for us to do something about removing Python 2.7 from Chromebrew and updating all Python-dependent packages to require Python3 instead.

**Comment by uberhacker** [comment]
This is easier said than done.  A lot of the older packages have either been abandoned or haven't been updated in a long time and likely won't have updates to support Python3.

**Comment by JL2210** [comment]
We can take the path that Debian and Gentoo are using and install the last update of Python 2 (due sometime in April), then dump all the Python 2 packages except setuptools.

**Comment by uberhacker** [comment]
I don't want to be like them.  No package dumping.

**Comment by JL2210** [comment]
If anyone objects, then we can keep some. But ultimately, it's not a good
idea to keep EOL software laying around.

**Comment by cstrouse** [comment]
I say we stop shipping binaries for EOL packages.

**Comment by heavygabriel** [comment]
Any ETA? ChromeOS/ChromiumOS is planning to remove python2.7 from its images per "/home/$USER/.vpython-root/cd913e/bin/python: warning: Python 2.7 is deprecated and will be removed from CrOS by end of 2021. All users must migrate ASAP."
cc: @uberhacker

**Comment by uberhacker** [comment]
We have another 6 months.

**Comment by saltedcoffii** [comment]
All of our python packages will be updated to python3 with #5717. I will close this issue.
