### ISSUE TITLE
tmux need ncurses

### ISSUE THREAD

**Issue by levinit** [skycocker/chromebrew#3880]
## Description
tmux need ncurses

If you executed a specific command:
```shell
tmux
```

Output:
```shell
tmux: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```
then, install `ncurses`, tmux works.

---
maybe should add `ncurses` to tmux.rb
```ruby
depends_on=ncurses
```

**Comment by uberhacker** [comment]
Thank you for the feedback @levinit.  `ncurses` is a core package so it should be installed out of the box.  Not sure how it was removed.  Have you run `crew update` recently?

**Comment by levinit** [comment]
> Thank you for the feedback @levinit. `ncurses` is a core package so it should be installed out of the box. Not sure how it was removed. Have you run `crew update` recently?

yesterday, I remove chromecrew and install it again, today I install tmux ,and find above problem.
