### ISSUE TITLE
Update glibc to 2.9 but seems to be important to stay with 2.2 ?

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#3921]
The whole code of `glibc.rb` makes me feel like 2.2 version is something important and to avoid upgrading it to 2.9 family. Am I wrong or not ? Since it is a key package, I don't want to break everything without tools to measure its impact. Does anybody has infos ?

**Comment by uberhacker** [comment]
@vincowl:  Yes, we don't want to update to a version higher than 2.2.7 since ChromeOS core libraries use that version and it would create incompatibilities that would make the system unusable.  If you are on a x86_64 system, run `ls /lib64` and it will show all the shared object files with that version.

**Comment by vincowl** [comment]
Fine  ! No update to glibc then. Phew ... cool !

**Comment by rafi16jan** [comment]
how to install the 2.27 version of glibc?

**Comment by vincowl** [comment]
@rafi16jan it would need to update or create a new package for each glibc dependency and consumer. All this being sure it respects chromeOS core libraries needs. A huge task that needs strong motivation and needs

**Comment by vincowl** [comment]
@rafi16jan did you try to set `LIBC_VERSION` to `2.27` ?

**Comment by uberhacker** [comment]
@rafi16jan: What is your architecture?  You should already have glibc 2.27 installed out-of-the-box.  You can check with `crew search glibc -v`.

**Comment by rafi16jan** [comment]
@uberhacker I install chromebrew on an old Chrome v70, the glibc in /lib64/ is 2.23. Looks like I'll just fork the repo and use some older commit

**Comment by rafi16jan** [comment]
And yeah, fortunately its successfully installed using the commit tree https://github.com/skycocker/chromebrew/tree/b90a38eeea5b7ae5b02f5627dee260e0ca58ef8b
