### ISSUE TITLE
problem with creating a package for lshw

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#394]
While attempting to create a package for `lshw` I noticed a bug in the way `crew` handles determining the `topdir` for an archive. I've only ran into this problem so far once but it could potentially show up with other projects that do weird things with their tarballs.

The code running ends up being (see [crew.rb](https://github.com/skycocker/chromebrew/blob/master/crew#L290)):
```ruby
topdir = `tar -tf lshw-B.02.18 | sed -e 's@/.*@@' | uniq`.chomp!
```

Which results in the following:
```
chronos@localhost /usr/local/tmp/crew $ tar -tf lshw-B.02.18.tar.gz | sed -e 's@/.*@@' | uniq | head
lshw-B.02.18
lshw.spec
```

`crew` attempts to use `lshw.spec` rather than `lshw-B.02.18`

I can get things working properly by modifying the code to read:
```ruby
topdir = `tar -tf lshw-B.02.18 | sed -e 's@/.*@@' | uniq | head -1`.chomp!
```

Here's my package file so far:
```ruby
require 'package'

class Lshw < Package
  version 'B.02.18'
  source_url 'http://www.ezix.org/software/files/lshw-B.02.18.tar.gz'
  source_sha1 'c0240f5e53cf40769d52e316719e8010ea6bdea3'

  def self.build
    FileUtils.chdir("src") do
      system "PREFIX=/usr/local", "make"
    end
  end

  def self.install
    FileUtils.chdir("src") do
      system "PREFIX=/usr/local make", "DESTDIR=#{CREW_DEST_DIR}", "install"
    end
  end
end
```

Is adding `head -1` a workable fix or is there a better way to handle this?

**Comment by jam7** [comment]
How about checking actually extracted directory like what zip supports does?

Currently, `crew` parse tar file twice with `xf` and `tf` options.  It means we decompress archive files twice.  However, `crew` parse zip files only once.  I prefer zip way.
