### ISSUE TITLE
0 issues and 0 pull requests goal

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#395]
@cstrouse has several pending PRs for a lot of really nice packages.  What is holding these back from getting merged into master?  Can we make it a goal to keep the issues and PRs queue empty?  I know everybody is busy but it would be nice if stuff moved along more rapidly so we can see good progress.  It will increase the incentive for volunteers if they experience a responsive and active project.  This project has huge potential.

**Comment by bfayers** [comment]
@thedamian yh, I see nothing wrong with @cstrouse 's PRs

**Comment by cstrouse** [comment]
Thanks @uberhacker and @bfayers! And thanks @lyxell for getting those merged. The only one that was overlooked was #365.

**Comment by uberhacker** [comment]
Guys, take notice!  @cstrouse is blazing a new trail.  Let's get these merged please!

**Comment by cstrouse** [comment]
@uberhacker Just so happened that a few thing I needed for myself had a bunch of dependencies to package.

**Comment by uberhacker** [comment]
Could we reopen this issue please? :)

**Comment by lyxell** [comment]
@uberhacker Do you really consider this a real issue? I'm sure everyone is already working as fast as they can.

**Comment by uberhacker** [comment]
@lyxell: This should be an ongoing issue until there are 0 prs and 0 issues.  Now that I know you have seen this, at least I know you will make this your goal. ;)  Thanks
