### ISSUE TITLE
Add python 3.6

### ISSUE THREAD

**Issue by tlnagy** [skycocker/chromebrew#397]
[Python 3.6](https://www.python.org/downloads/release/python-360/) is the latest release and would be nice to have.

**Comment by jam7** [comment]
Can someone pass python 3.6 test?  I personally build 3.6 but it hangs in the middle of test_asyncio.

**Comment by cstrouse** [comment]
@jam7 I'll let you know in a few minutes. Running a build/test now.

**Comment by cstrouse** [comment]
It's still going on the test portion.

```bash
running: test_asyncio (4195 sec)
running: test_asyncio (4225 sec)
```

**Comment by jam7** [comment]
that's what happens to me too.  i spend a night, but it doesn't finish.

**Comment by cstrouse** [comment]
There's a known bug in pytest when using asyncio from what I've read but for this one I'm thinking it's due to the httpservers test.

http://bugs.python.org/issue27787

If I ^C out of the asyncio loop the test runs the final group of test cases and results in this output:
```bash
FAILED (errors=5)
test test_venv failed
6 tests failed again:
    test_distutils test_fcntl test_httpservers test_shutil
    test_subprocess test_venv

Total duration: 132 min 48 sec
Tests result: FAILURE
make: *** [test] Error 1
```

**Comment by jam7** [comment]
Ok.  I've drilled down the problem.  The problem is caused by SIGHUP.  It is not working on chromebook.  I'm going to make different topic about SIGHUP.  So, here I'll explain what is the source of this problem.  You can see details by this:
```
$ ./python -m test -v test_asyncio
...
test_subprocess_kill (test.test_asyncio.test_events.EPollEventLoopTests) ... ok
test_subprocess_send_signal (test.test_asyncio.test_events.EPollEventLoopTests) ... 
```
The source code is:
```
    @unittest.skipIf(sys.platform == 'win32', "Don't have SIGHUP")
    def test_subprocess_send_signal(self):
        prog = os.path.join(os.path.dirname(__file__), 'echo.py')

        connect = self.loop.subprocess_exec(
                        functools.partial(MySubprocessProtocol, self.loop),
                        sys.executable, prog)
        transp, proto = self.loop.run_until_complete(connect)
        self.assertIsInstance(proto, MySubprocessProtocol)
        self.loop.run_until_complete(proto.connected)

        transp.send_signal(signal.SIGHUP)
        self.loop.run_until_complete(proto.completed)
        self.assertEqual(-signal.SIGHUP, proto.returncode)
        transp.close()
```
I checked SIGHUP and found it is not working on my chromebook at all.  I'll explain it in different thread.
