### ISSUE TITLE
mosh need to be rebuild for updated protobuf

### ISSUE THREAD

**Issue by daquexian** [skycocker/chromebrew#3978]
## Description
prebuilt mosh depends on libprotobuf.so.17, the chromebrew protobuf package contains libprotobuf.so.20

If you executed a specific command:
```shell
mosh localhost
```

Output:
```shell
mosh-client: error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or director
```

## Versions and system information
chromebrew: `crew --version`
1.3.2

Architecture: `uname -m`
x86_64

**Comment by uberhacker** [comment]
Thank you for the feedback @daquexian.  It appears we need new binaries due to a recent update of protobuf.  In the meantime, you can fix this with `crew reinstall mosh -s`.

**Comment by daquexian** [comment]
@uberhacker Thanks for your quick reply. I'm new to crew (and benefit very much from it, thanks!) and I tried `crew build mosh` but got permission denied:

> Rename all *.la_tmp files back to *.la
> Checking...
> Archiving...
> tar (child): //mosh-1.3.2-2-chromeos-x86_64.tar.xz: Cannot open: Permission denied
> tar (child): Error is not recoverable: exiting now
> tar: //mosh-1.3.2-2-chromeos-x86_64.tar.xz: Cannot write: Broken pipe
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> sh: 1: cannot create mosh-1.3.2-2-chromeos-x86_64.tar.xz.sha256: Permission denied

`crew const` gives:

> ARCH=x86_64
> ARCH_LIB=lib64
> CHROMEOS_RELEASE=76
> CREW_BREW_DIR=/usr/local/tmp/crew/
> CREW_BUILD=x86_64-cros-linux-gnu
> CREW_CONFIG_PATH=/usr/local/etc/crew/
> CREW_DEST_DIR=/usr/local/tmp/crew/dest
> CREW_DEST_HOME=/usr/local/tmp/crew/dest/home/chronos/user
> CREW_DEST_LIB_PREFIX=/usr/local/tmp/crew/dest/usr/local/lib64
> CREW_DEST_PREFIX=/usr/local/tmp/crew/dest/usr/local
> CREW_LIB_PATH=/usr/local/lib/crew/
> CREW_LIB_PREFIX=/usr/local/lib64
> CREW_NOT_COMPRESS=
> CREW_NOT_STRIP=
> CREW_NPROC=4
> CREW_PREFIX=/usr/local
> CREW_VERSION=1.3.2
> HOME=/home/chronos/user
> LIBC_VERSION=2.27
> USER=chronos
> 

Did I do something wrong? Thanks!

**Comment by uberhacker** [comment]
That appears to be a case where you are attempting to build in a read-only directory.  Try to cd over to a writable directory and you should be good.

**Comment by daquexian** [comment]
> That appears to be a case where you are attempting to build in a read-only directory. Try to cd over to a writable directory and you should be good.

It works, thanks! Just curious, isn't it better for crew to always use a fixed writable directory (/usr/local or something else) instead of the current directory?

**Comment by uberhacker** [comment]
Possibly but then you would lose the flexibility to build in any location you choose.
