### ISSUE TITLE
unable to update pip: pip install --upgrade pip

### ISSUE THREAD

**Issue by mtzaldo** [skycocker/chromebrew#3985]
## Description
When python 3.8.2 is being installer during chromebrew installation I get the following error and the installation stops:
```shell
Upgrading pip...
python3 failed to install: `pip3 install --upgrade pip` exited with 
```

If I try upgrading pip myself I got 
```shell
pip3 install -v --upgrade pip
```

Output:
```shell
Created temporary directory: /tmp/pip-ephem-wheel-cache-thzl5rkp
Created temporary directory: /tmp/pip-req-tracker-3ufabbt1
Created requirements tracker '/tmp/pip-req-tracker-3ufabbt1'
Created temporary directory: /tmp/pip-install-mtpssjgk
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Killed
```

## Versions and system information
chromebrew: `1.3.2`

ChromeOS: 
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_RELEASE_BOARD=daisy-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=daisy-release/R75-12105.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.100.0 (Official Build) stable-channel daisy 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.100.0
```

Model: [Samsung ARM Chromebook](https://www.chromium.org/a/chromium.org/dev/chromium-os/developer-information-for-chrome-os-devices/samsung-arm-chromebook)

Architecture: `armv7l`

## Addtional information
I thought it was an SSL issue, but I was able to run openssl and reach pypi.org

**Comment by cstrouse** [comment]
Do you have both python27 and python3 installed? I ran into the same issue with my Samsung Chromebook Plus. I resolved it by removing python27, building python3 from source, and then reinstalling python27 afterwards. Not sure what the problem is but we'll definitely be running into more issues like this as everyone drops 2.7 support.

Have you tried the new way of using pip? `python3 -m pip3 install <pkg>`

**Comment by mtzaldo** [comment]
@cstrouse I didn't have python27 installed. I ran the chromebrew installer and I got that issue. I installed python27 and pip works fine but it is linked to python2.7. I also tried `pytong -m pip install --upgrade pip` and I got the same issue.
I will try the reinstalling method and try again...

**Comment by mtzaldo** [comment]
@cstrouse I did the remove python27 and resinstall python3 from source (`-s`) and it didn't work. Now pip for python27 is not working...
```shell
Traceback (most recent call last):
  File "/usr/local/bin/pip2.7", line 6, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name PackageFinder
```

**Comment by uberhacker** [comment]
@mtzaldo: Try `rm -rf /usr/local/lib/python2.7/site-packages/pip` and then `crew reinstall python27` and pip (2.7 version) should work again.

**Comment by mtzaldo** [comment]
@uberhacker I was able to make pip for python27 to work, but I couldn't make pip3 to work after doing something similar `rm -rf /usr/local/lib/python3.8` and then `crew install -s python3`
@cstrouse I tried reinstalling as you did, it didn't work :(

Is there other thing I can try?

**Comment by uberhacker** [comment]
What happens if you simply run `crew reinstall python3`?

**Comment by mtzaldo** [comment]
No luck. I will powerwash and resinstall again tomorrow.
@uberhacker @cstrouse Thanks for your help.

**Comment by mtzaldo** [comment]
@uberhacker @cstrouse 
I did a powerwash, downloaded the install.sh and commented line 207... then I installed chromebrew using `bash install.sh`.
After that I installed python3 `crew install python3` and tried `pip3 search <package>`. I got a long error, but you can summarize it with:
```shell
pip._vendor.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```
Then I installed libressl `crew install libressl` and ran `pip3 search <package>`... I got the `Killed` message (the reason for this issue).
I removed libressl and installed it again using `crew install -s libressl`... samething...

btw python2 works fine.

**Comment by mtzaldo** [comment]
It seems that this could be a python 3.8 and pip problem. Nothing related to chromebrew. I will keep the issue open, I will try to find more information about it. Thanks.

**Comment by mtzaldo** [comment]
@cstrouse @uberhacker 
woooo I found a solution, I reverted back the openssl.rb package before it was replaced by libressl. Then I rebuilt python3 and everything worked! n__n

So I think there is an issue with python3 and libressl for armv7, let me know if you need more information...

**Comment by uberhacker** [comment]
FWIW, I installed Chromebrew fresh on my Hisense C11 Chromebook (armv7l) system and it worked without an error.  I noticed your ChromeOS version is 75.  Has your Chromebook reached end of life support from Google?  See https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices.

**Comment by mtzaldo** [comment]
@uberhacker 
Yes, it reached EOL a couple of months back. Idk if that is related.

**Comment by uberhacker** [comment]
Quite possibly but in any event, I'm glad you got it working!

**Comment by mtzaldo** [comment]
Thanks, I will close the issue since is working on the Hisense C11.

**Comment by YoshiLightStar** [comment]
> woooo I found a solution, I reverted back the openssl.rb package before it was replaced by libressl. Then I rebuilt python3 and everything worked! n__n

I'm sorry to comment on this after you closed this but how did you do this exactly? I am having the same issue on the Samsung Chromebook 2(XE503C12)

**Comment by mtzaldo** [comment]
@YoshiLightStar I went into the repo history and downloaded the openssl.rb before it was replaced by libressl. Then i copied that rb file in the local packages folder. Then I removed openssl and resinstalled it, after that I reinstaller pyhton3 using the rebuild flag (-s). I can put clearer steps later tonight.

Fyi... The issue is that libressl doesn't support the 3.8 kernel which is being used in the arm chromebook.

**Comment by mtzaldo** [comment]
@YoshiLightStar After you installed chromebrew:
1. Download the following file `https://raw.githubusercontent.com/skycocker/chromebrew/5cb95493aafd9f642de629311fc2ff5efa16e605/packages/openssl.rb`
2. Copy the downloaded file `openssl.rb` to `/usr/local/lib/crew/packages` folder using terminal.
3. Uninstall openssl and libressl `crew remove openssl` `crew remove libressl`
4. Uninstall python3 `crew remove python3`
5. Install openssl `crew install openssl`
6. Install python3 with the build flag`crew install -s python3`
7. Upgrade pip `pip install --upgrade pip`
8. Enjoy

**Comment by riiketi** [comment]
@mtzaldo, I have the same problem.

I tried to use your steps, but when i removing libressl, i am getting next error:

```
chronos@localhost /usr/local/lib/crew/packages $ crew remove libressl
Libressl removed!
chronos@localhost /usr/local/lib/crew/packages $ crew install python3 -s
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libssl.so.47: cannot open shared object file: No such file or directory - /usr/local/lib/ruby/2.7.0/armv7l-linux-gnueabihf/digest/sha2.so (LoadError)
```

**Comment by mtzaldo** [comment]
Did you try installing openssl before install python 3?

**Comment by riiketi** [comment]
Yep, I installed openssl, then remove libressl, and get nonworking crew with this errors:


```
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libssl.so.47: cannot open shared object file: No such file or directory - /usr/local/lib/ruby/2.7.0/armv7l-linux-gnueabihf/digest/sha2.so (LoadError)
```

**Comment by mtzaldo** [comment]
@riiketi IDK exactly about the issue. I don't have the chromebook anymore.
