### ISSUE TITLE
Why doesn't skycocker commit to this?

### ISSUE THREAD

**Issue by daemonspudguy** [skycocker/chromebrew#3992]
Most work seems to be done by @uberhacker, @cstrouse or @JL2210. Why doesn't Michał Siwek (@skycocker)
 do much?

**Comment by skycocker** [comment]
We can just move this repo to a shared/org account if that’s a problem.

**Comment by JL2210** [comment]
I think that he's lost interest, among other things (like not having a
Chromebook).

**Comment by daemonspudguy** [comment]
It's not an issue, I was just curious

**Comment by skycocker** [comment]
Sure - let me explain it it a little detail:

When I was creating chromebrew I was around 15-16 years old and happy to spend day and night on working on open source stuff. It gave my life a lot of sense. Today I’m a bit older and I spend a lot of time on work, helping my friends who want to be developers start, I also have a bit of a personal life. While I still create some open source projects from time to time (whenever something is clearly missing), I’m not really able to catch up with all the issues that are here, all the changes that are happening and so on. I’m super happy people are using and contributing to chromebrew, but it is a free, open source project. 

Hope that makes stuff a little clearer.

**Comment by uberhacker** [comment]
@skycocker: Thank you for the response.  I would like to set up a shared org if it's not too much trouble.  The problem we are having now is we cannot set up CI tools or configure Slack messages without project ownership to access Settings.  I would still expect you to get full credit for starting this project and helping with maintenance over the years.

**Comment by daemonspudguy** [comment]
How do I say your name @skycocker? I don't have much experience with Polish pronunciation.

**Comment by skycocker** [comment]
@uberhacker sure, let's do it. I know the organization is already present - just a question, since I'm quite a bit behind: will moving the repo immediately affect users? That seems like a possible concern - github returns 301s for the moved repo URLs, but I just found something that looks like an issue for us: https://github.community/t5/How-to-use-Git-and-GitHub/Raw-file-URLs-and-repository-transfers/td-p/19447 

@daemonspudguy you can try saying Mi-how 😄

**Comment by uberhacker** [comment]
@skycocker (aka Mi-how :): Not sure.  It doesn't look like that guy got any response on his question.

**Comment by cstrouse** [comment]
@uberhacker I've added @skycocker's answer to this question to the FAQ. Shall we close this?
