### ISSUE TITLE
Cross compiling on x86 to ARM?

### ISSUE THREAD

**Issue by nlilja** [skycocker/chromebrew#4]
I was wondering could the current packages be cross-compiled for port to ARM chrome os?

**Comment by pollardfamily** [comment]
Hello all,

I just wanted to pop in and share. I have an old CR-48 http://cr-48.wikispaces.com/Specifications and this worked for me.

**Comment by Kriskras99** [comment]
I've got a working version of crew running on my Acer Chromebook 13, will create a pull request tomorrow.

**Comment by heri** [comment]
awesome @Kriskras99 

I have one of the new Chromebook Flip. Am interested in testing

**Comment by heri** [comment]
Hi all

my understanding is that each package (go, curl, nodejs etc.) needs to be compiled by someone having an ARM chromebook before this can be done?

I'm working on something in a repo

**Comment by skycocker** [comment]
@heri not every package - just those that are a part of `buildessential`. Once they work, you should be able to compile pretty much everything you need and then create a package.rb file.

**Comment by heri** [comment]
@skycocker thanks, will do tests

**Comment by garevans** [comment]
Sorry to dredge up an old thread, but what's the current status of arm support?

**Comment by yangwao** [comment]
Hello, I'm ARMed with Asus Chromebook Flip C100PA, how I can help to make chromebrew work on ARM based chromebooks?

**Comment by jabyrd3** [comment]
I have a c100 and am looking to help too; i poked around install.sh and found a precompiled ruby binary for armv7 and got it installed before i realized we'd need the entire toolchain cross compiled, and I'm not exactly sure how to do that. If someone could help me i could update install.sh to properly install everything.

**Comment by lyxell** [comment]
Closing in favor of #235

**Comment by JL2210** [comment]
There is a cross compiler script now. `tools/build_cross_gcc`
