### ISSUE TITLE
chromebrew update not working, json parser error???

### ISSUE THREAD

**Issue by davidschaffrick** [skycocker/chromebrew#4013]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## when attempting to update/upgrade with the ¨crew¨ command it returned an error with an output that ive listed below.

If you executed a specific command:
```
crew
```

Output:
```traceback (most recent call last):
        2: from /usr/local/bin/crew:88:in `<main>'
        1: from /usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse': 416: unexpected token at '{ (JSON::ParserError)
      "name": "'
```

## Versions and system information
chromebrew: `1.3.5`

ChromeOS: `12607.34.0 (Official Build) dev-channel candy `

Model: dell chromebook 11

Architecture: `x64_86`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@davidschaffrick: Please change to the stable channel.  See the first paragraph of https://github.com/skycocker/chromebrew#Installation.
