### ISSUE TITLE
[Suggestion]Add more qt submodules as their own separate packages

### ISSUE THREAD

**Issue by YoshiLightStar** [skycocker/chromebrew#4016]
There are programs that require dependencies that qtbase package does not supply such as qt-mutlimedia, so to be able to compile those programs I have to grab a source package from qt's website(https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules) then compile that then run make install which installs the dependency and then building works as usual. It would be nice if qt-multimedia and other submodules were included with crew as separate packages.

**Comment by uberhacker** [comment]
@YoshiLightStar: Great suggestion.  If you feel up to it, you could use an existing package such as qtsvg.rb as a template for creating qtmultimedia.rb.  Check out the [wiki](https://github.com/skycocker/chromebrew/wiki/Creating-a-package) to learn how to create a new package.  Maybe this can be your first pull request? :)

**Comment by vincowl** [comment]
@YoshiLightStar Which qt submodules would you need ?
