### ISSUE TITLE
Pip3 crashes and not stable

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4022]
On a fresh install, pip3 command lead to errors quite randomly. 
Install python3, it will install pip3 and pip3 will run normally.
A few minutes later, or after a reboot, pip3 commands leads to :
```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```
I know my issue is sketchy. I am investigating on it, starting with a python3 package downgrade to 3.8.1

**Comment by vincowl** [comment]
OK, so this doesn't occurs with python3 in 3.8.1 version. Still investigating

**Comment by uberhacker** [comment]
FWIW, the latest python3 (3.8.2) upgrades pip to the latest release.  You should use pip instead of pip3.  That said, we probably should create a symlink from pip3 to pip after the upgrade.

**Comment by vincowl** [comment]
@uberhacker I reinstalled python3 v3.8.2, reboot and run / got this :
```
chronos@localhost ~/Downloads $ crew update
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 4e70539e [sqlitebrowser] New package, v3.11.2 (#4021)
Package lists, crew, and library updated.
Checking for package updates...

Your software is up to date.
chronos@localhost ~/Downloads $ pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
chronos@localhost ~/Downloads $ pip3
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

**Comment by uberhacker** [comment]
That looks like a case where python27 is installed AFTER python3.  What happens if you try this?
```
crew reinstall python27 python3
```

**Comment by vincowl** [comment]
I'll try this but I strongly expect the absolute same result since I removed python 3 and installed it after the whole installation. I did not reinstall anything but python3, so it leads to reproduce this  same use case.

**Comment by vincowl** [comment]
Well, as expected it failed. What I do : 

- `crew reinstall python27 python3` -> works well
- ` pip3` -> OK
- `crew update; pip3` -> OK
- `crew upgrade; pip3` -> fails

**Comment by vincowl** [comment]
Here are the involved lines :
