### ISSUE TITLE
Install fails on Pixelbook

### ISSUE THREAD

**Issue by clydebarrow** [skycocker/chromebrew#4025]
## Description

Following the instructions to install on a Google Pixelbook fails with the message:

`tar (child): xz: Cannot exec: No such file or directory`

If you executed a specific command:
```shell
curl -Ls https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
```

Output:
```shell
Creating new device.json...
Downloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-x86_64.tar.xz: OK
Extracting gcc8 (this may take a while)...
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

## Versions and system information
Google Pixelbook, stable channel, developer mode enabled.

ChromeOS: `cat /etc/lsb-release`

````
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6369516
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R81-12871.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=12871
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=81
CHROMEOS_RELEASE_DESCRIPTION=12871.76.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12871.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12871.76.0
````

**Comment by clydebarrow** [comment]
I got past the above problem by installing xz-utils with apt-get. Clearly that should be part of the install instructions.

Crew is now installed, but fails when run with:
````
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /usr/local/lib64/ruby/2.5.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libssl.so.1.0.0: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.5.0/x86_64-linux/digest/sha2.so (LoadError)
````
The file `/usr/local/lib64/ruby/2.5.0/x86_64-linux/digest/sha2.so` does in fact exist.

**Comment by uberhacker** [comment]
Hey @clydebarrow:  Are you trying to install this from the Crostini terminal?  If so, that is not recommended or even needed with a Debian container.  Just install all your apps with apt instead.  Otherwise, launch the Chrome browser and enter Ctrl + Alt + T to open a crosh session to install Chromebrew as mentioned [here](https://github.com/skycocker/chromebrew#installation).  I also noticed your Chrome OS release is 76.  The latest is 81 so if you are unable to update that means your Chromebook has reached end of life support.

**Comment by canyong** [comment]
download the openssl package from [here](https://dl.bintray.com/chromebrew/chromebrew/), then extract the package and "cp -r usr/local /usr/"

**Comment by ThatGeekyWeeb** [comment]
This was marked as "Invalid", and should therefore be closed now.
