### ISSUE TITLE
[ripgrep] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4062]
```
error[E0433]: failed to resolve. `crate` can only be used in absolute paths
error[E0433]: failed to resolve. `crate` can only be used in absolute paths
error[E0658]: `crate` in paths is experimental (see issue #45477)
error[E0658]: `crate` in paths is experimental (see issue #45477)
error[E0658]: `crate` in paths is experimental (see issue #45477)
error: aborting due to 5 previous errors
error: Could not compile `same-file`.
error[E0658]: underscore lifetimes are unstable (see issue #44524)
error[E0658]: underscore lifetimes are unstable (see issue #44524)
error[E0658]: underscore lifetimes are unstable (see issue #44524)
error[E0658]: underscore lifetimes are unstable (see issue #44524)
error: aborting due to 4 previous errors
error: Could not compile `termcolor`.
error: build failed
```
Test fails on x86_64:
```
test walk::tests::symlinks ... FAILED

failures:

---- walk::tests::symlinks stdout ----
thread 'walk::tests::symlinks' panicked at 'assertion failed: `(left == right)`
  left: `["a", "a/b", "a/b/foo"]`,
 right: `["a", "a/b", "a/b/foo", "z", "z/foo"]`: single threaded', crates/ignore/src/walk.rs:1880:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    walk::tests::symlinks

test result: FAILED. 130 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p ignore --lib'
ripgrep failed to build: `cargo test --all` exited with 101
```

**Comment by uberhacker** [comment]
Were you able to build @vincowl?

**Comment by vincowl** [comment]
Yes. It compiled and actually runs on my x86_64. I will reinstall to check. Maybe you need to update rust before

**Comment by vincowl** [comment]
Another idea : rust indicates several add-ons to insert in your .bashrc, especially the one related to cargo which seems to be part of your errors

**Comment by vincowl** [comment]
I've reinstalled ripgrep without any problem through removing every line related to my `~/.bashrc` and runngin :
```
crew remove rust ripgrep
crew install ripgrep
```
So, everything fine here.

**Comment by cstrouse** [comment]
I can build from source on x86_64 but it fails on ARM.

**Comment by vincowl** [comment]
@cstrouse `cargo` is part of `rust` package. Does `cargo` work as expected outside the `ripgrep` compilation's scope ? I suppose so given your explanation but need to be sure.
Otherwise it may be related to something like the `graphviz` troubles. Is there a way to set up a compilation environment for aarch64 on my x86_64 to run tests ?

**Comment by cstrouse** [comment]
It's fine I just wasn't paying attention. The aarch64 case needs to be removed and combined with arvm7l in the build step. That yields a working `rustup`/`rustc` and the package builds.

Updating the toolchain version to `1.43.1` (our current `rust` package version) might help with the test failures @uberhacker.
