### ISSUE TITLE
Message "php x.x is already installed" is not displayed as an error

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4078]
While trying to install a php version, if any other version of php is installed, it will output the message php x.x is already installed. This message is displayed in green instead as an error. This leads to visual misunderstanding while installing packages with newer php dependencies

**Comment by uberhacker** [comment]
It's not meant to be an error.  It just indicates another version is installed so you must uninstall the current version before you change versions.

**Comment by vincowl** [comment]
Not an error, ok, I understand. But shouldn't it be at least a warning instead of a "everything's fine"-like message ?
