### ISSUE TITLE
[cabal] Unable to install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4087]
```
$ crew install cabal
cabal: Common Architecture for Building Applications and Libraries
https://www.haskell.org/cabal/
version 2.4.1.0-1
The following packages also need to be installed: 
ghc stack libtinfo 
Do you agree? [Y/n] 
Proceeding...
ghc: The Glasgow Haskell Compiler is a state-of-the-art, open source compiler and interactive environment for the functional language Haskell.
https://www.haskell.org/ghc/
version 8.6.5
No precompiled binary available for your platform, downloading source...
############################################################################################################################################## 100.0%
Archive downloaded
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
ghc failed to install: `stack setup ghc-8.6.5` exited with 127
```
I believe this is an issue where the dependencies are not installed in the correct order.  If I install stack first, then I can install cabal.  It tries to install ghc before stack and ghc needs stack to install.  We really need a better dependency algorithm.

**Comment by vincowl** [comment]
Is there a way to test all of this in a CI job before merging PRs ? It doesn't solve this dependency management but it would avoid to face them in prod. I made a python script to handle dependencies several years ago, will see if I can exhume it and recode it in ruby.

**Comment by uberhacker** [comment]
Probably but the challenge is to create suitable test environments for each architecture.  I basically test every time I generate pre-built binaries.  The process is manual but there is no substitute for testing on actual hardware.  I'm all ears on how to improve the dependency sequence algorithm.  It will be interesting to see what you can figure out.

**Comment by vincowl** [comment]
Could we define the use cases this "algorithm" should address or at least its features ? Maybe it would likely be rather a small system than an algorithm.

Let's open the talk :
To me it would be great to have a dependencies graph, handle minimal version requirement and a maximum one (don't remember which package has this requirement), then a logic should be defined to handle installations. The solution could be set up around this dependencies "graph".

Maybe a bit further it would be great to handle uninstall of uneeded dependencies not declared as manually installed. A bit like `apt-get autoremove`

**Comment by cstrouse** [comment]
Have you guys thought about trying [libsolv](https://github.com/openSUSE/libsolv)'s ruby implementation from OpenSUSE?

**Comment by vincowl** [comment]
@cstrouse After a quick overview, that sounds great ! Sadly, I am not fluent enough in ruby to state deeper on its acceptance to chromebrew's environment and on its workload. What do you think of it ?
