### ISSUE TITLE
Conflict with libpam.so

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4099]
```
$ crew whatprovides libpam.so
linux_pam: /usr/local/lib64/libpam.so
linux_pam: /usr/local/lib64/libpam.so.0
linux_pam: /usr/local/lib64/libpam.so.0.84.2
openpam: /usr/local/lib64/libpam.so
openpam: /usr/local/lib64/libpam.so.2
openpam: /usr/local/lib64/libpam.so.2.0.0

Total found: 6
```

**Comment by satmandu** [comment]
Only package still using openpam is enlightenment, which won't compile due to issues with gtk2, so this appears to be no longer an issue...  maybe remove openpam?

**Comment by uberhacker** [comment]
Yes, that seems like the logical thing to do.  We shouldn't have packages with conflicting files, if possible.  We have the same kind of issue with libjpeg and libjpeg_turbo.  See #3832.

**Comment by saltedcoffii** [comment]
Openpam is no longer a package. This can be closed @uberhacker
