### ISSUE TITLE
openssh issues with openssl

### ISSUE THREAD

**Issue by niikoo** [skycocker/chromebrew#4117]
## Description
I try to connect to my other computer via ssh and receives an error.

It works with the internal one (ssh server is down btw.)
```shell
chronos@localhost ~ $ /usr/bin/ssh niikoo@192.168.1.3
ssh: connect to host 192.168.1.3 port 22: Connection refused
```

If you executed a specific command:
```shell
chronos@localhost ~ $ ssh niikoo@192.168.1.3
OpenSSL version mismatch. Built against 100020ef, you have 20000000
chronos@localhost ~ $ which ssh
/usr/local/bin/ssh
```

## Versions and system information
chromebrew: `crew --version`
1.3.7

ChromeOS: `cat /etc/lsb-release`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6540227
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_RELEASE_BOARD=elm-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=19
CHROMEOS_RELEASE_BUILDER_PATH=elm-release/R84-13099.19.0
CHROMEOS_RELEASE_BUILD_NUMBER=13099
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=84
CHROMEOS_RELEASE_DESCRIPTION=13099.19.0 (Official Build) beta-channel elm 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=13099.19.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13099.19.0

Model: Acer Chromebook R13

Architecture: `uname -m`
aarch64

**Comment by uberhacker** [comment]
@niikoo: Can you please explain in more detail how you are using ssh to connect to other Chromebooks are your network?  FWIW, you need sshd running on the target system before you can connect using the client.

**Comment by niikoo** [comment]
@uberhacker 
I am connecting to my computer running Ubuntu. It works fine using the built-in ssh in chrome.
```shell
chronos@localhost ~ $ /usr/bin/ssh -i $HOME/.ssh/id_rsa niikoo@192.168.1.3 -p 22
#   __    __   ______   _______    ______  
#  |  \  |  \ /      \ |       \  /      \ 
#  | $$\ | $$|  $$$$$$\| $$$$$$$\|  $$$$$$\
#  | $$$\| $$| $$  | $$| $$__/ $$| $$   \$$
#  | $$$$\ $$| $$  | $$| $$    $$| $$      
#  | $$\$$ $$| $$  | $$| $$$$$$$ | $$   __ 
#  | $$ \$$$$| $$__/ $$| $$      | $$__/  \
#  | $$  \$$$ \$$    $$| $$       \$$    $$
#   \$$   \$$  \$$$$$$  \$$        \$$$$$$               
#                                          
# WELCOME TO NOPC (nolinux part) RUNNING UBUNTU
# 
# PLEASE - DO NO HARM! WHO ARE YOU?
#                                          
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * MicroK8s gets a native Windows installer and command-line integration.

     https://ubuntu.com/blog/microk8s-installers-windows-and-macos

0 updates can be installed immediately.
0 of these updates are security updates.

*** System restart required ***
Last login: Sat Jun  6 20:37:43 2020 from 192.168.120.134
niikoo@nolinux:~$ 
```

**Comment by uberhacker** [comment]
Gotcha.  So I guess the solution would be to uninstall openssh?

**Comment by niikoo** [comment]
> Gotcha. So I guess the solution would be to uninstall openssh?

That is a solution, but that means the package provided by chromebrew is broken..

**Comment by uberhacker** [comment]
Maybe not broken, per say, just not compatible with some Linux distro versions.  The only true reason you would need to install openssh is if you wanted to run your own sshd service on your Chromebook.

**Comment by niikoo** [comment]
This fixes the error:
```shell
chronos@localhost /usr/local/lib/crew $ git checkout 5cb95493aafd9f642de629311fc2ff5efa16e605 -- /usr/local/lib/crew/packages/openssl.rb
chronos@localhost /usr/local/lib/crew $ crew install openssl
```

**Comment by cstrouse** [comment]
@uberhacker I think sshd is included in dev mode by default though isn't it?

**Comment by satmandu** [comment]
openssh now uses openssl. Plase reopen if this is still an issue.
