### ISSUE TITLE
installation fails on stable channel

### ISSUE THREAD

**Issue by bpstrngr** [skycocker/chromebrew#4122]
I think i'm lucky to experience a fresh bug after doing a powerwash after a long time. 
I used to be on beta channel and getting used to doing /usr/local/lib64/*.so symlink fixes, 
but now after a powerwash my installation failed for a different reason, 
and the issue persisted when I retreated to stable channel: 
    `    Traceback (most recent call last):
        12: from /usr/local/bin/crew:1079:in `<main>'
        11: from /usr/local/bin/crew:996:in `install_command'
        10: from /usr/local/bin/crew:996:in `each'
         9: from /usr/local/bin/crew:998:in `block in install_command'
         8: from /usr/local/bin/crew:198:in `search'
         7: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
         6: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
         5: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
         4: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
         3: from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
         2: from /usr/local/bin/crew:199:in `block in search'
         1: from /usr/local/bin/crew:121:in `set_package'
    /usr/local/bin/crew:98:in `print_package': undefined method `any?' for nil:NilClass (NoMethodError)`

The same issue comes from /usr/local/bin/crew:98 when 
trying to run it half-installed for any further purpose. 

I looked into the file and it looks for the "any" method 
on an object it parses from its `$CREW_CONFIG_PATH/device.json` file. 

the CREW_CONFIG_PATH variable is empty in the shell, 
so I tried `export CREW_CONFIG_PATH=/usr/local/etc/crew/` 
before running crew (the installation script assigns 
it for itself so I didn't go down further that path), 
but it still gives the exact same error. 
my device.json is quite bare 
after the half-baked installation so don't know if it's 
even directly the isse: 
    `{
    "architecture": "x86_64",
    "installed_packages": [
    {"name": "gcc8","version": "8.3.0"},
    {"name": "libressl","version": "3.0.2"},
    {"name": "ruby","version": "2.7.1"},
    {"name": "libiconv","version": "1.15-1"},
    {"name": "git","version": "2.26.0"},
    {"name": "libssh2","version": "1.9.0"}
    ]
    }`

I've heard someone else having the same error, 
but also getting it magically fixed after just 
starting to use the half-baked crew script. 
Magic hasn't happened for me. 
I'm on 64bit caroline build. 
Thanks!

**Comment by uberhacker** [comment]
@bpstrngr:  Thank you for the feedback.  Definitely a bug.
