### ISSUE TITLE
Have problems with python3 installation.

### ISSUE THREAD

**Issue by riiketi** [skycocker/chromebrew#4146]
When im installing python3, i am getting next error:

`Upgrading pip...
python3 failed to install: `pip3 install --upgrade pip` exited with `

Than i tryed to upgrade pip3 by my self, with command:
`pip3 install -v --upgrade pip`

I got next error:

```
Created temporary directory: /tmp/pip-ephem-wheel-cache-0zc7ffla
Created temporary directory: /tmp/pip-req-tracker-ml50rnke
Created requirements tracker '/tmp/pip-req-tracker-ml50rnke'
Created temporary directory: /tmp/pip-install-84_tlxwp
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Killed

```

I dont know what i should to do. Can u help me, please?

**Comment by uberhacker** [comment]
Hey @riiketi:  Can you please provide some info about your system?  What is the output of `/etc/lsb-release` and `arch`?

**Comment by riiketi** [comment]
```
chronos@localhost ~/Downloads $ sudo cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=89
CHROMEOS_RELEASE_BUILDER_PATH=nyan_big-release/R77-12371.89.0
CHROMEOS_RELEASE_BUILD_NUMBER=12371
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=77
CHROMEOS_RELEASE_DESCRIPTION=12371.89.0 (Official Build) stable-channel nyan_big 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12371.89.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12371.89.0
```

```
chronos@localhost ~/Downloads $ arch
armv7l
```

**Comment by uberhacker** [comment]
It appears your Chromebook has reached EoL support.  That means you can no longer get OS updates from Google.  See http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices#wuid:gx:770ab9f6e615a82a.  You might consider trying [this solution](https://www.ifixit.com/News/30282/how-to-get-updates-on-your-end-of-life-chromebook).

**Comment by riiketi** [comment]
I know about it

I want to understand the problem, why exactly pip can't connect over https? Python 3 itself is installed and running, and the hello world file was launched.

The pop3 version is currently installed:

`pip 19.2.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`

The latest available version of pip3: 20.1.1

Is it possible to manually replace the "pip" file, installes in `/usr/local/lib/python3.8/site-packages/pip` with the latest pip version?

**Comment by uberhacker** [comment]
My guess is the latest pip is not compatible with your Chrome OS version.  You can certainly try to install manually but I imagine you will run into the same issue.

**Comment by riiketi** [comment]
I tested some commands, and understand that problem is in python3.

May I install the previous version of python 3 (python 3.8.1 or 3.7)? if so, how?

**Comment by uberhacker** [comment]
You would have to edit python3.rb, downgrade the version and then compile from source with `crew reinstall python3 -s`.

**Comment by riiketi** [comment]
I cant understand how to install python from my modified python3.rb file? Can u help me with this?

**Comment by riiketi** [comment]
Ok, i got it. I just downloaded python3.rb with version python 3.8.1 version, copied it to `/usr/local/lib/crew/packages`, and it installed ok. But pip is not working, with same error. I think problem is in openssl/libressl, but cant understand how to fix it.

**Comment by uberhacker** [comment]
You might need to downgrade libressl.rb also.

**Comment by riiketi** [comment]
I just downgrade python3 to 3.8.0 version, and installed old version of openssl, and its work, i get updated pip.

**Comment by ThatGeekyWeeb** [comment]
Sorry to comment on such a old issue, but I've come across the same issue, and just wanted to post a fixed `python3.rb` to make fixing the issue a little easier!


[python3.rb.txt](https://github.com/skycocker/chromebrew/files/5046887/python3.rb.txt)

Just 
```sh
curl -LO https://github.com/skycocker/chromebrew/files/5046887/python3.rb.txt && mv ./python3.rb.txt /usr/local/lib/crew/packages/python3.rb`
