### ISSUE TITLE
[Suggestion] Add failsafe of sorts to download

### ISSUE THREAD

**Issue by synesthesium** [skycocker/chromebrew#4157]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
A common issue I've been having across Chromebooks and Wi-Fi networks is that it "Couldn't resolve host" when installing crew, and downloading a package such as isl or ncurses. It's not associated to a specific package, however.

## Versions and system information
chromebrew: You can't install crew due to this issue.

ChromeOS: 13020.87.0

Model: coral

Architecture: x86_64

What I think needs to be done:
Add a failsafe to the install process. For instance:
As you're installing it, and you get "Couldn't resolve host: dl.bintray.com" while downloading git.
It gives you the option to retry (or automatically retries, if you developers would like to do that.)
It retries the download of the package again.

**Comment by saltedcoffii** [comment]
Curl automatically retries failed downloads three times. I think that's sufficient?

**Comment by saltedcoffii** [comment]
we now have an internal `downloader` function for this
