### ISSUE TITLE
will chromebrew work this days?

### ISSUE THREAD

**Issue by mjonsson1986** [skycocker/chromebrew#4177]
i meen with all new security stuff. you cant e.g run scripts from download dir 

## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@mjonsson1986:  This has been part of the security initiative of ChromeOS since inception.  Search for `Downloads` in the [wiki](https://github.com/skycocker/chromebrew/wiki/FAQ) for workarounds.

**Comment by mjonsson1986** [comment]
i dont find any info about workarounds for installing the chromebrew..


Den 17 juli 2020 14:53:00 skrev Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
Your issue was regarding the inability to run executables in the Downloads directory.  If you are having trouble installing Chromebrew, you need to be more specific about the problem you have experienced.  We provided the issue template to help us help you.

**Comment by mjonsson1986** [comment]
yes i asked about running scripts in the download dir because when you 
install chromebrew you need to download a script in the download dir and 
run it. and that will not work this days? enough specific now?


Den 19 juli 2020 01:55:13 skrev Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
No, that is not specific enough.  What are your Chromebook specs?  What is your ChromeOS version?  What is your architecture? 
 What script are you trying to execute?  Where are you attempting to execute?  I can run `curl -Ls git.io/vddgY | bash` from any directory just fine.
