### ISSUE TITLE
No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)

### ISSUE THREAD

**Issue by loogol** [skycocker/chromebrew#4182]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Crew don't works after upgrade to Chrome OS 84. can not reinstall crew with same error

If you executed a specific command:
```shell
crew
curl -Ls https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
```

Output:
```
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib64/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)
```

## Versions and system information
chromebrew: can not get version because error

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6678995
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=72
CHROMEOS_RELEASE_BUILDER_PATH=samus-release/R84-13099.72.0
CHROMEOS_RELEASE_BUILD_NUMBER=13099
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=84
CHROMEOS_RELEASE_DESCRIPTION=13099.72.0 (Official Build) stable-channel samus 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13099.72.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13099.72.0
`

Model: Samus(pixel 2015)

Architecture: `x86_64`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@loogol: Thank you for the feedback.  Try the fix below:
```
ln -s /usr/local/lib64/libcrypto.so.45.0.5 /usr/local/lib64/libcrypto.so.1.0.0
```
Not sure why ruby is looking for libcrypto.so.1.0.0 but definitely an unexpected behavior.

**Comment by loogol** [comment]
@uberhacker, thank you, it is works

**Comment by niikoo** [comment]
For 32 bit systems:
Run as root.
`ln -s /usr/local/lib/libcrypto.so.45.0.5 /usr/local/lib/libcrypto.so.1.0.0`

**Comment by vincowl** [comment]
This is linked to the `curl` package installation I think. I had to make a fresh install and when installing php73 dependencies, I had : 
```
tidy: The granddaddy of HTML tools, with support for modern standards
http://www.html-tidy.org/
version 5.6.0
Precompiled binary available, downloading...
############################################################################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
unixodbc: ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources.
http://www.unixodbc.org/
version 2.3.7
Precompiled binary available, downloading...
############################################################################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
curl: Command line tool and library for transferring data with URLs.
https://curl.haxx.se/
version 7.71.1
Precompiled binary available, downloading...
############################################################################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
Precompiled binary available, downloading...
curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
        9: from /usr/local/bin/crew:1079:in `<main>'
        8: from /usr/local/bin/crew:996:in `install_command'
        7: from /usr/local/bin/crew:996:in `each'
        6: from /usr/local/bin/crew:1000:in `block in install_command'
        5: from /usr/local/bin/crew:685:in `resolve_dependencies_and_install'
        4: from /usr/local/bin/crew:784:in `install'
        3: from /usr/local/bin/crew:495:in `download'
        2: from /usr/local/bin/crew:495:in `chdir'
        1: from /usr/local/bin/crew:502:in `block in download'
/usr/local/bin/crew:502:in `read': No such file or directory @ rb_sysopen - ./php73-7.3.20-chromeos-x86_64.tar.xz (Errno::ENOENT)
```

**Comment by vincowl** [comment]
Removing `curl` allowed to install other packages. Trying to install curl from sources gives 
```
checking whether time.h and sys/time.h may both be included... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for time.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for struct timeval... yes
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2 -lidn2 -lrtmp -lssh2 -lssh2 -lpsl -lssl -lcrypto -lssl -lcrypto -lldap -llber -lbrotlidec -lbrotlidec -lz 
curl failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --disable-maintainer-mode --enable-libcurl-option --with-libmetalink --disable-static --disable-debug --with-libssh2 --with-nghttp2 --with-brotli --enable-ldap --with-ssl` exited with 1
```

**Comment by vincowl** [comment]
Here is my `curl` failing compilation log :
[log_curl.txt](https://github.com/skycocker/chromebrew/files/4990991/log_curl.txt)

**Comment by vincowl** [comment]
@uberhacker I think I solved this : just recompile and regenerate binaries of `libssh2`. Maybe you should also regenerate binaries for packages depending on it like `curl`

**Comment by vincowl** [comment]
@uberhacker recompilation of binaries step seems to be quite large : I needed to install `composer` which failed. It needed to regenerate `php73` (my php version) which itself needed to regenerate `libzip`... Please take #4185 before : there was a syntax error in previous package file so I took the opportunity to upgrade it
