### ISSUE TITLE
Installation error at the end couldn't find sha2.so (Very similar to the previous issue #4182)

### ISSUE THREAD

**Issue by Taylormsz** [skycocker/chromebrew#4187]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

Hello,
Just tried to install chromebrew on a Dell Chromebook and it returned and error about rubygem. Here's the installation log. I ran the listed command in the instructions. Is there any way I could solve this? Thank you so much!

chronos@localhost / $ uname -m
x86_64

chronos@localhost / $ crew --version
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib64/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)

chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=72
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R84-13099.72.0
CHROMEOS_RELEASE_BUILD_NUMBER=13099
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=84
CHROMEOS_RELEASE_DESCRIPTION=13099.72.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13099.72.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13099.72.0

chronos@localhost / $ curl -Ls https://raw.github.com/skycocker/chromebrew/master/install.sh | bash

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Creating new device.json...
Downloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-x86_64.tar.xz: OK
Extracting gcc8 (this may take a while)...
Installing gcc8 (this may take a while)...
Adding new information on gcc8 to device.json...
Downloading libressl...
######################################################################## 100.0%
Verifying libressl...
libressl-3.0.2-chromeos-x86_64.tar.xz: OK
Extracting libressl (this may take a while)...
Installing libressl (this may take a while)...
Adding new information on libressl to device.json...
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.7.1-chromeos-x86_64.tar.xz: OK
Extracting ruby (this may take a while)...
Installing ruby (this may take a while)...
Adding new information on ruby to device.json...
Downloading libiconv...
######################################################################## 100.0%
Verifying libiconv...
libiconv-1.16-chromeos-x86_64.tar.xz: OK
Extracting libiconv (this may take a while)...
Installing libiconv (this may take a while)...
Adding new information on libiconv to device.json...
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.26.0-chromeos-x86_64.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Adding new information on git to device.json...
Downloading libssh2...
######################################################################## 100.0%
Verifying libssh2...
libssh2-1.9.0-chromeos-x86_64.tar.xz: OK
Extracting libssh2 (this may take a while)...
Installing libssh2 (this may take a while)...
Adding new information on libssh2 to device.json...
Initialized empty Git repository in /usr/local/lib/crew/.git/
Updating origin
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 24113 (delta 15), reused 9 (delta 2), pack-reused 24078
Receiving objects: 100% (24113/24113), 6.41 MiB | 721.00 KiB/s, done.
Resolving deltas: 100% (16327/16327), done.
From https://github.com/skycocker/chromebrew
 * [new branch]        deps_order                       -> origin/deps_order
 * [new branch]        gh-pages                         -> origin/gh-pages
 * [new branch]        master                           -> origin/master
 * [new branch]        pr/205                           -> origin/pr/205
 * [new branch]        revert-1030-add-vpnc-package     -> origin/revert-1030-add-vpnc-package
 * [new branch]        revert-1177-update-screenfetch   -> origin/revert-1177-update-screenfetch
 * [new branch]        revert-758-add-moreutils-package -> origin/revert-758-add-moreutils-package
 * [new branch]        revert-760-add-cron-package      -> origin/revert-760-add-cron-package
 * [new branch]        revert-936-update-emacs-package  -> origin/revert-936-update-emacs-package
 * [new branch]        skiman6010-copyright-date-update -> origin/skiman6010-copyright-date-update
 * [new branch]        update-qt-packages               -> origin/update-qt-packages
 * [new tag]           0.4.1                            -> 0.4.1
 * [new tag]           v0.1                             -> v0.1
 * [new tag]           v0.1.1                           -> v0.1.1
 * [new tag]           v0.2                             -> v0.2
 * [new tag]           v0.2.1                           -> v0.2.1
 * [new tag]           v0.2.1.1                         -> v0.2.1.1
 * [new tag]           v0.2.1.2                         -> v0.2.1.2
 * [new tag]           v0.3                             -> v0.3
 * [new tag]           v0.3.1                           -> v0.3.1
 * [new tag]           v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 74101d17 Merge pull request #4184 from uberhacker/update-packages.yaml
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib64/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)

If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@Taylormsz: See #1481.  After that fix, repeat the install.  I'm working on a more long-term fix currently.

**Comment by Taylormsz** [comment]
Thank you so much!

**Comment by Taylormsz** [comment]
How do I update the bind package? I've never used chromebrew before...

**Comment by Taylormsz** [comment]
Thank you ^__^
