### ISSUE TITLE
Latest edits to libressl break curl

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4199]
## Description
exact issue is:
`curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: SLL_COMP_free_compression_methods`
This issue did not happen before the latest changes with `libressl`

Command:
```shell
curl -Ls git.io/vddgY | bash
```
(Install attempt)

Output:
```shell
Creating new device.json
Downloading gcc8...
<...>
Downloading libressl...
<...>
Extracting liibressl..
Installing libressl...
Add new info on libressl to device.json
Downloading ruby..
<...> (Progress bar of Ruby)
curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: SLL_COMP_free_compression_methods
```

## Versions and system information
chromebrew: `crew --version`
> Can't output, can't install at all

ChromeOS: 
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=75
CHROMEOS_RELEASE_BUILDER_PATH=nyan_big-release/R77-12371.75.0
CHROMEOS_RELEASE_BUILD_NUMBER=12371
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=77
CHROMEOS_RELEASE_DESCRIPTION=12371.75.0 (Official Build) stable-channel nyan_big
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12371.75.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12371.75.0
```

Model: Acer Chromebook 13

Architecture: arm7l

## Addtional information
I'm working on a project for Chromebrew, and decided to fresh install (Use a recovery USB) after `crew` was having issues with `curl`
I can confirm up until the a few days ago everything was fine, changes with `libressl`seem to have broke `curl`
I believe commit `751fd0b4dd95e8dec06e2ec5afe9768610d82568` was the commit before my issue began,
> https://github.com/skycocker/chromebrew/tree/751fd0b4dd95e8dec06e2ec5afe9768610d82568 

ATM I am working on resolving the issue on my personal device. (Issue occurred on said device)

**Comment by ThatGeekyWeeb** [comment]
Step by step resolve:

`rm /usr/local/* -rf`
`curl https://raw.githubusercontent.com/skycocker/chromebrew/751fd0b4dd95e8dec06e2ec5afe9768610d82568/install.sh | bash`

This fixed the install issue, but I most likely will see issues with `curl` and `libressl` as soon as the install is finished

**Comment by ThatGeekyWeeb** [comment]
Can confirm, install carries out fine
> Minus the pip issue #4146
> Simply edit `/usr/local/lib/crew/packages/python3.rb` to use older version
 > And install carries out fine

**Comment by ThatGeekyWeeb** [comment]
`libressl` can't be updated 
So, just
```sh
curl -LO https://raw.githubusercontent.com/skycocker/chromebrew/751fd0b4dd95e8dec06e2ec5afe9768610d82568/packages/libressl.rb && mv ./libressl.rb /usr/local/lib/crew/packages/libressl.rb
```

~

And large downloads with `curl` can result in; `curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104` which will kill `crew`, just try again, this is `curl` issue and has nothing to do with Chromebrew

> https://github.com/curl/curl/issues/4409#issuecomment-555715213

**Comment by ThatGeekyWeeb** [comment]
Here's a small script I wrote, to fix the `curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104` issue, it just tries again if the issue happens.
> https://raw.githubusercontent.com/ThatGeekyWeeb/ThatGeekyWeeb.github.io/master/src/crew-curl-issue.sh
It should be called like so;
```sh
sh crew-curl-issue.sh -p <package>
```
where `<package>` is the package that is having the  `curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104` issue

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: Your Chromebook looks past EoL support.  The latest ChromeOS release is 84.  You have 77 so you are definitely in YMMV territory.  Chromebrew only supports the latest _stable_ ChromeOS release.

**Comment by ThatGeekyWeeb** [comment]
I figured that was the main issue, and I do understand the lack of support. 
I opened this Issue as a way to document the issue and prove fixes. 
I believe documentation is always good!
ATM it functions fine after the changes I posted, I'll close this Issue as it servers it's purpose of providing a fix.
