### ISSUE TITLE
mandb: error while loading shared libraries: libgdbm.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by levinit** [skycocker/chromebrew#4202]
#Description
error for chromecrew new installation:
>mandb: error while loading shared libraries: libgdbm.so.6: cannot open shared Lobject file: No such file or directory
>mandb failed to install: `mandb -c` exited with 127

If you executed a specific command:
```shell
curl https://raw.githubusercontent.com/skycocker/chromebrew/master/install.sh |bash
```

Output:
```shell
mandb: mandb is used to initialize or manually update index database caches that are usually maintained by man.
http://man-db.nongnu.org/
version 2.9.0
Precompiled binary available, downloading...
######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
mandb: error while loading shared libraries: libgdbm.so.6: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew:  lastest, get from curl https://raw.githubusercontent.com/skycocker/chromebrew/master/install.sh (2020.08.10)

ChromeOS: `cat /etc/lsb-release`

> CHROMEOS_ARC_ANDROID_SDK_VERSION=28
> CHROMEOS_ARC_VERSION=6687630
> CHROMEOS_AUSERVER=https://tools.google.com/service/update2
> CHROMEOS_BOARD_APPID={495DCB07-E19A-4D7D-99B9-4710011A65B1}
> CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
> CHROMEOS_DEVSERVER=
> CHROMEOS_RELEASE_APPID={495DCB07-E19A-4D7D-99B9-4710011A65B1}
> CHROMEOS_RELEASE_BOARD=nami-signed-mp-v5keys
> CHROMEOS_RELEASE_BRANCH_NUMBER=85
> CHROMEOS_RELEASE_BUILDER_PATH=nami-release/R84-13099.85.0
> CHROMEOS_RELEASE_BUILD_NUMBER=13099
> CHROMEOS_RELEASE_BUILD_TYPE=Official Build
> CHROMEOS_RELEASE_CHROME_MILESTONE=84
> CHROMEOS_RELEASE_DESCRIPTION=13099.85.0 (Official Build) stable-channel nami 
> CHROMEOS_RELEASE_KEYSET=mp-v5
> CHROMEOS_RELEASE_NAME=Chrome OS
> CHROMEOS_RELEASE_PATCH_NUMBER=0
> CHROMEOS_RELEASE_TRACK=stable-channel
> CHROMEOS_RELEASE_UNIBUILD=1
> CHROMEOS_RELEASE_VERSION=13099.85.0
> DEVICETYPE=CHROMEBOOK
> GOOGLE_RELEASE=13099.85.0

Model: YOUR MODEL HERE

Architecture: ` x86-64`

**Comment by uberhacker** [comment]
@levinit: I didn't notice this issue on a fresh install.  Please try again as follows:
```bash
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by levinit** [comment]
fresh install:
```shell
rm /usr/local/* -rf
curl -Ls git.io/vddgY | bash
```
then:

> ownloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-x86_64.tar.xz: OK
Extracting gcc8 (this may take a while)...
Installing gcc8 (this may take a while)...
Adding new information on gcc8 to device.json...
Downloading libressl...
######################################################################## 100.0%
Verifying libressl...
libressl-3.0.2-2-chromeos-x86_64.tar.xz: OK
Extracting libressl (this may take a while)...
Installing libressl (this may take a while)...
Adding new information on libressl to device.json...
Downloading ruby...
curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods


maybe  there is a problem with the SS ver #4117

**Comment by levinit** [comment]
```shell
export LD_LIBRARY_PATH=''
```
then continue excute script again. only mandb can not be installed.

And excute `ssh` command ,it  show 
> OpenSSL version mismatch. Built against 1000215f, you have 20000000

fix above error reference issue #4117 :
```shell
cd /usr/local/lib/crew
git checkout 5cb95493aafd9f642de629311fc2ff5efa16e605 -- /usr/local/lib/crew/packages/openssl.rb
crew install openssl
```

**Comment by activedaily** [comment]
Does not work

export LD_LIBRARY_PATH=/usr/local/lib64
crew install mandb

mandb: mandb is used to initialize or manually update index database caches that are usually maintained by man.
http://man-db.nongnu.org/
version 2.9.0
Precompiled binary available, downloading...
curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods

**Comment by uberhacker** [comment]
@activedaily: mandb is a core package and should already be installed.  What is the output of `cat /etc/lsb-release`?  If you don't have an EoL Chromebook, I would recommend a fresh install as stated earlier in this thread.

**Comment by activedaily** [comment]
cat /etc/lsb-release
GOOGLE_RELEASE=83.4.4
CHROMEOS_RELEASE_BRANCH_NUMBER=97
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
CHROMEOS_RELEASE_BUILD_NUMBER=13020
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_RELEASE_CHROME_MILESTONE=83
CHROMEOS_RELEASE_PATCH_NUMBER=2020_07_21_0739
CHROMEOS_RELEASE_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_BOARD_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=83.4.4
CHROMEOS_RELEASE_DESCRIPTION=83.4.4 (Developer Build - neverware) stable-channel chromeover64

crew worked before, something broken now

**Comment by cstrouse** [comment]
@activedaily We don't support Cloudready.

**Comment by activedaily** [comment]
This works
git clone https://github.com/skycocker/chromebrew.git
cd chromebrew/
git checkout 2b887dece8b3d2af35490d7ce9e6774c1f8fab62
./install.sh
