### ISSUE TITLE
Missing libs from ncurses package

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4205]
# Description
Some libs that should be provided by `ncurses` are missing. This causes issues with packages that depend on `libcurses` libraries, such as the latest version of `fish`.

```shell
ld -lcurses --verbose
```

Expected Output:
```sh
<...>
attempt to open /usr/local/lib/libcurses.so succeeded
<...>
```

Output:
```sh
<...>
attempt to open /usr/local/lib/libcurses.so failed
attempt to open /usr/local/lib/libcurses.a failed
attempt to open /lib/libcurses.so failed
attempt to open /lib/libcurses.a failed
attempt to open /usr/lib/libcurses.so succeeded # ChromeOS provided ncurses libs
<...>
```
This causes packages looking for these headers to grab the ChromeOS provided libraries, which causes issues. 

## Versions and system information
chromebrew: `1.4.2`

Architecture: `armv7l`

## Additional information
I've made a package that provides nothing but the missing libs, I've hand tested it and it works fine, although there are some issues with compiling `ncurses` from source with latest version, and I've had to resort to using a pre-compiled pkg from another repo, I'm submitting this issue in hopes that someone who knows what their doing can fix this issue. I came across this issue when trying to compile `fish` from source using the latest version.

**Comment by ThatGeekyWeeb** [comment]
I've created the following package as nothing more than an example of what could be done to fix this issue. I've hand-tested this package and it serves the intended purpose, and should operate perfectly on all arches.

> https://github.com/ThatGeekyWeeb/rb-packs/blob/master/packages/libcurses_dev.rb

~
The package is being used as a place holder to provide the missing libs which are required for `fish-v3.1.2`. It servers it's purpose and I have no intent of linting it, as it results in zero errors and works perfectly on my testing device.

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: Check out #4207.  The update should resolve this issue.

**Comment by ThatGeekyWeeb** [comment]
Perfect, I'll remove both `libcurses_dev` and `fish_shell` from my repo after that's merged, thanks! :+1:
