### ISSUE TITLE
[Question] `crew` functions 

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4208]
***
I'm working on writing a manual for `crew`, I've looked over the `template` as well as several other package `.rb`'s.
And I wanted to ask a question, after searching over various packages, I found `self.preinstall` and `self.postinstall`.
I was wondering if `self.prebuild` and `self.postbuild` would work as well?
Sorry if this question has already been asked, I was unable to find `self.prebuild` or `self.postbuild`  within a `.rb` after doing a search on all of the packages, and figured I should inquire about such, before writing the Manual.

~
ThatGeekyWeeb
~

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: Thank you for showing interest in writing a manual.  You are correct that `self.prebuild` and `self.postbuild` are not available.  What is your potential use case?

**Comment by ThatGeekyWeeb** [comment]
I can't think of an exact use case for `self.prebuild` or `self.postbuild`, but I was inquiring as I am basing the manual off of the `xbps-src` manual <sup>(https://github.com/void-linux/void-packages/blob/master/Manual.md)</sup>, and these functions exist within `xbps-src` <sup>(https://github.com/void-linux/void-packages/blob/master/Manual.md#functions)</sup>

**Comment by uberhacker** [comment]
There's sorta is a `self.prebuild` already.  It's called `self.patch`.

**Comment by ThatGeekyWeeb** [comment]
Understood, I'll adjust my manual to reflect such, thank. :+1:
~
And I figure `self.postbuild` and `self.preinstall` could be used interchangeably.
~ 
Unless you have anything else to add I'll close this issue.

**Comment by uberhacker** [comment]
I actually thought of a good use case for `self.prebuild`.  Sometimes `configure` scripts write out the `Makefile` "incorrectly" and adjustments need to be made before building.  Sometimes `configure` scripts themselves need to be patched as well.

**Comment by uberhacker** [comment]
It might be good to make the distinction between actually applying a patch as opposed to making changes to `configure` or `Makefile`.

**Comment by ThatGeekyWeeb** [comment]
Yes, that seems like a good idea, maybe `self.prebuild` should be added, to help differ between `Makefile` patching and `configure` patching?

**Comment by uberhacker** [comment]
I was thinking of helping to differentiate between actual patching like `patch -p1 < my.patch` vs `sed -i 's,bad,good,' Makefile`.

**Comment by ThatGeekyWeeb** [comment]
I see. Adding a system in which `sed` and `patch` are in different functions, would be a good idea and may contribute to cleaner looking package script's. Although making it an actual rule would cause issues with preexisting script's. I figure if it were to be added I would outline such within my manual but still allow `crew` to operate without a issue.

**Comment by uberhacker** [comment]
Right, there still would be a bit of a gray area between `self.prebuild` and `self.patch` but I think it makes sense to add the new section.

**Comment by ThatGeekyWeeb** [comment]
Alright, I'll make sure to reflect such within my manual.

**Comment by ThatGeekyWeeb** [comment]
And in which way should it work?
~
Should `sed` be limited to `self.prebuild` or `self.patch`?
And the same for `patch`?

**Comment by uberhacker** [comment]
Chronologically, maybe like below?
```
self.prebuild (for sed operations)
self.patch (for patch operations)
self.build (for configure and make)
self.preinstall (for pre-install conditions)
self.install (for make install)
self.postinstall (for post-install messages or operations)
```
Of course, there are other ways to build such as with cmake, python or ninja/meson (but not limited to those).

**Comment by uberhacker** [comment]
These should be presented as suggestions and not hard and fast rules.

**Comment by ThatGeekyWeeb** [comment]
Alright, sounds good! I'll edit the manual for such.

**Comment by uberhacker** [comment]
It would be nice to document the constants in the manual as well.  The output of `crew const` shows everything available.

**Comment by ThatGeekyWeeb** [comment]
Understood, I'll check out `crew const` when I have access to my Chromebook! <sup>(The one that still runs ChromeOS at least)</sup>

**Comment by uberhacker** [comment]
Something also that will "help" is `crew help`. :)

**Comment by ThatGeekyWeeb** [comment]
Understood. :+1:
~
I experimented with how `crew` operates in each function while building the `libcurses_dev` package, I *believe* I have a good understanding of such.
