### ISSUE TITLE
[Question] Cross Building

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4219]
To help with the workload, I was thinking of setting up a personal binary repo for packages I setup,<sup>(If you'd rather I not, that works to, just state so :) )</sup>, and I am wondering if there's a way to cross compile for other archs with`crew build`.

~
I'm planning on making adding packages to Chromebrew my main project.
~
Please forgive me if this was already asked, I could not find a issue about it.
~
ThatGeekyWeeb

**Comment by uberhacker** [comment]
There was an attempt to create a cross compiler at https://github.com/skycocker/chromebrew/pull/2544/files but it has since been removed.

**Comment by uberhacker** [comment]
The updated script is [here](https://raw.githubusercontent.com/skycocker/chromebrew/797cd8d2d4b0d099bd991875737978e82d2ee672/tools/build_cros_gcc).

**Comment by ThatGeekyWeeb** [comment]
Well then, thank you :+1:, I shall get to work on compiling binaries! :)
