### ISSUE TITLE
mandb failed to install: `mandb -c` exited with 127 while chromebrew installation

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4220]
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
mandb: mandb is used to initialize or manually update index database caches that are usually maintained by man.
http://man-db.nongnu.org/
version 2.9.0
Precompiled binary available, downloading...
######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
mandb: error while loading shared libraries: libgdbm.so.6: cannot open shared object file: No such file or directory
mandb failed to install: `mandb -c` exited with 127

**Comment by supechicken666** [comment]
This happened on chromebrew installation

**Comment by uberhacker** [comment]
@supechicken666: Please give us the output of `cat /etc/lsb-release`.

**Comment by supechicken666** [comment]
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6612792
CHROMEOS_AUSERVER=https://block-tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=87
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R83-13020.87.0
CHROMEOS_RELEASE_BUILD_NUMBER=13020
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=83
CHROMEOS_RELEASE_DESCRIPTION=13020.87.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13020.87.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13020.87.0

**Comment by uberhacker** [comment]
It appears you have a Google Pixelbook.  The latest release is 84.  See https://www.thegeekstuff.com/2017/08/chrome-os-update-to-latest-version/.  Try to update and install again as follows:
```bash
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by supechicken666** [comment]
Thanks, problem solved
