### ISSUE TITLE
[libxfce4util] Circular dependency while installing

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4233]
I had this error while trying to install `libxfce4util` :
```
$ crew install libxfce4util
libxfce4util: Utility library for the Xfce4 desktop environment
https://xfce.org/
version 4.14.0
The following packages also need to be installed: 
libxfce4ui xfconf 
Do you agree? [Y/n] y
Proceeding...
libxfce4ui: Replacement of the old libxfcegui4 library
https://xfce.org/
version 4.15.3
```
And later while configuring step :
```
checking for libxfce4util-1.0 >= 4.12.0... not found
*** The required package libxfce4util-1.0 was not found on your system.
*** Please install libxfce4util-1.0 (atleast version 4.12.0) or adjust
*** the PKG_CONFIG_PATH environment variable if you
*** installed the package in a nonstandard prefix so that
*** pkg-config is able to find it.
```

Dependencies are probably circular : @ThatGeekyWeeb how did you manage to compile this ?

**Comment by ThatGeekyWeeb** [comment]
That, should not be happening, I'll fresh install and see if I can compile!

**Comment by ThatGeekyWeeb** [comment]
Indeed this is a issue, I will try and figure out what happened!

**Comment by ThatGeekyWeeb** [comment]
> https://github.com/void-linux/void-packages/blob/master/srcpkgs/libxfce4util/template  
The void linux template ^
> https://github.com/skycocker/chromebrew/blob/master/packages/libxfce4util.rb  
Our template

Seems I have linked things wrongly, allow me to try some fixes!

**Comment by ThatGeekyWeeb** [comment]
Hmm, I must have manually made that error, `libxfce4util` has no non-"core" package dependencies. I'll make a PR to fix it.
