### ISSUE TITLE
[netsurf] Missing dependency

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4264]
M.CONFIG: utf8 (libutf8proc)    failed        (NETSURF_USE_UTF8PROC := YES)
Makefile:552: *** Unable to find library for: utf8 (libutf8proc).  Stop.
netsurf failed to build: `make V=0 -j2 PREFIX=/usr/local` exited with 2

**Comment by ThatGeekyWeeb** [comment]
hmm, `netsurf` is set to depend on `utf8proc`
> `depends_on 'utf8proc'`

**Comment by uberhacker** [comment]
@ThatGeekyWeeb:  This issue is isolated to x86_84 architecture that has `LD_LIBRARY_PATH=/usr/local/lib64` (the default config).

**Comment by ThatGeekyWeeb** [comment]
Alright, understood.
