### ISSUE TITLE
[Question] `crew search` scripting

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4268]
One of my ongoing projects is automating the process of making packages within Chromebrew.
~
`templator` creates package scripts using templates from the `void-packages` repo. Currently my main issue with it is dependency matching, `void-packages`, and Chromebrew have packages with different names, this is to be expected, so to solve this issue, I need to somehow script `crew search`, although, there seems to be some issues. Mainly with searching for multiple packages at the same time, using a variable.
~
Manual search:
> ```sh
> crew search zlib ssl
> zlibpkg: zlib is a massively spiffy yet delicately unobtrusive compression library.
> libressl: LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, > improving security, and applying best practice development processes.
> openssl: OpenSSL is a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure > > Sockets Layer (SSL) protocols.
> perl_io_socket_ssl: IO::Socket::SSL - SSL sockets with IO::Socket interface
> ```
***
Variable search:
> ```sh
> var="zlib ssl"; crew search "$var"
> Package zlib ssl not found. :(
> ```

Due to the above issue, I cannot script `crew search` using bash, is there a reason for this? If not can someone provide me with a fix?

**Comment by ThatGeekyWeeb** [comment]
For the current time I've had to use command substitution, I figured it how something to do with crew not understanding how to handle bash syntax'ed variables, so unless anyone has a better way to do this, I've done the following.
> ```sh
> search_val="zlib ssl"
> search="$(printf 'crew search %b' "$search_val")"
> ${search}
> ```

**Comment by vincowl** [comment]
Please try :
```
var="zlib ssl"; 
crew search ${var}
```

It produces this output here : 
```
zlibpkg: zlib is a massively spiffy yet delicately unobtrusive compression library.
libressl: LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, improving security, and applying best practice development processes.
openssl: OpenSSL is a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols.
perl_io_socket_ssl: IO::Socket::SSL - SSL sockets with IO::Socket interface
```

**Comment by ThatGeekyWeeb** [comment]
Perfect, that works! I disliked using command substitution, so this is much nicer! 👍

**Comment by vincowl** [comment]
Great ! Hope you will handle this project soon : looking forward to test it. ;-)

**Comment by ThatGeekyWeeb** [comment]
Actually, my project is ready for testing, and, far as I can see, is fully operational!
> https://github.com/ThatGeekyWeeb/templator - Make sure to read the README :wink:

~
This is meant to act as a plugin, it only generates package scripts and when activated, matches dependency's
~
I've actually been using this for my PR's, so far `terminology`, `enlightenment`,`libefl`,`netsurf`,and `xfce4_terminal` have all been packaged using `templator`!
