### ISSUE TITLE
[htop] new package based on the fork?

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#4276]
`htop` has been forked into `htop-dev` since the original went without updates for several years. Shall we create a new package called `htop-dev` or just update the existing `htop` package to use the fork? You can read about the fork in their [changelog](https://github.com/htop-dev/htop/blob/master/ChangeLog).

**Comment by uberhacker** [comment]
We probably don't need to rename the package.  The domains are https://htop.dev/ and https://github.com/htop-dev/htop.

**Comment by vincowl** [comment]
Same here : don't think we need to create a new package if stop reached it's EOL
