### ISSUE TITLE
Uninstall script?

### ISSUE THREAD

**Issue by yoshifan509** [skycocker/chromebrew#429]
Is there a way to make a script for ChromeBrew that uninstalls crew? I looked at the issue from 3 years ago, but I wouldn't really know how.

**Comment by cstrouse** [comment]
@yoshifan509 you can either remove everything under /usr/local or if you don't like that idea you can concatenate all of the filelists under /usr/local/etc/crew/meta and remove all of those files plus the ones that install.sh creates.

**Comment by jam7** [comment]
How about this script?
```
#!/bin/bash
for i in `crew search|grep '(i)'|grep -v ruby|sed -e 's/(i) *//'`; do sudo crew remove $i; done; sudo crew remove ruby
```
If we have this script as uninstall.sh next to install.sh, we can perform `wget -O - ...uninstall.sh | bash`

This script doesn't work correctly if a user install several ruby like ruby and ruby3.

**Comment by dragon788** [comment]
Is there a reason other than that Homebrew does it that Chromebrew puts everything in /usr/local instead of in the user's home directory? Doing it in the home directory may be slightly safer to "clean", though on a multi-user system it would result in a bit of wasted space if multiple users had their own installs.

I believe Linuxbrew either defaults to the user's home directory (to avoid permissions issues with /usr/local) or can be set to a custom prefix.

**Comment by jam7** [comment]
Any files under user's home directory are not exacutable in chromebook environment.  Therefore, we don't use home directory.

It is possible to use `/usr/local/.local` or something instead like @cstrouse said in #536.

**Comment by uberhacker** [comment]
See #877.

**Comment by dragon788** [comment]
If you really want to "uninstall" and you don't have Linuxbrew or anything else in `/usr/local` you can use `dev_install --uninstall` which will automatically wipe any non-hidden folders from `/usr/local`. After discovering it in the comments in an issue on this repo I've been using it to recover from any shenanigans that break my Chromebrew/Linuxbrew installs.

**Comment by uberhacker** [comment]
@dragon788: I have never used `dev_install`.  Can you specify a directory other than `/usr/local` to uninstall?  Since we have the `#{CREW_PREFIX}` constant, we could override the `/usr/local` default directory.

**Comment by yoshifan509** [comment]
fuck you all bitches.....

**Comment by uberhacker** [comment]
And your point is?
