### ISSUE TITLE
curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods

### ISSUE THREAD

**Issue by da0ist** [skycocker/chromebrew#4290]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

Can't install chromebrew.

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Creating new device.json...
Downloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-x86_64.tar.xz: OK
Extracting gcc8 (this may take a while)...
Installing gcc8 (this may take a while)...
Adding new information on gcc8 to device.json...
Downloading libressl...
######################################################################## 100.0%
Verifying libressl...
libressl-3.0.2-2-chromeos-x86_64.tar.xz: OK
Extracting libressl (this may take a while)...
Installing libressl (this may take a while)...
Adding new information on libressl to device.json...
Downloading ruby...
curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods
```

## Versions and system information
chromebrew: `crew --version`
bash: crew: command not found

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6612792
CHROMEOS_AUSERVER=https://block-tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=87
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R83-13020.87.0
CHROMEOS_RELEASE_BUILD_NUMBER=13020
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=83
CHROMEOS_RELEASE_DESCRIPTION=13020.87.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13020.87.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13020.87.0

Model: YOUR MODEL HERE
ThinkPad T440p

Architecture: `uname -m`
x86_64

## Addtional information
Mention things we might need to know. Like:

This has worked in previous installs...

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by da0ist** [comment]
Looks like it may have broken my system altogether. :-(

**Comment by uberhacker** [comment]
@da0ist: Have you tried to update your ChromeOS release?  See https://www.thegeekstuff.com/2017/08/chrome-os-update-to-latest-version/.  The latest release is 85 and you have 83.  AFAICT, your Chromebook has not reached EoL yet so you should be able to update.  After updating, try to install again and report back if you still run into an issue.  Run the commands below:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by da0ist** [comment]
My box is runnind sebanc/brunch. I tried updating it to 84 (latest available) and it had worse problems. I thought that by going back to 83 which worked perfectly before, I'd be able to replicate my setup.

Since I will have to reinstall anyway, do you know if chromebrew will work on cloudready (83)?

**Comment by uberhacker** [comment]
So you don't have a Chromebook?  Cloudready is not supported but it might work.  You will probably run into symlink issues since they have a different install than ChromeOS.

**Comment by da0ist** [comment]
I have a chromebook, but I run ChromeOS on everything! I'll try cloudready, thanks!

**Comment by supechicken666** [comment]
The issue #4202 mentioned this problem
