### ISSUE TITLE
[Suggestion] Installing curl before libressl

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4292]
The installation process consists, of installing, `gcc8`, `libressl`, `ruby`, `libiconv`, `git` and `libssh2`
***
One of the main issues is replacing the systems `openssl` libs with `libressl`
***
Throughout the versions of ChromeOS, the `openssl` version used varies widely. As a result, there are many issues, usually centred around `curl` and `libressl`. I believe a simple fix is possible.
***
Upon installation of `libressl`, the systems `curl` installation breaks, as it was not compiled using the same version of `openssl`, I believe a simple fix would be to install a statically compiled version of `curl`, before installing `libressl`.
***
If we were to statically compile `curl` & `libcurl` to use a `tls` implementation, instead of `libressl`, In theory, this would fix issues caused by replacing the libraries of dynamically linked `curl` install.
***
I recommend installing `curl` before `libressl` and then adjusting the script to use `/usr/local/bin/curl` instead of `/usr/bin/curl`

**Comment by uberhacker** [comment]
I have not noticed the out-of-the-box curl breaking with libressl.  Most of the issues I've noticed were after installing the Chromebrew version of curl.  This is most likely due to packages that depend on curl not being recompiled.  What specific scenarios have you noticed?

**Comment by ThatGeekyWeeb** [comment]
Yes, the Chromebrew `curl` seems broken out of the box. Personally my device uses the 3.10 Kernel which doesn't have full support for ssl, (I am also running ChromeOS 83), but, supporting older version of ChromeOS becomes very hard, mainly with `libressl`, when I was using ChromeOS 77, this was a solution to issues with `libressl`, and I believe it would be a fix that would make Chromebrew more backwards compatible.

**Comment by uberhacker** [comment]
FWIW, you might try adding the following in your `~/.bashrc`:
```
export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib
```
This got rid of the curl error for me.

**Comment by uberhacker** [comment]
Just out of curiosity, is the curl error you noticed the same as below?
```
curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: RAND_egd
```

**Comment by ThatGeekyWeeb** [comment]
My exact issue was
```
curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: SLL_COMP_free_compression_methods
```
