### ISSUE TITLE
[sass] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4311]
```
getrandom: Success
sass failed to build: `pub get` exited with 
```

**Comment by vincowl** [comment]
Is this the whole error message ? Seems like it is truncated

I'll try to install this on a fresh install to see if I can reproduce this on a x86_64 architecture

**Comment by uberhacker** [comment]
Don't sweat it.  I'm not too concerned about i686.  I'll just change the compatibility to exclude this architecture.
