### ISSUE TITLE
[Request] Add `self.remove` function

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4315]
I suggest adding a `self.remove` function that would be executed upon removal. This would allow packages to undo commands that cannot be undone by simply removing the file. 
***
`docbook_xml43` uses `xmlcatmgr` to edit `/usr/local/etc/xml/docbook`, which is installed by `docbook_xml`, with the way `xmlcatmgr` works, recompiling `docbook_xml43` can't be done as it adds text to `/usr/local/etc/xml/catalog.xml` which also needs to be removed by `xmlcatmgr`.
***
> ```ruby
> # NOTE: run  `xmlcatmgr -c /usr/local/etc/xml/docbook remove public "-//OASIS//DTD DocBook XML V4.3//EN"` before reinstall
> ```
***
One could just copy, edit and reinstall the edited file, but that would then require `docbook_xml` to be reinstalled as well.

**Comment by uberhacker** [comment]
This is a great idea!  Several packages have postinstall removal instructions that could be added here instead.  In most cases, we should try to include the most tracked files as possible.  If files are generated from the package commands, sometimes just including a simple `touch #{CREW_DEST_PREFIX}/path/to/file` in the install section will track it in the package so it is deleted after `crew remove ...`.

**Comment by ThatGeekyWeeb** [comment]
The current removal system is great but adding to files installed by another package causes issues, as these commands have to be undone to reinstall the package, otherwise, reinstallation fails.
***
This can be seen if one tries to reinstall `docbook_xml43` without running 
> `xmlcatmgr -c /usr/local/etc/xml/docbook remove public "-//OASIS//DTD DocBook XML V4.3//EN"`

As `/usr/local/etc/xml/docbook` is provided by `docbook_xml`, but a edit needs to be made to link `docbook_xml` v4.3

**Comment by uberhacker** [comment]
Maybe the `xmlcatmgr` command should be executed from `docbook_xml43` instead?

**Comment by ThatGeekyWeeb** [comment]
running `xmlcatmgr -c /usr/local/etc/xml/docbook remove public "-//OASIS//DTD DocBook XML V4.3//EN"` before `docbook_xml43` has been installed, would cause compilation to fail.

**Comment by ThatGeekyWeeb** [comment]
Another idea would be to add a way for commands to fail, only if allowed.
```
xmlcatmgr -c /usr/local/etc/xml/docbook remove public "-//OASIS//DTD DocBook XML V4.3//EN"
``` Fails unless `docbook_xml43` has been installed once before, but that's fine, as long as 
```ruby
xmlcatmgr -c #{CREW_PREFIX}/etc/xml/docbook add public '-//OASIS//DTD DocBook XML V4.3//EN' '#{CREW_PREFIX}/share/xml/docbook/4.3/catalog.xml'"
``` runs afterwards its fine. But due to how `crew` works, it end as soon as one command fails.
***
A final option is to use a bash script, which would execute both of the, and exit with `0` no matter what.

**Comment by ThatGeekyWeeb** [comment]
Basically this:
***
```ruby
    system "cat << EOF > ./*.sh
cmd1
cmd2
EOF"
```
It would allow for one of the commands to fail but compilation to continue.
