### ISSUE TITLE
Opera cannot start : Exiting GPU process due to errors during initialization

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4326]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Install opera without any error
Cannot start opera after installation

If you executed a specific command:
```shell
opera
```

Output:
```shell
[18423:18440:0924/113539.864805:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /usr/local/var/run/dbus/system_bus_socket: No such file or directory
[18448:18448:0924/113539.876178:ERROR:gl_surface_glx.cc(449)] glxQueryVersion failed
[18448:18448:0924/113539.876259:ERROR:gl_initializer_x11.cc(149)] GLSurfaceGLX::InitializeOneOff failed.
[18448:18448:0924/113539.879091:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization

(opera:18423): GLib-GIO-ERROR **: 11:35:39.917: Settings schema 'org.gnome.desktop.background' is not installed
Trace/breakpoint trap (core dumped)
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6819528
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R85-13310.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=13310
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=85
CHROMEOS_RELEASE_DESCRIPTION=13310.76.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13310.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13310.76.0

Architecture:x86_64
## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@supechicken666: Let me know if #4354 fixes this issue when you get a chance.

**Comment by supechicken666** [comment]
> @supechicken666: Let me know if #4354 fixes this issue when you get a chance.

Just have time to try again, but the same error is reported

**Comment by supechicken666** [comment]
The `Trace/breakpoint trap (core dumped)` error disappeared but `GLib-GIO-ERROR **: 21:37:54.276: Settings schema 'org.gnome.desktop.background' is not installed` still reported

**Comment by supechicken666** [comment]
Update: Tried to install package `gsettings_desktop_schemas` , problem solved
