### ISSUE TITLE
Need a better dependency resolver

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4338]
The resolver works currently, however, it needs to be optimized for dependency order and performance.  For instance, sometimes dependencies are installed in the wrong order when some dependency packages depend on other packages first.  This is not so much an issue when installing from binaries but is especially important when installing from source.  However, there are certain instances where the dependency order matters for binary installs as well.

**Comment by cstrouse** [comment]
Perhaps try to leverage the solver from chef? https://github.com/berkshelf/solve

**Comment by supechicken** [comment]
See #6840
