### ISSUE TITLE
Create a PWA that launches a crew app from the desktop

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4341]
[Progressive Web Apps](https://web.dev/what-are-pwas/) are supposedly the new way to develop Android apps for the desktop.  See https://www.androidcentral.com/google-begins-replacing-android-apps-progressive-web-apps-chrome-os#:~:text=Google%20has%20started%20replacing%20a,also%20taking%20up%20less%20storage.  It would be really cool if we could write a PWA that launches a crew app from the desktop.  This would let us have icons on the desktop to run natively compiled apps for ChromeOS.

**Comment by daemonspudguy** [comment]
Someone needs to make that happen.

**Comment by uberhacker** [comment]
@daemonspudguy: Could that someone be you? :)

**Comment by daemonspudguy** [comment]
@uberhacker I have no skills in HTML, CSS, WebAssembly, or Ruby.

**Comment by uberhacker** [comment]
@daemonspudguy: Sounds like some good things to learn.  Might want to throw in Javascript as well.

**Comment by supechicken** [comment]
In Chrome OS, only the Secure Shell App extension have privilege to access the shell, we must make the PWA shortcut ID same as the Secure Shell App.

**Comment by EvidenceRepulsive151** [comment]
Not sure if that'd be possible, but `crew` could silently run a webserver and make PWAs that'll point to an endpoint that will launch the app the user wants. For example, a Firefox PWA would point to `127.0.0.1:6254/run/firefox?authentication=<random_token_used_to_prevent_websites_from_launching_apps>` and upon launhing that app, it'll close itself somehow and start the real Firefox app.

**Comment by supechicken** [comment]
> Not sure if that'd be possible, but `crew` could silently run a webserver and make PWAs that'll point to an endpoint that will launch the app the user wants. For example, a Firefox PWA would point to `127.0.0.1:6254/run/firefox?authentication=<random_token_used_to_prevent_websites_from_launching_apps>` and upon launhing that app, it'll close itself somehow and start the real Firefox app.

Seems possible, but I am afraid that it may cause battery drain issue since it required a web server running on the background
