### ISSUE TITLE
[qemu] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4359]
```
block/ssh.c:301:48: error: ‘SSH_PUBLICKEY_HASH_SHA256’ undeclared (first use in this function); did you mean ‘SSH_PUBLICKEY_HASH_SHA1’?
             r = ssh_get_publickey_hash(pubkey, SSH_PUBLICKEY_HASH_SHA256,
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                SSH_PUBLICKEY_HASH_SHA1
block/ssh.c:301:48: note: each undeclared identifier is reported only once for each function it appears in
block/ssh.c:307:27: warning: implicit declaration of function ‘ssh_get_fingerprint_hash’; did you mean ‘ssh_get_pubkey_hash’? [-Wimplicit-function-declaration]
             fingerprint = ssh_get_fingerprint_hash(SSH_PUBLICKEY_HASH_SHA256,
                           ^~~~~~~~~~~~~~~~~~~~~~~~
                           ssh_get_pubkey_hash
block/ssh.c:307:27: warning: nested extern declaration of ‘ssh_get_fingerprint_hash’ [-Wnested-externs]
make: *** [/usr/local/tmp/crew/qemu-4.2.0.tar.xz.dir/qemu-4.2.0/rules.mak:69: block/ssh.o] Error 1
make: *** Waiting for unfinished jobs....
qemu failed to build: `make V=0 -j2` exited with 2
```

**Comment by virtualb1** [comment]
Hello I had the same problem, but I was able to install some dependencies, and now my bug looks like this:


../lib64/libgtk-3.so: undefined reference to `hb_ft_font_set_funcs'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:208: qemu-system-arm] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/qemu-4.2.0.tar.xz.dir/qemu-4.2.0/arm-softmmu'
make: *** [Makefile:491: arm-softmmu/all] Error 2
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/lib64/libfontconfig.so.1: unknown type [0x13] section `.relr.dyn'
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/libcrypto.so.46: warning: EVP_EncryptFinal is often misused, please use EVP_EncryptFinal_ex and EVP_CIPHER_CTX_cleanup
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/libcrypto.so.46: warning: EVP_DecryptFinal is often misused, please use EVP_DecryptFinal_ex and EVP_CIPHER_CTX_cleanup
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/libcrypto.so.46: warning: EVP_CipherFinal is often misused, please use EVP_CipherFinal_ex and EVP_CIPHER_CTX_cleanup
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/libpangoft2-1.0.so.0: undefined reference to `hb_ft_face_create'
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/libpangoft2-1.0.so.0: undefined reference to `hb_glib_script_from_script'
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../lib64/libgtk-3.so: undefined reference to `hb_ft_font_create'
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../lib64/libpango-1.0.so: undefined reference to `hb_glib_script_to_script'
/usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../x86_64-cros-linux-gnu/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/../../../../lib64/libgtk-3.so: undefined reference to `hb_ft_font_set_funcs'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:208: qemu-system-aarch64] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/qemu-4.2.0.tar.xz.dir/qemu-4.2.0/aarch64-softmmu'
make: *** [Makefile:491: aarch64-softmmu/all] Error 2
qemu failed to install: `make V=0 -j4` exited with 2

**Comment by virtualb1** [comment]
block/ssh.c: In function ‘check_host_key_knownhosts’:
block/ssh.c:301:48: error: ‘SSH_PUBLICKEY_HASH_SHA256’ undeclared (first use in this function); did you mean ‘SSH_PUBLICKEY_HASH_SHA1’?
             r = ssh_get_publickey_hash(pubkey, SSH_PUBLICKEY_HASH_SHA256,
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                SSH_PUBLICKEY_HASH_SHA1
block/ssh.c:301:48: note: each undeclared identifier is reported only once for each function it appears in
block/ssh.c:307:27: warning: implicit declaration of function ‘ssh_get_fingerprint_hash’; did you mean ‘ssh_get_pubkey_hash’? [-Wimplicit-function-declaration]
             fingerprint = ssh_get_fingerprint_hash(SSH_PUBLICKEY_HASH_SHA256,
                           ^~~~~~~~~~~~~~~~~~~~~~~~
                           ssh_get_pubkey_hash
block/ssh.c:307:27: warning: nested extern declaration of ‘ssh_get_fingerprint_hash’ [-Wnested-externs]
make: *** [/usr/local/tmp/crew/qemu-4.2.0.tar.xz.dir/qemu-4.2.0/rules.mak:69: block/ssh.o] Error 1
make: *** Waiting for unfinished jobs....
qemu failed to install: `make V=0 -j4` exited with 2
