### ISSUE TITLE
Why do we need to install every docbook_xml versions with gtk_doc ?

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4361]
@ThatGeekyWeeb While upgrading `firefox` and `codium`, dependencies lead to install `gtk_doc` and its new dependencies. Fine. But why do I need to install every versions of `docbook_xml` ?? Even if docbook_xml is fake, I should just install by default the 5.1 version. Am I wrong ?

Here is the output of my ` crew upgrade codium` for instance : 
```shell
firefox: Mozilla Firefox (or simply Firefox) is a free and open-source web browser
https://www.mozilla.org/en-US/firefox/
version 81.0.1
Updating firefox...
The following packages also need to be installed: 
docbook_xsl docbook_xml51 gtk_doc docbook_xml docbook_xml50 docbook_xml45 docbook_xml44 docbook_xml42 fop 
Do you agree? [Y/n] y
```

**Comment by ThatGeekyWeeb** [comment]
iirc, when I was working `gtk_doc` it only depended on v4.3 `(43)`. It seems that the PR to fix #4320 and #4319 resulted in some changes that caused this.
> ```
> require 'package'
> class Gtk_doc < Package
> <...>
>  depends_on 'docbook_xml'
> ```

It also seems that this may be due to the fact that `docbook_xml**` requires `docbook_xml`  indirectly, as every package requires `docbook_xml51` as this is the only package that creates the `catalog` and `docbook` files.
> ```
> require 'package'
> class Docbook_xml43 < Package
> <...>
>  depends_on 'docbook_xml'
> ```

**Comment by vincowl** [comment]
I am not sure to understand : what you are describing should not lead to install every `docbook_xml**`. `gtk_doc` requires `docbook_xml`. If another package depends on the same one, it is not seen as a dependency otherwise we should install every packages since most of them depends on core packages. I think we should understand why `dockbook_xml` depends on every `dockbook_xml**` and leads to install everything.

**Comment by ThatGeekyWeeb** [comment]
`docbook_xml` is a `is_fake` package which installs all `docbook_xml**`'s

**Comment by ThatGeekyWeeb** [comment]
Not installing every `docbook_xml` version can be avoided, `gtk_doc` needs to be set to depend on only `43`, and `docbook_xml43` needs to be set to depend on `docbook_xml51` instead of `docbook_xml`

**Comment by vincowl** [comment]
Nice ! Do you handle the PR or shall I do this ?

**Comment by ThatGeekyWeeb** [comment]
It's best if you open a PR for it, I'm taking a break from programming for a while.

**Comment by vincowl** [comment]
Just a last question : 

> `docbook_xml` is a `is_fake` package which installs all `docbook_xml**`'s

What's the purpose of this and not installing just a chosen one such as the newest or the "most usefull" (such as 43) ?

**Comment by ThatGeekyWeeb** [comment]
This is just how I did it at the time, as I don't really have a way of knowing what version different packages depend on, as it seems most, if not all, major distros install all versions in the same package.

**Comment by vincowl** [comment]
OK. @uberhacker any thought about this ? Shall we avoid the whole packages installation or do I just handle the PR discussed above ?

**Comment by uberhacker** [comment]
It probably doesn't hurt to include all the versions.  That way, if some package depends on a certain version, it won't result in a 404.  This has been an ongoing issue with some packages that require gtk_doc prior to @ThatGeekyWeeb's update.

**Comment by vincowl** [comment]
Ok, so nothing more to handle here. Closing the issue

**Comment by satmandu** [comment]
```CREW_PATH/etc/xml``` has catalog files which should be populated by the xmlcatalog program, right?

Why is xmlcatalog not being run in a ```self.postinstall``` section?

Shouldn't the code in the docbook installation files go something like this so you don't clobber other cataloged information in those files?

```
  def self.install

    xml_version = '5.1'
    xml_dtd = "xml-dtd-#{xml_version}"

    system "install -v -d -m755 #{CREW_DEST_PREFIX}/share/xml/docbook/#{xml_dtd}"
    system "install -v -d -m755 #{CREW_DEST_PREFIX}/etc/xml"
    system "cp -rpa . #{CREW_DEST_PREFIX}/share/xml/docbook/#{xml_dtd}/"
  end
    
  def self.postinstall
    xml_version = '5.1'
    xml_dtd = "xml-dtd-#{xml_version}"
    
    system "xmlcatalog --noout --create #{CREW_PREFIX}/etc/xml/docbook.xml && \
            xmlcatalog --noout --add 'public' \
                '-//OASIS//DTD DocBook XML V#{xml_version}//EN' \
                'http://www.oasis-open.org/docbook/xml/#{xml_version}/docbookx.dtd' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//DTD DocBook XML CALS Table Model V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/calstblx.dtd' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//DTD XML Exchange Table Model 19990315//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/soextblx.dtd' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ELEMENTS DocBook XML Information Pool V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/dbpoolx.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ELEMENTS DocBook XML Document Hierarchy V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/dbhierx.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ELEMENTS DocBook XML HTML Tables V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/htmltblx.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ENTITIES DocBook XML Notations V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/dbnotnx.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ENTITIES DocBook XML Character Entities V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/dbcentx.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'public' \
                '-//OASIS//ENTITIES DocBook XML Additional General Entities V#{xml_version}//EN' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}/dbgenent.mod' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'rewriteSystem' \
                'http://www.oasis-open.org/docbook/xml/#{xml_version}' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}' \
                #{CREW_PREFIX}/etc/xml/docbook.xml &&
            xmlcatalog --noout --add 'rewriteURI' \
                'http://www.oasis-open.org/docbook/xml/#{xml_version}' \
                'file://#{CREW_PREFIX}/share/xml/docbook/#{xml_dtd}' \
                #{CREW_PREFIX}/etc/xml/docbook.xml"
    
    system "xmlcatalog --noout --create #{CREW_PREFIX}/etc/xml/catalog.xml && \
            xmlcatalog --noout --add 'delegatePublic' \
                '-//OASIS//ENTITIES DocBook XML' \
                'file://#{CREW_PREFIX}/etc/xml/docbook.xml' \
                #{CREW_PREFIX}/etc/xml/catalog.xml &&
            xmlcatalog --noout --add 'delegatePublic' \
                '-//OASIS//DTD DocBook XML' \
                'file://#{CREW_PREFIX}/etc/xml/docbook.xml' \
                #{CREW_PREFIX}/etc/xml/catalog.xml &&
            xmlcatalog --noout --add 'delegateSystem' \
                'http://www.oasis-open.org/docbook/' \
                'file://#{CREW_PREFIX}/etc/xml/docbook.xml' \
                #{CREW_PREFIX}/etc/xml/catalog.xml &&
            xmlcatalog --noout --add 'delegateURI' \
                'http://www.oasis-open.org/docbook/' \
                'file://#{CREW_PREFIX}/etc/xml/docbook.xml' \
                #{CREW_PREFIX}/etc/xml/catalog.xml"
  end
```

**Comment by satmandu** [comment]
Also, we don't set ```ENV['XML_CATALOG_FILES'] = "#{CREW_PREFIX}/etc/xml/catalog"``` as homebrew does, e.g. here: https://github.com/Homebrew/homebrew-core/blob/94f2606854535a6ad4c8009f0b7ac2b2d30cd820/Formula/docbook.rb#L102

Doesn't this break using docbook for lots of formulas?
