### ISSUE TITLE
Package updates

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4421]
If anybody else is interested in helping with package updates, a complete list is available at https://github.com/skycocker/chromebrew/wiki/Updating-existing-packages.

**Comment by satmandu** [comment]
Is there a way to install a package one has built with ```crew build -s``` without putting it up somewhere to download and putting that path into the recipe.rb file?

I'm building new versions of packages, and I'd like to be able to roll back packages if there is a problem with a version I have built, without going through and doing a ```crew install -s```

**Comment by uberhacker** [comment]
@satmandu: You might be able to grab a previous version at https://bintray.com/chromebrew/chromebrew.  There is no guarantee that earlier versions will be available, however, since they don't want us to use up too much space.

**Comment by satmandu** [comment]
Yes, but i'm looking for decent ways to preserve and install packages that _I_ compile.

(This is because I may get library issues as I test different versions of libraries.)

**Comment by uberhacker** [comment]
@satmandu: [This](https://github.com/skycocker/chromebrew/wiki/Creating-a-package#testing-a-pre-compiled-binary) may help.

**Comment by saltedcoffii** [comment]
stale, closing
