### ISSUE TITLE
Remmina wont launch -  libssl.so.47: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leonbollerup** [skycocker/chromebrew#4424]
## Description
Remmina wont launch:

chronos@localhost ~ $ remmina
remmina: error while loading shared libraries: libssl.so.47: cannot open shared object file: No such file or directory

```

## Versions and system information
chromebrew version: 1.4.4

ChromeOS version:
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6884493
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R86-13421.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=13421
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=86
CHROMEOS_RELEASE_DESCRIPTION=13421.53.0 (Official Build) beta-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13421.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13421.53.0


Model: Google Pixelbook i7
Architecture: x86_x64

**Comment by uberhacker** [comment]
Hi @leonbollerup:
You might try recompiling from source: `crew reinstall remmina -s`.  If that doesn't work, we can try an update: https://github.com/FreeRDP/Remmina/archive/v1.4.8.tar.gz

**Comment by leonbollerup** [comment]
Just have posted that i tried that already...

---


chronos@localhost ~ $ remmina
Failed to load plugin: /usr/local/lib64/remmina/plugins/remmina-plugin-rdp.so.
Error: libssl.so.47: cannot open shared object file: No such file or directory
[glibsecret] unable to get secret service: Unknown or unsupported transport “disabled” for address “disabled:”
Plugin entry returned false: /usr/local/lib64/remmina/plugins/remmina-plugin-secret.so.
StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed

(remmina:17386): Gtk-WARNING **: 16:07:43.992: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/gnome/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/gnome/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
chronos@localhost ~ $

**Comment by vincowl** [comment]
@uberhacker We have the same problem with `composer`, `php74`, ..... This workaround does the trick for a while :
``` shell
ln -s /usr/local/lib64/libssl.so.48 /usr/local/lib64/libssl.so.47
ln -s /usr/local/lib64/libcrypto.so.46 /usr/local/lib64/libcrypto.so.45
```

**Comment by leonbollerup** [comment]
That solves one proble.. the orginal anyway... still have:

[glibsecret] unable to get secret service: Unknown or unsupported transport “disabled” for address “disabled:”
Plugin entry returned false: /usr/local/lib64/remmina/plugins/remmina-plugin-secret.so.
StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed

(remmina:30426): Gtk-WARNING **: 16:32:30.739: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/gnome/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/gnome/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

**Comment by vincowl** [comment]
Did you try to reinstall gdk_pixbuf using `crew reinstall gdk_pixbuf` and add the postinstall infos in the .bashrc ?

**Comment by vincowl** [comment]
I have just tested a remmina installation and launch on a fresh install. Cannot reproduce your error on x86_64. everything runs perfectly

**Comment by ThatGeekyWeeb** [comment]
Idk if im right, but this might be due to the fact that we only support the stable channel, and the latest *stable* release.
> ```
> CHROMEOS_RELEASE_CHROME_MILESTONE=86
> ...
> CHROMEOS_RELEASE_TRACK=beta-channel
> ```
iirc 85 is the current stable release

**Comment by vincowl** [comment]
@uberhacker Any hint to solve the missing `libssl.so.47` which doesn't exist anymore since libressl upgrade ? Is it enough to regenerate every binaries ? The `ln -s` trick does the job waiting a better solution

**Comment by leonbollerup** [comment]
Got it working, but guess i have other problems.. it can connect to a remote desktop server.. but all i get is a black screen.. freerdp issue maybe..

**Comment by satmandu** [comment]
> @uberhacker Any hint to solve the missing `libssl.so.47` which doesn't exist anymore since libressl upgrade ?

Can you just do a ```ln -s libssl.so.1.0.0 libssl.so.47```?

That should fix it?

```
chronos@nocturne /usr/local/lib64 $ ln -s libssl.so.1.0.0 libssl.so.47
chronos@nocturne /usr/local/lib64 $ ls -Fl libssl*
-rw-r--r--. 1 chronos chronos 774130 Oct 19 16:28 libssl.a
-rw-r--r--. 1 chronos chronos    965 Oct 19 16:27 libssl.la
lrwxrwxrwx. 1 chronos chronos     16 Oct 19 16:27 libssl.so -> libssl.so.48.0.1
lrwxrwxrwx. 1 chronos chronos     33 Oct 19 16:27 libssl.so.1.0.0 -> /usr/local/lib64/libssl.so.48.0.1
lrwxrwxrwx. 1 chronos chronos     15 Oct 19 23:32 libssl.so.47 -> libssl.so.1.0.0
lrwxrwxrwx. 1 chronos chronos     16 Oct 19 16:27 libssl.so.48 -> libssl.so.48.0.1
-rw-r--r--. 1 chronos chronos 463080 Oct 19 16:28 libssl.so.48.0.1
chronos@nocturne /usr/local/lib64 $ realpath libssl.so.47
/usr/local/lib64/libssl.so.48.0.1
```

(The libressl installs explicitly make a symlink such that libssl.so.1.0.0 is there.)

**Comment by vincowl** [comment]
@satmandu, Already done it. Yes it solves the problem, but it is just a hack. It seems to be something like #4182 and maybe the solution would be to regenerate binaries

**Comment by satmandu** [comment]
@vincowl It isn't a hack. As long as the app can find the libraries, it's all good, I think.

The simple workaround would be to just also create symlinks to support older compiled binaries in the libressl package.

**Comment by satmandu** [comment]
@uberhacker This is my fault. I should have added the other symlink when I updated the libressl package last month.

The last commit should resolve that.

**Comment by satmandu** [comment]
I think the issue is that as new versions of libressl get installed, we need to make sure we preserve symlinks in place of the older libraries.

Libressl by default installs symlinks from the current library to libssl.so.1.0.0 (and similarly for libcrypto).

We should do the same when installing newer versions, that should keep this from happening again.

**Comment by ThatGeekyWeeb** [comment]
They were, before the most recent update to `libressl`
> https://github.com/skycocker/chromebrew/blob/11f126cf936699971110608df146fab75a6ecadd/packages/libressl.rb
> ```ruby
>   def self.install
>    system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
>
>    # remove all files under /etc/ssl (use system's /etc/ssl as is)
>    FileUtils.rm_rf "#{CREW_DEST_DIR}/etc/ssl"
>
>    # add symlink to libcrypto.so.1.0.0
>    FileUtils.ln_s "#{CREW_LIB_PREFIX}/libcrypto.so.45.0.5", "#{CREW_DEST_LIB_PREFIX}/libcrypto.so.1.0.0"
>
>    # add symlink to libssl.so.1.0.0
>    FileUtils.ln_s "#{CREW_LIB_PREFIX}/libssl.so.47.0.6", "#{CREW_DEST_LIB_PREFIX}/libssl.so.1.0.0"
>  end
>end

**Comment by uberhacker** [comment]
It might be as simple as recompiling remmina from source to fix the missing library.  This release is now stable so might be worth a try.

**Comment by ThatGeekyWeeb** [comment]
I believe all the binaries are simply linked against an old version of libressl, the current lib is `libssl.48`. I think that these packages should be statically compiled unless we plan to recompile every package each time a update comes along that changes the lib version, either way, @uberhacker, you are prob correct

**Comment by ThatGeekyWeeb** [comment]
I did some checks, and `libssl.so.47` exists in the latest libressl package, @uberhacker, this can be closed now, as the issue is fixed.
