### ISSUE TITLE
[rsync] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4443]
```
Configure found the following issues:

- Failed to find xxhash.h for xxhash checksum support.

See the INSTALL file for hints on how to install the missing libraries and/or
how to generate (or fetch) man pages:
    https://github.com/WayneD/rsync/blob/master/INSTALL.md

To disable one or more features, the relevant configure options are:
    --disable-xxhash

configure.sh: error: Aborting configure run
rsync failed to build: `./configure` exited with 
```

**Comment by vincowl** [comment]
It should be solved with the updated xxhash version.  I had the same problem and solved it this way

**Comment by uberhacker** [comment]
Still having issues even with the new xxhash version.  See below:
```
./proto.h:296:24: error: unknown type name ‘int32’; did you mean ‘uint32’?
  296 | void send_token(int f, int32 token, struct map_struct *buf, OFF_T offset,
      |                        ^~~~~
      |                        uint32
./proto.h:297:3: error: unknown type name ‘int32’; did you mean ‘uint32’?
  297 |   int32 n, int32 toklen);
      |   ^~~~~
      |   uint32
./proto.h:297:12: error: unknown type name ‘int32’; did you mean ‘uint32’?
  297 |   int32 n, int32 toklen);
      |            ^~~~~
      |            uint32
./proto.h:298:1: error: unknown type name ‘int32’; did you mean ‘uint32’?
  298 | int32 recv_token(int f, char **data);
      | ^~~~~
      | uint32
./proto.h:299:28: error: unknown type name ‘int32’; did you mean ‘uint32’?
  299 | void see_token(char *data, int32 toklen);
      |                            ^~~~~
      |                            uint32
./proto.h:352:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘fuzzy_distance’
  352 | uint32 fuzzy_distance(const char *s1, unsigned len1, const char *s2, unsigned len2);
      |        ^~~~~~~~~~~~~~
./rounding.c: In function ‘main’:
./rounding.c:35:13: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
   35 |  static int test_array[1 - 2 * (ACTUAL_SIZE != EXPECTED_SIZE)];
      |             ^~~~~~~~~~
Failed to create rounding.h!
make: *** [Makefile:119: rounding.h] Error 1
rsync failed to build: `make V=0 -j2` exited with 2
```
Builds fine on armv7l and i686.

**Comment by uberhacker** [comment]
I thought maybe a fresh reinstall would help but not.

**Comment by cstrouse** [comment]
Try adding `./prepare-source` before `./configure`

**Comment by uberhacker** [comment]
Still get the same error @cstrouse.  This is probably the first package I've ever dealt with the doesn't build on x86_64 but builds fine on all the other architectures.

**Comment by vincowl** [comment]
I will have a look at this tomorrow on a fresh install since it compiles fine on my x86_64 arch

**Comment by vincowl** [comment]
@uberhacker I've just tried to install rsync on a fresh install : absolutely no trouble encountered....

**Comment by uberhacker** [comment]
@vincowl:  Same issue after another fresh install for me.  Did you update to 86 yet?

**Comment by vincowl** [comment]
@uberhacker No I didn't....

**Comment by vincowl** [comment]
@uberhacker Still no v86 available on my CAVE machine

**Comment by vincowl** [comment]
@uberhacker Managed to reproduce this. Following errors, I found out that I could no more compile `glibc` from source....

**Comment by vincowl** [comment]
@uberhacker Solved it using this 
```shell
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/opt/bin:
export MANPATH=/usr/local/share/man:/usr/share/man
export PATH="~/.config/bin/:$PATH"
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib64:/usr/local/lib:/usr/lib
```

**Comment by satmandu** [comment]
Isn't someting like ```ENV['LD_LIBRARY_PATH'] = "#{CREW_LIB_PREFIX}:#{ARCH_LIB}:/usr/local/lib:/usr/lib"``` the default for packages?
I'm also noticing an LD_LIBRARY_PATH issue with compiling llvm 10.0.1 on x86_64, so I'm going to try that next.

**Comment by vincowl** [comment]
No trouble since new binaries and a fresh install on x86_64 (using gcc10). Seems OK to me...

**Comment by uberhacker** [comment]
@vincowl:  I'm having the same issue even after a fresh install.  Did you manipulate the paths in any way?  What happens if you simply use the default `export LD_LIBRARY_PATH=/usr/local/lib64`?

**Comment by vincowl** [comment]
@uberhacker It miserably fails. I use in my `~/.bashrc` the following `export LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib64:/usr/local/lib:/usr/lib`

**Comment by uberhacker** [comment]
I have a solution.  PR coming shortly.
