### ISSUE TITLE
xorg_proto failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Ddatadir=/usr/local/lib64 -Dbuildtype=release build` exited with 1

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4479]
## Description
`xorg_proto` install error during installing firefox

If you executed a specific command:
```shell
crew install firefox
```

Output:
```shell
xorg_proto: The xorgproto package provides the header files required to build the X Window system, and to allow other applications to build against the installed X Window system.
https://www.x.org/
version 2020.1
No precompiled binary available for your platform, downloading source...
################################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
The Meson build system
Version: 0.55.3
Source dir: /usr/local/tmp/crew/xorgproto-2020.1.tar.bz2.dir/xorgproto-2020.1
Build dir: /usr/local/tmp/crew/xorgproto-2020.1.tar.bz2.dir/xorgproto-2020.1/build
Build type: native build
Project name: xorgproto
Project version: 2020.1
Using 'CC' from environment with value: 'clang'

meson.build:21:0: ERROR: Unknown compiler(s): [['clang']]
The follow exceptions were encountered:
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang'"

A full log can be found at /usr/local/tmp/crew/xorgproto-2020.1.tar.bz2.dir/xorgproto-2020.1/build/meson-logs/meson-log.txt
xorg_proto failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Ddatadir=/usr/local/lib64 -Dbuildtype=release build` exited with 1
```

## Versions and system information
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6884493
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R86-13421.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=13421
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=86
CHROMEOS_RELEASE_DESCRIPTION=13421.53.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13421.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13421.53.0

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by vincowl** [comment]
Did you try `crew install clang` before ?
Don't know why it isn't part of the dependencies.

**Comment by supechicken666** [comment]
> Did you try `crew install clang` before ?
> Don't know why it isn't part of the dependencies.

But chromebrew doesn’t have this package. Should I use the older version of xorg porto rb first?

**Comment by vincowl** [comment]
Sorry clang is part of the llvm package : bad habit from linux... So try to install `llvm`, then you will have clang available and should be able to install xorg_proto

**Comment by vincowl** [comment]
To invest such error (I mean missing files), you can use `crew whatprovides clang`.

**Comment by supechicken666** [comment]
> Sorry clang is part of the llvm package : bad habit from linux... So try to install `llvm`, then you will have clang available and should be able to install xorg_proto

Thanks! Problem solved.
