### ISSUE TITLE
Cannot start i3

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4480]
I am trying to use i3 package. When running i3, it says `cannot open display` and if I start sommelier, or use `sommelier -X i3`, I have `ERROR: Another window manager seems to be running (X error 10)`. So how do we have to launch i3 please ?

**Comment by supechicken666** [comment]
Use XServer XSDL on Play Store and set up the environment variable (since there isn't any vncserver package yet), remember to run `stopsommelier` before setting the XSDL display variables

**Comment by vincowl** [comment]
Great ! Thanks @supechicken666 !

**Comment by uberhacker** [comment]
Should we add these instructions to the i3 package?

**Comment by vincowl** [comment]
Good idea, I will add a post install message

**Comment by supechicken666** [comment]
> Good idea, I will add a post install message

I am almost done it :)

**Comment by vincowl** [comment]
Perfect ! Less work is fine to me :)
