### ISSUE TITLE
ruby CREW_*_OPTIONS consts not working

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4496]
multiline CREW OPTIONS consts are not working for meson or configure, with the exception of configure when they are given in the same line, e.g. "./confgure #{CREW_OPTIONS}" . If #{CREW_OPTIONS} goes on any other line, there is an error.

#{CREW_MESON_OPTIONS} doesn't work at all. Defaults are nice, but this breaks builds.  Also --host,  --target, and --build doesn't work with meson at all.

recent updates will need to be fixed.

Also, we need to figure out if there is a way of doing this.

Here is how homebrew is doing it:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk+3.rb

**Comment by uberhacker** [comment]
Fixed in #4515.
