### ISSUE TITLE
Unable to install brew

### ISSUE THREAD

**Issue by Xmas118** [skycocker/chromebrew#4533]
I can't request https://raw.github.com/skycocker/chromebrew/master/install.sh
![image](https://user-images.githubusercontent.com/7402329/97264568-2fa1ec00-1860-11eb-8c2d-8b9ce8cd91aa.png)

So, I git the project to my downloads
But, I run 'sudo bash ./install.sh' show
'Chromebrew should not be installed or run as root.
![image](https://user-images.githubusercontent.com/7402329/97264669-59f3a980-1860-11eb-990b-ad09968d4feb.png)

How can i fix it? Thx.

**Comment by uberhacker** [comment]
@Xmas118: You cannot install as root.  Please remove `sudo` and just run `bash install.sh`.  That said, you might want to execute `rm -rf /usr/local` first.

**Comment by supechicken666** [comment]
> I can't request https://raw.github.com/skycocker/chromebrew/master/install.sh
> ![image](https://user-images.githubusercontent.com/7402329/97264568-2fa1ec00-1860-11eb-8c2d-8b9ce8cd91aa.png)
> 
> So, I git the project to my downloads
> But, I run 'sudo bash ./install.sh' show
> 'Chromebrew should not be installed or run as root.
> ![image](https://user-images.githubusercontent.com/7402329/97264669-59f3a980-1860-11eb-990b-ad09968d4feb.png)
> 
> How can i fix it? Thx.

你需要“梯子”

**Comment by saltedcoffii** [comment]
This issue is addressed in the README.md file. Closing issue.
