### ISSUE TITLE
libmbetls is not actually used

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#4542]
> https://github.com/skycocker/chromebrew/blob/91404d2b7f4a62e21ea85374bf8cfcf977cf255c/packages/curl.rb#L39

libmbedtls is not enabled here.
```
./configure  #{CREW_OPTIONS} --disable-maintainer-mode --enable-ares --with-ldap-lib=#{CREW_LIB_PREFIX}/libldap.so --with-lber-lib=#{CREW_LIB_PREFIX}/liblber.so --without-ssl --with-mbedtls
```
is the correct way to do this.

**Comment by uberhacker** [comment]
Right, we can probably remove that dependency now that libressl has been updated.  BTW, there should be no need now to set your `LD_LIBRARY_PATH` to include system paths.  I was able to install crew fresh on my i686 Chromebook with only `LD_LIBRARY_PATH=/usr/local/lib` set and everything worked fine.

**Comment by ThatGeekyWeeb** [comment]
I fear this will reopen the issues adding mbedtls closed, outdated devices won't like properly regardless of the update, iirc that was the whole reason libmbedtls was added....

**Comment by uberhacker** [comment]
See if the latest updates fix things for you and if not, we can revisit this later.

**Comment by ThatGeekyWeeb** [comment]
issues #4292, #4344, #4347, will most likely need to be reopened, as the only foreseeable fix was removed, I'll test, but my kernel does not like `*ssl` and I am certain it will fail.

**Comment by ThatGeekyWeeb** [comment]
you must not understand...
> ```
> $ uname -r
> 3.10.18
> ```
as fresh install won't fix a simple incompatibility with my kernel, it simply does not understand what to do with libressl, or openssl. Oddly only mbedtls and gnutls work.

**Comment by uberhacker** [comment]
Have you tried the new libressl yet?  It is now fully decoupled from the system libraries.

**Comment by ThatGeekyWeeb** [comment]
I did just try it, as I expected it results in a instant death on curl's side. As I stated, libressl just does not work with my kernel, even from a chroot, It can't be used, same for openssl, idk what google did to get it working on my device but It can't be reproduced.

**Comment by ThatGeekyWeeb** [comment]
@uberhacker, What is the status of this? Do you plan to either keep using Libressl and remove the mbedtls dep, or enable mebedtls?

**Comment by uberhacker** [comment]
Hi @ThatGeekyWeeb:  My plan was to deal with it on the next update.  cURL is an active project so I don't expect it will be long until the next release.  BTW, I was able to install crew fresh on my armv7l Hisense C11 Chromebook (jerry) and i686 Samsung Series 5 Chromebook (alex-he) that are both running a 3.18 kernel without issue.  The curl command works fine.  Make sure you don't have anything that sets extra paths in your `~/.bashrc`.  The output of `echo $LD_LIBRARY_PATH` should be `/usr/local/lib` and nothing else.  If you have other libraries, that could affect command execution.

**Comment by ThatGeekyWeeb** [comment]
How odd... I need to do a cleanup on my custom XBPS chroot, soon anyway, so I'll test it soon.

**Comment by uberhacker** [comment]
My guess is since you are using an older ChromeOS release, that may the difference here.  Although, I'm stuck on release 58 for my i686 Chromebook.  The armv7l Chromebook reached EoL at release 84.

**Comment by uberhacker** [comment]
FWIW, you can buy either of the Chromebooks I mentioned for under $100 now.

**Comment by ThatGeekyWeeb** [comment]
I reached EoL at release 77, and SSL problems everywhere, with nearly everything, my particular one uses a 3.10.18 kernel, and I figure it's missing proper support/firmware for ssl.

**Comment by uberhacker** [comment]
Yeah, that is a bit older than the 3.18 kernel.  That could be the issue.

**Comment by ThatGeekyWeeb** [comment]
Note that actual testing requires `curl`-ing a item on a `https` curl, with a ssl linked `curl` this results in it simply returning `killed`.
I am currently testing as we speak.

**Comment by ThatGeekyWeeb** [comment]
The error still exists sadly. The below screenshot shows the exact result. 
Note that it should return the HTML of this website.
![image](https://user-images.githubusercontent.com/59572686/99097179-42792800-25a5-11eb-92e3-a3104c591609.png)

**Comment by uberhacker** [comment]
Did you test after a fresh install?
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by ThatGeekyWeeb** [comment]
Yes I did test after fresh install, note that I have chroot inside `/usr/local/chroot`, so I grabbed the script and edited it to remove the `chown` part. Below is a screenshot of me preforming a fresh install & a test.
![image](https://user-images.githubusercontent.com/59572686/99099234-23c86080-25a8-11eb-9558-71692ed2096f.png)

**Comment by uberhacker** [comment]
Try adding `export LD_LIBRARY_PATH=/usr/local/lib` in your `~/.bashrc`, exit the cros shell session, enter again and repeat the process.  Also, don't use `&>/dev/null` because that will hide any errors which is the whole point of this exercise (to catch errors if they occur).

**Comment by ThatGeekyWeeb** [comment]
I tested twice, there are no errors, curl is broken due to my kernels incompatibly with ssl, note that I ran `export LD_LIBRARY_PATH=/usr/local/lib` in the Screenshot I provided and a putting in my bashrc will make no difference, `ld` will use whatever path if find in `$LD_LIBRARY_PATH`, when it is set, does not matter.

**Comment by uberhacker** [comment]
`LD_LIBRARY_PATH` definitely matters a lot.  If you don't have the `/usr/local/lib` path first, it will use the system version instead and that will most certainly break many commands.

**Comment by ThatGeekyWeeb** [comment]
![image](https://user-images.githubusercontent.com/59572686/99104775-71949700-25af-11eb-9422-7b41f1b85aa1.png)

**Comment by ThatGeekyWeeb** [comment]
@uberhacker, the best possible fix is to create 2 curl packages, one for LiberSSL and one for MbedTLS, then inside the `install.sh` file, simple do a check to see if the kernel is less then 3.18 since it works on your device.

**Comment by uberhacker** [comment]
But that would mean we have to support earlier versions.  I don't want to do that for the %0.01 of users like yourself. :)

**Comment by ThatGeekyWeeb** [comment]
Supporting as many versions/devices of ChromeOS as possible is the best way to go abt this, eitherway, what is your plan for fixing this? @uberhacker

**Comment by uberhacker** [comment]
Like I said earlier, I don't have the time or energy to support older releases and that is especially if Google no longer supports.  You are in YMMV territory.

**Comment by ThatGeekyWeeb** [comment]
Understood, closing this then, but the mbedtls dep should still be removed. @uberhacker
