### ISSUE TITLE
Cannot install freetype / harfbuzz

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4544]
There is a cycling dependency between freetype and harbuzz since @satmandu 's update #4456 . Indeed activating `graphite` dependency creates a loop since graphite depends on freetype.

**Comment by vincowl** [comment]
Solution could be : remove `freetype` dependency in `graphite` since it builds without it

**Comment by uberhacker** [comment]
Fixed in #4550.

**Comment by satmandu** [comment]
Sorry I missed commenting on this. Adding just the freetype_sub depend was also how I fixed graphite locally.
