### ISSUE TITLE
Python3 initial install on docker gives error

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4545]
Is this an issue with the pip portion being non-interactive?

Once I run ```crew install python3``` interactively at the prompt it works fine.

docker script being used: https://gist.github.com/satmandu/791dd6e982d365dda6bbba5c332f0f73

Here's the command in full I am using:
```chromeos_docker.sh https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13421.73.0_nocturne_recovery_stable-channel_mp.bin.zip nocturne 86```

```
python3: Python is a programming language that lets you work quickly and integrate systems more effectively.
https://www.python.org/
version 3.8.6
Precompiled binary available, downloading...
######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...

Upgrading pip...
/usr/local/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
python3 failed to install: `pip3 install --upgrade pip` exited with 127
```

**Comment by uberhacker** [comment]
I haven't noticed that yet.  Did you target the correct path in your Docker container?  Maybe you are in a i686 environment and looking for `/usr/local/lib64` instead of `/usr/local/lib`?

**Comment by skiman6010** [comment]
I can confirm this exact same issue using both the nocturne image and atlas image.

**Comment by uberhacker** [comment]
Definitely appears to be Docker related.  Fresh installs on actual Chromebook hardware work fine.

**Comment by satmandu** [comment]
Fantastic to hear that this is only a docker issue.

**Comment by uberhacker** [comment]
Solved with the latest python3 update?

**Comment by satmandu** [comment]
Actually currently running this in docker to make it work:
```
RUN sed -i "s%LD_LIBRARY_PATH%sudo $CREW_PREFIX/sbin/ldconfig $CREW_PREFIX/etc/ld.so.conf ; LD_PRELOAD=$CREW_LIB_PREFIX/libpython3.9.so.1.0 LD_LIBRARY_PATH%g" /usr/local/lib/crew/packages/python3.rb && \
(yes | crew install python3 || true ) 
```
This is of course annoying, but not terrible.

**Comment by satmandu** [comment]
Current working setup at https://gist.github.com/satmandu/791dd6e982d365dda6bbba5c332f0f73
