### ISSUE TITLE
Issues with installing gnome_keyring due to Pango failure from CFLAGS='-fuse-ld=lld'

### ISSUE THREAD

**Issue by espoelstra** [skycocker/chromebrew#4553]
I'm trying to install `libsecret` to use it with `git` as `git-credential-libsecret`. I ended up having to clone the actual `git` source and compile the `libsecret` helper under the [`contrib/credential/libsecret` helper](https://github.com/git/git/tree/master/contrib/credential/libsecret), but to USE `libsecret` and `secret-tool` you also need `dbus-x11` and it turns out you won't have an `org.freedesktop.secrets` daemon unless you run `gnome-keyring-daemon`. Therefore I was trying to install `gnome_keyring` with the below and got some errors, though they cleared up after a `crew upgrade` but I'm not sure if that was expected behavior.

    crew install gnome_keyring

```
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
The Meson build system
Version: 0.55.3
Source dir: /usr/local/tmp/crew/pango-1.47.0.tar.xz.dir/pango-1.47.0
Build dir: /usr/local/tmp/crew/pango-1.47.0.tar.xz.dir/pango-1.47.0/builddir
Build type: native build
Project name: pango
Project version: 1.47.0
Using 'CFLAGS' from environment with value: '-fuse-ld=lld'

meson.build:1:0: ERROR: Unable to determine dynamic linker

A full log can be found at /usr/local/tmp/crew/pango-1.47.0.tar.xz.dir/pango-1.47.0/builddir/meson-logs/meson-log.txt
pango failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Dmandir=/usr/local/share/man -Dbuildtype=release -Dinstall-tests=false builddir` exited with 1
```

Ran `crew upgrade` and only upgraded `gcc10 zstd lz4` but running `crew install gnome_keyring` again seemed to be working?

**Comment by uberhacker** [comment]
@espoelstra: Is this still an issue for you after the latest updates?

**Comment by ThatGeekyWeeb** [comment]
> ```
> Unable to determine dynamic linker
> ```
This means `lld` is missing, pleas install the llvm package.

**Comment by ThatGeekyWeeb** [comment]
This can likely be closed due to lack of response.
