### ISSUE TITLE
Forced coloring of the output of `crew list installed` messes with the ability to pass that output to `crew remove`

### ISSUE THREAD

**Issue by espoelstra** [skycocker/chromebrew#4554]
I wanted to clean up a large number of packages that had been pulled in as dependencies, but when trying to run `crew remove -v $(crew list installed)` it was printing out that `Package sommelier not installed`, but I know it was because it was definitely in the list. It was only after I tried passing it through `xargs` that I realized the issue was the coloring and not the package naming or anything.

Using the below to strip the ANSI color sequences worked, though a little too well because I was piping the entire output of `crew list installed` to `crew remove` and at some point it removed some packages `crew` itself depends on. https://superuser.com/a/380778/333828

     crew list installed | sed 's/\x1b\[[0-9;]*m//g' | xargs -n1 -I{} bash -c 'crew remove -v '{}

Thank goodness for `crewfix`, except that apparently it doesn't handle a missing libssl, though it can fix libssp and gcc.

**Comment by uberhacker** [comment]
@espoelstra: Thank you for the feedback.  If you want to remove everything, I would recommend a fresh install instead.  The problem with doing it this way is it uninstalls "core" packages necessary to execute crew commands.  If you want to start over, I would recommend the following:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```

**Comment by espoelstra** [comment]
Yeah, I figured that out after attempting to recover and running into a lot of library issues due to the system cache.

I had installed some stuff via `dev_install` and some via Chromebrew so I didn't want to blow everything away.

The colors causing issues for scripting was probably the bigger concern in this case.

**Comment by cstrouse** [comment]
We can check if the current session is interactive before enabling colored output using `$stdout.isatty`.

**Comment by kjperkin** [comment]
This issue is ancient, but for the sake of completeness: I recently added an option to suppress color in the output (#4996). @uberhacker This issue can be closed now.
