### ISSUE TITLE
During the install of chromebrew, `ldconfig` fails on many configs

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#4560]
During the installation of chromebrew with the `curl <link> | bash`, the script calls the install of buildessential. During some point in every package's post-install until either `isl` or `glibc` (I can't tell) this error occurs:
`sh: 1: /usr/local/sbin/ldconfig: not found`
This problem appears to be new as of Novemeber. Is this something to worry about?

chromebrew version: 1.5.1

ChromeOS:
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6857068
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v19keys
CHROMEOS_RELEASE_BRANCH_NUMBER=93
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R85-13310.93.0
CHROMEOS_RELEASE_BUILD_NUMBER=13310
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=85
CHROMEOS_RELEASE_DESCRIPTION=13310.93.0 (Official Build) stable-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v19
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13310.93.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13310.93.0
```

Model: DROID (Acer 314)

Architecture: x86_64

**Comment by uberhacker** [comment]
This is because glibc is not installed yet.  @satmandu: What we need to do is install glibc before any other packages are installed.  Do you want to take a shot at fixing this?

**Comment by satmandu** [comment]
Just a matter of modifying the order in buildessential.rb, right?

**Comment by uberhacker** [comment]
That could work as long as glibc is installed first.
