### ISSUE TITLE
[Suggestion] Use Skype deb repo instead of downloading deb on official website

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#4565]
The `skypeforlinux-64.deb` checksum will probably wrong when Microsoft pushes a new version (The file name won't change when Microsoft update it)
Using `https://repo.skype.com/deb/` repo can make sure getting the correct version according to the checksum

**Comment by uberhacker** [comment]
Seems reasonable to me if Skype actually works.

**Comment by uberhacker** [comment]
Fixed in #4564.
