### ISSUE TITLE
[libssh2] libssl.so.1.0.0 object file is missing when using precompiled binary

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#4571]
```shell
mc: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
Problem solved when building from source

**Comment by Warrentheo** [comment]
I also am running into this issue, and currently it has broken my chromebrew install...  I am afraid I am fairly computer literate, but don't have much experience with building from source...  Would it be possible to get you to point me in the correct direction for how you solved it?

**Comment by uberhacker** [comment]
@Warrentheo: We only support the ChromeOS stable channel.  Please provide the output of `cat /etc/lsb-release`, your Chromebook model and architecture.

**Comment by supechicken** [comment]
> I also am running into this issue, and currently it has broken my chromebrew install... I am afraid I am fairly computer literate, but don't have much experience with building from source... Would it be possible to get you to point me in the correct direction for how you solved it?

Just add -s option at install
```shell
crew reinstall -s libssh2
```

**Comment by Warrentheo** [comment]
@supechicken Thank you, that fixed it :-D

@uberhacker I am running latest stable 'rammus' x86 image on a MS Surface Pro 3...
