### ISSUE TITLE
Need X fonts package to prevent some xorg app font complaints

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4589]
The standard install doesn't include needed xorg fonts.
Pretty sure this is why I get errors like this as per [stackexchange](https://unix.stackexchange.com/questions/407710/xterm-can-not-load-font-misc-fixed-medium-r-semicondensed-13-120-75-75-c-60-i):
```
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
```
I think we need some version of ports of these arch pkgbuilds to get the standard x fonts:
https://github.com/archlinux/svntogit-packages/blob/master/xorg-fonts-100dpi/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/master/xorg-fonts-75dpi/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/master/xorg-fonts-type1/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/master/xorg-fonts-cyrillic/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/master/xorg-fonts-misc/trunk/PKGBUILD

(I hope I'm not missing any)

We may also need an alias package like this:
https://github.com/archlinux/svntogit-packages/raw/packages/xorg-fonts-alias/trunk/PKGBUILD

I've adapted that one thus:

```
# Adapted from Arch Linux xorg-fonts-alias PKGBUILD at:
# https://github.com/archlinux/svntogit-packages/raw/packages/xorg-fonts-alias/trunk/PKGBUILD

require 'package'

class Xorg_fonts_alias < Package
  description 'X.org font alias files'
  version '1.0.4'
  compatibility 'all'
  source_url 'https://xorg.freedesktop.org/releases/individual/font/font-alias-1.0.4.tar.bz2'
  source_sha256 'f3111ae8bf2e980f5f56af400e8eefe5fc9f4207f4a412ea79637fd66c945276'

  depends_on 'xorg_util_macros'

  def self.build
    system "./configure #{CREW_OPTIONS} --with-fontrootdir=#{CREW_PREFIX}/share/fonts"
    system "make"
  end
  def self.install
    system "DESTDIR=#{CREW_DEST_DIR} make -C 100dpi install"
    system "DESTDIR=#{CREW_DEST_DIR} make -C 75dpi install"
    system "DESTDIR=#{CREW_DEST_DIR} make -C cyrillic install"
    system "DESTDIR=#{CREW_DEST_DIR} make -C misc install"
  end
end
```

Maybe this could all be squashed into one package?

**Comment by ThatGeekyWeeb** [comment]
Did some research, and it seems to mostly be a meta package, which installs multiple adobe fonts
> https://github.com/void-linux/void-packages/blob/master/srcpkgs/xorg-fonts/template

> ```
> depends="encodings>=1.0.4 font-adobe-100dpi>=1.0.3 font-adobe-75dpi>=1.0.3
> font-adobe-utopia-100dpi>=1.0.4 font-adobe-utopia-75dpi>=1.0.4
> font-adobe-utopia-type1>=1.0.4 font-bh-100dpi>=1.0.3 font-bh-75dpi>=1.0.3
> font-bh-lucidatypewriter-100dpi>=1.0.3 font-bh-lucidatypewriter-75dpi>=1.0.3
> font-bh-ttf>=1.0.3 font-bh-type1>=1.0.3 font-bitstream-100dpi>=1.0.3
> font-bitstream-75dpi>=1.0.3 font-bitstream-type1>=1.0.3 font-cursor-misc>=1.0.3
> font-daewoo-misc>=1.0.3 font-dec-misc>=1.0.3 font-ibm-type1>=1.0.3
> font-isas-misc>=1.0.3 font-jis-misc>=1.0.3 font-misc-misc>=1.1.2
> font-mutt-misc>=1.0.3 dejavu-fonts-ttf"
> ```

This will likely not be a single PR package... Someone should package each of these fonts one by one, and then create a fake package that installs them all.

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: Could that someone be you? ;)

**Comment by ThatGeekyWeeb** [comment]
I might look into that, but I won't be able to test anything, as I'm currently doing everything from a custom chroot I've made.

**Comment by satmandu** [comment]
Is there a good default way to download multiple source URLs with hashes for a package?

Otherwise this gets very unwieldy.

For instance, for a notional 100dpi package,

we need to install from all of:
https://xorg.freedesktop.org/releases/individual/font/font-adobe-100dpi-1.0.3.tar.bz2
https://xorg.freedesktop.org/releases/individual/font/font-adobe-utopia-100dpi-1.0.4.tar.bz2
https://xorg.freedesktop.org/releases/individual/font/font-bh-100dpi-1.0.3.tar.bz2
https://xorg.freedesktop.org/releases/individual/font/font-bh-lucidatypewriter-100dpi-1.0.3.tar.bz2
https://xorg.freedesktop.org/releases/individual/font/font-bitstream-100dpi-1.0.3.tar.bz2

arch does this:
```
source=(${url}/releases/individual/font/font-adobe-100dpi-1.0.3.tar.bz2
        ${url}/releases/individual/font/font-adobe-utopia-100dpi-1.0.4.tar.bz2
        ${url}/releases/individual/font/font-bh-100dpi-1.0.3.tar.bz2
        ${url}/releases/individual/font/font-bh-lucidatypewriter-100dpi-1.0.3.tar.bz2
        ${url}/releases/individual/font/font-bitstream-100dpi-1.0.3.tar.bz2)
md5sums=('1347c3031b74c9e91dc4dfa53b12f143'
         '66fb6de561648a6dce2755621d6aea17'
         '9f11ade089d689b9d59e0f47d26f39cd'
         'c8b73a53dcefe3e8d3907d3500e484a9'
         '6b223a54b15ecbd5a1bc52312ad790d8')

build() {
  cd "${srcdir}"
  for dir in font-*-100dpi*; do
    if [ -d "${dir}" ]; then
      pushd ${dir}
      ./configure --prefix=/usr \
          --with-fontdir=/usr/share/fonts/100dpi
      make
      popd
    fi
  done
}
```

**Comment by ThatGeekyWeeb** [comment]
I think, to limit the amount of work I need to do, for now only 100dpi fonts will be packaged, I am currently working on it myself @uberhacker. This is going to be a fake package installing many fonts which will be added in many upcoming PR's, it's better to keep it one package per PR.

**Comment by satmandu** [comment]
@ThatGeekyWeeb Maybe put the dpi in the package name? That way we could just use those as templates for the other dpi fonts...

**Comment by ThatGeekyWeeb** [comment]
Thats everything minus `dejavu-fonts-ttf`, `xorg-fonts-alias`, and a fake package for all of these fonts.

**Comment by ThatGeekyWeeb** [comment]
Since this was closed I'm guessing the issue is fixed by the fonts I added from the PR's, perfect!

**Comment by satmandu** [comment]
Yes! The PRs completely fix these issues!
