### ISSUE TITLE
Package Request - Parsec

### ISSUE THREAD

**Issue by EvidenceRepulsive151** [skycocker/chromebrew#4593]
Parsec is a remote desktop application made specifically for cloud gaming. I and many people will probably enjoy being able to play demanding games on their Chromebooks without any containers or virtual machines.

**Comment by supechicken** [comment]
This package is added now:)

**Comment by EvidenceRepulsive151** [comment]
Thank you!

This is off-topic, but are Chromebrew packages integrated into Chrome OS? I mean, are they shown in the search menu thing (whatever that shows up when you press the search key on the keyboard)?

**Comment by supechicken** [comment]
We need for someone to achieve it:) See #4341
