### ISSUE TITLE
Add tags to repo to improve discoverability

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#460]
Github just added a new repo tagging feature to help categorize projects and make them more discoverable called [topics](https://github.com/blog/2309-introducing-topics). I've added a few to my fork and think it would be a good idea to get some added to the main repo.

The following would make good choices for topics to add:
- chromebook
- chromebox
- chromebrew
- chromeos
- chromiumos
- package-manager
- cloudready

**Comment by jam7** [comment]
Nice idea.  Maybe it is possible to add `cloudready` too.  I've just installed it and chromebrew.

**Comment by thedamian** [comment]
It looks like skycocker will have to do this. I don't have access to this.

but it looks like he already added: chromeos, chromebook, crew, linux, package-manager
