### ISSUE TITLE
Chromebrew fails trying to install python3

### ISSUE THREAD

**Issue by jvadair** [skycocker/chromebrew#4618]
## Description
I was running the install command, and it failed trying to install python. I then ran the following command to try and get python, and it gave the following output.

```shell
crew install python3
```

Output:
```shell
/usr/local/bin/crew:98:in `print_package': undefined method `any?' for nil:NilClass (NoMethodError)
	from /usr/local/bin/crew:121:in `set_package'
	from /usr/local/bin/crew:199:in `block in search'
	from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
	from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
	from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
	from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
	from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
	from /usr/local/bin/crew:198:in `search'
	from /usr/local/bin/crew:1005:in `block in install_command'
	from /usr/local/bin/crew:1003:in `each'
	from /usr/local/bin/crew:1003:in `install_command'
	from /usr/local/bin/crew:1089:in `<main>'
```

## Versions and system information
chromebrew: `1.5.1`

ChromeOS: `13421.99.0`

Model: HP Chromebook 11 G5 EE

Architecture: `x86_64`

**Comment by uberhacker** [comment]
@jvadair: Try `crew update && crew upgrade && crew install python3`.  I assume you already have a fresh Chromebrew install?

**Comment by mel0n** [comment]
I am getting that exact same error for all packages. /i am also on an x86_64 based chomebook (samsung, intel Celeron N4000) I just installed chromebrew (1.5.1) and I tried python3 and got the exact same output. Same for VIM and nano:
`crew install nano
Traceback (most recent call last):
        12: from /usr/local/bin/crew:1089:in `<main>'
        11: from /usr/local/bin/crew:1003:in `install_command'
        10: from /usr/local/bin/crew:1003:in `each'
         9: from /usr/local/bin/crew:1005:in `block in install_command'
         8: from /usr/local/bin/crew:198:in `search'
         7: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
         6: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
         5: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
         4: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
         3: from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
         2: from /usr/local/bin/crew:199:in `block in search'
         1: from /usr/local/bin/crew:121:in `set_package'
/usr/local/bin/crew:98:in `print_package': undefined method `any?' for nil:NilClass (NoMethodError)`

running the command sequence suggested by uberhacker produced a different output:
`crew update && crew upgrade && crew install python3
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at e6509cb4 Add pre-built binaries for packages e-x (#4612)
Package lists, crew, and library updated.
Generating compatible packages...
Traceback (most recent call last):
        12: from /usr/local/bin/crew:1089:in `<main>'
        11: from /usr/local/bin/crew:1062:in `update_command'
        10: from /usr/local/bin/crew:397:in `update'
         9: from /usr/local/bin/crew:181:in `generate_compatible'
         8: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
         7: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
         6: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
         5: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
         4: from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
         3: from /usr/local/bin/crew:184:in `block in generate_compatible'
         2: from /usr/local/bin/crew:117:in `set_package'
         1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /usr/local/lib/crew/packages/libhandy.rb:23: syntax error, unexpected end-of-input, expecting `end' (SyntaxError)`

**Comment by jvadair** [comment]
I'm also receiving the same output as mel0n, and yes, this is a fresh chromebrew install, in fact it is also a fresh dev mode install.

**Comment by satmandu** [comment]
@jvadair Does a ```crew update``` help at all?

**Comment by satmandu** [comment]
@jvadair @mel0n Sorry everyone, this is due to a file that was added with an incorrect copy from my system.

**Comment by satmandu** [comment]
Until this is resolved this is a workaround to get crew working again:

```
cd /usr/local/lib/crew/packages
curl -OLf https://github.com/skycocker/chromebrew/raw/b7cac9d430b16ac41fff5560a9981b66a29a3bff/packages/libhandy.rb
```
