### ISSUE TITLE
[sommelier] Issue with restartsommelier

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4646]
```
$ restartsommelier
cat: /usr/local/var/run/sommelier-wayland.pid: No such file or directory
cat: /usr/local/var/run/sommelier-wayland.pid: No such file or directory
cat: /usr/local/var/run/sommelier-wayland.pid: No such file or directory
sommelier processes running: 
```
Trying to cat? a non-existent file and no process id shown.

**Comment by uberhacker** [comment]
This works after recompiling all the dependencies, however, the `cat: /usr/local/var/run/sommelier-wayland.pid: No such file or directory` lines still remain.

**Comment by satmandu** [comment]
That's part of the logic to check for an existing wayland session.

I can fix this...
