### ISSUE TITLE
How to change CREW_PREFIX at install?

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4671]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Is there an option in `install.sh` that change the CREW_PREFIX location?
Just seen `install.sh` and found this part that about custom prefix
```shell
if [[ "${CREW_PREFIX}" != "/usr/local" ]]; then
  echo "Since you have installed Chromebrew in a directory other than '/usr/local',"
  echo "you need to run these commands to complete your installation:"
  echo "echo 'export CREW_PREFIX=${CREW_PREFIX}' >> ~/.bashrc"
  echo "echo 'export PATH=\"\${CREW_PREFIX}/bin:\${CREW_PREFIX}/sbin:\${PATH}\"' >> ~/.bashrc"
  echo "echo 'export LD_LIBRARY_PATH=${CREW_PREFIX}/lib${LIB_SUFFIX}' >> ~/.bashrc"
  echo 'source ~/.bashrc'
  echo
fi
```

Thanks!
## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by satmandu** [comment]
Changing CREW_PREFIX is massively massively broken. Don't bother. [I took a look at it](https://github.com/skycocker/chromebrew/pull/4546), but it would be a LOT of work to get working correctly.

Not least of the problems is that many apps aren't written to be installed elsewhere, and building & packaging programs when using an alternate CREW_PREFIX is a huge pain.

**Comment by supechicken666** [comment]
Can we use symlink or something like `chroot` to redirect `/usr/local/*` to custom prefix?

**Comment by satmandu** [comment]
You can use a chroot, but that's fundamentally a different way of doing things than what the brew variants are doing.
The Crouton project uses chroots, and it works well.

(I actually setup a chroot to my ubuntu partition too, which I also invoke from chromebrew... though it crashes the machine when I suspend the device.)

You can actually use a combo of chromebrew & crouton as well. For instance, you could run sommelier from chromebrew, and then just bind mount the Xauthority files into a crouton chroot and use X apps normally from your chroot.

**Comment by ThatGeekyWeeb** [comment]
I may fork your fork and continue trying @satmandu, I just need to finish my current project of getting a working custom kernel.

**Comment by satmandu** [comment]
@satmandu Please go ahead. Also let me know how your custom kernel work goes? I really need to get a newer kernel on my machine. Bonus points for getting the current google 5.4 tree working! 😁

**Comment by ThatGeekyWeeb** [comment]
Custom kernel works well! Booting it with ChromeOS, seems to not work though, luckily I have 2 Chromebooks, I can't test any newer kernels though as my device uses a Nvidia CPU/GPU, and the firmware for it is only in the 3.10 branch. I'll start working on it soon
