### ISSUE TITLE
[xwayland] - Failed to build

### ISSUE THREAD

**Issue by leonbollerup** [skycocker/chromebrew#4714]
chronos@localhost ~ $ crew upgrade libressl xwayland
libressl: LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, improving security, and applying best practice development processes.
https://www.libressl.org/
version 3.2.2
libressl is already up to date.
xwayland: X server configured to work with weston or sommelier
https://x.org
version 1.20.10
Updating xwayland...
The following packages also need to be installed: 
lzma 
Do you agree? [Y/n] y
Proceeding...
lzma: LZMA Utils are legacy data compression software with high compression ratio.
https://tukaani.org/lzma/
version 4.32.7-1
Precompiled binary available, downloading...
############################################################################################################################################################# 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
No precompiled binary available for your platform, downloading source...
                      -=O=-                                                                                                       #         #       #     #        
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Downloading patch1
patch1 archive downloaded
patching file glamor/glamor_egl.h
patching file glamor/glamor_priv.h
patching file hw/xwayland/xwayland-glamor-eglstream.c
patching file hw/xwayland/xwayland-glamor-gbm.c
patching file hw/xwayland/xwayland-glamor.c
Downloading patch2
patch2 archive downloaded
patching file hw/xwayland/xwayland-glamor-gbm.c
Hunk #1 succeeded at 201 (offset -15 lines).
Hunk #2 succeeded at 216 (offset -15 lines).
Downloading patch3
patch3 archive downloaded
patching file config/udev.c
patching file include/dix-config.h.in
Hunk #1 succeeded at 521 with fuzz 2 (offset 15 lines).
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: cannot import name 'load_entry_point' from 'pkg_resources' (unknown location)
xwayland failed to install: `meson setup build` exited with 1

... Seems to be problem with meson in other context

**Comment by satmandu** [comment]
Try a ```crew reinstall -s meson``` first?

**Comment by leonbollerup** [comment]
> crew reinstall -s meson

meson: The Meson Build System
http://mesonbuild.com/
version 0.55.3
Downloading source...
############################################################################################################################################################# 100.0%    -=O=-                                                                               #            #           #          #                                      
Archive downloaded
Unpacking archive using 'tar', this may take a while...
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup
ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
meson failed to install: `python3 setup.py install --prefix /usr/local --root /usr/local/tmp/crew/dest` exited with 1

**Comment by leonbollerup** [comment]
If its any help, this is the list of things that can't be upgraded.. all seems to relate around meson of some sort..

---

libva could be updated from 2.6.1 to 2.9.0
fribidi could be updated from 1.0.9 to 1.0.10
buildessential could be updated from 1.6 to 1.8
sommelier could be updated from 1382ce084cc407 to 20201025-2
libsecret could be updated from 0.20.3 to 0.20.4
libsoup could be updated from 2.63.90 to 2.72
glib_networking could be updated from 2.57.3 to 2.66.0
mesa could be updated from 20.2.0 to 20.3.0
gobject_introspection could be updated from 1.66.1 to 1.66.1-1
xwayland could be updated from 1.20.9-1 to 1.20.10

**Comment by satmandu** [comment]
Your meson should now be fixed, but some of those will use lld from llvm, so installing ```llvm``` should hopefully take care of the rest... But the fuse option to enable lld in gcc, might require gcc10, so you might want to install that and make sure your default compiler is gcc10.

**Comment by uberhacker** [comment]
@leonbollerup: What is your architecture and system specs?  Are you using a Chromebook or CloudReady?  The more detailed info you can give us, the more detailed help we can provide.
```
$ arch
$ cat /etc/lsb-release
```

**Comment by leonbollerup** [comment]
> @leonbollerup: What is your architecture and system specs? Are you using a Chromebook or CloudReady? The more detailed info you can give us, the more detailed help we can provide.
> 
> ```
> $ arch
> $ cat /etc/lsb-release
> ```

I'm running on a PixelBook i7, latest beta, dev. mode (logically) - i'm getting the same errors on a Pixelbook i5, stable branch.

---

chronos@localhost / $ arch
x86_64
chronos@localhost / $ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6942651
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=33
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R87-13505.33.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.33.0 (Official Build) beta-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.33.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.33.0

**Comment by uberhacker** [comment]
Right, so you are in YMMV territory since you are not on the stable channel.  We have recent pre-built binaries for this package.  Have you tried installing this normally without building from source?

**Comment by ThatGeekyWeeb** [comment]
87 is now stable, if this is still a issue it would be looked into.

**Comment by satmandu** [comment]
Is anyone still having an issue with this? Can we close it?
