### ISSUE TITLE
Packages need a pkgver & pkgrel variable

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4737]
Currently packages have a single version variable which combines source package version and a package release version.

This keeps us from being able to use a package variable throughout the package file, since a bumped release version would change the package version variable.

I suggest that we use a revision variable like homebrew uses.
e.g.: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docbook.rb#L102

We default to assuming revision = 1 unless otherwise specified (just like compatibility _should default to 'all'_ unless otherwise specified.)

Then revision would increase monotonically with edits of the package file for the same source package version.

At a minimum, this would require changing 
```
class Package
  property :description, :homepage, :version, :compatibility, :binary_url, :binary_sha1, :binary_sha256, :source_url, :source_sha1, :source_sha256, :is_fake
```
to 
```
class Package
  property :description, :homepage, :version, :revision, :compatibility, :binary_url, :binary_sha1, :binary_sha256, :source_url, :source_sha1, :source_sha256, :is_fake
```

**Comment by uberhacker** [comment]
Keep in mind that if you make this change, ALL 1300+ packages will need this added.  I did this back in May with compatibility.

**Comment by satmandu** [comment]
@uberhacker Why can't we set a default property value so all packages don't have to be updated?
You would have to have some sort of  ```@revision ||= '1'``` somewhere, no?

**Comment by uberhacker** [comment]
That's a good question.  I'm not sure.
