### ISSUE TITLE
[aria2] binaries don't work on x86_64

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#4741]
```bash
chronos@localhost / $ aria2 -i in

12/10 09:15:30 [NOTICE] Downloading 4 item(s)
aria2c: SocketCore.cc:987: bool aria2::SocketCore::tlsHandshake(aria2::TLSContext*, const string&): Assertion `0' failed.
Aborted (core dumped)
```

**Comment by uberhacker** [comment]
This doesn't surprise me with all the changes we have made recently.  Thank you for the report @cstrouse.  I imagine there is an update available for this package anyway?

**Comment by uberhacker** [comment]
Nope, no update available yet.  We'll just need to generate new binaries.  Does compiling from source still work?

**Comment by cstrouse** [comment]
Yes, building from source is successful and the few commands that I tested worked properly.

**Comment by saltedcoffii** [comment]
Here's a binary package I built and tested; it works on my computer. Someone with the authority can add it to bintray and close this issue (hopefully)
https://mega.nz/file/LaJDlKhK#TN3mneu7gx_ydBlmZ4gu9jn6B_aw659YSq7oqhFGAdI
SHA256: `07133484ac7f8b708dafc40ed461c5bb46f35df023425abb29036ff2f9a26c2c`
