### ISSUE TITLE
Parsec doesn't work

### ISSUE THREAD

**Issue by EvidenceRepulsive151** [skycocker/chromebrew#4743]
## Description
Chromebrew tries to download the Raspberry Pi version of Parsec for x64 and vice versa, resulting in an `Exec format error`. https://github.com/skycocker/chromebrew/blob/3820a0ccbb7b350888714c85cb8fb8562470a5b2/packages/parsec.rb#L18-L31

## Versions and system information
chromebrew: `1.5.1`

ChromeOS: `Stable 87`

Model: RELM (Braswell)

Architecture: `x86_64`

## Addtional information
I tried to manually install Parsec by installing all dependencies through `crew install parsec` and then replacing `crew`'s binaries of Parsec with the one that come with `parsec-linux.deb`. This stopped returning the `Exec format error`s but Parsec still doesn't start (it exits immediately after typing `parsecd` into the console, no output)

**Comment by supechicken** [comment]
@EvidenceRepulsive151 Sorry I mess them up after testing

**Comment by uberhacker** [comment]
This package has been removed.
