### ISSUE TITLE
[xfce4_panel] Failed to execute

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#4785]
```shell
$ xfce4-panel

(xfce4-panel:1116): xfce4-panel-WARNING **: 23:35:20.252: Failed to connect to the D-BUS session bus: Unknown or unsupported transport “disabled” for address “disabled:”
xfce4-panel: There is already a running instance
```

**Comment by supechicken** [comment]
Tried to install `gnome_keyring`

**Comment by satmandu** [comment]
@supechicken gnome_keyring now no longer uses openpam, which might have caused a conflict...

Try removing openpam, reinstalling linux_pam, and then see if the rebuilt gnome_keyring works?

**Comment by supechicken** [comment]
> gnome_keyring

Thanks a lot, It works:)
