### ISSUE TITLE
Go package tries to build with bootstrap with go installed

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#479]
I have go installed.
```bash
chronos@localhost /usr/local/lib/crew/packages $ which go
/usr/local/lib/go/bin/go
```
One issue is that the code checks the output of `which go` and compares it to an empty string. When using backticks in ruby the output has `\n` appended. 

Another is that the package doesn't appear to have access to the user's bash configuration and so the GOROOT is not set. I've tried in both ~/.bashrc and ~/.bash_profile with no luck.

Last, after running `crew install go` and it in turn install `go_bootstrap` only `go_bootstrap` is reported by `crew search` as being installed even though they both were installed successfully.

I updated the go.rb to 1.7.5 but it tries to build with the boostrap even though it shouldn't as a working go compiler is present.
```bash
Building from source, this may take a while...
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /home/chronos/user/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
go failed to install: `TMPDIR=/usr/local/tmp ./make.bash` exited with 1
```

**Comment by jam7** [comment]
@cstrouse `TMPDIR=/usr/local/tmp ./make.bash` is not bootstrap.  `GOROOT_BOOTSTRAP=/usr/local/lib/go_bootstrap/go TMPDIR=/usr/local/tmp ./make.bash` is the bootstrap.

I guess GOROOT environment variable caused this error.  Do you make it point to /home/chronos/user/go1.4?  I'm not sure but try it again after unsertting your GOROOT environment variable.

**Comment by jam7** [comment]
Nevermind, what I wrote above is completely wrong.  my bad.

**Comment by jam7** [comment]
@cstrouse It is required to use go_bootstrap even if go is installed.  So, I modified go.rb to do so.  I also updated go to 1.7.5.  Hope this works for you too.

**Comment by seitensei** [comment]
@jam7 That shouldn't be the case. Once you have a recent version of go installed, you should be able to compile using that version.

Go 1.4 can be built with C (and is the last version of the Go toolchain that is built with C), but after that, Go versions are dependent on Go to compile them.

**Comment by jam7** [comment]
@seitensei Thank you for the information.  First time, I thought as you mentioned, but when I tried to install new go using old go, I saw identical message what @cstrouse wrote above.

Therefore, I just though go1.4_bootstrap is required to compile new go each time.

The problem we have is we don't know what is correct command line to compile new go using old go.  Do you know how?  Old script runs `make.bash` for it.  Although, it results above no GOROOT_BOOTSTRAM error.

**Comment by seitensei** [comment]
@jam7 For bootstrap, you use ```make.bash```. For compiling with go using existing go, you use ```all.bash```.

**Comment by jam7** [comment]
Thank you for the information.  I'll try it.

However, we have problem with all.bash.  all.bash fails since it runs tests and tests try to write / (it is ro mount in chromebook).  I tried all.bash and failed when I made #489.  At that time, I also read #265, so just switch back to make.bash.  I guess I needed to find workaround instead of prohibiting all.sh.

**Comment by seitensei** [comment]
So it looks like ```make.bash``` specifically runs without tests, but we need to make sure that it knows how to access go to start with. It does expect $GOROOT_BOOTSTRAP as an environment variable- so we need to pass that in first. If we don't pass that in, it will automatically look for Go 1.4.

**Comment by jam7** [comment]
@seitensei I see.  Thank you so much, that's the way to use existing go as a bootstrap.

**Comment by jam7** [comment]
#509 solved a part of this issue regarding to bootstrap stuff.
#703 has solve the rest of this issue regarding to `which` stuff.

**Comment by jam7** [comment]
Closing this now in favor of #509 and #703.
