### ISSUE TITLE
Can't install chromebrew on armv7l

### ISSUE THREAD

**Issue by W0153R** [skycocker/chromebrew#4812]
The current install-script doesn't work on Samsung XE303C12 (ARMv7l). It ends with "git-remote-https died of signal 9".

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_RELEASE_BOARD=daisy-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=daisy-release/R75-12105.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.100.0 (Official Build) stable-channel daisy 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.100.0

Model: Samsung XE303C12

Architecture: armv7l

I tried replacing git version 2.29.1 with 2.28.0-1 but then I get "error: Could not fetch origin". The install-script from commit 36ce3f867af5936f1fcea6077486e555117fee93 works fine though. However, I haven't found a way to update to gcc10 yet and I think there are many other issues related to the outdated crew (upgrading curl and installing nano both failed).

While googling the "died of signal 9" message, I found some references to running out of memory and there being updates to git to prevent it.

**Comment by uberhacker** [comment]
@W0153R: Since your Chromebook has reached EoL, you are in YMMV territory.  We cannot fully support older versions of Chrome OS and since your version is 12 releases behind, it will be difficult to find a git commit in history that will work.  Even if you do find something, there are no guarantees any updates will be successful.

**Comment by satmandu** [comment]
This might have actually been a bug in the install script. I would try again with the script I just fixed up and updated here:

https://github.com/skycocker/chromebrew/raw/8c896d3606912e695e096b18a4baed4cb6d218f6/install.sh

**Comment by shawnbon206** [comment]
on my "peppy" Acer C720 I was having the same issue as @W0153R , but @satmandu 's edit fixed it.

Thank you

**Comment by satmandu** [comment]
Sorry for screwing it up!
