### ISSUE TITLE
Sommelier won't wait for sudo passwd

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4850]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description

When `chromeos-setdevpasswd` is set, `startsommelier` won't stop when `sudo` requesting passwd (only wait for timeout)

If you executed a specific command:
```shell
crosh> shell
```

Output:
```bash
bash: (5 * 1000000)        + (4 * 10000)        + 53+: syntax error: operand expected (error token is "+")
Password: some sommelier processes failed to start
sommelier processes running:  
 
chronos@localhost / $ 
Sorry, try again.
```

Architecture: `x86_64`

**Comment by satmandu** [comment]
Any suggestions on how to fix this?

running a sudo command before running restartsommelier should resolve this, but obviously this isn't a great solution.

**Comment by supechicken666** [comment]
I noticed that there are some `&> /dev/null` in `startsommelier` and `sommelierd`, maybe let `sommelierd` run in the foreground and let `sommelier.elf` in `sommelierd` run in background
```bash
# startsommelier and initsommelier
if ! checksommelierwayland || ! checksommelierxwayland ; then
  [ -f  /usr/local/bin/stopbroadway ] && stopbroadway
  /usr/local/sbin/sommelierd &> /dev/null
fi
```
```bash
# sommelierd
  sommelier -X --x-display=:$DISPLAY  \
--scale=$SCALE --glamor --drm-device=/dev/dri/renderD128 \
--virtwl-device=/dev/null --shm-driver=noop --data-driver=noop \
--display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland \
--xwayland-gl-driver-path=/usr/local/lib64/dri \
--peer-cmd-prefix="/usr/local/lib64/ld-linux-x86-64.so.2" \
--no-exit-with-child /bin/sh -c "touch ~/.Xauthority; xauth -f ~/.Xauthority add :$DISPLAY . $(xxd -l 16 -p /dev/urandom); . /usr/local/etc/sommelierrc" \
&>>/usr/local/var/log/sommelier.log &
```

**Comment by uberhacker** [comment]
@supechicken: Can you please post your environment details?  Is this a Chrome(book/box) or in a Docker container?  Are you running the latest STABLE release of Chrome OS?  Please post the output of `cat /etc/lsb-release`.

**Comment by supechicken666** [comment]
@uberhacker
```shell
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7017315
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_RELEASE_BOARD=hatch-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=73
CHROMEOS_RELEASE_BUILDER_PATH=hatch-release/R87-13505.73.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.73.0 (Official Build) stable-channel hatch 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.73.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.73.0
```

**Comment by uberhacker** [comment]
Yeah, i always reject ` &> /dev/null` when I see it.  Now @satmandu understands why I was so adamant about it. :)

**Comment by uberhacker** [comment]
What is your version of bash @supechicken?

**Comment by supechicken666** [comment]
```shell
chronos@localhost / $ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-cros-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

> What is your version of bash @supechicken?

**Comment by supechicken666** [comment]
@uberhacker  I will try to update `bash` to see if the syntax error is fixed :)

**Comment by satmandu** [comment]
The piping into /dev/null  & log files is useful to avoid voluminously excessive output from some of these daemons.

Due to the way that the chronos password works, we should just be able to check for the existence of ```/mnt/stateful_partition/etc/devmode.passwd``` to see if a password is set, right?

**Comment by uberhacker** [comment]
- piping to /dev/null is not useful
- piping to log files is useful

**Comment by satmandu** [comment]
> * piping to /dev/null is not useful
It depends?

Stuff like this isn't that useful to log, is it?
```pgrep -f \"sommelier.elf --parent\" 2> /dev/null```

**Comment by satmandu** [comment]
Does this work for you if you have a password set to get the sudo password prompt?
```
if [[ -f /mnt/stateful_partition/etc/devmode.passwd ]]; then
  sudo -v
fi
```

**Comment by satmandu** [comment]
Actually, sudo is only used in one place:
```
sudo rm \${XDG_RUNTIME_DIR}/wayland-1*
```

I think we can get rid of it as those files are owned by chronos.

**Comment by uberhacker** [comment]
The problem with `2> /dev/null` and especially `&> /dev/null` is you would never know if there was an error.

**Comment by satmandu** [comment]
(Not the only place, but let me see how it works w/o sudo.)

Re: &>/dev/null 
it doesn't always get rid of errors. Sometimes you have code to handle if there IS an error.

e.g.
```
checksommelierxwayland () {
  xdpyinfo -display \$DISPLAY &>/dev/null
}
if ! checksommelierxwayland; then
pkill -F #{CREW_PREFIX}/var/run/sommelier-xwayland.pid &>/dev/null
[[ ! -d /tmp/.X11-unix ]] && mkdir /tmp/.X11-unix
sudo chmod -R 1777 /tmp/.X11-unix
sudo chown root:root /tmp/.X11-unix
DISPLAY=\"\${DISPLAY//:}\"
DISPLAY=\"\${DISPLAY:0:2}\"
sudo rm /tmp/.X11-unix/X\"\${DISPLAY}\"
sommelier -X --x-display=:\$DISPLAY  --scale=\$SCALE --glamor --drm-device=/dev/dri/renderD128 --virtwl-device=/dev/null --shm-driver=noop --data-driver=noop --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=#{CREW_LIB_PREFIX}/dri --peer-cmd-prefix=\"#{CREW_PREFIX}#{PEER_CMD_PREFIX}\" --no-exit-with-child /bin/sh -c \"touch ~/.Xauthority; xauth -f ~/.Xauthority add :$DISPLAY . $(xxd -l 16 -p /dev/urandom); . #{CREW_PREFIX}/etc/sommelierrc\" &>>#{CREW_PREFIX}/var/log/sommelier.log
echo \$! >#{CREW_PREFIX}/var/run/sommelier-xwayland.pid
xhost +si:localuser:root &>/dev/null
fi
```
It isn't clean.... but it seems to get the job done?

**Comment by uberhacker** [comment]
Until there is an error that isn't obvious and you end up with an issue like this one. :)

**Comment by satmandu** [comment]
True too. But even if stuff was going to logs, it would still require going through the logs, for which one would have to read the code anyways...
