### ISSUE TITLE
[eudev and vdev] File conflict

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4865]
```
$ crew whatprovides /usr/local/lib64/libudev.so.1
eudev: /usr/local/lib64/libudev.so.1
eudev: /usr/local/lib64/libudev.so.1.6.3
vdev: /usr/local/lib64/libudev.so.1
vdev: /usr/local/lib64/libudev.so.1.5.2

Total found: 4
```
The version from eudev is newer so I imagine that should be the preferred?

**Comment by satmandu** [comment]
vdev looks to be dead: https://github.com/jcnelson/vdev/issues/102
eudev's last commit was 2 weeks ago... so that should make this an easy decision.

Only util_linux depends upon it, so I'll spin up some rebuilds of util_linux with vdev replaced as a dependency by eudev.
