### ISSUE TITLE
[Sommelier] Failed to build

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#4876]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:

`chronos@localhost /usr/local $ crew install sommelier`

Output:
```shell
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M    0 18.6M    0     0  2684k      0 --:--:--  0:00:07 --:--:-- 3348k
Downloading virtwl
virtwl base64 downloaded
The Meson build system
Version: 0.56.0
Source dir: /usr/local/tmp/crew/patch.dir/vm_tools/sommelier
Build dir: /usr/local/tmp/crew/patch.dir/vm_tools/sommelier/build
Build type: native build
Project name: sommelier
Project version: undefined
Using 'CFLAGS' from environment with value: '-fuse-ld=lld'

meson.build:5:0: ERROR: Unable to detect linker for compiler "cc -Wl,--version -fuse-ld=lld"
stdout: 
stderr: cc: error: unrecognized command line option ‘-fuse-ld=lld’; did you mean ‘-fuse-ld=bfd’?


A full log can be found at /usr/local/tmp/crew/patch.dir/vm_tools/sommelier/build/meson-logs/meson-log.txt
sommelier failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dmandir=/usr/local/share/man -Dbuildtype=release -Dc_args='-fuse-ld=lld' -Dxwayland_path=/usr/local/bin/Xwayland     -Dxwayland_gl_driver_path=/usr/lib/dri -Ddefault_library=both     -Dxwayland_shm_driver=noop -Dshm_driver=noop -Dvirtwl_device=/dev/null     -Dpeer_cmd_prefix="/usr/local/lib/ld-linux-i686.so.2" build` exited with 1
```

## Versions and system information
chromebrew: `1.5.4`

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_RELEASE_BOARD=chromeover32
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
GOOGLE_RELEASE=76.4.70
CHROMEOS_RELEASE_BUILD_NUMBER=12239
CHROMEOS_RELEASE_BRANCH_NUMBER=77
CHROMEOS_RELEASE_CHROME_MILESTONE=76
CHROMEOS_RELEASE_PATCH_NUMBER=2019_09_09_1854
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=76.4.70
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_DESCRIPTION=76.4.70 (Developer Build - neverware) stable-channel chromeover32

Model: YOUR MODEL HERE

Architecture: `i686`

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by satmandu** [comment]
Hmmm: 
```meson.build:5:0: ERROR: Unable to detect linker for compiler "cc -Wl,--version -fuse-ld=lld"```
Do you have llvm installed? gcc10?

**Comment by supechicken** [comment]
I am using `gcc8` with `llvm`, here is another error using `gcc10` to build
```shell
Using 'CFLAGS' from environment with value: '-fuse-ld=lld'

meson.build:5:0: ERROR: Compiler cc can not compile programs.

A full log can be found at /usr/local/tmp/crew/patch.dir/vm_tools/sommelier/build/meson-logs/meson-log.txt
sommelier failed to install: `meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dmandir=/usr/local/share/man -Dbuildtype=release -Dc_args='-fuse-ld=lld' -Dxwayland_path=/usr/local/bin/Xwayland     -Dxwayland_gl_driver_path=/usr/lib/dri -Ddefault_library=both     -Dxwayland_shm_driver=noop -Dshm_driver=noop -Dvirtwl_device=/dev/null     -Dpeer_cmd_prefix="/usr/local/lib/ld-linux-i686.so.2" build` exited with 1
```
(Same error when building `gdk_pixbuf`, seems `gcc10` is broken on my machine)

**Comment by satmandu** [comment]
sommelier binaries have been uploaded FYI...

**Comment by satmandu** [comment]
> (Same error when building `gdk_pixbuf`, seems `gcc10` is broken on my machine)

Try upgrading to the new gcc10?
