### ISSUE TITLE
Crew chokes on malformed package.rb files

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4887]
Any malformation in a package.rb file leads to ```crew``` erroring out.

One approach is to sanitize every single package file before crew is run.

But a better approach might be to have crew ignore package files it considers malformed

I do not think I am sufficiently versed in ruby to refactor crew to make this happen, but it's needed.

**Comment by uberhacker** [comment]
Or just remember to include all the necessary information. :) A template should help.

**Comment by satmandu** [comment]
If I'm migrating a package from arch I actually use [this script](https://gist.github.com/satmandu/18f926a905b28576f88775b1a8e79df4) most of the time, which does populate the necessary fields.

Ironically, this is probably due to a hacked up manual copy/paste from me updating the file before upload.

**Comment by satmandu** [comment]
But a crew "validate package file" function would be useful, especially one crew used itself before processing a package file. That way we wouldn't have to create a separate script to check package files for completeness.

**Comment by satmandu** [comment]
Another reason: This is a security risk because any malformed .rb file in the packages directory can lead to a local DOS attack on a user trying to use crew.

**Comment by cstrouse** [comment]
I think the way to go here is to create a Rubocop profile for pre-commit checks and PR checks that only covers what we care about for our needs.

**Comment by uberhacker** [comment]
@cstrouse: Sounds like a good solution.  Did you want to go ahead and set it up? :)

**Comment by saltedcoffii** [comment]
Crew no longer chokes on syntax errors from package files.
