### ISSUE TITLE
Rpath not set for anything

### ISSUE THREAD

**Issue by jbaum98** [skycocker/chromebrew#49]
I realized that the rpath is not set for any of the precompiled binaries included in Chrombrew. This is a problem, especially because we don't have write permissions on /etc/ld.so.cache so we cannot rely on `ldconfig` at all. This also manifests itself in the problem with `ncurses` and why we need the hacky solution. This can be fixed by recompiling the prebuilt binaries with the right LD_FLAGS. Alternatively, running the following commands sets the rpaths and interpreters for the crucial executables: gcc and ruby. Note this requires patchelf.

``` bash
patchelf --set-rpath /usr/local/lib:/usr/local/lib64 /usr/local/lib/ld-linux-x86-64.so.2 /usr/local/bin/{gcc,g++,ruby}
patchelf --set-rpath /usr/local/lib:/usr/local/lib64 /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.1/{cc1,cc1plus}
ls /usr/local/lib/ruby/2.0.0/x86_64-linux/digest | grep sha | xargs -I {} patchelf --set-rpath /usr/local/lib:/usr/local/lib64 /usr/local/lib/ruby/2.0.0/x86_64-linux/digest/{}
```

Now ncurses can be installed correctly with `./configure --prefix=/usr/local "CFLAGS= -fPIC" --without-debug --without-normal --with-shared --with-termlib`

**Comment by ryanpcmcquen** [comment]
We could also get around this by updating the `gcc` and `glibc` toolchain, and building it with rpath set. @skycocker seemed interested in doing this but we may need some help from the community.
