### ISSUE TITLE
[mesa] Binary not working with sommelier

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#4942]
## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
crosh> shell
```

Output:
```shell
chronos@localhost ~ $ restartsommelier

some sommelier processes failed to start
sommelier processes running: 28775 /usr/local/bin/../lib64/ld-linux-x86-64.so.2 --library-path /usr/local/bin/../lib64 --inhibit-rpath  /usr/local/bin/sommelier.elf --parent --peer-cmd-prefix=/usr/local/lib64/ld-linux-x86-64.so.2 --drm-device=/dev/dri/renderD128 --shm-driver=noop --data-driver=noop --display=wayland-0 --socket=wayland-1 --virtwl-device=/dev/null 
```

## Versions and system information

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7017315
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_RELEASE_BOARD=hatch-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=hatch-release/R87-13505.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.100.0 (Official Build) stable-channel hatch 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.100.0

Architecture: `x86_64`

**Comment by supechicken** [comment]
Solved after building `mesa` from source

**Comment by satmandu** [comment]
Did you do anything else besides rebuild from source?

**Comment by supechicken** [comment]
> Did you do anything else besides rebuild from source?

Only reinstalled sommelier with previous commit

**Comment by satmandu** [comment]
You could also see if these binaries work in the openssl packages PR: https://github.com/skycocker/chromebrew/blob/5031038b8069fef039243dde96838a0caffb8546/packages/sommelier.rb

**Comment by satmandu** [comment]
Is this still an issue? Also see today's sommelier package update.
