### ISSUE TITLE
openssl clobbers libressl

### ISSUE THREAD

**Issue by kjperkin** [skycocker/chromebrew#4967]
## Description
 * openssl was updated to be a real package by #4907
 * crew update prompted me to upgrade openssl. I thought, "sure, why not, I'm trying to author a package and the openssl tests are failing, maybe this will fix it."
 * After `crew upgrade openssl` I did `crew remove libressl` figuring that I only need one. That broke openssl because the packages share paths.

The following shows the overlap and differences between the files in the two packages:
```shell
cd /usr/local/tmp
cat >check.sh <<EOF
#!/usr/bin/env bash
cd /usr/local/tmp
crew download libressl openssl
mkdir libressl openssl
tar -C libressl -xJf crew/libressl-3.2.3-chromeos-x86_64.tar.xz
tar -C openssl -xJf crew/openssl-1.1.1i-chromeos-x86_64.tar.xz
diff -q -r libressl openssl
EOF
chmod 0755 check.sh
./check.sh
```

Output:
```shell
libressl: LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, improving security, and applying best practice development processes.
Precompiled binary available, downloading...
############################################################################################################### 100.0%
Archive downloaded
openssl: The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
Precompiled binary available, downloading...
############################################################################################################### 100.0%
Archive downloaded
Files libressl/dlist and openssl/dlist differ
Files libressl/filelist and openssl/filelist differ
Only in openssl/usr/local/bin: c_rehash
Only in libressl/usr/local/bin: ocspcheck
Files libressl/usr/local/bin/openssl and openssl/usr/local/bin/openssl differ
Only in libressl/usr/local/etc/ssl: cert.pem
Only in openssl/usr/local/etc/ssl: ct_log_list.cnf
Only in openssl/usr/local/etc/ssl: ct_log_list.cnf.dist
Only in openssl/usr/local/etc/ssl: misc
Files libressl/usr/local/etc/ssl/openssl.cnf and openssl/usr/local/etc/ssl/openssl.cnf differ
Only in openssl/usr/local/etc/ssl: openssl.cnf.dist
Only in openssl/usr/local/etc/ssl: private
Only in libressl/usr/local/etc/ssl: x509v3.cnf
Files libressl/usr/local/include/openssl/aes.h and openssl/usr/local/include/openssl/aes.h differ
... and so on
```

## Versions and system information
chromebrew: 1.5.6

ChromeOS:
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7017315
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R87-13505.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.100.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13505.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.100.0
```

Model: Samsung Chromebook Pro

Architecture: x86_64

## Addtional information
I'm not sure how this can be cleaned up. After breaking ssl, I was able to manually download the binary package for libressl, uninstall openssl, unpack libressl, then `crew reinstall libressl` for good measure to "fix" my install. However, I don't think that's the "happy path" for this scenario...

**Comment by uberhacker** [comment]
Thank you for the detailed analysis @kjperkin.  I think the solution is to remove the `libressl` package.  Thoughts @satmandu?

**Comment by satmandu** [comment]
Install.sh installs libressl and then openssl so that packages which might depend upon libressl don't get broken. The OpenSSL libraries appear to do a fine job of replacing the libressl libraries, and since the openssl headers supersede the libressl headers, any new compiles should just use openssl. But there might be apps which link to specific versioned libressl libraries, and that might break if you remove libressl.

The SSL situation is similar to that of gcc. Only remove libressl if you are going to immediately reinstall openssl.

But if you are willing to be a Guinea Pig, please remove libressl, reinstall openssl, and tell us which packages break, and we can get those packages rebuilt so they don't look for libressl!

( I did this for several packages which explicitly listed a libressl or openssl dependency, but that obviously doesn't cover everything.)

**Comment by kjperkin** [comment]
This little monstrosity does a quick and dirty search for libraries and executables that have unsatisfied dependencies.

There are a number after removing libressl. There are also a few surprising ones on my system, unrelated to libressl.

```shell
#!/bin/bash

# check_libs.sh

CHECK="/usr/local/bin/ldd \$1 | grep -q 'not found'"
QCHECK="{ /usr/local/bin/ldd \$1 | grep -q 'not found'; } 2>/dev/null"
PRINT="{ echo \$1; /usr/local/bin/ldd \$1 | grep 'not found'; }"
QPRINT="{ echo \$1; /usr/local/bin/ldd \$1 | grep -q 'not found'; } 2>/dev/null"

find /usr/local/{,s}bin /usr/local/lib{,64} \
    -type f \( -path '/usr/local/bin/*' -o -path '/usr/local/sbin/*' -o -name '*.so*' \) \
    \(  \
        \( -perm /111 -exec sh -c "$CHECK" sh {} \; -exec sh -c "$PRINT" sh {} \; \) \
        -o \( \( -not -perm /111 \) -exec sh -c "$QCHECK" sh {} \; -exec sh -c "$QPRINT" sh {} \; \) \
    \)

```

**Comment by uberhacker** [comment]
Nice @kjperkin!   I modified your script to only look in `/usr/local/lib64` for x86_64 architecture and return the package that includes the file to check.  It runs about 10 times slower but gets the job done...eventually.
```
#!/bin/bash

# check_libs.sh

CHECK="/usr/local/bin/ldd \$1 | grep -q 'not found'"
QCHECK="{ /usr/local/bin/ldd \$1 | grep -q 'not found'; } 2>/dev/null"
PRINT="{ echo \$1; /usr/local/bin/ldd \$1 | grep 'not found'; }"
QPRINT="{ echo \$1; /usr/local/bin/ldd \$1 | grep -q 'not found'; } 2>/dev/null"
LOCATIONS="/usr/local/bin /usr/local/sbin /usr/local/lib"
[ $(arch) == 'x86_64' ] && LOCATIONS+="{,64}"

find $LOCATIONS \
    -type f \( -path '/usr/local/bin/*' -o -path '/usr/local/sbin/*' -o -name '*.so*' \) \
    \(  \
        \( -perm /111 -exec sh -c "$CHECK" sh {} \; -exec sh -c "$PRINT" sh {} \; -exec crew whatprovides {} \; \) \
        -o \( \( -not -perm /111 \) -exec sh -c "$QCHECK" sh {} \; -exec sh -c "$QPRINT" sh {} \; \) \
    \)
```

**Comment by satmandu** [comment]
FYI this is also good at telling you which libs a binary is using:
```
#!/usr/bin/env bash
# put this in /usr/local/bin/libs
needs=`readelf -d $1 2>/dev/null| \
  awk '$2=="(NEEDED)" {
      gsub("[][]", "", $5); 
      hits[$5]=$5
  }
  END {
      for (i in hits) {
          printf(sprintf("%s ", i))
      }
  }'`

/usr/local/sbin/ldconfig -p | \
    awk -vneeds="$needs" \
       'BEGIN{
          split(needs,aneeds)
        }

        { 
          if (!arr[$1]) 
            arr[$1] = $NF
        }

        END { 
          for (i in aneeds) { 
            need = aneeds[i]; 
            if (arr[need]) {
              print need "\t" arr[need]
            } else {
               print "unfulfilled:", need
            }
          }
       }'
```

**Comment by satmandu** [comment]
Apparently the openssl install after libressl leads to dual dependencies by packages. Which is terrible.

So I'm recompiling now with libressl removed. Agree with assessments above on that being the right thing to do.

**Comment by kjperkin** [comment]
Any idea how hard would it be to change packages to use openssl installed to some weird prefix (e.g. /usr/local/ssl/openssl) and libressl to some other prefix (e.g. /usr/local/ssl/libressl)? I poked around in the config options for openssl and while it's possible to get it to install the shared objects with a suffix on the name, that doesn't affect everything else, so the only way to really prevent these two from fighting is to install them to completely different prefixes (or patch them, but that sounds like a recipe for pain).

**Comment by uberhacker** [comment]
How about just remove libressl and start using only openssl?  Why do we need two packages?

**Comment by kjperkin** [comment]
I agree in principle. I'm also curious as to what distros do, but I feel like that's a question for later. What I'm stuck on right now is:
1) How do we make sure that packages that were using libressl work correctly with openssl?
2) How do we cleanly remove libressl without erasing openssl files (since the package file lists overlap)?
3) How do we make sure that users aren't taken by surprise by the change?

I wish I had more to offer than questions and concerns... 😞

**Comment by uberhacker** [comment]
I think it's "simply" a matter of `crew remove libressl && crew reinstall openssl` and then recompile all packages that depend on ssl.  Then we can safely remove libressl.

**Comment by kjperkin** [comment]
Unfortunately, I don't think that it's that easy.

To get back to a state resembling how things were before #4907, I checked out the parent of that commit, removed openssl, manually unpacked libressl, did a `crew reinstall libressl` and crew install openssl. After checking out master again, this sequence of commands broke my install:
```
crew download libressl
crew download openssl
cp /usr/local/tmp/crew/libressl-3.2.3-chromeos-x86_64.tar.xz /usr/local/tmp
cp /usr/local/tmp/crew/openssl-1.1.1i-chromeos-x86_64.tar.xz /usr/local/tmp
crew remove libressl
crew reinstall openssl
crew update     # broken!
```

**Comment by satmandu** [comment]
Is your system working now?
This should hopefully work:
```crew update ; crew reinstall curl ;  crew reinstall git  ;  crew remove libressl ; crew reinstall openssl ; crew update ; crew upgrade```

**Comment by kjperkin** [comment]
Hi, I haven't been able to test yet. I'll try to do so in the next day or two.

**Comment by kjperkin** [comment]
After resetting to the last commit before openssl was changed to a real package, running crew upgrade, and reinstalling a handful of packages I had manually recompiled, I did those steps and they worked.
