### ISSUE TITLE
Sym link issue after remove and reinstall

### ISSUE THREAD

**Issue by Alex313031** [skycocker/chromebrew#5010]
Issue: Removing crew via the wiki [ https://github.com/skycocker/chromebrew/wiki/How-to-remove-chromebrew](url) leaves a simlink issue that makes reinstalling crew impossible. Unlinking and rm -rf or creating then removing /usr/local/var doesn't solve anything. The error given is "unlink: cannot unlink '/usr/local/var': No such file or directory" & "unlink: cannot unlink '/usr/local/var': Is a directory"

## Versions and system information:
1.6

ChromeOS: `cat /etc/lsb-release`:
GOOGLE_RELEASE=87.3.41
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_PATCH_NUMBER=2021_01_15_2352
CHROMEOS_RELEASE_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_BOARD_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=87.3.41
CHROMEOS_RELEASE_DESCRIPTION=87.3.41 (Developer Build - neverware) stable-channel chromeover64

Architecture: `uname -m`:
Linux localhost 5.4.66+ #1 SMP Tue Dec 22 13:39:49 UTC 2020 x86_64 AMD FX-8370 Eight-Core Processor AuthenticAMD GNU/Linux

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by supechicken** [comment]
Try this install command?
```shell
curl -Ls https://github.com/supechicken666/chromebrew/raw/fix-install-cloudready/install.sh | bash
```
