### ISSUE TITLE
CloudReady kernel version breaks sommelier.env

### ISSUE THREAD

**Issue by x-t** [skycocker/chromebrew#5091]
## Description
When I was trying to get `codium` to work, it couldn't open up the display. After some digging, the `sommelier.env` file was failing, because the kernel version isn't an expected number
```
$ uname -a
Linux localhost 5.4.66+ #1 SMP Tue Dec 22 13:39:49 UTC 2020 x86_64 Intel(R) Core(TM)2 Duo CPU P8600 @ 2.40GHz GenuineIntel GNU/Linux
$ echo ${VERTEMP[2]}
66+
$ 
```
This breaks the math. My temporary fix was to change `VERTEMP[2]` to just `66`
```diff
- + ${VERTEMP[2]}))
+ + 66))
```

## Versions and system information
chromebrew: `1.7.4`

ChromeOS: 
```
GOOGLE_RELEASE=87.3.41
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_PATCH_NUMBER=2021_01_15_2352
CHROMEOS_RELEASE_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_BOARD_APPID=87efface-864d-49a5-9bb3-4b050a7c227a
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=87.3.41
CHROMEOS_RELEASE_DESCRIPTION=87.3.41 (Developer Build - neverware) stable-channel chromeover64
```

Model: CloudReady/Chromium OS

Architecture: `x86_64`

## Addtional information

What I think needs to be done:
- [ ] Parse out the kernel version number safely

**Comment by satmandu** [comment]
Thanks for the report. Any suggestions for better kernel version comparisons from bash?

**Comment by x-t** [comment]
Since the script already has a way of concatenating the three integers of the kernel version, `A.B.C` is guaranteed, we only really need to ensure that they're numbers. Bash supports regular expressions, so you could use that.

`.sommelier.env` created [here](https://github.com/skycocker/chromebrew/blob/master/packages/sommelier.rb#L109)
```diff
19c19
<         + ${VERTEMP[2]}))
---
>         + ${VERTEMP[2]//[^0-9]/}))
```

**Comment by satmandu** [comment]
Anyone want to write a tiny c program that uses 

```
#include <linux/version.h>
#if LINUX_VERSION_CODE < KERNEL_VERSION(4,19,0)
```

or makes a generic version check program? How does this not exist?

**Comment by satmandu** [comment]
@uberhacker @supechicken Any ideas on how to do this better? 

bash based string comparisons of the output of ```uname``` seem annoying when a simpler c program could exist to do this properly...

**Comment by uberhacker** [comment]
I'm not convinced we need sommelier for CloudReady.  What happens if you don't use it @x-t?

**Comment by supechicken** [comment]
Just noticed that why we need to times the kernel version in `sommelier.env`? 
I think it is an issue with the `+` symbol, a filter that only allow dots and digital may works. (by the way sommelier works fine on my Cloudready system)

**Comment by supechicken** [comment]
In fact Cloudready have its own sommelier located in `/usr/bin/sommelier`, but it is going to be removed in next version since Cloudready is removing the Virtualbox and Flatpak support, see https://cloudreadykb.neverware.com/s/article/End-of-support-for-VBox-and-Flatpak

**Comment by satmandu** [comment]
Huh! Is there source somewhere to cloudready's current version of sommelier?

**Comment by satmandu** [comment]
Feel free to submit a PR!

FYI, here's output on a ChromeOS machine, so we can't break on that.
```
uname -r
4.4.250-19713-g86a113a4c077
```

**Comment by x-t** [comment]
> I'm not convinced we need sommelier for CloudReady. What happens if you don't use it @x-t?

Without following config in `.bashrc`, it does not work.
```bash
# Sommelier environment variables + daemon
set -a ; source ~/.sommelier-default.env ; source ~/.sommelier.env ; set +a

startsommelier
```
Following terminal output also appears without the `.env` files and with `startsommelier`.

Terminal output:
```
crosh> shell
chronos@localhost / $ ps -A | grep sommelier
 2863 ?        00:00:01 sommelier
chronos@localhost / $ codium --verbose
[7396:0209/012906.749224:ERROR:browser_main_loop.cc(1473)] Unable to open X display.
The futex facility returned an unexpected error code.
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.

Report Id:

chronos@localhost / $ 
```

However, it does work with the `.env` files and without `startsommelier`. Also works with the `$VERSION` code commented out, essentially hardcoding it to the 64-bit driver. I don't know if this is the already built-in version of CloudReady or not. However if it is the integrated version of sommelier, it may be axed in the next update.

> Huh! Is there source somewhere to cloudready's current version of sommelier?

The [Neverware Github page](https://github.com/neverware) is lacking and the only source code that I found (albeit I didn't look too much) was [this forum thread](https://neverware.zendesk.com/hc/en-us/community/posts/210869287-CloudReady-Source-Code-) that has sources for `v78.2.3`. I didn't have the time to look through it fully, so I cannot say if that has the source code for sommelier or anything of the sort, I think Flatpak support has been a several year-old feature, so it may be in there. However even if there was, it's still pretty outdated.

On the solutions side, the C code would require recompilation for every single machine because it's a macro, and other shell solutions tend to get ugly, as I'm not sure anyone in the first 3 pages of Google has figured out how to get the kernel version as a single number. With the closest other solution probably ignoring the third digit, since we need `>4.16.0`, not something sensitive to it like `4.16.2`. Which can be done by deleting the line here or how I saw other example code, with making the `X.Y` versions as floats and comparing them with `bc`, but that seems a tad *unnecessary*...

**Comment by satmandu** [comment]
Here's something I hacked up this evening:

```
/* kernelnewerthan.c
 * Compile: 
 * gcc -o kernelnewerthan kernelnewerthan.c
 * Usage: 
 * Two arguments expected: MAJORVERSION PATCHLEVEL.
 * e.g. to check if kernel is newer than 4.19:
 * ./kernelnewerthan 4 19
 * 
 * This program will intentionally error out if the kernel headers 
 * are too old, and then if the running kernel is too old, in that
 * order.
 * 
 * This used as reference https://stackoverflow.com/a/46282013 
 * 
 * - Satadru Pramanik
 */

#include <stdio.h>
#include <stdlib.h>
#include <linux/version.h>
#include <errno.h>
#include <ctype.h>
#include <sys/utsname.h>

int main( int argc, char *argv[] )  {

    if( argc == 3 ) {
        printf("The kernel version requested for comparison is %s.%s\n", argv[1], argv[2]);
    }
    else {
        printf("Two arguments expected: MAJORVERSION PATCHLEVEL.\n");
        printf("e.g. to check if kernel is newer than 4.19:\n");
        printf("./kernelnewerthan 4 19\n");
        exit(2);
    }

    int majorversion, patchlevel;
    sscanf (argv[1],"%d",&majorversion);
    sscanf (argv[2],"%d",&patchlevel);

    if (LINUX_VERSION_CODE >= KERNEL_VERSION(majorversion,patchlevel,0)) {
        printf("Linux kernel headers are new enough.\n");
    } else {
        printf("Linux kernel headers are not new enough.\n");
        exit (1);
    }
    
    struct utsname buffer;
    char *p;
    long ver[16];
    int i=0;
    
    errno = 0;
    if (uname(&buffer) < 0) {
       perror("uname");
       exit(EXIT_FAILURE);
    }
   
    p = buffer.release;

    while (*p) {
        if (isdigit(*p)) {
            ver[i] = strtol(p, &p, 10);
            i++;
        } else {
            p++;
        }
    }

    int majorversion_actual = ver[0];
    int patchlevel_actual = ver[1];
    
    printf("Kernel Major Version %d Patchlevel %d Sublevel %lu Extramajorversion %lu\n", 
        majorversion_actual, patchlevel_actual, ver[2], ver[3]);
    
    if (majorversion_actual > majorversion) {
        printf("Linux Kernel is new enough.\n");
        return EXIT_SUCCESS;
    }
        else if (majorversion_actual = majorversion)  {
        printf("Kernel Major Version is new enough.\n");
    } else {
        printf("Kernel Major Version is not new enough. Wanted %d, found %d.\n", 
            majorversion, majorversion_actual);
        printf("Linux Kernel is not new enough.\n");
        exit(1);
    }
    
    if (patchlevel_actual >= patchlevel) {
        printf("Kernel Patchlevel is new enough.\n");
        printf("Linux Kernel is new enough.\n");
        return EXIT_SUCCESS;
      } 
    else {
        printf("Kernel Patchlevel is not new enough. Wanted %d, found %d.\n", 
            patchlevel, patchlevel_actual);
        printf("Linux Kernel is not new enough.\n");
        exit (1);
    }

    return EXIT_SUCCESS;
    
}
```
If it's useful I can package it.

**Comment by x-t** [comment]
Should be useful at least in this use case, just a heads up `Extramajorversion` is out-of-bounds if it doesn't exist. And I'm guessing you want to only distribute as a source package, otherwise the kernel headers are bound to the machine it was built on, expanding to
```c
(265728 >= (((majorversion) << 16) + ((patchlevel) << 8) + (0)))
```

Checking this at run-time would require to read `/usr/local/include/linux/version.h` or `/usr/include/linux/version.h`

**Comment by kjperkin** [comment]
How about this? I don't see anything wrong with the multiplication-based approach. I can't imagine the minor or patch numbers ever getting high enough to overflow.

```
# usage: kv_check major minor patch sense
#    If sense == 0 (or not given) then check kernel version is less
#    If sense == 1 then check kernel version is greater or equal
function kv_check() {
    local major=$1 minor=$2 patch=$3 sense=$4
    local version=$(uname -r)
    version=${version//[^0-9]/ }
    version=( $version )
    version=$(( version[0]*1000000 + version[1]*10000 + version[2] ))
    check_version=$(( major*1000000 + minor*10000 + patch ))
    (( (sense != 0) - (version < check_version) ))
    return $?
}

function kv_lt() { kv_check $@ 0 }
function kv_ge() { kv_check $@ 1 }
if kv_lt 4 16 0
then
    echo old kernel
else
    echo new kernel
fi
```

**Comment by satmandu** [comment]
@kjperkin That's fine. Want to make it into a PR? (I think the version has to be greater than 4.19 for the sommelier env option, IIRC?)

**Comment by kjperkin** [comment]
@satmandu I'll have time/energy to do that later tonight or tomorrow evening. Please also feel free to incorporate it yourself if you need/want it sooner. Right now I'm rather worn out.
