### ISSUE TITLE
[ncurses] symlink of libtinfo.so.5 to libtinfo.so.6 causes segfault in /usr/bin/watch

### ISSUE THREAD

**Issue by kjperkin** [skycocker/chromebrew#5092]
## Description
libtinfo.so.6 does not appear to be binary-compatible with the system libtinfo.so.5. ncurses.rb creates symlinks to redirect references to libtinfo.so.5 to libtinfo.so.6. However, this causes the system ncurses.so.5 to be linked with /usr/local/lib64/libtinfo.so.6. This results in a segfault upon any attempt to run watch. Presumably other commands are impacted as well. 

If you executed a specific command:
```shell
watch ls
which watch
ldd $(which watch)
```

Output:
```
Segmentation fault (core dumped)
/usr/bin/watch
...
libtinfo.so.5 => /usr/local/lib64/libtinfo.so.5 (0x000079a83ffe4000)
...
```

## Versions and system information
chromebrew: `1.7.4`

ChromeOS:
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7069196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=111
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R87-13505.111.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.111.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13505.111.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.111.0
```

Model: Samsung Chromebook Pro (caroline)

Architecture: `x86_64`

## Addtional information
What I think needs to be done:
- [ ] Remove the lines 66,  70 from ncurses.rb
- [ ] Bump ncurses version
- [ ] Rebuild ncurses

**Comment by satmandu** [comment]
```crew install procps``` should give you ```/usr/local/bin/watch```

```
libs /usr/local/bin/watch
libc.so.6       /usr/local/lib64/libc.so.6
libdl.so.2      /usr/local/lib64/libdl.so.2
libncurses.so.6 /usr/local/lib64/libncurses.so.6
```

**Comment by satmandu** [comment]
There's the larger issue of whether libraries in CREW_LIB_PREFIX should support all installed chrome os binaries in /usr/bin and /bin. I say not. We should provide replacements where possible.

**Comment by kjperkin** [comment]
Yeah, I don't think it would be reasonable to expect all libraries in CREW_LIB_PREFIX to support what's in /usr/bin and /bin. However, I also don't think it's good for our libraries to prevent those programs from running normally. Especially in this case, the issue seems avoidable, and I suspect that it is technically incorrect to have that symlink. I'll be including a fix for this as part of a larger PR in a bit.

**Comment by satmandu** [comment]
Does it work fine if ```LD_LIBRARY_PATH=/usr/lib64:/lib64``` is set? If so removing the symlink should definitely fix the issue. Thanks for noticing the issue.

**Comment by kjperkin** [comment]
Yes, it does. Also, if you run `ldd /usr/bin/watch`, you will see that it is trying to link to libtinfo.so.5, which libtinfo.so.6 is very much not 😅
