### ISSUE TITLE
[readline] Link to libtinfo

### ISSUE THREAD

**Issue by kjperkin** [skycocker/chromebrew#5099]
## Description
By default, readline doesn't link against libtinfo despite requiring it when compiled with --with-curses. This can make compiling software that depends on libreadline difficult as link failures can occur if that software assumes that readline pulls in libtinfo. I'm currently working on one such piece of software and rather than trying to patch up Makefiles, I'd much rather have the build of libreadline add libtinfo. I've figured out the magic incantation to do so and will be including it in a larger PR to be created shortly.

**Comment by satmandu** [comment]
Just delete the binaries section in your PR. We can add new ones automatically.

Also, I think  when you have a ```CFLAGS='-flto=auto'``` you also need a ```LDFLAGS='-flto=auto'``` as well.
