### ISSUE TITLE
[ncurses] Binaries in /usr/local/bin are installed with prefixed names

### ISSUE THREAD

**Issue by kjperkin** [skycocker/chromebrew#5110]
## Description
Programs supplied by ncurses like `clear`, `infocmp`, etc. are installed with a name like `#{CREW_BUILD}-#{PROGRAM}` (e.g. `x86_64-cros-linux-gnu-clear` for `clear` on `x86_64`).

### Commands
```shell
which -a clear
```

### Expected Output:
```
/usr/local/bin/clear
/usr/bin/clear
```

### Actual Output:
```
/usr/bin/clear
```

## Versions and system information
chromebrew: `crew --version`
```
1.7.4
```

ChromeOS: `cat /etc/lsb-release`
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7069196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=111
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R87-13505.111.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.111.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13505.111.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.111.0
```

Model: Samsung Chromebook Pro (caroline)

Architecture: `uname -m`
```
x86_64
```

## Addtional information
This seems to be caused by either (or both) of the `--host` and `--target` options being passed to `configure`.

What I think needs to be done:
- [ ] **pick one**
   - Don't pass `--host` and `--target` to `configure`
   - Pass `--program-prefix='' --program-suffix=''` to configure (PR for this coming shortly)
- [ ] Bump version
- [ ] Rebuild

**Comment by satmandu** [comment]
Hopefully, this was finally fixed with https://github.com/skycocker/chromebrew/pull/5260 .
