### ISSUE TITLE
[install.sh] producing error

### ISSUE THREAD

**Issue by milan-stoj** [skycocker/chromebrew#5119]
## Description
When I try to run the install script on a freshly recovered and power-washed machine in developer mode, I get an error.

```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
chown: cannot access '/usr/local/bin': No such file or directory.
```

## Versions and system information
**ChromeOS:**
```shell
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7069196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={55DA7A1B-DCE6-47E6-95EC-0CCB7AC432F5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={55DA7A1B-DCE6-47E6-95EC-0CCB7AC432F5}
CHROMEOS_RELEASE_BOARD=soraka-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=111
CHROMEOS_RELEASE_BUILDER_PATH=soraka-release/R87-13505.111.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.111.0 (Official Build) stable-channel soraka
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.111.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.111.0
```

**Model:** HP Chromebook x2

**Architecture:**
x86_64

## Additional information
A few weeks ago the script was working fine on my machine. Can't say for sure if a change to the install script or an update to ChromeOS is what is now this issue.

EDIT: Using last version of install.sh worked fine for me.

**Comment by saltedcoffii** [comment]
I'm having this exact problem

**Comment by uberhacker** [comment]
@satmandu:  This should be fixed before anything else since it affects the install process.  I'm thinking we should return to the old logic.  If somebody has a mount in `/usr/local` then they are already in YMMV territory.  Chromebrew does not need to dance around Crouton or other chroots if this is the result.  In fact, Chromebrew should REPLACE Crouton or chroots of other operating systems.  That is the whole goal of this project.  We shouldn't need a chroot of another operating system if Chrome OS can run programs natively.

**Comment by satmandu** [comment]
@uberhacker I think we're hitting set exit on fail here, if we're trying to chown a folder which doesn't yet exist. The obvious solution here would be to make chown not exit on fail, no?

**Comment by satmandu** [comment]
What do you think of this:
```for folder in $crew_folders ; do sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"$folder" || true ; done```

**Comment by uberhacker** [comment]
I don't like the idea of whitelisting or blacklisting any folders.  The way we had it working previously is fine.  We shouldn't try to support users that want to set their own mounts.  That is YMMV territory.  All we need to do is add a warning in README.md.  It's OK not to support everything.

**Comment by satmandu** [comment]
Even crouton restricts itself to a subset of /usr/local. Ideally we would only touch files we are specifically installing. 

I'd be more ok with doing a generic chown to a folder if it was a folder that was chromebrew only... and /usr/local is used by more, no?  Google's sometimes-officially-supported dev-install uses /usr/local too: https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/install-software-on-base-images

**Comment by satmandu** [comment]
If anyone wants to play along, I'm trying this version of the install script on my build image now:

``` curl -Lsf curl -Ls https://github.com/satmandu/chromebrew/raw/install.sh_chown_logic/install.sh | bash ```

**Comment by satmandu** [comment]
Ok this appears to work just fine, ignoring the failures in my virgin container which lacks anything in /usr/local.

**Comment by uberhacker** [comment]
Reopening since i686 still has an issue.
