### ISSUE TITLE
Imagemagick6 and Imagemagick7 can't coexist, Inkscape Install failing because of it

### ISSUE THREAD

**Issue by booperlv** [skycocker/chromebrew#5124]
I tried to install Inkscape using
```
crew install inkscape
```
but it stopped midway with the last message being
```
ImageMagick version 6.9.11-29 already installed.
```

I then tried to uninstall Imagemagick6 and reinstalled, didn't work.
Tried to install Imagemagick7 first, didn't work.

Is there a different way to install inkscape? or does this need to be patched?
Thanks in advance!

**Comment by uberhacker** [comment]
Thank you for the feedback @booperlv.  I imagine inkscape has an update.  Have you tried installing from source with `crew install inkscape -s`?

**Comment by booperlv** [comment]
Tried it out just now, same error encountered, inkscape version doesn't change between -s and normal install either

**Comment by booperlv** [comment]
Hi @uberhacker, I'm guessing this can be solved by treating these packages as separate instead of versions of the same package? I don't have the experience with ruby to be able to make a pull request for this, but this seems to be fairly easy to do judging from the code. Can I ask you to do that if it is okay both in the practicality and effort sense?
