### ISSUE TITLE
Chromebrew doesn't properly calculate dependencies

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5160]
While testing a new package, I ran into the strangest error:
https://hatebin.com/khhsvqkydl
In that log, chromebrew attempts to install `flatpak`, a dependency of pakitheme, before any other dependencies, including flatpak's dependencies. Because flatpak's postinstall requires executing the flatpak binary, it was missing libraries and failed. 

This isn't the only instance this happens. On a newly installed chromebrew, try installing anything that has a decent amount of dependencies, e.g., sommelier, from the source with `crew install -S sommelier`. One will quickly notice that chromebrew doesn't calculate dependencies in the right order, causing packages to fail to compile.

I'm not sure what's causing this, but it's certainly a problem.

**Comment by uberhacker** [comment]
We should probably wait until flatpak and dependencies are merged into master before we open an issue.  I'm going to tag this as an enhancement.

**Comment by supechicken** [comment]
See #6840
