### ISSUE TITLE
crew openssl installation breaks https certificate verification

### ISSUE THREAD

**Issue by dmcaulay** [skycocker/chromebrew#52]
It looks like this issue was simply ignored by adding the `--no-check-certificate` option in https://github.com/skycocker/chromebrew/commit/8b773b1b46d7a2b8b404f591f1768f022c7aa51d. I verified that removing the chromebrew openssl installation fixed the issue for me. If I have more free time I'll continue to investigate.

**Comment by Downchuck** [comment]
Seems like libcurl could use libcurl-gnutls.so.4 -- not sure if that's related.

**Comment by thedamian** [comment]
Now I don't know if I didn't install something from crew that will break this. But when trying to test this and  trying the line in that check in that you mentioned and running it from the shell:

wget https://raw.github.com/skycocker/chromebrew/master/lib/package.rb

It works on my box and I have crew and about 10 packages from there installed (including ruby and node and nano etc)

What can I run to confirm that crew has changed something on my chromebook?

**Comment by lyxell** [comment]
This is impossible to recreate at the moment since chromebrew no longer installs it's own openssl. This issue can safely be closed.
