### ISSUE TITLE
tcpdump doesn't install along with several other packages such as nano 

### ISSUE THREAD

**Issue by charlieporth1** [skycocker/chromebrew#521]
tcpdump doesn't install along with several other packages such as nano it needs perl 5 and openssl

**Comment by jam7** [comment]
@charlieporth1 Do you still have problem?  I'm not sure about what the source of tcpdump problem, but at least the source of nano problem is fixed at #490.  Please retry them and let us know if you still have problem.  Thanks.

**Comment by lyxell** [comment]
Closing as inactive.
