### ISSUE TITLE
Installation Issue: git not installing properly

### ISSUE THREAD

**Issue by booperlv** [skycocker/chromebrew#5210]
Here's the few relevant parts of the installation as nothing else is out of the norm
```shell
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.30.0-2-chromeos-x86_64.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Adding new information on git to device.json...
Downloading icu4c...
######################################################################## 100.0%
Verifying icu4c...
icu4c-68.2-chromeos-x86_64.tar.xz: OK
Extracting icu4c (this may take a while)...
Installing icu4c (this may take a while)...
Adding new information on icu4c to device.json...
Downloading libedit...
######################################################################## 100.0%
Verifying libedit...
libedit-20191231-3.1-chromeos-x86_64.tar.xz: OK
Extracting libedit (this may take a while)...
Installing libedit (this may take a while)...
Adding new information on libedit to device.json...
bash: line 189: git: command not found
```

ChromeOS: 
`CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_RELEASE_BOARD=gnawty-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=94
CHROMEOS_RELEASE_BUILDER_PATH=gnawty-release/R88-13597.94.0
CHROMEOS_RELEASE_BUILD_NUMBER=13597
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=88
CHROMEOS_RELEASE_DESCRIPTION=13597.94.0 (Official Build) stable-channel gnawty 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13597.94.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13597.94.0`

Model: Acer CB3-11, Chromebook 11

Architecture: `x86_64`

Anyone else encountered this error? Or is it just in my case?
I've tried switching from stable then back to dev and powerwashing to no avail thus far.
This seems rather unusual, should I try to install git separately first just to see if it actually is a problem with the script and not with my device?

**Comment by supechicken** [comment]
Can you post the result of the following commands:
```shell
if [ -f /usr/local/bin/git ]; then echo 1; else echo 0; fi
```
It is probably not your fault :) Maybe there have some issues with our installation script.

**Comment by booperlv** [comment]
sorry for the late reply, the output is ``1``.
Went to the said directory and well - interestingly enough, the git command had worked immediately after a literal power off and power on. Don't get how that happened since I had already restarted TONS of times. Thanks for the help anyway!
