### ISSUE TITLE
[aircrack-ng] error: while loading shared libraries: libssl.so.1.0.0

### ISSUE THREAD

**Issue by lonestone463** [skycocker/chromebrew#5235]
## Description
ISSUE: I'm currently trying to build some cyber-security oriented projects using ChromeOS 
in order to test somethings in my home lab, I need aircrack-ng (along with some other tools listed via 'crew search' ) to be functional however upon 
downloading I recieve the error msg: ./aircrack-ng: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory (see attached image as well) 

If you executed a specific command:
```
./aircrack-ng 
```

Output:
```
./aircrack-ng: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: 1.7.5

ChromeOS: 
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_RELEASE_BOARD=gnawty-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=94
CHROMEOS_RELEASE_BUILDER_PATH=gnawty-release/R88-13597.94.0
CHROMEOS_RELEASE_BUILD_NUMBER=13597
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=88
CHROMEOS_RELEASE_DESCRIPTION=13597.94.0 (Official Build) stable-channel gnawty 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13597.94.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13597.94.0

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Addtional information
Mention things we might need to know. Like:

What I think needs to be done:
From my research and digging on other forums my understading is that there are two possible solutions. Either (A.) Download the missing module ( libssl.so.1.0.0 in this case)--which I haven't been able to find or do. (B.) Create a symbolic link using 'ln -s' point to the desired/current available module (libssl.so.1.1) 

- [step 1] 'ln -s libssl.so.1.0.0 libssl.so.1.1'
- [ step 2] 'ln -s libcrypto.so.1.0.0 libssl.so.1.1'

However, despite doing this i'm still getting the same error as I did to start.

PS (NOTE): 
Though this is occuring specifically with 'aircrack-ng' tool the issue of 'error: while loading shared libraries: [some-library]', is occuring when attempting to make use of other tools such as 'tcpdump'
![Screenshot 2021-02-21 at 5 18 31 PM](https://user-images.githubusercontent.com/79465201/108731605-54e2f600-74f2-11eb-9eb6-50479f4d433d.png)

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by satmandu** [comment]
Does ```crew reinstall openssl``` help?

**Comment by lonestone463** [comment]
Unfortunately, no :/. I ran the commad but still recieved the same error message: "./aircrack-ng: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory"

**Comment by lonestone463** [comment]
Also my architecture is: 

Linux localhost 4.4.241-19420-g5a63ca2874a0 #1 SMP PREEMPT Mon Feb 15 21:52:18 PST 2021 x86_64 Intel(R) Celeron(R) CPU N2840 @ 2.16GHz GenuineIntel GNU/Linux

**Comment by uberhacker** [comment]
@lonestone463: There is an update to this package.  See https://download.aircrack-ng.org/aircrack-ng-1.6.tar.gz.

**Comment by uberhacker** [comment]
Apply the attached patch with `patch -p1 < aircrack_ng.rb.patch.txt` and then try to install with `crew install aircrack_ng -s`.

[aircrack_ng.rb.patch.txt](https://github.com/skycocker/chromebrew/files/6024650/aircrack_ng.rb.patch.txt)

**Comment by lonestone463** [comment]
Just to be clear I should do the following and check back in: --
1. crew remove aircrack-ng 
2. cd /usr/local/lib/crew/packages && patch -p1 aircrack_ng.rb < ~/Downloads/aircrack_ng.rb.patch.txt (Apply the attached patch) 
3. crew install aircrack_ng -s

**Comment by uberhacker** [comment]
You should need to remove if you were never able to install.

**Comment by lonestone463** [comment]
also thanks for the help thus far @uberhacker and @satmandu

**Comment by lonestone463** [comment]
^^ okay gotcha I'll give it a try!

**Comment by uberhacker** [comment]
If this works, let us know and we can create a PR for the update or if you feel adventurous, you can give it a try. :)

**Comment by lonestone463** [comment]
1. Honesty if you guys are cool with creating a PR that would be awesome! I've been working on a personal prj to leverage ChromeOS to create a quasi sec. distro based around the already secure OS (might be a fools errand on my part)--so that people who are interested in cyber-sec but can't afford expensive hardware can still get something out of the affordable Chromebook.

2.Package was successfully patched and installed! BUT again when I run ```./aircrack-ng```, its giving me the same  ```libcrypto.so.1.0.0: cannot open shared object file: No such file or directory```, I'm thinking I'm doing something wrong with my execution potentially. The tool is located in my directory ```/usr/local/bin``` :/

**Comment by uberhacker** [comment]
I'm wondering if the `aircrack-ng` binary is looking for libraries in `/usr/local/lib` instead of `/usr/local/lib64`.  Is your architecture x86_64?  If so, you might try this: `export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib`.

**Comment by lonestone463** [comment]
I recieved the following output after running the command ```ldd $(which aircrack-ng)```
```
    linux-vdso.so.1 (0x00007ffcf15d0000)
        libpthread.so.0 => /usr/local/lib64/libpthread.so.0 (0x00007c0c07f51000)
        libssl.so.1.0.0 => /usr/local/lib64/libssl.so.1.0.0 (0x00007c0c082e3000)
        libcrypto.so.1.0.0 => not found
        libsqlite3.so.0 => /usr/local/lib64/libsqlite3.so.0 (0x00007c0c08199000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007c0c07d7c000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007c0c07d62000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007c0c079a9000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007c0c0816f000)
        libcrypto.so.1.1 => /usr/local/lib64/libcrypto.so.1.1 (0x00007c0c0766c000)
        libdl.so.2 => /usr/local/lib64/libdl.so.2 (0x00007c0c07468000)
        libz.so.1 => /usr/local/lib64/libz.so.1 (0x00007c0c07448000)
        libm.so.6 => /usr/local/lib64/libm.so.6 (0x00007c0c070e9000)
```
From what I can see the ```libssl.so.1.0.0``` shared lib is almost fixed but now ```libcrypto.so.1.0.0 => not found``` is now the problem--but I could be wrong lol i'm just a newb

**Comment by satmandu** [comment]
FYI, OpenSSL doesn't include ```libssl.so.1.0```

```
crew files openssl | grep libssl.so
/usr/local/lib64/libssl.so
/usr/local/lib64/libssl.so.1.1
```
aircrack-ng might need to be compiled against OpenSSL again. Please also make sure to remove Libressl if it exists on the system. If you are compiling against older headers for either libressl or OpenSSL, then that might be why it is looking for libssl.so.1.0.

**Comment by lonestone463** [comment]
I removed ```libressl``` and performed a reinstallation of both ```openssl``` using ```crew reinstall openssl -s```. After this I reattempted using the tool however still recieved and error regarding the ```libcrypto.so.1.0.0```. 

It seems the previous adivice provided by @uberhacker fixed the ```libssl.so.1.0.0``` error but i'm still missing libcrypto--maybe a similar strategy or patched needs to be deployed?

**Comment by satmandu** [comment]
I can get this to compile just fine if we update the aircrack_ng source and modify to use the updated configure setup.

I have a package incoming later this morning once I'm back from kid drop-off.

**Comment by satmandu** [comment]
Also, @uberhacker @cstrouse maybe we want to suggest that people check for an updated software release, and if one exists, to try that, before filing a bug report? The aircrack-ng sources were well over a year out of date, with multiple source releases between the one in our package file and what is current.

**Comment by lonestone463** [comment]
Hopefully this isn't a silly question but aside of more research is there anything else I can do on my end?

**Comment by satmandu** [comment]
ok I'm no longer seeing an OpenSSL related issue on my end with  the build I'm about to upload:
```
bash-5.1$ ldd `which aircrack-ng`
        linux-vdso.so.1 (0x00007ffe6bdc2000)
        libaircrack-osdep-1.6.0.so => /usr/local/lib64/libaircrack-osdep-1.6.0.so (0x00007f188b700000)
        libnl-3.so.200 => /usr/local/lib64/libnl-3.so.200 (0x00007f188b2ce000)
        libnl-genl-3.so.200 => /usr/local/lib64/libnl-genl-3.so.200 (0x00007f188b0c8000)
        libsqlite3.so.0 => /usr/local/lib64/libsqlite3.so.0 (0x00007f188b5c2000)
        libpthread.so.0 => /usr/local/lib64/libpthread.so.0 (0x00007f188aeaa000)
        libz.so.1 => /usr/local/lib64/libz.so.1 (0x00007f188b5a3000)
        libssl.so.1.1 => /usr/local/lib64/libssl.so.1.1 (0x00007f188adf9000)
        libcrypto.so.1.1 => /usr/local/lib64/libcrypto.so.1.1 (0x00007f188aabc000)
        libdl.so.2 => /usr/local/lib64/libdl.so.2 (0x00007f188a8b8000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007f188a6e3000)
        libm.so.6 => /usr/local/lib64/libm.so.6 (0x00007f188a384000)
        libssp.so.0 => /usr/local/lib64/libssp.so.0 (0x00007f188b59c000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f188b580000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x00007f1889fcb000)
        /lib64/ld-linux-x86-64.so.2 => /usr/local/lib64/ld-linux-x86-64.so.2 (0x00007f188b4eb000)
```

**Comment by lonestone463** [comment]
Yo sorry for the late response. Shouts out to @satmandu @uberhacker thank you my dudes!!! I can now coninute my chrome cyber-sec project, instead of having to build all of the tools from scratch using bash or golang :D

**Comment by VenomousSteam81** [comment]
Now, in 2024, I'm having this exact same issue but I'm using `nping` instead of `aircrack-ng`. I'm going to create a new issue, though.
