### ISSUE TITLE
Chromebrew doesn't install correctly

### ISSUE THREAD

**Issue by TheRubiksGamer** [skycocker/chromebrew#524]
uname -m
armv7l

uname -a
Linux localhost 3.8.11 #1 SMP Wed Feb 1 14:47:31 PST 2017 armv7l ARMv7 Processor rev 4 (v7l) SAMSUNG EXYNOS5 (Flattened Device Tree) GNU/Linux

Samsung 303c chromebook

Crew and ruby will install, but won't properly install git.
At the end after downloading every thing, it shows this error

/usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- package (LoadError)
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/crew/packages/readline.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/bin/crew:41:in `setPkg'
        from /usr/local/bin/crew:59:in `block in search'
        from /usr/local/lib/ruby/2.0.0/find.rb:43:in `block in find'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `catch'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `find'
        from /usr/local/bin/crew:58:in `search'
        from /usr/local/bin/crew:421:in `<main>'
/usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- package (LoadError)
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/crew/packages/git.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/bin/crew:41:in `setPkg'
        from /usr/local/bin/crew:59:in `block in search'
        from /usr/local/lib/ruby/2.0.0/find.rb:43:in `block in find'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `catch'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `find'
        from /usr/local/bin/crew:58:in `search'
        from /usr/local/bin/crew:421:in `<main>'
ln: failed to create symbolic link ‘/usr/local/bin/cc’: File exists
bash: line 116: git: command not found
bash: line 117: git: command not found
bash: line 118: git: command not found
bash: line 119: .git/info/sparse-checkout: No such file or directory
bash: line 120: .git/info/sparse-checkout: No such file or directory
bash: line 121: .git/info/sparse-checkout: No such file or directory
bash: line 122: git: command not found
bash: line 123: git: command not found

I have tried reinstalling, but it didn't help.

**Comment by jam7** [comment]
It looks like you miss `/usr/local/lib/crew/lib/packages.rb` although it is just installed by `install.sh`.

Don't you mind to retry installation after removing your `/usr/local/lib/crew` once?

**Comment by TheRubiksGamer** [comment]
I have tried that, but it still didn't work. Will try it again when I get home though.

**Comment by TheRubiksGamer** [comment]
Thanks for the help! I was able to get it to work by clearing the install files and using your Chomebrew script instead.
