### ISSUE TITLE
Cannot install through proxy

### ISSUE THREAD

**Issue by logan2k** [skycocker/chromebrew#5285]
My network is only working behind a proxy. The Chrome OS proxy settings don't apply to shell, including the install process for Chromebrew. How can I get around that?

**Comment by satmandu** [comment]
How would you suggest one get ChromeOS's proxy settings from the command line?

**Comment by satmandu** [comment]
Try doing this```export https_proxy=https://proxy.server.com:6443``` before starting the install, since curl is known to respect that environment variable.
