### ISSUE TITLE
[URGENT] Discussion: Jfrog bintray is being discontinued

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#5287]
@uberhacker - (If you are infact still the main contributor)
 As the title says, Jfrog plans to "sunset" bintray on May 1<sup>st</sup>, obv this is very bad for Chromebrew.  
> https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We'll need not only a new hosting service, but we'll need one fast.  
If things aren't moved by May 1<sup>st</sup> Chromebrew will crash and burn as all binaries will be lost.  
I personally have no idea whats to be done, or needs to be done, but I'm sure someone has an idea.  
Either way, time is of the essence if we want to keep Chromebrew alive and well.

**Comment by satmandu** [comment]
IIRC @uberhacker was reaching out to packagecloud.

**Comment by ThatGeekyWeeb** [comment]
Hopefully that goes well, but since packagecloud isn't free, I doubt much will come of it-

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: But the thing is packagecloud is free for open source projects.  From their website:
```
packagecloud supports Open Source Projects

Thousands of open source projects rely on packagecloud to distribute
their software around the world for free.

Contact us to start distributing your open source project with packagecloud
```

**Comment by ThatGeekyWeeb** [comment]
Ah, I misread then, hopefully that goes well. Goodluck

**Comment by satmandu** [comment]
FYI:

![image](https://user-images.githubusercontent.com/1096701/109510914-89196200-7a70-11eb-946b-32a71eb4b4ad.png)

Also 
![image](https://user-images.githubusercontent.com/1096701/109512299-f5e12c00-7a71-11eb-8d55-ad8e01ef1ea2.png)

(the text about bintray no longer allowing uploads by the end of February seems to be gone.)

**Comment by ThatGeekyWeeb** [comment]
Good we have more time!

**Comment by saltedcoffii** [comment]
@uberhacker I think we can close this now.

**Comment by mattfox** [comment]
Hi- Matt from [Balto Repo](https://www.getbalto.com/) here, where someone has uploaded the Chromebrew library of files.

Couple of questions-

1. What's your intention for use of Balto Repo for Chromebrew? Point all clients to download from there?
2. Does anyone know what the expected monthly network transfer for this is? I asked the person who signed up for the account for an estimate but did not receive an answer.

Balto Repo would love to help. But I don't want to set unrealistic expectations either, if it's a large amount of transfer. Or maybe Chromebrew has some sponsorship and can pay for the bandwidth?

**Comment by uberhacker** [comment]
Hey @mattfox:
Our main binary repo is https://sourceforge.net/projects/chromebrew/ so we don't plan on using Balto as mentioned in 1).  I'm not sure of the monthly network transfer statistics on Bintray so I don't have an answer for 2).
Thanks
