### ISSUE TITLE
crew whatprovides broken

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5294]
Running `crew whatprovides <anything>` results with the following issue:
```
/usr/local/bin/crew:383:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/bin/crew:383:in `block (2 levels) in whatprovides'
        from /usr/local/bin/crew:382:in `each'
        from /usr/local/bin/crew:382:in `block in whatprovides'
        from /usr/local/lib64/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `find'
        from /usr/local/bin/crew:378:in `whatprovides'
        from /usr/local/bin/crew:1081:in `block in whatprovides_command'
        from /usr/local/bin/crew:1080:in `each'
        from /usr/local/bin/crew:1080:in `whatprovides_command'
        from /usr/local/bin/crew:1092:in `<main>'
```

**Comment by satmandu** [comment]
This is a locale issue. We need to fix this.

Setting a locale manually fixes this.

@uberhacker @cstrouse @supechicken any ideas?

**Comment by uberhacker** [comment]
What do you mean a manual locale setting fixes it?  Please elaborate.

**Comment by satmandu** [comment]
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
Then try ```crew whatprovides <anything>```

**Comment by satmandu** [comment]
in my docker container this is what appears by default:
```
locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
in ChromeOS (actual) this is what appears for me:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by saltedcoffii** [comment]
Looks like 
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
fixed it.

Perhaps we can get that into people's `~/.bashrc`s, perhaps in the `glibc` package, since that's what manages locales anyway?

**Comment by uberhacker** [comment]
What happens if you adjust your Docker container environment to match ChromeOS?  I think our goal should be to simulate actual Chromebook hardware and configurations as closely as possible.

**Comment by satmandu** [comment]
@uberhacker A little googling suggests that ChromeOS locale is set in the vpd firmware, which you can get by doing a ```sudo cat /mnt/stateful_partition/
unencrypted/cache/vpd/filtered.txt```

There's a string there such as ```"region"="us"```

[This ](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/regions)will tell you what locale that translates to.

For instance ```"region"="us"``` translates to: 
```Region(
    'us', 'xkb:us::eng', 'America/Los_Angeles', 'en-US', KML.ANSI,
    'United States'),
```
The locale is clearly in there. I'm not sure where that gets converted to the environment variables though. Maybe this is a glibc modification of Google's?

BUT...

it turns out I've had my own .bashrc set to have this line in it:
```
LC_ALL=en_US.UTF-8
```

And that's an override which sets my system to have that locale at all times.

I can't seem to find where that might be set normally in ChromeOS...

**Comment by saltedcoffii** [comment]
FYI, `LC_ALL` can break program compilation and running if it's set incorrectly. It's always safer to set `LANG`.

**Comment by supechicken** [comment]
Try to add the following to `crew`"
```ruby
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```
(This will force utf8 encoding)

**Comment by uberhacker** [comment]
Unfortunately, that doesn't work for me.  However, exporting the environment variables does work.

**Comment by uberhacker** [comment]
Looks like there is a new issue with `crew whatprovides` as reported by @satmandu below:
```
$ crew whatprovides /usr/lib64/lib
cairo-gobject.so.2
$ crew whatprovides libcairo-gobje
ct
```
