### ISSUE TITLE
[curl and wget] Cert is not trusted

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5296]
Only happens on i686 architecture.
```
$ curl -L https://www.php.net/distributions/php-8.0.2.tar.xz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
$ wget https://www.php.net/distributions/php-8.0.2.tar.xz
--2021-02-28 03:53:25--  https://www.php.net/distributions/php-8.0.2.tar.xz
Resolving www.php.net (www.php.net)... 185.85.0.29, 2a02:cb40:200::1ad
Connecting to www.php.net (www.php.net)|185.85.0.29|:443... connected.
ERROR: The certificate of ‘www.php.net’ is not trusted.
ERROR: The certificate of ‘www.php.net’ doesn't have a known issuer.
```

**Comment by uberhacker** [comment]
What I tried without success:
1. crew reinstall ca_certificates
2. crew remove ca_certificates
3. restart crosh session
4. reboot
5. crew reinstall wget -s

**Comment by satmandu** [comment]
Hmm. Where is curl looking for certs?

**Comment by satmandu** [comment]
Maybe we should set ```SSL_CERT_DIR=/usr/local/etc/ssl/certs``` globally instead of having curl have```CURLOPT_CAPATH=/usr/local/etc/ssl/certs``` set and also having wget having ```ca_certificate=/usr/local/etc/ssl/certs/ca-certificates.crt``` set in a wgetrc?

We could do that from the ca_certiticates package... but maybe we also need to work on a package to set these globally in /usr/local/etc/env.d files like gentoo does... 

It's getting cumbersome setting global environment variables in ```~/.bashrc``` from various postinstall scripts.

**Comment by uberhacker** [comment]
I think part of the problem is the Docker containers don't simulate a true ChromeOS environment fully.  Rather than setting a bunch of environment variables, it probably makes more sense to work on a better Docker build environment.

**Comment by uberhacker** [comment]
In the meantime, I updated the [FAQ](https://github.com/skycocker/chromebrew/wiki/FAQ) to include the solutions above.
