### ISSUE TITLE
Unable to install chromebrew

### ISSUE THREAD

**Issue by thorstenludwigs** [skycocker/chromebrew#5316]
I Get an error message when I try to install chromebrew

 * [new tag]           v0.2.1                           -> v0.2.1
 * [new tag]           v0.2.1.1                         -> v0.2.1.1
 * [new tag]           v0.2.1.2                         -> v0.2.1.2
 * [new tag]           v0.3                             -> v0.3
 * [new tag]           v0.3.1                           -> v0.3.1
 * [new tag]           v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 0d97639d Gnome shell prereqs (#5315)
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 0d97639d Gnome shell prereqs (#5315)
Package lists, crew, and library updated.
Generating compatible packages...
/usr/local/bin/crew:201:in `block in generate_compatible': undefined method `include?' for nil:NilClass (NoMethodError)
        from /usr/local/lib64/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `find'
        from /usr/local/bin/crew:197:in `generate_compatible'
        from /usr/local/bin/crew:414:in `update'
        from /usr/local/bin/crew:1064:in `update_command'
        from /usr/local/bin/crew:1092:in `<main>'

Surface Pro 7 (Brunch r88 stable 20210223) 

I have installed it on a similar laptop yesterday and it worked.
Thanks for your help in advance.

**Comment by satmandu** [comment]
@thorstenludwigs Just noticed this too. I think there's a package file which is causing an error... Looking at it now.

**Comment by thorstenludwigs** [comment]
@satmandu yes it broke after updating the Gnome shell packages

**Comment by satmandu** [comment]
I think it is the ibus.rb file, but I can't seem to find anything wrong with it. @uberhacker @supechicken any ideas on why it is stopping on scanning that file?

**Comment by uberhacker** [comment]
@thorstenludwigs: Try again.  This issue should be fixed now.
