### ISSUE TITLE
Node install not working?

### ISSUE THREAD

**Issue by petegordon** [skycocker/chromebrew#535]
Node and Node_current packages return an error when trying to install.  Maybe with libmvec_nonshared.a

![screenshot 2017-02-19 at 1 53 18 pm](https://cloud.githubusercontent.com/assets/1993032/23105303/3b857634-f6ab-11e6-861d-fbd62a720c70.png)

**Comment by jam7** [comment]
Don't you use dev or beta channel?  As far as I know, this problem is caused by the fact that they are using glibc-2.23 although current chromebrew provides only glibc-2.19.  You can try glibc223 #533 if you want.

**Comment by bpstrngr** [comment]
months of headache resolved.... Thank You!
