### ISSUE TITLE
Vim and neovim cannot be both installed

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#5374]
Due to the removal of libiconv in vim package, neovim and vim cannot be installed together. What lead to the need to remove libiconv to install vim ?

**Comment by satmandu** [comment]
The dependency tree is `libiconv -> gettext nls -> vim`

I'm not quite sure why gettext doesn't recognize the iconv from glibc as sufficient, because it should be...

**Comment by vincowl** [comment]
What surprises me is that it is mandatory to uninstall libiconv to install vim, which leads to forbid neovim installation.

**Comment by satmandu** [comment]
The rationale was that libiconv dependencies were polluting everything, and on a Linux system, glibc should be providing libiconv.

compiling vim without nls gets rid of the libiconv dependency.

Is the nls important? we could put libiconv back in... but I was seeing weird compilation issues from packages seeing libiconv when they didn't expect it.

**Comment by vincowl** [comment]
Agree with that.
But still don't understand why it is now mandatory to uninstall libiconv to install vim. If libiconv is not a vim dependency, vim install should not be polluted by this. Am I wrong ?

**Comment by satmandu** [comment]
It's an ugly hack. IIRC this was in the build section so it wouldn't come up during installs.

Moving it to preflight might have been the problem here. @uberhacker ?

**Comment by uberhacker** [comment]
See #5380.

**Comment by satmandu** [comment]
Try this again @vincowl .

**Comment by vincowl** [comment]
Well..... I can now install both vim and neovim. BUT : my vim install is no more usable since it doesn't understand my .come which works like a charm with neovim and the previous vim version.... Under investigation !

**Comment by vincowl** [comment]
That's fine. Everything works like a charm. That was a local problem.
