### ISSUE TITLE
Milestone 90 implements nosymfollow on home mount

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#5400]
More info: https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.10-nosymfollow

This causes ruby problems if you have any gems installed because `xdg_base` symlinks 
`~/.config` to  `/usr/local/.config` and gem wants to drop local installs into that folder, which end up on a symlinked folder. 

This also causes issues with any apps which store preferences inside `~/.config` - which means all gtk apps.

```
chronos@localhost /usr/local/lib/crew/packages $ crew update
<internal:dir>:134:in `glob': Too many levels of symbolic links - /home/chronos/user/.local/share/gem/ruby/3.0.0/specifications (Errno::ELOOP)
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/util.rb:101:in `glob_files_in_dir'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:771:in `gemspec_stubs_in'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:786:in `block in map_stubs'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:783:in `each'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:783:in `flat_map'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:783:in `map_stubs'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:776:in `installed_stubs'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:841:in `stubs_for_pattern'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/specification.rb:830:in `stubs_for'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/dependency.rb:276:in `matching_specs'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/dependency.rb:303:in `to_specs'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'
        from /usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        from <internal:/usr/local/lib64/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:73:in `require'
        from <internal:gem_prelude>:8:in `<internal:gem_prelude>'
```
One workaround is to run `sudo mount -o remount,symfollow /home/chronos/user` but a cleaner solution involves: 
- change `XDG_` variables not to store files in a symlinked folder.
- have ruby not store gems in a user folder by putting `gem: --no-user-install --no-rdoc --no-ri ` in `/usr/local/etc/gemrc`
- change the flatpak wrapper script to NOT use `--user`

**Comment by brunnels** [comment]
This is still a problem and impacts flatpak installed apps too.  The remount resolves it until logout/reboot.

**Comment by saltedcoffii** [comment]
maybe we could add a remount to crew_profile_base along with mounting `~` as `exec` as well to make things like Minecraft work.

**Comment by satmandu** [comment]
Not remounting at all would be ideal...

**Comment by brunnels** [comment]
I think @supechicken had it figured out

**Comment by saltedcoffii** [comment]
This seems to be fixed with symlinks, reopen if not.
