### ISSUE TITLE
command to remove all dependencies for certain app

### ISSUE THREAD

**Issue by sudo-power** [skycocker/chromebrew#5437]
So I tried to install gnome_terminal but install failed. All dependencies stayed installed. Now my chromebook has low space. Is there any way to remove all dependencies for gnome_terminal???

**Comment by uberhacker** [comment]
@sudo-power: Try this: `for p in $(crew search gnome -d | cut -d':' -f1 | xargs) do; crew remove $p; done`

It will remove any package with gnome in the name.  Another thing you could try is `crew install clear-cache && clear-cache`.  I've noticed this often removes up to and even more than 1 gb.

**Comment by sudo-power** [comment]
Thanks!!! Will bookmark this issue page in case I forget the command. Anyway issue closed.

**Comment by saltedcoffii** [comment]
closing because of `crew autoremove`
