### ISSUE TITLE
Is elixir working?

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#544]
Just curious, while I am trying to compile elixir, my c202sa (x86_64 4GB) chromebook crashes because of, my guess, memory exhausted.  So, I just want to know it is only for me or everyone.  And want to know how much memory is required to prepare elixir.

My c202sa is crashed and rebooted.  So, be careful if you try it.  Thanks.

And if it is for everyone, I think adding some mechanism to check the amount of free memory size is good to do.

**Comment by bfayers** [comment]
Perhaps [get some swap?](http://www.omgchrome.com/how-to-add-swap-memory-to-your-chromebook/)

**Comment by jam7** [comment]
@bfayers, thank you for the info.  I've checked it and found recent chromebook is using swap by default.  It is 1.5 times bigger than physical memory.  It is not enough to compile elixir.  It may work if I increased it to 2 times or more, but I've not tested it yet.

**Comment by uberhacker** [comment]
See PR #864.

**Comment by jam7** [comment]
thanks.  I'll try that one.

2017年7月8日(土) 14:09 Ed Reel <notifications@github.com>:

**Comment by jam7** [comment]
Closing in favor of #864.
