### ISSUE TITLE
avisynthplus is unlicensed

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5449]
Because avisynthplus is unlicensed, they legally have all rights reserved and we cannot be distributing binaries/source code. This is likely an oversight and I've opened an [upstream issue](https://github.com/AviSynth/AviSynthPlus/issues/211), however until that's resolved it's likely prudent to remove the package from chromebrew's repositories.

**Comment by uberhacker** [comment]
According to http://www.avisynth.org/, AviSynth is free open-source software and according to http://avisynth.org.ru/docs/english/license.htm, GPL v2.

**Comment by saltedcoffii** [comment]
As far as I know, that only applies to the documentation, not the entire project. I could definitely be wrong.

**Comment by uberhacker** [comment]
Starting from 5 August 2007 the documentation on this site (avisynth.org) is released under the CreativeCommons Attribution-ShareAlike 3.0 License (abbreviated by "CC BY-SA 3.0", see also full license terms).

**Comment by saltedcoffii** [comment]
Ok looks like i'm wrong. I'll wait for upstream to clarify just in case, as it is confusing.

**Comment by uberhacker** [comment]
Right, it's important to get the license right or it could result in potential litigation.

**Comment by saltedcoffii** [comment]
This is resolved.
