### ISSUE TITLE
Is there any way to run GUI apps from the ChromeOS shell?

### ISSUE THREAD

**Issue by spaceface777** [skycocker/chromebrew#545]
According to [this XDA-Developers thread](https://forum.xda-developers.com/hardware-hacking/chromebooks/how-to-install-java-8-chrome-os-crouton-t3110778) you can run GUI Java programs on ChromeOS, but I have tried and it doesn't work. Can you use some sort of X11 forwarding to make it work?

**Comment by kirbyfan64** [comment]
Any GUI apps, or just Java ones?

I know for Gtk+, someone ran Broadway inside of crouton and then use Chrome to access the server...

In theory, I think you could build a Gtk+ version with *just* Broadway using Chromebrew.

**Comment by seitensei** [comment]
I don't see that thread on XDA mentioning anything about GUI Java programs on ChromeOS, just Java. 

Crouton does something [similar](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)) with X11 framebuffers to run GUIs in a Chrome Window, though. I'm not sure how well we could accomplish that in Chromebrew, given that crouton uses a separate Linux environment on the same kernel.

**Comment by jnsquire** [comment]
Recent versions of chromeos are running a wayland-compatible compositor, although it doesn't implement some of the more recent parts of the protocol, so e.g. gtk won't run on it. I have been able to get a graphic window to open from the shell, though.

**Comment by spaceface777** [comment]
> I have been able to get a graphic window to open from the shell, though.
How have you done this? Is there any tutorial on how to do it? I don't need GTK, just basic apps.

**Comment by jnsquire** [comment]
Install Weston, and you can run the example Weston applications using the
host-wayland wrapper script that crouton installs. I haven't tried, but
presumably you can use this to get the Wayland x server running as well.

**Comment by jbaum98** [comment]
In Crouton, there is a script called `xiwi` that does just this. I recently opened an issue (dnschneid/crouton#3173) asking the creator of Crouton to help split `xiwi` so it could be used without Crouton, such as with Chromebrew.
He hasn't responded yet, but maybe giving it a few thumbs up will help catch his attention?

**Comment by bfayers** [comment]
@jbaum98 this would be great to have! Great idea asking them to split.

**Comment by thedamian** [comment]
I'm closing this as this is not an issue. I wish there was a "forum" where we could lear about this. Crouton and especially XIWI is amazing.

**Comment by Axloqsizlik** [comment]
#2401 I tried to get this working, maybe I'll make a repo with an install script.
