### ISSUE TITLE
Cannot install android studio

### ISSUE THREAD

**Issue by lupohirp** [skycocker/chromebrew#5465]
Hi, i cannot install android studio. 
it says this: 

android_studio: Android Studio is the official IDE for Android development.
https://developer.android.com/studio
Version: 4.1.2.0
License: Apache-2.0
Not enough free disk space.  You need at least 6 GB to install.

but my disk is 256GB. And infact if i type df-h i have this:
/dev/nvme0n1p1                                                 225G   66G  148G  31% /home/chronos/user
/dev/nvme0n1p1                                                 225G   66G  148G  31% /home/chronos/user/MyFiles/Downloads

how can i solve?

**Comment by supechicken** [comment]
Can you try the following command?
```shell
sed -i "s/def self.preflight/def self.commented/g" /usr/local/lib/crew/packages/android_studio.rb && crew install android_studio
```
This will remove the disk space check

**Comment by uberhacker** [comment]
@lupohirp:  Thank you for your issue.  What is the output of `echo $(($(stat -f --format="%a*%S" .)))`?

**Comment by uberhacker** [comment]
@jake5253: The command I provided was under the assumption that you were not using a bind mount to a microsd drive.

**Comment by jake5253** [comment]
Yeah I figured that. But that appears to be the actual command that is
used  by at least a few packages (including Android studio) to determine if
there's enough space to install said package.
