### ISSUE TITLE
DPI Scalning

### ISSUE THREAD

**Issue by leonbollerup** [skycocker/chromebrew#5487]
Hi,

Maybe not entirely a crew problem - but it seems my dpi scaling got messed up.. any idea howto ajust that.

I'm on a pixelbook i7

![image](https://user-images.githubusercontent.com/342217/112468741-f1561d80-8d68-11eb-835a-12576e70b359.png)

**Comment by leonbollerup** [comment]
Nevermind, add:

echo Xft.dpi: 192 | xrdb -merge
export GDK_SCALE=2
export GDK_SCALE_DPI=192
export SOMMELIER_SCALE=1

Do your .bashrc

**Comment by leonbollerup** [comment]
![image](https://user-images.githubusercontent.com/342217/112469716-172ff200-8d6a-11eb-9491-ce571103a4ca.png)

fyi

**Comment by supechicken** [comment]
Alternatively, you can adjust the `SCALE` variable in `~/.sommelier-default.env`
