### ISSUE TITLE
readelf broken

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5513]
binutils's readelf is broken on a fresh installation of chromebrew, saying it can't find libdebuginfod.so.1. This is provided by the elfutils package. One can either add elfutils to the dependency list of binutils, or ensure binutils doesn't compile with debuginfod support in the `./configure` options. Which one would y'all like to do?

**Comment by satmandu** [comment]
I would vote for the latter option, as that reduces a dependency.

**Comment by saltedcoffii** [comment]
I can't find an option in `./configure --help` to fix this, and I don't know how to edit configure.ac files to fix this. I'm going to look into how other distros do this, but if nothing, then I'll add elfutils as a dependency to binutils.

**Comment by satmandu** [comment]
Does binutils build with elfutils removed? If so that should remove the dep.

We need a way to build WITHOUT certain deps...

**Comment by saltedcoffii** [comment]
It does, yes, but it throws a lot of warnings.

**Comment by satmandu** [comment]
Post a build log?

**Comment by saltedcoffii** [comment]
it's basically `WARNING: cannot find debuginfod, building without debuginfod support` a bunch of times.

**Comment by heavygabriel** [comment]
@uberhacker @satmandu can we close this thread per #5768 ?
