### ISSUE TITLE
Install fails due to corrupt mandb checksum

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5524]

**Comment by satmandu** [comment]
This is due to the package version for mandb not having been uprevved before I did the rebuild/compile of mandb in https://github.com/skycocker/chromebrew/pull/5503  - @saltedcoffii Can we merge that?

**Comment by uberhacker** [comment]
What does #5503 have to do with mandb?

**Comment by satmandu** [comment]
I was asked to build several packages there, one of which is mandb...

**Comment by uberhacker** [comment]
#5503 is going to create a merge conflict with #5525.

**Comment by uberhacker** [comment]
There are a lot of missing binaries in #5503.  Can we create a separate PR to fix mandb since it prevents users from installing crew?

**Comment by uberhacker** [comment]
Fixed in #5526.
