### ISSUE TITLE
issue installing cromebrew on samsung chromebook plus

### ISSUE THREAD

**Issue by mprorock** [skycocker/chromebrew#555]
`uname -m` identifies as aarch64

If however you add an arch entry for it that dupes the existing armv7l, or force 'architecture=armv7l' it works.

**Comment by jam7** [comment]
Does #547 fix it?  We also need to duplicates all armv7l lines in every package though.

**Comment by mprorock** [comment]
I went with a more temp workaround patch for now, alerting that things have not been fully tested yet...
[0001-fix-around-aarch64.patch.txt](https://github.com/skycocker/chromebrew/files/853249/0001-fix-around-aarch64.patch.txt)

**Comment by jnsquire** [comment]
So far, I've noticed the libsigsegv isn't installing due to running it's own 'uname -m' invocation not recognizing the arch during configure.

**Comment by jam7** [comment]
Does providing libsigsegv in binary format solve your problem?

**Comment by jnsquire** [comment]
I was able to get it to build and install by forcing --build and --target to armv7a-cros-linux-gnueabi in the configure command used

**Comment by thedamian** [comment]
Before I merge the fixes we have for this https://github.com/skycocker/chromebrew/pull/556

You guys have to discuss why not force it to armv7l
and ALSO

why I have to host the packages on the amazing @jam7 repo.

**Comment by mprorock** [comment]
I am ok with forcing arm7l.  most binaries seem to run fine there, but I have noticed compile problems on several packages that run their own architecture detection.  I currently have armv7l forced on my system.

**Comment by jam7** [comment]
@thedamian It's a good point.  I was thinking aarch64 can execute both armv7hf and aarch64 binaries.  So, I choose the way to not force it.  I'm not completely sure though.

**Comment by mprorock** [comment]
it certainly can run aarch64 bins in a chroot env, as it is a 64bit kernel, but i have had issues with some binaries (non static ones for instance) since the userspace appears to be 32 bit at the moment.  not 100% sure on that though

**Comment by jam7** [comment]
@thedamian Regarding to second part, hosting, I'm not sure your point.  Are you talking about binary files URL?  I simply use my github repo to post all binaries I submitted instead of my dropbox since those are too much these days.  If you want to copy them to under official repo or official bintray, please do it.  Only you and @lyxell can perform that, so we are waiting for you guys.  We have no permission to write to the official site.

If it is not what you point to, please let me know.

**Comment by awafaa** [comment]
I can confirm that PR #547 & #556 fix this issue, I'm running it happily now on a Samsung Plus.
