### ISSUE TITLE
[bmon] Failed to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5551]
```
checking for NcursesW wide-character library... yes
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... no
configure: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
configure: error: requires an X/Open-compatible Curses library with color
bmon failed to build: `./configure --prefix=/usr/local --libdir=/usr/local/lib --mandir=/usr/local/share/man --build=armv7l-cros-linux-gnueabihf --host=armv7l-cros-linux-gnueabihf --target=armv7l-cros-linux-gnueabihf --program-prefix='' --program-suffix=''             --without-ncurses             --with-ncursesw` exited with 1
```

**Comment by saltedcoffii** [comment]
I'm getting the same error on x86_64. There is a file at `/usr/local/include/ncursesw/curses.h`. I'll debug this further, but for now, can someone add the x86_64 tag as well?

**Comment by saltedcoffii** [comment]
Bmon is failing to build because ncurses was built on a system without an RGB information file at #{CREW_LIB_PREFIX}/X11/rgb.txt . This problem should be solved if ncurses is built on a system with that file.

**Comment by satmandu** [comment]
> Bmon is failing to build because ncurses was built on a system without an RGB information file at #{CREW_LIB_PREFIX}/X11/rgb.txt . This problem should be solved if ncurses is built on a system with that file.

Which package has that file?

**Comment by saltedcoffii** [comment]
I'm not sure. It almost seems to be legacy? I can't find it.

**Comment by esprout** [comment]
I'm running into same error installing bmon.  The bmon package was also missing a bunch of other dependencies that I had to install manually first.

According to, https://en.wikipedia.org/wiki/X11_color_names, "As of X.Org Release 7.4 rgb.txt is no longer included in the roll up release,[3] and the list is built directly into the server.[4] The optional module xorg/app/rgb contains the stand-alone rgb.txt file."

The packages I needed to install manually before hitting the ncurses error are:

automake
isl
mpc
binutils
glibc
linuxheaders
pkgconfig

**Comment by satmandu** [comment]
Hmm... Which package should include rgb.txt then?

**Comment by saltedcoffii** [comment]
I don't think it's packaged yet. Looks like the source code is available [here](https://www.x.org/releases/individual/app/rgb-1.0.6.tar.bz2)

**Comment by esprout** [comment]
Still not working for me after installing rgb:

```
bmon failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --program-prefix='' --program-suffix=''             --without-ncurses             --with-ncursesw` exited with 1
chronos@localhost /usr/local/tmp $ crew install rgb
rgb: X color name database
https://xorg.freedesktop.org/
Version: 1.0.6-1
License: custom
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Stripping libraries...
Stripping binaries...
Performing post-install...
Rgb installed!
chronos@localhost /usr/local/tmp $ crew install bmon
bmon: bmon is a commandline bandwidth monitor and rate estimator.
...
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... no
configure: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
configure: error: requires an X/Open-compatible Curses library with color
bmon failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --program-prefix='' --program-suffix=''             --without-ncurses             --with-ncursesw` exited with 1
```

Also, dependencies for bmon should be fixed so I don't need to chase down and install each package.

**Comment by satmandu** [comment]
@saltedcoffii bmon has the same issue building with ncurses rebuilt with rgb installed.

This might have to be kicked upstream...
