### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by 0xfth** [skycocker/chromebrew#558]
Running default (as on GitHub) returns:
`Downloading ruby...
--2017-03-20 13:26:31--  https://dl.dropboxusercontent.com/s/3dw5ue5vhf5nj8k/ruby-2.0.0-p247-chromeos1-chromeos-x86_64.tar.gz
Resolving dl.dropboxusercontent.com... 162.125.65.6
Connecting to dl.dropboxusercontent.com|162.125.65.6|:443... connected.
Unable to establish SSL connection.
Verifying ruby...
ruby-2.0.0-p247-chromeos1-chromeos-x86_64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the $1 download.
chronos@localhost ~/Downloads $ `

**Comment by jam7** [comment]
@0xfth That URL have worked fine and sha256sum is correct.  Don't you try it again?

**Comment by 0xfth** [comment]
It couldnt establish a connection to dl.dropboxusercontent.com at the time - i assume it was offline.
seems to work now.

- close this

**Comment by okwme** [comment]
i got a similar error:

````
Verifying libssh2...
libssh2-1.4.3-chromeos-x86_64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Verification failed, something may be wrong with the $1 download.
````
