### ISSUE TITLE
Lots of configure: error when installing packages

### ISSUE THREAD

**Issue by frontalot** [skycocker/chromebrew#56]
For example, when installing nano, I see the output:

```
2015-01-06 10:07:51 (943 KB/s) - 'nano-2.3.6.tar.gz' saved [1816012]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/nano-2.3.6':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
Preconfiguring package...
make: *** No rule to make target `install'.  Stop.
Installing...
Nano installed!
chronos@localhost /etc $`
```

Is this normal? If not, any ideas on what went wrong and how to fix it?

**Comment by skycocker** [comment]
Not normal unfortunately. Could you paste your output of `echo $PATH` ?

**Comment by frontalot** [comment]
chronos@localhost / $ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin

**Comment by frontalot** [comment]
I'm also getting this error when attempting to install nano:

chronos@localhost / $ sudo crew install nano
Found nano, version 2.3.6
Following packages also need to be installed: 
libsigsegv diffutils binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential ncurses 
Do you agree? [Y/n]
y
Proceeding...
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-01-13 20:43:47--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... failed: Connection refused.
Checksum mismatch :/ try again

**Comment by skycocker** [comment]
Ok, I'll be looking at it once I set up a virtual machine, so maybe somewhere this weekend. Sorry for the delay but I'm working a lot :/

**Comment by mjfriedmann** [comment]
same here, unfortunately.  on an acer c720 installing emacs (output below).

Thanks for the awesome tool (this issue notwithstanding ;) )

emacs-24.4.tar.xz                     100%[========================================================================>]  37.89M   735KB/s   in 78s    

2015-03-17 14:07:05 (496 KB/s) - 'emacs-24.4.tar.xz' saved [39733124]
Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
checking for xcrun... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/emacs-24.4':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
Preconfiguring package...
make: *** No rule to make target `install'.  Stop.
Installing...
Emacs installed!

**Comment by tmccisdj** [comment]
I have the same type of error with vim:
checking for gcc... gcc
checking whether the C compiler works... no

any fix yet?

**Comment by tmccisdj** [comment]
I had this problem, did you install crew as root? After I tried installing as chronos then I was able to install vim.

**Comment by frontalot** [comment]
Yes, I installed crew as root.

**Comment by tmccisdj** [comment]
Try installing it as chronos and see if that fixes your problem. It did for me.

**Comment by rac3rx** [comment]
I have the same problem; any suggestions?

**Comment by lyxell** [comment]
Closing in favor of #166
