### ISSUE TITLE
Package request - stunnel

### ISSUE THREAD

**Issue by debianuser2010** [skycocker/chromebrew#560]
I would like to run stunnel on Chrome OS

:-)

**Comment by bfayers** [comment]
Download the source like this `wget https://www.stunnel.org/downloads/stunnel-5.40.tar.gz` then run `tar xvf stunnel-5.40.tar.gz` then `cd stunnel-5.40` and `./configure` then `make` and finally `make install` and let me know if it works, if not ill make a package for it

**Comment by flyingP0tat0** [comment]
Installing stunnel this way works fine. Package for stunnel at #589.
