### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by spaceface777** [skycocker/chromebrew#561]
Whenever I try to download anything it just hangs. I think that it is because of the ftp: protocol. I put a screenshot below.
![screenshot](https://cloud.githubusercontent.com/assets/12110214/24257835/352af58e-0fec-11e7-8565-6ef51b01044f.png)
Is there any reason why we use it over HTTP? I have tried changing the `ftp://` links to `http://` and it works fine.

**Comment by lyxell** [comment]
Do you still have this issue? I suspect it might have been a temporary error with the gnu ftp server.

**Comment by spaceface777** [comment]
I still have the issue. I think it's because of my school's WiFi., but by
changing it to http it will fix it.

**Comment by lyxell** [comment]
@spaceface777 No, I can't find a reason to prefer ftp over http, you're welcome to submit a pull request
