### ISSUE TITLE
can't build ncurses

### ISSUE THREAD

**Issue by riceshrug** [skycocker/chromebrew#562]
Lots of other noise (was trying to install vim on acer cb-131) but here is the error:

gcc -fPIC  --param max-inline-insns-single=1200  -o background ../obj_s/background.o -Wl,-rpath,/usr/local/tmp/crew/ncurses-6.0.tar.gz.dir/ncurses-6.0/lib  -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include  -D_GNU_SOURCE -DNDEBUG -fPIC  --param max-inline-insns-single=1200  -fPIC  `echo "-L../lib -lformw -lmenuw -lpanelw -lncursesw   " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil -lm
/usr/local/lib/gcc/x86_64-cros-linux-gnu/4.9.x/../../../../x86_64-cros-linux-gnu/bin/ld: cannot find /usr/lib64/libmvec_nonshared.a
collect2: error: ld returned 1 exit status
make[1]: *** [background] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/tmp/crew/ncurses-6.0.tar.gz.dir/ncurses-6.0/test'
make: *** [all] Error 2
ncursesw failed to install: `make -j2` exited with 2

**Comment by jam7** [comment]
Install glibc223 by hand if you use Chrome OS 57.  It uses glibc-2.23 although chromebrew provides glibc-2.19.  For the case of x86_64, glibc-2.23 conflicts with glibc2.19.

**Comment by finwo** [comment]
Thanks, @jam7

That solved the issue for me.

**Comment by riceshrug** [comment]
@jam7 installing glibc223 fixed it, thank you.

**Comment by trusktr** [comment]
Can the vim.rb be updated to detect version of ChromeOS and add glib223 or something like that?
