### ISSUE TITLE
Temp directories not random

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5627]
All my temporary working directories for installs and builds end with `.AAAAAAAA.dir`.

**Comment by saltedcoffii** [comment]
There is a fix in #5598 to use the current UTC time instead of `/dev/urandom`. That issue will be resolved when #5598 is merged. But also, I'm not experiencing that issue, is something wrong with your computer?

**Comment by uberhacker** [comment]
Developers should never blame the computer because in 99.99% of the cases, the computer is as dumb as the programmer. :)  Maybe this update should be in a separate PR from #5598?  Remember...incremental changes.

**Comment by saltedcoffii** [comment]
@uberhacker check and see if you're still having the error after running `crew update`

**Comment by uberhacker** [comment]
Directories are getting a timestamp now (`20210417062043.dir`).
