### ISSUE TITLE
Packages removed on os update

### ISSUE THREAD

**Issue by finwo** [skycocker/chromebrew#563]
Whenever ChromeOS gets an update, it removes packages installed by chromebrew ( most noteable: ncursesw ). This means I have to rebuild all previously installed packages ( using the code below ). While this work-around works, it's not really desirable.

```sh
for i in $(crew search | grep '(i)' | grep -v ruby | awk '{print $2}') ; do yes | sudo crew remove $i ; yes | crew install $i ; done
```

Has anyone experienced this before? If yes, is there a more permanent solution than rebuilding all packages ( which is very time consuming )?

---

Sidenote: I also have to remove rootfs verification again to be able to add myself to the group `wheel` again & make `sudo` passwordless (yes, I know this is a security risk).

---

**Update [2017-04-05 13:15 CET]**

Due to #562 I can't re-install ncurses, which is quite an issue for using any program which makes use of that library.

**Comment by jam7** [comment]
I've never had this problem.  I guess your chromeos file system may has problem.  What does this show?
```
$ df / /usr/local
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        1763840 1565304    198536  89% /
/dev/mmcblk0p1  10732080 2401400   7762464  24% /usr/local
```

**Comment by finwo** [comment]
Here's the output:

```
$ df / /usr/local
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        1763840 1619968    143872  92% /
/dev/mmcblk0p1  25641188 5102212  19213408  21% /usr/local
```

**Comment by jam7** [comment]
Then, I'm not sure why /usr/local stuff is removed everytime.  I was thinking your /usr/local might point a part of / partition.

Just now, I've updated C202S chromeos from 56 to 57.  Crew works flawlessly.  :(

**Comment by finwo** [comment]
The contents weren't removed completely. `/usr/local/etc/crew` survived the upgrade, allowing me to restore the package list & re-install them.

**Comment by thedamian** [comment]
@finwo may I suggest a powerwash (reinstall everything) to figure out if this fixes this.

I've never ever had this issue, but a full reinstall (after you make sure to backup your DOWNLOADS directory has fixed many strange issues.
