### ISSUE TITLE
libpng issue

### ISSUE THREAD

**Issue by Muvuk** [skycocker/chromebrew#5630]
I tried to install sommelier but I cant without libpng, so then I tried to install libpng and I got the same error:

libpng failed to install: `update-mime-database /usr/local/share/mime` exited with 127

do you have any idea how to fix it?

thank you

Linux localhost 4.14.214-17104-g56f0bf5f36db #1 SMP PREEMPT Mon Mar 29 20:31:29 PDT 2021 x86_64 GNU/Linux

**Comment by uberhacker** [comment]
@Muvuk: Have you tried to run `crew update`?

**Comment by Muvuk** [comment]
@uberhacker thank you, but it does not help

`chronos@localhost / $ crew update
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13 (delta 10), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (13/13), 3.33 KiB | 148.00 KiB/s, done.
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
   e5d4c397..ef4f29bc  master     -> origin/master
HEAD is now at ef4f29bc Fix dash package (#5631)
Package lists, crew, and library updated.
Generating compatible packages...
############################################################################################################################################################################################################ 100.0%############################################################################################################################################################################################################ 100.0%
Checking for package updates...
Your software is up to date.
chronos@localhost / $ crew install libpng
libpng: libpng is the official PNG reference library.
http://libpng.org/pub/png/libpng.html
Version: 1.6.37-1
License: libpng2
Precompiled binary available, downloading...
############################################################################################################################################################################################################ 100.0%############################################################################################################################################################################################################ 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Performing post-install...
libpng failed to install: `update-mime-database /usr/local/share/mime` exited with 127`

**Comment by uberhacker** [comment]
Try this:
```
$ crew install shared_mime_info
```
@satmandu: Is this a case of a missing dependency?

**Comment by Muvuk** [comment]
It works! Thank you! :) I am happy with your chromebrew :)
