### ISSUE TITLE
sommelier issue

### ISSUE THREAD

**Issue by Muvuk** [skycocker/chromebrew#5634]
It worked in the past (I dont know versions), but now I got this when I try to run a java program:
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

Do you have any idea to fix it? thank you

**Comment by saltedcoffii** [comment]
Have you tried `startsommelier` and then running your command?

**Comment by Muvuk** [comment]
I forget that, because sommelier started automatically eariler. But now it helped. Thank you!

**Comment by satmandu** [comment]
Also, opening a new shell/terminal should automatically check to see if sommelier is running and if not start it for you.
