### ISSUE TITLE
Unable to install mlocate

### ISSUE THREAD

**Issue by finwo** [skycocker/chromebrew#564]
When trying to install the `mlocate` package on x86_64, the installation currently halts after downloading with the notification of a checksum mismatch.

Looks like a relatively small issue to me, but it does prevent (re-)installation of the package.

**Comment by jam7** [comment]
Same issue here.  New sha1sum is `7dc0114538997bc3afe0ab6c278f4fda0956b072` for me.

**Comment by flyingP0tat0** [comment]
The issue is, that fedorahosted is cancelled. Because of a notice instead of the actual `mlocate` code the archive is some website content pushed into a `.tar.xz`, leading to the error.
We will need to find a new source for the mlocate code.
