### ISSUE TITLE
git branch expects less at /usr/bin/less

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5644]
## Description
the `git branch` command reports an error and seems to expect less at `/usr/bin/less`. `less` isn't at `/usr/bin/less`

```shell
$ git branch
fatal: cannot run /usr/bin/less: No such file or directory
* main
```

## Reproducing
1. On a chromebook in developer mode, press `Ctrl + Alt + T`
2. Type `shell`
3. Ensure chromebrew and git are installed. It doesn't matter if less is installed, the error occurs both ways.
4. `cd` into any git repository (e.g. the one at `/usr/local/lib/crew`)
5. run `git branch`

Is this a bug in the way we compiled git, or is it an issue with upstream? If it's an upstream issue, I'd be happy to file a bug.

This doesn't seem to be an issue in X/Wayland virtual terminals, such as `gnome-terminal`, as git doesn't seem to try to invoke `less`.

**Comment by supechicken** [comment]
Try setting `PAGER=/usr/local/bin/less`?

**Comment by saltedcoffii** [comment]
That seems to fix the output but git then stops invoking the pager. Weird.
