### ISSUE TITLE
krb5-1.19-chromeos-x86_64

### ISSUE THREAD

**Issue by Alex313031** [skycocker/chromebrew#5645]
## Description
Provide a short description of your problem here.

New crew installations fail. Have tried on ChromeOS 89, ChromiumOS 91, and Cloudready 89.2. All with the same results. On machines with crew already installed, package installation works, but I have been reflashing machines. It also fails no matter if I make root read/write.

Output:
```
Verifying krb5...
krb5-1.19-chromeos-x86_64.tar.xz: OK
Extracting krb5 (this may take a while)...
Installing krb5 (this may take a while)...
tar: ./usr/local/var/krb5kdc: Cannot mkdir: Permission denied
tar: ./usr/local/var/krb5kdc: Cannot mkdir: Permission denied
tar: ./usr/local/var/krb5kdc/krb5kdc: Cannot mkdir: No such file or directory
tar: ./usr/local/var/krb5kdc: Cannot mkdir: Permission denied
tar: ./usr/local/var/krb5kdc/run: Cannot mkdir: No such file or directory
tar: ./usr/local/var/krb5kdc: Cannot mkdir: Permission denied
tar: ./usr/local/var/krb5kdc/run/krb5kdc: Cannot mkdir: No such file or directory
tar: Exiting with failure status due to previous errors
```

## Versions and system information
chromebrew: `crew --version`
ChromeBrew was unable to install, but I used commit "f215590". 

CHROMEOS_BOARD_APPID={09EF0583-EC2B-430D-B816-79DBDB6449BC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=CHROMEBOOK
CHROMEOS_RELEASE_BOARD=amd64-atb
CHROMEOS_DEVSERVER=http://chromeota.arnoldthebat.co.uk:8080
GOOGLE_RELEASE=13729.65.2021_03_24_2228
CHROMEOS_RELEASE_BUILD_NUMBER=13729
CHROMEOS_RELEASE_BRANCH_NUMBER=65
CHROMEOS_RELEASE_CHROME_MILESTONE=89
CHROMEOS_RELEASE_PATCH_NUMBER=2021_03_24_2228
CHROMEOS_RELEASE_TRACK=developer-build
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - tonyd
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13729.65.2021_03_24_2228
CHROMEOS_AUSERVER=http://chromeota.arnoldthebat.co.uk:8080/update
CHROMEOS_RELEASE_DESCRIPTION=13729.65.2021_03_24_2228 (Developer Build - tonyd) developer-build amd64-atb

Model: YOUR MODEL HERE. 
arnold the bat cros 89 on dell vosotro 460 (all intel hardware, cros/freon supported hardware, am able to run cros, chromeos (via brunch), cloudready, and crouton without issues.

**Comment by saltedcoffii** [comment]
It looks like there is a file at `/usr/local/var` that isn't ours. Could you (@Alex313031) run `pushd /usr/local && ls -la ; popd` please?

**Comment by satmandu** [comment]
This is also a non-google ChromeOS build, which we haven't tested on. Until we get more information on what is going on with the local additions to `/usr/local` in this build, we won't really be able to help further.

**Comment by jedi-ux** [comment]
I have the same problem, 
######################################################################## 100.0%
Verifying krb5...
krb5-1.19-chromeos-x86_64.tar.xz: OK
Extracting krb5 (this may take a while)...
Installing krb5 (this may take a while)...
tar: ./usr/local/var/krb5kdc/krb5kdc: Cannot mkdir: Permission denied
tar: ./usr/local/var/krb5kdc/run/krb5kdc: Cannot utime: Operation not permitted
tar: ./usr/local/var/krb5kdc/run: Cannot utime: Operation not permitted
tar: ./usr/local/var/krb5kdc: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors


I noticed this new installation, is this a ChromeBrew repo ?
 
chronos@localhost /usr/local/var/db/pkg $

![Screenshot 2021-05-05 07 57 50](https://user-images.githubusercontent.com/82736855/117101984-a243d500-ad77-11eb-84ec-c7ae201b1d92.png)

![Screenshot 2021-05-05 08 02 01](https://user-images.githubusercontent.com/82736855/117102232-32821a00-ad78-11eb-9c3e-132fc933bc41.png)

 ..

**Comment by jedi-ux** [comment]
![Screenshot 2021-05-05 08 03 50](https://user-images.githubusercontent.com/82736855/117102355-74ab5b80-ad78-11eb-8752-45d7410cb057.png)

**Comment by jedi-ux** [comment]
![Screenshot 2021-05-05 08 31 53](https://user-images.githubusercontent.com/82736855/117105083-9c50f280-ad7d-11eb-8fe1-9f2f95ff2b75.png)
![Screenshot 2021-05-05 08 14 39](https://user-images.githubusercontent.com/82736855/117105085-9ce98900-ad7d-11eb-8aae-98c2c62e682b.png)

**Comment by jedi-ux** [comment]
I never installed any repo, only the basic ChromeSO build from 
https://arnoldthebat.co.uk/wordpress/chromium-os/
Daily Build,

**Comment by supechicken** [comment]
@jedi-ux Could you post the output of the following:
```
ls -la /usr/local/var/krb5kdc/ /usr/local/var/ /usr/local/
```
`/usr/local/var` may a symlink to `/var` in third-party Chromium OS build

**Comment by uberhacker** [comment]
I don't think we can support a non-standard custom Chromium OS build; especially if it isn't on the stable branch.

**Comment by MilkyDeveloper** [comment]
I fixed it by doing:
```
setfacl -m u:username:rwx /usr/local/var
```
Rerun the install script. Then, you might get 'Error 127' about pip installing the `pygments` package. To fix this, run `crew install py3_pip`

**Comment by uberhacker** [comment]
You are definitely in YMMV territory @MilkyDeveloper.  Curious to know what is different about the Arnold the Bat builds versus the official builds from Google, however.

**Comment by MilkyDeveloper** [comment]
Here's the [source code](https://github.com/arnoldthebat/chromiumos) for the build I'm using. It only looks like the drivers are changed and some other stuff to fix Enterprise Enrollment and whatnot.

**Comment by jedi-ux** [comment]
@supechicken   
the output of  'ls -la /usr/local/var/krb5kdc/ //usr/local/'
$ ls: cannot access:s '/usr/local/var/krb5dc': No such file or directory
$ ls: cannot access '/usr/local/var/': no such file or directory
/usr/local:
total 8
drwxr-xr-x. 2 root root 4096 May 5 11:09 .
drwxr-xr-x. 11 root root 4096 Apr 29 05:47.

**Comment by jedi-ux** [comment]
@uberhacker  @MilkyDeveloper  ☈eel

**Comment by MilkyDeveloper** [comment]
Actually, what worked best for me was just running:
```bash
sudo rm -rf /usr/local/*
```
