### ISSUE TITLE
[sommelier] fails to start

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5646]
A recent update killed sommelier on all architectures.
```
some sommelier processes failed to start
sommelier processes running:  
 ```
`crew reinstall sommelier -s` does not fix.

**Comment by satmandu** [comment]
Does opening a new shell fix this?

**Comment by uberhacker** [comment]
No and all architectures are affected.

**Comment by satmandu** [comment]
Can you tell me what /usr/local/var/log/sommelier.log has?

**Comment by satmandu** [comment]
Also, reinstall xwayland... That might fix it.

**Comment by satmandu** [comment]
(This might be due to work separating xwayland and xorg to avoid file conflicts.)

**Comment by mackdroid** [comment]
> Can you tell me what /usr/local/var/log/sommelier.log has?

![image](https://user-images.githubusercontent.com/68280146/115149160-6ecb3000-a080-11eb-808f-fc91bb6b48ac.png)
this is what i have i tried starting sommelier several times
also im on canary channel....

**Comment by saltedcoffii** [comment]
glibc isn't installed it looks like. Try `crew reinstall glibc`

**Comment by mackdroid** [comment]
> glibc isn't installed it looks like. Try `crew reinstall glibc`
> 
> We also don't support the canary ChromeOS channel.
reinstalling didnt help, also im very aware canary isnt supported

**Comment by supechicken** [comment]
@mackdroid Could you try the following command?
```shell
ln -sf /lib64/ld-linux-x86-64.so.2 /usr/local/lib64
```

**Comment by mackdroid** [comment]
> @mackdroid Could you try the following command?
> 
> ```shell
> ln -sf /lib64/ld-linux-x86-64.so.2 /usr/local/lib64
> ```

Aye works, thanks for the support even though im on the canary channel! much appreciated

**Comment by mackdroid** [comment]
is this the same issue other architecture's on stable facing?

**Comment by satmandu** [comment]
That symlink should be created by the Chromebrew installer, but there may be other issues from our work in eliminating file conflicts which might be resolved by `crew reinstall xwayland`.
