### ISSUE TITLE
[aria2] broken, needs libssh2.so

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5648]
## Description
After a fresh install of chromebrew, installed aria2.
Ran:
```
$ aria2c
aria2c: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory
```

Potential solutions:
1. Compile aria2 without libssh2
2. Put libssh2 in aria2's dependencies.

**Comment by satmandu** [comment]
#2 is the easiest solution...

**Comment by saltedcoffii** [comment]
Whatever works for you guys :)

**Comment by satmandu** [comment]
Put in a PR to fix it! :)
