### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5678]
```
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Precompiled binary available, downloading...
Performing pre-install...
Performing install...
/usr/local/lib/ruby/3.0.0/fileutils.rb:551:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/glibc.directorylist) (Errno::ENOENT)
        from /usr/local/lib/ruby/3.0.0/fileutils.rb:551:in `block in mv'
        from /usr/local/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/local/lib/ruby/3.0.0/fileutils.rb:542:in `mv'
        from /usr/local/bin/crew:814:in `block in install_package'
        from /usr/local/bin/crew:810:in `chdir'
        from /usr/local/bin/crew:810:in `install_package'
        from /usr/local/bin/crew:972:in `install'
        from /usr/local/bin/crew:930:in `block in resolve_dependencies'
        from /usr/local/bin/crew:927:in `each'
        from /usr/local/bin/crew:927:in `resolve_dependencies'
        from /usr/local/bin/crew:836:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1156:in `block in install_command'
        from /usr/local/bin/crew:1150:in `each'
        from /usr/local/bin/crew:1150:in `install_command'
        from /usr/local/bin/crew:1242:in `<main>'
```

**Comment by MaIIow** [comment]
good morning a new problem, same as the previous one.

chronos@localhost / $ curl -Ls git.io/vddgY | bash
Install development tools? (not needed for most users) [y/N]: Password: 
Downloading gcc10...
######################################################################## 100.0%
Verifying gcc10...
sha256sum: WARNING: 1 computed checksum did NOT match
gcc10-10.2.1-0f64-chromeos-x86_64.tar.xz: FAILED
Extracting gcc10 (this may take a while)...
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chronos@localhost / $ date
Thu Apr 22 08:43:00 CEST 2021
chronos@localhost / $

**Comment by uberhacker** [comment]
@Mallow: Thank you for the feedback.  I just installed recently without any issue.  Maybe try again?

**Comment by uberhacker** [comment]
I did notice you have a `Password:` prompt.  That looks out of the ordinary.

**Comment by MaIIow** [comment]
chronos@localhost ~ $ curl -Ls git.io/vddgY | bash
Install development tools? (not needed for most users) [y/N]: N
Downloading gcc10...
######################################################################## 100.0%
Verifying gcc10...
sha256sum: WARNING: 1 computed checksum did NOT match
gcc10-10.2.1-0f64-chromeos-x86_64.tar.xz: FAILED
Extracting gcc10 (this may take a while)...
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by MaIIow** [comment]
I wanted to specify that I'm currently running chromeos with brunch framework 

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7179805
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R89-13729.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=13729
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=89
CHROMEOS_RELEASE_DESCRIPTION=13729.56.0 (Official Build) stable channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13729.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13729.56.0

**Comment by MaIIow** [comment]
you tell me is closed but i have same issue now!

**Comment by uberhacker** [comment]
@MaIIow: The issue above has been resolved.  Can you please provide some output of your exact error?

**Comment by uberhacker** [comment]
Please open a new issue if the above error is different.

**Comment by MaIIow** [comment]
solved, error was same of my issue but i think was caused by crew folder in /usr/local/crew.
I delete it and and other dir creare on fails install and script work now
