### ISSUE TITLE
jdk8 dropbox link not found

### ISSUE THREAD

**Issue by bpstrngr** [skycocker/chromebrew#568]
Hi I updated crew but still get 404 not found error for 
https://dl.dropboxusercontent.com/u/14799278/crew/jdk8u112-x86_64.tar.gz 
when I crew install jdk8. 
Could You resolve the link please? 
actually I may be able to compile it from source though, 
since I have the proper buildessentials, but I've been doing 
enough trouble with that before the times of chromebrew.. 
Thanks!

**Comment by bfayers** [comment]
Hey, i believe this is me due to dropbox discontinuing public folders #268 I'll take a look at the jdk8 stuff.

**Comment by bfayers** [comment]
Yep, this is me i'll update the urls and PR. i'll make a note and small guide in #268 too

**Comment by bfayers** [comment]
Fixed in #569

**Comment by bpstrngr** [comment]
awesome, thank You for the quick aid!
