### ISSUE TITLE
ChromeOS release 90 upgrade breaks ruby

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5681]
```
$ crew
env: 'ruby': Too many levels of symbolic links
```

**Comment by uberhacker** [comment]
A fresh install produces a similar error.  See below:
```
Install development tools? (not needed for most users) [y/N]: 
Creating new device.json...
Downloading gcc10...
############################################################################################################################################## 100.0%############################################################################################################################################## 100.0%
Verifying gcc10...
gcc10-10.2.1-0f64-chromeos-x86_64.tar.xz: OK
Extracting gcc10 (this may take a while)...
tar (child): xz: Cannot exec: Too many levels of symbolic links
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by satmandu** [comment]
hmmm... what does `ls -aFl /usr/local/bin/ruby` show?

**Comment by uberhacker** [comment]
I cannot do that now that I attempted, unsuccessfully, to reinstall fresh.

**Comment by satmandu** [comment]
in my M90 container:
```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ /usr/bin/env ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux-gnu]
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ env ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux-gnu]
```

**Comment by uberhacker** [comment]
Docker containers don't count. :)  How does an actual Chromebook behave?

**Comment by saltedcoffii** [comment]
I have an actual chromebook and i'm using chromeos 90 and it works just fine

**Comment by uberhacker** [comment]
Did you add any crazy configs like allowing executables to run in your home directory?  What happens if you powerwash and try again?  Are you brave enough to try?

**Comment by uberhacker** [comment]
Interesting observations.
```
tar xpf <tarball>.tar.xz outputs Too many levels of symbolic links
```
However,
```
xz -d <tarball>.tar.xz
tar xpf <tarball>.tar
```
This works without an error.

```
crew outputs env: 'ruby': Too many levels of symbolic links
```
However,
```
ruby -h
```
This runs fine.

**Comment by saltedcoffii** [comment]
> Did you add any crazy configs like allowing executables to run in your home directory?  What happens if you powerwash and try again?  Are you brave enough to try?

No, I just updated and reinstalled chromebrew.

**Comment by supechicken** [comment]
There may have more than one file call `ruby` in your `PATH`, changing the shebang to `#!/usr/local/bin/ruby` should fix it

**Comment by supechicken** [comment]
> $ crew
> env: 'ruby': Too many levels of symbolic links

Does `env ruby -h` works?

**Comment by primos63** [comment]
I experienced the same issue after upgrading to 90. 
@supechicken `env ruby -h` does not work.

Executing `/usr/bin/env <anything>` causes the too many levels of symbolic links to be displayed.

**Comment by uberhacker** [comment]
Thank you for the confirmation.  That has been my experience as well.

**Comment by satmandu** [comment]
@primos63 @uberhacker what hardware are you on? Maybe this is a hardware specific regression.

**Comment by uberhacker** [comment]
I think the issue is independent of hardware but I have a kip board (HP Chromebook 11 G3).

**Comment by primos63** [comment]
Agree with @uberhacker. I have an Asus C302.

**Comment by saltedcoffii** [comment]
> Thank you for the confirmation.  That has been my experience as well.

Maybe we can install busybox or coreutils before installing Ruby to make shebangs work

**Comment by uberhacker** [comment]
Another executable with this problem is xargs.
```
$ ls | xargs
xargs: echo: Too many levels of symbolic links
```

**Comment by satmandu** [comment]
Do those apps work any differently if you prepend the non-`CREW_LIB_PREFIX` LIBRARY Path to them? e.g. `LD_LIBRARY_PATH=/usr/lib64  /usr/bin/env --version`

**Comment by uberhacker** [comment]
```
$ LD_LIBRARY_PATH=/usr/lib64 /usr/bin/env --version
env (GNU coreutils) 8.32
Packaged by Gentoo (8.32-r1 (p0))
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard Mlynarik, David MacKenzie, and Assaf Gordon.
```

**Comment by uberhacker** [comment]
The `xargs` from findutils has the same issue as described above.

**Comment by primos63** [comment]
On my system I'm using Nodebrew and in the PATH I see `/home/chronos/user/.nodebrew/current/bin` listed twice. Removing the first instance from the PATH allows crew to run. 
**SUCCESS:** `PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:/home/chronos/user/.nodebrew/current/bin env crew update`

If the nodebrew bin path is listed first the 'Too many levels of symbolic links' is displayed.
**FAIL:** `PATH=/home/chronos/user/.nodebrew/current/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin env crew update`

**Comment by uberhacker** [comment]
@primos63:  Nice find!  That was the exact issue I had also.  I actually fixed it by moving that path to the end.  As long as there are no other node binaries in the previous paths, it should still find node, npm, etc.  I'm going to close this and create a Q&A in the [FAQ](https://github.com/skycocker/chromebrew/wiki/FAQ).

**Comment by Sasytoremember** [comment]
> Did you add any crazy configs like allowing executables to run in your home directory? What happens if you powerwash and try again? Are you brave enough to try?

Wait a minute, how do you allow executables to run in the home directory anyways?

**Comment by saltedcoffii** [comment]
> Wait a minute, how do you allow executables to run in the home directory anyways?

@Sasytoremember use the command `sudo mount -o remount,exec ~` to run executables in the home directory. it has to be run every boot. this isn't a chromebrew supported configuration but it shouldn't cause any problems.

**Comment by Sasytoremember** [comment]
> > Wait a minute, how do you allow executables to run in the home directory anyways?
> 
> @Sasytoremember use the command `sudo mount -o remount,exec ~` to run executables in the home directory. it has to be run every boot. this isn't a chromebrew supported configuration but it shouldn't cause any problems.

Thanks! I'll put that in my .bashrc
