### ISSUE TITLE
error preventing me from installing chromebrew

### ISSUE THREAD

**Issue by treypop** [skycocker/chromebrew#5688]
when I try to install chromebrew I get this error. `curl: error while loading shared libraries: libssl.so.48: cannot open shared object file: No such file or directory` 
I'm using it on an x86 machine

**Comment by uberhacker** [comment]
@treypop: Please provide more info.  What is the output of `cat /etc/lsb-release`?  What is your Chromebook make and model?

**Comment by saltedcoffii** [comment]
I suspect this may also be a problem with your environment, please provide the output of `printenv LD_LIBRARY_PATH`

**Comment by treypop** [comment]
> cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7179805
CHROMEOS_AUSERVER=https://block-tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=56
CHROMEOS_RELEASE_BUILDER_PATH=samus-release/R89-13729.56.0
CHROMEOS_RELEASE_BUILD_NUMBER=13729
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=89
CHROMEOS_RELEASE_DESCRIPTION=13729.56.0 (Official Build) stable-channel samus 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13729.56.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13729.56.0

I am running Brunch r89 using samus as my chrome os version

**Comment by treypop** [comment]
> printenv LD_LIBRARY_PATH

/usr/local/lib64

**Comment by satmandu** [comment]
can you try `CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl" ./install.sh`

You could also try a static curl for installation.

Download a static curl  such as from here: https://github.com/moparisthebest/static-curl/releases
Make sure it is executable. `chmod +x curl-amd64`
Do an `export CURL=/path_to_static_curl/curl-amd64` before running the install.

**Comment by treypop** [comment]
> CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl" ./install.sh

bash: ./install.sh: No such file or directory

Am I doing something wrong here?

**Comment by supechicken** [comment]
> > CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl" ./install.sh
> 
> `bash: ./install.sh: No such file or directory`
> 
> Am I doing something wrong here?

Can you try the following:
```shell
export CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl"

curl -Ls git.io/vddgY | bash
```

**Comment by satmandu** [comment]
That's not going to work. You need this:
export CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl" ; $CURL -Ls git.io/vddgY | bash

**Comment by treypop** [comment]
> `export CURL="LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64 /usr/bin/curl" ; $CURL -Ls git.io/vddgY | bash`

`bash: LD_LIBRARY_PATH=/usr/lib64:/lib64:/usr/local/lib64: No such file or directory`

**Comment by satmandu** [comment]
Try this:
```
export CURL="LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl"
$CURL -Ls git.io/vddgY | bash
```

**Comment by supechicken** [comment]
Seems that the `$()` wrapper in `install.sh` doesn't accept variables, try to use `env`
```shell
export CURL="env LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl"
```

**Comment by treypop** [comment]
using `env` worked I have a working chromebrew installation. thanks a lot 😀

**Comment by treypop** [comment]
^^^
