### ISSUE TITLE
man returns an error when fetching/displaying valid manual pages 

### ISSUE THREAD

**Issue by heavygabriel** [skycocker/chromebrew#5693]
## Description
Provide a short description of your problem here.
man returns an error when fetching/displaying valid manual pages
```shell
$ man man
```
Output:
```shell
man: can't execute nroff: No such file or directory
man: can't execute tbl: No such file or directory
man: command exited with status 255: (cd /usr/local/share/man && /usr/local/libexec/man-db/zsoelim) | (cd /usr/local/share/man && /usr/local/libexec/man-db/manconv -f UTF-8:ISO-8859-1 -t ANSI_X3.4-1968//IGNORE) | (cd /usr/local/share/man && tbl) | (cd /usr/local/share/man && nroff -mandoc -rLL=116n -rLT=116n -Tascii)
```
## Versions and system information
chromebrew: `crew --version`
1.8.10

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=55
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.55.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.55.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.55.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.55.0
Model: Lenovo C330 
Architecture: `uname -m`
aarch64
## Additional information
man returns an error like that for any valid man page, like `man bash`, `man printf`, etc.

**Comment by uberhacker** [comment]
I can confirm this bug.
