### ISSUE TITLE
ruby dowload fail - 401 not authorized

### ISSUE THREAD

**Issue by ghost** [skycocker/chromebrew#57]
--2015-01-08 10:08:45--  https://dl.dropboxusercontent.com/s/bwb315aluunam6b/ruby-2.0.0-p247-chromeos1-chromeos-x86_86.tar.gz?token_hash=AAGYQhHhEpgAHCKtVVonVlXIJKZOWzq3arNsirxcRJQgLA&dl=1
Resolving dl.dropboxusercontent.com... 23.21.210.59, 23.21.216.250, 23.21.244.13, ...
Connecting to dl.dropboxusercontent.com|23.21.210.59|:443... connected.
WARNING: cannot verify dl.dropboxusercontent.com's certificate, issued by '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 401 Not Authorized
Authorization failed.
Checksum mismatch :/ try again

**Comment by faddah** [comment]
@skycocker ,

i'm seeing this also with both the ruby and vim packages. +1. happens whether or not i prefix the command with ```sudo```. anything to be done about this? wait for an update for these packages? please advise.

best,

--  faddah
    portland, oregon

**Comment by skycocker** [comment]
@faddah @hiswitness I'll be looking at it in the evening or tomorrow.

**Comment by faddah** [comment]
@skycocker, 

thanks! do keep us updated.

--  faddah
    portland, oregon, u.s.

**Comment by hiswitness** [comment]
@skycocker 

Thanks very much for the quick response, really appreciated. Crew is a great idea, just what I needed!!

Adam

**Comment by skycocker** [comment]
@hiswitness `crew update` and let me know if Ruby works now. 
@faddah with vim? could you `crew update` and then post me the output of `crew install vim`? For me vim is working fine.

**Comment by hiswitness** [comment]
@skycocker I did <code>crew update</code> and ran into a different error

<code>
chronos@localhost / $ crew install ruby
Found ruby, version 2.0.0p247-chromeos1
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]
y
Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-01-10 22:14:41--  https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1
Resolving www.dropbox.com... 108.160.166.20
Connecting to www.dropbox.com|108.160.166.20|:443... connected.
WARNING: cannot verify www.dropbox.com's certificate, issued by '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/t65U5wkqaNlRd3YhLhEZsULObodQuRGVnoVaIsFcJcr0jlyGdl9aQuyLZ6icpfm3?dl=1 [following]
--2015-01-10 22:14:42--  https://dl.dropboxusercontent.com/content_link/t65U5wkqaNlRd3YhLhEZsULObodQuRGVnoVaIsFcJcr0jlyGdl9aQuyLZ6icpfm3?dl=1
Resolving dl.dropboxusercontent.com... 50.16.247.8, 50.19.92.75, 54.197.255.201, ...
Connecting to dl.dropboxusercontent.com|50.16.247.8|:443... connected.
WARNING: cannot verify dl.dropboxusercontent.com's certificate, issued by '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

Checksum mismatch :/ try again
</code>

**Comment by frontalot** [comment]
I'm encountering the same error.

**Comment by faddah** [comment]
hi @skycocker ,

ok, here's the output when i do ```crew update``` and then ```crew install ruby``` --


```bash

 $ crew update
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 1 (delta 0)
Unpacking objects: 100% (4/4), done.
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
   6d8daec..9d39bd9  master     -> origin/master
HEAD is now at 9d39bd9 Fix ruby x86_64 binary link
Package lists, crew, and library updated.
Checking for package updates...

Your software is up to date.
chronos@localhost / $ crew install ruby
Found ruby, version 2.0.0p247-chromeos1
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-01-13 14:37:18--  https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1
Resolving www.dropbox.com... 108.160.166.20
Connecting to www.dropbox.com|108.160.166.20|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/UCtj7onHs5A67Es1Ul94bRbGnSSKuiAj0exvrDePT0mXXzuZBBvK1zaRy0lG2Ipv?dl=1 [following]
--2015-01-13 14:37:19--  https://dl.dropboxusercontent.com/content_link/UCtj7onHs5A67Es1Ul94bRbGnSSKuiAj0exvrDePT0mXXzuZBBvK1zaRy0lG2Ipv?dl=1
Resolving dl.dropboxusercontent.com... 54.243.113.159, 54.235.163.202, 54.83.45.92, ...
Connecting to dl.dropboxusercontent.com|54.243.113.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28295655 (27M) [application/octet-stream]
Saving to: 'ruby-2.0.0p247-chromeos-x86_64.tar.gz'

100%[=========================================================================================================================>] 28,295,655  6.64MB/s   in 5.6s   

2015-01-13 14:37:26 (4.78 MB/s) - 'ruby-2.0.0p247-chromeos-x86_64.tar.gz' saved [28295655/28295655]

Checksum mismatch :/ try again

```

this happens each and every time i try and install with ```crew``` for the ruby package. now here is the results for vim --

```bash

$ crew update
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
HEAD is now at 9d39bd9 Fix ruby x86_64 binary link
Package lists, crew, and library updated.
Checking for package updates...

Your software is up to date.
chronos@localhost / $ crew install vim
Found vim, version 7.4
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg libsigsegv diffutils bz2 ncurses libsigsegv diffutils ncurses perl python27 ruby 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found bz2, version 1.4.17
Package bz2 already installed, skipping...
Found ncurses, version 5.9
Package ncurses already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found ncurses, version 5.9
Package ncurses already installed, skipping...
Found perl, version 5.16.3
Package perl already installed, skipping...
Found python27, version 2.7.8
Package python27 already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-01-13 14:41:55--  https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1
Resolving www.dropbox.com... 108.160.165.20
Connecting to www.dropbox.com|108.160.165.20|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/pdZmqQIk6bHLEeA9gE0Ct5etvEAwcOZye6j7N2HHrZbDqtJNfMQAcw08X4QYcK7k?dl=1 [following]
--2015-01-13 14:41:55--  https://dl.dropboxusercontent.com/content_link/pdZmqQIk6bHLEeA9gE0Ct5etvEAwcOZye6j7N2HHrZbDqtJNfMQAcw08X4QYcK7k?dl=1
Resolving dl.dropboxusercontent.com... 107.21.209.202, 54.235.105.167, 54.243.102.38, ...
Connecting to dl.dropboxusercontent.com|107.21.209.202|:443... connected.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

Checksum mismatch :/ try again

```

... so there you go. checksum mismatches, each time, both packages. the funny thing is, i can get to them in my shell, but if i do ```crew search``` on the list of packages, they don't show as finally installed, no ```(i)``` next to the ruby or vim package names. any help here, please? please let me know.

best,

--  faddah wolf
    portland, oregon, u.s.a.

**Comment by faddah** [comment]
hi @skycocker ,

is there any update on these issues yet? please advise when you can. thank you.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
hi @skycocker,

still waiting to hear on this. have tried ```crew update```, then trying to remove ruby if it thinks it is installed with ```sudo crew remove ruby```, but get — 

```bash

$ sudo crew remove ruby
Found ruby, version 2.0.0p247-chromeos1
Package ruby isn't installed.

```

and if i try to install it, still, with ```crew install ruby``` after the update, i still get — 

```bash

...

    The file is already fully retrieved; nothing to do.

Checksum mismatch :/ try again

```

any help in fixing this would be appreciated. thank you.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by skycocker** [comment]
@faddah could you try completely reinstalling chromebrew? I guess it's fixed in latest version.

**Comment by hiswitness** [comment]
@skycocker great! but (forgive my ignorance) how would I uninstall chromebrew?? (I only know how to uninstall packages using apt-get in ubuntu :confused: ?

**Comment by skycocker** [comment]
@hiswitness you have to run `crew search`, this will show you all the available packages, with `(i) ` at the beginning of the ones you have installed. Then for every package that has such `(i)` run `crew remove packagename` (with `packagename` substituted with the package name, ex. `crew remove ruby`). 

After you remove every package installed with crew, run: 
`sudo rm -rf /usr/local/lib/crew` 
`sudo rm -rf /usr/local/etc/crew` 
`sudo rm -rf /usr/local/tmp/crew` 
`sudo rm /usr/local/bin/crew` 

After that just run the crew install script: 
`wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash` 

And you should have chromebrew installed properly. Let me know if it worked.

**Comment by lyxell** [comment]
Closing in favor of #181
