### ISSUE TITLE
Modify permissions of "${TMPDIR}" in /usr/local/etc/env.d/05-chromebrew only when needed

### ISSUE THREAD

**Issue by esprout** [skycocker/chromebrew#5700]
chromebrew runs sudo at every shell invocation to change permission of "${TMPDIR}" to 1777.  This causes unnecessary prompt for sudo password when permission is already correct.

Modify /usr/local/etc/env.d/05-chromebrew as follows to prevent this:

\# Give TMPDIR standard permissions
if [ $(stat -c %a "${TMPDIR}") -ne 1777 ]; then
  sudo chmod 1777 "${TMPDIR}"
fi

chromebrew: 1.8.11
Architecture: x86_64

**Comment by satmandu** [comment]
You want to submit a PR to change https://github.com/chromebrew/crew-profile-base/blob/master/src/env.d/05-chromebrew @saltedcoffii
