### ISSUE TITLE
Stow is broken

### ISSUE THREAD

**Issue by linusboyle** [skycocker/chromebrew#5723]
## Description

When I execute `stow` it gives the following error:

```shell
Can't locate Stow.pm in @INC (you may need to install the Stow module) (@INC contains: /usr/local/lib/perl5/site_perl/5.32.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.32.1 /usr/local/lib/perl5/5.32.1/x86_64-linux-thread-multi /usr/local/lib/perl5/5.32.1 /usr/local/lib/perl5/site_perl) at /usr/local/bin/stow line 418.
BEGIN failed--compilation aborted at /usr/local/bin/stow line 418.
```

## Versions and system information
chromebrew: 1.8.15

ChromeOS: 

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0

Model: Pixelbook

Architecture: x86_64

**Comment by satmandu** [comment]
After that PR is merged, try `crew upgrade stow` .
