### ISSUE TITLE
Ninja fails when called

### ISSUE THREAD

**Issue by heavygabriel** [skycocker/chromebrew#5736]
## Description
Provide a short description of your problem here.
Ninja fails 
If you executed a specific command:
```shell
$ ninja
```

Output:
```shell
ninja: /usr/local/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ninja)

```

## Versions and system information
chromebrew: `crew --version`
1.9.5
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0
Model: Lenovo C330

Architecture: `uname -m`
aarch64

**Comment by uberhacker** [comment]
@heavygabriel:  Thank you for the feedback.  See if this works: `crew reinstall re2c ninja -s`.  If it does, then we'll need new binaries.  cc: @satmandu

**Comment by heavygabriel** [comment]
@uberhacker: I can confirm that `crew reinstall re2c ninja -s` has fixed my woes.

**Comment by satmandu** [comment]
I wonder if this is a GCC libs issue. The easier way to fix this would be to roll out gcc11, which includes that library...

**Comment by saltedcoffii** [comment]
We could just switch over to samurai entirely and depreciate ninja

**Comment by satmandu** [comment]
I would hesitate on switching over packages until we confirm they work with samurai, since upstream may not be testing with samurai. I'll grant that it is likely much less problematic than switching openssl to libressl, 

In any case, we need to fix ninja, and the updated gcc libs in https://github.com/skycocker/chromebrew/pull/5665 should hopefully resolve this.

**Comment by heavygabriel** [comment]
I can confirm that #5665 and #5767 has fixed ninja.
