### ISSUE TITLE
gdb fails when called

### ISSUE THREAD

**Issue by heavygabriel** [skycocker/chromebrew#5737]
## Description
Executing the command `gdb` gives an error about an undefined symbol.

If you executed a specific command:
```shell
$ gdb
```

Output:
```shell
gdb: symbol lookup error: gdb: undefined symbol: PyUnicodeUCS2_FromEncodedObject
```

## Versions and system information
chromebrew: `crew --version`
1.9.5

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0
Model: Lenovo C330

Architecture: `uname -m`
aarch64

**Comment by heavygabriel** [comment]
So, I did a little research and from this [thread](https://stackoverflow.com/questions/2584198/undefined-symbol-pyunicodeucs2-decode-whilst-trying-to-install-psycopg2), it looks like gcc needs python3 to be built with `--enable-unicode=ucs4`.

**Comment by satmandu** [comment]
There's the opposite suggestion further down the thread though... https://stackoverflow.com/a/62811981

**Comment by satmandu** [comment]
@heavygabriel You should be able to do  a `crew update && crew upgrade gdb` to get `gdb` working.
