### ISSUE TITLE
[gcc11] Version check too late in the process

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5764]
After waiting 2+ min for gcc11 to download and install, I was given a message that gcc10 is already installed.  See below:
```
gcc11: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
Precompiled binary available, downloading...
############################################################################################################################################## 100.0%
Archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Performing pre-install...
GCC version bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
10.2.1 already installed.
```
Suggestion: Add the version check to preflight instead.

**Comment by satmandu** [comment]
That would mean that we can't build newer gcc with older gcc right, because of this?
```
def build_command(args)
  args["<name>"].each do |name|
    @pkgName = name
    search @pkgName
    print_current_package @opt_verbose
    @pkg.preflight
    resolve_dependencies_and_build
  end
end
```

**Comment by satmandu** [comment]
Could we do preinstall with an `unless @pkg.in_build = true` ?

**Comment by satmandu** [comment]
That doesn't work. I'm working on adding a `self.installcheck` section just for this.

**Comment by heavygabriel** [comment]
This issue leaves me unable to build packages since GCC 11 is required to build.

**Comment by satmandu** [comment]
@heavygabriel This should take care of you until I get this fixed up later today:

```
cd  /usr/local/lib/crew/packages
curl -OLf https://github.com/satmandu/chromebrew/raw/8973177d0456c2ab2d67b61f15ab251b4df35b71/packages/gcc11.rb
crew remove gcc10
crew reinstall gcc11
```

**Comment by uberhacker** [comment]
I suppose you could ignore the preflight check for builds and enable for installs/upgrades?

**Comment by satmandu** [comment]
The entire point of preflight is to do checking before builds! :)

But I have a fix here: https://github.com/skycocker/chromebrew/pull/5767

@heavygabriel That should be the final fix for this once merged...

**Comment by uberhacker** [comment]
Builds can happen anytime.  It's installs that need preflight checks.

**Comment by satmandu** [comment]
You may want checks for both. There are use cases for wanting a pre-install check which doesn't keep building from happening (e.g. building a different version of a compiler). Pre-flight is currently setup to block both.

**Comment by uberhacker** [comment]
That's what I've been saying.  You don't need to block for builds...ever.  But you do need to block for installs.  We just need to update crew to ignore preflight checks for `crew build`.

**Comment by satmandu** [comment]
I'm coming around to that view... let me see what I can do about moving preflight around... I think that might be the simpler way to go.

**Comment by satmandu** [comment]
Addressed by https://github.com/skycocker/chromebrew/pull/5767
