### ISSUE TITLE
Minecraft for arm?

### ISSUE THREAD

**Issue by heavygabriel** [skycocker/chromebrew#5766]
## Description
So, it looks like the minecraft package has not been ported for ARM.
Fortunately, I know a few ways on how to make it run and maybe make these steps into a package or something?

What I think needs to be done:
-  step one: modify [this script](https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh) for crew 
-  step two: when calling minecraft, set the `_JAVA_OPTIONS='-Dorg.lwjgl.librarypath=LWJGL3DIR:LWJGL2DIR' environment variable to tell minecraft where LWJGL libraries are.

Most of the information has been taken from  [this forum post](https://www.raspberrypi.org/forums/viewtopic.php?t=284448) and [this article](https://www.96boards.org/blog/minecraft-dragonboard/)

Thank you for reading.

**Comment by satmandu** [comment]
If you want to mess around and try to contribute a package... Minecraft isn't free software, so we couldn't store binary packages, but you could create a package file would work like an install script.
