### ISSUE TITLE
openSSL install fails on aarch64

### ISSUE THREAD

**Issue by ksunden** [skycocker/chromebrew#577]
Workaround: add no-asm to the ./config options

**Comment by brucem1976** [comment]
Thanks that worked - but now I get:

No precompiled binary available for your platform, downloading source...
--2017-05-02 06:42:02--  https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
Resolving www.python.org... 151.101.172.223
Connecting to www.python.org|151.101.172.223|:443... connected.
*** Error in `wget': free(): invalid pointer: 0xb9112888 ***
Checksum mismatch :/ try again

**Comment by lyxell** [comment]
This was probably solved by #591

**Comment by brucem1976** [comment]
So this got it compiling and installing - however it messes up the crypto setup on the system - github stops authenticating, ssh-keygen won't run without sudo, and ssh-add doesn't work....

**Comment by jam7** [comment]
How about performing test?

```
$ sudo crew remove openssl
$ crew install openssl keep
$ cd /usr/local/tmp/crew/openssl...    # cd to working directory crew left as is
$ make test
```

**Comment by ksunden** [comment]
Why is openssl a required dependency for python2.7?
I am able to install python2.7 without the openssl dependency. (Python 2.7 was what prompted me to open this issue in the first place, as in #614 )

All problems go away without openssl installed.

**Comment by brucem1976** [comment]
How do you install without openssl?

**Comment by lyxell** [comment]
@ksunden OpenSSL gives Python features which is considered to be a part of the standard installation

**Comment by jam7** [comment]
Please refer https://github.com/skycocker/chromebrew/issues/614#issuecomment-305946120 if you can try new toolchains for aarch64

**Comment by jam7** [comment]
Close in favor of #1025.
