### ISSUE TITLE
Package gdk_pixbuf has circular dependencies

### ISSUE THREAD

**Issue by heavygabriel** [skycocker/chromebrew#5773]
## Description
The package `gdk_pixbuf` has circular dependencies because it requires the package `gtk3` and `gtk4`.
`gtk3` and `gtk4` requires gdk_pixbuf to be installed, making it impossible to install `gdk_pixbuf` with `gtk3` and `gtk4` as dependencies.
If you executed a specific command:
```shell
$ crew install gdk_pixbuf
```

Output:
```shell
gdk_pixbuf: GdkPixbuf is a library for image loading and manipulation.
https://developer.gnome.org/gdk-pixbuf
Version: 2.42.4-1
License: LGPL-2.1+
Performing pre-flight checks...
The following packages also need to be installed: 
gtk4 gtk3 
Do you agree? [Y/n] y
Proceeding...
gtk4: GTK+ is a multi-platform toolkit for creating graphical user interfaces.
Precompiled binary available, downloading...
############################################################################################################################################## 100.0%
Archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Stripping libraries...
Stripping binaries...
Performing post-install...
Warning: Schema ?org.gnome.system.locale? has path ?/system/locale/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy? has path ?/system/proxy/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.http? has path ?/system/proxy/http/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.https? has path ?/system/proxy/https/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.ftp? has path ?/system/proxy/ftp/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.socks? has path ?/system/proxy/socks/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
/usr/local/bin/gtk4-update-icon-cache: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
gtk4 failed to install: `/usr/local/bin/gtk4-update-icon-cache -ft /usr/local/share/icons/*` exited with 127
```

## Versions and system information
chromebrew:
1.9.8

ChromeOS: 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0
Model: Lenovo C330

Architecture: `uname -m`
armhf
## Additional information
Strangely enough, `crew install gtk3` or `crew install gtk4` actually installs gdk_pixbuf correctly.

What I think needs to be done:
- [ ] Change the dependencies of `gdk_pixbuf`

**Comment by satmandu** [comment]
Replacing the postinstall sections of `gtk3` and `gtk4` with this should address this issue:

```
  def self.postinstall
    # generate schemas
    system "#{CREW_PREFIX}/bin/glib-compile-schemas #{CREW_PREFIX}/share/glib-2.0/schemas"
    # update mime database
    system "#{CREW_PREFIX}/bin/update-mime-database #{CREW_PREFIX}/share/mime"
    # update icon cache, but only if gdk_pixbuf is already installed.
    @device = JSON.parse(File.read(CREW_CONFIG_PATH + 'device.json'), symbolize_names: true)
    return unless @device[:installed_packages].any? 'gdk_pixbuf'
    system "#{CREW_PREFIX}/bin/gtk-update-icon-cache -ft #{CREW_PREFIX}/share/icons/*"
  end
```
