### ISSUE TITLE
Apache Httpd

### ISSUE THREAD

**Issue by gitbucket-crypto** [skycocker/chromebrew#5783]
Guys I have installed chromebrew  and i made crew search apache, return with lot options but how to install that option Apache HTTP :

httpd: The Apache HTTP Server Project is an effort to develop and maintain an open-source HTTP server for modern operating systems including UNIX and Windows.
maven: Apache Maven is a software project management and comprehension tool.
netbeans: Apache NetBeans IDE is free open source software to quickly and easily develop desktop, mobile, and web applications with Java, JavaScript, HTML5, PHP, C/C++ and more.
serf: The serf library is a high performance C-based HTTP client library built upon the Apache Portable Runtime (APR) library.

Thanks

**Comment by uberhacker** [comment]
Did you try `crew install httpd` yet?
