### ISSUE TITLE
npm global package installation

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#579]
I know that this issue is only partially connected to this project, but maybe someone has some solution.
I installed node and everything is Wirkung. If I install a npm package globally with sudo, npm tells me that /root/.npm couldn't be created due to the read-only filesystem.
I already tried to get a writeable filesystem, but I am still stucked with this error.
Maybe someone already faced this issue and has some solution? Looking forward to hear from you...

**Comment by ntchambers** [comment]
Does this work for you?

```curl -sLo /usr/local/lib/crew/packages/nodetest.rb https://spectre.spookyinternet.com/dl/node.rb
sudo crew remove node
crew install nodetest
```

**Comment by flyingP0tat0** [comment]
The version you provided seems to be the exact same as in the repo?
Anyway, I should have just checked the tip to run chown (shown after installation via crew). Everything is working fine now!
