### ISSUE TITLE
libicu18n.so.68: cannot open shared object file: no such file or directory 

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#5791]
this error was reported to the discord server. I don't know the back story and can't test what went wrong exactly since I don't have a chrome device anymore, but I'm sure there was recently an update for curl that broke it again....
![image](https://user-images.githubusercontent.com/59572686/118538346-9542c080-b73d-11eb-8fbb-796083720cd0.png)

**Comment by uberhacker** [comment]
@ThatGeekyWeeb: We'll need more info.  Output of `/etc/lsb-release`, `arch` and Chromebook make and model if applicable.

**Comment by uberhacker** [comment]
My first thought was did they run `rm -rf /usr/local` prior?

**Comment by ThatGeekyWeeb** [comment]
Will keep chatting with them, waiting for a response ^^

**Comment by ThatGeekyWeeb** [comment]
![image](https://user-images.githubusercontent.com/59572686/118540730-611ccf00-b740-11eb-8ada-f8094d8bc395.png)
they are also on `x86_64`, I think they were trying to chromebrew ontop of brunch-toolchain, which may be the issue, waiting for them to reinstall after wiping `/usr/local`, but I think the install script should automatically do that...

**Comment by ThatGeekyWeeb** [comment]
we have a new problem now, @uberhacker 
![image](https://user-images.githubusercontent.com/59572686/118541630-734b3d00-b741-11eb-97f5-d6d5c3b63eed.png)

**Comment by uberhacker** [comment]
What is the output of `echo $LD_LIBRARY_PATH`?

**Comment by uberhacker** [comment]
We don't want to add `rm -rf /usr/local` to the script because someone may have chroots or other mounts there.  I also don't want to encourage users to run this blindly.

**Comment by stem2580** [comment]
hi, i'm the one with the problem and this is the output
![image](https://user-images.githubusercontent.com/37732484/118547041-ba8cfa00-b750-11eb-95f8-27e82cbc98e6.png)

**Comment by uberhacker** [comment]
@stem2580: Try this:
```
export LD_LIBRARY_PATH=/usr/local/lib64
rm -rf /usr/local
curl -Ls git.io/vddgY | bash
```
Do not use sudo.

**Comment by stem2580** [comment]
just as a confirmation 
`rm -rf /usr/local` or `rm -rf /usr/local/*`

**Comment by uberhacker** [comment]
Don't use `*` because that does not remove hidden files.

**Comment by stem2580** [comment]
`chronos@localhost ~/Downloads $ rm -rf /usr/local/
rm: cannot remove '/usr/local/': Permission denied
chronos@localhost ~/Downloads $ sudo rm -rf /usr/local/
rm: cannot remove '/usr/local/': Device or resource busy`

**Comment by uberhacker** [comment]
Don't worry about that error.  `/usr/local` is read-only and the goal here is just to clear about everything below that directory.

**Comment by stem2580** [comment]
well it's still running, how long would it take ?

**Comment by uberhacker** [comment]
My guess is 5 to 10 minutes depending on the speed of your Chromebook.

**Comment by uberhacker** [comment]
If you answered yes to the development tools prompt, it could take over 20 minutes.

**Comment by stem2580** [comment]
ok i guess setting that `export LD_LIBRARY_PATH=/usr/local/lib64` fixed it
![image](https://user-images.githubusercontent.com/37732484/118551096-6c2e2a00-b755-11eb-871b-48154cdbc736.png)
tysm @uberhacker 😘

**Comment by uberhacker** [comment]
Sure thing.  You might want to add `export LD_LIBRARY_PATH=/usr/local/lib64` to your `~/.bashrc`.

**Comment by stem2580** [comment]
ok `echo "export LD_LIBRARY_PATH=/usr/local/lib64" >> ~/.bashrc` should do it
