### ISSUE TITLE
crew build pixz compression not working

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5806]
crew build only works on x86_64.
```
Archiving...
Using pixz to compress archive.
Error creating block encoder
```

**Comment by satmandu** [comment]
I've been building pixz archives on i686 and armv7l.

Is pixz installed?

**Comment by satmandu** [comment]
What does `pixz -v` give you?

**Comment by satmandu** [comment]
Actually, this could also be a memory issue on those architectures. Are you compressing a large package?

**Comment by uberhacker** [comment]
These were jdk8 binaries so yes, they were large(r than most other package binaries).  FWIW, I don't have the same issue with .tar.xz archives.  What is the rationale for using .pixz over .xz?  Could .lz be another option?

**Comment by satmandu** [comment]
Rationale is to easily extract files without downloading entire package. Should save download time at install once I get the partial install stuff working in crew. (Probably not needed for java.)

Primarily useful for packages which need just need some libraries installed from other (large)packages as dependencies.

**Comment by satmandu** [comment]
GCC & LLVM are the large packages here which matter.... But those are built on (relatively) beefy machines with tons of ram, so that avoids this compression with low ram problem.

But maybe it might also be easier not to build the larger packages on i686 and armv7l?
