### ISSUE TITLE
Python3 and tkinter + mono-vbnc questions

### ISSUE THREAD

**Issue by GitHubDragonFly** [skycocker/chromebrew#5807]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.
- Missing module _tkinter + mono cannot run VB app

## Versions and system information
chromebrew: `crew --version`
1.10.5

ChromeOS: `cat /etc/lsb-release`
Chromium OS - CloudReady v89.4.0

Model: YOUR MODEL HERE
HP Compaq Presario C700

Architecture: `uname -m`
x86_64

## Additional information
Mention things we might need to know. Like:

- tkinter runs ok if I compile python3 from source and point it to use crew installation of tcl and tk with the following steps:

./configure --enable-optimizations --with-tcltk-includes='-I/usr/local/include' --with-tcltk-libs='/usr/local/lib64/libtcl8.6.so /usr/local/lib64/libtk8.6.so'
make
make install

This ends up being installed in /usr/local/lib/python3.9 instead of /usr/local/lib64/python3.9 where crew installs it.
It works but I had to use 'disable_verity' and then 'sudo mount -o rw,remount -o exec /home/chronos/user/' in order to start the compilation from my Downloads folder.

- On standard Linux distributions I would normally install 'mono-complete' and 'mono-vbnc' in order to run Windows based VB apps. This doesn't work with crew installation of 'mono' (error: Could not load file or assembly 'Microsoft.VisualBasic ...') while crew installation of 'wine' does actually start a VB app.

What I think needs to be done:
- [x] step one
The python3.rb file currently has 'depends on' tcl and tk commented out so I am not sure if re-enabling these alone would work.

- [x] step two
Hopefully include mono-vbnc package to run VB apps.

**Comment by satmandu** [comment]
I believe the rationale for leaving out tcl/tk was to reduce the size of python as a core package, since that also removes the requirement for installing tcl/tk.

Note also that we use the `-Wl,-rpath,-L#{CREW_LIB_PREFIX}` bit in the package file to find the libraries in lib64.

You could uncomment the two depends lines and then do a `crew reinstall -s python3` and see if that fixes your issue too.

**Comment by satmandu** [comment]
(if that does, let us know and we can talk about making that the default again.)

**Comment by saltedcoffii** [comment]
When adding TK into Python's core packages, it creates the IDLE3 IDE which requires X or Wayland support. Which means that core would require all of those deps as well.

**Comment by GitHubDragonFly** [comment]
Your usage of the word "core" somehow indicates using the crew on devices with limited storage.

Leaving tcl/tk out and offering them separately doesn't make much sense since the crew installation of python3 doesn't use them after they are installed as separate packages.

What would make sense to me is installing python3 with all the options in a single step, meaning to include tcl/tk and idle3 and X or Wayland support and anything else that might be required. So, besides for the python3.rb there could also be python3-full.rb, or similar, to offer this.

I am not too familiar with the chromebrew and its repository to actually follow your suggestion of changing the file and re-installing. Would I have to create a fork and make changes there or something else?

Since I am only experimenting with this on an old computer then I don't see these as an issue.

**Comment by uberhacker** [comment]
@GitHubDragonFly: We cannot assume everyone wants or needs X or Wayland support with python.  Some may only want to use the basic python.  That said, installing X packages does require many packages and an excessive amount of disk space.  Since python is a core package, adding all this extra bloat would make for long installs and make it impossible to install on devices with limited storage.

**Comment by GitHubDragonFly** [comment]
The sole reason for my suggesting an additional optional python3-full.rb package, so those who have enough storage can try it.

Your comment still doesn't explain why separate tcl/tk packages exist when they are not usable with the core installation of python3 (at least I couldn't make it work out of the box).

As stated, I am only experimenting with these so debating any of it is just pointless.
