### ISSUE TITLE
flatpak command is broken in some cases

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5812]
When running `flatpak` with some commands, the wrapper script breaks flatpak. Most of the instances where flatpak is broken involves informational commands.

Reproduction:
Install flatpak with chromebrew.
Run any of the following commands:
`flatpak`
`flatpak --help`
`flatpak ps`
`flatpak kill <program>`

This can be fixed temporarily by specifying the full name of the actual flatpak binary, e.g.:
`/usr/local/libexec/flatpak/flatpak ps`

Perhaps we can figure out how to get the system install at `/usr/local/var/lib/flatpak` working instead of `${HOME}/.local/share/flatpak`

**Comment by ClaytonTDM** [comment]
Same issue, same temporary fix. Hmm.
