### ISSUE TITLE
e2fsprogs conflicts with krb5

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5820]
Building e2fsprogs from the source with krb5 installed results in this error:
```
$ crew install -s e2fsprogs
# Skipping lines for brevity
Rename all *.la_tmp files back to *.la
Checking for conflicts with files from installed packages...
Unable to complete this build since there is a conflict with the same file in another package.

krb5 package conflicts below:
/usr/local/share/man/man1/compile_et.1.gz
```

**Comment by uberhacker** [comment]
Since krb5 is a core package, probably the best solution is to remove the conflict from e2fsprogs.

**Comment by satmandu** [comment]
Looking at other packages elsewhere it probably makes sense to make e2fsprogs core, and modify krb5 NOT to create these conflicts.

See https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=krb5-git and also https://github.com/archlinux/svntogit-packages/blob/packages/e2fsprogs/trunk/PKGBUILD

**Comment by satmandu** [comment]
Have some updates in progress to handle this. krb5 needs a reinstall after e2fsprogs is built, since the dependency is now reversed... 

This also may need updated brotli & curl...

**Comment by satmandu** [comment]
This was fixed by https://github.com/skycocker/chromebrew/pull/5837 and https://github.com/skycocker/chromebrew/pull/5893
