### ISSUE TITLE
fail to run android studio

### ISSUE THREAD

**Issue by blinderjay** [skycocker/chromebrew#5824]
## Description
Android Studio failed to run neither via crew or official website

If you executed a specific command:
```shell
studio
```

Output:
```shell
Startup Error: Unable to detect graphics environment
```

## Versions and system information
chromebrew: 1.10.8

ChromeOS: `cat /etc/lsb-release`
```
chronos@localhost /usr/local/share $ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7334568
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BD7F7139-CC18-49C1-A847-33F155CCBCA8}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BD7F7139-CC18-49C1-A847-33F155CCBCA8}
CHROMEOS_RELEASE_BOARD=nocturne-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=82
CHROMEOS_RELEASE_BUILDER_PATH=nocturne-release/R90-13816.82.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.82.0 (Official Build) stable-channel nocturne 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13816.82.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.82.0
```

Model: PixelSlate

Architecture: `x86_64 m3`

## Additional information

**Comment by uberhacker** [comment]
Is sommelier running?  `ps ax|grep sommelier`

**Comment by satmandu** [comment]
Hello fellow Pixel Slate user. It's nice to see the other one of us on here. :)

Try running `restartsommelier` before running `studio`...

and please make sure you've run `crew update` too.

**Comment by blinderjay** [comment]
> Is sommelier running? `ps ax|grep sommelier`

Although haven't figured out the problem, I solved this problem along with vscodium 

## by start another sommelier daemon：
```bash
# ~/.bashrc
alias studio="sommelier -X --x-display=:0  --scale=0.7 --glamor --drm-device=/dev/dri/renderD128 --virtwl-device=/dev/null --shm-driver=noop --data-driver=noop --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland  /usr/local/bin/studio"
```
android-studio will always succeed to run in this way, and then exec `pgrep -f "sommelier"` , or  start a new shell from crosh, two PID will return. 

---------
## `source ~/.sommelier*` 
this wiil take effect sometimes, thats confusing...
