### ISSUE TITLE
Fresh install : multiple error "too many levels of symbolic links"

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#5826]
On a fresh install on a x86_64 machine (chromeOS 90.0.4430.218), I am facing multiple errors each time a symbolic link is involved (installation of yarn modules, simple ls commans, ...).

Even if I run : 
``` bash
chronos@localhost ~ $ mkdir foo
chronos@localhost ~ $ ln -s ~/login-times foo/login
chronos@localhost ~ $ ls -l foo/login 
lrwxrwxrwx 1 chronos chronos 34 May 31 16:57 foo/login -> /home/chronos/user/login-times
chronos@localhost ~ $ ls foo/login 
ls: cannot access 'foo/login': Too many levels of symbolic links
```

Thus, my chromebrew install is totally useless.... Any hints to solve this ? There is absolutely no loop or reference to itself in the example above which is normaly what this error implies....

**Comment by vincowl** [comment]
`cat foo/login` fails with the same error while `cat ~/login-times` works perfectly.... So strange...

Already tried to wipe the whole chromebook and reinstall

**Comment by uberhacker** [comment]
@vincowl: Release 90 has symlink nofollow enabled in the `$HOME` directory.  My guess is you have something configured in your `~/.bashrc` that triggers this issue.  [This comment](https://github.com/skycocker/chromebrew/issues/5681#issuecomment-826007026) may be helpful.

**Comment by vincowl** [comment]
Alas this occurs even before chromebrew installation and .bashrc is empty. I'm going to try to install chromebrew and see if it solves this

**Comment by vincowl** [comment]
So.... still the same problem... modifying the PATH envvar didn't change anything..... Note that I had to manually add the line to the .bashrc file....

**Comment by uberhacker** [comment]
There might be something else doing it.  What is the output of `echo $PATH`?

**Comment by vincowl** [comment]
```
chronos@localhost / $ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin
```

**Comment by uberhacker** [comment]
What happens if you move the first path to the end? `export PATH=/usr/bin:/bin:/opt/bin:/usr/local/bin`

**Comment by vincowl** [comment]
Exactly the same. I already tried using the `ls` command from `/bin/ls` and `/usr/local/bin/ls` without success...

**Comment by uberhacker** [comment]
Do you have the lines below in your `~/.bashrc`?

**Comment by vincowl** [comment]
Yes, it's at the top of the file

**Comment by uberhacker** [comment]
Try commenting `source /usr/local/etc/profile`.

**Comment by vincowl** [comment]
stil the same...

**Comment by uberhacker** [comment]
Did you run `source ~/.bashrc`?

**Comment by vincowl** [comment]
Yep... I opened a new terminal which sources ~/.bashrc
Note that this problem occurs even if chromebrew is not installed. Installing it didn't change anything at all

**Comment by uberhacker** [comment]
Well, that is interesting.  The latest release 90 stable update must have locked it down even further.

**Comment by vincowl** [comment]
That implies that we probably have to store our apps config files in /usr/local instead of the user's home, which is a pain in the ass when we have several user accounts on the chromebook.

**Comment by vincowl** [comment]
Well... That's unbearable.... Even vim's plugin (coc.nvim) cannot install its modules...Chromebrew becomes totally unusable to me... Does anybody face the same trouble ? I am running a Cave chromebook (asus C302CA)

**Comment by satmandu** [comment]
> That implies that we probably have to store all our apps config files in /usr/local instead of the user's home, which is a pain in the ass when we have several user accounts on the chromebook.

With the nosymfollow stuff in M90 I suspect that multiuser usage on the same device is just utterly broken.

**Comment by satmandu** [comment]
As this appears to be `nosymfollow` related, I'm closing this, as this appears to be a symptom of local settings unrelated to the default install settings. 

(Not that it doesn't suck for users affected by this.)
