### ISSUE TITLE
Chromeos' vmc command broken after installing chromebrew

### ISSUE THREAD

**Issue by ilia3101** [skycocker/chromebrew#5864]
Used to run the following to fix linux issues:
```
vmc stop termina; vmc start termina
```
It would run for a few seconds and enter some shell I would then exit.

Now it does nothing and just prints this:
```
Error: D-Bus error: Failed to connect to socket /usr/local/var/run/dbus/system_bus_socket: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)
Error: D-Bus error: Failed to connect to socket /usr/local/var/run/dbus/system_bus_socket: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)
```

What has chromebrew changed in the system to make this happen and how can I undo it? Also I now have to enter my password to enter 'shell' from crosh. How can I undo all of this?

**Comment by uberhacker** [comment]
@ilia3101: Can you please provide more info?  What is the output of `cat /etc/lsb-release` and `arch`?  If you are already on the stable channel, you might try a powerwash, although you will have to reinstall chromebrew afterwards.

**Comment by satmandu** [comment]
What does `crew list installed` give you?

**Comment by satmandu** [comment]
You can remove the dev mode password with `rm /mnt/stateful_partition/etc/devmode.passwd` which is set inside `/usr/sbin/chromeos-setdevpasswd`...

**Comment by satmandu** [comment]
Also the DBUS variable is probably set inside `/usr/local/etc/env.d/` so you can grep for `DBUS` there to see what is setting it and comment that out.

**Comment by satmandu** [comment]
a `vmc` wrapper script to unset that appropriately might fix this too for you.

Also check `~/.bashrc`  and `~/.profile` and so on to see if anything DBUS is being set there...

**Comment by ilia3101** [comment]
Thanks so much for the advice!

Ok I figured this out. 

> What does `crew list installed` give you?

dbus was one of the packages! removing it fixed the issue. Somehow must've been overriding the original chromeos' dbus through environment variables in the shell environment. As this seems to break `vmc` and possibly other commands in the shell maybe it should be looked in to by chromebrew developers?

> Also check `~/.bashrc` and `~/.profile` and so on to see if anything DBUS is being set there...

Thank you, the password checking was also enabled by a line chromebrew added in `.bashrc`, although I'm going to keep it, as it's only a good thing tbh.

**Comment by supechicken** [comment]
@ilia3101 Could you try the following:
```
export DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'
```
(This will tell dbus to use system bus)
As a alternative, you can use the system dbus command instead:
```
env PATH='/bin:/sbin:/usr/bin:/usr/sbin' LD_LIBRARY_PATH='' crosh
```
