### ISSUE TITLE
crew should check on update to see if there are uninstalled packages in core.

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#5865]
- Since `install.sh` is installing `core`, we should make sure that any changes to core are reflected later too in the installation state.

**Comment by uberhacker** [comment]
That's why we have `crew update`.  An install is (or should be) in an initial state so there will be no updates unless I'm missing something.

**Comment by satmandu** [comment]
What I mean is that crew update should also compare the list of packages in core with those in installed_packages, and offer to install packages newly listed in core.

I don't believe crew does that at the moment.

**Comment by satmandu** [comment]
What I mean is that crew update should also compare the list of packages in core with those in installed_packages, and offer to install packages newly listed in core.

I don't believe crew does that at the moment.

**Comment by satmandu** [comment]
What I mean is that crew update should also compare the list of packages in
core with those in installed_packages, and offer to install packages newly
listed in core.

I don't believe crew does that at the moment.

**Comment by uberhacker** [comment]
Oh, I think I understand now.

**Comment by satmandu** [comment]
I think the easiest way to do this would be to just make `core` a metapackage like `buildessential`, no?

Otherwise, we need to rearchitect `crew` to read a file from the utils folder, and the utils folder is only synced to new installs anyways.

I'm perfectly happy taking out the pretty core logic in `install.sh` to make it simpler. :)

**Comment by uberhacker** [comment]
I like the idea.  It makes a lot of sense.  What would happen if somebody uninstalled the fake core metapackage, however?

**Comment by satmandu** [comment]
Does removing metapackages even work? 

`crew remove buildessential` does basically nothing, no?

**Comment by uberhacker** [comment]
If the core metapackage is removed and an update includes a new package, for instance, that new package would not be included in the update unless crew knows the core metapackage is installed, right?

**Comment by satmandu** [comment]
We could make sure it is installed like with buildessential, where that automatically gets reinstalled during crew build functions...

**Comment by satmandu** [comment]
Let's do this one step at a time. Currently, we have no mechanism to look
for updates for core, right?

So I suggest:
1. Make a core metapackage.
2. Modify install.sh to use that metapackage.
3. Modify crew to check to see if core is installed during updates.
