### ISSUE TITLE
Install script fails at line 54

### ISSUE THREAD

**Issue by Coy-Allen** [skycocker/chromebrew#5868]
## Description
running install script fails at line 54

```
crosh> shell
chronos@localhost / $ curl -Ls git.io/vddgY | bash
Welcome to Chromebrew!

Install development tools? (not needed for most users) [y/N]: bash: line 54: cho: command not found
chronos@localhost / $
```

I have also tried manualy downloading the file and pipeing it into bash but the problem persists.

## Versions and system information
ChromeOS: 13816.82.0

Model: s330 lenovo chromebook

Architecture: aarch64

**Comment by satmandu** [comment]
I've seen this too occasionally, and I think it is from a failed download of the install script.

Can you try piping the direct link to the install script to bash:

```curl -Ls https://github.com/skycocker/chromebrew/raw/master/install.sh | bash```

**Comment by satmandu** [comment]
If that gives the same error try this:
```
curl -OLf https://github.com/skycocker/chromebrew/raw/master/install.sh
bash install.sh
```

**Comment by satmandu** [comment]
@uberhacker Any ideas on this?

line 54 seems fine. Somehow the file is getting cut off when passed to bash.

**Comment by uberhacker** [comment]
I get the same results.  It looks like we are going to have to revert the last commit.
```
$ curl -Ls git.io/vddgY | bash
Welcome to Chromebrew!

Install development tools? (not needed for most users) [y/N]: bash: line 54: cho: command not found
$ curl -Ls git.io/vddgY -o install.sh
$ bash install
...snip...
Setup and synchronize local package repo...

install.sh: line 221: 16384 Segmentation fault      (core dumped) git clone --depth=1 --filter=blob:none --no-checkout "https://github.com/${OWNER}/${REPO}.git" "${CREW_LIB_PATH}"
```
We can't have broken binaries in core packages.

**Comment by satmandu** [comment]
You're getting a different error. Are you seeing segfaults on anything besides i686 @uberhacker ?

**Comment by satmandu** [comment]
The line 54 issue is likely not related to git, as it happens before git is actually used.

**Comment by Coy-Allen** [comment]
> If that gives the same error try this:
> 
> ```
> curl -OLf https://github.com/skycocker/chromebrew/raw/master/install.sh
> bash install.sh
> ```

That seemed to fix the problem as i can now select y/N so it was probably the pipe that broke it somehow.
It now shows a noexec mount warning before the script starts but seems to not interfere with or break the script.
Thanks for the help!

**Comment by uberhacker** [comment]
@satmandu: Yes, this only happens on i686.
