### ISSUE TITLE
symbol lookup error: /usr/local/lib64/libjavascriptcoregtk-4.0.so.18: undefined symbol: u_strToUpper_68

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#5880]
I installed `gemacs` package, then installed [doom emacs](https://github.com/hlissner/doom-emacs). When running `gemacs` I have this error : 
```
gemacs: symbol lookup error: /usr/local/lib64/libjavascriptcoregtk-4.0.so.18: undefined symbol: u_strToUpper_68
```
I couldn't manage to reinstall gemacs with compilation (`crew reinstall -s gemacs`) due to compile errors, and also failed with `webkit2gtk_4`

**Comment by uberhacker** [comment]
@vincowl:  Did you try reinstalling `webkit2gtk_4` from source?

**Comment by vincowl** [comment]
Yes. Compilation failed. I'll try to get the error message tomorrow

**Comment by satmandu** [comment]
I think webkit2gtk needs a rebuild with the newer icu4c...

**Comment by satmandu** [comment]
I have an incoming rebuild with llvm for x86_64. Other architectures are having problems.

**Comment by satmandu** [comment]
Got this building for everything.
