### ISSUE TITLE
nano & emacs packages shown as installed but do not launch from command line -- $PATH ?

### ISSUE THREAD

**Issue by faddah** [skycocker/chromebrew#59]
hello @skycocker ,

using your chromebrew tool, i installed both nano and emacs to have some choices in command line word processing. they show as installed when i do `crew search`  --

``` bash

$ crew search
(i) autoconf
(i) automake
(i) binutils
bison
buildessential
(i) bz2
clisp
cmake
ctags
(i) curl
dartsdk
(i) diffutils
(i) emacs
(i) expat
ffcall
gawk
(i) gcc
(i) gettext
(i) git
(i) glibc
(i) gmp
htop
(i) jdk8
less
(i) leveldb
(i) libevent
(i) libsigsegv
(i) libssh2
(i) linuxheaders
(i) m4
(i) make
(i) mpc
(i) mpfr
(i) nano
(i) ncurses
ncurses_so
(i) openssl
patch
(i) perl
powerline_fonts
(i) python
(i) python27
python34
(i) readline
rsync
ruby
(i) sqlite
tig
(i) tmux
vim
(i) zlibpkg
(i) zsh

```

and here is what happens if i try and install again, the packages show as all ready installed, as here with nano --

``` bash

$ crew install nano
Found nano, version 2.3.6
Following packages also need to be installed: 
libsigsegv diffutils binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential ncurses 
Do you agree? [Y/n]

Proceeding...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found ncurses, version 5.9
Package ncurses already installed, skipping...
Found nano, version 2.3.6
Package nano already installed, skipping...

```

... and here with emacs --

``` bash

$ crew install emacs
Found emacs, version 24.4
Following packages also need to be installed: 
libsigsegv perl m4 autoconf libsigsegv perl m4 libsigsegv libsigsegv diffutils m4 autoconf automake 
Do you agree? [Y/n]

Proceeding...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found perl, version 5.16.3
Package perl already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found autoconf, version 2.69
Package autoconf already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found perl, version 5.16.3
Package perl already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found autoconf, version 2.69
Package autoconf already installed, skipping...
Found automake, version 1.14
Package automake already installed, skipping...
Found emacs, version 24.4
Package emacs already installed, skipping...

```

however, each and every time i attempt to launch nano or emacs from the command line, i get the following --

``` bash

$ emacs
bash: emacs: command not found

```

... the same happens with nano. 

can you please offer any help here? do i need to add something to my $PATH statement in `~/.bashrc` to make this work? i'm on a Acer C720P intel chromebook and yes, it is in dev mode and has your chromebrew tool installed, as indicated above.

please advise, thank you in advance.

best,

--  faddah wolf
    portland, oregon, u.s.a.

**Comment by skycocker** [comment]
It's probably not your fault. I'll be looking at it when I find some spare time.

**Comment by faddah** [comment]
hi @skycocker ,

is there any update on these issues yet? please advise when you can. thank you.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by mrzmmr** [comment]
@faddah ,
I was able to install both nano and emacs without a problem.
Did you make sure that /usr/local/bin was in your $PATH
```
echo $PATH
```
also did you check /usr/local/bin to see if either nano or emacs binaries were in there? If they are and /usr/local/bin is in your path then you could try just adding an alias to ~/.bashrc

```
alias nano=/usr/local/bin/nano
alias emacs=/usr/local/bin/emacs
```

**Comment by faddah** [comment]
hello @mrzmmr & @skycocker ,

thank you for responding. still waiting to hear an update from @skycocker, however.

yes, i know ```$echo $PATH``` and yes, ```/usr/local/bin``` is in my ```$PATH``` statement.

however, if i do ```ls -a /usr/local/bin```, that comes back showing no nano or emacs in that directory, whatsoever. however, if i do ```crew install nano``` or ```crew install emacs```, what i get on both is — 

```bash

$ crew install nano
Found nano, version 2.3.6
Following packages also need to be installed: 
libsigsegv diffutils binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential ncurses 
Do you agree? [Y/n]

Proceeding...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found ncurses, version 5.9
Package ncurses already installed, skipping...
Found nano, version 2.3.6
Package nano already installed, skipping...

$ crew install emacs
Found emacs, version 24.4
Following packages also need to be installed: 
libsigsegv perl m4 autoconf libsigsegv perl m4 libsigsegv libsigsegv diffutils m4 autoconf automake 
Do you agree? [Y/n]

Proceeding...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found perl, version 5.16.3
Package perl already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found autoconf, version 2.69
Package autoconf already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found perl, version 5.16.3
Package perl already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found libsigsegv, version 2.10
Package libsigsegv already installed, skipping...
Found diffutils, version 3.3
Package diffutils already installed, skipping...
Found m4, version 1.4.17
Package m4 already installed, skipping...
Found autoconf, version 2.69
Package autoconf already installed, skipping...
Found automake, version 1.14
Package automake already installed, skipping...
Found emacs, version 24.4
Package emacs already installed, skipping...

```

as i said, neither ```nano``` or ```emacs``` are in my ```/usr/local/bin``` directory, the ```/usr/local/bin``` is in my ```$PATH```, but for some reason, crew thinks i all ready have both ```nano``` and ```emacs``` installed. this is why i need help with this.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
@skycocker & @mrzmmr,

**update**: 

i did a ```sudo crew remove nano``` and ```sudo crew remove emacs``` and removed both applications, then made sure both showed as not installed with ```crew search``` and that was indeed the case.

then i reinstalled both with ```crew install nano``` and ```crew install emacs```.

now both are installed fine — they are both in the ```/usr/local/bin``` directory and they run just fine from the command line.

so you can feel free to go ahead and close this one out, but you should perhaps add to the README.md that if folk run into problems like this, the answer i have found is:  ```sudo crew remove [NAME OF CLI APP]``` then reinstall, and then make sure the CLI App is in there with both ```ls -a /usr/local/bin``` and ```crew search```. 

again, o.k. to close this out, but i would suggest adding that to the README.md. i can do that, if you like, and issue a pull request, if you would like. please let me know.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by Borealis023** [comment]
Rather than opening a new issue, I wanted to say that I'm experiencing this issue but none of the above solutions are working. There is no `node` in my /usr/local/bin, but when I `crew search node` it insists that it is installed. This is happening for everything that I am trying to install, and even upon multiple tries of uninstalling, reinstalling, testing, and such it doesn't work. 

I'm not really sure of the issue, and why Chromebrew thinks that it is installed when it isn't.

**Comment by jam7** [comment]
`/usr/local/etc/crew/device.json` file contains information why chromebrew thinks that a package is installed or not.

Generally, `sudo crew remove PACKAGE` will remove files and directories for the package and remove existing information from `/usr/local/etc/crew/device.json` well, but it may fails for some unkown reason.  If you see error message or something, please let us know.  thanks.
