### ISSUE TITLE
error in opening gnome-terminal

### ISSUE THREAD

**Issue by sandeep-gh** [skycocker/chromebrew#5936]
## Description
Just giving chromebrew a try.  gemacs is working fine. But gnome-terminal is not opening up.  

If you executed a specific command:
```shell
gnome-terminal
```

Output:
```shell
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Unknown or unsupported transport “disabled” for address “disabled:”
```

## Versions and system information
1.11.5

ChromeOS: `cat /etc/lsb-release`
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7487557
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={50F3C95B-CA5B-4AF8-87A2-8CD19588BD12}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={50F3C95B-CA5B-4AF8-87A2-8CD19588BD12}
CHROMEOS_RELEASE_BOARD=kukui-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=39
CHROMEOS_RELEASE_BUILDER_PATH=kukui-release/R92-13982.39.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.39.0 (Official Build) beta-channel kukui 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.39.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13982.39.0
```
Model: lenovo duet chromebook

Architecture: aarch64

**Comment by uberhacker** [comment]
Thank you for the feedback @sandeep-gh.  What happens if you build `gnome-terminal` from source with `crew install gnome_terminal -s`?

**Comment by uberhacker** [comment]
Also, I noticed you were on the beta channel.  We only officially support the stable channel.

**Comment by satmandu** [comment]
I'm seeing the same issue with `gnome-terminal`.  Let me try a rebuild...

**Comment by satmandu** [comment]
I have a solution for this... I think we just need to add a postinstall section.

Can you tell me if this works for you?
```
glib-compile-schemas /usr/local/share/glib-2.0/schemas
gnome-terminal &
```

**Comment by satmandu** [comment]
(Once I have a new armv7l build I'll submit a PR for this.)

**Comment by sandeep-gh** [comment]
> Also, I noticed you were on the beta channel. We only officially support the stable channel.

All I did was invoke this command 
```
curl -Ls git.io/vddgY | bash
```
followed by `crew install`. Not sure why this is connecting to the beta channel.

**Comment by satmandu** [comment]
The issue is that there are changes on the beta channel which might not have been tested.

For instance, Beta Channel/M92 has moved to glibc 2.32, and we are still working on getting that supported properly.

Please do try to do a `crew update ; crew upgrade` now though, as hopefully this issue with `gnome-terminal` is now addressed.

**Comment by satmandu** [comment]
(and let us know if it does not work for you!)

**Comment by sandeep-gh** [comment]
> ```
> glib-compile-schemas /usr/local/share/glib-2.0/schemas
> gnome-terminal &
> ```
I tried the above steps. The compile fails for me. Have attached the error log:

```
more /usr/local/tmp/crew/gnome_terminal.2021070814
4824.dir/gnome-terminal-3b79354a357970147ae276a02ca2222db98a0d28/builddir/meson-logs/meson-log.txt
Build started at 2021-07-08T20:18:31.106412
Main binary: /usr/local/bin/python3
Build Options: -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dmandir=/usr
/local/share/man -Dbuildtype=minsize -Db_lto=true -Dstrip=true -Db_pie=t
rue '-Dcpp_args=-flto -fno-stack-protector -U_FORTIFY_SOURCE -fuse-ld=go
ld -pipe' '-Dc_args=-flto -fno-stack-protector -U_FORTIFY_SOURCE -fuse-l
d=gold -pipe' -Dsearch_provider=false -Dnautilus_extension=false -Ddefau
lt_library=both
Python system: Linux
The Meson build system
Version: 0.58.1
Source dir: /usr/local/tmp/crew/gnome_terminal.20210708144824.dir/gnome-
terminal-3b79354a357970147ae276a02ca2222db98a0d28
Build dir: /usr/local/tmp/crew/gnome_terminal.20210708144824.dir/gnome-t
erminal-3b79354a357970147ae276a02ca2222db98a0d28/builddir
Build type: native build
Project name: gnome-terminal
Project version: 3.41.0
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /usr/local/tmp/crew/gnome_termina
l.20210708144824.dir/gnome-terminal-3b79354a357970147ae276a02ca2222db98a
0d28/builddir/meson-private/sanitycheckc.c -o /usr/local/tmp/crew/gnome_
terminal.20210708144824.dir/gnome-terminal-3b79354a357970147ae276a02ca22
22db98a0d28/builddir/meson-private/sanitycheckc.exe -flto -fno-stack-pro
tector -U_FORTIFY_SOURCE -fuse-ld=gold -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/local/bin/ld.gold: error: cannot open Scrt1.o: No such file or dire
ctory
/usr/local/bin/ld.gold: error: cannot open crti.o: No such file or direc
tory
/usr/local/bin/ld.gold: error: cannot open crtn.o: No such file or direc
tory
/usr/local/bin/ld.gold: error: cannot find -lc
collect2: error: ld returned 1 exit status

**Comment by satmandu** [comment]
Right. that's a glibc 2.32 issue with gcc compiles we still haven't dealt with properly. (I also run beta channel, so I feel your pain.)

`crew update ; crew upgrade ; crew reinstall gnome_terminal` should get you the precompiled gnome-terminal though, which I built yesterday on a armv7l VM in a M90 container.

**Comment by satmandu** [comment]
(Running `gnome-terminal &` after that should hopefully work.)

**Comment by sandeep-gh** [comment]
@satmandu  I did the above steps. Still getting
```# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Unknown or unsupported transport “disabled” for address “disabled:”```

**Comment by sandeep-gh** [comment]
can we reopen this issue?

**Comment by satmandu** [comment]
So maybe this is a dbus issue?
Do you have `NO_AT_BRIDGE=1` set?

i.e. see what this gives you:
 ```env | grep NO_AT_BRIDGE```

First try this:
`NO_AT_BRIDGE=1  gnome-terminal`

You should also try this:
`dbus-launch gnome-terminal gnome-terminal`

And if that doesn't work try this:
`LC_ALL="en_US.UTF-8" gnome-terminal`

Last, try them all together:
`NO_AT_BRIDGE=1 LC_ALL="en_US.UTF-8"  dbus-launch gnome-terminal gnome-terminal`

**Comment by sandeep-gh** [comment]
I had given hope by the third command. Magically, the last command worked :). Great help. Thank you.

**Comment by satmandu** [comment]
Do you have anything set normally for those other variables?

What do these give you:
```
env | grep NO_AT_BRIDGE
env | grep LC
env | grep DBUS
```

(I'm trying to figure out if we need to adjust settings globally so that this works without people having to open an issue... so it would be helpful to know the minimum settings required to allow that to happen.)

**Comment by sandeep-gh** [comment]
Attached is the output for the above command:
```
chronos@localhost / $ env | grep NO_A
chronos@localhost / $ env | grep LC  
chronos@localhost / $ env | grep DBUS
DBUS_SESSION_BUS_ADDRESS=disabled:
DBUS_FATAL_WARNINGS=0
```

**Comment by satmandu** [comment]
Thanks for the feedback.
