### ISSUE TITLE
unstall chromebrew

### ISSUE THREAD

**Issue by zheyiyuezhuo** [skycocker/chromebrew#5952]
When I don't want to use chromedrew, how do I uninstall it from chrome os?
I browsed some materials, but none of them explained how to uninstall chromebrew when I don't want to use it.
Thank you for developing this awesome tool,
If you can answer, thank you!

**Comment by uberhacker** [comment]
See https://github.com/skycocker/chromebrew/wiki/How-to-remove-chromebrew.

**Comment by zheyiyuezhuo** [comment]
> https://github.com/skycocker/chromebrew/wiki/How-to-remove-chromebrew

Thank you！
