### ISSUE TITLE
Git broken on fresh install

### ISSUE THREAD

**Issue by cparker15** [skycocker/chromebrew#5962]
## Description
When I run the installer referenced on the Chromebrew site with an empty `/usr/local` directory, it succeeds until the first git command

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
Setup and synchronize local package repo...

Cloning into '/usr/local/lib/crew'...
git: 'remote-https' is not a git command. See 'git --help'.
```

## Versions and system information
ChromeOS: `CHROMEOS_RELEASE_VERSION=13904.66.0`

Model: Acer Chromebook Spin 311

Architecture: `x86_64`

**Comment by satmandu** [comment]
What does running ```/usr/local/libexec/git-core/git-remote-https```  give you?

**Comment by satmandu** [comment]
This is what I see:
```
chronos@localhost /usr/local/lib/crew/lib $ /usr/local/libexec/git-core/git-remote-https
error: remote-curl: usage: git remote-curl <remote> [<url>]
```

**Comment by uberhacker** [comment]
@cparker15: Can you please output the entire result of `cat /etc/lsb-release`?

**Comment by cparker15** [comment]
```
Cloning into '/usr/local/lib/crew'...
git: 'remote-https' is not a git command. See 'git --help'.
chronos@localhost / $ /usr/local/libexec/git-core/git-remote-https
bash: /usr/local/libexec/git-core/git-remote-https: Too many levels of symbolic links
```

I think I figured out why this is happening. I am bind-mounting `/usr/local` to a directory on my SD card because my Chromebook has such a small hard drive. I decided to start fresh by running `dev_install --reinstall` as root and that gave me a working git which gave me the output of

```
chronos@localhost / $ /usr/local/libexec/git-core/git-remote-https
error: remote-curl: usage: git remote-curl <remote> [<url>]
```

However, now that I've run the Chromebrew installer after running `dev_install --reinstall`, I get this:

```
chronos@localhost / $ /usr/local/libexec/git-core/git-remote-https
bash: /usr/local/libexec/git-core/git-remote-https: Too many levels of symbolic links
```

Apparently symlinks and bind mounts don't play well together? This is how I'm doing the bind mount in `~/.bash_profile`:

```
SD_CARD_PATH=/media/removable/SD\ Card

sudo umount /usr/local &>/dev/null || true
sudo mount -o remount,rw,exec "${SD_CARD_PATH}"
sudo mount --rbind "${SD_CARD_PATH}/.local" /usr/local
sudo mount -o remount,rw,exec /usr/local
```

Is there any other way of getting Chromebrew to use the ample storage space on the SD card instead of the paltry amount of space on the Chromebook's hard drive?

**Comment by cparker15** [comment]
Peculiar. `dev_install --reinstall` doesn't work if `/usr/local` is bind-mounted, either. Definitely not a Chromebrew issue.

```
chronos@localhost / $ sudo dev_install --reinstall
INFO dev_install: [dev_install.cc(170)] To clean up, we will run:
  rm -rf /usr/local/
Any content you have stored in there will be deleted.
Remove all installed packages now? (y/N) y
INFO dev_install: [dev_install.cc(189)] Removed all installed packages.
INFO dev_install: [dev_install.cc(537)] Reinstalling dev state
ERROR dev_install: [dev_install.cc(223)] Creating /usr/local/usr/local failed: Too many levels of symbolic links (40)
```

**Comment by satmandu** [comment]
Is your SD card formatted as ext4?

**Comment by satmandu** [comment]
Symlinking to other filesystems after M90 is a mine field, owing to security Google has added by default (I think) using `nosymfollow`. (Hopefully, that hasn't hit you.)

Also, I'm not sure if dev_install will work to a bind mounted `/usr/local` - you may have to remove the bind mount, and rsync after the dev_install finishes, and then do the bind mount.

Same goes for the chromebrew install...

**Comment by cparker15** [comment]
That was it! I modified `~/.bash_profile` to account for `nosymfollow` and now everything is working as expected.

```
SD_CARD_PATH=/media/removable/SD\ Card

sudo umount /usr/local &>/dev/null || true
sudo mount -o remount,rw,exec,symfollow "${SD_CARD_PATH}"
sudo mount --rbind "${SD_CARD_PATH}/.local" /usr/local
sudo mount -o remount,rw,exec,symfollow /usr/local
```

Thank you, @satmandu!
