### ISSUE TITLE
Inkscape cannot be installed or built

### ISSUE THREAD

**Issue by q4z1** [skycocker/chromebrew#5966]
## Description
Installation of inkscape fails due to imagemagick6 & imagemagick7 dependency, which cannot be installed together.
Removing the imagemagick6 dep succeeds with installation but then libgsl.so.23 is not found which seems to be outdated since libgsl.so.25 is installed.
Building results in the glibc 2.32 issue mentioned in #5936 

If you executed a specific command:
```shell
crew install inkscape
---
inkscape
---
crew build inkscape
```
Output:
```shell
install:

The following packages also need to be installed: 
imagemagick6 
Do you agree? [Y/n] Y
Proceeding...
imagemagick6: Use ImageMagick to create, edit, compose, or convert bitmap images.
Precompiled binary available, downloading...
########################################################################################## 100.0%
Imagemagick6 archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
ImageMagick version 7.0.11-2 already installed.
---

running after installation without imemageick6:

inkscape: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
---

build:

/usr/local/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/local/bin/ld: cannot find crti.o: No such file or directory

```

## Versions and system information
chromebrew: `crew --version`
1.12

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7487557
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={0C1E39B7-DAE6-4972-8004-E96F60D9342C}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={0C1E39B7-DAE6-4972-8004-E96F60D9342C}
CHROMEOS_RELEASE_BOARD=fizz-signed-mp-v13keys
CHROMEOS_RELEASE_BRANCH_NUMBER=39
CHROMEOS_RELEASE_BUILDER_PATH=fizz-release/R92-13982.39.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.39.0 (Official Build) beta-channel fizz 
CHROMEOS_RELEASE_KEYSET=mp-v13
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.39.0
DEVICETYPE=CHROMEBOX
GOOGLE_RELEASE=13982.39.0

Model: Asus Chromebox i7

Architecture: `uname -m`
x86_64

**Comment by satmandu** [comment]
You're on M92/Beta. 

Building on M92 won't work until https://github.com/skycocker/chromebrew/pull/5941 is merged.

**Comment by satmandu** [comment]
Beta channel isn't supported yet.

If you want to test a fix which should fix compiling on beta channel, try this:
```CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING=1 CREW_TESTING_BRANCH=glibc_2.32-1 crew update ; crew reinstall glibc ; crew update```

Then try: `crew build inkscape`

That should get farther!

**Comment by q4z1** [comment]
Thank you very much. I forgot about the fact, that I'm on beta channel with this device. It's building now.

I will propably fork this repo and provide the adapted .rb file if I get inkscape up and running.
