### ISSUE TITLE
Setting up a real time community platform?

### ISSUE THREAD

**Issue by ntchambers** [skycocker/chromebrew#597]
I know that the title sounded a little buzzword-y, but I couldn't think of a better way to define what I'm talking about. I know this is a somewhat small project, compared to many other package managers, but would it be beneficial to have something like a community gitter, or an IRC channel? I see quite a few advantages of this. For example, #596  could theoretically get a much faster response, for a simple solution. It would also be a good place to discuss potential new packages, and the likelihood of someone using a package.

**Comment by Borealis023** [comment]
Not exactly a real time community, but a subreddit would be good just for Chromebrew and Chromebrew-related projects (i.e. #545)
