### ISSUE TITLE
JSON:ParserError during install

### ISSUE THREAD

**Issue by sguy311** [skycocker/chromebrew#5984]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
During install, and after when using crew install, I get the following error:
/usr/local/lib64/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at '' (JSON::ParserError)
        from /usr/local/lib64/ruby/3.0.0/json/common.rb:216:in `parse'
        from /usr/local/bin/crew:128:in `<main>'
If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`
1.12.0
ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE
Google Chromebook 2013
Architecture: `uname -m`
x86_64
## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by satmandu** [comment]
Hmmm. I'm seeing this too.

**Comment by uberhacker** [comment]
@sguy311: Please provide the output from `cat /etc/lsb-release`.

**Comment by satmandu** [comment]
I'm actually no longer seeing this any more. Please try an install again?

**Comment by saltedcoffii** [comment]
I'm not seeing this either. @sguy311 please let us know if you see this, if not, we can close the issue.

**Comment by satmandu** [comment]
No update, closing issue.
