### ISSUE TITLE
[fontconfig] Binary compiled with glibc 2.28?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6000]
```
$ codium
/usr/local/VSCodium-linux-arm/bin/../codium: /usr/local/lib/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/libfontconfig.so.1)
```

**Comment by satmandu** [comment]
What does `/usr/local/lib/libc.so.6` give you?

**Comment by satmandu** [comment]
It's possible that maybe this got built on a aarch64/glibc 2.32 container. That would explain this message.

Do you want to rebuild fontconfig for armv7l when you get a chance? Or I can... (I have fresh containers as of yesterday.)

**Comment by satmandu** [comment]
(But when stable moves to M92/ glibc 2.32 in days... this won't be an issue.)

**Comment by uberhacker** [comment]
You are making my life miserable. :)  We can't have the wrong build environments for generating binaries.  I'm losing faith in the Docker solution.  I've mentioned it before but there is no substitute for building on actual Chromebook hardware devices.  At a minimum, we should be at least testing on hardware before merging into master.

**Comment by satmandu** [comment]
mea culpa...
