### ISSUE TITLE
after installing perl_io_socket_ssl, seems not available to Perl :IO::Socket::SSL  

### ISSUE THREAD

**Issue by apple-corps** [skycocker/chromebrew#6019]
crew install perl_io_socket_ssl
perl_io_socket_ssl: IO::Socket::SSL - SSL sockets with IO::Socket interface
https://metacpan.org/pod/IO::Socket::SSL
Version: 2.068-1
License: GPL-1+ or Artistic
Performing pre-flight checks...
Package perl_io_socket_ssl already installed, skipping...
Performing post-install for perl_io_socket_ssl...
Perl_io_socket_ssl installed!

chronos@localhost /usr/local/kde/kdesrc-build $ ./kdesrc-build knotifications
kdesrc-build requires some minimal support to operate, including support
from the Perl runtime that kdesrc-build is built upon.

Some mandatory Perl modules are missing, and kdesrc-build cannot operate
without them.  Please ensure these modules are installed and available to Perl:

        IO::Socket::SSL

kdesrc-build can do this for you on many distros:
Run 'kdesrc-build --initial-setup'

kdesrc-build can do this for you on many distros:
Run 'kdesrc-build --initial-setup'

**Comment by drocsid** [comment]
perl_io_socket_ssl depends on Net::SSLeay , and it's not quite clear how you built that module without providing Net::SSLeay .

**Comment by drocsid** [comment]
Workaround by installing via cpan. Need to set perl configuration to build under /usr/local/ to use shared objects. It would probably be good to configure cpan package this way by default.

**Comment by drocsid** [comment]
One option might be to remove the perl package. Configure cpan as suggested, and let users install perl modules. Why does a broken module need to be provided?

**Comment by satmandu** [comment]
Would you mind seeing if dropping these into `/usr/local/lib/crew/packages` and then running `crew update compatible ; crew install perl_net_ssleay perl_mozilla_ca ; crew upgrade perl_io_socket_ssl` 
to see if that solves your issue?

`perl_net_ssleay.rb`
```
require 'package'

class Perl_net_ssleay < Package
  description 'Perl extension for using OpenSSL'
  homepage 'https://search.cpan.org/dist/Net-SSLeay/'
  version '1.90'
  license 'BSD'
  compatibility 'all'
  source_url "https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-#{version}.tar.gz"
  source_sha256 'f8696cfaca98234679efeedc288a9398fcf77176f1f515dbc589ada7c650dc93'

  binary_url({
    x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_net_ssleay/1.90_x86_64/perl_net_ssleay-1.90-chromeos-x86_64.tpxz'
  })
  binary_sha256({
    x86_64: '65271f786fbf6480fea9b9e95e05d15227add6cb418e1dae9ba97bfe7e35424e'
  })

  def self.build
    system "yes | perl Makefile.PL PREFIX=#{CREW_PREFIX} DESTDIR=#{CREW_DEST_DIR}"
    system 'make'
  end

  def self.install
    system 'make', 'install'
  end
end
```
`perl_mozilla_ca.rb`
```
require 'package'

class Perl_mozilla_ca < Package
  description 'Mozilla CA cert bundle in PEM format'
  homepage 'https://metacpan.org/release/Mozilla-CA'
  version '20200520'
  license 'GPL2'
  compatibility 'all'
  source_url "https://search.cpan.org/CPAN/authors/id/A/AB/ABH/Mozilla-CA-#{version}.tar.gz"
  source_sha256 'b3ca0002310bf24a16c0d5920bdea97a2f46e77e7be3e7377e850d033387c726'

  binary_url({
    x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_mozilla_ca/20200520_x86_64/perl_mozilla_ca-20200520-chromeos-x86_64.tpxz'
  })
  binary_sha256({
    x86_64: '1a34e9effb91e7814ca05fed4622461ea9af1c6917a6dc82dc0d407deeca2e9a'
  })

  def self.build
    system "yes | perl Makefile.PL PREFIX=#{CREW_PREFIX} DESTDIR=#{CREW_DEST_DIR}"
    system 'make'
  end

  def self.install
    system 'make', 'install'
  end
end
```
`perl_io_socket_ssl.rb`
```
require 'package'

class Perl_io_socket_ssl < Package
  description 'IO::Socket::SSL - SSL sockets with IO::Socket interface'
  homepage 'https://metacpan.org/pod/IO::Socket::SSL'
  version '2.071'
  license 'GPL-1+ or Artistic'
  compatibility 'all'
  source_url 'https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.071.tar.gz'
  source_sha256 '40da40948ecc9c787ed39c95715872679eebfd54243721174993a2003e32ab0a'

  binary_url({
    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_io_socket_ssl/2.068-1_armv7l/perl_io_socket_ssl-2.068-1-chromeos-armv7l.tar.xz',
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_io_socket_ssl/2.068-1_armv7l/perl_io_socket_ssl-2.068-1-chromeos-armv7l.tar.xz',
       i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_io_socket_ssl/2.068-1_i686/perl_io_socket_ssl-2.068-1-chromeos-i686.tar.xz',
    x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/perl_io_socket_ssl/2.071_x86_64/perl_io_socket_ssl-2.071-chromeos-x86_64.tpxz'
  })
  binary_sha256({
    aarch64: '8c2230feb2b7205349703e5b5b5b10e9f21f3ce079e5b6036728c33ee91a1ff6',
     armv7l: '8c2230feb2b7205349703e5b5b5b10e9f21f3ce079e5b6036728c33ee91a1ff6',
       i686: '24df6cac573463073b723da4b9b1a65380e2cdd67a053aabb9e61491410960c7',
    x86_64: 'edb13970364eda495488af15f78716f4959fa907645574667ef9dddf5e3281cf'
  })

  depends_on 'perl_net_ssleay'
  depends_on 'perl_mozilla_ca'

  def self.build
    system "yes | perl Makefile.PL PREFIX=#{CREW_PREFIX} DESTDIR=#{CREW_DEST_DIR}"
    system 'make'
  end

  def self.install
    system 'make', 'install'
  end
end
```

**Comment by drocsid** [comment]
@satmandu just seeing this now. 


i'm curious why you need a package and furthermore if required why you can't rely on cpan to install the module from your packaging wrapper, since the cpan variant worked. 

But I can test if you would still like me to. But I do notice the mention to update the OpenSSL perl modules.

**Comment by satmandu** [comment]
I think the rationale for packaging perl modules is the same as for packaging python modules, and is shared by many distributions (Debian, Arch, etc) as a way to be independent of a separate packaging system.

Having said that, @saltedcoffii did a lot of the groundwork with some of Chromebrew's recent python packaging, and maybe you can engage with her on the pros and cons of doing such as opposed to depending upon perl or python's own standalone module packaging/repository functionality.

**Comment by drocsid** [comment]
@satmandu @saltedcoffii if IE cpan , etc can provide working modules, wouldn't it make more sense to focus on packages that can't be provided elsewhere first and foremost? There's plenty of work to do there: #6053
