### ISSUE TITLE
broken crew after libressl upgrade to 1.1.1i

### ISSUE THREAD

**Issue by leoplo** [skycocker/chromebrew#6029]
## Before you submit an issue
Similar to https://github.com/skycocker/chromebrew/issues/4424

## Description
Once I upgraded libressl I was not able to run any crew command anymore.

If you executed a specific command:
```shell
crew upgrade libressl
crew --version
```

Output:
```shell
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib64/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libssl.so.47: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)
```

## Versions and system information
chromebrew: `crew --version`
cannot tell anymore

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_RELEASE_BUILD_NUMBER=12607

Model: Acer Chromebook 14

Architecture: `uname -m`
x86_64

## Additional information
I guess running `cd /usr/lib64 && ln -s libssl.so.1.0.0 libssl.so.47` would have normally fix this but sadly I am running a read-only file system.
```shell
chronos@localhost /usr/lib64 $ ln -s libssl.so.1.0.0 libssl.so.47
ln: failed to create symbolic link 'libssl.so.47': Read-only file system
```

**Comment by supechicken** [comment]
Could you try the following:
```
crew reinstall -s ruby
```
(all of our packages are using OpenSSL instead of Libressl now, a rebuild of ruby might fix it)

**Comment by satmandu** [comment]
Your install is borked because libressl has been replaced by openssl, and ruby depends upon openssl. Running `crew` as @supechicken suggests won't work because it depends upon a working ruby.

The easiest way to get back to a working install would be to just run the chromebrew  installer again.

I would suggest this: 
```
export OLDPACKAGES=$(jq -r '.installed_packages | .[].name' /usr/local/etc/crew/device.json) 
curl -Ls git.io/vddgY | bash
crew reinstall $OLDPACKAGES
```

**Comment by leoplo** [comment]
I confirm @supechicken 's way was not working. 

> Your install is borked because libressl has been replaced by openssl, and ruby depends upon openssl. Running `crew` as @supechicken suggests won't work because it depends upon a working ruby.
> 
> The easiest way to get back to a working install would be to just run the chromebrew installer again.
> 
> I would suggest this:
> 
> ```
> export CREW_CACHE_ENABLED=1 
> export OLDPACKAGES=$(jq -r '.installed_packages | .[].name' /usr/local/etc/crew/device.json) 
> curl -Ls git.io/vddgY | bash
> crew reinstall $OLDPACKAGES
> ```

I reinstalled my ChromeOS (because it is a read-only file system I had no files saved on it). Every works fine with a fresh new crew and all updated packages but I can't confirm if @satmandu commands would have solved it sorry.

**Comment by satmandu** [comment]
Glad you are back up!
