### ISSUE TITLE
QT5 base package with broken headers : /usr/local/lib/libQt5Core.so.5: undefined symbol: u_strToUpper_68

### ISSUE THREAD

**Issue by drocsid** [skycocker/chromebrew#6053]
/usr/local/lib/libQt5Core.so.5: undefined symbol: u_strToUpper_68
see http://ix.io/3uDy

**Comment by satmandu** [comment]
Looks ike this is going to need a rebuild... using the kde tree at https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15 ... Trying a build now...
