### ISSUE TITLE
`has_key` method not found

### ISSUE THREAD

**Issue by gjrtimmer** [skycocker/chromebrew#6061]
## Description
Failure to install packages on fresh install of Chromum OS of CloudReady.

If you executed a specific command:
```shell
crew install buildessential
```

Output:
```shell
chronos@localhost / $ crew install buildessential
buildessential: A collection of tools essential to compile and build software.

Version: 1.18
License: GPL-3+
The following packages also need to be installed: 
crew_profile_base gcc_tools make pkgconfig bison patch attr util_macros valgrind compressdoc help2man xmlcatmgr bash jdk8 libgpgerror perl_locale_messages perl_text_unidecode perl_unicode_eastasianwidth samurai rdfind symlinks ucl core binutils glibc flex m4 gettext gnutls libunistring nettle openssl libtasn1 p11kit libunbound groff krb5 less libarchive libcyrussasl libmetalink libssp libtirpc libxml2 manpages most openldap perl xzutils py3_pip python3 sqlite py3_wheel python2 unzip gcc11 mpc mpfr linuxheaders automake autoconf diffutils intltool libtool perl_xml_parser sed acl doxygen gtk_doc docbook_xml docbook_xml412 docbook_xml42 docbook_xml43 docbook_xml44 docbook_xml45 docbook_xml50 docbook_xml51 docbook_xsl docbook_xsl_nons fop itstool py3_libxml2 libxslt libgcrypt texinfo cmake llvm meson ninja upx mandb 
Do you agree? [Y/n] 
Proceeding...
crew_profile_base: Crew-profile-base sets up Chromebrew's environment capabilities.
/usr/local/lib/crew/lib/package.rb:44:in `get_url': undefined method `has_key?' for "SKIP":String (NoMethodError)
        from /usr/local/bin/crew:613:in `download'
        from /usr/local/bin/crew:1185:in `install'
        from /usr/local/bin/crew:1165:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1162:in `each'
        from /usr/local/bin/crew:1162:in `resolve_dependencies'
        from /usr/local/bin/crew:1053:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1425:in `block in install_command'
        from /usr/local/bin/crew:1420:in `each'
        from /usr/local/bin/crew:1420:in `install_command'
        from /usr/local/bin/crew:1514:in `<main>'
chronos@localhost / $
```

## Versions and system information
chromebrew: 1.16.2

ChromeOS:
CHROMEOS_RELEASE_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_BOARD_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=OTHER
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
GOOGLE_RELEASE=89.4.44
CHROMEOS_RELEASE_BUILD_NUMBER=13729
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_CHROME_MILESTONE=89
CHROMEOS_RELEASE_PATCH_NUMBER=2021_06_04_2041
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=89.4.44
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_DESCRIPTION=89.4.44 (Developer Build - neverware) stable-channel chromeover64

Model: MacBook Pro 4,1

Architecture: x86_64

## Additional information

What I think needs to be done:
Current unknown

**Comment by ironmanisdead** [comment]
Do you think I could replace 'has_key?' with 'in' on my existing installation, to make it work?

**Comment by satmandu** [comment]
Fix incoming!

**Comment by gjrtimmer** [comment]
@satmandu Thanks, will await the fix, currently just installed CloudReady Chrome OS, and working on getting my fans fixed, so I'm going to try to add some kernel drivers to chromebrew

**Comment by uberhacker** [comment]
@gjrtimmer:  Kernel drivers?  Do tell more.

**Comment by gjrtimmer** [comment]
@satmandu Can corfirm that currently its installing buildessential on my ld MacBook Pro 4,1; always fun to bring old hardwar back to life.

@uberhacker | fresh install of CloudReady Chrome OS running on a MacBook Pro 4,1 (Late 2008) problem however is the fans, so I need to incorporate the correct drivers and fan control into chromebrew, what I'm working on right now is this fix, so that I can continue building the required libraries.

## End Goal
The end goal is to have a user install CloudReady Chrome OS on old hardware, then install chromebrew, and then give the command for install macbook fan control and the fans will return of automatic mode, instead of lingering at 100% because of the default boot mode. this will give the ability to combine an easy to install Chromium OS on old Mac hardware and bring it back to life with the use of chromebrew
