### ISSUE TITLE
[gtk3] Conflict with gtk2

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6070]
When building gtk3 from source with gtk2 installed, I get the following:
```
Checking for FHS3 compliance...
Checking for conflicts with files from installed packages...
Exiting due to above errors.
Error: There is a conflict with the same file in another package.

gtk2 package conflicts below:
/usr/local/bin/gtk-update-icon-cache
```
How should we handle this conflict?  Does it make sense to rename to `gtk2-update-icon-cache`?

**Comment by satmandu** [comment]
Sure, and then make a symlink to /usr/local/bin/gtk-update-icon-cache if /usr/local/bin/gtk-update-icon-cache doesn't exist in the postinstall, which can be overwritten if gtk3 gets installed.
