### ISSUE TITLE
vulkan not installing

### ISSUE THREAD

**Issue by iknoors** [skycocker/chromebrew#6082]
whenever i try to install anything it fails because of this:
Performing install...
vulkan_icd_loader: Vulkan Installable Client Driver ICD Loader
Precompiled binary available, downloading...
######################################################################################################################################################################## 100.0%
Checksum mismatch. 😔 Try again.
Can Anyone help me?

**Comment by satmandu** [comment]
There's a vulkan driver update in the pipeline in https://github.com/skycocker/chromebrew/pull/6033

Try this:
```
CREW_TESTING=1 \
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew \
CREW_TESTING_BRANCH=mesa_21.2 \
crew update ; yes | crew upgrade vulkan_headers vulkan_icd_loader
```

**Comment by iknoors** [comment]
Thanks for your help! :)

**Comment by iknoors** [comment]
can you also make snapd for cros?

**Comment by satmandu** [comment]
> @skycocker can you also make snapd for cros?

Open a separate package request for snapd.

I suspect that might be difficult, because that may require kernel patching.

But we have made progress with getting flatpak to work.

**Comment by iknoors** [comment]
thx fir your help again
