### ISSUE TITLE
Accessing to apps installed via Chromebrew.

### ISSUE THREAD

**Issue by tomas-wrobel** [skycocker/chromebrew#6085]
Maybe I don't understand what chromebrew is (I think package manager like APT) but if I succesfully installed Atom, can I just run it, somehow? It does not show in launcher and I didn't find any command which can execute app.

**Comment by tomas-wrobel** [comment]
OK, I figured out there is a command `atom` but when running, there is an error:
```
/usr/local/share/atom/atom: error while loading shared libraries: libcom_err.so.3: cannot open shared object file: No such file or directory
```

**Comment by satmandu** [comment]
Run `crew install libcom_err` .
