### ISSUE TITLE
Skype not launching

### ISSUE THREAD

**Issue by iknoors** [skycocker/chromebrew#6094]
Hello. I am here with an issue (again)
so when i installed "skype" i ran into a error when trying to run skype
OS: chromeos brunch-sebanc
I have  a question, does any video call apps such as skype support camera ?

**Comment by iknoors** [comment]
I have another issue, whenever i launch any apps they give this error and dont launch:
ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists

Note that the directory 

'/usr/local/var/lib/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

bwrap: Can't find source path /tmp/.X11-unix/X0: No such file or directory

**Comment by iknoors** [comment]
Can anyone help?

**Comment by supechicken** [comment]
About the Skype launch issue, could you try the following:
```shell
export GDK_BACKEND=x11
startsommelier
skypeforlinux
```

**Comment by supechicken** [comment]
> I have a question, does any video call apps such as skype support camera ?

Yes, but it depends on your chromebook (it works if your webcam is supported natively by Linux kernel)

**Comment by saltedcoffii** [comment]
#7127
