### ISSUE TITLE
Uninstall a package with its unique dependencies (or an `apt autoremove` equivalent)

### ISSUE THREAD

**Issue by RJVB** [skycocker/chromebrew#6105]
I haven't found if this is possible:

- to uninstall a package with all dependencies not needed by any other package (like `port uninstall foo --follow-dependencies`)
- uninstall all packages that were pulled in automatically and are no longer required by any other package

I don't think I'd have to explain why those are very appreciable options. So much so in fact that I have to assume I overlooked them in the current implementation ... did I?!

**Comment by saltedcoffii** [comment]
Duplicate to #4572, closing
