### ISSUE TITLE
[sommelier]: Failed to start (missing `llvm` dependency)

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#6108]
```
$ cat /usr/local/var/log/sommelier.log 
MESA-LOADER: failed to open crocus: libLLVM-12.so: cannot open shared object file: No such file or directory (search paths /usr/local/lib64/dri, suffix _dri)
failed to load driver: crocus
...snip...
error: couldn't get display device
```
Fixed after installing `llvm`

**Comment by satmandu** [comment]
Same problem as with gcc. We just need a way of installing just the libraries of both without the entire compiler collection installed.

**Comment by satmandu** [comment]
Add `#{CREW_LIB_PREFIX}/libLLVM-12.so` to `CREW_ESSENTIAL_FILES` and this problem sort of goes away if you delete llvm after installing mesa...
