### ISSUE TITLE
App Request

### ISSUE THREAD

**Issue by krome-3k** [skycocker/chromebrew#6116]
Hi,
I was told on your discord to make app requests here. Please add virt-manager and all video editors possible(avidemux, kdenlive, openshot, shotcut) for ARM64/AARCH64. My device is the Acer Spin 311 with the Mediatek MT8183C cpu if it helps.
Thank you in advance.

Edit : Please add meson, ninja and their dependencies for ARM64. 
Edit : Please add xorg-xhost for ARM64.

**Comment by saltedcoffii** [comment]
Please split each app request into different issues, thank you!
