### ISSUE TITLE
Checksum mismatch :/ try again

### ISSUE THREAD

**Issue by thedogb** [skycocker/chromebrew#612]
just as #93, i get same problem with vim again.
when i run 'crew install vim' ,i returns error information as fellow:
Found vim, version 8.0
Following packages also need to be installed:
glibc223 binutils gmp mpfr mpc isl cloog glibc gcc make linuxheaders pkgconfig buildessential readline zlibpkg perl libsigsegv diffutils ncursesw bz2 ncurses openssl python27 ruby
Do you agree? [Y/n]

Proceeding...
Found glibc223, version 2.23
Package glibc223 already installed, skipping...
Found binutils, version 2.25-1
Package binutils already installed, skipping...
Found gmp, version 6.1.2
Package gmp already installed, skipping...
Found mpfr, version 3.1.5
Package mpfr already installed, skipping...
Found mpc, version 1.0.3
Package mpc already installed, skipping...
Found isl, version 0.14.1
Package isl already installed, skipping...
Found cloog, version 0.18.4
Package cloog already installed, skipping...
Found glibc, version 1.0
Package glibc already installed, skipping...
Found gcc, version 4.9.x
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.18
Package linuxheaders already installed, skipping...
Found pkgconfig, version 0.29.1
Package pkgconfig already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.3
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found perl, version 5.24.1
Package perl already installed, skipping...
Found libsigsegv, version 2.11
Package libsigsegv already installed, skipping...
Found diffutils, version 3.5
Package diffutils already installed, skipping...
Found ncursesw, version 6.0
Package ncursesw already installed, skipping...
Found bz2, version 1.4.17
Package bz2 already installed, skipping...
Found ncurses, version 6.0-1
Package ncurses already installed, skipping...
Found openssl, version 1.0.2k
Package openssl already installed, skipping...
Found python27, version 2.7.13
Package python27 already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Package ruby already installed, skipping...
Found vim, version 8.0
No precompiled binary available for your platform, downloading source...
--2017-04-26 08:22:31-- ftp://ftp.vim.org/pub/vim/unix/vim-8.0.tar.bz2
=> 'vim-8.0.tar.bz2'
Resolving ftp.vim.org... 145.220.21.40
Connecting to ftp.vim.org|145.220.21.40|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done. ==> PWD ... done.
==> TYPE I ... done. ==> CWD (1) /pub/vim/unix ... done.
==> SIZE vim-8.0.tar.bz2 ... 10866752
==> PASV ... done. ==> RETR vim-8.0.tar.bz2 ... done.
Length: 10866752 (10M) (unauthoritative)

vim-8.0.tar.bz2 100%[======================================================================>] 10.36M 63.9KB/s in 1m 53s

2017-04-26 08:24:33 (93.9 KB/s) - 'vim-8.0.tar.bz2' saved [10866752]

Checksum mismatch :/ try again

and i try running 'crew update' and it return

From https://github.com/skycocker/chromebrew

branch master -> FETCH_HEAD
HEAD is now at 3282ab3 Merge pull request #570 from ntchambers/master
Package lists, crew, and library updated.
Checking for package updates...
Your software is up to date

then i run 'crew upgrade' , and it return

Your software is already up to date.

and now i don't know what shall i do

**Comment by thedogb** [comment]
my chromebook is asus c201

**Comment by thedogb** [comment]
and it exits same problem with jdk8.
Found jdk8, version 8u112
Found jdk8, version 8u112
Precompiled binary available, downloading...
--2017-04-28 08:49:32--  https://www.dropbox.com/s/vcejuitboafaxib/jdk8u22-armv7l.tar.gz
Resolving www.dropbox.com... 37.61.54.158
Connecting to www.dropbox.com|37.61.54.158|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.dropboxusercontent.com/content_link/YiOsFMzcpxX7qUSVGI6NZaC6xSf9BjtmMfvblSfMyeurb7pKZEXew9GaLQr43Z2x/file [following]
--2017-04-28 08:49:33--  https://dl.dropboxusercontent.com/content_link/YiOsFMzcpxX7qUSVGI6NZaC6xSf9BjtmMfvblSfMyeurb7pKZEXew9GaLQr43Z2x/file
Resolving dl.dropboxusercontent.com... 93.46.8.89
Connecting to dl.dropboxusercontent.com|93.46.8.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61006623 (58M) [application/octet-stream]
Saving to: 'jdk8u22-armv7l.tar.gz'

jdk8u22-armv7l.tar.gz                 100%[======================================================================>]  58.18M  1.60MB/s    in 36s     

2017-04-28 08:50:10 (1.64 MB/s) - 'jdk8u22-armv7l.tar.gz' saved [61006623/61006623]

Checksum mismatch :/ try again

**Comment by kirbyfan64** [comment]
FWIW the JDK one is now a 404.

**Comment by ntchambers** [comment]
This is fixed in #613. If you want it before my commits gets merged, you can pull the vim.rb from my pull request.
