### ISSUE TITLE
kvm and wine packages?

### ISSUE THREAD

**Issue by mjonsson1986** [skycocker/chromebrew#6128]
i dont remember if kvm and wine are in chromebrew repo?## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by satmandu** [comment]
Wine: https://github.com/skycocker/chromebrew/blob/master/packages/wine.rb
kvm: no.
