### ISSUE TITLE
Add aarch64 firefox 

### ISSUE THREAD

**Issue by linusrg1** [skycocker/chromebrew#6149]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.
I am unable to install aarch64 firefox on an arm chromebook, would it be possible to add this package into chromebrew
If you executed a specific command:
```shell
crew install firefox
```

Output:
```shell
Package firefox is not compatible with your device architecture (aarch64
```

## Versions and system information
chromebrew: `crew --version`
1.16.5
ChromeOS: `cat /etc/lsb-release`
chrome os 92 stable
Model: YOUR MODEL HERE
idea pad duet
Architecture: `uname -m`
aarch64
## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
It would be nice if you could add aarch64 firefox to the repo as I can instaljl it via linux mode, but it would run alot better on my machine if I could get it through crew.

**Comment by satmandu** [comment]
Note that you would need an `armv7l` version, since the userland on ChromeOS arm devices is not `aarch64`...

**Comment by linusrg1** [comment]
> Note that you would need an `armv7l` version, since the userland on ChromeOS arm devices is not `aarch64`...

ok sry I jsut assumed it would be aarch64 as thats what the error was about.

**Comment by satmandu** [comment]
No worries. The problem is that there isn't a prebuilt binary for armv7l and we're just using the prebuilt binaries of firefox.

You can use aarch64 installs of firefox within crostini though, since AFAIK that is a aarch64 VM.

Does that work for you?
