### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by Vannrith** [skycocker/chromebrew#615]
Hi, thanks for your work, Chromebrew.
this is not an error or issue ..
I just have a question. How can I install Apache and full lamp stack?
I found nginx and php7, but still not enough, I want Apache and mysql as well.
thanks again :)

**Comment by ntchambers** [comment]
I am working on mysql right now for #211. I'll add apache to the list.

**Comment by Vannrith** [comment]
i'd love to know when it's ready.
thanks so much

**Comment by ntchambers** [comment]
I was able to get apache built (I'll submit a PR later tonight), but I'm still having trouble with mysql/mariadb, so that will have to come at a later time

**Comment by Vannrith** [comment]
it's near ^^

**Comment by thedamian** [comment]
@Vannrith httpd added in https://github.com/skycocker/chromebrew/pull/618

**Comment by Vannrith** [comment]
thanks so much

**Comment by dihuta** [comment]
@ntchambers 
Any update on MySQL?
Thank you.

**Comment by flyingP0tat0** [comment]
@dihuta Working on it, but will take some time. Please use the open MySQL issue for that.

**Comment by hutzlibu** [comment]
I installed apache ... but how do I start it? (And how to auto-start it with login?)
Also in general, where do packages get installed to?

**Comment by uberhacker** [comment]
Hey @hutzlibu: All great questions and we should definitely do a better job of documenting this.  PRs are certainly welcome.
How do I start it?
```
$ sudo /usr/local/apache2/bin/apachectl start
```
How do auto-start it with login?
```
$ echo 'sudo /usr/local/apache2/bin/apachectl start' >> ~/.bashrc
```
Where do packages get installed to?  Usually the files of most packages are installed in a subdirectory of `/usr/local` which is the default prefix for most configure scripts.  In the case of httpd, it is installed in `/usr/local/apache2`.  Other things worth mentioned about httpd:
How do I stop the server?
```
$ sudo /usr/local/apache2/bin/apachectl stop
```
Where is the document root?
```
/usr/local/apache2/htdocs
```
How do I view files served by Apache?
```
Visit localhost or 127.0.0.1 in your browser
```

**Comment by hutzlibu** [comment]
Thanks a lot for the detailed answer.
I think this belongs into Wikipage, no?
I will try to create a PR (never done that before)

**Comment by uberhacker** [comment]
We could create a wiki page or it might even be a good idea to create something like README.md and add it to the package.
