### ISSUE TITLE
ruby_latest package: broken RubyGems due to incorrect owner/permissions

### ISSUE THREAD

**Issue by lucaspetter** [skycocker/chromebrew#616]
After installing `ruby_latest`, RubyGems is broken. For example, you can no longer install new gems:
```
chronos@localhost / $ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/lib/ruby/gems/2.4.0 directory.
```
If you try installing gems with `sudo`, it throws another error about a read-only file system:
```
chronos@localhost / $ sudo gem install bundler
ERROR:  While executing gem ... (Errno::EROFS)
    Read-only file system @ dir_s_mkdir - /root/.gem
```

The issue seems to be that the gem folder `/usr/local/lib/ruby/gems/2.4.0` is owned by `root`. For comparison, the `/usr/local/lib/ruby/gems/2.0.0` gem folder is owned by the `chronos` user; it's used by the regular `ruby` package, not `ruby_latest`, and it doesn't have this issue.

I had to run `sudo chown -R chronos: /usr/local/lib/ruby/gems/2.4.0` to fix this and make RubyGems work again.

**Comment by thedamian** [comment]
I'll try this at home.

anyone else having this problem? Can you install gems and which version of ruby do you have installed?

**Comment by jam7** [comment]
No, I don't have this problem.  Recently, we modify crew to not use sudo, so it won't happen anymore anyway.

**Comment by lucaspetter** [comment]
@jam7 Which version of ruby are you using? Is it the `ruby` or `ruby_latest` package, or the default ruby that gets installed by `install.sh`?

As far as crew not using sudo anymore, I'm not sure if that's quite what this issue is about. The issue I'm having here is that, regardless of `crew` or `sudo crew` usage, there is a permissions problem on the folder `/usr/local/lib/ruby/gems/2.4.0` that happens during installation of `ruby_latest`. Because of that problem, you can't install new RubyGems unless you change the folder's owner and permissions.

I don't know if this is a bug on Chromebrew's end or Ruby's end. Maybe we should add a command to the end of the `ruby_latest.rb` recipe to fix the permissions.

**Comment by jam7** [comment]
@lucaspetter I tried ruby_latest without any errors like below.
```
$ crew install ruby_latest
...
$ ls -l /usr/local/lib/ruby/gem
total 4
drwxr-xr-x. 8 chronos chronos 4096 Jun 23 23:32 2.4.0
```

Crew doesn't sudo anymore.  Also, gem doesn't work with sudo.  On the other hand, in order to create directory owned by root, we need privilege like sudo.  Therefore, I think it's not a crew problem nor gem problem.

You can check it by performing something like below:
```
$ crew remove ruby
$ crew remove ruby_latest
$ rm -rf /usr/local/lib/ruby
$ wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
$ crew install ruby_latest
```

**Comment by uberhacker** [comment]
Should we have the same permission checks here as the `node` and `node_latest` packages?  Everyone needs to resist using `sudo` on anything going forward. ;)

**Comment by lucaspetter** [comment]
@jam7 Thank you for your input. I uninstalled crew and all gems and then re-installed crew and ruby_latest without using sudo. Now the permissions are correct and there are no issues when I try to install gems. Maybe I'd been doing `sudo crew install ruby_latest` before by mistake, but I can't remember. Anyway, I'm closing this issue.

```
$ sudo rm -rf /usr/local/*
$ wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
$ crew install ruby_latest
$ gem install bundler
```
