### ISSUE TITLE
aarch64 native compiler

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#617]
I'd like to add aarch64 native compiler instead of using armv7l compiler.  Can someone tell me about aarch64 chromebook please?  I'd like to know the results of following commands.

1. `ls /usr`
1. `ls /etc/ssl`
1. `ls /usr/lib`
1. `ls /usr/lib64`

**Comment by jam7** [comment]
Can someone who own samsong plus show results of above commands?

**Comment by ksunden** [comment]
Acer R13:

$ ls /usr
bin  include  lib  libexec  local  sbin  share
$ ls /etc/ssl
blacklist  certs  misc  openssl.cnf  private  rsyslog
$ ls /usr/lib
alsa-lib                                   libfdisk.so.1.1.0                libnl-route-3.so
avahi                                      libfdt-1.4.1.so                  libnl-route-3.so.200
avfs                                       libfdt.so                        libnl-route-3.so.200.19.0
bluetooth                                  libfdt.so.1                      libnl.so
cairo                                      libffi-3.1                       libnl.so.1
cmake                                      libffi.so                        libnl.so.1.1
connectivity-common.sh                     libffi.so.6                      libnsl.so
conntrack-tools                            libffi.so.6.0.2                  libnspr4.so
crda                                       libfmap.so                       libnspr4.so.0d
dbus-1.0                                   libfmap.so.0                     libnss3.so
dri                                        libfmap.so.0.0.0                 libnss3.so.1d
e2initrd_helper                            libfontconfig.so                 libnssckbi.so
ecryptfs                                   libfontconfig.so.1               libnssdbm3.chk
elfutils                                   libfontconfig.so.1.8.0           libnssdbm3.so
engines                                    libfontembed.so                  libnss_dns.so
gcc                                        libfontembed.so.1                libnss_files.so
gconv                                      libfontembed.so.1.0.0            libnsssysinit.so
ghostscript                                libform.so                       libnssutil3.so
gio                                        libform.so.5                     libntfs-3g.so
glib-2.0                                   libform.so.5.9                   libntfs-3g.so.83
ipsec                                      libfreebl3.chk                   libntfs-3g.so.83.0.0
libacl.so                                  libfreebl3.so                    libp11.so
libanl.so                                  libfreetype.so                   libp11.so.2
libasm-0.166.so                            libfreetype.so.6                 libp11.so.2.2.0
libasm.so                                  libfreetype.so.6.12.6            libpamc.so
libasm.so.1                                libfuse.so                       libpam_misc.so
libasound.so                               libfuse.so.2                     libpam.so
libasound.so.2                             libfuse.so.2.8.6                 libpanel.so
libasound.so.2.0.0                         libgbm.so                        libpanel.so.5
libatk-1.0.so                              libgbm.so.1                      libpanel.so.5.9
libatk-1.0.so.0                            libgcc_s.so                      libpango-1.0.so
libatk-1.0.so.0.3209.1                     libgcc_s.so.1                    libpango-1.0.so.0
libattr.so                                 libgcrypt.so                     libpango-1.0.so.0.3200.5
libavahi-client.so                         libgcrypt.so.20                  libpangocairo-1.0.so
libavahi-client.so.3                       libgcrypt.so.20.0.3              libpangocairo-1.0.so.0
libavahi-client.so.3.2.9                   libgestures.so                   libpangocairo-1.0.so.0.3200.5
libavahi-common.so                         libgestures.so.0                 libpangoft2-1.0.so
libavahi-common.so.3                       libgio-2.0.so                    libpangoft2-1.0.so.0
libavahi-common.so.3.5.3                   libgio-2.0.so.0                  libpangoft2-1.0.so.0.3200.5
libavahi-core.so                           libgio-2.0.so.0.3400.3           libpaper.so
libavahi-core.so.7                         libglapi.so                      libpaper.so.1
libavahi-core.so.7.0.2                     libglapi.so.0                    libpaper.so.1.1.2
libavahi-glib.so                           libglapi.so.0.0.0                libpcap.so
libavahi-glib.so.1                         libGLESv2.so                     libpcap.so.1
libavahi-glib.so.1.0.2                     libGLESv2.so.1.6.3859696         libpcap.so.1.5.3
libavahi-gobject.so                        libGLESv2.so.2                   libpci.so
libavahi-gobject.so.0                      libglib-2.0.so                   libpci.so.3
libavahi-gobject.so.0.0.4                  libglib-2.0.so.0                 libpci.so.3.4.1
libavfs.so                                 libglib-2.0.so.0.3400.3          libpcrecpp.so
libavfs.so.0                               libglslcompiler.so               libpcrecpp.so.0
libavfs.so.0.0.2                           libglslcompiler.so.1.6.3859696   libpcrecpp.so.0.0.1
libbase-395517.so                          libgmodule-2.0.so                libpcreposix.so
libbase-core-395517.so                     libgmodule-2.0.so.0              libpcreposix.so.0
libbase-crypto-395517.so                   libgmodule-2.0.so.0.3400.3       libpcreposix.so.0.0.3
libbase-dbus-395517.so                     libgmp.so                        libpcre.so
libbase-dl-395517.so                       libgmp.so.10                     libpixman-1.so
libbase-policy-395517.so                   libgmp.so.10.3.0                 libpixman-1.so.0
libbase-sandbox-395517.so                  libgnutls-extra.so               libpixman-1.so.0.32.4
libbase-timers-395517.so                   libgnutls-extra.so.26            libpkcs11-helper.so
libblkid.so                                libgnutls-extra.so.26.22.6       libpkcs11-helper.so.1
libbluetooth.so                            libgnutls-openssl.so             libpkcs11-helper.so.1.0.0
libbluetooth.so.3                          libgnutls-openssl.so.27          libplc4.so
libbluetooth.so.3.18.13                    libgnutls-openssl.so.27.0.0      libplc4.so.0d
libbootstat.so                             libgnutls.so                     libplds4.so
libbrillo-395517.so                        libgnutls.so.26                  libplds4.so.0d
libbrillo-core-395517.so                   libgnutls.so.26.22.6             libpng16.so
libbrillo-cryptohome-395517.so             libgobject-2.0.so                libpng16.so.16
libbrillo-glib-395517.so                   libgobject-2.0.so.0              libpng16.so.16.25.0
libbrillo-http-395517.so                   libgobject-2.0.so.0.3400.3       libpng.so
libbrillo-minijail-395517.so               libgpg-error.so                  libpolicy-395517.so
libbrillo-streams-395517.so                libgpg-error.so.0                libpoppler-cpp.so
libbrlapi.so                               libgpg-error.so.0.10.0           libpoppler-cpp.so.0
libbz2.so                                  libgs.so                         libpoppler-cpp.so.0.2.1
libcairo-gobject.so                        libgs.so.9                       libpoppler-glib.so
libcairo-gobject.so.2                      libgs.so.9.19                    libpoppler-glib.so.8
libcairo-gobject.so.2.11200.12             libgthread-2.0.so                libpoppler-glib.so.8.7.0
libcairo-script-interpreter.so             libgthread-2.0.so.0              libpoppler.so
libcairo-script-interpreter.so.2           libgthread-2.0.so.0.3400.3       libpoppler.so.52
libcairo-script-interpreter.so.2.11200.12  libgudev-1.0.so                  libpoppler.so.52.0.0
libcairo.so                                libgudev-1.0.so.0                libprocps.so
libcairo.so.2                              libgudev-1.0.so.0.2.0            libprotobuf-lite.so
libcairo.so.2.11200.12                     libharfbuzz.so                   libprotobuf-lite.so.9
libcap.so                                  libharfbuzz.so.0                 libprotobuf-lite.so.9.0.1
libcares.so                                libharfbuzz.so.0.10302.0         libprotobuf.so
libcares.so.2                              libhistory.so                    libprotobuf.so.9
libcares.so.2.2.0                          libhogweed.so                    libprotobuf.so.9.0.1
libchaps.so                                libhogweed.so.2                  libpthread.so
libchromeos-ui-395517.so                   libhogweed.so.2.5                libpvr_dri_support.so
libcidn.so                                 libijs-0.35.so                   libqpdf.so
libcom_err.so                              libijs.so                        libqpdf.so.13
libconfig.so                               libiniparser.so                  libqpdf.so.13.1.2
libconfig++.so                             libiniparser.so.0                libreadline.so
libconfig.so.9                             libiniparser.so.0.0.0            libresolv.so
libconfig++.so.9                           libinstallattributes-395517.so   librootdev.so
libconfig.so.9.2.0                         libip4tc.so                      librootdev.so.1
libconfig++.so.9.2.0                       libip6tc.so                      librootdev.so.1.0
libcras.so                                 libiptc.so                       librt.so
libcras.so.0                               libjbig2dec.so                   libsbc.so
libcras.so.0.0.0                           libjbig2dec.so.0                 libsbc.so.1
libcros_config.so                          libjbig2dec.so.0.0.0             libsbc.so.1.2.1
libcrypto.so                               libjpeg.so                       libscrypt-1.1.6.so
libcrypto.so.1.0.0                         libjpeg.so.62                    libscrypt.so
libcrypt.so                                libjpeg.so.62.1.0                libselinux.so
libc.so                                    libjq.so                         libsepol.so
libcupscgi.so                              libjq.so.1                       libshill-net-395517.so
libcupscgi.so.1                            libjq.so.1.0.4                   libsmartcols.so
libcupsfilters.so                          libjsoncpp.so                    libsmime3.so
libcupsfilters.so.1                        libjsoncpp.so.0                  libsnappy.so
libcupsfilters.so.1.0.0                    libjsoncpp.so.0.6.0              libsnappy.so.1
libcupsimage.so                            libkeyutils.so                   libsnappy.so.1.1.2
libcupsimage.so.2                          libkmod.so                       libsoftokn3.chk
libcupsmime.so                             libkms.so                        libsoftokn3.so
libcupsmime.so.1                           libkms.so.1                      libspeexdsp.so
libcupsppdc.so                             libkms.so.1.0.0                  libspeexdsp.so.1
libcupsppdc.so.1                           liblcms2.so                      libspeexdsp.so.1.5.0
libcups.so                                 liblcms2.so.2                    libspeex.so
libcups.so.2                               liblcms2.so.2.0.6                libspeex.so.1
libcurl.so                                 libleveldb.so                    libspeex.so.1.5.0
libcurl.so.4                               libleveldb.so.1                  libsqlite3.so
libcurl.so.4.4.0                           libleveldb.so.1.18               libsqlite3.so.0
libcurses.so                               liblogging-stdlog.so             libsqlite3.so.0.8.6
libdaemon.so                               liblogging-stdlog.so.0           libsrv_um.so
libdaemon.so.0                             liblogging-stdlog.so.0.0.0       libsrv_um.so.1.6.3859696
libdaemon.so.0.5.0                         liblzma.so                       libssl3.so
libdbm.so                                  liblzo2.so                       libssl.so
libdbm.so.1.6.3859696                      liblzo2.so.2                     libssl.so.1.0.0
libdbus-1.so                               liblzo2.so.2.0.0                 libss.so
libdbus-1.so.3                             libmbim-glib.so                  libstdc++.so
libdbus-1.so.3.7.12                        libmbim-glib.so.4                libstdc++.so.6
libdbus-c++-1.so                           libmbim-glib.so.4.1.0            libstdc++.so.6.0.20
libdbus-c++-1.so.0                         libmemenv.so                     libtasn1.so
libdbus-c++-1.so.0.0.0                     libmemenv.so.1                   libtasn1.so.3
libdbus-glib-1.so                          libmemenv.so.1.18                libtasn1.so.3.1.7
libdbus-glib-1.so.2                        libmenu.so                       libthread_db.so
libdbus-glib-1.so.2.2.2                    libmenu.so.5                     libtlsdate_compat.so
libdevmapper.so                            libmenu.so.5.9                   libtlsdate_compat.so.0
libdl.so                                   libmetrics-395517.so             libtlsdate_compat.so.0.0.0
libdrm_mediatek.so                         libminigbm.so.1.0.0              libtsm.so
libdrm_mediatek.so.1                       libmm-glib.so                    libtsm.so.3
libdrm_mediatek.so.1.0.0                   libmm-glib.so.0                  libtsm.so.3.0.0
libdrm.so                                  libmm-glib.so.0.2.0              libtspi.so
libdrm.so.2                                libmnl.so                        libtspi.so.1
libdrm.so.2.4.0                            libmount.so                      libtspi.so.1.2.0
libdw-0.166.so                             libm.so                          libturbojpeg.so
libdw.so                                   libmtp.so                        libturbojpeg.so.0
libdw.so.1                                 libmtp.so.9                      libturbojpeg.so.0.1.0
libe2p.so                                  libmtp.so.9.3.0                  libudev.so
libeasy-unlock-crypto.so                   libncurses.so                    libulockmgr.so
libecryptfs.so                             libndp.so                        libulockmgr.so.1
libecryptfs.so.0                           libndp.so.0                      libulockmgr.so.1.0.1
libecryptfs.so.0.0.0                       libndp.so.0.1.0                  libunrar.so
libEGL.so                                  libnetfilter_conntrack.so        libunrar.so.4
libEGL.so.1                                libnetfilter_conntrack.so.3      libunrar.so.4.2.4
libEGL.so.1.0.0                            libnetfilter_conntrack.so.3.6.0  libusb-1.0.so
libelf-0.166.so                            libnetfilter_cthelper.so         libusb.so
libelf.so                                  libnetfilter_cthelper.so.0       libusc.so
libelf.so.1                                libnetfilter_cthelper.so.0.0.0   libusc.so.1.6.3859696
libestr.so                                 libnetfilter_cttimeout.so        libutil.so
libestr.so.0                               libnetfilter_cttimeout.so.1      libuuid.so
libestr.so.0.0.0                           libnetfilter_cttimeout.so.1.0.0  libxkbcommon.so
libevdev_hollow.so                         libnetfilter_queue.so            libxkbcommon.so.0
libevdev_hollow.so.0                       libnetfilter_queue.so.1          libxkbcommon.so.0.0.0
libevdev.so                                libnetfilter_queue.so.1.3.0      libxml2.so
libevdev.so.0                              libnettle.so                     libxml2.so.2
libevdi.so                                 libnettle.so.4                   libxml2.so.2.9.4
libevent-2.0.so.5                          libnettle.so.4.7                 libxtables.so
libevent-2.0.so.5.1.9                      libnfnetlink.so                  libz.so
libevent_core-2.0.so.5                     libnfnetlink.so.0                locale
libevent_core-2.0.so.5.1.9                 libnfnetlink.so.0.2.0            misc
libevent_core.so                           libnih-dbus.so                   modem-common.sh
libevent_extra-2.0.so.5                    libnih.so                        ModemManager
libevent_extra-2.0.so.5.1.9                libnl-3.so                       opengl
libevent_extra.so                          libnl-3.so.200                   openvpn
libevent.so                                libnl-3.so.200.19.0              pango
libexpat.so                                libnl-genl-3.so                  pm-utils
libexpat.so.1                              libnl-genl-3.so.200              pppd
libexpat.so.1.6.0                          libnl-genl-3.so.200.19.0         rsyslog
libext2fs.so                               libnl-idiag-3.so                 shill
libfastjson.so                             libnl-idiag-3.so.200             sudo
libfastjson.so.4                           libnl-idiag-3.so.200.19.0        terminfo
libfastjson.so.4.0.0                       libnl-nf-3.so                    xml2Conf.sh
libfdisk.so                                libnl-nf-3.so.200                xtables
libfdisk.so.1                              libnl-nf-3.so.200.19.0
$ ls /usr/lib64
ls: cannot access /usr/lib64: No such file or directory

**Comment by awafaa** [comment]
Samsung Plus:

$ ls /usr/
bin  include  lib  libexec  local  sbin  share

$ ls /etc/ssl/
blacklist  certs  misc  openssl.cnf  private  rsyslog

$ ls /usr/lib/
alsa-lib
avahi
avfs
bluetooth
cairo
cmake
connectivity-common.sh
conntrack-tools
crda
dbus-1.0
e2initrd_helper
ecryptfs
elfutils
engines
gcc
gconv
ghostscript
gio
glib-2.0
ipsec
libacl.so
libanl.so
libasm-0.166.so
libasm.so
libasm.so.1
libasound.so
libasound.so.2
libasound.so.2.0.0
libatk-1.0.so
libatk-1.0.so.0
libatk-1.0.so.0.3209.1
libattr.so
libavahi-client.so
libavahi-client.so.3
libavahi-client.so.3.2.9
libavahi-common.so
libavahi-common.so.3
libavahi-common.so.3.5.3
libavahi-core.so
libavahi-core.so.7
libavahi-core.so.7.0.2
libavahi-glib.so
libavahi-glib.so.1
libavahi-glib.so.1.0.2
libavahi-gobject.so
libavahi-gobject.so.0
libavahi-gobject.so.0.0.4
libavfs.so
libavfs.so.0
libavfs.so.0.0.2
libbase-395517.so
libbase-core-395517.so
libbase-crypto-395517.so
libbase-dbus-395517.so
libbase-dl-395517.so
libbase-policy-395517.so
libbase-sandbox-395517.so
libbase-timers-395517.so
libblkid.so
libbluetooth.so
libbluetooth.so.3
libbluetooth.so.3.18.13
libbootstat.so
libbrillo-395517.so
libbrillo-core-395517.so
libbrillo-cryptohome-395517.so
libbrillo-glib-395517.so
libbrillo-http-395517.so
libbrillo-minijail-395517.so
libbrillo-streams-395517.so
libbrlapi.so
libbz2.so
libcairo-gobject.so
libcairo-gobject.so.2
libcairo-gobject.so.2.11200.12
libcairo-script-interpreter.so
libcairo-script-interpreter.so.2
libcairo-script-interpreter.so.2.11200.12
libcairo.so
libcairo.so.2
libcairo.so.2.11200.12
libcap.so
libcares.so
libcares.so.2
libcares.so.2.2.0
libchaps.so
libchromeos-ui-395517.so
libcidn.so
libcom_err.so
libconfig.so
libconfig++.so
libconfig.so.9
libconfig++.so.9
libconfig.so.9.2.0
libconfig++.so.9.2.0
libconfuse.so
libconfuse.so.0
libconfuse.so.0.0.0
libcras.so
libcras.so.0
libcras.so.0.0.0
libcros_config.so
libcrypto.so
libcrypto.so.1.0.0
libcrypt.so
libc.so
libcupscgi.so
libcupscgi.so.1
libcupsfilters.so
libcupsfilters.so.1
libcupsfilters.so.1.0.0
libcupsimage.so
libcupsimage.so.2
libcupsmime.so
libcupsmime.so.1
libcupsppdc.so
libcupsppdc.so.1
libcups.so
libcups.so.2
libcurl.so
libcurl.so.4
libcurl.so.4.4.0
libcurses.so
libdaemon.so
libdaemon.so.0
libdaemon.so.0.5.0
libdbus-1.so
libdbus-1.so.3
libdbus-1.so.3.7.12
libdbus-c++-1.so
libdbus-c++-1.so.0
libdbus-c++-1.so.0.0.0
libdbus-glib-1.so
libdbus-glib-1.so.2
libdbus-glib-1.so.2.2.2
libdevmapper.so
libdl.so
libdrm_rockchip.so
libdrm_rockchip.so.1
libdrm_rockchip.so.1.0.0
libdrm.so
libdrm.so.2
libdrm.so.2.4.0
libdvbv5.so
libdvbv5.so.0
libdvbv5.so.0.0.0
libdw-0.166.so
libdw.so
libdw.so.1
libe2p.so
libeasy-unlock-crypto.so
libecryptfs.so
libecryptfs.so.0
libecryptfs.so.0.0.0
libEGL.so
libEGL.so.1
libEGL.so.1.1.20
libelf-0.166.so
libelf.so
libelf.so.1
libestr.so
libestr.so.0
libestr.so.0.0.0
libevdev_hollow.so
libevdev_hollow.so.0
libevdev.so
libevdev.so.0
libevdi.so
libevent-2.0.so.5
libevent-2.0.so.5.1.9
libevent_core-2.0.so.5
libevent_core-2.0.so.5.1.9
libevent_core.so
libevent_extra-2.0.so.5
libevent_extra-2.0.so.5.1.9
libevent_extra.so
libevent.so
libexpat.so
libexpat.so.1
libexpat.so.1.6.0
libext2fs.so
libfastjson.so
libfastjson.so.4
libfastjson.so.4.0.0
libfdisk.so
libfdisk.so.1
libfdisk.so.1.1.0
libfdt-1.4.1.so
libfdt.so
libfdt.so.1
libffi-3.1
libffi.so
libffi.so.6
libffi.so.6.0.2
libfmap.so
libfmap.so.0
libfmap.so.0.0.0
libfontconfig.so
libfontconfig.so.1
libfontconfig.so.1.8.0
libfontembed.so
libfontembed.so.1
libfontembed.so.1.0.0
libform.so
libform.so.5
libform.so.5.9
libfreebl3.chk
libfreebl3.so
libfreetype.so
libfreetype.so.6
libfreetype.so.6.12.6
libftdi1.so
libftdi1.so.2
libftdi1.so.2.0.0
libfuse.so
libfuse.so.2
libfuse.so.2.8.6
libgbm.so
libgbm.so.1
libgcc_s.so
libgcc_s.so.1
libgcrypt.so
libgcrypt.so.20
libgcrypt.so.20.0.3
libgestures.so
libgestures.so.0
libgio-2.0.so
libgio-2.0.so.0
libgio-2.0.so.0.3400.3
libGLESv1_CM.so
libGLESv1_CM.so.1
libGLESv1_CM.so.1.1.20
libGLESv2.so
libGLESv2.so.2
libGLESv2.so.2.1.20
libglib-2.0.so
libglib-2.0.so.0
libglib-2.0.so.0.3400.3
libgmodule-2.0.so
libgmodule-2.0.so.0
libgmodule-2.0.so.0.3400.3
libgmp.so
libgmp.so.10
libgmp.so.10.3.0
libgnutls-extra.so
libgnutls-extra.so.26
libgnutls-extra.so.26.22.6
libgnutls-openssl.so
libgnutls-openssl.so.27
libgnutls-openssl.so.27.0.0
libgnutls.so
libgnutls.so.26
libgnutls.so.26.22.6
libgobject-2.0.so
libgobject-2.0.so.0
libgobject-2.0.so.0.3400.3
libgpg-error.so
libgpg-error.so.0
libgpg-error.so.0.10.0
libgs.so
libgs.so.9
libgs.so.9.19
libgthread-2.0.so
libgthread-2.0.so.0
libgthread-2.0.so.0.3400.3
libgudev-1.0.so
libgudev-1.0.so.0
libgudev-1.0.so.0.2.0
libharfbuzz.so
libharfbuzz.so.0
libharfbuzz.so.0.10302.0
libhistory.so
libhogweed.so
libhogweed.so.2
libhogweed.so.2.5
libijs-0.35.so
libijs.so
libiniparser.so
libiniparser.so.0
libiniparser.so.0.0.0
libinstallattributes-395517.so
libip4tc.so
libip6tc.so
libiptc.so
libjbig2dec.so
libjbig2dec.so.0
libjbig2dec.so.0.0.0
libjpeg.so
libjpeg.so.62
libjpeg.so.62.1.0
libjq.so
libjq.so.1
libjq.so.1.0.4
libjsoncpp.so
libjsoncpp.so.0
libjsoncpp.so.0.6.0
libkeyutils.so
libkmod.so
libkms.so
libkms.so.1
libkms.so.1.0.0
liblcms2.so
liblcms2.so.2
liblcms2.so.2.0.6
libleveldb.so
libleveldb.so.1
libleveldb.so.1.18
liblogging-stdlog.so
liblogging-stdlog.so.0
liblogging-stdlog.so.0.0.0
liblzma.so
liblzo2.so
liblzo2.so.2
liblzo2.so.2.0.0
libmali.so
libmali.so.0
libmali.so.0.1.20
libmbim-glib.so
libmbim-glib.so.4
libmbim-glib.so.4.1.0
libmemenv.so
libmemenv.so.1
libmemenv.so.1.18
libmenu.so
libmenu.so.5
libmenu.so.5.9
libmetrics-395517.so
libminigbm.so.1.0.0
libmm-glib.so
libmm-glib.so.0
libmm-glib.so.0.2.0
libmnl.so
libmount.so
libm.so
libmtp.so
libmtp.so.9
libmtp.so.9.3.0
libncurses.so
libndp.so
libndp.so.0
libndp.so.0.1.0
libnetfilter_conntrack.so
libnetfilter_conntrack.so.3
libnetfilter_conntrack.so.3.6.0
libnetfilter_cthelper.so
libnetfilter_cthelper.so.0
libnetfilter_cthelper.so.0.0.0
libnetfilter_cttimeout.so
libnetfilter_cttimeout.so.1
libnetfilter_cttimeout.so.1.0.0
libnetfilter_queue.so
libnetfilter_queue.so.1
libnetfilter_queue.so.1.3.0
libnettle.so
libnettle.so.4
libnettle.so.4.7
libnfnetlink.so
libnfnetlink.so.0
libnfnetlink.so.0.2.0
libnih-dbus.so
libnih.so
libnl-3.so
libnl-3.so.200
libnl-3.so.200.19.0
libnl-genl-3.so
libnl-genl-3.so.200
libnl-genl-3.so.200.19.0
libnl-idiag-3.so
libnl-idiag-3.so.200
libnl-idiag-3.so.200.19.0
libnl-nf-3.so
libnl-nf-3.so.200
libnl-nf-3.so.200.19.0
libnl-route-3.so
libnl-route-3.so.200
libnl-route-3.so.200.19.0
libnl.so
libnl.so.1
libnl.so.1.1
libnsl.so
libnspr4.so
libnspr4.so.0d
libnss3.so
libnss3.so.1d
libnssckbi.so
libnssdbm3.chk
libnssdbm3.so
libnss_dns.so
libnss_files.so
libnsssysinit.so
libnssutil3.so
libntfs-3g.so
libntfs-3g.so.83
libntfs-3g.so.83.0.0
libp11.so
libp11.so.2
libp11.so.2.2.0
libpamc.so
libpam_misc.so
libpam.so
libpanel.so
libpanel.so.5
libpanel.so.5.9
libpango-1.0.so
libpango-1.0.so.0
libpango-1.0.so.0.3200.5
libpangocairo-1.0.so
libpangocairo-1.0.so.0
libpangocairo-1.0.so.0.3200.5
libpangoft2-1.0.so
libpangoft2-1.0.so.0
libpangoft2-1.0.so.0.3200.5
libpaper.so
libpaper.so.1
libpaper.so.1.1.2
libpcap.so
libpcap.so.1
libpcap.so.1.5.3
libpci.so
libpci.so.3
libpci.so.3.4.1
libpcrecpp.so
libpcrecpp.so.0
libpcrecpp.so.0.0.1
libpcreposix.so
libpcreposix.so.0
libpcreposix.so.0.0.3
libpcre.so
libpixman-1.so
libpixman-1.so.0
libpixman-1.so.0.32.4
libpkcs11-helper.so
libpkcs11-helper.so.1
libpkcs11-helper.so.1.0.0
libplc4.so
libplc4.so.0d
libplds4.so
libplds4.so.0d
libpng16.so
libpng16.so.16
libpng16.so.16.25.0
libpng.so
libpolicy-395517.so
libpoppler-cpp.so
libpoppler-cpp.so.0
libpoppler-cpp.so.0.2.1
libpoppler-glib.so
libpoppler-glib.so.8
libpoppler-glib.so.8.7.0
libpoppler.so
libpoppler.so.52
libpoppler.so.52.0.0
libprocps.so
libprotobuf-lite.so
libprotobuf-lite.so.9
libprotobuf-lite.so.9.0.1
libprotobuf.so
libprotobuf.so.9
libprotobuf.so.9.0.1
libpthread.so
libqpdf.so
libqpdf.so.13
libqpdf.so.13.1.2
libreadline.so
libresolv.so
librootdev.so
librootdev.so.1
librootdev.so.1.0
librt.so
libsbc.so
libsbc.so.1
libsbc.so.1.2.1
libscrypt-1.1.6.so
libscrypt.so
libselinux.so
libsepol.so
libshill-net-395517.so
libsmartcols.so
libsmime3.so
libsnappy.so
libsnappy.so.1
libsnappy.so.1.1.2
libsoftokn3.chk
libsoftokn3.so
libspeexdsp.so
libspeexdsp.so.1
libspeexdsp.so.1.5.0
libspeex.so
libspeex.so.1
libspeex.so.1.5.0
libsqlite3.so
libsqlite3.so.0
libsqlite3.so.0.8.6
libssl3.so
libssl.so
libssl.so.1.0.0
libss.so
libstdc++.so
libstdc++.so.6
libstdc++.so.6.0.20
libtasn1.so
libtasn1.so.3
libtasn1.so.3.1.7
libthread_db.so
libtlsdate_compat.so
libtlsdate_compat.so.0
libtlsdate_compat.so.0.0.0
libtsm.so
libtsm.so.3
libtsm.so.3.0.0
libtspi.so
libtspi.so.1
libtspi.so.1.2.0
libturbojpeg.so
libturbojpeg.so.0
libturbojpeg.so.0.1.0
libudev.so
libulockmgr.so
libulockmgr.so.1
libulockmgr.so.1.0.1
libunrar.so
libunrar.so.4
libunrar.so.4.2.4
libusb-1.0.so
libusb.so
libutil.so
libuuid.so
libv4l
libv4l1.so
libv4l1.so.0
libv4l1.so.0.0.0
libv4l2rds.so
libv4l2rds.so.0
libv4l2rds.so.0.0.0
libv4l2.so
libv4l2.so.0
libv4l2.so.0.0.0
libv4lconvert.so
libv4lconvert.so.0
libv4lconvert.so.0.0.0
libxkbcommon.so
libxkbcommon.so.0
libxkbcommon.so.0.0.0
libxml2.so
libxml2.so.2
libxml2.so.2.9.4
libxtables.so
libz.so
locale
misc
modem-common.sh
ModemManager
openvpn
pango
pm-utils
pppd
rsyslog
shill
sudo
terminfo
xml2Conf.sh
xtables

$ ls /usr/lib64
ls: cannot access /usr/lib64: No such file or directory

**Comment by awafaa** [comment]
@jam7 would missing a native aarch64 compiler be the reason why I get the following when trying to upgrade or install a package?:
```bash
You don't have a working C compiler. Run 'crew install buildessential' to get one and try again.
```

**Comment by jam7** [comment]
@ksunden @awafaa Thanks.  Is it possible to show the result of following command also?
```
$ ls /lib/ld*
```
@awafaa Crew shows that message if `gcc --version` cause some errors.  Can you show the result of `gcc --version` also?  Thanks.

**Comment by awafaa** [comment]
@jam7 

$ ls /lib/ld*
/lib/ld-2.23.so  /lib/ld-linux-armhf.so.3

Hah, I know gcc is installed but I get ```bash: /usr/local/bin/gcc: No such file or directory```
Removing gcc and re-installing I see ```https://github.com/jam7/chrome-cross/releases/download/v1.2/gcc-4.9.x-cc1.2-chromeos-aarch64.tar.xz```

**Comment by jam7** [comment]
@awafaa Thank you for the info.  I was thinking it may uses /lib/ld-linux-aarch64.so.3 or something, but armhf.  It looks like there is no armv8 stuff yet.  Thanks.

BTW, I think you can compile any packages now since you have runnable gcc.  :)

**Comment by jam7** [comment]
I'm going to close this issue since it looks like it is not possible to privide armv8 native compilers to aarch64 environment yet.  Thanks.
