### ISSUE TITLE
Firefox will not install

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6176]
I tried installing Firefox on a freshly powerwashed chromebook using chromebrew. After installing all the dependencies, it fails at the end when installing the Firefox package.

Output:
```
Firefox archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
Rename all *.la_tmp files back to *.la
Checking for FHS3 compliance...
Error: /usr/local/firefox in firefox is not FHS3 compliant.
Checking for conflicts with files from installed packages...
Exiting due to above errors.
```
I tried googling and searching the git issues to see if this was a common problem, but I haven't found anyone who has run into it already.

Chromebrew version: 1.16.6

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R92-13982.88.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.88.0 (Official Build) stable-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.88.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13982.88.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by satmandu** [comment]
@uberhacker looks like we need a FHS3 opt-out for this package.
