### ISSUE TITLE
Firefox will not start: Cannot open display :0

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6189]
I installed firefox on a freshly powerwashed chromebook. When starting it, I receive the following error;

```
user@localhost / $ firefox
Error: cannot open display: :0
```
I cannot find anything similar to this, but I may have missed it.

Chromebrew version: 1.16.6

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R92-13982.88.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.88.0 (Official Build) stable-channel octopus
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.88.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13982.88.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by uberhacker** [comment]
@aghebert: Did you start the sommelier daemon?  If not, run `crew postinstall sommelier` and follow the instructions.

**Comment by aghebert** [comment]
> @aghebert: Did you start the sommelier daemon? If not, run `crew postinstall sommelier` and follow the instructions.

I missed that. I wonder what other postinstall messages I missed...
