### ISSUE TITLE
[Question] Cannot get browser.tabs.drawInTitlebar to work in Firefox

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6192]
I can't get browser.tabs.drawInTitlebar to work in firefox. The checkbox appears, but the titlebar does not go away. Is there a .desktop config I should be using to hide the sommelier titlebar? I have already tried adding 
```
env MOZ_USE_XINPUT2=1 MOZ_GTK_TITLEBAR_DECORATION=client /usr/local/firefox/firefox-bin %u
````
to the firefox .desktop file, but that also does not work.

Chromebrew version: 1.16.6

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R92-13982.88.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.88.0 (Official Build) stable-channel octopus
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.88.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13982.88.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by uberhacker** [comment]
@aghebert: Can you please attach a screenshot of what you are noticing?  I'll try to see if I can reproduce.

**Comment by aghebert** [comment]
Title bar enabled:
![Screenshot 2021-09-14 14 31 44](https://user-images.githubusercontent.com/30908336/133314082-09bfc51a-b1a9-40b0-926e-f8e8fecc0423.png)

Title bar disabled:
![Screenshot 2021-09-14 14 31 58](https://user-images.githubusercontent.com/30908336/133314042-e7c37c94-d549-4ef4-813a-2e9696c27c3e.png)
