### ISSUE TITLE
Receiving error after installing Flatpak

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6198]
After installing Flatpak, when I open a new terminal or source my .bashrc file, I recieve the following errors;

```
ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists
error: Unknown option --user

See '/usr/local/libexec/flatpak/flatpak --help'
```

I tried deleting the broken linked file, and the error didn't show the next time I opened a new terminal, but it came back after that and stayed.

I have little understanding of what the '---user' error is about, and am not sure if it is related.

I checked the `packages/flatpak.rb' file and it seems the '--user' issue might be related, as well as the broken linked file.

I cannot find a solution for this.

Chromebrew version: 1.16.6

ChromeOS:
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=88
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R92-13982.88.0
CHROMEOS_RELEASE_BUILD_NUMBER=13982
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=92
CHROMEOS_RELEASE_DESCRIPTION=13982.88.0 (Official Build) stable-channel octopus
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13982.88.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13982.88.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by satmandu** [comment]
I think this broke with M90's introduction of `nosymfollow`.

Any workaround for this will have to deal with that.

**Comment by aghebert** [comment]
In the meantime, is this something I could workaround by mounting whatever is affected without `nosymfollow`?

**Comment by satmandu** [comment]
You could try remounting the home partitions with `-o remount,symfollow` ...

**Comment by aghebert** [comment]
That worked. I used `sudo mount -o remount,rw,seclabel,nosuid,nodev,noexec,noatime,symfollow,resgid=20119,commit=600,data=ordered /home/chronos/user`
That got rid of the symlinking error.
Any insight for the `error: Unknown option --user` error?

**Comment by supechicken** [comment]
According to the `flatpak` wrapper:
https://github.com/skycocker/chromebrew/blob/691e2ff7d5d14355704dbb2291a54cecf0356de2/packages/flatpak.rb#L127-L132
The `--run` parameter will be added to the command always, however `flatpak` accept it only when install/uninstall acion

**Comment by aghebert** [comment]
> According to the `flatpak` wrapper:
> 
> https://github.com/skycocker/chromebrew/blob/691e2ff7d5d14355704dbb2291a54cecf0356de2/packages/flatpak.rb#L127-L132
> 
> The `--user` parameter will be added to the command always, however `flatpak` accept it only when install/uninstall action

Sorry, I'm only slightly more knowledgeable about BASH than a novice, so I dont understand what you're trying to tell me, nor the code you showed me.

**Comment by saltedcoffii** [comment]
the `--user` issue is a known bug that nobody's bothered to fix yet. If you want to run `/usr/local//libexec/flatpak/flatpak` to get to the actual flatpak binary for the time being, insteal of just `flatpak`, it should get you past the `--user` issue.

**Comment by saltedcoffii** [comment]
#7127
