### ISSUE TITLE
Cannot install scons

### ISSUE THREAD

**Issue by trebinor** [skycocker/chromebrew#620]
In trying to install subversion, it pulled in scons as a dependency.  scons cannot install because it tries to install to /usr/local, which is not writeable without sudo, which we are not supposed to use with crew.

```ruby
  def self.install
    system "python2.7 setup.py install --prefix=/usr/local"
  end
```

I notice most other other packages install using PREFIX=#{CREW_DEST_DIR}, so is scon's #install to /usr/local an oversight?

**Comment by jam7** [comment]
#621 will fix this problem.
