### ISSUE TITLE
error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by him5** [skycocker/chromebrew#6207]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.
(only found a closed issue that doesn't specify a solution)

## Description
I tried installing PHP w/ crew, but curl doesn't work anymore

If you executed a specific command:
crew install php
crew install {any package} or curl {options} {url}

Output:
`error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory`

## Versions and system information
chromebrew: `1.16.6`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7712471
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R96-14209.0.0
CHROMEOS_RELEASE_BUILD_NUMBER=14209
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=96
CHROMEOS_RELEASE_DESCRIPTION=14209.0.0 (Official Build) dev-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14209.0.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14209.0.0`

Model: hp 14a-na0031wm

Architecture: `x86_64`

**Comment by uberhacker** [comment]
Try `crew install libcurl` and attempt again.  This is likely an issue with the dependency resolver not installing packages in the correct order.

**Comment by him5** [comment]
i just removed libcurl and everything worked again

**Comment by him5** [comment]
curl: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory
new problem with new chromebrew installation

**Comment by ZZZXXX0110** [comment]
> curl: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory new problem with new chromebrew installation

I'm having this exactly problem too when trying to update my Crouton installation after upgrading to Chrome OS 98.

**Comment by uberhacker** [comment]
@ZZZXXX0110:  We don't support Crouton.  I would highly recommend you use either Crouton or Chromebrew but not both.  That said, what brought me to this project was my frustration with Crouton.
