### ISSUE TITLE
[Suggestion] Add mesa patch for nyan boards

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [skycocker/chromebrew#6218]
There are a few chromebooks using the nyan board, and until just recently I have been searching for a way to get hardware acceleration working on them. I recently came across https://github.com/hexdump0815/linux-mainline-tegra-k1-kernel/issues/4; which features a relatively new patch that makes mesa/opengl/glamor work _at all_ on these boards.

The patch is just a hack in it's current state, and there are still some issues, but it's better then nothing at all.

I know the nyan boards are no longer offically supported, but adding the patch wouldn't cause any issues, and I have confirmed proof that it does infact fix the issue.

The proposed patch is found below
> https://github.com/hexdump0815/mesa-etc-build/blob/master/tegra-hack.patch

Additionally a issue was opened on the official freedesktop mesa repo
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/3505

---

Adding the patch alone wouldn't be enough to get hardware acceleration with sommelier fully working, but it would bring us a lot closer. With some work to make sommelier use the nouveau drive with glamor, (and possibly an updated kernel) it might work.

But I still see no reason to not add this patch, as it would not cause any issues, and only improve support and usability of the Nyan boards.

**Comment by satmandu** [comment]
Do any other arm64 boards use the nouveau driver? I'd be happy to add it to the mesa build for arm64, so long as it doesn't break anything.
