### ISSUE TITLE
can't install mongodb

### ISSUE THREAD

**Issue by brucem1976** [skycocker/chromebrew#622]
Pkgconfig installed!
Found buildessential, version 1.0
Buildessential installed!
Found mongodb, version 3.0.8
No precompiled binary available for your platform, downloading source...
/usr/local/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        from /usr/local/bin/crew:172:in `download'
        from /usr/local/bin/crew:353:in `install'
        from /usr/local/bin/crew:267:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:458:in `<main>'

**Comment by jam7** [comment]
The reason of this probelm is mongodb is not prepared for arm7l or aarch64.  It is for only i686 and x86_64.  When this mongodb.rb is merged, chromebrew supports only i686 and x86_64.  If someone prepare mongodb.rb for building from source codes, it will solve this problem.

Also better error message will be appreciated.

**Comment by brucem1976** [comment]
Thanks - I can compile and install Mongo db on same machine in Ubuntu with
apt-get, so it should be possible.

**Comment by jam7** [comment]
Yes, it's possible.  I meant we didn't prepare mongodb for arm7l nor aarch64 for chromebrew.

**Comment by lyxell** [comment]
@thedamian This issue is not solved. Please, do not close issues if you're unsure about whether they are solved or not.

**Comment by flyingP0tat0** [comment]
`apt-get` does not compile anything. It provides prebuilt binaries, otherwise installing packages would take way longer.
I think we should just add a build from source to the package.

**Comment by jam7** [comment]
Close in favor of #933.

**Comment by Ieathan** [comment]
Am I wrong in assuming this allows us to install mongodb on a pixelbook?

When I run `crew install mongodb` I get

```
Creating 'build/opt/mongo/config.h'
/usr/local/bin/python src/mongo/db/auth/generate_action_types.py src/mongo/db/auth/action_types.txt build/opt/mongo/db/auth/action_type.h build/opt/mongo/db/auth/action_type.cpp
/usr/local/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
scons: *** [build/opt/mongo/base/error_codes.h] Error 127
scons: *** [build/opt/mongo/db/auth/action_type.h] Error 127
scons: building terminated because of errors.
mongodb failed to install: `scons -j4 install --ssl --prefix=/usr/local/tmp/crew/dest/usr/local --use-new-tools` exited with 2
```

**Comment by uberhacker** [comment]
@leathan: From the error message, it appears python is not installed.  What is the output of `crew search python`?

**Comment by Ieathan** [comment]
I did a blind google and found a stack exchange answer that has nothing to do with my problem and i changed the answer a bit and ran this command: `sudo ln -s /usr/local/lib64/libpython2.7.so.1.0 /usr/lib64/libpython2.7.so.1.0`

and now I think its working.

I have no idea what I did but python2.7 was for sure installed before because i could enter the python `>>>` prompt.

**Comment by ileathan** [comment]
For the record the above command solved the problem yet again.

From my google pixelbook.
