### ISSUE TITLE
Failed to execute install.sh, failed to install chromebrew

### ISSUE THREAD

**Issue by jidro** [skycocker/chromebrew#6267]
## Description
An error was reported when executing `Downloading Bootstrap packages`
```shell
basename:extra operand'from' 
Try 'basename --help' for more information
```

Did not execute any specific commands , only the following commands were executed:
```shell
bash ./install.sh
```

No errors were reported before, until the following output is displayed , Output:
```shell
Downloading Bootstrap packages……

basename:extra operand'from' 
Try 'basename --help' for more information
```

## Versions and system information

ChromeOS: `cat /etc/lsb-release`
```shell
Chromium OS
```

Model: RedmiBook 14 II

Architecture: `uname -m`
```shell
x86_64
```

---

**Comment by satmandu** [comment]
How have you installed ChromeOS on this device?
