### ISSUE TITLE
Packages that need updates => easy <=

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6268]
The packages below do not require binaries so bumping the version and changing the source (listed) + hash (sha256sum [source]) should be all that is necessary to update.
- [ ] acli | https://github.com/acquia/cli/archive/refs/tags/1.15.0.tar.gz | 1.14.0 | 1.15.0
- [ ] flutter | https://github.com/flutter/flutter/archive/refs/tags/2.5.2.tar.gz | 2.5.1 | 2.5.2
- [ ] github_desktop | https://github.com/shiftkey/desktop/archive//refs/tags/release-2.9.3-linux2.tar.gz | 2.9.0-RC4 | 2.9.3
- [ ] hugo | https://github.com/gohugoio/hugo/archive//refs/tags/v0.88.1.tar.gz | 0.82.1 | 0.88.1
- [ ] idea | https://download.jetbrains.com/idea/ideaIC-2021.2.2.tar.gz | 2021.1.2 | 2021.2.2
- [ ] julia | https://github.com/JuliaLang/julia/archive/refs/tags/v1.6.3.tar.gz | 1.3.1 | 1.6.3
- [ ] kr | https://github.com/kryptco/kr/archive/refs/tags/2.4.15.tar.gz | 2.4.4 | 2.4.15
- [ ] leiningen | https://github.com/technomancy/leiningen/archive/refs/tags/2.9.7.tar.gz | 2.9.1 | 2.9.7
- [ ] mutagen | https://github.com/mutagen-io/mutagen/releases/download/v0.11.8/mutagen_linux_amd64_v0.11.8.tar.gz | 0.11.5 | 0.11.8
- [ ] netbeans | https://downloads.apache.org/netbeans/netbeans/12.5/netbeans-12.5-bin.zip | 12.0-1 | 12.5
- [ ] newsboat | https://github.com/newsboat/newsboat/archive/refs/tags/r2.25.tar.gz | 2.23 | 2.25
- [ ] oc | https://github.com/openshift/origin/archive/refs/tags/v4.1.0.tar.gz | 3.11.0 | 4.1.0
- [ ] peazip | https://github.com/peazip/PeaZip/archive//refs/tags/8.2.0.tar.gz | 7.6.0 | 8.2.0
- [ ] platformsh | https://github.com/platformsh/platformsh-cli/archive/refs/tags/v3.70.0.tar.gz | 3.65.2 | 3.70.0
- [ ] powershell | https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/powershell-7.1.4-linux-x64.tar.gz | 7.0.3 | 7.1.4
- [ ] sublime_text | https://download.sublimetext.com/sublime_text_build_4113_x64.tar.xz | 3.2.2 | 4113
- [ ] symfony | https://github.com/symfony/cli/archive//refs/tags/v4.26.6.tar.gz | 4.23.5 | 4.26.6
- [ ] uwsgi | https://github.com/unbit/uwsgi/archive/refs/tags/2.0.19.1.tar.gz | 2.0.17 | 2.0.19.1
- [ ] v2ray | https://github.com/v2ray/v2ray-core/archive//refs/tags/v4.31.0.tar.gz | 4.24.2 | 4.31.0
- [ ] wp_cli | https://github.com/wp-cli/wp-cli/archive/refs/tags/v2.5.0.tar.gz | 2.4.0 | 2.5.0
- [ ] yarn | https://github.com/yarnpkg/yarn/archive/refs/tags/v1.22.15.tar.gz | 1.22.10 | 1.22.15

**Comment by uberhacker** [comment]
For those who have never done this, the steps to update are outlined below:

1. Fork this repo (link located in the top right corner of this screen).
2. Clone your forked repo locally: `git clone https://github.com/yourname/chromebrew.git`.  Replace yourname with your repo.
3. Change to the packages directory: `cd chromebrew/packages`.
4. Click on the link of the package you wish to update above (this will download to your ~/Downloads folder).
5. From your shell session in crosh, execute `sha256sum ~/Downloads/file.tar.gz` where file.tar.gz is the downloaded file.
6. Copy the hash to your clipboard by highlighting and then hit enter.
7. Edit the package file package.rb from the name above (replace package with the actual name).
8. Replace the source_url with the link and source_sha256 with the hash you copied earlier.
9. Remember to bump the version to match.
10. Save the file.
11. Create a working branch: `git checkout -b update-package`
12. Add and commit the package `git add package.rb && git commit -m 'Update package to version #.#'`
13. Push up to your repo with `git push origin update-package`
14. Submit a pull request to the master branch with a short description of the update.

**Comment by satmandu** [comment]
Is there a way to automate this for this sort of package?  E.g. RSS feed
for package updates?

**Comment by uberhacker** [comment]
We need smart people like you to figure that out. :)

**Comment by saltedcoffii** [comment]
Stale, no longer hacktoberfest, closing.
