### ISSUE TITLE
Chromebrew Launcher broken symlink

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#6286]
Getting this issue:
![image](https://user-images.githubusercontent.com/1096701/136711828-3bdb148a-9308-4ec8-9152-dbd5e139d0b8.png)

I don't think you made the changes I mentioned in the PR's thread. That fixes this issue:
```
    Dir.chdir "#{CREW_DEST_PREFIX}/share/crew-launcher/lib" do
      FileUtils.ln_s "../../../lib/crew/lib/color.rb", 'color.rb'
    end
    Dir.chdir "#{CREW_DEST_PREFIX}/bin" do
      FileUtils.ln_s '../share/crew-launcher/main.rb', "crew-launcher"
    end
```

**Comment by satmandu** [comment]
![image](https://user-images.githubusercontent.com/1096701/136712283-e6722822-a8a2-4566-a742-b6180090c05d.png)

**Comment by uberhacker** [comment]
I don't have this problem.
