### ISSUE TITLE
[rust] cargo and rustup not found

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6288]
```
$ cargo
bash: cargo: command not found
$ ls -l /usr/local/bin/cargo
lrwxrwxrwx. 1 chronos chronos 39 Sep 25 21:36 /usr/local/bin/cargo -> ../../../../../../share/cargo/bin/cargo
$ rustup
bash: rustup: command not found
$ ls -l /usr/local/bin/rustup
lrwxrwxrwx. 1 chronos chronos 40 Sep 25 21:36 /usr/local/bin/rustup -> ../../../../../../share/cargo/bin/rustup
```
The symlinks command broke the absolute symlinks that worked.  Not good.  This means we have to create relative symlinks that work so the symlinks command won't break working symlinks.  Not ideal.

**Comment by saltedcoffii** [comment]
As a temporary fix, one can run `for i in /usr/local/share/cargo/bin/*; do ln -sfv ${i} /usr/local/bin; done`

**Comment by satmandu** [comment]
Also, the rustup symlink just points to cargo anyways...

My guess is that this isn't working properly?
```
    Dir.chdir "#{CREW_DEST_PREFIX}/bin" do
      Dir['*'] do |f|
        FileUtils.ln_sf "../share/cargo/bin/#{f}", f
      end
    end
```
