### ISSUE TITLE
Crew-launcher fails when trying to run

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6293]
Tried to run crew-launcher after installing, but was met with the following error.
```
$ crew-launcher
/usr/local/bin/crew-launcher:10:in 'require_relative': cannot load such file -- /usr/local/share/crew-launcher/lib/color (LoadError) from /usr/local/bin/crew-launcher:10:in '<main>'
```

## Versions and system information
chromebrew: 1.17.0

ChromeOS: 
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=66
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R93-14092.66.0
CHROMEOS_RELEASE_BUILD_NUMBER=14092
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=93
CHROMEOS_RELEASE_DESCRIPTION=14092.66.0 (Official Build) stable-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14092.66.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14092.66.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by satmandu** [comment]
I also see the same issue.
