### ISSUE TITLE
Firefox cursors are using default X server cursors and don't always change with context on websites

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6340]
The firefox cursors are default X11 cursors. In addition, they don't always change correctly when hovering over content in websites (the cursor changes to a pinching hand when hovering over a link, but doesn't change to default when moving off of it. It takes repeated shifting back and forth for it to change back.)

Something I think is relevant is the following error whenever I start Firefox;
```
Gtk-WARNING **: 15:07:54.553: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

I did some hunting around but I think because of how chromebrew works, some directory or another is not being read/found? I'm not sure, just speculating.

## Versions and system information
chromebrew: 1.17.6

ChromeOS: 
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R94-14150.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=14150
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=94
CHROMEOS_RELEASE_DESCRIPTION=14150.64.0 (Official Build) stable-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14150.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14150.64.0

Model: Acer Spin 512

Architecture: x86_64

**Comment by uberhacker** [comment]
@aghebert:  Have you tried the latest firefox update (version 94.0.1)?  I don't receive this error with that version.

**Comment by supechicken** [comment]
This issue is fixed on the latest version of `sommelier`, a cursor theme (Adwaita) will be set at `sommelier` startup now
