### ISSUE TITLE
running server under chrombrew: chromeOS potentially blocking remote incoming connection

### ISSUE THREAD

**Issue by sandeep-gh** [skycocker/chromebrew#6357]
This isn't a chromebrew issue but certainly relevant to its applicability. 

Is it possible to run a server on ChormeOS and have client from remote machine connect to it? I couldn't find any information regarding this. Asked on [stackoverflow](https://stackoverflow.com/questions/69739958/chrome-os-not-allowing-connection-from-remote-machine?noredirect=1#comment123272428_69739958) but no leads there too. 

I started a simple file server using python installed via chromebrew:
```python3 -m http.server --bind 192.168.0.188 9000```

I am able to connect from remote machine to the server but don't get any response. Is chromeOS designed to block remote incoming connection?

**Comment by sandeep-gh** [comment]
Turns out that chromeOS does limit port accessibilty.  Fortunately, angles are web have given soultions. Its a port forwarder, available here:
https://chrome.google.com/webstore/detail/connection-forwarder/ahaijnonphgkgnkbklchdhclailflinn.

The github page: https://github.com/kzahel/connection-forwarder. This also give more details about the issue.

**Comment by satmandu** [comment]
Can you just use iptables to reset the rules?

`sudo iptables -L` should tell you the firewall rules...

**Comment by sandeep-gh** [comment]
Cool. Didn't occur to me to look for iptables (chromOS is linux underneath). This is helpful. Think I can use that. 
I guess that connection tool  has added benefit to modify rules without the need for developer mode.

**Comment by satmandu** [comment]
For sure, but starting a daemon requires opening a dev mode shell or crostini at startup anyways so...

**Comment by sandeep-gh** [comment]
:) True.
