### ISSUE TITLE
Error installing nano

### ISSUE THREAD

**Issue by ricksdunn** [skycocker/chromebrew#636]
color.c: In function ‘color_update’:
color.c:233:2: error: unknown type name ‘magic_t’
  magic_t cookie = NULL;
  ^
color.c:240:6: warning: implicit declaration of function ‘magic_open’ [-Wimplicit-function-declaration]
      cookie = magic_open(MAGIC_SYMLINK |
      ^
color.c:240:26: error: ‘MAGIC_SYMLINK’ undeclared (first use in this function)
      cookie = magic_open(MAGIC_SYMLINK |
                          ^
color.c:240:26: note: each undeclared identifier is reported only once for each function it appears in
color.c:244:9: error: ‘MAGIC_ERROR’ undeclared (first use in this function)
         MAGIC_ERROR);
         ^
color.c:245:17: warning: comparison between pointer and integer
      if (cookie == NULL || magic_load(cookie, NULL) < 0)
                 ^
color.c:245:6: warning: implicit declaration of function ‘magic_load’ [-Wimplicit-function-declaration]
      if (cookie == NULL || magic_load(cookie, NULL) < 0)
      ^
color.c:248:3: warning: implicit declaration of function ‘magic_file’ [-Wimplicit-function-declaration]
   magicstring = magic_file(cookie, openfile->filename);
   ^
color.c:248:15: warning: assignment makes pointer from integer without a cast
   magicstring = magic_file(cookie, openfile->filename);
               ^
color.c:251:5: warning: implicit declaration of function ‘magic_error’ [-Wimplicit-function-declaration]
     openfile->filename, magic_error(cookie));
     ^
color.c:267:6: warning: implicit declaration of function ‘magic_close’ [-Wimplicit-function-declaration]
      magic_close(cookie);
      ^
make[2]: *** [color.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/browser.Tpo .deps/browser.Po
make[2]: Leaving directory `/usr/local/tmp/crew/nano-2.7.1.tar.gz.dir/nano-2.7.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/nano-2.7.1.tar.gz.dir/nano-2.7.1'
make: *** [all] Error 2
nano failed to install: `make -j2` exited with 2

seems to fail at the very end...

**Comment by jam7** [comment]
what architecture are you using?  It is shown by `uname -m`.
```
$ uname -m
armv7l
```
nano is compiled well on armv7l, I guess some architecture dependencies cause this problem.

**Comment by ricksdunn** [comment]
i686

**Comment by jam7** [comment]
I've installed nano on i686 now without any errors, so I think it is not a problem of crew itself.
On the other hand, I know magic_t is defined under filecmd, so I think your filecmd may be broken.
Don't you try following steps?

 -  `sudo crew remove filecmd`, then `crew install nano` again
   In my environment, nano uses magic_t if filecmd is exist, but it could be compiled without filecmd well.

**Comment by finwo** [comment]
Which version of glibc is installed?
I know a while back there were some issues.

Could you post the output of the following command?

```
# crew search | grep libc
```

**Comment by ricksdunn** [comment]
so filecmd was not installed ... I installed it and then nano installed!

Thanks for the help!

**Comment by finwo** [comment]
@ricksdunn Strange, on my amd64 it installs fine without filecmd.
