### ISSUE TITLE
Neofetch depends on make

### ISSUE THREAD

**Issue by DGTWT** [skycocker/chromebrew#6383]
Hi,
I got this error after trying to install neofetch:

```
chronos@localhost / $ crew install neofetch
neofetch: A fast, highly customizable system info script
https://github.com/dylanaraps/neofetch
Version: 7.1.0
License: MIT-with-advertising
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
#### 100.0% -=#=- #      #       #                                                                                                                                                
Neofetch archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
neofetch failed to install: `make DESTDIR=/usr/local/tmp/crew/dest PREFIX=/usr/local install` exited with 127
```

I've solved it installing make. 

`chronos@localhost / $ crew install make
`

Neofetch should be marked as dependent on make.

## Versions and system information
chromebrew: 1.18.2 x86_64

Regards

**Comment by satmandu** [comment]
Hmmm. `make` is in `buildessential`.... @uberhacker any ideas?

**Comment by uberhacker** [comment]
I can look into it but crew is supposed to automatically install the necessary tools if attempting to build from source.

**Comment by saltedcoffii** [comment]
Not necessarily @uberhacker. Chromebrew installs buildessential when using the `-s` option, however without, it does not.

**Comment by satmandu** [comment]
> Not necessarily @uberhacker. Chromebrew installs buildessential when using the `-s` option, however without, it does not.

That's a bug, then! We should have buildessential added to the stack of dependencies which need to be installed whenever we need to build a package!

**Comment by uberhacker** [comment]
I agree @satmandu.  However, we shouldn't expect regular users to compile packages from source when it takes over a minute to install.  This issue is only a problem if prebuilt binaries are not available and in the case of neofetch, they probably should be added.
