### ISSUE TITLE
Minecraft will not install (Error: /usr/local/.config in minecraft is not FHS3 compliant.)

### ISSUE THREAD

**Issue by KriiXOne** [skycocker/chromebrew#6387]
## Description
Minecraft will refuse to install exiting with an error.

```shell
chronos@localhost / $ crew install minecraft
```

Output:
```shell
minecraft: A sandbox video game developed by Mojang Studios AB.
https://minecraft.net
Version: 2.2.3200
License: Mojang
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
################################################################################################# 100.0%
Minecraft archive downloaded.
Unpacking archive using 'ar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
Rename all *.la_tmp files back to *.la
Checking for FHS3 compliance...
Error: /usr/local/.config in minecraft is not FHS3 compliant.
Checking for conflicts with files from installed packages...
Exiting due to above errors.
chronos@localhost / $ 
```

## Versions and system information
chromebrew: `1.18.2`

ChromeOS: `CHROMEOS_RELEASE_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_BOARD_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=OTHER
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_DESCRIPTION=94.2.4 (Developer Build - neverware) stable-channel chromeover64
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_RELEASE_BRANCH_NUMBER=65
CHROMEOS_RELEASE_BUILD_NUMBER=14150
CHROMEOS_RELEASE_CHROME_MILESTONE=94
CHROMEOS_RELEASE_PATCH_NUMBER=2021_10_22_0727
CHROMEOS_RELEASE_VERSION=94.2.4
GOOGLE_RELEASE=94.2.4`

Model: CloudReady Generic Laptop (Intel 8gen)

Architecture: `x86_64`

**Comment by satmandu** [comment]
Try `CREW_FHS_NONCOMPLIANCE_ONLY_ADVISORY=1 crew install minecraft` ...

**Comment by KriiXOne** [comment]
> Try `CREW_FHS_NONCOMPLIANCE_ONLY_ADVISORY=1 crew install minecraft` ...

installed fine but now it gives an error upon launching:
`chronos@localhost / $ minecraft-launcher
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
MessageBox(Minecraft Launcher): Couldn't load launcher core from /usr/local/.config/.minecraft/launcher/liblauncher.so: LoadErrorNotPresent`

**Comment by KriiXOne** [comment]
> > Try `CREW_FHS_NONCOMPLIANCE_ONLY_ADVISORY=1 crew install minecraft` ...
> 
> installed fine but now it gives an error upon launching: `chronos@localhost / $ minecraft-launcher https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json MessageBox(Minecraft Launcher): Couldn't load launcher core from /usr/local/.config/.minecraft/launcher/liblauncher.so: LoadErrorNotPresent`

oh boy... this was a dependency error, `minecraft-launcher` requires `libsecret`, it needs to be added to dependencies perhaps.

launcher and game seems fine so far!

**Comment by satmandu** [comment]
Thanks for the suggestions for fixing this package!
