### ISSUE TITLE
[On Install] Chromebrew Installer fails to download glibc and just ends.

### ISSUE THREAD

**Issue by JadenJSJ** [skycocker/chromebrew#6404]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.
None alike

## Description
Provide a short description of your problem here.
When installing chromebrew it fails downloading glibc

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output: https://pastebin.com/6f0uqNVZ (Its too long)
![image](https://user-images.githubusercontent.com/44781632/142746369-764f1e06-066f-4b38-9ee5-b7dcdfebf649.png)

## Versions and system information
chromebrew: `1.18.2`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7906507
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9496CDE8-85E6-4118-960F-E26DC0C69FD6}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_RELEASE_BOARD=grunt-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILDER_PATH=grunt-release/R98-14350.0.0
CHROMEOS_RELEASE_BUILD_NUMBER=14350
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=98
CHROMEOS_RELEASE_DESCRIPTION=14350.0.0 (Official Build) canary-channel grunt 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=canary-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14350.0.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14350.0.0`

Model: Acer C721

Architecture: x86_64
![image](https://user-images.githubusercontent.com/44781632/142746486-d4f7d695-1b70-49c9-ae85-0395b22249e8.png)

Additional Info
My network is stable, and it has nothing to do with my internet.
~~I did the installer twice and it stopped on glibc again, meaning its not my internet, probably a dead link somewhere on the code, I'm not sure. (just a guess, there is no link provided to download the package so im not sure how to check the link.)~~
Nevermind the links seem to be from popular sites so It's probably not it. (Gitlab, GNU, Google, Gentoo, Fedora yea these are stable servers) 
![image](https://user-images.githubusercontent.com/44781632/142746618-33411701-9ced-4979-8a87-70b319e3ddff.png)

Result:
Some apps like nano don't work probably because of some packages required by it that failed to install. (Or was supposed to be installed when installing Chromebrew)
![image](https://user-images.githubusercontent.com/44781632/142746894-a2eb583e-246b-429c-a34b-ea7500654dc9.png)

Looks like gdb won't work
![image](https://user-images.githubusercontent.com/44781632/142746973-76ba6b4a-0176-4bb4-8483-6b64bcf8e63c.png)

Thank You for reading.

**Comment by supechicken** [comment]
Seems that you are in Canary channel, it is very likely that your system is running glibc 2.32+ (we only support 2.27 and 2.32)

Could you provide the output of `crew const LIBC_VERSION`
(if the output is greater than 2.32 then we don't support it)

**Comment by saltedcoffii** [comment]
According to the [README.md file](https://github.com/skycocker/chromebrew/blob/02d4b1b/README.md):
```
The beta, dev, and Canary channels are not supported and should not be used with Chromebrew. Failure to take notice of this will cause major issues with your Chromebrew installation.
```

Due to this, I am marking this issue as wontfix and closing the issue. We're so happy that you're using Chromebrew and helping us improve the tool, however the beta, dev and canary branches simply change too much for a team of small developers to keep up with. However, if you'd like to edit the `glibc.rb` file to support your version of glibc and open a pull request, we would be elated. Here's a previous [https://github.com/skycocker/chromebrew/pull/5851/files](pull request) when support for 2.32 was added, if that helps at all.
