### ISSUE TITLE
"Checksum mismatch. 😔 Try again" when install py3_dnspython

### ISSUE THREAD

**Issue by iscodeeasyornot** [skycocker/chromebrew#6406]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
your command here
```

Output:
```
chronos@localhost / $ crew install nautilus
nautilus: Default file manager for GNOME
https://wiki.gnome.org/Apps/Files
Version: 40.2
License: GPLv3
Performing pre-flight checks...
The following packages also need to be installed: 
py3_dnspython libhandy tracker3_miners exempi libgrss libgsf tracker3 gtk3 gtk4 
Do you agree? [Y/n] 
Proceeding...
py3_dnspython: DNSPython is a DNS toolkit.
Precompiled binary available, downloading...
#################################################################################################################################################### 100.0%
Checksum mismatch. 😔 Try again.
```

## Versions and system information
chromebrew: `1.18.2`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7888632
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={85F8FA82-F276-4EA6-8980-93FE091F6D25}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={85F8FA82-F276-4EA6-8980-93FE091F6D25}
CHROMEOS_RELEASE_BOARD=nautilus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=87
CHROMEOS_RELEASE_BUILDER_PATH=nautilus-release/R94-14150.87.0
CHROMEOS_RELEASE_BUILD_NUMBER=14150
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=94
CHROMEOS_RELEASE_DESCRIPTION=14150.87.0 (Official Build) stable-channel nautilus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14150.87.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14150.87.0`

Model: Nautilus

Architecture: `uname -m`

## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@iscodeeasyornot: Does `crew install py3_dnspython -s` work?

**Comment by uberhacker** [comment]
We don't support the canary channel so you might get better results if you switch over to the stable channel.

**Comment by uberhacker** [comment]
Sorry, never mind.  I noticed you are already on the stable channel.

**Comment by iscodeeasyornot** [comment]
> @iscodeeasyornot: Does `crew install py3_dnspython -s` work?

I tried "crew install -s -v "and the result is same.

**Comment by uberhacker** [comment]
It worked fine for me.  What is your architecture?

**Comment by saltedcoffii** [comment]
It may also be an internet issue. If the checksum is `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (internally), it means nothing was downloaded.
