### ISSUE TITLE
Web Server with PHP possible?

### ISSUE THREAD

**Issue by bdodroid** [skycocker/chromebrew#641]
Not exactly an issue, but does anyone know how to setup any of the available web servers to handle php? 

I've tried modifying nginx and darkhttpd with no luck and httpd only gives me SVN not found :(

**Comment by thedamian** [comment]
You can google how to host PHP through NGINX (it's not obvious) or just look at this comment and I'll think you'll be set: 

https://github.com/skycocker/chromebrew/pull/306#issuecomment-269578366

**Comment by bdodroid** [comment]
Perfect thank you! I forgot PHP had its own built in server lol
