### ISSUE TITLE
Keepassxc fails to start

### ISSUE THREAD

**Issue by DGTWT** [skycocker/chromebrew#6421]
Hi,

keepassxc fails to start after a successful installation (thanks #6419). I suppose that this problem is related to a bad sommelier installation,  because crosh takes some time to start and returns a failed to start message while this package is installed.

Input:
```
chronos@localhost ~/MyFiles/Downloads $ keepassxc
```

Output:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

/usr/local/bin/keepassxc: line 3:  6718 Aborted                 (core dumped) ./AppRun "$@"
```

## Versions and system information
chromebrew: `1.18.2`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7833743
CHROMEOS_AUSERVER=https://block-tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5A3AB642-2A67-470A-8F37-37E737A53CFC}
CHROMEOS_RELEASE_BOARD=coral-signed-mp-v19keys
CHROMEOS_RELEASE_BRANCH_NUMBER=74
CHROMEOS_RELEASE_BUILDER_PATH=coral-release/R94-14150.74.0
CHROMEOS_RELEASE_BUILD_NUMBER=14150
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=94
CHROMEOS_RELEASE_DESCRIPTION=14150.74.0 (Official Build) stable-channel coral 
CHROMEOS_RELEASE_KEYSET=mp-v19
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14150.74.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14150.74.0`

Architecture: `x86_64

**Comment by DGTWT** [comment]
Error message displayed by sommelier:

```
some sommelier processes failed to start
sommelier processes running:  
```
I've already tried:

`source ~/.bashrc
`

And:
`startsommelier`
`stopsommelier`
`restartsommelier`

**Comment by uberhacker** [comment]
I have noticed this too @DGTWT.  The latest release has some issues.  You might try an earlier release.
```
source_url 'https://github.com/keepassxreboot/keepassxc/releases/download/2.6.4/KeePassXC-2.6.4-x86_64.AppImage'
source_sha256 '5f9657440eb0740ad65e7fc3c80524247a863315528705b8fb79df6755329483'
```

**Comment by DGTWT** [comment]
Hi,

I've seen today that many packages were updated. I've upgraded them and now everything runs fine!

I've even noticed that Telegram runs faster. Many thanks, you're an awesome team.

**Comment by uberhacker** [comment]
Thank you for the feedback @DGTWT.  If you would like to get involved, we could use help to keep packages updated.  Some packages that don't need binaries take less than 5 minutes to update.

**Comment by DGTWT** [comment]
I'd love to help! This project along with brunch has given a new life to my computer :)

**Comment by saltedcoffii** [comment]
> Hi,
> 
> I've seen today that many packages were updated. I've upgraded them and now everything runs fine!
> 
> I've even noticed that Telegram runs faster. Many thanks, you're an awesome team.

It's very rare that we get compliments like this, and I just want to say that it made my heart melt a little, knowing that people appreciate our work. Those updates that were pushed yesterday were two months in the making. Thank you <3

I'm closing this issue because you said everything runs fine. Ping me if you need it repopened.
