### ISSUE TITLE
Package 'pkgname' is not compatible with your device architecture

### ISSUE THREAD

**Issue by Zachary-Rude** [skycocker/chromebrew#6429]
Hi,

When I try to build a custom package called `diction`, I just get an error telling me that it's not compatible with my architecture.

Here is what I ran:

```shell
$ crew build diction
```

Output:
```
diction: Diction identifies wordy or commonly misused phrases.
Package diction is not compatible with your device architecture (armv7l) :/
```

How do I fix this?

**Comment by uberhacker** [comment]
Hey @Zachary-Rude:  Make sure your new package is in `/usr/local/lib/crew/packages`, execute `crew update compatiblity` and then try to build again.

**Comment by Zachary-Rude** [comment]
It worked! I just had to run `crew update compatibility`, and then it worked!

**Comment by satmandu** [comment]
@uberhacker @saltedcoffii @supechicken Maybe we should modify the `not compatible with your device architecture` message to ask users to run `crew update compatibility` automatically if a package is new?

**Comment by uberhacker** [comment]
This situation only ever happens when new packages are added so it only applies to package developers.  That said, how could it be run automatically or are you just saying it should have a different message prompt to run manually?

**Comment by saltedcoffii** [comment]
I think we should at least add it in the help message. maybe we could make it a POSIX or GNU style option `-c` `--compatibility`.
