### ISSUE TITLE
[Request] Add Podman

### ISSUE THREAD

**Issue by aghebert** [skycocker/chromebrew#6488]
[Podman](https://podman.io/) is a drop-in replacement for docker. I'd like to run the application [DistroBox](https://github.com/89luca89/distrobox), which I was able to successfully install, but it fails to run since it requires Podman. I have tried to create a package file for chromebrew before, but found the instructions unclear and confusing. I would love some direction, or even better, direct help. Thanks.

**Comment by uberhacker** [comment]
The problem with installing Podman (and Docker) is your Chromebook needs a virtualized kernel.  Most devices (ones that are 2 years old or older) don't have this capability.  In theory, if your Chromebook can run Linux Apps (aka Crostini), it can also run Docker/Podman too.
