### ISSUE TITLE
OpenSSL version mismatch. Built against 1000200f, you have 1000105f | need update

### ISSUE THREAD

**Issue by HLFH** [skycocker/chromebrew#65]
Hi,

I got the following issue:
```bash
ssh user@mydomain.com
OpenSSL version mismatch. Built against 1000200f, you have 1000105f
```

Please update openssl.rb to the last version: 1.0.2a.

**Comment by naushit** [comment]
I am also affected by this , latest  chromebook update breaks ssh !!   Please update ssh to 1.0.2a

**Comment by andrew-christianson** [comment]
I'm seeing the same issue on beta channel (currently 43.0.2357 but I've been seeing it for a while)

**Comment by ngamradt** [comment]
I too am having this issue running the following:

Version 43.0.2357.81 (64-bit)
Platform 6946.55.0 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

**Comment by ngamradt** [comment]
Actually, it appears that there is now a standard version of openssl located at...

/usr/bin/openssl

...if you uninstall the crew version...

sudo crew remove openssl

...then the error goes away.  I can now SSH.  A check of the version (openssl version) shows...

OpenSSL 1.0.2a 19 Mar 2015

**Comment by naushit** [comment]
Thanks , removing  openssl from chromebrew  fixed the issue.

**Comment by HLFH** [comment]
Yep, solved this way too. Chromebrew seems discontinued. It would be great if their openssl package could be updated or removed.

**Comment by ngamradt** [comment]
I wouldn't say that Chromebrew is discontinued.  Since it is open source, I
believe anyone could contribute a package if they would like, but it also
means that a package could be easily abandoned.  It appears that nodejs was
updated not that long ago.  In the case of the openssl package, it appears
that Google is going to now provide one out-of-the-box since they support
SFTP in the Files App.  This may reduce or eliminate the need for this
Chromebrew package since it is now supported natively as part of Chrome OS.

**Comment by HLFH** [comment]
@ngamradt You're right. Thank you for the recall and precision. So I made a PR https://github.com/skycocker/chromebrew/pull/82 to remove the Chromebrew OpenSSL package.

**Comment by tdingman** [comment]
I'm still getting this error, and I've tried `sudo crew remove openssl`. I'm getting `package openssl not found :(` as a result, which makes sense given the PR above. Any ideas on how I can remove Chromebrew's OpenSSL and let the native version take over?

**Comment by tdingman** [comment]
OK, for anyone who runs into my same problem, here's the move:

1. `cd /usr/local/lib/crew/packages/`
2. `vim openssl.rb`
3. Copy and paste the contents of [this file](https://github.com/skycocker/chromebrew/blob/470e7e0e9b31e644b00088779fb1ab4bd5b952f0/packages/openssl.rb) in there
4. `sudo crew remove openssl`

**Comment by skycocker** [comment]
@tdingman do you think we can close this?

**Comment by tdingman** [comment]
@skycocker it's already closed, no?

**Comment by skycocker** [comment]
@tdingman oh, sorry, I must have thought it's still open once I got a notification.

**Comment by nathansmyth** [comment]
Thanks @ngamradt, worked on my hp chromebook 14 to 

```
$ sudo crew remove openssl
```

now I'm getting 

```
chronos@localhost ~/Downloads/Projects/synesthesia $ git push -u origin master
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 415 bytes | 0 bytes/s, done.
```

also big thanks to @skycocker for chromebrew, I'm able to have a sane (almost no crouton now with all the new packages this year) dev environment on my chromebook, of all places!

**Comment by emicol** [comment]
The simple solution I think is to use synaptic, find openssl, right click, "reinstall". It's avoid some problems.
