### ISSUE TITLE
I can't run Steam

### ISSUE THREAD

**Issue by Ajgamerstorms** [skycocker/chromebrew#6509]
## Description
I can't run steam using flatpak

I ran the following command:
```shell
flatpak run com.valvesoftware.Steam I also wrote this command too /usr/local/libexec/flatpak/flatpak run com.valvesoftware.Steam


```

I recieve the following errors
```
ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists
Note that the directory 

'/usr/local/var/lib/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: app/com.valvesoftware.steam/x86_64/master not installed 
I get a different error when I ran this command /usr/local/libexec/flatpak/flatpak run com.valvesoftware.Steam
```

## Versions and system information
chromebrew: `1.19.3`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7898127
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=51
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R96-14268.51.0
CHROMEOS_RELEASE_BUILD_NUMBER=14268
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=96
CHROMEOS_RELEASE_DESCRIPTION=14268.51.0 (Official Build) stable-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14268.51.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14268.51.0`

Model: YOUR MODEL HERE

Architecture: `x86_64`

## Additional information
What I think this issue is coming from flatpak itself because app/com.valvesoftware.steam/x86_64/master doesn't exist for some reason when I tried to install it

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.
Btw I don't know how to label

**Comment by saltedcoffii** [comment]
#7127
