### ISSUE TITLE
Sommelier package is broken

### ISSUE THREAD

**Issue by weberk** [skycocker/chromebrew#6512]
## Description
Sommelier does not start correctly, but claims some processes could not be started. I.e. xauth add 

Output:
```shell
chronos@localhost ~ $ startsommelier 
some sommelier processes failed to start
sommelier processes running:  
 23538 /usr/local/bin/../lib64/ld-linux-x86-64.so.2 --library-path /usr/local/bin/../lib64 --inhibit-rpath  /usr/local/bin/sommelier.elf -X --x-display= --scale= --glamor --drm-device=/dev/dri/renderD128 --virtwl-device=/dev/null --shm-driver=noop --data-driver=noop --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib64/dri --peer-cmd-prefix=/usr/local/lib64/ld-linux-x86-64.so.2 --no-exit-with-child /bin/sh -c touch ~/.Xauthority       xauth -f ~/.Xauthority add  . e04a7ca71380839acaf8f9e37c348f86       source /usr/local/etc/sommelierrc
```
in sommelier.log it was claiming about wrong parameter for xauth because of missing $DISPLAY
```shell
chronos@localhost / $ export WAYLAND_DEBUG=1
chronos@localhost / $ tail -f /usr/local/var/log/sommelier.log 
xauth: (argv):1:  bad "add" command line
/bin/sh: 3: source: not found
```

## Versions and system information
chromebrew: `crew --version`
1.19.3
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7982014
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=67
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R96-14268.67.0
CHROMEOS_RELEASE_BUILD_NUMBER=14268
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=96
CHROMEOS_RELEASE_DESCRIPTION=14268.67.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14268.67.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14268.67.0

Model: MacBookAir mid 2013

Architecture: `uname -m`
x86_64

## Additional information
I could fix this error by filling the file ~/.sommelier.env with the stuff usually set globally (SCALE, DISPAY,...). These are missing in the above excecution of sommelier process. The global sommelier.env is missing!
```shell
chronos@localhost / $ cat ~/.sommelier.env 
          set -a
          CLUTTER_BACKEND=wayland
          DISPLAY=:0
          GDK_BACKEND=x11
          SCALE=1
          SOMMELIER_ACCELERATORS='Super_L,<Alt>bracketleft,<Alt>bracketright'
          WAYLAND_DISPLAY=wayland-0
          XDG_RUNTIME_DIR=/var/run/chrome
          case "$(uname -m)" in
          x86_64|i686)
            sort_result="$(sort -V <<< "$(uname -r)"$'\\n'"4.16.0" | tail -n1)"
            if [[ "${sort_result}" == "4.16.0" ]]; then
              MESA_LOADER_DRIVER_OVERRIDE=i965
            fi
          ;;
          esac
          set +a
```
In ~/.bashrc now I have the following:
```shell
chronos@localhost / $ cat ~/.bashrc
# /etc/skel/.bashrc
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi

# Put your fun stuff here.
if [ ! -d /tmp/.X11-unix ]; then
mkdir /tmp/.X11-unix
fi
sudo chmod -R 1777 /tmp/.X11-unix
sudo chown root:root /tmp/.X11-unix
source ~/.sommelier.env
restartsommelier
```

**Comment by supechicken** [comment]
Could you try the following:
```shell
CREW_TESTING_REPO=https://github.com/supechicken666/chromebrew.git \
CREW_TESTING_BRANCH=update_sommelier \
CREW_TESTING=1 \
crew update
crew reinstall sommelier
```
(This is the latest version of sommelier)

**Comment by weberk** [comment]
Hi,
just tested the above sommelier build from sources. Installation was running fine.
-------------------
I removed everything concerning sommelier from .bashrc and also deleted ~/.sommelier.env
-------------------
After relogin I tryed to start codium from the shell. Did not worked! I guess sommelier is not running as a daemon?
Then manually (re)started sommelier:
chronos@localhost ~ $ restartsommelier 
sommelier stopped
sommelier processes running: 5501 5508
wonder if it is ok that two processes are listed?
Then I tried to start codium from the shell. Did not worked!
-------------------
Realized that the environment variable $DISPLAY was not set (by restartsommelier?)
Manually set DISPLAY to :0 and started codium from the shell. Now codium started fine!
-------------------
This means in my bashrc I have to keep the following lines active and some commented since not necessary:
# sommelier
export DISPLAY=:0
#if [ ! -d /tmp/.X11-unix ]; then
#mkdir /tmp/.X11-unix
#fi
#sudo chmod -R 1777 /tmp/.X11-unix
#sudo chown root:root /tmp/.X11-unix
#source ~/.sommelier.env
restartsommelier

**Comment by supechicken** [comment]
The latest version of `sommelier` should fix this issue
