### ISSUE TITLE
[crew]: `rsync: ACLs are not supported on this client`

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#6516]
This error was reported when installing any package:
```
rsync: ACLs are not supported on this client
rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
```

**Comment by supechicken** [comment]
Also, seems that `rsync` will not handle symlinks, see below:
$ crew files codium
codium: VSCodium is Open Source Software Binaries of VSCode with a community-driven default configuration.
/usr/local/bin/codium
...snip...
$ ls /usr/local/bin/codium
bash: codium: command not found
```

**Comment by satmandu** [comment]
Hmmm do a `crew update ; crew reinstall codium`? I think https://github.com/skycocker/chromebrew/pull/6514 fixed this.

**Comment by satmandu** [comment]
At least for symlinks... 
```
ls -aFl /usr/local/bin/codium
lrwxrwxrwx 1 chronos chronos 32 Dec 22 14:52 /usr/local/bin/codium -> ../VSCodium-linux-x64/bin/codium*
```

**Comment by satmandu** [comment]
Try `crew update ; crew reinstall zstd rsync```

**Comment by satmandu** [comment]
Also, is this a `cloudready` only issue? How is `/usr/local` mounted on cloudready?

**Comment by supechicken** [comment]
> Also, is this a `cloudready` only issue? How is `/usr/local` mounted on cloudready?

Cloudready also have a `rsync` binary in `/usr/local`, but same error happened in both `crew` and `cloudready` provided binaries

**Comment by supechicken** [comment]
> Try `crew update ; crew reinstall zstd rsync`

It works, thanks!
