### ISSUE TITLE
flags now added to make prevent builds from succeeding

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#6529]
Trying to do a new build of ruby I get this:
```
ruby failed to build: `make -j4 DESTDIR=/usr/local/tmp/crew/dest install` exited with 127
/usr/local/lib/crew/lib/package.rb:195:in `system': No such file or directory - make -j4
```

This is happening from an invocation of `system 'make'`

@supechicken Thoughts?

**Comment by uberhacker** [comment]
I will second @satmandu's observation.  If this is not fixed today @supechicken, I will be submitting a revert commit.  This is a huge stopper.

**Comment by saltedcoffii** [comment]
I'm running into this as well, it's inhibiting.
