### ISSUE TITLE
Unable to Install QEMU - Noob sorry

### ISSUE THREAD

**Issue by necrolatry** [skycocker/chromebrew#6536]
Hey guys just trying to install the android subsystem into cloud ready but hit a snag installing qemu, says that c doesn't exist?
Tried reinstalling gcc but no dice

chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $ crew reinstall gcc
gcc: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
Removing since upgrade or reinstall...
Gcc removed!
Performing post-install for gcc...
Gcc installed!
chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $ crew install qemu
qemu: QEMU is a generic and open source machine emulator and virtualizer.
http://www.qemu.org/
Version: 4.2.0
License: GPL-2, LGPL-2 and BSD-2
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
[##############################################################################################################################################################]  59.34 MB 100%
Qemu archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp

ERROR: "cc" either does not exist or does not work

qemu failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --disable-stack-protector` exited with 1
chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $

**Comment by necrolatry** [comment]
tried compling it also but yeh no c compiler working  also ninja throwing an error, still a bit new to linux so any help would be appreciated cheers
chronos@localhost /usr/local/tmp/build $     cd qemu-5.2.0
chronos@localhost /usr/local/tmp/build/qemu-5.2.0 $     ./configure --enable-sdl --enable-opengl --enable-virglrenderer \
> --enable-system --enable-modules --audio-drv-list=pa \
> --target-list=x86_64-softmmu --enable-kvm --enable-gtk \
> --prefix=/usr/local --libdir=/usr/local/lib64 \
> --mandir=/usr/local/share/man 
Using './build' as the directory for build output

ERROR: "cc" either does not exist or does not work

chronos@localhost /usr/local/tmp/build/qemu-5.2.0 $     ninja -C build
ninja: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ninja)
chronos@localhost /usr/local/tmp/build/qemu-5.2.0 $     meson install -C build
Install data not found. Run this command in build directory root.
chronos@localhost /usr/local/tmp/build/qemu-5.2.0 $

**Comment by satmandu** [comment]
Maybe @supechicken can help wth this? I don't think we have tested installs against cloudready...

**Comment by saltedcoffii** [comment]
qemu is currently broken, this is a known bug. this isn't just for cloudready, it's for chromeos proper and fydeos as well. we're sorry for any inconvienences.

**Comment by supechicken** [comment]
Hello, do you following [this Reddit post](https://www.reddit.com/r/chromeos/comments/kk2d56/tutorial_install_android_with_full_graphics/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) I wrote months ago about installing Android?

Due to a new bug from Chromebrew, you need to install the `buildessential` package before building `libepoxy` and `qemu`. Could you try the following:
```shell
crew install buildessential
crew install -a libepoxy
```

**Comment by necrolatry** [comment]
> Hello, did you following [this Reddit post](https://www.reddit.com/r/chromeos/comments/kk2d56/tutorial_install_android_with_full_graphics/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) I wrote months ago about installing Android?
> 
> Due to a new bug from Chromebrew, you need to install the `buildessential` package before building `libepoxy` and `qemu`. Could you try the following:
> 
> ```shell
> crew install buildessential
> crew install -a libepoxy
> ```

Hi yes I am following that one, tried removing buildessentials, cmake, gcc, meson, the pre packaged libepoxy, python3, python2, then installing buildessentials and trying the crew -s install libepoxy (That's what you meant right?) and it throws the error 

ValueError: No closing quotation 
/usr/local/lib/crew/lib/package.rb:189:in 'system': Command failed with exit 2: bash
libepoxy failed to install: 'meson -Dprefix=/usr/local -Dlibdir=/usr/local/lib64 -Dmandir=/usr/local/share/man -Dbuildtype=release -Db_lto=false -Dstrip=true -Db_pie=true -Dcpp_args=' -02' builddir' exited with 2

Then if I try to do it the way in your tutorial it gives me the

meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc']]

just a wild assumption given meson can't find the compilers and because I'm still learning and like to ask stupid questions, is this some sort of linking issue in buildessential or gcc, also where is gcc saved to after installing it I don't see it in /usr/local/bin (if that's the crew prefix)

**Comment by necrolatry** [comment]
Ok some progress, it's found cc
Reinstalled glibc, mpc, isl, mpfr, zstd, gcc, gcc11, buildessential, cmake, meson, python2, python3, and now I'm getting

meson.build:1:0: ERROR: Unable to detect linker for compiler "cc -Wl,--version"

Might try a downgrade of meson tomorrow, time for bed lol

**Comment by necrolatry** [comment]
Fixed it with crew reinstall binutils glib hahaha oh man, yeh ld was missing *facepalm, when linux breaks it breaks
It's asking for gtk3_devel for the qemu 5.2.0 build mentioned in the android reddit 
and needs glib-2.48 and gthread-2.0 to compile the qemu 4.2.0 thats in the crew repo
will play around more later on, guess me chucking all this up will help somebody else with compiler issues

**Comment by necrolatry** [comment]
Yeh the cause is 'rsync: ACLs are not supported on this client' during the initial install, breaks packages on the fly,
seems rsync is broken during the install
I got around it by removing chromebrew completely
rm /usr/local/bin/crew
rm -r -f /usr/local/lib/crew /usr/local/etc/crew /usr/local/tmp/crew
curl -Ls git.io/vddgY | bash
hitting ctrl c as soon as I saw the first one, then crew update ; crew reinstall zstd rsync
curl -Ls git.io/vddgY | bash
meson is working perfectly now qemu compiled and installed

**Comment by necrolatry** [comment]
Some observations using the install tutorial, I know it was made awhile ago and thanks for your hard work
curl git.io/vddgY | bash should be curl -Ls git.io/vddgY | bash
'crew reinstall -s gdk_pixbuf libpng wayland' fails creating the gdk_pixbuf from source so used 'crew reinstall gdk_pixbuf libpng wayland' instead
libepoxy is already installed so can skip building that
have run out of time today but qemu is installed will carry on with the process and post any findings below
thanks guys

**Comment by necrolatry** [comment]
Annnd after a million years while my 1.6ghz i7 boots up we have android on cloud ready wow
![20211230_134837](https://user-images.githubusercontent.com/65431278/147713193-068f19bb-8a93-45fe-85c1-e25728a19011.jpg)
