### ISSUE TITLE
configure: error: C preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by scottrangerio** [skycocker/chromebrew#654]
I installed Chromebrew yesterday and have been unable to install various packages. Most packages fail with `configure: error: C preprocessor "/lib/cpp" fails sanity check`.

I managed to find a solution, which is to explicitly `crew install linuxheaders` before trying to install any of the various packages that didn't work, even if those packages were meant to install `linuxheaders` as a dependency (such as `neovim`).

I'm not sure whether this is an issue with Chromebrew itself or whether the problem lies elsewhere, but I couldn't find any related issues referring to Chromebrew / Chrome OS, so I thought I'd raise an issue in case there is a fault in Chromebrew, or simply, in case someone else runs into the same problem and comes looking for a solution.

Thanks for Chromebrew ^.^

Model: ASUS C300
Chromebrew version: 0.4.1

**Comment by flyingP0tat0** [comment]
The cpp should be at another location. Do you have the cpp at `/usr/local/bin/cpp`?
If so, export the right path via `export CPP=/usr/local/bin/cpp` and try again.

**Comment by stmuk** [comment]
@flyingP0tat0 I have the same problem and tried setting CPP and it made no difference.

````
checking how to run the C preprocessor... /usr/local/bin/cpp
configure: error: in `/usr/local/tmp/crew/make-4.2.tar.bz2.dir/make-4.2':
configure: error: C preprocessor "/usr/local/bin/cpp" fails sanity check
See `config.log' for more details
make failed to install: `./configure` exited with 1
````

**Comment by uberhacker** [comment]
@jam7: #657 should resolve this issue, correct?  @stmuk: Did you perform `crew upgrade` before setting the CPP environment variable?

**Comment by jam7** [comment]
#657 fixed this problem.  @stmuk had asked it before #657 was merged.
