### ISSUE TITLE
Teams and Chrome packages are broken

### ISSUE THREAD

**Issue by necrolatry** [skycocker/chromebrew#6542]
Hey guys, just went to install chrome and it's just coming up with 
curl: (3) URL using bad/illegal format or missing URL so maybe something not right in the installer package.

Teams installs fine, but when it loads it's missing the hooks.json and complains of a memory leak, just shows a white box with no dialog.

On a positive note, it's really nice to use gparted, nautilus, android subsystem and microsoft edge on Cloud Ready, keep up the good work.

**Comment by uberhacker** [comment]
@necrolatry:  We do not officially support CloudReady since their config differs greatly from the typical ChromeOS installed on most Chromebooks and other compatible devices.  My guess is the extra X11 libraries preinstalled in CloudReady are conflicting with the Chromebrew versions.

**Comment by satmandu** [comment]
Also @necrolatry feel free to submit patches to help fix these issues for cloudready!

**Comment by necrolatry** [comment]
Ah right that makes alot of sense with teams not working, when I ran a recursive install it errored out on x11 just like you said the os already has it, and with Chrome because it has no source to build from, it just throws the URL error because the package it sees isn't made for the os. Can say that blonde moment is resolved cheers guys.

**Comment by supechicken** [comment]
> @necrolatry:  We do not officially support CloudReady since their config differs greatly from the typical ChromeOS installed on most Chromebooks and other compatible devices.  My guess is the extra X11 libraries preinstalled in CloudReady are conflicting with the Chromebrew versions.

Notice that all extra things like virtualbox and all x11 related things are removed (because Neverware is a part of Google now :) )

**Comment by necrolatry** [comment]
@satmandu Wish I was smart enough to do that, I'm at that beginner/intermediate stage with linux and have no coding experience whatsoever. Still got to start somewhere right?

**Comment by necrolatry** [comment]
@supechicken Yeah I saw that, they want to sell chromebooks not let people repurpose their ewaste, it doesn't fit the business model. Even with a few packages that are incompatible I would much rather use Chromebrew than the Linux VM, for the simple fact that VM barely runs on a 3rd gen, 1st gen i7 like what I've been testing this on, basically just hangs.

**Comment by satmandu** [comment]
> @satmandu Wish I was smart enough to do that, I'm at that beginner/intermediate stage with linux and have no coding experience whatsoever. Still got to start somewhere right?
> 
> 

We were all there once... 😅
