### ISSUE TITLE
We need rdesktop / freerdp package

### ISSUE THREAD

**Issue by HLFH** [skycocker/chromebrew#66]
Hi,

Please add rdesktop package. With rdesktop, you could easily connect to a VirtualBox VM, so you won't use any shitty Chrome apps or the rdesktop package running via Crouton & Ubuntu Trusty.

Thanks in advance,
HLFH

**Comment by Downchuck** [comment]
freerdp is an alternative. It'd be nice to have a good RDP client; the Chrome apps market does not have a reliable offering.

**Comment by bfayers** [comment]
[https://github.com/FreeRDP/FreeRDP/wiki/Compilation](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) FreeRDP provides a guide on how to compile it, take a look and make sure you have `crew install make` already done.

**Comment by flyingP0tat0** [comment]
This will maybe be possible once we got X working (#889).

**Comment by sajjaadf** [comment]
X now works

**Comment by superloach** [comment]
I'm working on this, unfortunately the dependency tree is pretty large and `crew` sucks at handling it. Other than that, I'm fairly sure this package should work.

**Comment by superloach** [comment]
Stuck at #3107

**Comment by JL2210** [comment]
I worked on this a while back. It was frustrating.

**Comment by superloach** [comment]
FreeRDP has compiled! 🎉
#3106 will fix the dependency tree issue.
Now I just need to clean up the package and test it :)
