### ISSUE TITLE
installing htop, command doesnt work

### ISSUE THREAD

**Issue by kidney-bean** [skycocker/chromebrew#6633]
## Description
After installing htop, the command `htop` does not work.

If you executed a specific command:
```shell
crew install htop
```

Output:
```shell
htop: htop is an interactive process viewer for Unix systems.
https://github.com/htop-dev/htop
Version: 3.0.5
License: BSD and GPL-2
Performing pre-flight checks...
Precompiled binary available, downloading...
[#######################################################################################################################################################]  77.16 KB 100%
Htop archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync: ACLs are not supported on this client
rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
Performing post-install for htop...
Htop installed!
```

## Versions and system information
chromebrew: 1.21.3
ChromeOS: 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8015778
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5BF597B2-ADE3-52C9-1DDA-95719C914AFF}
CHROMEOS_RELEASE_BOARD=elm-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=62
CHROMEOS_RELEASE_BUILDER_PATH=elm-release/R97-14324.62.0
CHROMEOS_RELEASE_BUILD_NUMBER=14324
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=97
CHROMEOS_RELEASE_DESCRIPTION=14324.62.0 (Official Build) stable-channel elm 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14324.62.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14324.62.0

Model: Acer Chromebook R13

Architecture: aarch64

**Comment by satmandu** [comment]
Try this:
```
CREW_TESTING_REPO=https://github.com/supechicken666/chromebrew.git CREW_TESTING_BRANCH=cloudready_fix CREW_TESTING=1 crew update
crew install rsync htop
crew update
```

**Comment by satmandu** [comment]
This should take care of this issue now: `crew update ; crew reinstall rsync htop`

Please let us know if that fixes the issue?
