### ISSUE TITLE
Glibc Throws error upon attempt to download

### ISSUE THREAD

**Issue by NeonSupernova** [skycocker/chromebrew#6643]
## Description
Trying to install glibc returns an error.

If you executed a specific command:
```shell
crew install glibc
```
or 
```shell
crew install -s glibc
```

Output:
```shell
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
https://www.gnu.org/software/libc/
Version: 
License: LGPL-2.1+, BSD, HPND, ISC, inner-net, rc, and PCRE
Performing pre-flight checks...
/usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib64/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:638:in `download'
        from /usr/local/bin/crew:1315:in `install'
        from /usr/local/bin/crew:1181:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1602:in `block in install_command'
        from /usr/local/bin/crew:1597:in `each'
        from /usr/local/bin/crew:1597:in `install_command'
        from /usr/local/bin/crew:1690:in `<main>'
/usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib64/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:638:in `download'
        from /usr/local/bin/crew:1315:in `install'
        from /usr/local/bin/crew:1181:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1602:in `block in install_command'
        from /usr/local/bin/crew:1597:in `each'
        from /usr/local/bin/crew:1597:in `install_command'
        from /usr/local/bin/crew:1690:in `<main>'
```

## Versions and system information
chromebrew: `1.21.8`

ChromeOS: `cat /etc/lsb-release`
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8050614
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E9E5C8F0-C30C-190F-CA75-D6184C3FEED6}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E9E5C8F0-C30C-190F-CA75-D6184C3FEED6}
CHROMEOS_RELEASE_BOARD=setzer-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=27
CHROMEOS_RELEASE_BUILDER_PATH=setzer-release/R98-14388.27.0
CHROMEOS_RELEASE_BUILD_NUMBER=14388
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=98
CHROMEOS_RELEASE_DESCRIPTION=14388.27.0 (Official Build) beta-channel setzer 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=14388.27.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14388.27.0
```
Model: HP Chromebook
Architecture: `x86_64`

**Comment by supechicken** [comment]
Could you provide the output of the following command:
```
crew const LIBC_VERSION
```

**Comment by supechicken** [comment]
Seems you are running a beta version of Chrome OS, be aware we are not supporting system running non-stable channel version.

**Comment by NeonSupernova** [comment]
>crew const LIBC_VERSION
`LIBC_VERSION=2.33`

>Seems you are running a beta version of Chrome OS, be aware we are not supporting system running non-stable channel version.

From the looks of the error, I don't think its channel specific, I could be wrong. I have successfully downloaded this on beta channel before.

**Comment by satmandu** [comment]
We haven't actually built glibc for 2.33 yet, which is partly why you are seeing this issue.

**Comment by NeonSupernova** [comment]
> We haven't actually built glibc for 2.33 yet, which is partly why you are seeing this issue.

It would seem that the other packages use it though?

**Comment by satmandu** [comment]
We have glibc 2.32 built, but we don't have one built yet for 2.33 yet. I
have a package I'm going to test building shortly...

**Comment by satmandu** [comment]
Since you're on beta channel, you could try this to see if this works on your system:

```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew update
crew upgrade glibc
```
This will try to install the 2.32 glibc on your system, and copy over the essential glibc 2.33 files from chromeos itself.

**Comment by satmandu** [comment]
(If that breaks things, you can wipe `/usr/local` and try reinstalling Chromebrew on stable channel.)

**Comment by NeonSupernova** [comment]
> Since you're on beta channel, you could try this to see if this works on your system:
> 
> 
> 
> ```
> 
> CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew update
> 
> crew upgrade glibc
> 
> ```
> 
This seems to install it, but applications I'm trying to install (firefox) refuses to acknowledge that it exists.

**Comment by satmandu** [comment]
I've updated the binary to be a build of glibc 2.33.

Please try this: 
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew update

crew upgrade glibc ; crew reinstall glibc
```

**Comment by esprout** [comment]
I updated to beta channel 98, and it broke my install.  I'm getting Segmentation fault trying to run anything in /usr/local/bin:

`chronos@localhost /dev/shm $ CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew update
`
`
Segmentation fault (core dumped)
`
`
chronos@localhost /dev/shm $ which ruby
`
`
/usr/local/bin/ruby
`
`chronos@localhost /dev/shm $ ruby
`
`
Segmentation fault (core dumped)`

**Comment by satmandu** [comment]
@esprout Thanks for the feedback. Looks like that build of glibc 2.33 doesn't work. Are you on `x86_64` or `armv7l`?

If the answer is`x86_64` does this work for you to fix your system?
```
LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl -Ls https://gitlab.com/api/v4/projects/26210301/packages/generic/glibc/2.32-2_x86_64/glibc-2.32-2-chromeos-x86_64.tpxz -o /tmp/glibc-2.32-2-chromeos-x86_64.tpxz
LD_LIBRARY_PATH=/usr/lib64 tar -Ipixz -xf /tmp/glibc-2.32-2-chromeos-x86_64.tpxz -C /
crew postinstall glibc ; crew postinstall glibc
crew update
```

**Comment by satmandu** [comment]
If that works, it would be nice to know if `crew reinstall -s glibc` gives you a working glibc. Part of our problem here us that building glibc on a system with another glibc/kernel combo doesn't always work well.

**Comment by esprout** [comment]
To be clear, I formerly had a working install presumably with glibc 2.32, while on beta channel.  I updated to latest beta which broke the install.  So maybe what I need is to install a glibc 2.33 binary manually?

I tried (re?)installing glibc 2.32 manually as instructed with a couple tweaks to the tar command to avoid erroring out on read only filesystem folders, and not surprisingly it's a no go:

`chronos@localhost /dev/shm $ LD_LIBRARY_PATH=/usr/lib64 tar -Ipixz -m -xf /tmp/glibc-2.32-2-chromeos-x86_64.tpxz --exclude=dlist --exclude=filelist -C /`
`chronos@localhost /dev/shm $ which crew`
`/usr/local/bin/crew`
`chronos@localhost /dev/shm $ crew`
`Segmentation fault (core dumped)`

**Comment by esprout** [comment]
I found the glibc 2.33 download URL in 6649, and it appears to be working:

`chronos@localhost /dev/shm $ LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl -Ls https://gitlab.com/api/v4/projects/26210301/packages/generic/glibc/2.33_x86_64/glibc-2.33-chromeos-x86_64.tpxz -o /dev/shm/glibc-2.33-chromeos-x86_64.tpxz`
`chronos@localhost /dev/shm $ LD_LIBRARY_PATH=/usr/lib64 tar -Ipixz -m -xf /dev/shm/glibc-2.33-chromeos-x86_64.tpxz --exclude=dlist --exclude=filelist -C /`
`chronos@localhost /dev/shm $ crew`
`Usage:
  crew build [options] [-k|--keep] <name> ...
  crew const [options] [<name> ...]
  crew deps [options] <name> ...
  crew download [options] <name> ...
  crew files [options] <name> ...
  crew help [<command>]
  crew install [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew list [options] (available|installed|compatible|incompatible)
  crew postinstall [options] <name> ...
  crew reinstall [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew remove [options] <name> ...
  crew search [options] [<name> ...]
  crew update [options] [<compatible>]
  crew upgrade [options] [-k|--keep] [-s|--build-from-source] [<name> ...]
  crew whatprovides [options] <pattern> ...`

I'll try the crew update later after doing some other local testing first.

**Comment by satmandu** [comment]
Thanks for the update. Feel free to help debug the code to build a glibc 2.33 for M98... the current problem is that the build I'm generating causes program segfaults...

**Comment by satmandu** [comment]
> I found the glibc 2.33 download URL in 6649, and it appears to be working:
> 
> `chronos@localhost /dev/shm $ LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl -Ls https://gitlab.com/api/v4/projects/26210301/packages/generic/glibc/2.33_x86_64/glibc-2.33-chromeos-x86_64.tpxz -o /dev/shm/glibc-2.33-chromeos-x86_64.tpxz` `chronos@localhost /dev/shm $ LD_LIBRARY_PATH=/usr/lib64 tar -Ipixz -m -xf /dev/shm/glibc-2.33-chromeos-x86_64.tpxz --exclude=dlist --exclude=filelist -C /`
> 
> I'll try the crew update later after doing some other local testing first.

Wait, are you saying that the glibc 2.33 build there **IS** working for you?

That would be fantastic...

**Comment by NeonSupernova** [comment]
Not sure if such a feature exists already(if so I cannot find it) but can crew build from source of a local file?

**Comment by saltedcoffii** [comment]
> Not sure if such a feature exists already(if so I cannot find it) but can crew build from source of a local file?

It cannot, no. We should add that feature, that is, a feature for custom .rb files.

**Comment by esprout** [comment]
> 
> Wait, are you saying that the glibc 2.33 build there **IS** working for you @esprout ?
> 
> That would be fantastic...

Indeed I am saying that :)  No more segfaults!  Good job!  Updated today to Version 98.0.4758.79 (14388.44.0), still working!

Still haven't had a chance to try full crew update yet.  Haven't been playing with this chromebook much lately.
