### ISSUE TITLE
Installing openSSL breaks ssh/wget

### ISSUE THREAD

**Issue by bdodroid** [skycocker/chromebrew#665]
EDIT: When I try and install anything requiring OpenSSL on my Samsung Chromebook Plus it fails and breaks wget/ssh until I remove openssl.

Here is the last few lines of the install:
```
Installing...
Groff installed!
Found curl, version 7.54.0
No precompiled binary available for your platform, downloading source...
--2017-05-18 19:31:47--  https://curl.haxx.se/download/curl-7.54.0.tar.bz2
Resolving curl.haxx.se... 151.101.2.49, 151.101.66.49, 151.101.130.49, ...
Connecting to curl.haxx.se|151.101.2.49|:443... connected.
*** Error in `wget': free(): invalid pointer: 0xb9059b78 ***
Checksum mismatch :/ try again
```

Trying any wget after this fails with *** Error in `wget': free(): invalid pointer: 0xb2c1f0e0 ***

Im running - Version 60.0.3100.0 (Official Build) dev (32-bit) (same results installing php on version 58.0.3029.112)

*edit was to change "Crew" to "anything requiring OpenSSL" as Crew itself doesn't cause any problems. **Also removed Crew from the title.

**Comment by ksunden** [comment]
I had this issue as well, turned out to just be my disk was full, so wget ran out of space

**Comment by bdodroid** [comment]
I was wondering if that was it but I have 20gb free space :(
Turns out it also breaks ssh for me as well, with an invalid pointer error. 
So weird, I've never had any problems on my laptop (neverware) or my last Asus chromebook flip, but for some reason my chromebook plus just wont do it.

Anyone have this working on a Samsung Chromebook Plus?

**Comment by ksunden** [comment]
try "sudo crew remove openssl"

For me, python had that as a dependency, but installing had the same effect (aarch64 acer R13)
Removing (and even installing python without openssl in the first place), made it work

**Comment by lyxell** [comment]
Related to #614

**Comment by bdodroid** [comment]
@ksunden you where right, openssl is the problem and removing fixes my invalid pointer issue.
Is it possible to install php5/7 without openssl? 
I tried removing references to it in the php.rb package file but it still ends up installing it.

**Comment by Ulexus** [comment]
I have an Acer CB5-312T, arm64/armv8.  Same problem.  If the chromebrew openssl package is installed, it breaks any tool which uses openssl (wget, ssh, etc).

```
$ uname -a
Linux localhost 3.18.0-14582-g2fa17b5c810f #1 SMP PREEMPT Tue May 30 22:12:35 PDT 2017 aarch64 ARMv8 Processor rev 2 (v8l) GNU/Linux
```

**Comment by flyingP0tat0** [comment]
@bdodroid and @Ulexus have you tried @jam7's new toolchain in #614, as @lyxell mentioned?

**Comment by Ulexus** [comment]
@flyingP0tat0 No, that did not help.  I wiped my install and used the jam7/aarch64 branch. No change:

```
--2017-06-05 17:33:25--  https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.xz
Resolving cache.ruby-lang.org... 151.101.56.233
Connecting to cache.ruby-lang.org|151.101.56.233|:443... connected.
*** Error in `wget': free(): invalid pointer: 0xb2255360 ***
Checksum mismatch :/ try again
```

**Comment by jam7** [comment]
@Ulexus how about using https://raw.githubusercontent.com/jam7/chromebrew/openssl-arm-bin/packages/openssl.rb instead?  This include binary openssl package pre-built for armv7l.

**Comment by Ulexus** [comment]
@jam7 That worked!

**Comment by jam7** [comment]
@ulexus thanks for the result.  I compiled it on armv7l.  I guess the problem is in openssl build methods.  It may confuse how to make openssl correctly since chromeos uses 32bit architecture althouh system says aarch64.

**Comment by Ulexus** [comment]
@jam7 I had never even checked, but you are quite correct; the system binaries appear to be 32-bit ARM EABI5.  That would very likely explain the problem (and your solution).

**Comment by thedamian** [comment]
So do we need a different compilation or binary to suppose 64bit arm chromebooks? @jam7  @ulexus

**Comment by Ulexus** [comment]
@thedamian The issue is basically just as @jam7 mentioned:  it's a 64-bit kernel, but all of the userspace libraries and binaries are 32-bit.  Until that changes, then, we need to build 32-bit binaries and libraries on Arm64.

The problems with doing that:
  - no idea if it is universal that all 64-bit Arm chromebooks use 32-bit tooling
  - no way of knowing if/when a ChromeOS distribution is released which uses 64-bit tooling
