### ISSUE TITLE
Anyway to choose installation directory

### ISSUE THREAD

**Issue by Melab** [skycocker/chromebrew#666]
I don't want Chromebrew messing with my portage-installed files, so is there anyway I can change the installation location, like maybe to `/usr/local/crew`, in such a way that it won't get screwed by updating Chromebrew?

**Comment by jam7** [comment]
Just info.  Chromebrew has no way to choose the install directory yet.  We discussed it little in #536.

**Comment by lyxell** [comment]
Closing in favour of #536
