### ISSUE TITLE
/bin/bash: /usr/local/lib64/libc.so.6: version `GLIBC_2.33' not found (required by /bin/bash) /bin/bash: /usr/local/lib64/libc.so.6: version `GLIBC_2.33' not found (required by /bin/bash)

### ISSUE THREAD

**Issue by him5** [skycocker/chromebrew#6660]
## Description
I'm not sure if chromebrew is causing this, but for some reason I can't even access the shell anymore. bash is broken for both root and chronos.

Chrome OS: 98.0.4758.67 (Official Build) beta (64-bit)

![Screenshot 2022-01-27 5 57 50 AM](https://user-images.githubusercontent.com/50527029/151354523-9fe4ab74-2fd3-4ffe-83a6-ce218acbae48.png)

**Comment by him5** [comment]
The OS works, I just can't run any commands anymore

**Comment by supechicken** [comment]
See #6643

**Comment by supechicken** [comment]
Could you try the following:
```bash
LD_LIBRARY_PATH='' /bin/bash
```

This should bypass all libraries provided by chromebrew

**Comment by him5** [comment]
![Screenshot 2022-01-29 8 01 00 PM](https://user-images.githubusercontent.com/50527029/151683819-59aa65eb-892b-467f-87ca-da2a0b1bf694.png)

**Comment by satmandu** [comment]
`LD_LIBRARY_PATH=/usr/lib64:/lib64 /bin/bash` should work.

**Comment by supechicken** [comment]
You may need to clear the `~/.bashrc` file by running `echo > ~/.bashrc`

**Comment by satmandu** [comment]
Also, no promises, but this might work for you to fix your system:

```
LD_LIBRARY_PATH=/usr/lib64 /usr/bin/curl -Ls https://gitlab.com/api/v4/projects/26210301/packages/generic/glibc/2.33_x86_64/glibc-2.33-chromeos-x86_64.tpxz -o /tmp/glibc-2.33-chromeos-x86_64.tpxz
LD_LIBRARY_PATH=/usr/lib64 tar -Ipixz -xf /tmp/glibc-2.33-chromeos-x86_64.tpxz --exclude=dlist --exclude=filelist -C /
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew update
crew postinstall glibc ; crew postinstall glibc
```
