### ISSUE TITLE
libudev.h missing when compiling stuff manually. Is there any way to install with crew?

### ISSUE THREAD

**Issue by trusktr** [skycocker/chromebrew#667]
I was running make on some source code, and got this:

```
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
```

Just curious if there's anything I can install with crew to get past that?

**Comment by flyingP0tat0** [comment]
(lib)udev is part of freedesktops systemd. Thats the only thing I can tell you at the moment. Maybe you take a look at its docs or clone the git repo and see if you can compile some stuff. But it does not look like chromebrew provides something like that.

**Comment by lyxell** [comment]
Libudev seems to be found in the source of https://www.freedesktop.org/software/systemd/
`./src/libudev`
