### ISSUE TITLE
"No F77 compiler found" when installing r

### ISSUE THREAD

**Issue by wangguansong** [skycocker/chromebrew#668]
When installing r, it exited with a configure error "No F77 Compiler found".
I thought gcc covers f77. Anyway, is there an available package for this in crew?

**Comment by jam7** [comment]
#662 adds gfortran also.  I could compile r with it.  Please apply #662 by hand or wait until the merge.

**Comment by jam7** [comment]
#662 is merged.  so, I think you can compile R now.  Please close this issue if it works.  Thanks.

**Comment by wangguansong** [comment]
I tried again, it passed f77 checking, while stopped at zlib:

`checking if zlib version >= 1.2.5... no
checking whether zlib support suffices... configure: error: zlib library and headers are required
r failed to install: `./configure --with-x=no` exited with 1`

**Comment by jam7** [comment]
you can install zlib by typing `crew install zlibpkg`.  you will need `pcre` package also.

**Comment by wangguansong** [comment]
I added zlibpkg, which is already installed, and pcre. Then I tried again and got the same error.

**Comment by jam7** [comment]
Ya.  R-3.3.2 has a problem in the way to recognize zlib version.  It is fixed in R-3.4.0.  So, apply #683 first please.

**Comment by wangguansong** [comment]
Success! Thanks!
