### ISSUE TITLE
I pressed ctrl+c while building something. How to clean up?

### ISSUE THREAD

**Issue by trusktr** [skycocker/chromebrew#671]
If I ctrl+c out of an installation, what files might still be laying around that I should clean up?

**Comment by jam7** [comment]
Nothing.  Theoretically, all temporary files are created under /usr/local/tmp/crew and removed by ctrl+c.

If you use `keep` option or a given package file has problems, it is different story, though.

**Comment by trusktr** [comment]
> If you use keep option or a given package file has problems, it is
different story, though.

Hey Kazushi, where is stuff left in that case? Same place?

**Comment by jam7** [comment]
In that case, stuff is left under temporary directory, `/usr/local/tmp/crew`.
