### ISSUE TITLE
Cannot enter dev mode shell after v98 glibc update

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#6729]
The `LD_LIBRARY_PATH` variable will be exported in `crosh> shell` command, that means `/bin/bash` will always starts with the `glibc` in `/usr/local/lib64`. Due to an incompatible `libc.so.6` version, `/bin/bash` will throw an `GLIBC_2.33' not found` error.

Unlike #6660, it just exits immediately and fallback to `crosh` on my system. Then I fixed it by deleting all files listed in `/usr/local/etc/crew/meta/glibc.filelist` in another OS. 

Does there have a way to prevent crew binaries from loading before the main shell loads?

**Comment by satmandu** [comment]
glibc now uses the system `libc.so.6` via postinstall symlinking. Is that not working? I think the glibc update needs to happen before the M98 update for that to work though.
