### ISSUE TITLE
Install fails on docbook_xsl (xmlcatalog: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zopolis4** [skycocker/chromebrew#6737]
## Description
While installing chromebrew on a rooted Asus C100P, the install script errored out while trying to install `docbook_xsl`. `crew` was still installed, but I am unable to upgrade packages or continue the installation.

Command:
```shell
curl -Ls git.io/vddgY | bash
```

Output :
(This is where it errored out, everything had installed successfully up until this point, most recently gcc)
```shell
docbook_xsl: The DocBook XSL Stylesheets package contains XSL stylesheets. These are useful for performing transformations on XML DocBook files.
Precompiled binary available, downloading...
[###########################################################################################################################]   6.73 KB 100%
Docbook_xsl archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
xmlcatalog: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory
/usr/local/lib/crew/lib/package.rb:166:in `system': Command failed with exit 127: bash
docbook_xsl failed to install: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" LDFLAGS="-flto" bash -c xmlcatalog --noout --create /usr/local/etc/xml/catalog` exited with 127
```

## Versions and system information
chromebrew: 1.22.8

ChromeOS: ```CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6772344
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={432FF9F1-4D2E-7E74-6F98-32E56E904BFB}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={432FF9F1-4D2E-7E74-6F98-32E56E904BFB}
CHROMEOS_RELEASE_BOARD=veyron_minnie-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=110
CHROMEOS_RELEASE_BUILDER_PATH=veyron_minnie-release/R84-13099.110.0
CHROMEOS_RELEASE_BUILD_NUMBER=13099
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=84
CHROMEOS_RELEASE_DESCRIPTION=13099.110.0 (Official Build) stable-channel veyron_minnie 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13099.110.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13099.110.0```

Model: Asus C100P

Architecture: armv7l

## Additional information
When trying to upgrade all packages `crew upgrade`, chromebrew once again errored out on `docbook_xsl`
```shell
chronos@localhost / $ crew upgrade
Updating packages...
curl: Command line tool and library for transferring data with URLs.
The following packages also need to be installed: 
docbook_xsl docbook_xml docbook_xml412 docbook_xml42 docbook_xml43 docbook_xml44 docbook_xml45 docbook_xml50 docbook_xml51 docbook_xsl_nons libunbound 
Do you agree? [Y/n] Y
Proceeding...
docbook_xsl: The DocBook XSL Stylesheets package contains XSL stylesheets. These are useful for performing transformations on XML DocBook files.
Precompiled binary available, downloading...
[###########################################################################################################################]   6.73 KB 100%
Docbook_xsl archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
xmlcatalog: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory
/usr/local/lib/crew/lib/package.rb:166:in `system': Command failed with exit 127: bash
docbook_xsl failed to install: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=gold" LDFLAGS="-flto" bash -c xmlcatalog --noout --create /usr/local/etc/xml/catalog` exited with 127
```

**Comment by Zopolis4** [comment]
Trying to reinstall (`curl -Ls git.io/vddgY | bash`) throws `curl: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory`, while trying to install `docbook_xsl` in any way leads to the same error.

**Comment by Zopolis4** [comment]
However, a full [uninstall](https://github.com/skycocker/chromebrew/wiki/How-to-remove-chromebrew) and re-install (`curl -Ls git.io/vddgY | bash`) works perfectly!

**Comment by satmandu** [comment]
Fantastic!
