### ISSUE TITLE
tcpdump need a older libcrypto.so file

### ISSUE THREAD

**Issue by pengxy72** [skycocker/chromebrew#6755]
## Description
After installation of tcpdump pacakage, run it, got error message:
tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

## Versions and system information
chromebrew: `crew --version`
1.22.10

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_RELEASE_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_BOARD_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=OTHER
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_DESCRIPTION=94.4.4 (Developer Build - neverware) stable-channel chromeover64
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_RELEASE_BRANCH_NUMBER=90
CHROMEOS_RELEASE_BUILD_NUMBER=14150
CHROMEOS_RELEASE_CHROME_MILESTONE=94
CHROMEOS_RELEASE_PATCH_NUMBER=2021_12_02_0741
CHROMEOS_RELEASE_VERSION=94.4.4
GOOGLE_RELEASE=94.4.4

Model: YOUR MODEL HERE
Google pixelbook 2013 

Architecture: `uname -m`
x86_64

## Additional information
There are some libcrypto.so files:
/usr/local/lib64: 
   libcrypto.a  libcrypto.so  libcrypto.so.1.1

**Comment by pengxy72** [comment]
After create a symbolic link to libcrypto.so.1.1, run tcpdump, got another error:

chronos@localhost /usr/local/lib64 $ sudo tcpdump -h
tcpdump version 4.9.2
libpcap version 1.10.0 (with TPACKET_V3)
tcpdump: symbol lookup error: tcpdump: undefined symbol: SSLeay_version

**Comment by supechicken** [comment]
Hello

**Comment by supechicken** [comment]
Hello, seems the prebuilt binaries for this package is generated before we decided to switch from libressl to openssl. Could you try to rebuild the package:
```
crew reinstall -s tcpdump
```

**Comment by pengxy72** [comment]
Yes! It works.
Thank you very much. @superchicken

**Comment by Superchicken** [comment]
@pengxy72 I think you meant @supechicken :)
