### ISSUE TITLE
/usr/local/bin/rsync command not found

### ISSUE THREAD

**Issue by mjonsson1986** [skycocker/chromebrew#6823]
not sure when this happen. maybe after the latest chrome os canary..
when the glibc changes..
how to reinstall rsync?
the reinstall command dont work just because rsync are missing
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
your command here
```

Output:
```shell
output
of
your
command
here
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@mjonsson1986: We do not support non-stable versions of ChromeOS.  See https://github.com/skycocker/chromebrew#installation.
