### ISSUE TITLE
failed to get urandom (RuntimeError)

### ISSUE THREAD

**Issue by s0lid** [skycocker/chromebrew#6854]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
I just installed chromebrew using the instrucition

If you executed a specific command:
```shell
chronos@localhost / $ crew search top
```

Output:
```shell
/usr/local/lib64/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib64/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib64/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib64/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib64/ruby/3.1.0/resolv.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib64/ruby/3.1.0/resolv-replace.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib64/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/crew/lib/downloader.rb:4:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_RELEASE_BOARD=peppy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=92
CHROMEOS_RELEASE_BUILDER_PATH=peppy-release/R76-12239.92.0
CHROMEOS_RELEASE_BUILD_NUMBER=12239
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=76
CHROMEOS_RELEASE_DESCRIPTION=12239.92.0 (Official Build) stable-channel peppy 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12239.92.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12239.92.0

Model: Acer C720

Architecture: `uname -m`
x86_64

## Additional information
Mention things we might need to know. Like:

The error also shown while installing after the "Updating crew package information..."

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by supechicken** [comment]
It is very likely that the `/dev/urandom` device is missing from your system, could you provide the output of `ls -la /dev/urandom`?

**Comment by supechicken** [comment]
By the way, we don't use `securerandom` anymore since months ago. Could you try to reinstall Chromebrew also? (It seems that you are using an older version of crew which is still using the `securerandom` module)

**Comment by saltedcoffii** [comment]
Because this is a very old version of chromebrew, I'm closing this issue as invalid. Try either reinstalling chromebrew by running `rm /usr/local/* /usr/local/.*` and then restarting your computer and running `curl -L git.io/vddgY | bash`, or running `crew update` if you can. In the future, be sure to run `crew update` every so often. Hope this helps! <3
