### ISSUE TITLE
[sommelier] No status on start

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6864]
When you run `startsommelier` there is no feedback to indicate the service started successfully.  Earlier releases returned a success message.  I think we should try to restore this behavior.

**Comment by supechicken** [comment]
I think it is better to make it silent since we can always use `sommelierd --status` to check the status. (If we can confirm it is fully working and stable, there is no reason that keeping this kind of verbosely "debug message" :) )

**Comment by uberhacker** [comment]
Maybe we differ but I prefer verbosity. :)

**Comment by uberhacker** [comment]
My workaround is to add to `~/.bashrc` the following:
```
[ -f /usr/local/bin/sommelierd ] && sommelierd --status
```
