### ISSUE TITLE
Sommelier just won't start (how to run apps with sommelier?)

### ISSUE THREAD

**Issue by adithv08** [skycocker/chromebrew#6868]
## Description
I installed sommelier to open a gui app, but the gui app says no display found and sommelier says it failed to start.
Input:
```shell
startsommelier
```

Output:
```shell
chronos@localhost / $ startsommelier
some sommelier processes failed to start
sommelier processes running:  
 
chronos@localhost / $ 
```

## Versions and system information
chromebrew: `1.23.2`

ChromeOS: `CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8186398
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={495DCB07-E19A-4D7D-99B9-4710011A65B1}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={495DCB07-E19A-4D7D-99B9-4710011A65B1}
CHROMEOS_RELEASE_BOARD=nami-signed-mp-v5keys
CHROMEOS_RELEASE_BRANCH_NUMBER=41
CHROMEOS_RELEASE_BUILDER_PATH=nami-release/R99-14469.41.0
CHROMEOS_RELEASE_BUILD_NUMBER=14469
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=99
CHROMEOS_RELEASE_DESCRIPTION=14469.41.0 (Official Build) stable-channel nami 
CHROMEOS_RELEASE_KEYSET=mp-v5
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14469.41.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14469.41.0
`

Model: SONA

Architecture: `x86_64`

## Additional information
I am attempting to run Pixelorama.

If anyone could tell me what went wrong and how to properly set up sommelier, it would be helpful.

**Comment by supechicken** [comment]
Hi, seems you are using the previous version of `sommelier`, could you try the following:
```
crew update
crew reinstall sommelier
source /usr/local/etc/profile
```
(this will update sommelier to latest version)

**Comment by uberhacker** [comment]
It probably wouldn't hurt to run `crew upgrade` too if more package updates were reported by `crew update`.

**Comment by adithv08** [comment]
Ok, thanks! It updated, but Pixelorama still says:
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
ERROR: X11 Display is not available
   at: initialize (platform/x11/os_x11.cpp:127)
How would I get sommelier to work?

**Comment by adithv08** [comment]
I found I need to specify a few options, `sommelier --x-display=$DISPLAY /usr/local/pixelorama/linux-64bit/Pixelorama.x86_64`
I tried finding these libraries using `crew whatprovides` but couldn't find anything. Where is this library?
Output: 
```
chronos@localhost / $ sommelier --x-display=$DISPLAY /usr/local/pixelorama/linux-64bit/Pixelorama.x86_64 
warning: virtwl-dmabuf driver not supported by host, using virtwl instead
/usr/local/bin/Xwayland: error while loading shared libraries: libxcvt.so.0: cannot open shared object file: No such file or directory
chronos@localhost / $ 
```

**Comment by adithv08** [comment]
Never mind I found the file thanks for your help!
