### ISSUE TITLE
Catch 22 installing Android Studio

### ISSUE THREAD

**Issue by adithv08** [skycocker/chromebrew#6886]
## Description
Catch 22 installing Android Studio. jdk11 is a dependency but requires to be built from source. Building from source brings up overwriting issues with jdk8. Uninstalling jdk8 and building jdk11 installs jdk8 as a dependency. Forgetting all of that and installing Android studio and jdk11 as a dependency brings up 404 not found

## Versions and system information
fatal: not a git repository (or any parent up to mount point /media/fuse)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.4.172-17736-gfddbc46e9604`

- Chromebrew version: `1.23.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ``

- OS variant: `Chrome OS`
- OS version: `nami-release/R99-14469.41.0`
- OS channel: `stable-channel`
## Additional information
also updated using crew update

**Comment by uberhacker** [comment]
Thank you for the feedback @adithv08.  This is definitely a bug because there are no dependencies in the jdk11 package.  @supechicken?
