### ISSUE TITLE
Dev-channel LD_LIBRARY_PATH does not include /usr/local/lib

### ISSUE THREAD

**Issue by dihuta** [skycocker/chromebrew#689]
I install the lasted chromebrew and install nano via command: crew install nano. 
Then run nano, it display this error:

`nano: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory`

Please help me.
Thank you.

**Comment by jam7** [comment]
What does `crew whatprovides libncursesw` show?  And what does `ls -l /usr/local/lib*/libncurses*` show?  And please let us know your machine's architecture also which is shown by `uname -m`.

**Comment by dihuta** [comment]
>> crew whatprovides libncursesw
`chronos@localhost / $ crew whatprovides libncursesw
ncursesw: /usr/local/lib/libncursesw.a
ncursesw: /usr/local/lib/libncursesw.so
ncursesw: /usr/local/lib/libncursesw.so.6
ncursesw: /usr/local/lib/libncursesw.so.6.0

Total found: 4
chronos@localhost / $ uname
x86_64
ls -l /usr/local/lib*/libncurses*
lrwxrwxrwx. 1 chronos chronos     15 May 28 18:01 /usr/local/lib/libncurses.so -> libncurses.so.6
lrwxrwxrwx. 1 chronos chronos     17 May 28 18:01 /usr/local/lib/libncurses++.so -> libncurses++.so.6
lrwxrwxrwx. 1 chronos chronos     17 May 28 18:01 /usr/local/lib/libncurses.so.6 -> libncurses.so.6.0
lrwxrwxrwx. 1 chronos chronos     19 May 28 18:01 /usr/local/lib/libncurses++.so.6 -> libncurses++.so.6.0
-rwxr-xr-x. 1 chronos chronos 449792 May 28 18:01 /usr/local/lib/libncurses.so.6.0
-rwxr-xr-x. 1 chronos chronos 315672 May 28 18:01 /usr/local/lib/libncurses++.so.6.0
-rw-r--r--. 1 chronos chronos 689462 May 28 18:00 /usr/local/lib/libncurses++w.a
-rw-r--r--. 1 chronos chronos 870760 May 28 18:00 /usr/local/lib/libncursesw.a
lrwxrwxrwx. 1 chronos chronos     18 May 28 18:00 /usr/local/lib/libncurses++w.so -> libncurses++w.so.6
lrwxrwxrwx. 1 chronos chronos     16 May 28 18:00 /usr/local/lib/libncursesw.so -> libncursesw.so.6
lrwxrwxrwx. 1 chronos chronos     20 May 28 18:00 /usr/local/lib/libncurses++w.so.6 -> libncurses++w.so.6.0
lrwxrwxrwx. 1 chronos chronos     18 May 28 18:00 /usr/local/lib/libncursesw.so.6 -> libncursesw.so.6.0
-rwxr-xr-x. 1 chronos chronos 316784 May 28 18:00 /usr/local/lib/libncurses++w.so.6.0
-rwxr-xr-x. 1 chronos chronos 529808 May 28 18:00 /usr/local/lib/libncursesw.so.6.0

**Comment by jam7** [comment]
Thanks.  Don't you set LD_LIBRARY_PATH wrongly?  My LD_LIBRARY_PATH on x86_64 is below by default.
```
$ echo $LD_LIBRARY_PATH 
/usr/local/lib:/usr/local/lib64
```

**Comment by jam7** [comment]
BTW, if you are having this problem with sudo, it is what it should be.  You need to use `sudo -i` to use `nano` as root.

**Comment by dihuta** [comment]
I din't see LD_LIBRARY_PATH. I will modify it.
Thank you.

**Comment by littlewey** [comment]
Thanks! after switch chanel from stable to others, my $LD_LIBRARY_PATH  was reset to  /usr/local/lib64 and faced similar issues.
After restoring it as:
/usr/local/lib:/usr/local/lib64
the issue gone.

**Comment by flyingP0tat0** [comment]
Exactly the same here! I switched to dev channel and face this issue. Maybe it's worth noting on the `README`?

**Comment by jam7** [comment]
It's headache.  Do you guys have xzutils out of the box?  Once @phlie explains the latest one has no xzutils also at #698.

**Comment by thedamian** [comment]
I'm guessing this is solved. 

Once it is please don't wait for me to close these comments. Close them yourself: @dihuta

**Comment by lyxell** [comment]
@thedamian This issue is not solved.

**Comment by flyingP0tat0** [comment]
I guess the best approach would be to check `LD_LIBRARY_PATH` at setup?

**Comment by jam7** [comment]
FYI, beta (60.0.3112.41) doesn't have `/usr/local/lib` in LD_LIBRARY_PATH already.

**Comment by jam7** [comment]
There are several approaches.

1. tell user to modify .bash_proffile
1. change all package files to use --prefix and --libdir
1. make a symbolic link from /usr/local/lib64 to lib at setup

I think 2nd option is not so bad, since we only need to modify package files of library.  We can modify crew to prepare new constant like `CREW_LIB_PREFIX` and package files like `./configure --libdir=#{CREW_LIB_PREFIX}`.

**Comment by jam7** [comment]
Just an update.  As you guys already notice, Chrome OS 60 is on the road.  We modified several packages to install their libraries into `/usr/local/lib64`, but those are not enough.  If you find problems, you can:

1. Simply modify LD_LIBRARY_PATH environment to include `/usr/local/lib`
2. Submit PR to modify install directory to correct problems you've found.

Either way is fine.  Thanks.

**Comment by uberhacker** [comment]
If we include the `--prefix=#{CREW_PREFIX}` and `--libdir=#{CREW_LIB_PREFIX}` configure options when compiling packages, then this problem should go away.  Some packages may not have a configure script which may require the sed command to change the locations in the Makefile.  Several packages use this technique already.
