### ISSUE TITLE
Firefox's UI is too big

### ISSUE THREAD

**Issue by nchristopher** [skycocker/chromebrew#6937]
## Description

Firefox's UI scale is too big compared to the rest of Chrome OS.

![image](https://user-images.githubusercontent.com/58091943/161395240-b6434bf4-6120-423e-982f-108c8974dd83.png)

## Additional information

According to Mozilla, Firefox follows the UI scale of the System, but Chrome OS doesn't implement this option.

**Comment by satmandu** [comment]
Try putting `SCALE=0.5` in `~/.sommelier.env`

**Comment by uberhacker** [comment]
Setting the `SCALE` environment variable doesn't appear to work.  Try this.  Enter `about:config` in the browser address bar and search for `layout.css.devPixelsPerPx`.  Set to a lower value.

**Comment by supechicken** [comment]
This is because of a workaround in the sommelier package (the DPI returned by `xdpyinfo` is incorrect on my system, `${dpi_returned_by_xdpyinfo}/ 4 * 5` fixed it), could you provide the output of `uname -a`? (seems the DPI issue only happened on `x86_64`)

In `/usr/local/etc/sommelierrc`, change the following:
```patch
- DPI="$(( $(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}") / 4 * 5 ))"
+ DPI="$(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}")"
```

**Comment by supechicken** [comment]
@satmandu @uberhacker Does this issue appears on your system also? (without configuring any env variables manually) (let me confirm that the DPI issue is just on my system or on all `x86_64` systems :) )

**Comment by satmandu** [comment]
> This is because of a workaround in the sommelier package (the DPI returned by `xdpyinfo` is incorrect on my system, `${dpi_returned_by_xdpyinfo}/ 4 * 5` fixed it), could you provide the output of `uname -a`? (seems the DPI issue only happened on `x86_64`)
> 
> In `/usr/local/etc/sommelierrc`, change the following:
> ```patch
> - DPI="$(( $(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}") / 4 * 5 ))"
> + DPI="$(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}")"
> ```

This is a chicken and egg issue, no? Xdpyinfo won't run unless there is an xserver running, which requires sommelier to be started.

**Comment by nchristopher** [comment]
> This is because of a workaround in the sommelier package (the DPI returned by `xdpyinfo` is incorrect on my system, `${dpi_returned_by_xdpyinfo}/ 4 * 5` fixed it), could you provide the output of `uname -a`? (seems the DPI issue only happened on `x86_64`)
> 
> In `/usr/local/etc/sommelierrc`, change the following:
> 
> ```diff
> - DPI="$(( $(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}") / 4 * 5 ))"
> + DPI="$(xdpyinfo | sed -n -E "/dots per inch/{s|^.* ([0-9]+)x.*$|\\1|g; p}")"
> ```

Output of `uname -a`:
```
Linux localhost 4.14.262-18687-g0d37a4afae7b #1 SMP PREEMPT Sat Mar 19 16:40:06 PDT 2022 x86_64 Intel(R) Celeron(R) N4020 CPU @ 1.10GHz GenuineIntel GNU/Linux
```

Changing that line in `/usr/local/etc/sommelierrc` seems to have fixed the issue.

**Comment by supechicken** [comment]
> This is a chicken and egg issue, no? Xdpyinfo won't run unless there is an xserver running, which requires sommelier to be started.

The `sommelierrc` file will run by sommelier after the Xwayland instance starts
