### ISSUE TITLE
startsommelier uses env feature not available in older coreutils

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#6961]
Coreutils 8.24 does not support the `-S` option, and this is the default coreutils `/usr/bin/env` found on many chromebooks.

This causes a startup error whenever `startsommelier` is run.

**Comment by satmandu** [comment]
Consider using a polyglot script?

See https://unix.stackexchange.com/questions/361794/why-am-i-able-to-pass-arguments-to-usr-bin-env-in-this-case/361796#361796

**Comment by supechicken** [comment]
> Consider using a polyglot script?
> 
> See https://unix.stackexchange.com/questions/361794/why-am-i-able-to-pass-arguments-to-usr-bin-env-in-this-case/361796#361796

Actually `ruby` has supported this internally :)
```
-x[directory]
Tells Ruby that the script is embedded in a message. Leading garbage will be discarded until the first that starts with ''#!'' and contains the string, ''ruby''. Any meaningful switches on that line will applied. The end of script must be specified with either EOF, ^D (control-D), ^Z (control-Z), or reserved word __END__. If the directory name is specified, Ruby will switch to that directory before executing script.
```

It can be used like this:
```bash
#!/bin/bash -eu
exec ruby -x "${0}" "${@}"

#!ruby
# ruby code here
```

**Comment by supechicken** [comment]
I decided to remove the `--disable-all` argument because polyglot scripts will break Github's syntax highlighting... (also in my code editor)
