### ISSUE TITLE
GCC internal compiler error 

### ISSUE THREAD

**Issue by tempdc** [skycocker/chromebrew#697]
Hi, when I try to compile qemu, I am getting an internal compiler error. Any hint on what to do to address?

Making all in test
  CC       utils.lo
  CC       utils-prng.lo
utils-prng.c: In function ‘prng_randmemset_r’:
utils-prng.c:272:6: internal compiler error: in emit_move_insn, at expr.c:3609
 void prng_randmemset_r (prng_t                  *prng,
      ^

utils-prng.c:272:6: internal compiler error: Aborted
gcc: internal compiler error: Aborted (program cc1)
../libtool: line 1749: 10309 Aborted                 (core dumped) gcc -DHAVE_CONFIG_H -I. -I.. -I../pixman -I../pixman -fopenmp -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -g -fPIC -m32 -Wall -Wdeclaration-after-statement -fno-strict-aliasing -fvisibility=hidden -pthread -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -g -fPIC -m32 -Wall -Wdeclaration-after-statement -fno-strict-aliasing -fvisibility=hidden -MT utils-prng.lo -MD -MP -MF .deps/utils-prng.Tpo -c utils-prng.c -o utils-prng.o
make[3]: *** [Makefile:1044: utils-prng.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:503: all-recursive] Error 1
make[1]: *** [Makefile:410: all] Error 2
make: *** [Makefile:330: subdir-pixman] Error 2
qemu failed to install: `make -j2` exited with 2

**Comment by lyxell** [comment]
Is this on Samsung Chromebook Plus?

**Comment by tempdc** [comment]
I am using Cloudready 32 bit version 56 on a x686 platform. I used the standard ruby file that download qemu 2.9.0.  I have made some attempts with lower versions (2.7.1 and 2.8.1) with the same error.

**Comment by flyingP0tat0** [comment]
Maybe try to install the pixman package (as the error seems to be connected to the compilation of pixman) and see what happens could be a good starting point.

**Comment by tempdc** [comment]
Unfortunately, still get the same error compiling pixman...

make[2]: Entering directory '/usr/local/tmp/crew/pixman-0.34.0.tar.gz.dir/pixman-0.34.0/test'
  CC       utils.lo
  CC       utils-prng.lo
utils-prng.c: In function ‘prng_randmemset_r’:
utils-prng.c:272:6: internal compiler error: in emit_move_insn, at expr.c:3609
 void prng_randmemset_r (prng_t                  *prng,
      ^

utils-prng.c:272:6: internal compiler error: Aborted
gcc: internal compiler error: Aborted (program cc1)
../libtool: line 1749: 12935 Aborted                 (core dumped) gcc -DHAVE_CONFIG_H -I. -I.. -I../pixman -I../pixman -I/usr/local/include/libpng16 -fopenmp -g -O2 -Wall -Wdeclaration-after-statement -Wno-unused-local-typedefs -fno-strict-aliasing -fvisibility=hidden -pthread -g -O2 -Wall -Wdeclaration-after-statement -Wno-unused-local-typedefs -fno-strict-aliasing -fvisibility=hidden -MT utils-prng.lo -MD -MP -MF .deps/utils-prng.Tpo -c utils-prng.c -fPIC -DPIC -o .libs/utils-prng.o
make[2]: *** [Makefile:1125: utils-prng.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/local/tmp/crew/pixman-0.34.0.tar.gz.dir/pixman-0.34.0/test'
make[1]: *** [Makefile:503: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/pixman-0.34.0.tar.gz.dir/pixman-0.34.0'
make: *** [Makefile:410: all] Error 2
pixman failed to install: `make -j2` exited with 2

**Comment by lyxell** [comment]
This is the source of prng_randmemset_r:
```c
/*
 * Fill memory buffer with random data. Flags argument may be used 
 * to tweak some statistics properties:
 *    RANDMEMSET_MORE_00        - set ~25% of bytes to 0x00 
 *    RANDMEMSET_MORE_FF        - set ~25% of bytes to 0xFF 
 *    RANDMEMSET_MORE_00000000  - ~25% chance for 00000000 4-byte clusters
 *    RANDMEMSET_MORE_FFFFFFFF  - ~25% chance for FFFFFFFF 4-byte clusters
 */
void prng_randmemset_r (prng_t                  *prng,  
                        void                    *voidbuf,
                        size_t                   size,   
                        prng_randmemset_flags_t  flags)  
{
    uint8_t *buf = (uint8_t *)voidbuf;
    if ((uintptr_t)buf & 15)
    {
        /* unaligned buffer */
        if (flags == 0)
            randmemset_internal (prng, buf, size, 0, 0);
        else if (flags == RANDMEMSET_MORE_00_AND_FF)
            randmemset_internal (prng, buf, size, RANDMEMSET_MORE_00_AND_FF, 0);
        else    
            randmemset_internal (prng, buf, size, flags, 0);
    }
    else    
    {
        /* aligned buffer */
        if (flags == 0)
            randmemset_internal (prng, buf, size, 0, 1);
        else if (flags == RANDMEMSET_MORE_00_AND_FF)
            randmemset_internal (prng, buf, size, RANDMEMSET_MORE_00_AND_FF, 1);
        else    
            randmemset_internal (prng, buf, size, flags, 1);
    }
}
```

**Comment by lyxell** [comment]
Can you give an output of `gcc -v`?

**Comment by flyingP0tat0** [comment]
I have no time to test this at the moment, but you could try to add the `--without-pixman` configuration flag to the qemu script at `./configure`. If that works we can put it into the package, we don't need graphics support.

**Comment by tempdc** [comment]
GCC version details:

chronos@localhost / $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/i686-cros-linux-gnu/4.9.x/lto-wrapper
Target: i686-cros-linux-gnu
Configured with: /src/gcc-4.9.x/configure --prefix=/usr/local --build=x86_64-linux-gnu --host=i686-cros-linux-gnu --target=i686-cros-linux-gnu --enable-languages=c,c++,fortran --disable-static --with-gmp-include=/opt/cross/i686-cros-linux-gnu/usr/local/include --with-gmp-lib=/opt/cross/i686-cros-linux-gnu/usr/local/lib --with-mpfr-include=/opt/cross/i686-cros-linux-gnu/usr/local/include --with-mpfr-lib=/opt/cross/i686-cros-linux-gnu/usr/local/lib --with-mpc-include=/opt/cross/i686-cros-linux-gnu/usr/local/include --with-mpc-lib=/opt/cross/i686-cros-linux-gnu/usr/local/lib --with-isl-include=/opt/cross/i686-cros-linux-gnu/usr/local/include --with-isl-lib=/opt/cross/i686-cros-linux-gnu/usr/local/lib --with-cloog-include=/opt/cross/i686-cros-linux-gnu/usr/local/include --with-cloog-lib=/opt/cross/i686-cros-linux-gnu/usr/local/lib --disable-multilib
Thread model: posix
gcc version 4.9.x 20150123 (prerelease) (GCC)

**Comment by tempdc** [comment]
Disabling Pixman does not appear to be the way to go as it remove system emulation...

Building from source, this may take a while...

ERROR: pixman disabled but system emulation or tools build
       enabled.  You can turn off pixman only if you also
       disable all system emulation targets and the tools
       build with '--disable-tools --disable-system'.

qemu failed to install: `./configure --without-pixman` exited with 1

Is there a way to try a version of GCC prior to 4.9?

**Comment by lyxell** [comment]
@tempdc Here's gcc-4.8.1
https://dl.dropboxusercontent.com/s/c06pcge8ogsqfcd/gcc-4.8.1-baseline-chromeos-i686.tar.gz

**Comment by tempdc** [comment]
Thank you, I tried to make it work but am getting errors as the compiler does not appear to be found and with the same configure options. 

Also, can you advise if you can compile pixman without error on a x86 platform with the new version?

**Comment by lyxell** [comment]
This seems to be a bug inside gcc itself, and not a bug originating from the chromebrew system. I would need to reproduce the bug myself to aid you in your troubleshooting.

**Comment by tempdc** [comment]
Agree with you... I suspect if it was posted , it means it was compiling with the previous gcc version. Is there a way to get the previous ruby file version of gcc (on maybe the libs)?

**Comment by lyxell** [comment]
Available via any commit before February 2017.
https://github.com/skycocker/chromebrew/commits/master/packages/gcc.rb

**Comment by tempdc** [comment]
thank you. same error results with gcc 4.9.x.

**Comment by jam7** [comment]
@tempdc If you can, please try https://github.com/jam7/chrome-cross/releases/download/v1.5/gcc-7.1.0-cc1.5-chromeos-i686.tar.xz.

**Comment by tempdc** [comment]
Can you indicate how I should install? I was modifying a ruby scrip to install but am getting another error when I try to compile pixman (version 0.34 in my test)

2017-06-05 09:36:23 (730 KB/s) - 'pixman-0.34.0.tar.gz' saved [878784/878784]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/pixman-0.34.0.tar.gz.dir/pixman-0.34.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
pixman failed to install: `./configure` exited with 77

**Comment by jam7** [comment]
Can you use the gcc directly and see error messages from that?  Maybe `gcc helloworld.c` or something?

**Comment by tempdc** [comment]
getting error when compiling heeloworld: /usr/local/libexec/gcc/i686-cros-linux-gnu/7.1.0/cc1: error while loading shared libraries: libisl.so.15: cannot open shared object file: No such file or directory

**Comment by jam7** [comment]
I said you may need to install isl also.  Did you install it?

**Comment by tempdc** [comment]
I installed the newer ISL and Pixman compiles now without error. No more internal compiler error! Will try with the current Pixman but should be fine as both were triggering an ICE. Thank you all for your support

**Comment by jam7** [comment]
Nice to hear that.  Thanks for testing.

**Comment by tempdc** [comment]
Closing, working fine with GCC 7.1

**Comment by jam7** [comment]
@tempdc don't you mind to try https://github.com/jam7/chrome-cross/releases/download/v1.6/gcc-4.9.4-cc1.6-chromeos-i686.tar.xz if you have time?  Since gcc 7.1 has a lot of conflicts like I descrbed in #715.  I'm going to release gcc 4.9.4 instead.  Thanks.

**Comment by tempdc** [comment]
Will I need to install isl for that version too? Let me know and will check after

**Comment by jam7** [comment]
this time it is not required.  thank you.
