### ISSUE TITLE
chsh: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FarelRA** [skycocker/chromebrew#6971]
## Description

I love zsh, and I want to use zsh on my ChromeOS
But, after I run:
```shell
sudo chsh -s $(which zsh)
```

This happened:
```
chsh: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

Due to this, now I can't login to root using ```sudo su```
But I can still login to root using ```sudo bash```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.11`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: ``
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.57.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8334839
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=57
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.57.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.57.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.57.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.57.0
***

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Install zsh with ```crew install zsh```
3. Change the shell with ```sudo chsh -s $(which zsh)```

## Other

I've tried to do this on my other ChromeOS but the same thing happens again

**Comment by supechicken** [comment]
Tips: Tools like `chsh` will not work on Chrome OS because the shell path is hardcoded in the `shell` command of `crosh`. Instead, you can add `exec zsh` to `~/.bashrc` (let `zsh` cover `bash` everytime)

**Comment by FarelRA** [comment]
> Tips: Tools like `chsh` will not work on Chrome OS because the shell path is hardcoded in the `shell` command of `crosh`. Instead, you can add `exec zsh` to `~/.bashrc` (let `zsh` cover `bash` everytime)

Yes, chsh does not work on chronos users but works on root users
