### ISSUE TITLE
Error trying to login to root with zsh when user chronos runs zsh as shell

### ISSUE THREAD

**Issue by FarelRA** [skycocker/chromebrew#6975]
## Description

Due to this issue #6971 #6972 and this pull #6974

When I try to log in as root with zsh as the default shell via the chronos user running zsh, I get an error similar to that problem

In the chronos user running zsh I run:
```shell
sudo su
```
Or this:
```shell
sudo zsh
```

I got this error:
```
$ sudo su
su: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```
and this:
```
$ sudo zsh
zsh: error while loading shared libraries: libgdbm.so.6: cannot open shared object file: No such file or directory
```

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Get #6974 pull request's changes locally with ```CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=zsh CREW_TESTING=1 crew update```
3. Install zsh with ```crew install zsh```
4. Change the root shell to zsh with ```sudo chsh -s $(which zsh)```
5. Run ```zsh```
6. Run ```sudo su``` or ```sudo zsh```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.11`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: `734ed5c: zsh -> 5.8.1`
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.57.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8334839
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=57
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.57.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.57.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.57.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.57.0
***

**Comment by satmandu** [comment]
That is because sudo is not preserving `LD_LIBRARY_PATH=/usr/local/lib64`

**Comment by FarelRA** [comment]
Is there a way to make sudo use ```LD_LIBRARY_PATH=/usr/local/lib64```

**Comment by satmandu** [comment]
Using patchelf cn fix this. I should have a PR up to fix this later today...

**Comment by satmandu** [comment]
Try 
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=patchelf_crew CREW_TESTING=1 crew update
crew upgrade zsh
sudo zsh
```

**Comment by FarelRA** [comment]
> Try
> 
> ```
> CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=patchelf_crew CREW_TESTING=1 crew update
> crew upgrade zsh
> sudo zsh
> ```

Yes, this fixes the ```sudo zsh```
But what about ```sudo su```?

**Comment by satmandu** [comment]
We may have to recompile `util_linux` to fix that.

Try `crew reinstall -s util_linux`

**Comment by FarelRA** [comment]
When I try to recompile util_linux, I get an error:
```/tmp/ccj7w6Tb.ltrans0.ltrans.o:<artificial>:function main: error: undefined reference to 'crypt'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:7734: sulogin] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/local/tmp/crew/util_linux.20220416015608.dir/util-linux-2.36.2'
make[1]: *** [Makefile:13798: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/util_linux.20220416015608.dir/util-linux-2.36.2'
make: *** [Makefile:5898: all] Error 2
/usr/local/lib/crew/lib/package.rb:258:in `system': Command failed with exit 2: bash
util_linux failed to install: `CFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " CXXFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FCFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " FFLAGS="-O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold " LDFLAGS="-flto " bash -c make -j2` exited with 2
```
