### ISSUE TITLE
Can't open java gui apps

### ISSUE THREAD

**Issue by FarelRA** [skycocker/chromebrew#6976]
## Description

When I try to run some .jar application that provides a gui, I get an error output

I run:
```shell
java -jar example.jar 
```

I got this error:
```
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Install jdk for java ```crew install jdk8```
3. Run ```java -jar example.jar```

## Other
I've tried to do with other versions of jdk and also with other apps but same thing happen again

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.11`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: `734ed5c: zsh -> 5.8.1`
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.57.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8334839
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=57
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.57.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.57.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.57.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.57.0
***

**Comment by satmandu** [comment]
Run `startsommelier` first?

You need `sommelier` installed for X11 apps to work.

**Comment by FarelRA** [comment]
```sommelier``` has started but the same problem still occurs

**Comment by FarelRA** [comment]
Thanks for the great work

## This can be fixed with 

1. Install ```sommelier```
2. Start sommelier ```startsommelier```
3. Export DISPLAY ```export DISPLAY=:0.0```

**Comment by satmandu** [comment]
Ah! But are you using zsh? The env variable isn't set automatically unless you use bash, IIRC.

Patches welcome!

**Comment by FarelRA** [comment]
Yes I use zsh
