### ISSUE TITLE
Installing .xz Programs Such as EMACS

### ISSUE THREAD

**Issue by phlie** [skycocker/chromebrew#698]
I tried installing EMACS but as soon as it gets to  glibc-2.23-cc1.3-chromeos-x86_64.tar.xz it says "tar (child): xz: Cannot exec: No such file or directory".

I have looked everywhere but can't figure it out. I tried to get a Arch Linux package to open .xz files but it was just a couple Bash scripts so that may be the error but on chromebrew I cannot find a way to open .xz. There doesn't seem to be a way to upgrade tar using Crew.

It worked fine installing but below I get the message "/usr/local/lib/ruby/2.0.0/fileutils.rb:1551:in `stat': No such file or directory - dlist (Errno::ENOENT)".

**Comment by jam7** [comment]
We have xz as `/usr/bin/xz` as a part of Chromeos, so we don't have dependency for that in emacs package.  If your system doesn't, you can install xzutils separately.  It installs `/usr/local/bin/xz`.

**Comment by phlie** [comment]
I tried that but xvutils still relies "glibc-2.23-cc1.3-chromeos-x86_64.tar.xz" so it gives the same error. I don't have /usr/bin/xz at all running the latest version of Chromeos developer edition with an Asus 301C. How could I get that.

**Comment by jam7** [comment]
Thank you for the info.  The easiest way is to prepare xzutils binary package and distribute it.

For the meantime, you can use any of binary packages available at my page, https://github.com/jam7/chromebrew/releases.  I put simple tar files for xzutils there.  You can extract xz and put it in `/usr/local/bin`.

**Comment by phlie** [comment]
Thanks.

**Comment by jam7** [comment]
Update: place `xz` in `/usr/local/bin` and place `liblzma.so*` at `/usr/local/lib`.

**Comment by phlie** [comment]
I think I almost have it working except now it gives the error "/usr/local/bin/xz: 1: Syntax error: word unexpected (expecting ")")".

Thanks for all the help.

**Comment by jam7** [comment]
Which architecture are you using?  `uname -m` shows it.

`xz` is binary file, so chromeos should not show such error message if the binary is for your architecture.  I wonder you may extract wrong tar file or I put wrong tar file there.

**Comment by phlie** [comment]
uname -m says it is x86_64. I first tried the ARM out of mistake but tried the x86_64 and it gives the same error. I did the command "cp local/ /usr/" while in the usr directory you gave me and it works. Thanks.
