### ISSUE TITLE
Failled to install vlc and spotify  with flatpak

### ISSUE THREAD

**Issue by FarelRA** [skycocker/chromebrew#6982]
## Description

When i try to install the app via flatpak i get an error
I've tried to install vlc and spotify, and they get the same error

I run:
```shell
flatpak install flathub com.spotify.Client
```

I got this error:
```
(/usr/local/libexec/flatpak/flatpak install:6196): GLib-GIO-CRITICAL **: 08:39:15.915: g_file_get_child: assertion '!g_path_is_absolute (name)' faile        
        ID                                        Branch           Op           Remote            Download
 1. [✗] org.freedesktop.Platform.Locale           21.08            i            flathub               1.0 kB / 325.8 MB
 2. [✗] org.freedesktop.Platform                  21.08            i            flathub               1.1 kB / 199.7 MB
 3. [ ] com.spotify.Client                        stable           i            flathub           < 178.5 MB

Warning: (internal error, please report)
Error: Failed to read commit e5aff027f1cfc1b950d476dab5159628f077a4ca114e87160a123df9cce700bf: No such metadata object 34d3c387106f89f23c928a086c53be30009e19e6e509600d0850ecab20a49bab.dirtree
error: Failed to install org.freedesktop.Platform: Failed to read commit e5aff027f1cfc1b950d476dab5159628f077a4ca114e87160a123df9cce700bf: No such metadata object 34d3c387106f89f23c928a086c53be30009e19e6e509600d0850ecab20a49bab.dirtree

```

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Install flatpak ```crew install flatpak```
3. Install a flatpak apps (e.g. ```flatpak install flathub com.spotify.Client``` or ```flatpak install flathub org.videolan.VLC```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.11`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: `ef84887: Vivaldi 5.2.2623.33 => 5.2.2623.39 (#6977)`
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.84.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8414072
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=84
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.84.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.84.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.84.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.84.0
***

**Comment by satmandu** [comment]
I think flatpack is currently broken. PRs welcome.

**Comment by saltedcoffii** [comment]
#7127
