### ISSUE TITLE
Chromebrew fails to start because of Ruby.

### ISSUE THREAD

**Issue by z9485** [skycocker/chromebrew#6996]
## Description
When running Chromebrew (crew) on ChromeOS, Ruby fails with urandom error, and Chromebrew does not execute.

If you executed a specific command:
```shell
chronos@localhost / $ crew
```

Output:
```
/usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv-replace.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/crew/lib/downloader.rb:5:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
```

## Versions and system information
***
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={5615D466-EF74-FCD0-46EA-D7F60416B3CD}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={5615D466-EF74-FCD0-46EA-D7F60416B3CD}
CHROMEOS_RELEASE_BOARD=peach_pi-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=peach_pi-release/R75-12105.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.100.0 (Official Build) stable-channel peach_pi 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.100.0
***

## Additional information
Chromebrew will output `Chromebrew should not be run as root.` if executing `sudo crew`.
I removed crew manually by using `rm -rf /usr/local/bin`
I don't want to delete my installed apps.
This issue also happened when running `crew upgrade` when Chromebrew still worked.
I also have a crouton chroot with Ubuntu 20.04 LTS with XFCE.

Also, how do I add labels on my issue?

**Comment by satmandu** [comment]
Try reinstalling chromebrew on top of your existing install...

**Comment by z9485** [comment]
I tried running `curl -Ls git.io/vddgY | bash` already, but it resulted in the same error.

**Comment by z9485** [comment]
The command results in the same error, and the error is outputted two times after the install.

**Comment by z9485** [comment]
Also, Chromebrew worked on a November version.

**Comment by supechicken** [comment]
According to your `lsb-release`, you are using an EOL Chromebook with kernel 3.8 (that kernel is pretty old...)

Could you provide the output of the following commands:
```shell
uname -a
ls /dev/urandom
```

**Comment by z9485** [comment]
`uname -a`:
`Linux localhost 3.8.11 #1 SMP Sat Jul 13 23:29:49 PDT 2019 armv7l ARMv7 Processor rev 3 (v7l) SAMSUNG EXYNOS5 (Flattened Device Tree) GNU/Linux`

`ls /dev/urandom`:
`/dev/urandom` (in yellow on black background)

**Comment by satmandu** [comment]
Likely related to this: https://bugs.ruby-lang.org/issues/14716

**Comment by z9485** [comment]
So how would I fix this? Do I need to edit the crew file?

**Comment by satmandu** [comment]
Might be a ulimit issue too, as per https://stackoverflow.com/a/59890433

Can you try increasing your ulimit?

**Comment by supechicken** [comment]
According to the backtrace, `securerandom` is required by `resolv`, and it is needed by our ruby downloader, maybe try the following to fallback to `curl`:
```shell
export CREW_USE_CURL=1
sed -i 's/resolv-replace//' /usr/local/lib/crew/lib/downloader.rb
sed -i 's#net/http##' /usr/local/lib/crew/lib/donwloader.rb
```

**Comment by satmandu** [comment]
`sudo ulimit -n unlimited`

(Then try the Chromebrew install again)

**Comment by z9485** [comment]
`ulimit` works, but not `sudo ulimit`.

**Comment by z9485** [comment]
The new ulimit command returns `bash: ulimit: open files: cannot modify limit: Operation not permitted`

**Comment by z9485** [comment]
I ran the code below after installing Chromebrew (crew still had the same error):
```bash
export CREW_USE_CURL=1
sed -i 's/resolv-replace//' /usr/local/lib/crew/lib/downloader.rb
sed -i 's#net/http##' /usr/local/lib/crew/lib/downloader.rb
```
and there is a new error now:
```bash
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file --  (LoadError)
    from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    from /usr/local/lib/crew/lib/downloader.rb:3:in `<top (required)>'
    from /usr/local/bin/crew:15:in `require_relative'
    from /usr/local/bin/crew:15:in `<main>'
```

**Comment by supechicken** [comment]
Sorry, it should be:
```shell
rm -rf /usr/local
curl -Ls git.io/vddgY | bash # ignore the ruby error

export CREW_USE_CURL=1
sed -i 's/.*resolv-replace.*//' /usr/local/lib/crew/lib/downloader.rb
sed -i 's#.*net/http.*##' /usr/local/lib/crew/lib/downloader.rb

crew
```

**Comment by satmandu** [comment]
> Will rm -rf /usr/local delete my chroots and downloaded apps?

Yes it will.

**Comment by z9485** [comment]
How do I save them?

**Comment by satmandu** [comment]
@supechicken can we make the fallback automatic?

**Comment by supechicken** [comment]
> > Will rm -rf /usr/local delete my chroots and downloaded apps?
> 
> Yes it will.

**No...**, Crouton is installed to `/mnt/stateful_partition/` but not `/usr/local` (but you need to reinstall the crouton script) (see https://github.com/skycocker/chromebrew/wiki/How-to-remove-chromebrew)

**Comment by supechicken** [comment]
> @supechicken can we make the fallback automatic?

Okay :)

**Comment by z9485** [comment]
I ran
```bash
rm -rf /usr/local
curl -Ls git.io/vddgY | bash # ignore the ruby error

export CREW_USE_CURL=1
sed -i 's/.*resolv-replace.*//' /usr/local/lib/crew/lib/downloader.rb
sed -i 's#.*net/http.*##' /usr/local/lib/crew/lib/downloader.rb

crew
```
followed by
```bash
sudo ln -s /mnt/stateful_partition/crouton/chroots /usr/local/
sudo curl -L https://goo.gl/fd3zc -o /usr/local/bin/crouton
sudo chmod +x /usr/local/bin/crouton
for chroot in "$(ls /mnt/stateful_partition/crouton/chroots/)"; do sudo crouton -n "${chroot}" -u; done
```
then ran `crew`.

Chromebrew now works without errors, and my chroots are updating.
However, all my apps, like nano, are now gone. How do I get them back? (I did make a copy of /usr/local)

**Comment by supechicken** [comment]
Do you mean in chroot or in crew?

**Comment by z9485** [comment]
> Do you mean in chroot or in crew?

For what???

**Comment by supechicken** [comment]
> > Do you mean in chroot or in crew?
> 
> I need my Chromebrew installed apps. My chroot should be fine.

For `crew` apps you need to reinstall them since we removed chromebrew completely in the previous step

**Comment by satmandu** [comment]
The old /usr/local/etc/crew/device.json has a record of all installed apps.

**Comment by satmandu** [comment]
Try this, changing `your_backup`:
```
export OLDPACKAGES=$(jq -r '.installed_packages | .[].name' /your_backup//usr/local/etc/crew/device.json) 
crew reinstall $OLDPACKAGES
```

**Comment by z9485** [comment]
The command results in 
```bash
/usr/local/bin/crew:162:in `print_current_package': undefined method `any?' for nil:NilClass (NoMethodError)

  status = 'incompatible' unless @device[:compatible_packages].any? do |elem| elem[:name] == @pkg.name end
                                                              ^^^^^
        from /usr/local/bin/crew:1812:in `block in reinstall_command'
        from /usr/local/bin/crew:1809:in `each'
        from /usr/local/bin/crew:1809:in `reinstall_command'
        from /usr/local/bin/crew:1897:in `<main>'
```

**Comment by satmandu** [comment]
What does
```
export OLDPACKAGES=$(jq -r '.installed_packages | .[].name' /your_backup/usr/local/etc/crew/device.json) 
echo $OLDPACKAGES
```
give?

**Comment by z9485** [comment]
That command gives me `pixz jq ca_certificates gmp ncurses libyaml screen libpcap shared_mime_info libjpeg expat gdbm libdb readline libedit pcre2 libeconf termcap glibc sqlite xzutils linux_pam jp2a xdg_base musl_zstd xxhash lz4 popt rsync zstd nano openssl python3 libcap_ng util_linux glib libpng zlibpkg libffi bz2 libssh2 libnl3 p7zip core ruby git` as a result.

**Comment by satmandu** [comment]
Does this work?
```
crew reinstall pixz jq ca_certificates gmp ncurses libyaml screen libpcap shared_mime_info libjpeg expat gdbm libdb readline libedit pcre2 libeconf termcap glibc sqlite xzutils linux_pam jp2a xdg_base musl_zstd xxhash lz4 popt rsync zstd nano openssl python3 libcap_ng util_linux glib libpng zlibpkg libffi bz2 libssh2 libnl3 p7zip core ruby git
```

**Comment by z9485** [comment]
It still results in the same error.

**Comment by satmandu** [comment]
Try:
```
for i in pixz jq ca_certificates gmp ncurses libyaml screen libpcap shared_mime_info libjpeg expat gdbm libdb readline libedit pcre2 libeconf termcap glibc sqlite xzutils linux_pam jp2a xdg_base musl_zstd xxhash lz4 popt rsync zstd nano openssl python3 libcap_ng util_linux glib libpng zlibpkg libffi bz2 libssh2 libnl3 p7zip core ruby git
do
  crew install $i || crew reinstall $i
done
```

**Comment by z9485** [comment]
It still results in the same errors, but they repeat.

Also, running `crew install nano` results in
```bash
/usr/local/bin/crew:162:in `print_current_package': undefined method `any?' for nil:NilClass (NoMethodError)

  status = 'incompatible' unless @device[:compatible_packages].any? do |elem| elem[:name] == @pkg.name end
                                                              ^^^^^
        from /usr/local/bin/crew:1778:in `block in install_command'
        from /usr/local/bin/crew:1775:in `each'
        from /usr/local/bin/crew:1775:in `install_command'
        from /usr/local/bin/crew:1897:in `<main>'
```

**Comment by satmandu** [comment]
Do a `crew update compatible` first?

**Comment by satmandu** [comment]
Try this:
```
export CREW_CACHE_ENABLED=1 
curl -Ls git.io/vddgY | bash
for i in pixz jq ca_certificates gmp ncurses libyaml screen libpcap shared_mime_info libjpeg expat gdbm libdb readline libedit pcre2 libeconf termcap glibc sqlite xzutils linux_pam jp2a xdg_base musl_zstd xxhash lz4 popt rsync zstd nano openssl python3 libcap_ng util_linux glib libpng zlibpkg libffi bz2 libssh2 libnl3 p7zip core ruby git
do
  crew install $i || crew reinstall $i
done
```

**Comment by z9485** [comment]
The programs are reinstalling now, hopefully everything works.

**Comment by z9485** [comment]
Thank you for helping me!
