### ISSUE TITLE
xhost cannot load shared library when run with sudo

### ISSUE THREAD

**Issue by FarelRA** [skycocker/chromebrew#6999]
## Description

Due to this issue #6998 
When I run xhost as chronos or root I don't get an error but when I run with sudo I get an error

I run:
```shell
sudo xhost +
```
I got this error:
```
xhost: error while loading shared libraries: libXmuu.so.1: cannot open shared object file: No such file or directory
```

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Install xhost ```crew install xhost```
3. Run xhost ```sudo xhost +```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.13`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: `30eac6d: bump crew version`
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.84.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8414072
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=84
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.84.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.84.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.84.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.84.0
***

**Comment by satmandu** [comment]
Can you see if https://github.com/skycocker/chromebrew/pull/7001 fixes this for you?

**Comment by satmandu** [comment]
```
chronos@localhost /usr/local/lib/crew/packages (master|SPARSE<>)$ sudo xhost +
access control disabled, clients can connect from any host
```

**Comment by FarelRA** [comment]
Yes, this is fixed
