### ISSUE TITLE
Support tinycore packages

### ISSUE THREAD

**Issue by Downchuck** [skycocker/chromebrew#70]
To support tinycore 64 bit:

Create a glibc wrapper.
/usr/local/bin/wrap:

``` sh
LD_LIBRARY_PATH=/tmp/image/usr/local/lib /lib64/ld-linux-x86-64.so.2 /tmp/image/usr/local/bin/$@
```

Grab a tinycore package, like binutils:

``` sh
cd ~/Downloads;
curl -O http://distro.ibiblio.org/tinycorelinux/6.x/x86_64/tcz/binutils.tcz
sudo mount -o loop binutils.tcz /tmp/image
```

Now you can run it with your wrapper:

``` sh
wrap ld
```

Tinycore (6.x) binutils is about 2.5megs vs the 37meg chromebrew binutils; chromebrew decompresses to 100megs whereas tcz files are mounted via loopback. Feels like a big win.

-Charles

**Comment by Downchuck** [comment]
There's also patchelf: https://nixos.org/patchelf.html

**Comment by thedamian** [comment]
Great suggestion. Thank you both!

**Comment by JL2210** [comment]
Possible.
