### ISSUE TITLE
install.sh fails at "crew install core"; glibc post-install (Errno::ENOENT)

### ISSUE THREAD

**Issue by Granshmeyr** [skycocker/chromebrew#7017]
## Description

If you executed a specific command:
```shell
# curl -Ls git.io/vddgY | bash
```

Output:

[https://pastebin.com/raw/v4PNwdaS](https://pastebin.com/raw/v4PNwdaS)

## Versions and system information

- Architecture: `aarch64` (`aarch64`)
- Kernel version: `4.19.229-12876-gf06fecba2685`

- Chromebrew version: `1.23.15`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: ``

- OS variant: `Chrome OS`
- OS version: `hana-release/R100-14526.89.0`
- OS channel: `stable-channel`

## Additional information

`LIBC_VERSION=2.33`

The linked output is from a reinstall of Chromebrew, but the error is the same on fresh install.  The same error also occurs when running `crew install glibc`:
```
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
https://www.gnu.org/software/libc/
Version: 2.33
License: LGPL-2.1+, BSD, HPND, ISC, inner-net, rc, and PCRE
Performing pre-flight checks...
Package glibc already installed, skipping...
Performing post-install for glibc...
/usr/local/lib/crew/packages/glibc.rb:588:in ``': No such file or directory - /usr/local/lib/libc.so.6 (Errno::ENOENT)
        from /usr/local/lib/crew/packages/glibc.rb:588:in `postinstall'
        from /usr/local/bin/crew:947:in `block (2 levels) in post_install'
        from /usr/local/bin/crew:945:in `chdir'
        from /usr/local/bin/crew:945:in `block in post_install'
        from /usr/local/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
        from /usr/local/bin/crew:944:in `post_install'
        from /usr/local/bin/crew:1301:in `block in resolve_dependencies_and_install'
        from /usr/local/bin/crew:1299:in `each'
        from /usr/local/bin/crew:1299:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1781:in `block in install_command'
        from /usr/local/bin/crew:1776:in `each'
        from /usr/local/bin/crew:1776:in `install_command'
        from /usr/local/bin/crew:1898:in `<main>'
```
I can still use `crew`, but I seemed to be getting errors when installing certain packages. As a simpleton I can only assume this is why.

**Comment by supechicken** [comment]
Could you provide the output of `ls -la /usr/local/lib/libc.so.6`?

**Comment by satmandu** [comment]
I think we need to modify glibc.rb, as this doesn't work if the glibc package doesn't have the libc.so.6 there.
https://github.com/skycocker/chromebrew/blob/7cb595811e0c9b49fba5f6717eca735890cadf52/packages/glibc.rb#L588

Can you do a `crew files glibc | grep libc.so` and tell us what you get?

**Comment by Granshmeyr** [comment]
```
chronos@localhost ~/Downloads $ crew files glibc | grep libc.so
/usr/local/lib/libc.so
```

**Comment by ingemarh** [comment]
Well, managed to install today, so I assume the bug is fixed.

**Comment by supechicken** [comment]
Yeah, #7118 fixed it
