### ISSUE TITLE
Fatal error when installing R

### ISSUE THREAD

**Issue by BobbyBobster** [skycocker/chromebrew#707]
Tried to install R on my Toshiba Chromebook 2 (x86_64) but got a fatal error. I first ran into some other minor problems, namely I had to install `bz2`, `curl` and `openssl` (after applying #690) first.

Then I got this error message:

![errormessager](https://cloud.githubusercontent.com/assets/23128298/26757176/6e42302a-48b4-11e7-9932-8747bbe72b8d.png)

**Comment by BobbyBobster** [comment]
Turns out I also had to install `readline`. Now it has installed without error. 
I don't know if this means that the dependencies of `r.rb` should be changed, but I am closing the issue.

**Comment by flyingP0tat0** [comment]
Well it should definetly be added as a dependency.
