### ISSUE TITLE
[jdk8] Links to Oracle JDK 8 Violate Oracle License Agreement?

### ISSUE THREAD

**Issue by kjperkin** [skycocker/chromebrew#7094]
I'm not a lawyer, but a quick skim of what I could find suggests that hosting copies of Oracle JDK 8u211 and later is a violation of the license agreement.

The question "Of all the currently supported Java SE versions from Oracle, what is the past/present licensing they are/were made available under?" in the [Oracle Java SE Licensing FAQ](https://www.oracle.com/java/technologies/javase/jdk-faqs.html) says that the license for Oracle JDK 8u211 and higher is [here](https://www.oracle.com/downloads/licenses/oracle-javase-license.html). That license says among other things:

> **License Rights and Restrictions**
> ...
> You may not:
> ...
> * make the Programs available in any manner to any third party 

In fact, lines 46-54 of jdk8.rb acknowledge that Oracle requires users to download the JDK themselves: 
https://github.com/skycocker/chromebrew/blob/cc47949806d8fa2a8abd95549913aeae94bb2891/packages/jdk8.rb#L46-L54

I think that these files need to be removed from GitLab so that this repository and the one hosting the binaries doesn't get DMCA'd. The offending links are found on lines 12-15 of jdk8.rb:
https://github.com/skycocker/chromebrew/blob/cc47949806d8fa2a8abd95549913aeae94bb2891/packages/jdk8.rb#L12-L15

**Comment by saltedcoffii** [comment]
I'm working on two package upgrades but after that I'll work on replacing our jdk packages with openjdk sources instead of oracle jdk sources.

**Comment by uberhacker** [comment]
Just add a new package.  No need to replace.

**Comment by saltedcoffii** [comment]
they'll conflict with each other.

**Comment by uberhacker** [comment]
Not if you add a preflight check to allow only one or the other.

**Comment by kjperkin** [comment]
I think step 1 needs to be to take down (from whatever hosting site they're on) any Oracle JDK binaries for JDK versions less than 17. Not just taking the links out of the packages, but actually taking down the links. To find suspect URLs I wrote a small script (inline below). There are a number of them across a number of services.

```bash
#!/bin/bash                                                                                      
(cd /usr/local/lib/crew && git log -u -G'https://') | \                                          
awk "                                                                                            
    match(\$0, /https?:\/\/.*jdk(8|9|10|11|12|13|14|15|16).*\.tar.[^\"']+/) > 0 {                
        print substr(\$0, RSTART, RLENGTH)                                                       
    }                                                                                            
" | \                                                                                            
grep -Ev 'download.oracle.com|hg.openjdk' | \                                                    
sort -u | \                                                                                      
xargs -d'\n' curl -L -I -s -w '%{stderr}%{response_code}\t%{url}\n' 2>&1 >/dev/null | \          
tee /dev/stderr | \                                                                              
awk '/^[23]/ { print $2 }' | \                                                                   
tee ACTIVE_JDK_URLS
```

**Comment by saltedcoffii** [comment]
Closing as duplicate to #7097

**Comment by kjperkin** [comment]
@saltedcoffii I don't think this is a duplicate, although it is related. #7097 has to do with getting new packages to meet the need for a JDK. This is about removing binaries that violate license agreements from wherever they are hosted.
