### ISSUE TITLE
[`glibc`]: `#{CREW_LIB_PREFIX}/libc.so.6` missing from prebuilt binary (`armv7l`)(`2.33`)

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#7117]
The `libc.so.6` symlink is missing from the `armv7l` prebuilt tarball (does not exist in `filelist` also)

This lead to errors in `postinstall`:
```
#6 384.5 Performing post-install for glibc...
#6 387.4 /usr/local/lib/crew/packages/glibc.rb:588:in ``': No such file or directory - /usr/local/lib/libc.so.6 (Errno::ENOENT)
#6 387.4 	from /usr/local/lib/crew/packages/glibc.rb:588:in `postinstall'
#6 387.4 	from /usr/local/bin/crew:947:in `block (2 levels) in post_install'
#6 387.4 	from /usr/local/bin/crew:945:in `chdir'
#6 387.4 	from /usr/local/bin/crew:945:in `block in post_install'
#6 387.4 	from /usr/local/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
#6 387.4 	from /usr/local/bin/crew:944:in `post_install'
#6 387.4 	from /usr/local/bin/crew:1301:in `block in resolve_dependencies_and_install'
#6 387.4 	from /usr/local/bin/crew:1299:in `each'
#6 387.4 	from /usr/local/bin/crew:1299:in `resolve_dependencies_and_install'
#6 387.4 	from /usr/local/bin/crew:1781:in `block in install_command'
#6 387.4 	from /usr/local/bin/crew:1776:in `each'
#6 387.4 	from /usr/local/bin/crew:1776:in `install_command'
#6 387.4 	from /usr/local/bin/crew:1898:in `<main>'
#6 ERROR: executor failed running [/bin/bash -i -x -o pipefail -c curl -Ls git.io/vddgY | bash]: exit code: 1
------
```

Not sure does it require a rebuild...

**Comment by uberhacker** [comment]
This would affect installation too, right?

**Comment by satmandu** [comment]
Isn't this symlinked from the system libc.so.6? This shouldn't matter...

**Comment by satmandu** [comment]
Looks like an issue with the postinstall script.

**Comment by uberhacker** [comment]
The postinstall script would affect installation too, correct?

**Comment by supechicken** [comment]
According to `glibc.rb`, the symlink will be created after calling `libc.so.6` for glibc version:
https://github.com/skycocker/chromebrew/blob/464a55c2d07b0030719f0cfc3f9fbd06ba4a5258/packages/glibc.rb#L587-L590
https://github.com/skycocker/chromebrew/blob/464a55c2d07b0030719f0cfc3f9fbd06ba4a5258/packages/glibc.rb#L597-L602

> This would affect installation too, right?

Yeah

**Comment by supechicken** [comment]
Just look at it again, the `@crew_libc_version` variable is only used to print the `glibc` version provided by `crew`, maybe just remove the whole section?

**Comment by supechicken** [comment]
Fair enough :)
