### ISSUE TITLE
LibPNG is broken, manually reverted to old libpng.rb, problem fixed

### ISSUE THREAD

**Issue by sihawken** [skycocker/chromebrew#7129]
## Description
GraphicsMagick could not find the png.la file, despite the file clearly being there.

```
 $ crew-launcher add gimp
identify identify: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found").
identify identify: Request did not return an image.
convert convert: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found").
/usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `system': Command
```
No matter how many reinstalls, the problem would go away. It was only resolved by reverting to the old libpng.rb manually and reinstalling libpng:

https://github.com/skycocker/chromebrew/blob/49b19ac1dd3535efbc3a160a2423dfe322e2d6dd/packages/libpng.rb 

This fixed my problem.

**Comment by saltedcoffii** [comment]
yeah i'm not sure bundling libpng with harfbuzz was the best idea...
@satmandu wanna take a look at this?

**Comment by satmandu** [comment]
So Imagemagick is broken?

**Comment by satmandu** [comment]
Looks like the easiest fix here would be to rebuild Imagemagick, since that package is the one with the relevant `png.la` file being built against libpng.


Doing that now...


(This may also require a gimp rebuild, but maybe not...)

**Comment by satmandu** [comment]
The issue is that imagemagick7 was built against the old customized `libpng`.  The current build uses a standard `libpng`, without any special patching, so anything built against the old custom `libpng` needs rebuilding.  Looks like `gimp` is pulling in `imagemagick7` dependencies... so an `imagemagick7` rebuild should take care of this...

**Comment by satmandu** [comment]
Imagemagick and gimp updates/rebuilds in progress...

**Comment by satmandu** [comment]
I have updates for imagemagick7, openjpeg, and ffmpeg.

Building current Gimp appears to require gegl, which appears to have problems building on all architectures though....

**Comment by satmandu** [comment]
Let us know if this helps?

**Comment by sihawken** [comment]
I reinstalled chromebrew, which I assumed reset the changes that I have made.

Crew-launcher now works properly again, and the gimp icons aren't broken anymore. It appears to have worked. Thanks!
