### ISSUE TITLE
Add Git folder check at every update

### ISSUE THREAD

**Issue by tonyxue** [skycocker/chromebrew#72]
At the moment, crew will directly run the git fetch command at every update but does not check whether the directory is a valid git directory. In this case, if the directory is not a git folder, git will return error but crew will still prompt `up to date`.
So a check on whether the remote is correct should be added in prior, and fix folder if it is not a git directory.

**Comment by lyxell** [comment]
Closing as invalid. The directory will always be a git directory unless the user manually deleted `.git`.
