### ISSUE TITLE
Your device is not supported by Chromebrew yet.

### ISSUE THREAD

**Issue by cigan1** [skycocker/chromebrew#73]
I am trying to install on HP Chromebook 11. I am getting a message "Your device is not supported by Chromebrew yet.".
It would be nice to have a list of supported devices.

Thank you!

**Comment by gregkrsak** [comment]
no Teresa

**Comment by gregkrsak** [comment]
(Apologies if I sent a random message-- some visiting kids were playing
with my Moto 360 and activated the voice control.)

**Comment by l3li3l** [comment]
Chromebrew does not yet support ARM devices. This is readily understood by reading the source but I'll try to make an edit to the readme.

**Comment by skycocker** [comment]
Readme updated in https://github.com/skycocker/chromebrew/pull/75
