### ISSUE TITLE
Update project homepage

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#765]
We need to update the http://skycocker.github.io/chromebrew/ page example with description and homepage metadata, otherwise, it will confuse newcomers to the project who want to commit.  Also, we should remove the sudo references since they are no longer needed.  Not sure if you noticed this @skycocker, but the size of this project has nearly tripled in the last 6 months.  Earlier this year there were less than 100 packages available.  Now there are nearly 300 packages and growing.

**Comment by uberhacker** [comment]
@jam7, @lyxell, @thedamian, @cstrouse, @minektur:  Do you guys know what happened to @skycocker?  He has essentially disappeared from the project.  How would we update the project homepage in his absence?

**Comment by kirbyfan64** [comment]
... don't you just push to the `gh-pages` branch?

**Comment by kirbyfan64** [comment]
https://github.com/skycocker/chromebrew/tree/gh-pages?files=1

**Comment by flyingP0tat0** [comment]
Yes, pushing to `gh-pages` is the way to go.

**Comment by thedamian** [comment]
WOW! You found the files. I've been looking how to do that and didn't know how skycocker had hid them.

Fantastic @kirbyfan64 

Ok folks. Put in your changes here or on a gist (Unless you can make a PR to make the changes)

If you guys suggest the changes I will try to implement it.

**Comment by uberhacker** [comment]
I will create a new PR soon to update this page.  There are several grammatical errors I would like to correct as well.  Thank you @kirbyfan64 and @flyingP0tat0.
