### ISSUE TITLE
rsync failed to install: `make -j2` exited with 2

### ISSUE THREAD

**Issue by satarah** [skycocker/chromebrew#766]
I've been happily using crew packages for some time now on my Chrombook.
>> Dell 11 w/ Intel Celeron 2955U @ 1.40GHz

Today when trying to install `rsync`, and after removing `gliibc` and allowing it to be reinstalled with the rsync install, I received the following error and exit code.
>> rsync failed to install: `make -j2` exited with 2

On this website
>> https://lxadm.com/Rsync_exit_codes

It gives the following explanation for that exit code
>> 2  Protocol incompatibility

Any thoughts?
It would be nice to use this package.

Thank you for all the work you've done.

**Comment by thedamian** [comment]
I've had this issue with a package that was missing in my system (and hence in the project)
We have to make sure we have all package references in the package.

**Comment by satarah** [comment]
Thank you for your fast response.
I'm  a bit of a noob when it comes to linux management, and especially the extra limitations placed on Chromebook. Can you direct me how to check for or load this missing package (`make`)?
Thanks again.
