### ISSUE TITLE
bash: crew: command not found

### ISSUE THREAD

**Issue by dev-edo** [skycocker/chromebrew#77]
When I type crew in it says:

bash: crew: command not found

even though I just installed Chromebrew:

Chromebrew installed successfully and package lists updated.

**Comment by DGO143** [comment]
Did you try sudo crew?
Also try restarting/reinstalling.
Maybe you could check the directory crew is installed to, I don't know exactly where that is.

**Comment by skycocker** [comment]
@dev-edo you're gonna have to install crew again (and possibly remove the earlier created by install script files). Let me know if it works now - the install script is fixed.
