### ISSUE TITLE
Dart package needs work

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#780]
This package does not install.  After examining the output, it appears `/usr/bin`, `/usr/include` and `/usr/lib` directories in the tarball should be changed to `/usr/local/...` instead.  Also, the dart.rb package file is missing description and homepage metadata.

**Comment by kirbyfan64** [comment]
Sorry, I lost access to my Chromium OS install a while ago and am unable to get it back ATM...

**Comment by uberhacker** [comment]
Hey @kirbyfan64: No worries at all.  Let me know if you need any assistance.

**Comment by thedamian** [comment]
Should we remove dart here. 

I looked into how to do dart from source instead of from these prebuilt files that are hosted in someone's dropbox, but didin't finish the package.

If it doesn't work. we should revert it no?

**Comment by uberhacker** [comment]
@thedamian: The best case scenario would be to fix with a new PR so the revert is unnecessary.  That being said, I agree that we should compile from source instead of hosting binaries from Dropbox if that avenue is not fraught with peril.  Where did you get hung up?  Maybe I can assist.  Can you post any errors you received?

**Comment by thedamian** [comment]
@uberhacker You're amazing my friend.
I didn't have any trouble. Truly it was a matter of looking up HOW to do it, but not having the time to do it.

the installation looks rather  simple according to their site:https://github.com/dart-lang/sdk/wiki/Building

the only thing that I was going to have to spend a little time on is that their build scripts have to see if they're 32bit or 64 bit

./tools/build.py --mode release --arch **x64** create_sdk
 ("ia32" for 32bit devices)

then the output is in "build/ReleaseIA32/dart_sdk" and we just have to figure out where to copy it (Do you have libs, do you have just a binary... those types of questions)

Really it's just "Grunt work" as they call it that just has to be done by someone. 
If we had an official list of "things to do" this could be setup as an "easy one" for someone. 

I will do it. but will do so when I have the time.

**Comment by uberhacker** [comment]
Right, the key is persistence and patience.  Do we need to worry about 32-bit devices...ever?  I thought all Chromebooks were built with 64-bit processors.  Maybe I'm wrong?

**Comment by jam7** [comment]
FYI, there are 4 devices, aarch64, armv7l, i686, x86_64.  Only x86_64 is 64 bits.  All others are 32 bits.

**Comment by uberhacker** [comment]
I think you are right about i686 and armv7l, however, isn't aarch64 64 bits?

**Comment by jam7** [comment]
aarch64 means 64 bits.  However, chromeos on aarch64 uses aarch32 mode.  It means it is identical to armv7l.

**Comment by uberhacker** [comment]
Gotcha.  It's starting to make a bit more sense now if that is even possible. LoL

**Comment by dantrevino** [comment]
This should be fixed with #809
