### ISSUE TITLE
Node package install issue

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#784]
```
chown: cannot access ‘/usr/local/lib/node_modules’: No such file or directory
node failed to install: `sudo chown -R chronos /usr/local/lib/node_modules` exited with 1
```

**Comment by flyingP0tat0** [comment]
Do you encounter the same error when using `node_current`?

**Comment by uberhacker** [comment]
@flyingP0tat0: Yes.  IMHO, we should never need to change permissions (EVER! :).  As a general rule, you should never (NEVER! :) install node packages via `sudo npm install`.  We shouldn't have anything under `/usr/local` that is ever owned by any user except `chronos`.  With that said, can we just remove these lines from the packages? :)

**Comment by flyingP0tat0** [comment]
If we do, you won't be able to install npm packages globally. I get your point about permissions. But in this case, it is nothing harmful, it is just a workaround for Chromium OS's somewhat triky filesystem.
There are valid reasons to do a `sudo npm install` if you are doing it globally (and obviousely not on a chromebook).

**Comment by uberhacker** [comment]
This is the reason projects like `nvm` have arisen.  See https://github.com/creationix/nvm.  We would never need to install node packages globally on a Chromebook so we should just forget about such nonsense as `sudo npm install`. :)  In any event, I think the proper fix would be to check and see if any node packages were installed previously (ie. does the `/usr/local/lib/node_modules` exist before attempting to fix permissions).  Something like below:
```
system "sudo chown -R chronos /usr/local/lib/node_modules" if Dir.exists? '/usr/local/lib/node_modules'
```
On a virgin system, you will not have this directory until you install node packages so we shouldn't assume it will always exist.

**Comment by uberhacker** [comment]
Sorry, I should rephrase.  We should never need to use `sudo npm install` when installing node packages globally.  So instead of `sudo npm install -g somepackage`, it would be `npm install -g somepackage`.

**Comment by uberhacker** [comment]
Right, because if you don't check for the directory first, the sudo chmod line will fail and cause the package install to abort.

**Comment by flyingP0tat0** [comment]
Yes. I am not that into ruby and my day here in Europe is going to an end, so maybe someone else wants to implement these checks. If not, it will take me another 18 hours or so.
