### ISSUE TITLE
Can't install things globally using node or rubygems

### ISSUE THREAD

**Issue by liamness** [skycocker/chromebrew#79]
Installing like so

```
sudo gem install lolcat
```

results in the following error

```
ERROR:  While executing gem ... (Errno::EROFS)
    Read-only file system - /root/.gem
```

Installing an npm module

```
sudo npm install -g gulp
```

does something similar:

```
npm ERR! rofs EROFS, mkdir '/root/.npm'
```

Looks like at least one other person has had this issue too:

http://stackoverflow.com/questions/28334768/ruby-gems-area-not-writeable

This is a filesystem issue, they are trying to write into /root/ which is read only. But why aren't they installing nicely into my /usr/local/bin or somewhere? I probably messed something up somewhere but I can't quite figure out what.

**Comment by mrzmmr** [comment]
It looks like you have to change the prefix for npm. just run
``` bash
npm config set prefix /usr/local
```
and that should work. You can also run npm config ls -l to see all options.
For ruby gems you can make a ~/.gemrc and include
``` ruby
gemhome: /usr/local/gems
```
Npm has a lot of information on configuration. Heres where I got the answer above:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by liamness** [comment]
This solved things for me:

    sudo chown -R chronos:chronos /usr/local

Then you can install things with rubygems / npm without sudo. If you run with sudo, it tries to install things for the root user, which apparently results in the config being incorrect. So the problem seems to be that things are installing as root, not chronos.

**Comment by lagerratrobe** [comment]
Make sure you also update the "tmp" prefix as well.  I had to change it from /tmp to someplace writable.

`npm config set tmp /usr/local/tmp`
