### ISSUE TITLE
ruby failed to install: `make -j2` exited with 2

### ISSUE THREAD

**Issue by gishnanigans** [skycocker/chromebrew#790]
After trying to install `rsync` again after [issue 766](https://github.com/skycocker/chromebrew/issues/766) and getting the same error as before, I decided to do an `update` and `upgrade` on crew and its packages. The result of the upgrade was a lot of processing followed by a similar error and exit code, but this time for `ruby`.

Thought you would like to know.

>... many lines ...
compiling math.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
compiling parse.c
compiling proc.c
compiling process.c
compiling random.c
In file included from /usr/local/include/sys/syscall.h:31:0,
                 from /usr/local/include/syscall.h:1,
                 from random.c:81:
random.c: In function ‘fill_random_bytes_syscall’:
random.c:525:16: error: ‘__NR_getrandom’ undeclared (first use in this function)
  ret = syscall(SYS_getrandom, seed, size, flags);
                ^
random.c:525:16: note: each undeclared identifier is reported only once for each function it appears in
random.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
make: *** [random.o] Error 1
make: *** Waiting for unfinished jobs....
ruby failed to install: `make -j2` exited with 2

**Comment by thedamian** [comment]
It was a dependency issue, it looks like one of our packages (that you had installed) has this missing. 
I'll look to see what it was before. You might have to update all your /usr/local/lib/crew/packages/ directory manual from github.
and then the upgrade should work. if it doesn't please tell us which package this broke on.

**Comment by gishnanigans** [comment]
I'll give it a try tonight or tomorrow ASAP. Thank you.

**Comment by jam7** [comment]
@gishnanigans you may need to install linuxheaders.  `__NR_getrandom` is defined in `/usr/local/include/bits/syscall.h`.  Please try `crew upgrade linuxheaders` by hand at first.

I think the source of problem is that `crew upgrade` doesn't upgrade files belong to dependency.  So, you may need to install them by hand belong to dependency sometime.

**Comment by gishnanigans** [comment]
`crew upgrade linuxheaders` which I followed by a global `crew upgrade` just for good measure, did the trick.

I was able to install `rsync` and related.

Thank you.

**Comment by thedamian** [comment]
I'm getting an error with the PHP7 package, you have to figure out two things.
1)  did the latest PR https://github.com/skycocker/chromebrew/pull/791 fix your issue.
2) If you're still having the error scroll up and figure out which package are you installing when this error happens.

**Comment by jam7** [comment]
Close since `crew upgrade linuxheaders` solved the problem.
