### ISSUE TITLE
Wine on aarch64

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#796]
If I undertstand #780 correctly, `aarch64` uses 32-bit mode?
The thing is, that I set up wine to build with 64-bit support on `aarch64`. Could someone please build wine on `aarch64` and let me know about the result?

**Comment by lyxell** [comment]
Correct, wine installation for aarch64 is probably broken.
Another way to test this is to try to install the package on armv7 with the 64-bit flag enabled.

**Comment by flyingP0tat0** [comment]
I guess I will just edit the package...

**Comment by flyingP0tat0** [comment]
Possible problem is acknowledged, change is proposed.
