### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by dantrevino** [skycocker/chromebrew#797]
chronos@localhost / $ crew install make keep
...
./config.status: line 3183: cmp: command not found
pkgconfig failed to install: `make -j4` exited with 127

**Comment by jam7** [comment]
It is caused by a difficult to solve dependency problem.  :(

You can avoid this problem by `crew install buildessential`.

**Comment by jam7** [comment]
This issue will be fixed once #815 is merged.

**Comment by jam7** [comment]
Close in favor of #815.
