### ISSUE TITLE
Use SHA256 instead of SHA1

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#808]
It's probably time to migrate to a more modern hash function since the vulnerabilities of SHA1 applies to our use case.

**Comment by jam7** [comment]
How about modifying crew to support both sha1 and sha256 first?  Then, we can move toward to sha256 step by step.  I'll send a PR.

**Comment by uberhacker** [comment]
I think I heard @lyxell just volunteered that he would update all the packages also. ;)

**Comment by uberhacker** [comment]
See #826 and #830.

**Comment by uberhacker** [comment]
@lyxell: Can we please get the PRs mentioned previously merged into master soon?  If you have an issue with anything, I will try and change quickly.  Otherwise, I foresee merge conflicts galore as more package PRs enter the queue.

**Comment by lyxell** [comment]
Sure, however, just changing the hashes shouldn't spawn any conflicts.

**Comment by uberhacker** [comment]
@lyxell: The conflict arises when the PR has the old sha1 hash.  Please see #834, #835 and #836 which should complete the conversion for all packages.

**Comment by uberhacker** [comment]
Can we close this task?
