### ISSUE TITLE
Homepage looks wonky when screen is wider than 1200 pixels

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#819]
The boxes shrink when the screen is wider than 1200 pixels at http://skycocker.github.io/chromebrew/.  This appears to be a possible css media query logic error.  Do any of you front-end guys want to take a stab at this?

**Comment by skiman6010** [comment]
Can you post a screenshot of what it looks like on your screen when this error happens?

**Comment by uberhacker** [comment]
![screenshot 2017-08-09 at 9 20 52 am](https://user-images.githubusercontent.com/387945/29126488-1b2d6b16-7ce4-11e7-9526-da7f6552d59c.png)

**Comment by flyingP0tat0** [comment]
Fixed it in #1034.
