### ISSUE TITLE
🐞 Bug: rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]

### ISSUE THREAD

**Issue by reboun** [skycocker/chromebrew#8235]
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync: ACLs are not supported on this client
rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
/usr/local/bin/crew:1286:in `system': Command failed with exit 1: rsync (RuntimeError)
        from /usr/local/bin/crew:1286:in `install_files'
        from /usr/local/bin/crew:1328:in `block in install_package'
        from /usr/local/bin/crew:1297:in `chdir'
        from /usr/local/bin/crew:1297:in `install_package'
        from /usr/local/bin/crew:1482:in `install'
        from /usr/local/bin/crew:1425:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1422:in `each'
        from /usr/local/bin/crew:1422:in `resolve_dependencies'
        from /usr/local/bin/crew:1346:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1795:in `block in install_command'
        from /usr/local/bin/crew:1790:in `each'
        from /usr/local/bin/crew:1790:in `install_command'
        from /usr/local/bin/crew:1922:in `<main>'

To reproduce: curl -Ls git.io/vddgY | bash

**Comment by uberhacker** [comment]
There must be something in your `/usr/local` directory because rsync is not available in a pristine out-of-the-box ChromeOS bash shell session.  If there is nothing in there you want to keep, try the following:
```
rm -rf /usr/local
curl -Ls git.io/vddgY | bash
```

**Comment by reboun** [comment]
> There must be something in your `/usr/local` directory because rsync is not available in a pristine out-of-the-box ChromeOS bash shell session. If there is nothing in there you want to keep, try the following:
> 
> ```
> rm -rf /usr/local
> curl -Ls git.io/vddgY | bash
> ```

rm: cannot remove '/usr/local': Read-only file system

**Comment by satmandu** [comment]
Try this:

```
rm -rf /usr/local/*
curl -Ls git.io/vddgY | bash
```

**Comment by uberhacker** [comment]
The error is nothing to worry about since that directory is read-only.  I suggest `rm -rf /usr/local` over `rm -rf /usr/local/*` since the latter doesn't cover hidden files and folders.

**Comment by reboun** [comment]
> The error is nothing to worry about since that directory is read-only. I suggest `rm -rf /usr/local` over `rm -rf /usr/local/*` since the latter doesn't cover hidden files and folders.

rm: cannot remove '/usr/local': Read-only file system
