### ISSUE TITLE
Should we remove the heroku package?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#829]
This package is currently broken.  Heroku CLI (see https://devcenter.heroku.com/articles/heroku-cli) can be installed via `npm -g install heroku-cli`.  The legacy version can also be installed via `gem install heroku` (see https://blog.heroku.com/the_heroku_toolbelt).

**Comment by jam7** [comment]
If it is possible to make those installed files uninstallable through crew, preparing a package file for chromebrew is very good, I think.

For example, the [Heroku CLI install guide](https://devcenter.heroku.com/articles/heroku-cli#download-and-install) you referred explains how to install heroku-cli through homebrew.  Maybe, we can see how homebrew does that job.
