### ISSUE TITLE
Tmux no longer installs

### ISSUE THREAD

**Issue by Tivoli** [skycocker/chromebrew#83]
Looks like there are missing headers with the built in Openssl, which causes Tmux to not install anymore.

```
/bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./compat -I./include -I./include    -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c -o bufferevent_openssl.lo bufferevent_openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c bufferevent_openssl.c  -fPIC -DPIC -o .libs/bufferevent_openssl.o
bufferevent_openssl.c:60:25: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
                         ^
compilation terminated.
make[2]: *** [bufferevent_openssl.lo] Error 1
make[2]: Leaving directory `/usr/local/tmp/crew/libevent-2.0.21-stable'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/libevent-2.0.21-stable'
make: *** [all] Error 2
libevent failed to install: `make` exited with 2
```

**Comment by tmccisdj** [comment]
I just ran across this myself. I'm starting to think something like crouton installation without a gui might be the better way of going for myself. I love the idea of chromebrew but I keep running into problems that seem to take more time then it might be worth :(

**Comment by cassial** [comment]
same problem here.Thank for your effort.

**Comment by lyxell** [comment]
It might be a good idea to add openssl as a dependency again. Even though the binary now is included natively, the headers like "openssl/bio.h" seem to be excluded.

**Comment by idvoretskyi** [comment]
I have the same issue. Please, provide us with the informations of how-to solve it.

**Comment by thedamian** [comment]
What package is this from?

**Comment by idvoretskyi** [comment]
@thedamian what do you mean?

**Comment by create** [comment]
Same issue here. libevent fails to install with
```bufferevent_openssl.c:60:25: fatal error: openssl/bio.h: No such file or directory```

**Comment by thedamian** [comment]
I tried installing all the openssl includes into the /usr/include but it's mounted as read only.

So would the fix of adding the ssl package back fix this? You can't copy the includes? Or how is this fixed?

P.S. ignore my packges comment (Didn't see it was TMUX)

**Comment by idvoretskyi** [comment]
Folks, so what's the actual status of a fix on the issue?

**Comment by thedamian** [comment]
@idvoretskyi like everything in open source. If you don't fix it it doesn't get fixed. 

I tried to fix it and I can't figure out how without mounting /etc as writable.

Can you make a suggestion?

**Comment by idvoretskyi** [comment]
@thedamian the same.
I'm not a senior expert in this, so I asked on some suggestions regarding that.

BTW, haven't anybody tried to install tmux using the `dev_install` tool?

**Comment by lyxell** [comment]
https://github.com/skycocker/chromebrew/blob/470e7e0e9b31e644b00088779fb1ab4bd5b952f0/packages/openssl.rb

Adding this file to the packages folder and installing openssl via chromebrew would probably work.

**Comment by thedamian** [comment]
Great suggestion lyxell;

would copying the file that it's complaining about to /usr/local/include also work?
Here's the original: https://raw.githubusercontent.com/openssl/openssl/master/include/openssl/bio.h

I know it's suppose to go to /etc/include but where is make/gcc actually looking for it? and are there more dependencies?

**Comment by lyxell** [comment]
Yes, /usr/local/include would work fine, it is usually searched before /usr/include.
Please note that *only* copying `bio.h` would not work, `bio.h` depends on other files too, such as `crypto.h` etc.

**Comment by idvoretskyi** [comment]
@lyxell could you please provide the brief instructions - I will test that on my own.

Thank you.

**Comment by lyxell** [comment]
@idvoretskyi 
`cd /usr/local/lib/crew/packages`
`wget https://raw.githubusercontent.com/skycocker/chromebrew/470e7e0e9b31e644b00088779fb1ab4bd5b952f0/packages/openssl.rb`
`brew install openssl`
`brew install tmux`

**Comment by ttroutman** [comment]
@lyxell 
Thank you. This worked perfectly for me.

**Comment by lyxell** [comment]
I added a pull request which restores the removed openssl package.
