### ISSUE TITLE
Dropbox fails to start

### ISSUE THREAD

**Issue by vince** [skycocker/chromebrew#848]
Just installed Dropbox and running dropbox start fails with:

```
Starting Dropbox...Traceback (most recent call last):
  File "<string>", line 5, in <module>
zipimport.ZipImportError: not a Zip file: '/usr/local/bin/dropbox-lnx.x86_64-28.4.14/library.zip'
^[c^CTraceback (most recent call last):
  File "/usr/local/bin/dropbox.py", line 1535, in <module>
    ret = main(sys.argv)
  File "/usr/local/bin/dropbox.py", line 1524, in main
    result = commands[argv[i]](argv[i+1:])
  File "/usr/local/bin/dropbox.py", line 1395, in start
    if not start_dropbox():
  File "/usr/local/bin/dropbox.py", line 741, in start_dropbox
    time.sleep(interval)
```

Trying to unzip it manually I see something similar:

```
chronos@localhost /usr/local/bin/dropbox-lnx.x86_64-28.4.14 $ unzip library.zip 
Archive:  library.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  library.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of library.zip or
        library.zip.zip, and cannot find library.zip.ZIP, period.
```

Edit: I ended up downloading that zip file and manually copying it over and then it launched. Now just trying to figure out how to use the package..

**Comment by uberhacker** [comment]
Hi @vince: Thank you for reporting this issue.  Could you please send your system specs?  You can find them in `Settings` at the top by clicking on `About Chromium OS`.  Also, please send the output of `uname -a` from the terminal.

**Comment by vince** [comment]
Hey there, thanks for the response!

Here's uname -a
    Linux localhost 3.18.0-15776-g24ef2013948e #1 SMP PREEMPT Tue Jul 4 02:52:28 PDT 2017 x86_64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz GenuineIntel GNU/Linux

About Chrome
    Version 61.0.3147.0 (Official Build) canary (64-bit)

I ended up installing the headless version of dropbox using [these instructions](https://www.dropbox.com/install-linux) and that seemed to work so I no longer need this fixed but happy to help debug!

**Comment by uberhacker** [comment]
Hey @vince: The package uses the same steps as the instructions link you provided.  I was able to reproduce the error you received.  For some reason, the extraction is corrupting the library.zip file.  I thought maybe updating the version (see PR #854) would help but the problem remains.  This is really strange.

**Comment by uberhacker** [comment]
I also have a pending PR (see #831) which might interest you.

**Comment by uberhacker** [comment]
The workaround to fix this strange bug is shown below (replace x86_64 with x86 if you are using the 32-bit version):
```
$ wget https://clientupdates.dropboxstatic.com/dbx-releng/client/dropbox-lnx.x86_64-29.4.20.tar.gz
$ tar xvf dropbox-lnx.x86_64-29.4.20.tar.gz 
$ cp .dropbox-dist/dropbox-lnx.x86_64-29.4.20/library.zip /usr/local/bin/dropbox-lnx.x86_64-29.4.20/
$ rm -rf .dropbox-dist/
```

**Comment by vince** [comment]
This error still occurs in the latest dropbox

    zipimport.ZipImportError: not a Zip file: '/usr/local/bin/dropbox-lnx.x86_64-30.4.22/library.zip'

Happy to close this issue since there's a workaround, but would prefer to keep it open until it's truly resolved.

**Comment by jam7** [comment]
Having the same problem at the first `dropbox start` command.

Their official tarball has this `library.zip` as a link to `dropbox` executable.  So, it is clearly not a zip file from the beginning.  I'm not sure what this means...  Why others can run it...  Anyway, this is just another error report.

**Comment by uberhacker** [comment]
@vince: See PR #1047 which resolves this issue.

**Comment by vince** [comment]
@uberhacker tried it out and it does not by itself fix dropbox. Dropbox now installs but none of the commands actually give you a working dropbox. It does show the process started but there's no prompt to login, nor is there instructions in help as to how to link it to your computer. Headless still works.

```
chronos@localhost / $ ps aux | grep dropbox
chronos  13678  0.5  2.1 2101252 85184 ?       Sl   Aug13   0:37 /home/chronos/user/.dropbox-dist/dropbox-lnx.x86_64-32.4.23/dropbox /newerversion
chronos  20325  0.0  0.0   6004  2088 pts/4    S+   01:04   0:00 grep --colour=auto dropbox
```

> chronos@localhost / $ dropbox running
> chronos@localhost / $ dropbox status
> Starting...

**Comment by uberhacker** [comment]
@vince: Has this issue been resolved on your end?

**Comment by vince** [comment]
@uberhacker I'm happy to close this but using this package still requires you to install the headless option from dropbox and start it manually that way. In my opinion this package should be removed as it does not work as expected.

**Comment by uberhacker** [comment]
Can you please elaborate what you mean by the headless option?  I know, initially, you need to set up your system to authorize Dropbox access.  Are you saying the service doesn't start automatically when the system starts?

**Comment by jam7** [comment]
I think the first problem is solved by #1047.  We can start dropboxd without problem we had before.  However, it doesn't work as we expected.  It starts but nothing.  It should ask username and password to login dropbox, but it won't happen by unknown reason.  Could you upload something to dropbox using this CLI?  I cannot.

**Comment by vince** [comment]
Sorry for the delay responding. @jam7 is exactly right, dropboxd starts but you can't use the client because there's no option to authenticate with dropbox. We should either remove the dropbox package, find a way to install the [headless version](https://www.dropbox.com/install-linux), or add an authenticate option to the script.

**Comment by uberhacker** [comment]
@vince: If this issue resolved, can we close?
