### ISSUE TITLE
aircrack_ng checksum mismatch

### ISSUE THREAD

**Issue by MD5HashBrowns** [skycocker/chromebrew#849]
aircrack_ng would not install, spit out a `checksum mismatch` error.

After changing the `source_sha256` from `ca715e687ef159d56e7524125cc46508d61598ad0c4b2f78748540f664fbb186` to `d93ac16aade5b4d37ab8cdf6ce4b855835096ccf83deb65ffdeff6d666eaff36`, aircrack_ng built fine.

```
chronos@localhost ~/Downloads $ sha256sum aircrack-ng-1.2-rc4.tar.gz 
d93ac16aade5b4d37ab8cdf6ce4b855835096ccf83deb65ffdeff6d666eaff36  aircrack-ng-1.2-rc4.tar.gz
```

**Comment by uberhacker** [comment]
@MD5HashBrowns: Thank you for reporting this issue.  PR #853 should fix it.

**Comment by jam7** [comment]
Close in favor of #853.
