### ISSUE TITLE
Join our new chromebrew slack user group!

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#857]
Signup [here](https://join.slack.com/t/chromebrew/signup?x=x-208886097602-262829259008).

If the above link doesn't work, please send an email to crewonslack@gmail.com to receive an invite.

**Comment by vince** [comment]
@uberhacker Not sure if this is on my end or not, but getting this notice when I try to sign up.

<img width="639" alt="screen shot 2017-07-10 at 1 16 47 pm" src="https://user-images.githubusercontent.com/15513/28030535-2a0f772a-6572-11e7-9539-c531beeca2e4.png">

**Comment by flyingP0tat0** [comment]
Same

**Comment by uberhacker** [comment]
Sorry for the trouble.  Please send your email to edreel@gmail.com and I'll send you an invite to join.

**Comment by Church-** [comment]
@uberhacker So I sent an email to the the crewonslack gmail, just waiting for a reply I guess.
