### ISSUE TITLE
Unable to install iojs

### ISSUE THREAD

**Issue by kresli** [skycocker/chromebrew#86]
Toshiba chromebook 2, intel, 4gb ram 
```
ojs-v2.2.1.tar.gz        100%[=======================================>]  19.53M  3.51MB/s   in 6.9s   

2015-07-10 23:33:06 (2.82 MB/s) - 'iojs-v2.2.1.tar.gz' saved [20477722/20477722]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
  File "./configure", line 404
    '''
      ^
SyntaxError: invalid syntax
iojs failed to install: `./configure` exited with 1
```

**Comment by lyxell** [comment]
Line 399-404:
```
    print '''io.js configure error: No acceptable C compiler found!

        Please make sure you have a C compiler installed on your system and/or
        consider adjusting the CC environment variable if you installed
        it in a non-standard prefix. 
        '''     
```
I will try to reproduce later. I have the same setup.

Could you post the output of `which python` and `python -v`?

**Comment by Tivoli** [comment]
@kresli This should have been fixed with the last merge, can you try again?

**Comment by skycocker** [comment]
@kresli can we close this?

**Comment by lyxell** [comment]
This problem occurs when /usr/env python is not version 2.7, io.js (as well as node.js) expects version 2.7 to be the default python.

**Comment by kresli** [comment]
@skycocker Sorry for late response. Unfortunately Im not using chromebrew anymore. Can't help further. Sorry

**Comment by skycocker** [comment]
@kresli no problem. 
@lyxell I'll try to find some time to alter the io.js install script to set the default python to the right one.

**Comment by Tivoli** [comment]
@skycocker it already has python27 as a requirement. The error that was posted was an issue with cc to gcc which was fixed.

**Comment by lyxell** [comment]
@Tivoli Why do you think that? "SyntaxError: invalid syntax" is clearly an error from the python interpreter.

**Comment by lyxell** [comment]
@Tivoli Ah, alright. Does "depends_on" ensure that "/bin/env python" is version 2.7?

**Comment by skycocker** [comment]
@Tivoli @lyxell yeah, this *default* python is the thing that I'm worrying about

**Comment by lyxell** [comment]
I guess
```ruby
  def self.build
    system "CC='gcc' python2.7 configure"
    system "make"
  end
```
would work on most (all?) systems.
