### ISSUE TITLE
Failed to build python27

### ISSUE THREAD

**Issue by c-yan** [skycocker/chromebrew#869]
When I run "crew install mercurial", I get build error of python27.
The error message indicates that zlib is missing.
So, I run "crew install zlibpkg" and run "crew install mercurial" again, I got a success.
Is there a error in dependency?

**Comment by uberhacker** [comment]
Hi @c-yan: Thank you for reporting this issue.  I just tried a `mercurial` install without the `zlibpkg` package and it installed fine.  Can you please provide your Chromebook specs along with the Chrome OS version?  If you don't know how to get your Chrome OS version, you can install the `lsb_release` package and provide the output of `lsb_release -a`.  Also, please provide the output of `uname -a`.
Thanks

**Comment by c-yan** [comment]
@uberhacker 
LSB Version: 1.4
Distributor ID: Chrome OS
Description: 9334.72.0 (Official Build) stable-channel veyron_minnie
Release: 9334.72.0
Codename: veyron_minnie-signed-mp-v4keys
Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:55:22 PDT 2017 armv7l ARMv7 Processor rev 1 (v7l) Rockchip (Device Tree) GNU/Linux

**Comment by uberhacker** [comment]
@c-yan: Thank you for the feedback.  @jam7: Do you notice the same issue on your armv7l system?  It compiled fine on my x86_64 without the zlibpkg package.  BTW, I added PR #870.

**Comment by jam7** [comment]
@uberhacker It depends on the situation I think.  I could compile it without zlibpkg, but setup.py refers zlib.h, so it's possible that zlib.h is required under some conditions.  I think adding zlibpkg as a part of dependencies is good and easy way to fix this problem.

**Comment by paulwratt** [comment]
I can confirm the OP failure to build Python (crew install vim) with the same error. The same solution works (crew install zlibpkg). 

NOTE: it is not the build of Python that fails, but one of the .py scripts that requires zlib that is "installed" (or compiled)

```
LSB Version:    1.4
Distributor ID: Chrome OS
Description:    9460.67.0 (Official Build) stable-channel veyron_speedy 
Release:        9460.67.0
Codename:       veyron_speedy-signed-mp-v3keys
Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jun 22 14:28:49 PDT 2017 armv7l ARMv7 Processor rev 1 (v7l) Rockchip (Device Tree) GNU/Linux
```

**Comment by flyingP0tat0** [comment]
@uberhacker You added zlib to mercurial, but if I get this correctly it is needed by python?

**Comment by uberhacker** [comment]
@flyingP0tat0: Yes, I think it probably makes more sense to put the dependency in with the python package rather than including the dependency in each package that requires the python script that references zlib.h.  With that said, should all the python packages include this dependency as well?  (ie. python, python27 and python3)

**Comment by flyingP0tat0** [comment]
@uberhacker That needs to be tested. I will do that right now.

**Comment by flyingP0tat0** [comment]
Done.

**Comment by thedamian** [comment]
Fixed with PR https://github.com/skycocker/chromebrew/pull/883
