### ISSUE TITLE
Add '-y' and/or '--yes' flag to 'crew upgrade'

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#878]
If there are several updates and these packages have dependencies which prompt, you could potentially end up with several prompts to finish the upgrade process.  It would be nice if there was a `-y` and/or `--yes` flag that would automate the process by assuming yes on each prompt.

**Comment by jam7** [comment]
FYI, `yes | crew upgrade` works great.

2017年7月11日(火) 9:26 Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
Awesome.  I added a FAQ page with this excellent tip.  See https://github.com/skycocker/chromebrew/wiki/FAQ.

**Comment by jam7** [comment]
Nice FAQ.  How about add recomended mandb configuration here also?

2017年7月11日(火) 13:06 Ed Reel <notifications@github.com>:

**Comment by uberhacker** [comment]
See https://github.com/skycocker/chromebrew/wiki/FAQ.  Please feel free to edit if you have something to add.
