### ISSUE TITLE
Using cURL instead of wget?

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#882]
How about using cURL instead of wget?
It would look better the way cURL displays the progress of the download, without all the connection information wget gives us (with appropriate cURL settings).
This is just a minor 'issue' with the way it looks, but I guess it is worth thinking about to switch...

**Comment by uberhacker** [comment]
The issue with curl is that it doesn't come out-of-the-box like wget.  We would have to install it first.

**Comment by flyingP0tat0** [comment]
@uberhacker Are you sure? If i remember correctly, I could use curl before I installed anything else.

**Comment by uberhacker** [comment]
I guess you are correct.  My bad.
```
$ which curl
/usr/local/bin/curl
$ crew remove curl
Curl removed!
$ which curl
/usr/bin/curl
```

**Comment by jam7** [comment]
Is there any objection?  There is new PR to use chromebrew on OnHub, #990.  It requires to use curl since OnHub doesn't own wget.  If there is no objection, I'll merge this PR soon.

**Comment by uberhacker** [comment]
Aren't there pending changes requested on #990?

**Comment by jam7** [comment]
close in favor of #990.
