### ISSUE TITLE
How to remove chromebrew

### ISSUE THREAD

**Issue by stephentcannon** [skycocker/chromebrew#9]
Can we get instructions on removing chromebrew?

**Comment by gudmundsonsc** [comment]
crew list installed | sed $'s,\x1b\\[[0-9;]*[a-zA-Z],,g' | grep -vi ruby | xargs -l crew remove

**Comment by pvp-god70254** [comment]
Try a factor reset if none work try a powerwash/factor reset, but make sure all your important files an in your drive or any type of removable storage before it and you might need to backup Linux if you have it setup. This does not affect dev mode for those who don't know.
