### ISSUE TITLE
subversion not installing

### ISSUE THREAD

**Issue by paulwratt** [skycocker/chromebrew#918]
`crew install subversion` comes back with:

> subversion: Subversion is an open source version control system.
https://subversion.apache.org/
version 1.9.5
No precompiled binary available for your platform, downloading source...
--2017-07-20 14:11:30--  http://apache.mirrors.ionfish.org/subversion/subversion-1.9.5.tar.gz
Resolving apache.mirrors.ionfish.org... 38.126.148.232
Connecting to apache.mirrors.ionfish.org|38.126.148.232|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-07-20 14:11:31 ERROR 404: Not Found.
Checksum mismatch. :/ Try again.

correct versions (according to url) is 1.9.6 (or 1.8.18) 

Cheers
paul

**Comment by uberhacker** [comment]
@paulwratt: You can always use git instead.  Sorry, I couldn't resist making that comment. :)  I'll see if I can correct the sha256 checksum and submit a pull request to fix.
