### ISSUE TITLE
Should we remove python.rb?

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#923]
We have following python related packages.

 - python.rb
   - python 3.3.2 without pip, binary, will be installed as python3, i686 and x86_64 binary package create a symbolic link from python to python3 also.
 - python3.rb
   - python 3.6.0 with pip, source, will be installed as python3
 - python27.rb
   - python 2.7.13 with pip, source, will be installed as python

Should we remove python.rb?  It is not updateded.  The symbolic link confuse us...

Please let me know if you have opposite opinion.  Thanks.

**Comment by flyingP0tat0** [comment]
Maybe make python a fake package to install python3 or python27?

**Comment by uberhacker** [comment]
How about this idea?  Get rid of both python3 and python27 packages and create a single package that prompts which python version you would like installed.  The challenge would be how to handle multiple versions.  Do we want to provide the ability to default the `/usr/local/bin/python` executable to the preferred version or have `/usr/local/bin/python2` and `/usr/local/bin/python3` executables?

**Comment by kirbyfan64** [comment]
FWIW Python 2 is gradually nearing EOL. It might be worth it to make 3 the default, and have Python 2 be installed as `python2` (e.g. no `python`).

**Comment by uberhacker** [comment]
@kirbyfan64: There are still several packages that rely on python27 specifically as a dependency but we could change those package to execute python2 instead of python.

**Comment by jam7** [comment]
I think we need to decide which python is executed as /usr/local/bin/python.  Otherwise, some programs may fails because there is no compatibility between python2 and python3.

Then question is which one we need to choose.

Python 2 has been nearing EOL from ten years ago.  It is still alive...  It's the source of headache.  ;)

I am thinking it is better to have python2 as python.  Because it won't break anything.  Many programs assume python is python2.  But we can challenge...  It's possible as @uberhacker said.  Do many of us want to challenge it?

**Comment by uberhacker** [comment]
We probably shouldn't assume that python means python2.  I think it would be a good idea to change all the packages that depend on python27 to use python2 instead of python during installation, at least in the package itself.  This assures the correct version is executed without any assumptions.

**Comment by jam7** [comment]
Please submit PR to fix these issues.  I volunteered as a collaborator recently.  So, I can merge other's PR after reviews.  I cannot merge myself PR, though.  :)

**Comment by thedamian** [comment]
MERGED
