### ISSUE TITLE
checksum not matched for vim 

### ISSUE THREAD

**Issue by kresli** [skycocker/chromebrew#93]
`Checksum mismatch :/ try again`

**Comment by jwhipp** [comment]
Did this fail due to an invalid URL?

**Comment by skycocker** [comment]
@kresli please run `crew update` and try again. If the problem persists, please paste the whole console output (more than just 1 line).

**Comment by Camarde** [comment]
I get the same problem. I believe the problem isn't with the VIM-package, but with the ruby package.

see output when downloading ruby. I get the same error when trying to install ruby or installoing vim:

```
Found ruby, version 2.0.0p247-chromeos1
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-10-12 22:41:59--  https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1
Resolving www.dropbox.com... 108.160.172.206, 108.160.172.238
Connecting to www.dropbox.com|108.160.172.206|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/2Ifox9CVUPE0f8xaDWqjRdVFLui5QZWFanZ2ttNPFQ4D4qsAf7BgXrPbMNEGU5oK?dl=1 [following]
--2015-10-12 22:42:00--  https://dl.dropboxusercontent.com/content_link/2Ifox9CVUPE0f8xaDWqjRdVFLui5QZWFanZ2ttNPFQ4D4qsAf7BgXrPbMNEGU5oK?dl=1
Resolving dl.dropboxusercontent.com... 107.21.216.209, 54.243.102.38, 54.243.74.238, ...
Connecting to dl.dropboxusercontent.com|107.21.216.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28295655 (27M) [application/octet-stream]
--2015-10-12 22:42:01--  https://dl.dropboxusercontent.com/content_link/2Ifox9CVUPE0f8xaDWqjRdVFLui5QZWFanZ2ttNPFQ4D4qsAf7BgXrPbMNEGU5oK?dl=1
Reusing existing connection to dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 28295655 (27M) [application/octet-stream]
Saving to: 'ruby-2.0.0p247-chromeos-x86_64.tar.gz'

ruby-2.0.0p247-chromeos-x86_64.tar.gz 100%[========================================================================>]  26.98M  1.34MB/s   in 22s    

2015-10-12 22:42:25 (1.21 MB/s) - 'ruby-2.0.0p247-chromeos-x86_64.tar.gz' saved [28295655/28295655]

Checksum mismatch :/ try again
```

**Comment by thedamian** [comment]
This is the same problem as the JDK8 package. 

Here's how to fix it.

Your package (ruby.rb) file is out of date. I don't know how to update it (which command updates the package file itself) but it's easy to do manually.

Edit the ruby.rb file already on your computer that should be in somewhere like /usr/local/lib/crew/packages (or look for it) 

Now copy the content of the latest file (it's a simple file that just holds links to packages)
https://github.com/skycocker/chromebrew/blob/master/packages/ruby.rb

then ruby will be able to be installed or upgraded because those links work just fine.

(Notice in your output that if you go to the url where the dropbox link where the REAL ruby package is install that dropbox does a 404. that's how you can tell the problem is your ruby.rb file.

let us know if this fixed it.

**Comment by thedamian** [comment]
I suggest this issue be closed.

**Comment by Camarde** [comment]
Thanks! I will try to manually update my ruby package.

**Comment by skycocker** [comment]
Let us know if there are any more problems.

**Comment by thedogb** [comment]
i get same problem with vim again. 
when i run 'crew install vim' ,i returns error information as fellow:
Found vim, version 8.0
Following packages also need to be installed: 
glibc223 binutils gmp mpfr mpc isl cloog glibc gcc make linuxheaders pkgconfig buildessential readline zlibpkg perl libsigsegv diffutils ncursesw bz2 ncurses openssl python27 ruby 
Do you agree? [Y/n]

Proceeding...
Found glibc223, version 2.23
Package glibc223 already installed, skipping...
Found binutils, version 2.25-1
Package binutils already installed, skipping...
Found gmp, version 6.1.2
Package gmp already installed, skipping...
Found mpfr, version 3.1.5
Package mpfr already installed, skipping...
Found mpc, version 1.0.3
Package mpc already installed, skipping...
Found isl, version 0.14.1
Package isl already installed, skipping...
Found cloog, version 0.18.4
Package cloog already installed, skipping...
Found glibc, version 1.0
Package glibc already installed, skipping...
Found gcc, version 4.9.x
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.18
Package linuxheaders already installed, skipping...
Found pkgconfig, version 0.29.1
Package pkgconfig already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.3
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found perl, version 5.24.1
Package perl already installed, skipping...
Found libsigsegv, version 2.11
Package libsigsegv already installed, skipping...
Found diffutils, version 3.5
Package diffutils already installed, skipping...
Found ncursesw, version 6.0
Package ncursesw already installed, skipping...
Found bz2, version 1.4.17
Package bz2 already installed, skipping...
Found ncurses, version 6.0-1
Package ncurses already installed, skipping...
Found openssl, version 1.0.2k
Package openssl already installed, skipping...
Found python27, version 2.7.13
Package python27 already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Package ruby already installed, skipping...
Found vim, version 8.0
No precompiled binary available for your platform, downloading source...
--2017-04-26 08:22:31--  ftp://ftp.vim.org/pub/vim/unix/vim-8.0.tar.bz2
           => 'vim-8.0.tar.bz2'
Resolving ftp.vim.org... 145.220.21.40
Connecting to ftp.vim.org|145.220.21.40|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/vim/unix ... done.
==> SIZE vim-8.0.tar.bz2 ... 10866752
==> PASV ... done.    ==> RETR vim-8.0.tar.bz2 ... done.
Length: 10866752 (10M) (unauthoritative)

vim-8.0.tar.bz2                       100%[======================================================================>]  10.36M  63.9KB/s    in 1m 53s  

2017-04-26 08:24:33 (93.9 KB/s) - 'vim-8.0.tar.bz2' saved [10866752]

Checksum mismatch :/ try again


and i try running 'crew update' and it return 

From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
HEAD is now at 3282ab3 Merge pull request #570 from ntchambers/master
Package lists, crew, and library updated.
Checking for package updates...

Your software is up to date

then i run 'crew upgrade' , and it return 

Your software is already up to date.

and now i don't know what shall i do
