### ISSUE TITLE
emacs no info nodes

### ISSUE THREAD

**Issue by fkunze** [skycocker/chromebrew#94]
I love chromebrew!
the message "can't find the Info directory node is displayed in response to ^h i
Fritz Kunze
fkunze@gmail.com
version GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu)                              |
 of 2015-06-08 on localhost"

**Comment by thedamian** [comment]
I think you'll get an answer faster if you give us what you were doing, and what happened when you did.

**Comment by thedamian** [comment]
crew install emacs works perfectly.

Not working for you? 
Try crew update 
then crew install emacs or crew upgrade emacs.

It should work then.

**Comment by thedamian** [comment]
I suggest closing this issue.
