### ISSUE TITLE
Can't install nodejs

### ISSUE THREAD

**Issue by samuelwight** [skycocker/chromebrew#96]
I was able to install it a few days ago, but I had to remove it. I tried reinstalling it, but I get an error:

ln: failed to create symbolic link ‘/usr/local/bin/cc’: File exists
nodejs failed to install: `sudo ln -s /usr/local/bin/gcc /usr/local/bin/cc` exited with 1

Help please!

**Comment by skycocker** [comment]
Please paste the output of 
`ls -lh /usr/local/bin/gcc` 
`ls -lh /usr/local` 
`ls -lh /usr/local/bin/cc`

**Comment by skycocker** [comment]
@samuelwight is the issue still alive? Please run `crew update` and try again, then let me know.

**Comment by samuelwight** [comment]
@skycocker I found out the problem. I had installed the v package from npm. When I uninstalled node, it left some stuff behind. I powerwashed my Chromebook and everything works fine now. Thanks for the help!

**Comment by skycocker** [comment]
@samuelwight thanks for letting know! :)
