### ISSUE TITLE
Close some issues!

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#964]
Some issues are fixed and other not activ any more. I think they could need some cleanup.

- [ ]  #214
- [x]  #479 
- [ ]  #577 
- [x]  #622
- [x]  #790 
- [x]  #797 
- [x]  #849
- [ ]  #857 (maybe move to README)

**Comment by jam7** [comment]
#214 and #577 are not solved, so I think leaving them as is is not bad idea.
#857 is also not solved at the moment.

**Comment by flyingP0tat0** [comment]
Sure about #214?

**Comment by jam7** [comment]
It's difficult question, but no for me.  It's fine other collaborator close it, though.  :)

**Comment by flyingP0tat0** [comment]
Alright. Great, thank you!
