### ISSUE TITLE
SystemStackError

### ISSUE THREAD

**Issue by camphi** [skycocker/chromebrew#965]
Edit: corrected markdown...

Hello!

I tried a few things but in the end here is what happen.

========================

crew install vim
vim: Vim is a highly configurable text editor built to make creating and changing any kind of text very efficient.
http://www.vim.org/
version 8.0-1
/usr/local/lib/ruby/2.4.0/rubygems.rb:1241:in `find_unresolved_default_spec': stack level too deep (SystemStackError)
        from /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:44:in `require'
        from /usr/local/bin/crew:144:in `set_package'
        from /usr/local/bin/crew:160:in `block in search'
        from /usr/local/lib/ruby/2.4.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib/ruby/2.4.0/find.rb:48:in `catch'
        from /usr/local/lib/ruby/2.4.0/find.rb:48:in `block in find'
        from /usr/local/lib/ruby/2.4.0/find.rb:43:in `each'
        from /usr/local/lib/ruby/2.4.0/find.rb:43:in `find'
         ... 12667 levels...
        from /usr/local/bin/crew:533:in `expand_dependencies'
        from /usr/local/bin/crew:539:in `resolve_dependencies'
        from /usr/local/bin/crew:487:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:766:in `<main>'

=============

also "crew install buildessential" ended with pkgconfig not installing:

=============
....
checking if arpa/nameser_compat.h is needed... configure: error: could not compile test program either way
configure: error: ./configure failed for glib
pkgconfig failed to install: `./configure --with-internal-glib --with-pc-path=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig` exited with 1

=============

I use an Asus c201 armv7I

Can I do something else to help you resolve this?

Thank you

**Comment by jam7** [comment]
which os are you using? chrome os 59, 60 or..?

I'll check it tonight, but i have no idea atm.

**Comment by camphi** [comment]
It's a chrome os 59.0.3071.134

Thank you

**Comment by flyingP0tat0** [comment]
This could be related to #956.
Please try to manually modify `/usr/local/lib/crew/packages/perl.rb` and remove the line that says:
```ruby
depends_on 'curl'
```

Then try again.

**Comment by jam7** [comment]
Regarding to vim, @flyingP0tat0 suggestion should work.

Regarding to `pkgconfig`, I'm not sure since it works fine on my c101 flip, armv7l and ChromeOS 59.0.3071.91.
```
$ crew install buildessential
...
checking for if_nametoindex... yes
checking for if_indextoname... yes
checking if arpa/nameser_compat.h is needed... no
checking for res_query... in -lresolv
checking for socket... yes
...
```

**Comment by camphi** [comment]
commented `depends_on 'curl'` and tried again `crew install vim`

```
In file included from ../test/hanoi.c:48:0:
/usr/local/include/math.h:31:30: fatal error: bits/math-vector.h: No such file or directory
 #include <bits/math-vector.h>
                              ^
compilation terminated.
make[1]: *** [../obj_s/hanoi.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/tmp/crew/ncurses-6.0.tar.gz.dir/ncurses-6.0/test'
make: *** [all] Error 2
ncursesw failed to install: `make -j4` exited with 2
```

tried https://github.com/skycocker/chromebrew/issues/562 but got:
```
crew install glibc223
(i) glibc223: GNU C Library
https://www.gnu.org/software/libc/
version 2.23-2
Package glibc223 already installed, skipping...
```

ty

**Comment by jam7** [comment]
I think you corrupted your crew environment.  You can try:
```
$ crew remove glibc223
$ crew isntall glibc223
```
But, I recommend you to remove all and install chromebrew from scratch again.

**Comment by camphi** [comment]
how do you remove all?
I'll try this tonight
ty

**Comment by jam7** [comment]
you can do it by removing everything under /usr/local like `rm -rf /usr/local/*` if you don't have anything important there.  You can try #877 instead.  Anyway, chromebrew install files under `/usr/local`, so you can check there to see whether something left there.

**Comment by camphi** [comment]
Thank you!

so it was related to https://github.com/skycocker/chromebrew/issues/956

and after clearing my install everything is working. Sorry for the trouble!
