### ISSUE TITLE
jdk8 without javac

### ISSUE THREAD

**Issue by bpstrngr** [skycocker/chromebrew#966]
Hi I've been ignoring it for a while but now 
I would need javac and it's missing from the 
package recently. It used to be included 
some months ago and it worked perfectly.

**Comment by flyingP0tat0** [comment]
Are you running on ARM?

**Comment by bpstrngr** [comment]
It's an arnoldthebat-built x86_64 chromium os. 
I've been sticking to his builds for a year and only 
lately it's been acting strange but it's as if only I had 
those problems. I mean nano doesn't install either 
for some weird missing "lib" excuses and than there's this.

**Comment by flyingP0tat0** [comment]
Have you added `/usr/local/lib` to `LD_LIBRARY_PATH`?
If not do that, for example by adding the following to `~/.bashrc`:
```shell
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```
One `source ~/.bashrc` later and you should have some lib problems resolved.
But for the java stuff I have no idea...

**Comment by bpstrngr** [comment]
That's a good hint yes, I even tried it 
but it's probably something else, not 
even libs, I just can't elaborate, 
here's the point of failure:
```
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -DLOCALEDIR=\"/usr/local/share/locale\" -DSYSCONFDIR=\"/usr/local/etc\" -I../lib -I../lib -I/usr/local/include/ncurses  -g -O2 -Wall -MT cut.o -MD -MP -MF .deps/cut.Tpo -c -o cut.o cut.c
color.c: In function ‘color_update’:
color.c:230:2: error: unknown type name ‘magic_t’
  magic_t cookie = NULL;
[ etc... ]
make[1]: Leaving directory '/usr/local/tmp/crew/nano-2.8.4.tar.xz.dir/nano-2.8.4'
make: *** [Makefile:1470: all] Error 2
nano failed to install: `make -j2` exited with 2
```

I couldn't be more off-topic though, 
so i'm only wondering if anyone else 
has this issue with jdk8. 
I'd paste my crew installation log as an only clue, if I may: 
```
chronos@localhost / $ crew install jdk8
jdk8: The JDK is a development environment for building applications, applets, and components using the Java programming language.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
version 8u131
No precompiled binary available for your platform, downloading source...
--2017-07-29 17:43:55--  http://javadl.oracle.com/webapps/download/AutoDL?BundleId=220305_d54c1d3a095b4ff2b6607d096fa80163
Resolving javadl.oracle.com... 137.254.120.23
Connecting to javadl.oracle.com|137.254.120.23|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz&BHost=javadl.sun.com&File=jre-8u131-linux-x64.tar.gz&AuthParam=1501344238_4e64b9b58fe652bc0534abc0a9fb8eea&ext=.gz [following]
--2017-07-29 17:43:56--  http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz&BHost=javadl.sun.com&File=jre-8u131-linux-x64.tar.gz&AuthParam=1501344238_4e64b9b58fe652bc0534abc0a9fb8eea&ext=.gz
Resolving sdlc-esd.oracle.com... 104.83.4.11, 104.83.4.26
Connecting to sdlc-esd.oracle.com|104.83.4.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75920010 (72M) [application/x-gzip]
Saving to: 'AutoDL'

AutoDL                              100%[================================================================>]  72.40M  2.40MB/s    in 30s     

2017-07-29 17:44:26 (2.43 MB/s) - 'AutoDL' saved [75920010/75920010]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Preconfiguring package...
Installing...
Jdk8 installed!
chronos@localhost / $ which java
/usr/local/bin/java
chronos@localhost / $ which javac
which: no javac in (/usr/local/bin:/usr/bin:/bin:/opt/bin)
```

**Comment by flyingP0tat0** [comment]
Nothing gets compiled because it is a binary package. You can look it up in the ruby file for jdk8.

**Comment by jam7** [comment]
Regarding to `nano`, you need to install `filecmd` before the installation of `nano`.  `nano` tries to use `magic_t` defined in `magic.h` if it finds `libmagic`.  Chromium OS has `libmagic` without `magic.h`

Regarding to `javac`, I don't know whether we used to have it or not.  I've installed `jdk8` on real x86_64 chromebook, but no `javac` is installed.  This chromebook is in beta channel, so Chrome OS is 60 though.

**Comment by bpstrngr** [comment]
Thanks for the nano insight, i now got that through. 
´javac´ we sure did have, in the time of #568 I did use it. 
It actually is very suspicious now that you mention, that version 
60 introduced some changes that puzzle me the 1-2 months...
