### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by jrc2139** [skycocker/chromebrew#967]
first off,  this is a great project and thank you for creating it!

Running ChromiumOS 62.0.3166.0 on a Dell Chromebook 3120 (candy)

i'm having issues installing python3 & vim with the same error being thrown:

```shell
usr/local/lib64/ruby/2.4.0/rubygems.rb:1241:in `find_unresolved_default_spec': stack level too deep (SystemStackError)
        from /usr/local/lib64/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:44:in `require'
        from /usr/local/bin/crew:144:in `set_package'
        from /usr/local/bin/crew:160:in `block in search'
        from /usr/local/lib64/ruby/2.4.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/2.4.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/2.4.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/2.4.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/2.4.0/find.rb:43:in `find'
         ... 12667 levels...
        from /usr/local/bin/crew:533:in `expand_dependencies'
        from /usr/local/bin/crew:539:in `resolve_dependencies'
        from /usr/local/bin/crew:487:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:766:in `<main>'
```

after some google searches, i read that this was an issue with ruby2.4, but that it was resolved long ago!

any help much appreciated!

**Comment by flyingP0tat0** [comment]
The problem is known and an PR under way (#957).
Basically, we currently have `perl` depending on `curl`, depending on `perl`, which results in a circle and ruby hangs up.

For now, please edit `/usr/local/lib/chromebrew/packages/perl.rb` and delete the line that says:
```ruby
depends_on 'curl'
```

Then it should work.

**Comment by jrc2139** [comment]
awesome thanks!
