### ISSUE TITLE
Various installs fail due to un-resolvable url

### ISSUE THREAD

**Issue by jwhipp** [skycocker/chromebrew#97]
--2015-08-23 23:13:33--  http://softlayer-dal.dl.sourceforge.net/project/zsh/zsh/5.0.7/zsh-5.0.7.tar.gz
Resolving softlayer-dal.dl.sourceforge.net... failed: Unknown host.
wget: unable to resolve host address 'softlayer-dal.dl.sourceforge.net'
Checksum mismatch :/ try again

I was able to install htop right before I tried ZSH.  I'm guessing a bad URL in the recipe.

**Comment by skycocker** [comment]
Zsh should now work fine. Please open new issues if you find something else not working. Thanks! :)
