### ISSUE TITLE
crew install tmux failed

### ISSUE THREAD

**Issue by mjc0608** [skycocker/chromebrew#972]
the error is "stack level too deep" in "find_unresolved_default_spec"

**Comment by flyingP0tat0** [comment]
The same as in #967.

Please edit `/usr/local/lib/chromebrew/packages/perl.rb` and delete the line that says:
```ruby
depends_on 'curl'
```

Then it should work.

**Comment by mjc0608** [comment]
thx a lot, this solution helps. However, tmux installation still fails due to a configure error, it said something like "/lib/cpp fails sanity check".

**Comment by flyingP0tat0** [comment]
Thatis strange, as `linuxheaders` should be installed after installation of crew itself.
@jam7

**Comment by jam7** [comment]
@flyingP0tat0 Nope.  Users need to install `buildessential` to install linuxheaders.

**Comment by flyingP0tat0** [comment]
@jam7 Ah, ok.

**Comment by jam7** [comment]
Close in favor of #957.  We can discuss about `buildessential` in #952.
