### ISSUE TITLE
nano refresh loop

### ISSUE THREAD

**Issue by flywebguy** [skycocker/chromebrew#992]
Immediately after installing nano in Chromebrew I tried to open a test project's index.html file and got this: https://photos.app.goo.gl/PsrlFhPqVwsCKomF3

This is on a Samsung Chromebook Plus on beta version 60.0.3112.80

**Comment by jam7** [comment]
@flyingP0tat0 do you have this problem?  I'm having the same issue on armv7l Chrome OS 59.

As a remedy, it is possible to avoid this problem by running `nano` inside `screen`.  I tested `nano` inside `screen`, therefore I didn't notice this problem.

**Comment by flywebguy** [comment]
@jam7 you're awesome. Thanks for that quick fix. 

It'd be nice if screen wasn't required, but great find nonetheless!

**Comment by flyingP0tat0** [comment]
@jam7 @flywebguy Yes I am having the same issue.
Of course, the `screen` fix won't stay forever, we need to find a solution.

**Comment by jam7** [comment]
This problem still happens on the latest 2.8.7.

**Comment by lyxell** [comment]
Do we know more about the source of this bug?

**Comment by Kriskras99** [comment]
It was solved for me by installing the `readline` package, the binary was probably build with the `readline` package installed so it was automatically linked. I will open a pull request to fix the dependency.

**Comment by qualityshepherd** [comment]
This is a problem on my chromebook asus c201 (rockchip). Installing `readline` didn't fix the issue.

**Comment by cstrouse** [comment]
I have `readline` installed and can't reproduce this on the Samsung Chromebook Plus running stable channel.

**Comment by hursey013** [comment]
This is still an issue, happening on Asus C302, ChromeOS Version 63.0.3239.140 (Official Build) (64-bit).
