### ISSUE TITLE
Implementing Tests

### ISSUE THREAD

**Issue by yancouto** [skycocker/chromebrew#997]
This issue is to discuss whether tests should be implemented.

- Should we create tests?
- Which kind of tests? (In #963 I implemented a test to check if there is a dependency cycle)
- Should some kind of testing framework be used?
- Could they be automated? (Travis?)

**Comment by jam7** [comment]
In my opinion

- yes, definitely
- there are two.  to check the correctness of .rb file including dependencies and to check the correctness of compile/install
- we have check function to self.check the correctness of compile/install.  see go.rb, perl.rb, python27.br, etc.  we didn't have any for .rb file correctness.
- yes.  I'd like to try some soon.

**Comment by jam7** [comment]
I have a question about automated test execution environment for chromebrew.  Is there any good tools we can use free...
 - to check correctness of .rb files like #963?
 - to check and build pre-compiled binaries for at least x86_64?
 - to check and build pre-compiled binaries for other architecture?
Thanks.

**Comment by yancouto** [comment]
In Travis it is possible to automatically run tests like #963.

Building stuff from source is possible, but I'm not sure if is possible to do in those specific architectures, I've only used it in small projects.

**Comment by jam7** [comment]
I see.  Just a test with several scripts should be easy.  Maybe we can try some of them.  Then, we may try building stuff later.  I'd like to try some in near future definitely.

**Comment by uberhacker** [comment]
@jam7: I found a few executables available in our very own package system that may be helpful.  The `fslint` package will assist in identifying issues with files.  I ran it recently on my system and found this section interesting:
```
-------------------------Non Stripped executables
-rwxr-xr-x 1 chronos chronos    14104 Aug  2 20:58 /usr/local/bin/checkgid
-rwxr-xr-x 1 chronos chronos    23624 Aug  2 20:58 /usr/local/bin/httxt2dbm
-rwxr-xr-x 1 chronos chronos    27464 Aug  2 20:58 /usr/local/bin/htdigest
-rwxr-xr-x 1 chronos chronos    27712 Aug  2 20:58 /usr/local/bin/logresolve
-rwxr-xr-x 1 chronos chronos    29464 Aug  2 20:58 /usr/local/bin/rotatelogs
-rwxr-xr-x 1 chronos chronos    36184 Aug  2 20:58 /usr/local/bin/htdbm
-rwxr-xr-x 1 chronos chronos    39368 Aug  2 20:58 /usr/local/bin/htpasswd
-rwxr-xr-x 1 chronos chronos    54904 Aug  2 20:58 /usr/local/bin/htcacheclean
-rwxr-xr-x 1 chronos chronos    67112 Aug 26 00:32 /usr/local/bin/autossh
-rwxr-xr-x 1 chronos chronos    90656 Aug  2 20:58 /usr/local/bin/ab
-rwxr-xr-x 1 chronos chronos   101320 Aug 23 13:39 /usr/local/bin/glib-compile-resources
-rwxr-xr-x 1 chronos chronos   963824 Aug 11 23:44 /usr/local/bin/ctags
-rwxr-xr-x 1 chronos chronos  2514096 Aug  2 20:58 /usr/local/bin/httpd

**Comment by JL2210** [comment]
I'm fairly sure that this can be closed for now. If need be, we can reopen it later.

**Comment by uberhacker** [comment]
Why don't you write up a wiki article to explain the testing procedure?  After that, we can link here and close this issue.

**Comment by JL2210** [comment]
I don't think that tests would be appropriate for the average user. I'll go ahead, though.

**Comment by JL2210** [comment]
OK. See Testing-procedure.

**Comment by uberhacker** [comment]
See https://github.com/skycocker/chromebrew/wiki/Testing-procedure.
